### ISSUE TITLE
arm32_v5 boot errors after 87383e408d41623ada41e2bbc371b037fa29e894

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1001]
@nathanchance reported: https://bugs.llvm.org/show_bug.cgi?id=45632

Just filing a bug here to help track.

**Comment by nathanchance** [comment]
@MaskRay pushed https://reviews.llvm.org/D79229.

I am not sure if this is something that should be added to LLVM 10.0.1 since it was only exposed with an `ld.lld` change but I'll leave that up to @MaskRay.

**Comment by nickdesaulniers** [comment]
The change in default page size is not in llvm 10 (cc @tstellar ), or I would consider it too risky a change for a point release.

Big thanks @MaskRay .

@nathanchance we should revert https://github.com/ClangBuiltLinux/continuous-integration/commit/4db0c1e19f8dc7ee6f9ae8ae50d20930ba689c39

**Comment by nathanchance** [comment]
@nickdesaulniers I'll make a note to do it once D79229 is available through apt.llvm.org.

**Comment by MaskRay** [comment]
Cherry picked https://reviews.llvm.org/D79229 to https://github.com/llvm/llvm-project/commit/d4d4c6bf834142326301a743d2939e868d9f0f0f

`llvm-objcopy -O binary` was somewhat broken for LLVM <= 9 (before https://reviews.llvm.org/D71035).
