### ISSUE TITLE
-Wframe-address in arch/x86/include/asm/thread_info.h

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#1003]
```
warning: calling '__builtin_frame_address' with a nonzero argument is unsafe
```
https://github.com/ClangBuiltLinux/linux/blob/50cc09c18985eacbbd666acfd7be2391394733f5/arch/x86/include/asm/thread_info.h#L190-L192

Also here:
https://github.com/ClangBuiltLinux/linux/blob/50cc09c18985eacbbd666acfd7be2391394733f5/include/linux/ftrace.h#L778

**Comment by nathanchance** [comment]
ef6000b4c6706cbb1787836442b5a74542b1809f

Someone is probably clobbering KBUILD_CFLAGS (i915.....)

**Comment by nathanchance** [comment]
Accepted: https://cgit.freedesktop.org/drm/drm-intel/commit/?id=9f4069b055d1508c833115df7493b6e0001e5c9b

**Comment by nickdesaulniers** [comment]
sorry, I didn't look to see that we already had an issue filed for this. 👎 😞

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9f4069b055d1508c833115df7493b6e0001e5c9b
