### ISSUE TITLE
-Wtautological-pointer-compare in drivers/usb/gadget/udc/s3c2410_udc.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1004]
Found by 0day in an obscure ARM configuration.

```
drivers/usb/gadget/udc/s3c2410_udc.c:255:11: warning: comparison of address of 'ep->queue' equal to a null pointer is always false [-Wtautological-pointer-compare]
        if (&ep->queue == NULL)
             ~~~~^~~~~    ~~~~
1 warning generated.
```

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20200423162923.10886-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch is in a testing branch: https://git.kernel.org/balbi/usb/c/634e903a38095e116d1c1037ef1579e8be9a3830

Tentatively marking as accepted.

**Comment by nickdesaulniers** [comment]
-next: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=7a0fbcf7c308920bc6116b3a5fb21c8cc5fec128
not yet in mainline

**Comment by nathanchance** [comment]
https://git.kernel.org/linus/7a0fbcf7c308920bc6116b3a5fb21c8cc5fec128
