### ISSUE TITLE
undefined reference to __aeabi_uldivmod in drivers/net/ethernet/freescale/dpaa2/fsl-dpaa2-eth.ko

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1012]
arm32 allmodconfig linux-next reported by kernelci
```
    ERROR: modpost: "__aeabi_uldivmod" [drivers/net/ethernet/freescale/dpaa2/fsl-dpaa2-eth.ko] undefined!
```
typically means that a helper function needs to be called rather than use the division operator for 64b inputs.

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20200428174221.2040849-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/netdev/net-next/c/88fb831f773e6c51ec528eacb524f00f518f7e54

**Comment by nathanchance** [comment]
Fixed in -next: https://git.kernel.org/next/linux-next/c/88fb831f773e6c51ec528eacb524f00f518f7e54
