### ISSUE TITLE
-Wunused-variable in drivers/spi/spi-amd.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1013]
arm32 allmodconfig linux-next reported by kernelci
```
    drivers/spi/spi-amd.c:171:17: warning: unused variable 'opcode' [-Wunused-variable]
```

**Comment by nathanchance** [comment]
Looks like a patch was sent and picked up already: https://git.kernel.org/broonie/spi/c/68d047cb0a20f612506c6cf3a98e3600a7d4371f

**Comment by nathanchance** [comment]
https://git.kernel.org/next/linux-next/c/68d047cb0a20f612506c6cf3a98e3600a7d4371f
