### ISSUE TITLE
undefined reference to `__compiletime_assert_162` in mm/madvise.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1015]
https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/324177899
```
s390x-linux-gnu-ld: mm/madvise.o: in function `__se_compat_sys_process_madvise':
/travis/linux-next/mm/madvise.c:1314: undefined reference to `__compiletime_assert_162'
s390x-linux-gnu-ld: /travis/linux-next/mm/madvise.c:1314: undefined reference to `__compiletime_assert_164'
```
so `__se_compat_sys_process_madvise` or one of the functions inlined into it has a `BUILD_BUG` that's failing.  Commenting it out is the easiest way of bisecting/finding these.  Looks like this just started failing in the past 24hrs.  That source file should be target agnostic.

**Comment by nathanchance** [comment]
Reported: https://lore.kernel.org/lkml/20200428190459.GA2299615@ubuntu-s3-xlarge-x86/

**Comment by nathanchance** [comment]
Note, this is not a clang issue, my report was done with GCC for that reason.

**Comment by nickdesaulniers** [comment]
is it worthwhile for us to add/use a "bug in gcc, too" label, then close such issues?

**Comment by nathanchance** [comment]
That seems like a good idea. I don't know if we should close the issue until it is resolved but the GCC label should mean "not necessarily our problem".

**Comment by nathanchance** [comment]
Fixed in latest -next.
