### ISSUE TITLE
-Winteger-overflow in drivers/gpu/drm/amd/amdgpu/amdgpu_device.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1017]
```
drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:4160:53: warning: overflow in expression; result is -294967296 with type 'long' [-Winteger-overflow]
                expires = ktime_get_mono_fast_ns() + NSEC_PER_SEC * 4L;
                                                                  ^
1 warning generated.
```

Patch submitted: https://lore.kernel.org/lkml/20200502031141.2732221-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
@arndb sent a patch for this too, shortly after you did.

**Comment by nathanchance** [comment]
Patch accepted: https://cgit.freedesktop.org/~agd5f/linux/commit/?id=ee94b6c318d6518092617800a27e7481390bed82

**Comment by nathanchance** [comment]
https://git.kernel.org/next/linux-next/c/54b7feb93fc33c48619472d8b7fce41cc5acafc9
