### ISSUE TITLE
Include (a subset of) libelf with the kernel

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#1019]
Instead of finding libelf on host system like this:
https://github.com/ClangBuiltLinux/linux/blob/0e698dfa282211e414076f9dc7e83c1c288314fd/Makefile#L1018
we could include (a subset of) libelf with the kernel. This will allow `UNWINDER_ORC` to be enabled regardless of the availability of libelf on the host system. Right now it's disabled even if libelf is available unless clang is built with `CLANG_DEFAULT_LINKER=lld`: https://github.com/ClangBuiltLinux/linux/issues/479#issuecomment-492460731.

libelf comes from [elfutils](https://sourceware.org/elfutils/) which is a big project and has certain incompatibilities with clang (e.g. using nested functions, a gnu-specific extension not supported by clang). So my suggestion is to extract only the necessary functions from libelf and bundle it with the kernel. The libraries of elfutils project are dual licensed under GPLv2+/LGPLv3+.

**Comment by E5ten** [comment]
One could also use a different, more portable libelf implementation to make it easier to port the subset to the kernel, there's a libelf version that has been dead forever that works, or one present in elftoolchain.

**Comment by E5ten** [comment]
I guess a useful start would be checking what functions from libelf are needed in the kernel.

**Comment by 12101111** [comment]
There is another implement of libelf from BSD: 
https://sourceforge.net/p/elftoolchain/wiki/Home/
https://wiki.freebsd.org/LibElf
It don't have GNU extensions and works fine when compiling Linux with clang.
However, this project uses BSD make, so the Makefile needs to be rewritten to GNU style.

**Comment by E5ten** [comment]
https://fossies.org/linux/misc/old/libelf-0.8.13.tar.gz This is the dead libelf I was referring to, I think it's GPL2 or LGPL2? So licensing-wise probably easier to integrate than the elftoolchain version? And it works with clang unlike the elfutils version. So maybe the relevant subset could be pulled from this, and then the newer libelf features the kernel uses that it doesn't support like `ELF_C_READ_MMAP` could be added to it? It would also be convenient because there wouldn't be any need to worry about merging upstream changes because it gets no development.

**Comment by E5ten** [comment]
elftoolchain will stop working with kernel 5.8, because the kernel started using gelf_getsymshndx(), with a 2nd parameter that is NULL (it is sometimes set to non-NULL if a condition is true), and elfutils' libelf works with a NULL 2nd parameter, but elftoolchain's libelf does not, so for it to continue working, elftoolchain's gelf_getsymshndx() needs to be changed to support NULL as the 2nd parameter.

**Comment by E5ten** [comment]
> elftoolchain will stop working with kernel 5.8, because the kernel started using gelf_getsymshndx(), with a 2nd parameter that is NULL (it is sometimes set to non-NULL if a condition is true), and elfutils' libelf works with a NULL 2nd parameter, but elftoolchain's libelf does not, so for it to continue working, elftoolchain's gelf_getsymshndx() needs to be changed to support NULL as the 2nd parameter.

This has been fixed upstream

**Comment by staalmannen** [comment]
Personally, I think it would make more sense to merge elftoolchain with LLVM. It would be mutually beneficial where elftoolchain provides missing components (like libelf) and redundant stuff (like binutils utilities replacements) could be merged.

**Comment by emaste** [comment]
I maintain ELF Tool Chain in FreeBSD and am a committer to the upstream project; I am not sure if it's feasible to merge the project under the LLVM umbrella but I'm happy to help support this effort.

**Comment by staalmannen** [comment]
> I maintain ELF Tool Chain in FreeBSD and am a committer to the upstream project; I am not sure if it's feasible to merge the project under the LLVM umbrella but I'm happy to help support this effort.

That would be awesome!
To toy with the idea I just did a rough import of elftoolchain svn trunk into the llvm-project tree :
https://github.com/staalmannen/llvm-project (branch main)

At the time of this writing no changes to the code has been made, so the bmake files remain. The first TODO is thus to replace bmake files with cmake and integrate it in the llvm build system.

General overview of the rough import:
elftoolchain libraries + library-related tests in llvm-project/elflibs
non-redundant elftoolchain tools in llvm-project/llvm/tools
redundant tools (ar, nm, addr2line, ...) are not imported.
elftoolchain tool tests in llvm-project/llvm/test/tools

The idea was to put all binutils replacement tools together, and the tests for the tools from elftoolchain might also be good to run against the llvm tools.

**Comment by nathanchance** [comment]
#479 has a patch that works for allowing libelf to be found in a GNU-free environment even if clang has not been configured with `-DCLANG_DEFAULT_LINKER=lld`. At this point, I think the discussion is more about doing something that is not strictly related to ClangBuiltLinux so I am going to go ahead and close this for now. The [userspace](https://github.com/ClangBuiltLinux/userspace) repo might be a better place for this, or the LLVM issue tracker.
