### ISSUE TITLE
Section mismatch in reference from the function qcom_cpufreq_kryo_probe

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#102]
```sh
  MODPOST vmlinux.o
WARNING: vmlinux.o(.text+0x7995914): Section mismatch in reference from the function qcom_cpufreq_kryo_probe() to the function .init.text:qcom_cpufreq_kryo_get_msm_id()
The function qcom_cpufreq_kryo_probe() references
the function __init qcom_cpufreq_kryo_get_msm_id().
This is often because qcom_cpufreq_kryo_probe lacks a __init 
annotation or the annotation of qcom_cpufreq_kryo_get_msm_id is wrong.
```

Hey, that looks like a familiar driver.  similar to #101. `CONFIG_ARM_QCOM_CPUFREQ_KRYO`

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20180919060504.29281-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch v3: https://lore.kernel.org/lkml/20180920002220.16644-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted and pushed in 4.19-rc6: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d51aea13dd6753186a2bea7619029c460bdf0c4c
