### ISSUE TITLE
error: relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#1020]
When linking `.tmp_vmlinux.kallsyms1` multiple similar linker errors are produced:

```
ld.lld: error: arch/riscv/kernel/head.o:(.text+0x0): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax
ld.lld: error: arch/riscv/kernel/head.o:(.text+0x2): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax
ld.lld: error: arch/riscv/kernel/head.o:(.head.text+0x0): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax
ld.lld: error: arch/riscv/kernel/head.o:(.head.text+0xA): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax
ld.lld: error: arch/riscv/kernel/head.o:(.head.text+0x40): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax
ld.lld: error: arch/riscv/kernel/head.o:(.head.text+0x4A): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax
ld.lld: error: arch/riscv/kernel/head.o:(.head.text+0x88): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax
ld.lld: error: arch/riscv/kernel/head.o:(.init.text+0x0): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax
ld.lld: error: main.c:(.text+0x0): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax
ld.lld: error: version.c:(.text+0x0): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax
ld.lld: error: do_mounts.c:(.text+0x0): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax
ld.lld: error: do_mounts_initrd.c:(.text+0x0): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax
...
```

@MaskRay mentioned `R_RISCV_ALIGN` support here: https://github.com/ClangBuiltLinux/linux/issues/970#issuecomment-608128817

**Comment by nickdesaulniers** [comment]
marking this as a bug on the LLVM side, as we probably want support for that relocation in LLD.

**Comment by tpimh** [comment]
Currently my workaround is adding `-mno-relax` as the error message suggests: https://github.com/ClangBuiltLinux/continuous-integration/commit/15caf2717cab2f196c609a72564d6f57420c0f5a

**Comment by MaskRay** [comment]
Last Thursday I answered a question from another person interested in lld's RISC-V support.

> You are right that lld does not support R_RISCV_RELAX or R_RISCV_ALIGN.
I did some RISC-V work last year and made it mostly complete minus linker relaxations.
Linker relaxation for RISC-V is very hard due to its shrinkable sections.
>
> There are contributors posting patches (e.g. https://reviews.llvm.org/D77694 https://reviews.llvm.org/D79105) but the patches have major structural problems (which I mentioned in the review). They require major pass reordering in LLD.

The first is more promising. For the second patch, I appreciate that they spent efforts on this stuff but they largely underestimated the amount of work..

For now, -mno-relax with LLD :/

**Comment by nickdesaulniers** [comment]
@berolinux filed a bug upstream about this unsupported relocation type: https://llvm.org/pr44836

**Comment by nickdesaulniers** [comment]
@nathanchance has a patch in https://github.com/ClangBuiltLinux/linux/issues/1143#issuecomment-770125754.

Discussing with @nathanchance , we think we can:
1. send @nathanchance 's [patch](https://github.com/ClangBuiltLinux/linux/issues/1143#issuecomment-770125754).
2. keep CONFIG_EFI=n for CI (file a new issue for that)
3. disable CONFIG_JUMP_LABEL=n for CI (file a new issue for that)
Though now I hit #1023 ... hmm. So maybe we shouldn't send `-mno-relax` patches quite yet until we resolve the individual issues.

**Comment by nathanchance** [comment]
Someone sent a patch equivalent to mine above: https://lore.kernel.org/r/20210514205643.383422-1-raj.khem@gmail.com/

**Comment by nickdesaulniers** [comment]
that someone is @kraj, who has given talks on [Linux and LLVM](http://events17.linuxfoundation.org/sites/events/files/slides/Embedded-linux-with-clang.pdf) before. ;)

**Comment by kraj** [comment]
@nickdesaulniers yay :) I can boot 5.13-rc1 on Real hardware now with LLVM=1, so when my patch is accepted, we need to update https://www.kernel.org/doc/html/latest/kbuild/llvm.html#supported-architectures to reflect that RISCV can build with `LLVM=1` too

There still is a clang driver bug where it should have passed `-mno-relax` to GNU as but I had it neutered. @MaskRay has sent a patch to clang to fix it  https://reviews.llvm.org/D102535

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/riscv/linux.git/commit/?h=fixes&id=ec3a5cb61146c91f0f7dcec8b7e7157a4879a9ee has been accepted.

**Comment by nickdesaulniers** [comment]
v5.13-rc5: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ec3a5cb61146c91f0f7dcec8b7e7157a4879a9ee

**Comment by nickdesaulniers** [comment]
Also, @MaskRay implemented linker relaxation in lld-15
https://github.com/llvm/llvm-project/commit/6611d58f5bbcbec77262d392e2923e1d680f6985
https://github.com/llvm/llvm-project/commit/6b1d151fe3dc530195d8802f1ecc247c8235dd3a
And sent a patch to stop using `-mno-relax`:
https://lore.kernel.org/llvm/20220710071117.446112-1-maskray@google.com/
