### ISSUE TITLE
error: Unsupported relocation type in arch/riscv/kernel/head.S

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#1023]
```
arch/riscv/kernel/head.S:138:9: error: Unsupported relocation type
 .dword _end - _start
        ^
```
https://github.com/ClangBuiltLinux/linux/blob/335b139057ef79dbede01dea6e8c3f47c2b88802/arch/riscv/kernel/head.S#L38
[Travis CI](https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/330928526#L697)

**Comment by nickdesaulniers** [comment]
confirmed in [this comment](https://github.com/ClangBuiltLinux/linux/issues/1020#issuecomment-828689118)
```sh
$ ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- make LLVM=1 LLVM_IAS=1 -j72 arch/riscv/kernel/head.o
```

**Comment by nickdesaulniers** [comment]
Adding some logging to LLVM, it seems that the unsupported relocation kind is `R_RISCV_COPY` in `RISCVELFObjectWriter::getRelocType`, since there's no corresponding `llvm::RISCV::Fixups`.

**Comment by nickdesaulniers** [comment]
```asm
_start :.dword _end - _start
```

```sh
$ clang --target=riscv64-linux-gnu -c -mno-relax head.s
head.s:1:16: error: Unsupported relocation type
_start :.dword _end - _start
               ^
```
cc @topperc @jrtc27 @MaskRay

**Comment by nickdesaulniers** [comment]
https://llvm.org/pr50153

**Comment by jrtc27** [comment]
The problem is there's no R_RISCV_64_PCREL, only R_RISCV_32_PCREL, presumably because DWARF only needed the 32-bit form, so the FK_Data_8/FK_PCRel_8 IsPCRel case in RISCVELFObjectWriter::getRelocType has nothing it can use to represent that.

**Comment by jrtc27** [comment]
GNU as implements symbol subtraction with R_RISCV_ADD/R_RISCV_SUB, which is equivalent to R_RISCV_64_PCREL, except in the case the symbol may be preempted, where I believe the latter will give an error at link time whereas the former will succeed using the defined symbol?

**Comment by jrtc27** [comment]
Presumably FK_Data_8 given you say the Kind was value 4 (this is still MCFixupKind, not the ELF relocation, so that's not R_RISCV_COPY).

**Comment by nickdesaulniers** [comment]
> Presumably FK_Data_8 given you say the Kind was value 4 (this is still MCFixupKind, not the ELF relocation, so that's not R_RISCV_COPY).

Ah, yes, sorry. You're right.

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D103539 resolves this for me.

**Comment by nickdesaulniers** [comment]
big thanks @compnerd !
https://reviews.llvm.org/rGbbea64250f65480d787e1c5ff45c4de3ec2dcda8
