### ISSUE TITLE
CFI violations in drivers/clk/bcm/clk-bcm2835.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1028]
With #282 and #732 fixed, I have started experimenting with some of the features that @samitolvanen wrote for Android (LTO, SCS, and CFI) on my Raspberry Pi 3 since it supports a 64-bit kernel. I came across several violations in drivers/clk/bcm/clk-bcm2835.c, which I sent a couple of patches to fix:

https://lore.kernel.org/lkml/20200516080806.1459784-1-natechancellor@gmail.com/
https://lore.kernel.org/lkml/20200516080806.1459784-2-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patches accepted:

https://git.kernel.org/clk/c/f376c43bec4f8ee8d1ba5c5c4cfbd6e84fb279cb

https://git.kernel.org/clk/c/ 99a1ae29360980e79fa2d616819a6fe7411e4eda

**Comment by nickdesaulniers** [comment]
not yet in mainline

**Comment by nathanchance** [comment]
Merged into mainline:

https://git.kernel.org/linus/f376c43bec4f8ee8d1ba5c5c4cfbd6e84fb279cb

https://git.kernel.org/linus/99a1ae29360980e79fa2d616819a6fe7411e4eda
