### ISSUE TITLE
-Wmissing-prototypes

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1030]
kbuild is flooding our mailing list about `-Wmissing-prototypes`, which I thought was disabled.  Seems to be coming from randconfig builds?

**Comment by nathanchance** [comment]
Did they turn on `W=1`?

https://github.com/ClangBuiltLinux/linux/blob/03fb3acae4be8a6b680ffedb220a8b6c07260b40/scripts/Makefile.extrawarn#L20-L55

I've seen `-Wmissing-prototype`, `-Wtautological-constant-out-of-range-compare`, `-Wformat`, and `-Winitializer-overrides`, at least.

**Comment by nickdesaulniers** [comment]
yes, @rli9 confirmed it: https://groups.google.com/g/clang-built-linux/c/NGQl10Y-wNI/m/0rWuME12AwAJ
