### ISSUE TITLE
ppc64 builds are failing lock torture tests

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1031]
I noticed the CI was red again.
I emailed MPE about this.
https://groups.google.com/g/clang-built-linux/c/6W3Ee6PByyg

**Comment by nathanchance** [comment]
Fixed on the CI side by https://github.com/ClangBuiltLinux/continuous-integration/commit/6137298951403007add747709960379f3fa8f13c.

This has been resolved with QEMU 5.0.0 (https://github.com/ClangBuiltLinux/continuous-integration/issues/262 and https://github.com/qemu/qemu/commit/5ed195065cc6895f61b9d59bfa0a0536ed5ed51e), we just do not have access to it without building it in our Docker image, which I am not particularly interested in doing.
