### ISSUE TITLE
kernel/panic.o: warning: objtool: __warn_printk() falls through to next function clear_warn_once_fops_open()

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1040]
on linux next x86_64 defconfig, ToT LLVM, I'm seeing:
```
kernel/panic.o: warning: objtool: __warn_printk() falls through to next function clear_warn_once_fops_open()
```
I wonder if this is a recent regression on the LLVM, or the kernel side, or just a bug?

**Comment by ihalip** [comment]
I'm not seeing this with [https://github.com/ClangBuiltLinux/llvm-project/commit/a375463ad0630cab3a5b62d534ad64f822a20406](url) and next-20200611.

**Comment by nickdesaulniers** [comment]
thanks for confirming. Indeed, I don't see this anymore.
