### ISSUE TITLE
s390 vDSO does not respect $(LD)

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1041]
I will be sending a patch along for this shortly.

**Comment by nathanchance** [comment]
Patch submitted: https://lore.kernel.org/lkml/20200528060600.2732012-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
linux-next: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=2b2a25845d534ac6d55086e35c033961fdd83a26

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/2b2a25845d534ac6d55086e35c033961fdd83a26
