### ISSUE TITLE
PowerPC commit 334710b1496af8a0960e70121f850e209c20958f breaks clang

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1044]
Filed upstream: https://bugs.llvm.org/show_bug.cgi?id=46186

**Comment by nathanchance** [comment]
This is now in mainline.

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/lkml/20200611224355.71174-1-ndesaulniers@google.com/T/#m1664d2537576aa780037717ec01a948e7f7a778e

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D81767

**Comment by nickdesaulniers** [comment]
https://llvm.org/pr46390
