### ISSUE TITLE
unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000 via aarch64

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1054]
cc @DanielKristofKiss @broonie @kbeyls 

our [clang-10 arm64 builds on kernel CI](https://storage.kernelci.org/next/master/next-20200617/arm64/defconfig/clang-10/build.log) are getting flooded with 
```
aarch64-linux-gnu-ar: warning: <foo>.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
```

I also noticed the warning from gdb:
```
unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000 via aarch64
```

I assume we just need to refine our test in Kconfig for whether the tools support this note property?  @DanielKristofKiss mentioned being familiar with the note; can you help recommend a way to feature test support?

**Comment by nickdesaulniers** [comment]
0xc0000000 looks like a magic constant from https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=a6aadc28278a05f394c9353460ec74610ddf7ac6&id=3a9b136c998fc990cbde1a3cbc343050de704d6b

**Comment by nickdesaulniers** [comment]
Since the warning appears to be coming from aarch64-linux-gnu-ar, I would have guessed that
```
# foo.s
.set NT_GNU_PROPERTY_TYPE_0, 5
.set GNU_PROPERTY_AARCH64_FEATURE_1_AND, 0xc0000000

        .pushsection .note.gnu.property, "a"
        .align  3
        .long   2f - 1f
        .long   6f - 3f
        .long   NT_GNU_PROPERTY_TYPE_0
1:      .string "GNU"
2:
        .align  3
3:      .long   GNU_PROPERTY_AARCH64_FEATURE_1_AND
        .long   5f - 4f
4:
        .long   0
5:
        .align  3
6:
        .popsection
```
```sh
$ aarch64-linux-gnu-as foo.s -o foo.o
$ aarch64-linux-gnu-ar cDPrsT foo.a foo.o
```
would've reproduced.  I tested with binutils 2.27, but couldn't reproduce with that.

**Comment by nickdesaulniers** [comment]
> Since the warning appears to be coming from aarch64-linux-gnu-ar

nvm, the [log](https://storage.kernelci.org/next/master/next-20200617/arm64/defconfig/clang-10/build.log) has warnings from:
* aarch64-linux-gnu-strip
* aarch64-linux-gnu-objdump
* aarch64-linux-gnu-objcopy
* aarch64-linux-gnu-ar
* aarch64-linux-gnu-ld
* aarch64-linux-gnu-nm

So it seems that for some version of binutils, none of the utilities understand this note.

For the assembler file not reproducing, I wonder if Clang is emitting these notes?

**Comment by nickdesaulniers** [comment]
0xc0000000 shows up in https://github.com/llvm/llvm-project/blob/55d53d4f5448db87ab0bec903be94b696c8ed3e8/llvm/include/llvm/BinaryFormat/ELF.h#L1446 and is used in `AArch64AsmPrinter::emitStartOfAsmFile`.

**Comment by DanielKristofKiss** [comment]
This warning is caused by the .note.gnu.property. [1]
Both toolchain should emit this section for PAC/BTI. 
Since GCC 9.1  the .note.gnu.property section is added.
LLVM 10 does the same: https://reviews.llvm.org/rGd53e61863d48a07ce285d5b0a36abc67583023bd 

The above reproducer works with binutils 2.30 for me.
Binutils supports it from version 2.33.1. 
As I see the version check added only for GCC.
https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux.git/+/refs/tags/v5.8-rc1/arch/arm64/Kconfig#1523

Maybe that check should be there globally if the gnu-binutils are used.
LLVM utils support it since LLVM 9 as I know, I tested with LLVM10.0.1 so that should work.

[1] Special Sections at 
https://developer.arm.com/docs/ihi0056/g/elf-for-the-arm-64-bit-architecture-aarch64-abi-2019q4-documentation

**Comment by DanielKristofKiss** [comment]
#844 is a similar issue.

**Comment by broonie** [comment]
I've done a patch adding the check for binutils - will put it on the list shortly. These binutils version checks will need revisiting for lld support. I've not made the check global since some versions of GCC don't emit the note and therefore don't need the newer binutils.

**Comment by nickdesaulniers** [comment]
submitted: https://lore.kernel.org/linux-arm-kernel/CAKwvOdmOCVJOzp7tc62SV8yO8KkFpY9_fiX6yWqQRTtFC6vsfA@mail.gmail.com/T/#m4f2b5bbd70c5205522bba3686c8f0a6445a2139c
(Thanks @DanielKristofKiss  and @broonie !)

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git/commit/?id=4dc9b282bf5f

**Comment by nickdesaulniers** [comment]
Cool, that dropped our number of warnings down from >29k to 149.  It looks like we might still have an issue in EFI libstub:
```
   aarch64-linux-gnu-strip: warning: drivers/firmware/efi/libstub/lib-ctype.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
    aarch64-linux-gnu-objdump: warning: drivers/firmware/efi/libstub/lib-ctype.stub.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
    aarch64-linux-gnu-objcopy: warning: drivers/firmware/efi/libstub/lib-ctype.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
    aarch64-linux-gnu-ar: warning: drivers/firmware/efi/libstub/lib-ctype.stub.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
```
I didn't see any PAC related CFLAGS in drivers/firmware/efi/libstub/Makefile.  IIUC, drivers/firmware/efi/libstub/lib-ctype.o comes from lib/ctype.o?  I don't see any modifications to CFLAGS_ctype.o in lib/Makefile that might accidentally modify any flags.  Maybe there's a missing preprocessor guard on `CONFIG_ARM64_PTR_AUTH` being included in lib/ctype.c?  There's not much to that file, but maybe some of the headers?

cc @ardbiesheuvel

**Comment by kees** [comment]
Yeah, I think that's the same problem as #1068 : non-code object files are getting GNU_PROPERTY_TYPEs emitted.

**Comment by nickdesaulniers** [comment]
The Clang-10 release has finished, and I wouldn't consider this a blocker. Clang-10 will ship with this known issue. We can either choose to disable PAC w/ clang-10 (@broonie notes that there's no codegen bugs per se, just annoying build warnings), or move kernel CI builds to `LLVM=1` (which I'd rather do).

I'd still like to land the LLVM patches for clang-11 before closing this; just noting this will be a known issue w/ Clang 10.

**Comment by broonie** [comment]
The kernel already disables PAC on these systems - the bug is that clang emits the PAC/BTI notes unconditionally for some input files, regardless of what it's been asked to produce or what the linker on the system can cope sensibly with.

**Comment by nathanchance** [comment]
@nickdesaulniers you mentioned there was some follow up that was needed for clang-11 with this? Otherwise, are we good to close this up?

**Comment by nickdesaulniers** [comment]
A fix hasn't landed in LLVM yet. #1068 .  Let's close this and follow up there.
