### ISSUE TITLE
add -fno-addrsig when LLVM_IAS=1

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1060]
@ardbiesheuvel sent a patch
commit f77767ed5f4d ("efi/libstub/x86: Work around LLVM ELF quirk build regression")
Looking at https://reviews.llvm.org/D48155 defaults to `-faddrsig` unless `-no-integrated-as` is set.  It seems that the point of `-faddrsig` is to improve Identical Code Folding (ICF, `--icf=safe`).  Since the Linux kernel doesn't currently support ICF, we can probably shave down our vmlinux size slightly by just disabling this via `-fno-addrsig` globally when `LLVM_IAS=1` is set. cc @pcc @MaskRay

**Comment by MaskRay** [comment]
If --icf=safe is not used, then -fno-addrsig can be added to the toplevel CFLAGS if the compiler is clang. I don't think `LLVM_IAS` needs to be checked.

**Comment by pcc** [comment]
The size of vmlinux would not be affected by disabling address-significance tables, as they do not appear in the final binary. I wouldn't turn it off in the kernel globally, as long as it isn't causing any problems, as this would just be one more hurdle to enabling safe ICF in the kernel.
