### ISSUE TITLE
-Wenum-conversion in include/linux/memcontrol.h

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1061]
```
include/linux/memcontrol.h:45:30: warning: implicit conversion from enumeration type 'enum memcg_stat_item' to different enumeration type 'enum node_stat_item' [-Wenum-conversion]
        return vmstat_item_in_bytes(item);
               ~~~~~~~~~~~~~~~~~~~~ ^~~~
1 warning generated.
```

Reported on the mailing list: https://lore.kernel.org/linux-mm/20200622014803.GA2916179@ubuntu-n2-xlarge-x86/

**Comment by nickdesaulniers** [comment]
Looks like it also breaks mips builds since -Werror is set for at least arch/mips/kernel/ptrace.c.

**Comment by nickdesaulniers** [comment]
and ppc for arch/powerpc/kernel/ptrace/ptrace.c.

**Comment by nathanchance** [comment]
This has long since been fixed by an update to the patchset.
