### ISSUE TITLE
Section mismatch in reference from the function remove_pmd_table() to the function .meminit.text:split_kernel_mapping()

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1064]
Reported by @ikitayama in #811 
```
WARNING: modpost: vmlinux.o(.text+0x72050): Section mismatch in reference from the function remove_pmd_table() to the function .meminit.text:split_kernel_mapping()
The function remove_pmd_table() references
the function __meminit split_kernel_mapping().
This is often because remove_pmd_table lacks a __meminit 
annotation or the annotation of split_kernel_mapping is wrong.
```
also https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/352565615
ARCH=ppc64le

**Comment by ikitayama** [comment]
I no longer have access to POWER8 machine, so no support can be provided from my end.

**Comment by jcai19** [comment]
I tried to reproduce this issue with following commands but ran into different issues. Are the commands correct?

ARCH=powerpc CROSS_COMPILE=powerpc64le-linux-gnu- LLVM=1 O=out.powerpc64le make distclean ppc64le_defconfig zImage.epapr
  ARCH=powerpc CROSS_COMPILE=powerpc64le-linux-gnu- LLVM=1 O=out.powerpc64le make

**Comment by nathanchance** [comment]
It does not look like this is reproducible anymore (the warnings are tracked as #1328 and #664 [lol 664 * 2 is 1328])

```
$ make -skj"$(nproc)" ARCH=powerpc CROSS_COMPILE=powerpc64le-linux-gnu- LLVM=1 powernv_defconfig all
block/blk-mq.c:630:39: warning: passing 8-byte aligned argument to 32-byte aligned parameter 2 of 'smp_call_function_single_async' may result in an unaligned pointer access [-Walign-mismatch]
                smp_call_function_single_async(cpu, &rq->csd);
                                                    ^
1 warning generated.
arch/powerpc/boot/inffast.c:20:1: warning: unused function 'get_unaligned16' [-Wunused-function]
get_unaligned16(const unsigned short *p)
^
1 warning generated.
```

Looks like it was "fixed" by https://git.kernel.org/linus/d6d6ebfc5dbb4008be21baa4ec2ad45606578966.

@jcai19 you probably ran into #811 with that config.
