### ISSUE TITLE
.note.gnu.property always generated for object file without code

### ISSUE THREAD

**Issue by kees** [ClangBuiltLinux/linux#1068]
In trying to eliminate unwanted sections to support --orphan-handling=warn, it was discovered that -mbranch-protection=none for the efistub wasn't actually removing the .note.gnu.property section:
https://lore.kernel.org/lkml/20200624152646.GA6768@willie-the-truck/

This appears to be a Clang-specific bug, so I opened a bug for it:
https://bugs.llvm.org/show_bug.cgi?id=46480

I will be currently working around the issue by adding unused no-op code to lib/ctype.c

@willdeacon @arndb

**Comment by nickdesaulniers** [comment]
efistub? Maybe that's what we're still seeing from KernelCI?
https://github.com/ClangBuiltLinux/linux/issues/1054#issuecomment-650338838

**Comment by kees** [comment]
(Ah, my workaround must not be "static" for this to work.)

```
/*
 * Clang will generate .note.gnu.property sections for object files
 * without code, even in the presence of -mbranch-protection=none.
 * To work around this, define an unused static function.
 * https://llvm.org/pr46480
 */
#ifdef CONFIG_CC_IS_CLANG
void __maybe_unused __clang_needs_code_here(void) { }
#endif

```

**Comment by DanielKristofKiss** [comment]
I have a pending patch for LLVM that solves this issue (too). https://reviews.llvm.org/D80791

**Comment by DanielKristofKiss** [comment]
LLVM patch landed.
