### ISSUE TITLE
 -fsanitize=thread produces unwanted .eh_frame and .init_array.* sections

### ISSUE THREAD

**Issue by kees** [ClangBuiltLinux/linux#1069]
I am preparing to add --orphan-handling=warn to the linking stage. However, building with CONFIG_KCSAN (-fsanitize=thread) produces unwanted .eh_frame and .init_array.0 sections that cannot be removed without an explicit DISCARDS section.
https://lore.kernel.org/lkml/202006270840.E0BC752A72@keescook/

I have opened a Clang bug:
https://bugs.llvm.org/show_bug.cgi?id=46478

@melver

**Comment by kees** [comment]
-fsanitize=kernel-address (by way of CONFIG_KASAN_GENERIC) also causes this problem.

**Comment by nathanchance** [comment]
I think this just came up again with the 0day bot but with `CONFIG_GCOV_PROFILE_ALL`: https://lists.01.org/hyperkitty/list/kbuild-all@lists.01.org/thread/VNU25BJUAQACDDO35OGTVYULI3CKAXBB/

```
$ make -skj"$(nproc)" ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- defconfig

$ scripts/config -e GCOV_KERNEL -e GCOV_PROFILE_ALL

$ make -skj"$(nproc)" ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- olddefconfig vmlinux
...
aarch64-linux-gnu-ld: warning: orphan section `.eh_frame' from `init/main.o' being placed in section `.eh_frame'
aarch64-linux-gnu-ld: warning: orphan section `.eh_frame' from `init/version.o' being placed in section `.eh_frame'
aarch64-linux-gnu-ld: warning: orphan section `.eh_frame' from `init/do_mounts.o' being placed in section `.eh_frame'
aarch64-linux-gnu-ld: warning: orphan section `.eh_frame' from `init/do_mounts_initrd.o' being placed in section `.eh_frame'
aarch64-linux-gnu-ld: warning: orphan section `.eh_frame' from `init/initramfs.o' being placed in section `.eh_frame'
aarch64-linux-gnu-ld: warning: orphan section `.eh_frame' from `init/calibrate.o' being placed in section `.eh_frame'
aarch64-linux-gnu-ld: warning: orphan section `.eh_frame' from `init/init_task.o' being placed in section `.eh_frame'
...
```

With `LD=ld.lld`:

```
ld.lld: warning: <internal>:(.eh_frame) is being placed in '.eh_frame'
ld.lld: warning: <internal>:(.eh_frame) is being placed in '.eh_frame'
ld.lld: warning: <internal>:(.eh_frame) is being placed in '.eh_frame'
```

This should fix it:

```diff
diff --git a/include/asm-generic/vmlinux.lds.h b/include/asm-generic/vmlinux.lds.h
index b2b3d81b1535..7fa16ec2911d 100644
--- a/include/asm-generic/vmlinux.lds.h
+++ b/include/asm-generic/vmlinux.lds.h
@@ -993,7 +993,7 @@
  * CONFIG_CONSTRUCTORS wants to keep any .init_array.* sections.
  * https://llvm.org/pr46478
  */
-#if defined(CONFIG_KASAN_GENERIC) || defined(CONFIG_KCSAN)
+#if defined(CONFIG_KASAN_GENERIC) || defined(CONFIG_KCSAN) || defined(CONFIG_GCOV_KERNEL)
 # ifdef CONFIG_CONSTRUCTORS
 #  define SANITIZER_DISCARDS                                           \
        *(.eh_frame)
```

I suspect that #1227 also falls under this issue (meaning `CONFIG_CFI_CLANG` should be added to that list too).

**Comment by nickdesaulniers** [comment]
I wonder if this is another case of `-f` flags not being passed through to synthesized functions (cc @MaskRay who mentioned this before; I have the feeling the same is the case for `-fno-stack-protector` and friends)?  For example, does GCOV require `-fasynchronous-unwind-tables`? I doubt it.

**Comment by MaskRay** [comment]
The synthesized function issue (e.g. frame pointer, various security enhancement attributes) only affect LLVM IR. `-fasynchronous-unwind-tables` is MachineInstr/MCInstr level thing and is likely irrelevant. Clang's GCOV implementation uses debug info internally. It does not need unwind information.

**Comment by nathanchance** [comment]
Patch submitted for `CONFIG_GCOV_KERNEL` because of more 0day reports:

https://lore.kernel.org/r/20210129201116.2658179-1-nathan@kernel.org

https://groups.google.com/g/clang-built-linux/c/vd0HjMs_LTg/m/Mb6WT9UGBAAJ

**Comment by nickdesaulniers** [comment]
I suspect this was fixed on the LLVM side by https://reviews.llvm.org/D100251, please reopen if that's not the case.
