### ISSUE TITLE
-Wself-assign in drivers/misc/mic/scif/scif_dma.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#107]
Something funny going on there, maybe this line should be just removed.
```
drivers/misc/mic/scif/scif_dma.c:1577:12: warning: explicitly assigning value of variable of type 'bool' (aka '_Bool') to itself [-Wself-assign]
        dst_local = dst_local;
        ~~~~~~~~~ ^ ~~~~~~~~~
1 warning generated.
```

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/char-misc.git/commit/?id=6dbfdc1a4ee0030563af22bb682ff3bc590422f9

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6dbfdc1a4ee0030563af22bb682ff3bc590422f9
