### ISSUE TITLE
Certain powerpc builds fail after D77448

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1070]
Reported upstream: https://reviews.llvm.org/D77448#2105115

I'll file an actual PR on Wednesday if there is no response yet.

**Comment by nickdesaulniers** [comment]
@nathanchance can you please test https://reviews.llvm.org/rG57ad8f4 which should address this?

**Comment by nathanchance** [comment]
Testing right now, I will comment on Phabricator with the results and close this if it is all okay.
