### ISSUE TITLE
-Werror,-Wimplicit-function-declaration: implicit declaration of dl_task

### ISSUE THREAD

**Issue by torvic9** [ClangBuiltLinux/linux#1073]
```
kernel/trace/trace_sched_wakeup.c:548:35: error: implicit declaration of function 'dl_task' [-Werror,-Wimplicit-function-declaration]
        if (tracing_dl || (wakeup_dl && !dl_task(p)) ||
                                         ^
1 error generated.
```

This is with kernel 5.7.7 (`make LLVM=1`) and Clang 10.0.1rc2.

EDIT: doesn't seem to happen on 5.7.6.

**Comment by torvic9** [comment]
I added
`static int dl_task(struct task_struct *p);` 
to
`kernel/trace/trace_sched_wakeup.c`
and now the error is gone and a warning appears:
```
kernel/trace/trace_sched_wakeup.c:53:12: warning: function 'dl_task' has internal linkage but is not defined [-Wundefined-internal]
static int dl_task(struct task_struct *p);
           ^
kernel/trace/trace_sched_wakeup.c:554:35: note: used here
        if (tracing_dl || (wakeup_dl && !dl_task(p)) ||
```

I have no idea what I did there, is this even correct?

**Comment by torvic9** [comment]
Okay I changed it to `extern inline` and it now seems to work properly.

Since I do not know C , could someone please just confirm or comment on what I just did?

**Comment by nathanchance** [comment]
Can you post a config that triggers this?

**Comment by nickdesaulniers** [comment]
> kernel/trace/trace_sched_wakeup.c:53:12: warning: function 'dl_task' has internal linkage but is not defined [-Wundefined-internal]

If you forward declare a `static` function, then the definition MUST appear in the translation unit. `extern` is what you want, but even better is that there's probably a header that properly declares `dl_task`.

> This is with kernel 5.7.7 (make LLVM=1) and Clang 10.0.1rc2.

What about mainline?  Any non-stable branch may have bugs (though I think 5.7 currently is a stable for a short while until 5.8 is finalized?) since they don't get backports.

**Comment by torvic9** [comment]
> Can you post a config that triggers this?

https://github.com/torvic9/linux57-vd/blob/master/config.x270

Note that the config does not have clang in it, as I normally compile with gcc. However, the PKGBUILD has a switch to enable Clang, it basically just appends `LLVM=1` to the make command.
I use your very own tc-build script to build Clang btw, which is then added to $PATH.
Also, this kernel has a sh*tload of patches applied to it, so it's possible that the bug comes from there? Although none of the patches changes the file where the error comes up.

I don't have the knowledge to debug unfortunately, but I think the problem only came up with 5.7.7, as 5.7.6 worked just fine. I went through the changelog from .6 to .7 but I couldn't figure out anything.

> What about mainline?
Not tested yet, as I normally only use "stable" kernels. 5.7 is the current stable kernel.

Please excuse me if this error is on my side. I'm new to clang+linux kernel and I can only code Hello World...

> there's probably a header that properly declares `dl_task`.

Yes, that's the aforementioned `deadline.h`, which is included in `trace_sched_wakeup.c` via `#include <linux/sched/deadline.h>`.
See here: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/kernel/trace/trace_sched_wakeup.c?h=v5.7.7

**Comment by nathanchance** [comment]
```
$ head -n4 Makefile
# SPDX-License-Identifier: GPL-2.0
VERSION = 5
PATCHLEVEL = 7
SUBLEVEL = 7

$ mkdir -p out/x86_64

$ curl -LSso out/x86_64/.config https://github.com/torvic9/linux57-vd/raw/master/config.x270

$ make -skj"$(nproc)" O=out/x86_64 olddefconfig kernel/trace/

$ ls out/x86_64/kernel/trace
blktrace.o     power-traces.o      trace_events_filter.o    trace_functions.o  trace_printk.o        trace_stat.o
bpf_trace.o    ring_buffer.o       trace_events_hist.o      trace_hwlat.o      trace_probe.o         trace_syscalls.o
built-in.a     rpm-traces.o        trace_events.o           trace_mmiotrace.o  trace_sched_switch.o  trace_uprobe.o
fgraph.o       trace_clock.o       trace_events_trigger.o   trace_nop.o        trace_sched_wakeup.o  tracing_map.o
ftrace.o       trace_dynevent.o    trace_export.o           trace.o            trace_seq.o
modules.order  trace_event_perf.o  trace_functions_graph.o  trace_output.o     trace_stack.o
```

Looks fine to me with stock `linux-5.7.y`.

> Also, this kernel has a sh*tload of patches applied to it, so it's possible that the bug comes from there?

Entirely possible. I would try to remove those patches and see if that makes a difference.

> Although none of the patches changes the file where the error comes up.

The kernel is quite unwieldy with config dependencies at times so just because the patches appear not to touch the apparently relevant files does not mean they are not the problem.

**Comment by torvic9** [comment]
Okay, I will investigate as soon as I find some (compilation) time...

However, and that is the thing I do not understand: 5.7.6 works, 5.7.7 doesn't. Both of course with the same out-of-tree patches. Changelog is here: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.7.7 

Also why does my ridiculously lame patch apparently "fix" (or workaround) the issue?

**Comment by torvic9** [comment]
D'oh!
I'm sorry for wasting your time :-( 

The error indeed comes from one of the patches and is not at all related to clang, see here: https://gitlab.com/alfredchen/projectc/-/issues/18

It's fixed, and I'll close this now.
Thank you for your patience and keep up the good work!
