### ISSUE TITLE
LLD: `ld.lld: error: undefined symbol: pa_trampoline_start`

### ISSUE THREAD

**Issue by paulmenzel** [ClangBuiltLinux/linux#1076]
Using Debian Sid/unstable with

    $ ld.lld --version # symbolic link to ld.lld-10
    LLD 10.0.0 (compatible with GNU linkers)

building Linux 5.8-rc3+ for `ARCH=x86` fails with the errors below.

```
$ make bindeb-pkg -j32 LLVM=1
[…]
  LD      arch/x86/realmode/rm/realmode.elf
ld.lld: error: undefined symbol: pa_trampoline_start
>>> referenced by arch/x86/realmode/rm/header.o:(real_mode_header)

ld.lld: error: undefined symbol: pa_trampoline_header
>>> referenced by arch/x86/realmode/rm/header.o:(real_mode_header)

ld.lld: error: undefined symbol: pa_trampoline_pgd
>>> referenced by arch/x86/realmode/rm/header.o:(real_mode_header)
>>> referenced by trampoline_64.S:122 (arch/x86/realmode/rm/trampoline_64.S:122)
>>>               arch/x86/realmode/rm/trampoline_64.o:(startup_32)

ld.lld: error: undefined symbol: pa_wakeup_start
>>> referenced by arch/x86/realmode/rm/header.o:(real_mode_header)

ld.lld: error: undefined symbol: pa_wakeup_header
>>> referenced by arch/x86/realmode/rm/header.o:(real_mode_header)

ld.lld: error: undefined symbol: pa_machine_real_restart_asm
>>> referenced by arch/x86/realmode/rm/header.o:(real_mode_header)

ld.lld: error: undefined symbol: pa_startup_32
>>> referenced by trampoline_64.S:76 (arch/x86/realmode/rm/trampoline_64.S:76)
>>>               arch/x86/realmode/rm/trampoline_64.o:(trampoline_start)

ld.lld: error: undefined symbol: pa_tr_flags
>>> referenced by trampoline_64.S:104 (arch/x86/realmode/rm/trampoline_64.S:104)
>>>               arch/x86/realmode/rm/trampoline_64.o:(startup_32)

ld.lld: error: undefined symbol: pa_tr_cr4
>>> referenced by trampoline_64.S:118 (arch/x86/realmode/rm/trampoline_64.S:118)
>>>               arch/x86/realmode/rm/trampoline_64.o:(startup_32)

ld.lld: error: undefined symbol: pa_tr_efer
>>> referenced by trampoline_64.S:126 (arch/x86/realmode/rm/trampoline_64.S:126)
>>>               arch/x86/realmode/rm/trampoline_64.o:(startup_32)
>>> referenced by trampoline_64.S:127 (arch/x86/realmode/rm/trampoline_64.S:127)
>>>               arch/x86/realmode/rm/trampoline_64.o:(startup_32)

ld.lld: error: undefined symbol: pa_startup_64
>>> referenced by trampoline_64.S:141 (arch/x86/realmode/rm/trampoline_64.S:141)
>>>               arch/x86/realmode/rm/trampoline_64.o:(startup_32)

ld.lld: error: undefined symbol: pa_tr_gdt
>>> referenced by arch/x86/realmode/rm/trampoline_64.o:(tr_gdt)
>>> referenced by reboot.S:28 (arch/x86/realmode/rm/reboot.S:28)
>>>               arch/x86/realmode/rm/reboot.o:(machine_real_restart_asm)

ld.lld: error: undefined symbol: pa_machine_real_restart_paging_off
>>> referenced by reboot.S:34 (arch/x86/realmode/rm/reboot.S:34)
>>>               arch/x86/realmode/rm/reboot.o:(machine_real_restart_asm)

ld.lld: error: undefined symbol: pa_machine_real_restart_idt
>>> referenced by reboot.S:47 (arch/x86/realmode/rm/reboot.S:47)
>>>               arch/x86/realmode/rm/reboot.o:(machine_real_restart_asm)

ld.lld: error: undefined symbol: pa_machine_real_restart_gdt
>>> referenced by reboot.S:54 (arch/x86/realmode/rm/reboot.S:54)
>>>               arch/x86/realmode/rm/reboot.o:(machine_real_restart_asm)
>>> referenced by arch/x86/realmode/rm/reboot.o:(machine_real_restart_gdt)

ld.lld: error: undefined symbol: pa_wakeup_gdt
>>> referenced by arch/x86/realmode/rm/wakeup_asm.o:(wakeup_gdt)
make[6]: *** [arch/x86/realmode/rm/Makefile:57: arch/x86/realmode/rm/realmode.elf] Error 1
make[5]: *** [arch/x86/realmode/Makefile:23: arch/x86/realmode/rm/realmode.bin] Error 2
make[4]: *** [scripts/Makefile.build:497: arch/x86/realmode] Error 2
make[4]: *** Waiting for unfinished jobs....
```

Using the GNU nm (Binutils 2.34-8) instead `llvm-nm`, the build is successful.

**Comment by dileks** [comment]
Setting `LLVM=1` enables a lot of LLVM tools beyond `clang` compiler and `ld.lld` linker, see kernel-docs `llvm.rst`.

Is that what you really want?

[1] has also some good hints for building and check our wiki.

Did you try with `clang-10` and `ld.lld-10` only?
( Using `LLVM=1` is known to be broken with `clang-10` or needs workarounds. )

Just some hints:
The Debian repositories offer `llvm-toolchain-10` version `10.0.1-rc2` (for example Debain/experimental) or try packages from <apt.llvm.org>.

Please use and set appropriate labels.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/kbuild/llvm.rst

**Comment by paulmenzel** [comment]
> Setting `LLVM=1` enables a lot of LLVM tools beyond `clang` compiler and `ld.lld` linker, see kernel-docs `llvm.rst`.
> 
> Is that what you really want?

Thank you for your reply. Yes, it is what I want and it works for `ARCH=x86`. I patched the Makefile to just change `LD` to the GNU linker, and the build succeeded.

```
--- a/Makefile
+++ b/Makefile
@@ -430,7 +430,7 @@ ifneq ($(LLVM),)
 CC             = clang
 LD             = ld.lld
 AR             = llvm-ar
-NM             = llvm-nm
+NM             = nm
 OBJCOPY                = llvm-objcopy
 OBJDUMP                = llvm-objdump
 READELF                = llvm-readelf
```

> [1] has also some good hints for building and check our wiki.

I read that.

> Did you try with `clang-10` and `ld.lld-10` only?
> ( Using `LLVM=1` is known to be broken with `clang-10` or needs workarounds. )

No, I just tried replacing LLD by the GNU linker, and the build succeeded.

> Just some hints:
> The Debian repositories offer `llvm-toolchain-10` version `10.0.1-rc2` (for example Debain/experimental) or try packages from <apt.llvm.org>.

I’ll try that next week.

> Please use and set appropriate labels.

Sorry for not doing that. Trying to do it now, I couldn’t find out how. I am not allowed to set any labels.

> [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/kbuild/llvm.rst

**Comment by nathanchance** [comment]
You wouldn't happen to have a config to try? Additionally, this is `ARCH=x86` (as in 32-bit x86), not `ARCH=x86_64`, correct?

**Comment by dileks** [comment]
@paulmenzel 

Not 100% sure what your intention is on this issue here.

You do not need to hack the toplevel Makefile :-).
Just pass all `LLVM tools` you want manually.
Unsure about the status of `llvm-nm` and `llvm-ar` - depending on selected target arch - but are known to be BROKEN the lower their version are.

You can pass `ARCH=...` to your `make` line - whatever you want 32bit or 64bit (see @nathanchance reply).

BTW, I am building here with a 99,9% compatible Debian-kernel config.

Thanks for sharing your results.

Did you try?
```
make LLVM=1 NM=nm ...
```
Unsure, if this is overriding `NM=llvm-nm` from `LLVM=1`. Just try.

Currently, I am experimenting with Linux v5.7.y - with `Linux v5.8-rc4` I will jump on Linux v5.8 - I hope so.

NOTE: llvm-toolchain-11:
A good choice is to build a selfmade `llvm-toolchain-11` with `tc-build` and use the `--good-revision` parameter.

[1] https://github.com/ClangBuiltLinux/tc-build

**Comment by paulmenzel** [comment]
Sorry, I incorrectly wrote in the original report, that I had replaced the linker to get it building. But I had replaced `llvm-nm` by `nm`. I updated the report. Sorry for the confusion.

**Comment by dileks** [comment]
For less confusion what x86 arch? 32bit or 64bit?

**Comment by paulmenzel** [comment]
> For less confusion what x86 arch? 32bit or 64bit?

Give me some time, I am going through the comments. ;-) (And trying to find out the difference between `ARCH=x86` and `ARCH=x86_64`, as I built with `ARCH=i386` for 32-bit environments.) So, give me an hour.

**Comment by dileks** [comment]
You can have 2 hours :-).

Speaking in Debian language "AMD64" vs. "i386".

**Comment by dileks** [comment]
Just finished my first `Linux v5.8-rc4` build with `gcc-10` and `ld.bfd`.

Later in a 2nd run `clang-11` and `ld.lld-11` and maybe as 3rd together with `LLVM_IAS=1` and `OBJDUMP=llvm-objdump`.

**Comment by paulmenzel** [comment]
[`config`](https://github.com/ClangBuiltLinux/linux/files/4878101/config.txt) has `CONFIG_X86_64=y`, but `make bindeb-pkg` still outputs `ARCH=x86`, so no idea what is going on. The resulting Linux kernel build boots on x86_64, and the package has `amd64` in the name. (I verified, that I get the same error with `ARCH=x86_64`.)

Patching the `NM=` variable in `Makefile` was the quickest way for me to still use the other LLVM tools with `LLVM=1`.

A package with the name *llvm-toolchain* does not exist in Debian, but I installed [`clang-11`](https://packages.debian.org/experimental/clang-11) and `ldd-11` from Debian experimental. The version is 1:11~++20200701093119+ffee8040534-1~exp1. With that it worked with `llvm-nm`, so I am closing the issue. (I’ll be able to boot test this in the next days.)

```
  INSTALL debian/linux-libc-dev/usr/include
dpkg-deb: building package 'linux-libc-dev' in '../linux-libc-dev_5.8.0-rc3-00165-g9e60394fee92d-104_amd64.deb'.
dpkg-deb: building package 'linux-image-5.8.0-rc3-00165-g9e60394fee92d' in '../linux-image-5.8.0-rc3-00165-g9e60394fee92d_5.8.0-rc3-00165-g9e60394fee92d-104_amd64.deb'.
 dpkg-genbuildinfo --build=binary
 dpkg-genchanges --build=binary >../linux-5.8.0-rc3-00165-g9e60394fee92d_5.8.0-rc3-00165-g9e60394fee92d-104_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build .
dpkg-buildpackage: info: binary-only upload (no source included)
```

(I have other local (unrelated) changes, but it’s based on v5.8-rc3-156-g35e884f89df4c.

Great work, and thank you to all of you.

**Comment by dileks** [comment]
I do not doubt you had success but if you have installed `llvm-toolchain-11` (the name of the Debian source package, here: 11) from Debian/experimental you cannot be done with `LLVM=1`.
`LLVM=1` expects each LLVM tool as `$llvm_tool` but Debian provides `$llvm_tool-$LLVM_MAJOR_VERSION`.

What I did:
```
### LLVM tools options (here: OBJDUMP=llvm-objdump)
# See <https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/kbuild/llvm.rst>
# LLVM=1 sets these host and target options:
#   host:   HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar HOSTLD=ld.lld
#   target: CC=clang LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump OBJSIZE=llvm-size READELF=llvm-readelf
##LLVM_TOOLS_OPTS="LLVM=1"
##LLVM_TOOLS_OPTS="OBJDUMP=llvm-objdump"
##LLVM_TOOLS_OPTS=""
LLVM_MAJOR_VER="11"
LLVM_TOOLS_HOST_OPTS="HOSTCC=clang-$LLVM_MAJOR_VER HOSTCXX=clang++-$LLVM_MAJOR_VER HOSTAR=llvm-ar-$LLVM_MAJOR_VER HOSTLD=ld.lld-$LLVM_MAJOR_VER"
LLVM_TOOLS_TARGET_OPTS="CC=clang-$LLVM_MAJOR_VER LD=ld.lld-$LLVM_MAJOR_VER AR=llvm-ar-$LLVM_MAJOR_VER NM=llvm-nm-$LLVM_MAJOR_VER STRIP=llvm-strip-$LLVM_MAJOR_VER OBJCOPY=llvm-objcopy-$LLVM_MAJOR_VER OBJDUMP=llvm-objdump-$LLVM_MAJOR_VER OBJSIZE=llvm-size-$LLVM_MAJOR_VER READELF=llvm-readelf-$LLVM_MAJOR_VER"

LLVM_TOOLS_OPTS="$LLVM_TOOLS_HOST_OPTS $LLVM_TOOLS_TARGET_OPTS"
```

**Comment by paulmenzel** [comment]
Yes, I can. ;-) Sorry for omitting this, and thank you for solving my confusion regarding the source package name.

Anyway, as the Debian LLVM packages do not support `update-alternatives`, here is my workaround.

    $ for i in /usr/bin/llvm-*11; do sudo ln -fs $i ${i%-11}; done
    $ cd /usr/bin; sudo ln -sf clang-11 clang; sudo ln -sf ld.lld-11 ld.lld; sudo ln -sf lld-11 lld; cd -

**Comment by dileks** [comment]
For Debian users `LLVM=1` is not very ideal.

And the term "LLVM tools" is confusing in the Debian world as well - as we have `llvm-$ver-tools` Debian package.

BTW, I recall we had `llvm-defaults` like `gcc-defaults` - this is now `llvm` Debian package as far as I can see.
For `11` there is nothing.

**Comment by dileks** [comment]
As an interim solution I did:

```
### Compiler options
# Optional: mycompiler wrapper-script (suggested by Linus Torvalds)
##CC_FOR_BUILD="mycompiler"
##GCC_MAJOR_VER="10"
##CC_FOR_BUILD="gcc-$GCC_MAJOR_VER"
LLVM_MAJOR_VER="11"
CC_FOR_BUILD="clang-$LLVM_MAJOR_VER"
CXX_FOR_BUILD="clang++-$LLVM_MAJOR_VER"

### Linker options
# Optional: mylinker wrapper-script
##LD_FOR_BUILD="mylinker"
##LD_FOR_BUILD="ld.bfd"
LD_FOR_BUILD="ld.lld-$LLVM_MAJOR_VER"

### LLVM tools options
# See <https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/kbuild/llvm.rst>
# LLVM=1 sets these host and target options:
#   host:   HOSTCC=clang HOSTCXX=clang++ HOSTLD=ld.lld HOSTAR=llvm-ar
#   target: CC=clang LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump OBJSIZE=llvm-size READELF=llvm-readelf
##LLVM_TOOLS_OPTS="LLVM=1"
##LLVM_TOOLS_OPTS="OBJDUMP=llvm-objdump"
##LLVM_TOOLS_OPTS=""
AR_FOR_BUILD="llvm-ar-$LLVM_MAJOR_VER"
NM_FOR_BUILD="llvm-nm-$LLVM_MAJOR_VER"
OBJCOPY_FOR_BUILD="llvm-objcopy-$LLVM_MAJOR_VER"
OBJDUMP_FOR_BUILD="llvm-objdump-$LLVM_MAJOR_VER"
OBJSIZE_FOR_BUILD="llvm-size-$LLVM_MAJOR_VER"
READELF_FOR_BUILD="llvm-readelf-$LLVM_MAJOR_VER"
STRIP_FOR_BUILD="llvm-strip-$LLVM_MAJOR_VER"
LLVM_TOOLS_HOST_OPTS="HOSTCC=$CC_FOR_BUILD HOSTCXX=$CXX_FOR_BUILD HOSTLD=$LD_FOR_BUILD HOSTAR=$AR_FOR_BUILD"
LLVM_TOOLS_TARGET_OPTS="CC=$CC_FOR_BUILD LD=$LD_FOR_BUILD AR=$AR_FOR_BUILD NM=$NM_FOR_BUILD OBJCOPY=$OBJCOPY_FOR_BUILD OBJDUMP=$OBJDUMP_FOR_BUILD OBJSIZE=$OBJSIZE_FOR_BUILD READELF=$READELF_FOR_BUILD STRIP=$STRIP_FOR_BUILD"
```

**Comment by dileks** [comment]
@paulmenzel 

Looks good with above "manually" set `LLVM=1`:
```
$ cat /proc/version 
Linux version 5.8.0-rc4-2-amd64-llvm11 (sedat.dilek@gmail.com@iniza) (Debian clang version 11.0.0-++20200701093119+ffee8040534-1~exp1 , LLD 11.0.0) #2~bullseye+dileks1 SMP 2020-07-06
```

**Comment by dileks** [comment]
Looks good with above "manually" set LLVM=1 and `LLVM_IAS=1`:

```
$ cat /proc/version 
Linux version 5.8.0-rc4-3-amd64-llvm11-ias (sedat.dilek@gmail.com@iniza) (Debian clang version 11.0.0-++20200701093119+ffee8040534-1~exp1 , LLD 11.0.0) #3~bullseye+dileks1 SMP 2020-07-06
```

Note: https://github.com/ClangBuiltLinux/linux/issues/1043#issuecomment-654523721
