### ISSUE TITLE
"error: unknown use of instruction mnemonic without a size suffix" while assembling arch/x86/entry/entry_64.o of linux-next

### ISSUE THREAD

**Issue by jcai19** [ClangBuiltLinux/linux#1079]
Assembling arch/x86/entry/entry_64.o of linux-next failed on x86_64 with the follow message.

$ clang -Wp,-MMD,arch/x86/entry/.entry_64.o.d  -nostdinc -isystem ${PATH_TO_LLVM_SRC}/build/release/lib/clang/11.0.0/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -Qunused-arguments -D__ASSEMBLY__ -fno-PIE -Werror=unknown-warning-option -m64    -c -o arch/x86/entry/entry_64.o arch/x86/entry/entry_64.S
<instantiation>:2:2: error: unknown use of instruction mnemonic without a size suffix

Currently assembling entry_64.S with IAS has another issue reported at https://github.com/ClangBuiltLinux/linux/issues/1043. Apply the patch from https://github.com/ClangBuiltLinux/linux/issues/1043#issuecomment-642163507 to work around.

**Comment by nickdesaulniers** [comment]
Any idea which instruction it's referring to? Sounds like maybe a pseudo we don't implement? #1010 comes to mind, though the error is different.

**Comment by nathanchance** [comment]
```
$ make -skj"$(nproc)" LLVM=1 LLVM_IAS=1 O=out distclean defconfig bzImage
<instantiation>:2:2: error: unknown use of instruction mnemonic without a size suffix
 lsl %rax, %rax
 ^
<instantiation>:2:2: note: while in macro instantiation
 LOAD_CPU_AND_NODE_SEG_LIMIT %rax
 ^
<instantiation>:1:1: note: while in macro instantiation
ALTERNATIVE "LOAD_CPU_AND_NODE_SEG_LIMIT %rax", "RDPID  %rax", (16*32+22)
^
<instantiation>:2:2: note: while in macro instantiation
 GET_PERCPU_BASE %rax
 ^
../arch/x86/entry/entry_64.S:846:2: note: while in macro instantiation
 SAVE_AND_SET_GSBASE scratch_reg=%rax save_reg=%rbx
 ^
make[4]: *** [../scripts/Makefile.build:382: arch/x86/entry/entry_64.o] Error 1
make[4]: Target '__build' not remade because of errors.
make[3]: *** [../scripts/Makefile.build:544: arch/x86/entry] Error 2
...
```

**Comment by nickdesaulniers** [comment]
bgawk! 🐔 

So even though `lsl` would make sense as "Logical shift left," on x86 it stands for "[load segment limit](https://www.felixcloutier.com/x86/lsl)" which can have a 64b operand, but not two 64b operands. (Logical Shift Left is `shl` on x86).

Though it seems GCC accepts this? https://godbolt.org/z/cnez4c `48 0f 03 c0` seems to be the encoding for it.

cc @topperc

**Comment by topperc** [comment]
We seem to be adhering strictly to what the SDM says LSL r64, r32/m16*

so we'll accept "lsl %eax, %rax" 

I think I can fix it to match gcc pretty easily.

**Comment by nickdesaulniers** [comment]
Ah, indeed, gcc encodes `lsl %rax, %rax` the same as `lsl %eax, %rax`.  I guess we could fix this on the kernel side to not use the same register for both operands (this all comes from the expansion of `SAVE_AND_SET_GDBASE`, though I'm not sure if there's an easy way in assembler to say something to the effect of "when give a 64b register, instead use it's lower 32b alias."


kernel commit eaad981291ee3

**Comment by jcai19** [comment]
Sorry it seems I missed some important information when reporting issue, and thanks @nathanchance for adding it. @nickdesaulniers I was just typing up my question about whether we should fix this in kernel instead since that's more clear. And I wonder if we should support this in IAS since that does not appear to have much benefit?

**Comment by nickdesaulniers** [comment]
Maybe. Also, `lsl %ax, %rax` gets rejected by LLVM, though that's what the disassembly from GCC presents.

**Comment by dileks** [comment]
"[X86] Teach assembler parser to accept lsl and lar with a 64 or 32 source register when the destination is a 64 register."

[1] https://github.com/llvm/llvm-project/commit/3c2a56a857227b6bc39285747269f02cd7a9dbe5

**Comment by nathanchance** [comment]
Everything appears okay after https://github.com/llvm/llvm-project/commit/3c2a56a857227b6bc39285747269f02cd7a9dbe5.

Should that be added to `release/11.x`?

**Comment by dileks** [comment]
I cherry-picked it on top of `release/11.x/d256b8ad5f2898cd05faa7319e00ea4a86b0cb47` and was able to build and boot with `Linux v5.8-rc5+`.

**Comment by topperc** [comment]
I also fixed 16-bit registers for source in https://github.com/llvm/llvm-project/commit/71b49aa438b22b02230fff30e8874ff756336e6d

**Comment by dileks** [comment]
Cherry-picked both on top of `release/11.x (d256b8ad5f2898cd05faa7319e00ea4a86b0cb47)` - looks good with `Linux v5.8-rc5+`.

**Comment by nickdesaulniers** [comment]
Thanks @topperc ! Good eye noticing the initial fix @dileks . And thanks for testing @nathanchance . 🇦🇼 🛳️

**Comment by dileks** [comment]
To clarify:
`[FIXED][LLVM] 12` label is correct but both fixes did not land in `release/11.x`.

Note: I had cherry-picked as 3rd fix https://github.com/llvm/llvm-project/commit/00f3579aea6e3d4a4b7464c3db47294f71cef9e4 which landed in `release/11.x` some hours ago.

**Comment by nickdesaulniers** [comment]
> but both fixes did not land in release/11.x.

Ah, @topperc would you mind pushing those two to the release/11.x branch please?

**Comment by dileks** [comment]
+1

**Comment by topperc** [comment]
Merge request filed here https://llvm.org/pr46765

**Comment by dileks** [comment]
Merged into `release/11.x` branch (see update in [1]).

[1] https://llvm.org/pr46765

**Comment by dileks** [comment]
@nickdesaulniers 
I leave it to you with closing - unsure what you mean with "Needs LTS Backport" label.

**Comment by nickdesaulniers** [comment]
@dileks I try to use it to denote bugs for which we should try to get the fix backported if possible.  `LTS` may be too specific to Linux.

**Comment by dileks** [comment]
Labels help a lot to keep the overview and the possibility of sorting.
Is there a list with explanation of the labels?
Sort of bubble-help - do not know what GitHub offers as a service.

**Comment by nickdesaulniers** [comment]
Yes, if you go to the issue list, then click "Labels" near the top left near the green "New Issue" button.
https://github.com/ClangBuiltLinux/linux/labels will show a description if it exists, which is then shown as a tooltip for an issues labels (in the top left of an individual issue) when `mouseover` even occurs.

**Comment by dileks** [comment]
Sorry for being off-topic: I looked through the list of labels and did some minor changes.

**Comment by dileks** [comment]
> @dileks I try to use it to denote bugs for which we should try to get the fix backported if possible. `LTS` may be too specific to Linux.

OK, this one has not a description - I leave it to you.
Maybe rename it to reflect it's `Linux` specific.
What do you mean with `LTS` (LongTerm Support)?
`Linux LTS` means to me one release mentioned in [1].

[1] https://www.kernel.org/category/releases.html

**Comment by nickdesaulniers** [comment]
No worries, feel free to create new labels as you see fit.  How does the description I've added here look: https://github.com/ClangBuiltLinux/linux/labels?q=backport ?

**Comment by dileks** [comment]
Looks find to me.

Nick Desaulniers <notifications@github.com> schrieb am Mo., 20. Juli 2020,
23:53:
