### ISSUE TITLE
-Wint-conversion in drivers/remoteproc/qcom_common.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1087]
via kernelci linux-next defconfig
```
    drivers/remoteproc/qcom_common.c:210:7: warning: incompatible integer to pointer conversion assigning to 'struct qcom_ssr_subsystem *' from 'int' [-Wint-conversion]
```
there's also a
    drivers/remoteproc/qcom_common.c:210:9: error: implicit declaration of function 'kzalloc' [-Werror,-Wimplicit-function-declaration]
that can be fixed too.

**Comment by nathanchance** [comment]
Fairly certain that `kzalloc` not being declared is the reason for the first warning...

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/andersson/remoteproc/c/0cf17702d872128fc2bec79a9578b5cb00d54a11
