### ISSUE TITLE
error: could not find corresponding %pcrel_hi

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1089]
looks like riscv linux-next and mainline are failing with the error:
```
error: could not find corresponding %pcrel_hi
1 error generated.
make[2]: *** [scripts/Makefile.build:281: kernel/irq/manage.o] Error 1
```
https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/360362545
looks related to #1072. I wonder if the LLVM fix fixed the crash, but still has a bug?

cc @nathanchance @palmer-dabbelt

**Comment by nathanchance** [comment]
I am guessing that the problematic optimization that was discussed in #1072 has been merged again but I have not had time to dig into this yet. I do not think I have seen an assertion failure in my local builds though so might be something different. I should be able to do a bisect and reduction tonight after work.

**Comment by nathanchance** [comment]
Related to https://reviews.llvm.org/D82988, reverting this causes the build to succeed again (and I do not see an assertion failure like last time). Looks like there is a separate report at the bottom of the Phabricator issue as well, I'll try to keep an eye on this and jump in if it does not get resolved in a few days.

**Comment by nickdesaulniers** [comment]
Looks like maybe it was reverted today: https://reviews.llvm.org/rG1d15bbb9d9168a7eecf4a37a46e12babd1d58afc

**Comment by lenary** [comment]
Sorry about this!

**Comment by nathanchance** [comment]
This has been fixed with the revert.
