### ISSUE TITLE
Failed assertion in net/core/fib_rules.c after D59730

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1091]
Reported upstream: https://reviews.llvm.org/D59730#2152440

**Comment by nickdesaulniers** [comment]
fix: https://reviews.llvm.org/D83870

**Comment by dileks** [comment]
Patch in LLVM upstream.

[1] https://github.com/llvm/llvm-project/commit/8b354cc8db413f596c95b4f3240fabaa3e2c931e

**Comment by dileks** [comment]
"Merge 8b354cc8db413f596c95b4f3240fabaa3e2c931e into 11.0 release"

[1] https://llvm.org/pr46785

**Comment by dileks** [comment]
Fixed in `release/11.x` branch.

[1] https://github.com/llvm/llvm-project/commit/cebd637c88624dfd44520848cb1f43dc8a02ba80
[2] https://llvm.org/pr46785

**Comment by nickdesaulniers** [comment]
so tomorrow's (Jul 22) ci run for riscv should be green

**Comment by nathanchance** [comment]
For linux, it should with the uprev to LLVM 12.

For linux-next, https://github.com/ClangBuiltLinux/linux/issues/1092 will still cause a failure.
