### ISSUE TITLE
LLVM commit 3452a0d8c17f7166f479706b293caf6ac76ffd90 causes issues with cross compiling

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1099]
https://github.com/llvm/llvm-project/commit/3452a0d8c17f7166f479706b293caf6ac76ffd90

```
$ make -skj"$(nproc)" ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 O=out/arm64 distclean defconfig init/main.o
arch/arm64/Makefile:34: LSE atomics not supported by binutils
arch/arm64/Makefile:45: Detected assembler with broken .inst; disassembly will be unreliable
/home/nathan/cbl/toolchains/binutils/bin/as: unrecognized option '-EL'
clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/home/nathan/src/linux/scripts/Makefile.build:281: scripts/mod/empty.o] Error 1
...
```

That change seems like a fairly big departure from how cross compiling with clang has always worked. I suppose this is the expected change on the kernel side? Is this going to have an impact on compiling with older versions of clang?

```diff
diff --git a/Makefile b/Makefile
index 0b5f8538bde5..ae932386ed47 100644
--- a/Makefile
+++ b/Makefile
@@ -567,7 +567,7 @@ ifneq ($(shell $(CC) --version 2>&1 | head -n 1 | grep clang),)
 ifneq ($(CROSS_COMPILE),)
 CLANG_FLAGS    += --target=$(notdir $(CROSS_COMPILE:%-=%))
 GCC_TOOLCHAIN_DIR := $(dir $(shell which $(CROSS_COMPILE)elfedit))
-CLANG_FLAGS    += --prefix=$(GCC_TOOLCHAIN_DIR)
+CLANG_FLAGS    += --prefix=$(GCC_TOOLCHAIN_DIR)/$(CROSS_COMPILE)
 GCC_TOOLCHAIN  := $(realpath $(GCC_TOOLCHAIN_DIR)/..)
 endif
 ifneq ($(GCC_TOOLCHAIN),)
```

cc @MaskRay

**Comment by MaskRay** [comment]
It is late in my timezone. I'll change -B to consider `$value/powerpc64-linux-gnu/$name` as well.

I removed `$value/powerpc64-linux-gnu-$name` from clang -B.

**Comment by MaskRay** [comment]
```patch
Subject: [PATCH] Makefile: correct --prefix= for Clang builds

When CROSS_COMPILE is set (e.g. aarch64-linux-gnu-), if $(CROSS_COMPILE)elfedit
is found at /usr/bin/aarch64-linux-gnu-, GCC_TOOLCHAIN_DIR will be set to
/usr/bin/.  --prefix= will be set to /usr/bin/ and Clang as of 11 will search
for $(GCC_TOOLCHAIN_DIR)aarch64-linux-gnu-$needle and $(GCC_TOOLCHAIN_DIR)$needle.
Newer Clang only searches for $(GCC_TOOLCHAIN_DIR)$needle and for example will
find /usr/bin/as instead of /usr/bin/aarch64-linux-gnu-as. The new behavior is
to better model how GCC handles -B/--prefix.

Set --prefix= to $(GCC_TOOLCHAIN_DIR)$(CROSS_COMPILE)
(/usr/bin/aarch64-linux-gnu-) so that newer Clang can find the appropriate cross
compiling GNU as (when -no-integrated-as is in effect).
---
 Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Makefile b/Makefile
index 0b5f8538bde5..3ac83e375b61 100644
--- a/Makefile
+++ b/Makefile
@@ -567,7 +567,7 @@ ifneq ($(shell $(CC) --version 2>&1 | head -n 1 | grep clang),)
 ifneq ($(CROSS_COMPILE),)
 CLANG_FLAGS    += --target=$(notdir $(CROSS_COMPILE:%-=%))
 GCC_TOOLCHAIN_DIR := $(dir $(shell which $(CROSS_COMPILE)elfedit))
-CLANG_FLAGS    += --prefix=$(GCC_TOOLCHAIN_DIR)
+CLANG_FLAGS    += --prefix=$(GCC_TOOLCHAIN_DIR)$(CROSS_COMPILE)
 GCC_TOOLCHAIN  := $(realpath $(GCC_TOOLCHAIN_DIR)/..)
 endif
 ifneq ($(GCC_TOOLCHAIN),)
-- 
```

-----

`git send-email --dry-run --to-cmd='scripts/get_maintainer.pl -i' 0001-Makefile-correct-prefix-for-Clang-builds.patch`

Looks good?

**Comment by MaskRay** [comment]
> That change seems like a fairly big departure from how cross compiling with clang has always worked. I suppose this is the expected change on the kernel side? Is this going to have an impact on compiling with older versions of clang?
> 
> ```diff
> diff --git a/Makefile b/Makefile
> index 0b5f8538bde5..ae932386ed47 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -567,7 +567,7 @@ ifneq ($(shell $(CC) --version 2>&1 | head -n 1 | grep clang),)
>  ifneq ($(CROSS_COMPILE),)
>  CLANG_FLAGS    += --target=$(notdir $(CROSS_COMPILE:%-=%))
>  GCC_TOOLCHAIN_DIR := $(dir $(shell which $(CROSS_COMPILE)elfedit))
> -CLANG_FLAGS    += --prefix=$(GCC_TOOLCHAIN_DIR)
> +CLANG_FLAGS    += --prefix=$(GCC_TOOLCHAIN_DIR)/$(CROSS_COMPILE)
> ```

I think this should work. I'd remove `/` before `$(CROSS_COMPILE)`. Tested with the commit before llvm/llvm-project@3452a0d8c17f7166f479706b293caf6ac76ffd90 and after.

**Comment by dileks** [comment]
I am using currently `release/11.x`Git, so I cannot say much to the issue as it affects  `ToT` (which means in German `dead`).

Still confused by the term `triple` - it is not a triple in the LLVM world - it is a `quadruple`.

Just speaking for Debian - which uses a real `triple` - and let you know for a Debian AMD64 system (see especially `*_GNU_TYPE` and `*_MULTIARCH`):
```
# dpkg-architecture -l
DEB_BUILD_ARCH=amd64
DEB_BUILD_ARCH_ABI=base
DEB_BUILD_ARCH_BITS=64
DEB_BUILD_ARCH_CPU=amd64
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_LIBC=gnu
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=x86_64
DEB_BUILD_GNU_SYSTEM=linux-gnu
DEB_BUILD_GNU_TYPE=x86_64-linux-gnu
DEB_BUILD_MULTIARCH=x86_64-linux-gnu
DEB_HOST_ARCH=amd64
DEB_HOST_ARCH_ABI=base
DEB_HOST_ARCH_BITS=64
DEB_HOST_ARCH_CPU=amd64
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_LIBC=gnu
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=x86_64
DEB_HOST_GNU_SYSTEM=linux-gnu
DEB_HOST_GNU_TYPE=x86_64-linux-gnu
DEB_HOST_MULTIARCH=x86_64-linux-gnu
DEB_TARGET_ARCH=amd64
DEB_TARGET_ARCH_ABI=base
DEB_TARGET_ARCH_BITS=64
DEB_TARGET_ARCH_CPU=amd64
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_LIBC=gnu
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=x86_64
DEB_TARGET_GNU_SYSTEM=linux-gnu
DEB_TARGET_GNU_TYPE=x86_64-linux-gnu
DEB_TARGET_MULTIARCH=x86_64-linux-gnu
```
...as I see in my build-logs (reported as tc-build issue #92):
```
dpkg-architecture: warning: specified GNU system type x86_64-linux-gnu does not match CC system type x86_64-unknown-linux-gnu, try setting a correct CC environment variable
```

@MaskRay 
Can you please check this does respects the Debian and LLVM world?

[1] https://github.com/ClangBuiltLinux/tc-build/issues/92

**Comment by MaskRay** [comment]
@dileks config.guess does normalize aarch64-linux-gnu to aarch64-unknown-linux-gnu. However, aarch64-linux-gnu-gcc uses `aarch64-linux-gnu/` instead of `aarch64-unknown-linux-gnu/` or `aarch64-linux-gnu-` for its `exec_prefixes` (its mechanism searching for executables).

"Target triple" is indeed a bit of misnomer and in many cases they are quadruples. "triple" is the convention, though.

**Comment by dileks** [comment]
Hmm, LLVM world uses `cmake` as default (in my build it is the fact)?
You expect the usual `normalization` does the correct `exec_prefixes` handling for `cmake`, too?

**Comment by nathanchance** [comment]
@MaskRay I threw your patch through my build testing infrastructure and it appears to work fine for both `clang-11` and `clang-12` across all of our architectures. I know that @agners initially added the flag in https://github.com/torvalds/linux/commit/ef8c4ed9db80261f397f0c0bf723684601ae3b52, it might be worth making sure that it continues to work for him.

**Comment by MaskRay** [comment]
@dilekes Thanks, adopted your first suggested subject. [Sent patch](http://lore.kernel.org/r/20200720181237.3015826-1-maskray@google.com). Hope I did not do things wrongly... (It is one of my very few commits so far, you know...)

**Comment by MaskRay** [comment]
> Hmm, LLVM world uses `cmake` as default (in my build it is the fact)?
> You expect the usual `normalization` does the correct `exec_prefixes` handling for `cmake`, too?

Yes. An autoconf build system once existed but was removed long ago. CMake is now the canonical build system. Some folks use a secondary gn build (`llvm/utils/gn/`) but that is very uncommon.

> UPDATE: Normalization works as expected see above "warning:" line. Sorry for the noise.
> 
> ```
> $ dpkg-architecture --query DEB_TARGET_GNU_TYPE
> x86_64-linux-gnu
> 
> $ clang-11 -v
> clang version 11.0.0 (https://github.com/llvm/llvm-project a1f2fd11bde3efe2dd145163be1a7df15d0800d1)
> Target: x86_64-unknown-linux-gnu
> ...
> ```

For `--target=` (or `-target `), clang prefers `$target-$name`. If it cannot find it, a quite complex gcc-cross detection logic will take over. For example, `clang -target aarch64-linux-gnu- a.c '-###'` will pick `"/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld"`

**Comment by dileks** [comment]
@MaskRay 

Inspired by your `git send-email` line I updated our wiki :-).

[1] https://github.com/ClangBuiltLinux/linux/wiki/Command-line-tips-and-tricks > "Sending a patch to Linux upstream"

**Comment by dileks** [comment]
@MaskRay 

I have preferred the 2nd example for a subject-line but anyway it's a version 1 of your patch.

Hmm, `clang-11 -v` prints out the local `gcc --print-search-dirs`?
```
$ clang-11 -v
clang version 11.0.0 (https://github.com/llvm/llvm-project a1f2fd11bde3efe2dd145163be1a7df15d0800d1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/dileks/src/llvm-toolchain/install/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$ gcc --print-search-dirs
install: /usr/lib/gcc/x86_64-linux-gnu/9/
programs: =/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/bin/
libraries: =/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/:/lib/x86_64-linux-gnu/9/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/9/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../:/lib/:/usr/lib/
```

As said I am not using cross-compilation so I cannot say much.

**Comment by nickdesaulniers** [comment]
> As said I am not using cross-compilation so I cannot say much.

The change in LLVM should only affect cross compiles of the Linux kernel.

**Comment by dileks** [comment]
Submitted patch see [1].

[1] https://lore.kernel.org/patchwork/patch/1276716/

**Comment by MaskRay** [comment]
Submitted PATCH v2: https://lore.kernel.org/patchwork/patch/1276826/

**Comment by dileks** [comment]
@MaskRay 
Just finished a new Linux-kernel build - with the next run I will test v2.

**Comment by nathanchance** [comment]
v3: https://lore.kernel.org/lkml/20200721173125.1273884-1-maskray@google.com/

**Comment by dileks** [comment]
Adapted patch from @masahir0y now in <kbuild.git#fixes>:

[1] https://git.kernel.org/pub/scm/linux/kernel/git/masahiroy/linux-kbuild.git/commit/?h=fixes&id=5987cd8120da33c0c19beb1acae382e2937771b9

**Comment by nathanchance** [comment]
We will also need the same thing in `arch/arm64/kernel/vdso32/Makefile`:

```diff
diff --git a/arch/arm64/kernel/vdso32/Makefile b/arch/arm64/kernel/vdso32/Makefile
index d88148bef6b0..5139a5f19256 100644
--- a/arch/arm64/kernel/vdso32/Makefile
+++ b/arch/arm64/kernel/vdso32/Makefile
@@ -14,7 +14,7 @@ COMPAT_GCC_TOOLCHAIN_DIR := $(dir $(shell which $(CROSS_COMPILE_COMPAT)elfedit))
 COMPAT_GCC_TOOLCHAIN := $(realpath $(COMPAT_GCC_TOOLCHAIN_DIR)/..)

 CC_COMPAT_CLANG_FLAGS := --target=$(notdir $(CROSS_COMPILE_COMPAT:%-=%))
-CC_COMPAT_CLANG_FLAGS += --prefix=$(COMPAT_GCC_TOOLCHAIN_DIR)
+CC_COMPAT_CLANG_FLAGS += --prefix=$(COMPAT_GCC_TOOLCHAIN_DIR)$(notdir $(CROSS_COMPILE_COMPAT))
 CC_COMPAT_CLANG_FLAGS += -no-integrated-as -Qunused-arguments
 ifneq ($(COMPAT_GCC_TOOLCHAIN),)
 CC_COMPAT_CLANG_FLAGS += --gcc-toolchain=$(COMPAT_GCC_TOOLCHAIN)
```

I can send that along later (or someone else can) or we could try to get it squashed into the first patch.

**Comment by dileks** [comment]
Yeah, that is another location using `--prefix` together with `CROSS_COMPILE`.

**Comment by nathanchance** [comment]
vdso32 patch submitted: https://lore.kernel.org/r/20200723041509.400450-1-natechancellor@gmail.com

**Comment by nathanchance** [comment]
vdso32 patch accepted: https://git.kernel.org/arm64/c/7b7891c7bdfd

**Comment by nathanchance** [comment]
vdso32 patch in mainline now: https://git.kernel.org/linus/7b7891c7bdfd61fc9ed6747a0a05efe2394dddc6

**Comment by nathanchance** [comment]
Both patches are now in Linus' tree (and looks like they are getting picked by custom downstream Android kernels).

https://git.kernel.org/linus/7b7891c7bdfd61fc9ed6747a0a05efe2394dddc6
https://git.kernel.org/linus/ca9b31f6bb9c6aa9b4e5f0792f39a97bbffb8c51

They should get automatically backported to stable due to the CC tag.
