### ISSUE TITLE
Labels in patches sent to Linux upstream

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/linux#1100]
While talking about labels here in the CBL issue tracker I had in mind how to label patches sent to LKML?

One example which comes to my mind is a label with topic `(Clang's) Integrated Assembler`:
```
crypto: aesni - Fix build with LLVM_IAS=1
crypto: aesni - add compatibility with IAS
x86: crypto: fix building crc32c with clang ias
```
Is there a `netiquette` (to follow)?

Normally, I check with `git log --oneline /path/to/file` and/or together with grepping to have an orientation.

**Comment by nickdesaulniers** [comment]
I like `LLVM_IAS=1`.  `IAS` doesn't say much about who's integrated assembler we're referring to.

Definitely a bikeshed though.

**Comment by dileks** [comment]
Personally, I like `LLVM_IAS=1` in the patch subject-line and used it as it fits best and follows `llvm.rst` kernel-doc.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/kbuild/llvm.rst#n62
