### ISSUE TITLE
./include/linux/cgroup-defs.h:452:16: error: field 'cgrp' with variable sized type 'struct cgroup' not at the end of a struct or class is a GNU extension

### ISSUE THREAD

**Issue by gwelymernans** [ClangBuiltLinux/linux#1101]
I'm seeing this again on arm64. When I add `-Wno-gnu-variable-sized-type-not-at-end`, it compiles. I know this has been reported before, but I haven't seen a fix for ARM.

Note, this is an older version of the kernel (4.15).

```
In file included from arch/arm64/kernel/asm-offsets.c:24:
In file included from ./include/linux/kvm_host.h:38:
In file included from ./arch/arm64/include/asm/kvm_host.h:40:
In file included from ./include/kvm/arm_pmu.h:21:
In file included from ./include/linux/perf_event.h:56:
In file included from ./include/linux/cgroup.h:28:
./include/linux/cgroup-defs.h:452:16: error: field 'cgrp' with variable sized type 'struct cgroup' not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end]
        struct cgroup cgrp;
                      ^
1 error generated.
```

**Comment by nickdesaulniers** [comment]
see also #113 .
https://github.com/ClangBuiltLinux/linux/issues/113#issuecomment-490772149 ?

**Comment by gwelymernans** [comment]
I'm not so sure that the solution listed there is the correct one. It seems like a lot of flags aren't being passed back to `arch/arm64/kernel`. When I compile the upstream kernel, the "missing" flags are there (e.g. -Qunused-arguments). And when I build the same file for other architectures those flags appear. So something in arm64 is trouncing on the flags, and it was fixed for upstream, but I don't know which fix to backport.

**Comment by gwelymernans** [comment]
This has to do with the toolchain we're using. The compiler is using the x86 assembler for some reason, so the arm-specific flags that are passed in won't be added.

**Comment by nickdesaulniers** [comment]
Your toolchain might not yet be affected by #1099 , but in the event that it is, there's a kernel patch for that, too.
