### ISSUE TITLE
LTO causes issues with arm64 KVM's new HYPCOPY rule

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1105]
As @willdeacon mentioned in #1096, the `__hyp_text` section annotation is gone and they use an invocation with `$(OBJCOPY)` to do the sectioning now: https://git.kernel.org/maz/arm-platforms/c/c50cb04303cb88c517715b078e3e010c024af1a5

As it turns out, this somehow causes issues with LTO (I assume because it is LLVM bitcode at first?). I was attempting to test SCS + LTO + CFI on my Raspberry Pi on -next and I ran into this. Easy way to reproduce:

```
$ git clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/

$ cd linux

$ git pull --no-edit https://git.kernel.org/pub/scm/linux/kernel/git/maz/arm-platforms.git kvm-arm64/next-5.9

$ git pull --no-edit https://github.com/samitolvanen/linux clang-lto

$ scripts/config --file arch/arm64/configs/defconfig -e LTO_CLANG

$ make -skj"$(nproc)" ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 O=out distclean defconfig arch/arm64/kvm/hyp/nvhe/
llvm-objcopy: error: 'arch/arm64/kvm/hyp/nvhe/timer-sr.hyp.tmp.o': The file was not recognized as a valid object file
make[6]: *** [../arch/arm64/kvm/hyp/nvhe/Makefile:21: arch/arm64/kvm/hyp/nvhe/timer-sr.hyp.o] Error 1
llvm-objcopy: error: 'arch/arm64/kvm/hyp/nvhe/sysreg-sr.hyp.tmp.o': The file was not recognized as a valid object file
make[6]: *** [../arch/arm64/kvm/hyp/nvhe/Makefile:21: arch/arm64/kvm/hyp/nvhe/sysreg-sr.hyp.o] Error 1
llvm-objcopy: error: 'arch/arm64/kvm/hyp/nvhe/../vgic-v2-cpuif-proxy.hyp.tmp.o': The file was not recognized as a valid object file
make[6]: *** [../arch/arm64/kvm/hyp/nvhe/Makefile:21: arch/arm64/kvm/hyp/nvhe/../vgic-v2-cpuif-proxy.hyp.o] Error 1
llvm-objcopy: error: 'arch/arm64/kvm/hyp/nvhe/tlb.hyp.tmp.o': The file was not recognized as a valid object file
make[6]: *** [../arch/arm64/kvm/hyp/nvhe/Makefile:21: arch/arm64/kvm/hyp/nvhe/tlb.hyp.o] Error 1
llvm-objcopy: error: 'arch/arm64/kvm/hyp/nvhe/../aarch32.hyp.tmp.o': The file was not recognized as a valid object file
make[6]: *** [../arch/arm64/kvm/hyp/nvhe/Makefile:21: arch/arm64/kvm/hyp/nvhe/../aarch32.hyp.o] Error 1
llvm-objcopy: error: 'arch/arm64/kvm/hyp/nvhe/debug-sr.hyp.tmp.o': The file was not recognized as a valid object file
make[6]: *** [../arch/arm64/kvm/hyp/nvhe/Makefile:21: arch/arm64/kvm/hyp/nvhe/debug-sr.hyp.o] Error 1
llvm-objcopy: error: 'arch/arm64/kvm/hyp/nvhe/switch.hyp.tmp.o': The file was not recognized as a valid object file
make[6]: *** [../arch/arm64/kvm/hyp/nvhe/Makefile:21: arch/arm64/kvm/hyp/nvhe/switch.hyp.o] Error 1
llvm-objcopy: error: 'arch/arm64/kvm/hyp/nvhe/../vgic-v3-sr.hyp.tmp.o': The file was not recognized as a valid object file
make[6]: *** [../arch/arm64/kvm/hyp/nvhe/Makefile:21: arch/arm64/kvm/hyp/nvhe/../vgic-v3-sr.hyp.o] Error 1
...
```

cc @samitolvanen

**Comment by samitolvanen** [comment]
I think filtering out `$(CC_FLAGS_LTO)` as well should fix this.

**Comment by nathanchance** [comment]
Yes, it does! I see a new error related to the integrated assembler after this, which I will file a new issue for.

**Comment by davidbrazdil** [comment]
Hey, I'm the author of that HYPCOPY command. Filtering out the CFLAGS works but would you be interested in doing LTO on this code too? It would have to be only between the files of this folder though as this code runs in a different address space from the rest of the kernel.

1) compile nvhe/*.c to LLVM IR
2) link nvhe/*.o with LTO, produce relocatable ELF
3) rename sections, prefix symbols with objcopy, producing another ELF
4) link ELF into vmlinux

I've attached a patch that does this. Compiles with LTO_CLANG. Haven't tried booting/testing it.

[nvhe-lto.patch.txt](https://github.com/ClangBuiltLinux/linux/files/4977605/nvhe-lto.patch.txt)

**Comment by nathanchance** [comment]
@davidbrazdil thanks! I went ahead and tried testing it on my Raspberry Pi 4 but it unfortunately does not boot. In fact, I do not see output on my serial console so it is getting stuck pretty early in the boot process (or it is panicking before the serial driver loads...?)

**Comment by samitolvanen** [comment]
We could use a linker script to merge the `.text.*` sections before running `objcopy`, similarly to `scripts/module-lto.lds.S`, which we use for modules.

**Comment by samitolvanen** [comment]
This landed in Linus' tree and I [updated my patch set](https://github.com/samitolvanen/linux/commit/4bc0e0e4993ba950b9712d59140f3c8a9e9f6518) to disable LTO for the nVHE code. I'm not sure if using LTO here is beneficial, but we can always revisit this later if needed.

**Comment by nickdesaulniers** [comment]
@samitolvanen what landed in Linus' tree for which tag?

**Comment by samitolvanen** [comment]
Commit 7621712918ad4f5e6356193d9058debf657a6254, which added the HYPCOPY rule.
