### ISSUE TITLE
error: TLBI RVALE1IS requires tlb-rmi with LLVM_IAS=1

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1106]
```
arch/arm64/include/asm/tlbflush.h:346:5: error: TLBI RVALE1IS requires tlb-rmi
                                __tlbi(rvale1is, addr);
                                ^
arch/arm64/include/asm/tlbflush.h:47:26: note: expanded from macro '__tlbi'
#define __tlbi(op, ...)         __TLBI_N(op, ##__VA_ARGS__, 1, 0)
                                ^
arch/arm64/include/asm/tlbflush.h:45:35: note: expanded from macro '__TLBI_N'
#define __TLBI_N(op, arg, n, ...) __TLBI_##n(op, arg)
                                  ^
<scratch space>:21:1: note: expanded from here
__TLBI_1
^
arch/arm64/include/asm/tlbflush.h:38:32: note: expanded from macro '__TLBI_1'
#define __TLBI_1(op, arg) asm ("tlbi " #op ", %0\n"                            \
                               ^
<inline asm>:1:7: note: instantiated into assembly here
        tlbi rvale1is, x1
             ^
```

Introduced by https://git.kernel.org/arm64/c/d1d3aa98b1d4826a19adfefb69b96142a0cac633.

To reproduce:

```
$ git clone https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/

$ cd linux-next

$ git revert --no-edit f7b93d42945cc71e1346dd5ae07c59061d56745e

$ make -skj"$(nproc)" ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1 O=out/arm64 distclean defconfig mm/mprotect.o
```

**Comment by nathanchance** [comment]
It looks like this is an ARMv8.4-A extension and requires `.arch_extension tlb-rmi`?

https://github.com/llvm/llvm-project/blob/22c16360dd00230987fee5f6f3c57f8071144cc1/llvm/lib/Target/AArch64/AArch64.td#L315-L317

https://github.com/llvm/llvm-project/blob/22c16360dd00230987fee5f6f3c57f8071144cc1/llvm/test/MC/AArch64/directive-arch_extension.s#L51

**Comment by nickdesaulniers** [comment]
The inline asm likely needs the directive (rather than a global asm statement which wont get merged or none at all and no command line flag to set the target arch).

**Comment by nathanchance** [comment]
This works, would it be acceptable?

```diff
diff --git a/arch/arm64/include/asm/tlbflush.h b/arch/arm64/include/asm/tlbflush.h
index d493174415db..fbdbe24af4cb 100644
--- a/arch/arm64/include/asm/tlbflush.h
+++ b/arch/arm64/include/asm/tlbflush.h
@@ -28,14 +28,16 @@
  * not. The macros handles invoking the asm with or without the
  * register argument as appropriate.
  */
-#define __TLBI_0(op, arg) asm ("tlbi " #op "\n"                                       \
+#define __TLBI_0(op, arg) asm (".arch_extension tlb-rmi\n"                    \
+                              "tlbi " #op "\n"                                \
                   ALTERNATIVE("nop\n                   nop",                  \
                               "dsb ish\n               tlbi " #op,            \
                               ARM64_WORKAROUND_REPEAT_TLBI,                   \
                               CONFIG_ARM64_WORKAROUND_REPEAT_TLBI)            \
                            : : )

-#define __TLBI_1(op, arg) asm ("tlbi " #op ", %0\n"                           \
+#define __TLBI_1(op, arg) asm (".arch_extension tlb-rmi\n"                    \
+                              "tlbi " #op ", %0\n"                            \
                   ALTERNATIVE("nop\n                   nop",                  \
                               "dsb ish\n               tlbi " #op ", %0",     \
                               ARM64_WORKAROUND_REPEAT_TLBI,                   \
```

**Comment by nathanchance** [comment]
Actually, this should work due to https://git.kernel.org/arm64/c/7c78f67e9bd97478d56157c2ad53823668b5b822. However, I think there is something funky with `-march=` getting passed down to the assembler via the `-Wa,-march=` flag.

```
$ cat test.c
void foo(void) {
        asm("tlbi vmalle1os");
}

$ clang --target=aarch64-linux-gnu -march=armv8.4-a -c -o /dev/null test.c

$ clang --target=aarch64-linux-gnu -Wa,-march=armv8.4-a -c -o /dev/null test.c
<inline asm>:1:7: error: TLBI VMALLE1OS requires tlb-rmi
        tlbi vmalle1os
             ^
1 error generated.

$ clang --target=aarch64-linux-gnu -no-integrated-as --prefix=${CBL_BNTL}/aarch64-linux-gnu- -march=armv8.4-a -c -o /dev/null test.c

$ clang --target=aarch64-linux-gnu -no-integrated-as --prefix=${CBL_BNTL}/aarch64-linux-gnu- -Wa,-march=armv8.4-a -c -o /dev/null test.c
```

I feel like we have run into this before? I cannot remember or find it though.

**Comment by samitolvanen** [comment]
> I think there is something funky with -march= getting passed down to the assembler via the -Wa,-march= flag.
 
`-Wa` is only passed to an external assembler, it's ignored with IAS, which uses the `-march` passed to clang instead. Otherwise, we could pass an appropriate `-march` to IAS and work around issue #1078 too...

**Comment by nathanchance** [comment]
Is there any reason not to pass `-march=armv8.4-a` always or should it only be done when using the integrated assembler? If the later, do we want to add some new Kconfig symbol like `AS_IS_LLVM` or `AS_IS_CLANG` which could be true if `LTO_CLANG` is set or `LLVM_IAS=1`?

**Comment by samitolvanen** [comment]
> Is there any reason not to pass `-march=armv8.4-a` always or should it only be done when using the integrated assembler?

If we pass `-march=armv8.4-a` to the compiler, it might generate instructions that are not supported on older hardware. Typically in inline assembly these are wrapped in alternative macros, where the instructions are patched in at runtime only if the hardware supports them. However, passing the `-march` to the assembler only is fine.

**Comment by nathanchance** [comment]
Maybe we should add the `.arch_extension` if `CONFIG_CC_IS_CLANG` or is that too dirty/hacky?

**Comment by samitolvanen** [comment]
Does GNU assembler understand `.arch_extension tlb-rmi`? If it does, I think your earlier patch looked fine. Maybe we can even remove the unnecessary `-Wa,-march=archv8.4-a` at the same time?

**Comment by nickdesaulniers** [comment]
> Maybe we should add the .arch_extension if CONFIG_CC_IS_CLANG or is that too dirty/hacky?

No. We've sent patches for this in the past that have added the assembler directive unconditionally. See also:
* 2cbd1cc3dcd3e84be1fc1987da24b190ddf24a70
* a6c30873ee4a5cc0549c1973668156381ab2c1c4
* dd1f6308b28edf0452dd5dc7877992903ec61e69

> Does GNU assembler understand .arch_extension tlb-rmi?

My local copy of 2.34 doesn't seem to:
```asm
.arch armv8.4-a+crc
.text
.globl foo
foo:
.arch_extension tlb-rmi
    tlbi vmalle1os
```
```sh
$ aarch64-linux-gnu-as x.s
x.s: Assembler messages:
x.s:5: Error: unknown architectural extension `tlb-rmi'
```
Probably need to file a bug there.  (cc @kbeyls as a heads up for ARMs GNU binutils folks).

**Comment by samitolvanen** [comment]
> My local copy of 2.34 doesn't seem to

OK, we need to work around this some other way in that case.

One option would be to autodetect whether `.arch_extension tlb-rmi` works in inline assembly (similarly to `cc_has_k_constraint` in `arch/arm64/Makefile`) and do something like this in the header:
```c
#ifdef CONFIG_CC_AS_HAS_TLBRMI
#define __TLBRMI_PREAMBLE ".arch_extension tlb-rmi"
#else
#define __TLBRMI_PREAMBLE 
#endif
...
define __TLBI_0(op, arg) asm (__TLBRMI_PREAMBLE "\n"
...
```
Not exactly ideal, but it should work with GNU as and IAS.

**Comment by nathanchance** [comment]
> > My local copy of 2.34 doesn't seem to
> 
> OK, we need to work around this some other way in that case.
> 
> One option would be to autodetect whether `.arch_extension tlb-rmi` works in inline assembly (similarly to `cc_has_k_constraint` in `arch/arm64/Makefile`) and do something like this in the header:
> 
> ```c
> #ifdef CONFIG_CC_AS_HAS_TLBRMI
> #define __TLBRMI_PREAMBLE ".arch_extension tlb-rmi"
> #else
> #define __TLBRMI_PREAMBLE 
> #endif
> ...
> define __TLBI_0(op, arg) asm (__TLBRMI_PREAMBLE "\n"
> ...
> ```
> 
> Not exactly ideal, but it should work with GNU as and IAS.

Yes, this was what I had in mind. I will try to test it tonight.

I am not sure that we really have any other option with the current code:

1. `-Wa,-march=` does not work with the integrated assembler.

2. `-march=` to `$(CC)` is invalid as it could break older CPUs.

3. binutils does not appear to support `.arch_extension tlb-rmi`, which means that we can only use it conditionally.

Are there any other alternatives?

**Comment by nathanchance** [comment]
For what it's worth, that patch sort of works. However, it falls apart when using `LLVM_IAS=0` and LTO is disabled for a certain translation unit (or units), such as working around #1105.

**Comment by samitolvanen** [comment]
> it falls apart when using `LLVM_IAS=0` and LTO is disabled for a certain translation unit (or units)

Right. I suppose we could filter out `-no-integrated-as` from `KBUILD_CFLAGS` in this case (in addition to `CC_FLAGS_LTO`) to avoid using two different assemblers for inline assembly. I would rather not use IAS for stand-alone assembly with LTO by default to avoid making the build even more brittle than it is now.

**Comment by samitolvanen** [comment]
> Are there any other alternatives?

Using `.arch armv8.4-a` instead of `.arch_extension tlb-rmi` might work for both GNU as and IAS. Since this overrides the `-Wa,-march` parameter, it might need to be updated later if the kernel decides to use even newer instructions, especially since with gcc this might apply to all inline assembly in the translation unit.

**Comment by nathanchance** [comment]
`.arch armv8.4-a` does indeed work.

**Comment by samitolvanen** [comment]
> `.arch armv8.4-a` does indeed work.

Great, thank you for testing! Do you want to send a patch upstream, so we can see if the maintainers are fine with this approach?

**Comment by nathanchance** [comment]
Sure, I will draft up a commit message and send it along.

**Comment by nathanchance** [comment]
Unfortunately, `.arch armv8.4-a` does not work with older versions of binutils:

```
/tmp/ccDAfphj.s: Assembler messages:
/tmp/ccDAfphj.s:1801: Error: unknown architecture `armv8.4-a'

/tmp/ccDAfphj.s:2128: Error: unknown architecture `armv8.4-a'

/tmp/ccDAfphj.s:2262: Error: unknown architecture `armv8.4-a'

/tmp/ccDAfphj.s:2366: Error: unknown architecture `armv8.4-a'
```

I think the real solution here is to get `.arch_extension tlb-rmi` supported in binutils then use that when the assembler supports it, maybe falling back to `.arch armv8.4-a` if not to cover needing both GNU as and the integrated assembler within the same build.

**Comment by samitolvanen** [comment]
Which binutils version doesn't support the `.arch`? Does the `-march` parameter still work with it?

**Comment by nathanchance** [comment]
According to the help text, anything earlier than 2.30 will not support it: https://git.kernel.org/arm64/c/7c78f67e9bd97478d56157c2ad53823668b5b822

No, `-march=` will not work but that prevent the option from even being selected.

**Comment by samitolvanen** [comment]
> No, `-march=` will not work but that prevent the option from even being selected.

OK, so maybe we could also use the `.arch` directive only when the option is selected? That would fix the issue with old binutils, right?

In the long term, getting newer versions of binutils to support `.arch_extension tlb-rmi` would obviously be better, but we still have to support existing versions as well.

**Comment by nathanchance** [comment]
I will see if I can test that within the new few days. Sorry, drowning a bit with school and work sapping the energy out of me.

**Comment by samitolvanen** [comment]
Sure, no worries. We could possibly even change `$(cc-option,-Wa$(comma)-march=armv8.4-a)` to `$(as-instr,.arch armv8.4-a)`, but I'm not sure if that's needed.

**Comment by nickdesaulniers** [comment]
Maybe a Kconfig `as-instr` check is more appropriate for detecting tooling support?

**Comment by samitolvanen** [comment]
This is now in Linus' tree. I worked around it for now with commit 4ea7d40603a0d1b5e39e50d8159958929e12deb4. Thoughts?

> Maybe a Kconfig `as-instr` check is more appropriate for detecting tooling support?

Looking at `arch/arm64/Kconfig`, they also use a `-Wa,-march` check for `AS_HAS_PAC`, so I decided to keep it unchanged for now.

**Comment by nathanchance** [comment]
That is probably worth sending just to see what upstream thinks.

**Comment by samitolvanen** [comment]
https://lore.kernel.org/lkml/20200805181920.4013059-1-samitolvanen@google.com/

**Comment by nickdesaulniers** [comment]
Filed binutils bug: https://sourceware.org/bugzilla/show_bug.cgi?id=26339

**Comment by eillon** [comment]
> If we pass `-march=armv8.4-a` to the compiler, it might generate instructions that are not supported on older hardware. 

No need to worry about this because this feature is only enabled when the machine supports ARMv8.4:
```
static inline bool system_supports_tlb_range(void)
{
       return IS_ENABLED(CONFIG_ARM64_TLB_RANGE) &&
               cpus_have_const_cap(ARM64_HAS_TLB_RANGE);
}
```
Even if some 'newer' instructions are generated, they will never be used on older hardware.

**Comment by samitolvanen** [comment]
> > If we pass `-march=armv8.4-a` to the compiler, it might generate instructions that are not supported on older hardware.
> 
> No need to worry about this because this feature is only enabled when the machine supports ARMv8.4:

Sure, this feature won't be enabled, but as Catalin pointed out in the LKML thread, if we pass `-march=armv8.4-a` to the compiler, it could theoretically generate newer instructions elsewhere, which means the binary might no longer boot on older hardware.

**Comment by samitolvanen** [comment]
https://git.kernel.org/arm64/c/1764c3edc668

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/1764c3edc66880778604f5053fe2dda7b3ddd2c1
