### ISSUE TITLE
Make compile issue

### ISSUE THREAD

**Issue by allenfickle** [ClangBuiltLinux/linux#1111]
- running this on Ubuntu 18.04.3 VM
- using the linux 4.9.139 kernel source
- the script I run:

make O=out ARCH=arm64 defconfig
PATH=$HOME/arm-linux-androideabi-4.9/bin:$HOME/aarch64-linux-android-4.9/bin:$HOME/arm-linux-androideabi-4.9/bin:$HOME/Documents/android-10.0.0_r3-clang/bin:${PATH} 
make -j$(nproc --all) O=out \
                      ARCH=arm64 \
                      CC=clang \
                      CLANG_TRIPLE=aarch64-linux-gnu- \
                      CROSS_COMPILE=aarch64-linux-android- \
                      CROSS_COMPILE_ARM32=arm-linux-androideabi-

- Error messages I get:
<img width="854" alt="Screen Shot 2020-07-28 at 1 52 47 PM" src="https://user-images.githubusercontent.com/47254212/88720383-a0a6fb80-d0d9-11ea-93ef-1762a893f834.png">

**Comment by nickdesaulniers** [comment]
> using the linux 4.9.139 kernel source

If you're building stable tree's linux-4.9.y branch, then you should follow the [directions from the wiki](https://github.com/ClangBuiltLinux/linux/wiki/Steps-for-compiling-the-kernel-with-Clang#cross-compiling). Note the lack of `CLANG_TRIPLE` since Android renames their binutils binaries.  Can you clarify which tree you're building?

**Comment by allenfickle** [comment]
> > using the linux 4.9.139 kernel source
> 
> If you're building stable tree's linux-4.9.y branch, then you should follow the [directions from the wiki](https://github.com/ClangBuiltLinux/linux/wiki/Steps-for-compiling-the-kernel-with-Clang#cross-compiling). Note the lack of `CLANG_TRIPLE` since Android renames their binutils binaries. Can you clarify which tree you're building?


I'm not sure which tree I'm building - how can I find this out?  Also, I ran sudo apt install binutils-aarch64-linux-gnu and that resolved the issue!  Now that I've compiled my kernel and got a image.gz in my boot folder, do you know how I can create a virtual emulator with this?

**Comment by nickdesaulniers** [comment]
> I'm not sure which tree I'm building - how can I find this out?

Where did you `git clone` it from? If you `cd` into your kernel tree then run `git remote -vv` it should give you the URL.

> do you know how I can create a virtual emulator with this?

We have another repo we use for virtualized testing; I use it frequently to debug with GDB: https://github.com/ClangBuiltLinux/boot-utils.  That runs your kernel in QEMU with `-nographic`; if you're looking to have a graphical environment, you could play with removing that flag and adding other command line params to QEMU.  We'd accept patches for adding such a feature flag.  For instance, to fire up a debian env on a given kernel might be nice.

**Comment by nickdesaulniers** [comment]
Please reopen with the requested info if you can reproduce. Thank you for taking the time to file a bug.
