### ISSUE TITLE
LLVM MC accepted at plumbers

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1113]
* [Blog announcement](https://www.linuxplumbersconf.org/blog/2020/llvm-microconference-accepted-into-2020-linux-plumbers-conference/)
* [List of accepted MCs](https://www.linuxplumbersconf.org/event/7/page/80-accepted-microconferences)

Get your tickets [here](https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fwww.linuxplumbersconf.org%2Fevent%2F7%2Fpage%2F47-attend).

**Comment by gwelymernans** [comment]
WOO!

**Comment by dileks** [comment]
If you did not know: https://planet.kernel.org/

**Comment by nickdesaulniers** [comment]
We will also be having a BoF session.  Looks like Monday for BoF, Thursday for MC.  MC starts 7am PDT. [tentative]

**Comment by nathanchance** [comment]
Came and went successfully :) Many thanks to @nickdesaulniers and @behanw for organizing it! I have updated the wiki with a link to the live stream on YouTube, a link to the repo with the slides, and the schedule.

**Comment by gwelymernans** [comment]
+1! This went very smoothly. Thank you both so much for all!
