### ISSUE TITLE
unused function 'of_bus_pci_get_flags'

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1115]
allnoconfig arm/arm64 linux-next:
```
    /scratch/linux/drivers/of/address.c:104:21: warning: unused function 'of_bus_pci_get_flags' [-Wunused-function]

```
via kernelci

**Comment by nathanchance** [comment]
https://lore.kernel.org/lkml/20200730005614.32302-1-jiaxun.yang@flygoat.com/

https://lore.kernel.org/lkml/20200731154539.GA16683@alpha.franken.de/

**Comment by nickdesaulniers** [comment]
@nathanchance I guess this is fixed then or did this regress into mainline?

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/linus/0fc0ead3488836503573286bcaa56f9743ea2bcc
