### ISSUE TITLE
[PATCH] RAS/CEC: Fix cec_init prototype

### ISSUE THREAD

**Issue by luca020400** [ClangBuiltLinux/linux#1119]
V1: https://lore.kernel.org/patchwork/patch/1284125/
V2: https://lore.kernel.org/patchwork/patch/1284438/

Fixes x86_64 5.8 build with ThinLTO

**Comment by nickdesaulniers** [comment]
Link to v2?

**Comment by luca020400** [comment]
https://lore.kernel.org/patchwork/patch/1284438/

**Comment by luca020400** [comment]
Fixed https://git.kernel.org/tip/71aefb9a89d4ad751726ff5b902896c35c7df5b9

**Comment by nickdesaulniers** [comment]
if this was a bug that wasn't a regression in linux-next, would you mind keeping this bug open to track which tagged version of linux the fix ultimately lands in? We've been using the fixed -next tag for fixing regressions in -next before they hit mainline.  I suspect mainline was broken.

**Comment by nickdesaulniers** [comment]
85e6084e0b436cabe9c909e679937998ffbf9c9d
