### ISSUE TITLE
ERROR: modpost: "__force_order" [drivers/misc/lkdtm/lkdtm.ko] undefined!

### ISSUE THREAD

**Issue by luca020400** [ClangBuiltLinux/linux#1120]
While building with CLANG 10 and 5.8 with the backported LTO targeting 5.9 we hit this error during modpost

Related: https://github.com/ClangBuiltLinux/linux/issues/1104#issuecomment-667470053
Supposed fix: https://lore.kernel.org/patchwork/patch/1248382/

cc: @samitolvanen

**Comment by luca020400** [comment]
Setting CONFIG_LKDTM=m is enough to trigger the error

**Comment by samitolvanen** [comment]
Do you see the same error with ToT Clang?

**Comment by luca020400** [comment]
Seems like the error isn't deterministic, I can't repro on a 2nd run.
I'll try a few more times.

When I can repro it I'll switch to ToT

**Comment by samitolvanen** [comment]
> Seems like the error isn't deterministic, I can't repro on a 2nd run.

That's unexpected. Did you run make mrproper between the builds?

**Comment by nickdesaulniers** [comment]
I've asked @pcc why `-faddrsig` leaves behind an undefined symbol reference and whether or not that's expected.  Though don't symbols have to be `EXPORT`ed before they can be used from kernel modules?

**Comment by luca020400** [comment]
> > Seems like the error isn't deterministic, I can't repro on a 2nd run.
> 
> That's unexpected. Did you run make mrproper between the builds?

make LLVM=1 clean mrproper
zcat /proc/config.gz > .config
make LLVM=1 oldconfig # Enable ThinLTO
make LLVM=1 modules_prepare
make LLVM=1 M=drivers/misc/lkdtm

I'll try a "full" build again to see if I can trigger it this way.

**Comment by luca020400** [comment]
Ok apparently building the module alone isn't enough. So it's likely related to modversions that applies only when a full build is executed.

Will try ToT

**Comment by pcc** [comment]
It's because of the fake references to `__force_order` in `special_insns.h`. Normally the compiler will skip these symbols when it sees that the symbol is unreferenced, but it can't look inside the inline asm, so the symbol gets emitted. An undefined symbol without any relocations pointing to it is almost always harmless, unless you're doing something like reading the object file directly, as this kernel tool apparently does.

The fix on the kernel thread (change the variable to static) seems like it will work. I'm not sure that the comment "Volatile isn't enough to prevent the compiler from reordering the read/write functions" is correct, but I'm not going to wade into that discussion.

**Comment by luca020400** [comment]
Ok same error on ToT
Simple re-pro
```
make LLVM=1 x86_64_defconfig
scripts/config -m LKDTM
make LLVM=1`

**Comment by dileks** [comment]
More comments from `Thomas Gleixner` (Linux/x86 maintainer).

[1] https://lore.kernel.org/patchwork/patch/1248382/

**Comment by samitolvanen** [comment]
As Peter pointed out, the undefined symbol is harmless and the issue here is that modpost is unhappy about it. While I wouldn't mind getting rid of the `__force_order` hack entirely, there's a trivial workaround that won't end up adding an unused variable to each module:
```diff
diff --git a/arch/x86/include/asm/special_insns.h b/arch/x86/include/asm/special_insns.h
index 59a3e13204c3..e1c19c5ecd5e 100644
--- a/arch/x86/include/asm/special_insns.h
+++ b/arch/x86/include/asm/special_insns.h
@@ -17,7 +17,7 @@
  * all loads stores around it, which can hurt performance. Solution is to
  * use a variable and mimic reads and writes to it to enforce serialization
  */
-extern unsigned long __force_order;
+extern unsigned long __force_order __weak;
 
 void native_write_cr0(unsigned long val);

```
This causes modpost to ignore the undefined symbol, which fixes the build, and the module appears to load and function normally:
```
# modprobe lkdtm
[  489.391323] lkdtm: No crash points registered, enable through debugfs
# echo CFI_FORWARD_PROTO > /sys/kernel/debug/provoke-crash/DIRECT 
[  502.580329] lkdtm: Performing direct entry CFI_FORWARD_PROTO
[  502.581655] lkdtm: Calling matched prototype ...
[  502.582690] lkdtm: Calling mismatched prototype ...
[  502.583742] ------------[ cut here ]------------
[  502.584661] CFI failure (target: lkdtm_increment_int+0x0/0x10 [lkdtm]):
[  502.586169] WARNING: CPU: 3 PID: 125 at kernel/cfi.c:30 __ubsan_handle_cfi_check_fail+0x2e/0x40
...
```

**Comment by dileks** [comment]
In a first run, I was able to build with `gcc-10 v10.2` and `GNU/ld v2.35`, boot on bare metal with the proposed diff from @nickdesaulniers and start FreeDOS 1.2 VM in VirtualBox GUI (details see https://github.com/ClangBuiltLinux/linux/issues/1104).

Here is the diff I adapted and applied on top of `Linux v5.8.1`:
```diff
---
 arch/x86/boot/compressed/pgtable_64.c |  9 ---------
 arch/x86/include/asm/special_insns.h  | 23 +++++++----------------
 arch/x86/kernel/cpu/common.c          |  2 +-
 3 files changed, 8 insertions(+), 26 deletions(-)

diff --git a/arch/x86/boot/compressed/pgtable_64.c b/arch/x86/boot/compressed/pgtable_64.c
index c8862696a47b..7d0394f4ebf9 100644
--- a/arch/x86/boot/compressed/pgtable_64.c
+++ b/arch/x86/boot/compressed/pgtable_64.c
@@ -5,15 +5,6 @@
 #include "pgtable.h"
 #include "../string.h"
 
-/*
- * __force_order is used by special_insns.h asm code to force instruction
- * serialization.
- *
- * It is not referenced from the code, but GCC < 5 with -fPIE would fail
- * due to an undefined symbol. Define it to make these ancient GCCs work.
- */
-unsigned long __force_order;
-
 #define BIOS_START_MIN         0x20000U        /* 128K, less than this is insane */
 #define BIOS_START_MAX         0x9f000U        /* 640K, absolute maximum */
 
diff --git a/arch/x86/include/asm/special_insns.h b/arch/x86/include/asm/special_insns.h
index eb8e781c4353..04c938890edd 100644
--- a/arch/x86/include/asm/special_insns.h
+++ b/arch/x86/include/asm/special_insns.h
@@ -10,46 +10,37 @@
 #include <linux/irqflags.h>
 #include <linux/jump_label.h>
 
-/*
- * Volatile isn't enough to prevent the compiler from reordering the
- * read/write functions for the control registers and messing everything up.
- * A memory clobber would solve the problem, but would prevent reordering of
- * all loads stores around it, which can hurt performance. Solution is to
- * use a variable and mimic reads and writes to it to enforce serialization
- */
-extern unsigned long __force_order;
-
 void native_write_cr0(unsigned long val);
 
 static inline unsigned long native_read_cr0(void)
 {
        unsigned long val;
-       asm volatile("mov %%cr0,%0\n\t" : "=r" (val), "=m" (__force_order));
+       asm volatile("mov %%cr0,%0\n\t" : "=r" (val));
        return val;
 }
 
 static __always_inline unsigned long native_read_cr2(void)
 {
        unsigned long val;
-       asm volatile("mov %%cr2,%0\n\t" : "=r" (val), "=m" (__force_order));
+       asm volatile("mov %%cr2,%0\n\t" : "=r" (val));
        return val;
 }
 
 static __always_inline void native_write_cr2(unsigned long val)
 {
-       asm volatile("mov %0,%%cr2": : "r" (val), "m" (__force_order));
+       asm volatile("mov %0,%%cr2": : "r" (val));
 }
 
 static inline unsigned long __native_read_cr3(void)
 {
        unsigned long val;
-       asm volatile("mov %%cr3,%0\n\t" : "=r" (val), "=m" (__force_order));
+       asm volatile("mov %%cr3,%0\n\t" : "=r" (val));
        return val;
 }
 
 static inline void native_write_cr3(unsigned long val)
 {
-       asm volatile("mov %0,%%cr3": : "r" (val), "m" (__force_order));
+       asm volatile("mov %0,%%cr3": : "r" (val));
 }
 
 static inline unsigned long native_read_cr4(void)
@@ -64,10 +55,10 @@ static inline unsigned long native_read_cr4(void)
        asm volatile("1: mov %%cr4, %0\n"
                     "2:\n"
                     _ASM_EXTABLE(1b, 2b)
-                    : "=r" (val), "=m" (__force_order) : "0" (0));
+                    : "=r" (val) : "0" (0));
 #else
        /* CR4 always exists on x86_64. */
-       asm volatile("mov %%cr4,%0\n\t" : "=r" (val), "=m" (__force_order));
+       asm volatile("mov %%cr4,%0\n\t" : "=r" (val));
 #endif
        return val;
 }
diff --git a/arch/x86/kernel/cpu/common.c b/arch/x86/kernel/cpu/common.c
index 95c090a45b4b..01d25b6c0a94 100644
--- a/arch/x86/kernel/cpu/common.c
+++ b/arch/x86/kernel/cpu/common.c
@@ -358,7 +358,7 @@ void native_write_cr0(unsigned long val)
        unsigned long bits_missing = 0;
 
 set_register:
-       asm volatile("mov %0,%%cr0": "+r" (val), "+m" (__force_order));
+       asm volatile("mov %0,%%cr0": "+r" (val));
 
        if (static_branch_likely(&cr_pinning)) {
                if (unlikely((val & X86_CR0_WP) != X86_CR0_WP)) {
-- 
2.28.0
```

**Comment by dileks** [comment]
In a 2nd run building with a selfmade `clang-11` and `LLVM "bin"utils` is fine, too.

**Comment by dileks** [comment]
@samitolvanen @pcc @nickdesaulniers 

With the diff from https://github.com/ClangBuiltLinux/linux/issues/1120#issuecomment-674182703 applied I see:

```
  ld.lld-11 -m elf_x86_64  -pie  --no-dynamic-linker -T arch/x86/boot/compressed/vmlinux.lds arch/x86/boot/compressed/kernel_info.o arch/x86/boot/compressed/head_64.o arch/x86/boot/compressed/misc.o arch/x86/boot/compressed/string.o arch/x86/boot/compressed/cmdline.o arch/x86/boot/compressed/error.o arch/x86/boot/compressed/piggy.o arch/x86/boot/compressed/cpuflags.o arch/x86/boot/compressed/early_serial_console.o arch/x86/boot/compressed/kaslr.o arch/x86/boot/compressed/kaslr_64.o arch/x86/boot/compressed/mem_encrypt.o arch/x86/boot/compressed/pgtable_64.o arch/x86/boot/compressed/acpi.o arch/x86/boot/compressed/efi_thunk_64.o drivers/firmware/efi/libstub/lib.a -o arch/x86/boot/compressed/vmlinux
ld.lld-11: error: Unexpected GOT entries detected!
ld.lld-11: error: Unexpected run-time relocations detected!
ld.lld-11: error: Unexpected GOT entries detected!
ld.lld-11: error: Unexpected run-time relocations detected!
make[5]: *** [arch/x86/boot/compressed/Makefile:91: arch/x86/boot/compressed/vmlinux] Error 1
```

NOTE: I have the patchset "x86/boot: Remove run-time relocations from compressed kernel" [1] in my series.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/log/?h=x86/boot

**Comment by dileks** [comment]
When I revert the changes from `x86/boot/compressed: Don't declare __force_order in kaslr_64.c`:

```diff
--- a/arch/x86/boot/compressed/kaslr_64.c
+++ b/arch/x86/boot/compressed/kaslr_64.c
@@ -29,6 +29,9 @@
 #define __PAGE_OFFSET __PAGE_OFFSET_BASE
 #include "../../mm/ident_map.c"
 
+/* Used by pgtable.h asm code to force instruction serialization. */
+unsigned long __force_order;
+
 /* Used to track our page table allocation area. */
 struct alloc_pgt_data {
        unsigned char *pgt_buf;
```

I am able to build with Sami's diff.

Without my above diff I see:
```
$ for o in acpi.o cmdline.o cpuflags.o early_serial_console.o efi_thunk_64.o error.o head_64.o kaslr_64.o kaslr.o kernel_info.o mem_encrypt.o misc.o pgtable_64.o piggy.o string.o ; do echo [ $o ] ; llvm-objdump -dr arch/x86/boot/compressed/$o | grep '\__force_order' ; done
[ acpi.o ]
[ cmdline.o ]
[ cpuflags.o ]
[ early_serial_console.o ]
[ efi_thunk_64.o ]
[ error.o ]
[ head_64.o ]
[ kaslr_64.o ]
                00000000000001b9:  R_X86_64_GOTPCREL    __force_order-0x4
                000000000000033a:  R_X86_64_GOTPCREL    __force_order-0x4
[ kaslr.o ]
[ kernel_info.o ]
[ mem_encrypt.o ]
[ misc.o ]
[ pgtable_64.o ]
[ piggy.o ]
[ string.o ]
```

[1] https://git.kernel.org/linus/df6d4f9db79c1a5d6f48b59db35ccd1e9ff9adfc

**Comment by dileks** [comment]
I was able to build with my selfmade LLVM toolchain and `make LLVM=1 LLVM_IAS=1`, boot on bare metal and start FreeDOS VM in VirtualBox.

**Comment by dileks** [comment]
Debian's GCC-10 and ld.bfd is fine.

**Comment by dileks** [comment]
So, Sami's diff [1] plus the `revert` of `x86/boot/compressed: Don't declare __force_order in kaslr_64.c` [2] works fine with the `patchset` of `x86/boot: Remove run-time relocations from compressed kernel` [3].

Both OK means build successfully out-of-kernel `VirtualBox kernel-modules` and start `FreeDOS 1.2 VM` [4] in VBox-GUI.

Toolchains:
1. Debian's `GCC v10.2` and `GNU/ld v2.35` (using binutils v2.35)
2. Selfmade `LLVM toolchain v11.0.0-rc1+` (using Clang's integrated assembler and LLVM "bin"utils)

[1] https://github.com/ClangBuiltLinux/linux/issues/1120#issuecomment-674182703
[2] https://git.kernel.org/linus/df6d4f9db79c1a5d6f48b59db35ccd1e9ff9adfc
[3] https://lore.kernel.org/patchwork/project/lkml/list/?series=456251
[4] https://www.osboxes.org/freedos/#freedos-1-2-vbox

NOTE: I did not test without patchset from [3] (and not willing to).

**Comment by dileks** [comment]
Alternative #2:

1. Sami's diff from https://github.com/ClangBuiltLinux/linux/issues/1120#issuecomment-674182703
2. Arvind's patch `[v2] x86/boot/compressed: Disable relocation relaxation ` see [1] (as replacement for the above revert of df6d4f9db79c)

Works here fine, too.

[1] https://lore.kernel.org/patchwork/patch/1286579/

**Comment by dileks** [comment]
Fixed by:

```diff
--- a/arch/x86/boot/compressed/kaslr_64.c
+++ b/arch/x86/boot/compressed/kaslr_64.c
@@ -29,6 +29,9 @@
 #define __PAGE_OFFSET __PAGE_OFFSET_BASE
 #include "../../mm/ident_map.c"
 
+/* Used by pgtable.h asm code to force instruction serialization. */
+unsigned long __force_order __weak;
+
 /* Used to track our page table allocation area. */
 struct alloc_pgt_data {
        unsigned char *pgt_buf;
```

**Comment by dileks** [comment]
Test:

```diff
diff --git a/arch/x86/boot/compressed/kaslr_64.c b/arch/x86/boot/compressed/kaslr_64.c
index f9c5c13d979b..29a7f452a4c4 100644
--- a/arch/x86/boot/compressed/kaslr_64.c
+++ b/arch/x86/boot/compressed/kaslr_64.c
@@ -29,6 +29,9 @@
 #define __PAGE_OFFSET __PAGE_OFFSET_BASE
 #include "../../mm/ident_map.c"
 
+/* Used by pgtable.h asm code to force instruction serialization. */
+//unsigned long __force_order;
+
 /* Used to track our page table allocation area. */
 struct alloc_pgt_data {
        unsigned char *pgt_buf;
diff --git a/arch/x86/boot/compressed/pgtable_64.c b/arch/x86/boot/compressed/pgtable_64.c
index c8862696a47b..b13c3eac03e8 100644
--- a/arch/x86/boot/compressed/pgtable_64.c
+++ b/arch/x86/boot/compressed/pgtable_64.c
@@ -12,7 +12,7 @@
  * It is not referenced from the code, but GCC < 5 with -fPIE would fail
  * due to an undefined symbol. Define it to make these ancient GCCs work.
  */
-unsigned long __force_order;
+//unsigned long __force_order;
 
 #define BIOS_START_MIN         0x20000U        /* 128K, less than this is insane */
 #define BIOS_START_MAX         0x9f000U        /* 640K, absolute maximum */
```

Results in (LLVM toolchain when IAS used):
```
$ for o in acpi.o cmdline.o cpuflags.o early_serial_console.o efi_thunk_64.o error.o head_64.o kaslr_64.o kaslr.o kernel_info.o mem_encrypt.o misc.o pgtable_64.o piggy.o string.o ; do echo [ $o ] ; llvm-objdump -dr arch/x86/boot/compressed/$o | grep '\__force_order' ; done
[ acpi.o ]
[ cmdline.o ]
[ cpuflags.o ]
[ early_serial_console.o ]
[ efi_thunk_64.o ]
[ error.o ]
[ head_64.o ]
[ kaslr_64.o ]
                00000000000001b9:  R_X86_64_GOTPCREL    __force_order-0x4
                000000000000033a:  R_X86_64_GOTPCREL    __force_order-0x4
[ kaslr.o ]
[ kernel_info.o ]
[ mem_encrypt.o ]
[ misc.o ]
[ pgtable_64.o ]
                0000000000000153:  R_X86_64_GOTPCREL    __force_order-0x4
                000000000000019e:  R_X86_64_GOTPCREL    __force_order-0x4
[ piggy.o ]
[ string.o ]
```

**Comment by dileks** [comment]
GCC toolchain simply ignores if `kaslr_64.o` has `__force_order` means the build ends up successfully whereas LLVM toolchain and IAS breaks and the build stops:

```diff
diff --git a/arch/x86/boot/compressed/kaslr_64.c b/arch/x86/boot/compressed/kaslr_64.c
index 1836ded28a95..29a7f452a4c4 100644
--- a/arch/x86/boot/compressed/kaslr_64.c
+++ b/arch/x86/boot/compressed/kaslr_64.c
@@ -30,7 +30,7 @@
 #include "../../mm/ident_map.c"
 
 /* Used by pgtable.h asm code to force instruction serialization. */
-unsigned long __force_order;
+//unsigned long __force_order;
 
 /* Used to track our page table allocation area. */
 struct alloc_pgt_data {
dileks@iniza:~/src/linux-kernel/git$ for o in kaslr_64.o pgtable_64.o ; do echo [ $o ] ; llvm-objdump -dr arch/x86/boot/compressed/$o | grep '\__force_order' ; done
[ kaslr_64.o ]
                00000000000003c4:  R_X86_64_GOTPCREL    __force_order-0x4
                00000000000004ea:  R_X86_64_GOTPCREL    __force_order-0x4
[ pgtable_64.o ]
```

This is with Sami's diff [1] and the patchset of `x86/boot: Remove run-time relocations from compressed kernel` applied [3].

If I keep `x86/boot/compressed: Don't declare __force_order in kaslr_64.c` [2] reverted, I do not see any `__force_order` in `kaslr_64.o`

References:
[1] #1120 (comment)
[2] https://git.kernel.org/linus/df6d4f9db79c1a5d6f48b59db35ccd1e9ff9adfc
[3] https://lore.kernel.org/patchwork/project/lkml/list/?series=456251

**Comment by dileks** [comment]
@samitolvanen 

Can you test if you diff and the revert of `commit df6d4f9db79c1a5d6f48b59db35ccd1e9ff9adfc "x86/boot/compressed: Don't declare __force_order in kaslr_64.c"` works fine in your environment (LTO etc.)?

**Comment by samitolvanen** [comment]
> Can you test if you diff and the revert of `commit df6d4f9db79c1a5d6f48b59db35ccd1e9ff9adfc "x86/boot/compressed: Don't declare __force_order in kaslr_64.c"` works fine in your environment (LTO etc.)?

Yes, but it also builds fine for me without the revert (I do have Arvind's patch in my tree as well). This is with ToT Clang and x86 defconfig.

**Comment by dileks** [comment]
@samitolvanen 

Here with LLVM toolchain version `11.0.0 c2f52e2c1288b00eae528825fb92668b1f3df732` I need the revert plus your diff.

I double-checked with GCC-10 where it works with and without the revert.

Can you look at the objdumps?
```
$ for o in kaslr_64.o pgtable_64.o ; do echo [ $o ] ; llvm-objdump-11 -dr arch/x86/boot/compressed/$o | grep '\__force_order' ; done
```

**Comment by samitolvanen** [comment]
I see the same `R_X86_64_GOTPCREL` relocations in `kaslr_64.o`, but it builds and boots nevertheless.

**Comment by dileks** [comment]
Hmm, here the build breaks and stops.

**Comment by samitolvanen** [comment]
> Hmm, here the build breaks and stops.

Where does it fail and what's the error message?

**Comment by dileks** [comment]
The kernel-build does not breal but it breaks when building VirtualBox kernel-modules:

https://github.com/ClangBuiltLinux/linux/issues/1104#issuecomment-667470053

**Comment by nathanchance** [comment]
Latest patch: https://lore.kernel.org/lkml/20200823212550.3377591-1-nivedita@alum.mit.edu/

**Comment by nickdesaulniers** [comment]
v3: https://lore.kernel.org/lkml/20200902232152.3709896-1-nivedita@alum.mit.edu/

**Comment by nickdesaulniers** [comment]
merged: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=029f56db6ac248769f2c260bfaf3c3c0e23e904c

(TODO find right link)

**Comment by nickdesaulniers** [comment]
Thanks @dileks for finding the right link!

> Do we keep the label [BUG] Linux here?

Sure, it's a bug in linux, not llvm.  I've been using those two to denote which side the error was on.

> Does this affect also [ARCH] x86 (i386 aka 32bit)?

Likely.

**Comment by dileks** [comment]
@nickdesaulniers 

Label '[BUG] Linux` means `bug in mainline Linux`, so that's OK.

I cannot say much to `x86 32bit`.
