### ISSUE TITLE
CONFIG_DEBUG_INFO_COMPRESSED=y and SHF_COMPRESSED

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/linux#1122]
@MaskRay @nickdesaulniers 

I use the `Clang integrated assembler` on `x86-64` and want to try the patch `Reland D61689 Change -gz and -Wa,--compress-debug-sections to use gABI compression (SHF_COMPRESSED) with integrated assembler` [1] in `release/11.x` when I have `
CONFIG_DEBUG_INFO_COMPRESSED=y`.

First., I wanted to ask how to check for `SHF_COMPRESSED`.

Second, is [1] enough to backport to `release/11.x` or do I need more commits to pick up?

[2] says:
```
config DEBUG_INFO_COMPRESSED
	bool "Compressed debugging information"
	depends on DEBUG_INFO
	depends on $(cc-option,-gz=zlib)
	depends on $(ld-option,--compress-debug-sections=zlib)
	help
	  Compress the debug information using zlib.  Requires GCC 5.0+ or Clang
	  5.0+, binutils 2.26+, and zlib.

	  Users of dpkg-deb via scripts/package/builddeb may find an increase in
	  size of their debug .deb packages with this config set, due to the
	  debug info being compressed with zlib, then the object files being
	  recompressed with a different compression scheme. But this is still
	  preferable to setting $KDEB_COMPRESS to "none" which would be even
	  larger.
```

In the `llvmorg-11.0.0-rc1` sources:
```
$ git grep CompressDebugSections clang/ | grep 'DebugCompressionType::'
clang/lib/Frontend/CompilerInvocation.cpp:      Opts.setCompressDebugSections(llvm::DebugCompressionType::GNU);
clang/tools/driver/cc1as_main.cpp:      Opts.CompressDebugSections = llvm::DebugCompressionType::GNU;
```

[1] https://github.com/llvm/llvm-project/commit/7cf4603faee366a6e5860b6fdbedadd91872e231
[2] https://github.com/torvalds/linux/blob/master/lib/Kconfig.debug#L228

**Comment by dileks** [comment]
AFAICS, the check via Kconfig is for `zlib` but with `LLVM_IAS=1` and `LLVM` version `11.0.0-rc1` `zlib-gnu` is used.

**Comment by dileks** [comment]
I hope the resulting `linux-image-dbg` Debian package will not grow as with `gcc` and `binutils` see #1086.

**Comment by nickdesaulniers** [comment]
> First., I wanted to ask how to check for SHF_COMPRESSED.

I think I put it in the commit message, but if you dump the section list via `llvm-readelf -S <object file>` there's a set of individual characters that represent flags. `C` stands for Compressed.

**Comment by dileks** [comment]
Yupp, that I recall this afternoon and tried `llvm-readelf-11 --all *.o`:
```
$ llvm-readelf-11 -S aesni-intel.o| grep '\.debug' | grep C
  [20] .debug_info       PROGBITS        0000000000000000 069020 0079d0 00   C  0   0  1
  [22] .debug_abbrev     PROGBITS        0000000000000000 08bb70 0002ba 00   C  0   0  1
  [23] .debug_aranges    PROGBITS        0000000000000000 08be2a 00004b 00   C  0   0  1
  [25] .debug_ranges     PROGBITS        0000000000000000 08bf20 00003d 00   C  0   0  1
  [27] .debug_line       PROGBITS        0000000000000000 08c6b0 001c66 00   C  0   0  1
  [39] .debug_loc        PROGBITS        0000000000000000 08fa70 000b0b 00   C  0   0  1
  [41] .debug_str        PROGBITS        0000000000000000 091a98 003542 01 MSC  0   0  1
  [43] .debug_frame      PROGBITS        0000000000000000 095040 000190 00   C  0   0  8
```

But again how to see this is `SHF_COMPRESSED`? The above LLVM commit log mentions `.zdebug`.

**Comment by nickdesaulniers** [comment]
`.zdebug` was the initial implementation which is deprecated and not adopted by llvm.  I suspect because many tools expect the debug sections to be named with `.debug_` convention, and breaking that convention breaks many tools.  The column of `C` in your output shows those debug sections are compressed (notice how grep did not output any other sections, because we don't compress .text and the rest).

**Comment by dileks** [comment]
OK, I see no `.zdebug` in any `llvm-readelf` outputs here.

**Comment by dileks** [comment]
Installed:
```
root# dpkg -l | grep zlib | awk '/^ii/ {print $1 " " $2 " " $3}' | column -t
ii  zlib1g:amd64      1:1.2.11.dfsg-2
ii  zlib1g-dev:amd64  1:1.2.11.dfsg-2
```

**Comment by MaskRay** [comment]
`Reland D61689 Change -gz and -Wa,--compress-debug-sections to use gABI compression (SHF_COMPRESSED) with integrated assembler` affects `-gz` but not `-gz=zlib`

Before D61689, -gz enables zlib-gnu with (a) integrated assembler or (b) older GNU as (<2.26), but SHF_COMPRESSED with newer GNU as.
Now, -gz is similar to -gz=zlib.

**Comment by nickdesaulniers** [comment]
Not sure there's any action item to do here, so closing. Please reopen if there's something to resolve here.
