### ISSUE TITLE
-Wstring-concatenation in drivers/clk/rockchip/clk-rk3228.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1123]
```
../drivers/clk/rockchip/clk-rk3228.c:140:58: warning: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Wstring-concatenation]
PNAME(mux_pll_src_4plls_p)      = { "cpll", "gpll", "hdmiphy" "usb480m" };
                                                              ^
                                                             ,
../drivers/clk/rockchip/clk-rk3228.c:140:48: note: place parentheses around the string literal to silence warning
PNAME(mux_pll_src_4plls_p)      = { "cpll", "gpll", "hdmiphy" "usb480m" };
                                                    ^
1 warning generated.
```

This is a new warning from LLVM. Seems sort of noisy but it pointed this out so I guess it is worth keeping around. I'll eventually get around to silencing the other instances that are not bugs (although I think putting parentheses around the literals will look ugly but so be it).

Patch submitted for this: https://lore.kernel.org/lkml/20200810044020.2063350-1-natechancellor@gmail.com/

**Comment by davidbolvansky** [comment]
Some noise cases were eliminated after I landed the warning.

If you have a log from build with recent clang, can you paste it somewhere, please?

I would try to implement some new heuristics to avoid warning. Thanks.

**Comment by nathanchance** [comment]
Opened #1124 to discuss it, thanks!

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/clk/c/e9c006bc782c488f485ffe50de20b44e1e3daa18

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/e9c006bc782c488f485ffe50de20b44e1e3daa18
