### ISSUE TITLE
[CROSS_COMPILE=] why gcc target triple and not llvm target triple?

### ISSUE THREAD

**Issue by n8v8R** [ClangBuiltLinux/linux#1127]
compiling with _llvm_'s target triple as per https://github.com/llvm/llvm-project/blob/master/llvm/include/llvm/ADT/Triple.h does not work if set through `CROSS_COMPILE=` as apparently https://github.com/ClangBuiltLinux/linux/blob/master/Makefile#L575 it expects `CLANG_FLAGS	+= --gcc-toolchain=$(GCC_TOOLCHAIN)`

Does is not make sense to leverage _llvm_'s build-in target triple instead of relying on gcc code?

**Comment by nickdesaulniers** [comment]
Can you give me an example of an "LLVM target triple" that you had in mind, and how it would differ from GCC's?  Clang's "driver" is meant to be a drop in replacement for GCC and MSCV (on windows); the front end driver will translate whatever flags to an internally consistent representation.  I'd expect the target triple to be the same between GCC and Clang.

`--gcc-toolchain` is different than setting the `--target=` triple; it's the location of tools like the assembler (when you use `-no-integrated-as`, as Clang builds currently do for the kernel) and the linker (unless you set `LD=ld.lld` or `LLVM=1` when invoking `make`).

**Comment by n8v8R** [comment]
> Can you give me an example of an "LLVM target triple" that you had in mind

* `--target armv7-linux-gnueabihf`

is valid for _LLVM_ but there is no such match for GCC https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html and thus setting `CROSS_COMPILE=armv7-linux-gnueabihf` fails the build
___
> I'd expect the target triple to be the same between GCC and Clang.

That does not seem to be the case.
___
> setting the `--target=` triple

the syntax appears to be wrong, least on my node with _clang-10_ it prints on the cli

>clang: error: unsupported option '--target'; did you mean '-target'?

the correct syntax would seem to be `-target

**Comment by n8v8R** [comment]
reopening since it appears to be an issue, if not for the support of _llvm_'s target triple then for the syntax issue `-target` <> `--target`

**Comment by nathanchance** [comment]
It is `-target <triple>` and `--target=<triple>`. That appears to be a conscious decision, I would not call that a bug.

I am also not really understanding the initial report, what is the bug?

**Comment by n8v8R** [comment]
> That appears to be a conscious decision, I would not call that a bug.

thank you for the clarification.
___
> I am also not really understanding the initial report, what is the bug?

`ARCH=arm CROSS_COMPILE=armv7-linux-gnueabihf make -j12 CC=clang-10 AR=llvm-ar-10 STRIP=llvm-strip-10 NM=llvm-nm-10 OBJCOPY=llvm-objcopy-10 OBJDUMP=llvm-objdump-10 OBJSIZE=llvm-size-10 READELF=llvm-readelf-10 LD=ld.lld-10 HOSTCC=clang-10 HOSTCXX=clang++-10 HOSTAR=llvm-ar-10 HOSTLD=ld.lld-10 CLANG_FLAGS+='-fintegrated-as'`

produces a build failure

>   CC      scripts/mod/devicetable-offsets.s
> errorerror: : unknown target CPU 'armv5t'unknown target CPU 'armv5t'
> 
> note: note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, tigerlake, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, x86-64valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, tigerlake, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, x86-64
> 
> make[1]: *** [scripts/Makefile.build:117: scripts/mod/devicetable-offsets.s] Error 1

**Comment by n8v8R** [comment]
Instead with 

`ARCH=arm make -j12 CC=clang-10 AR=llvm-ar-10 STRIP=llvm-strip-10 NM=llvm-nm-10 OBJCOPY=llvm-objcopy-10 OBJDUMP=llvm-objdump-10 OBJSIZE=llvm-size-10 READELF=llvm-readelf-10 LD=ld.lld-10 HOSTCC=clang-10 HOSTCXX=clang++-10 HOSTAR=llvm-ar-10 HOSTLD=ld.lld-10 CLANG_FLAGS+='-target armv7-linux-gnueabihf -fintegrated-as'`

The error does not exhibit but the build fails nonetheless with a bunch of other errors:

>   AS      arch/arm/kernel/entry-armv.o
> arch/arm/kernel/entry-armv.S:520:4: error: invalid instruction, any one of the following would fix this:
> 2: ldrht r5, [r4]
>    ^
> arch/arm/kernel/entry-armv.S:520:18: note: too few operands for instruction
> 2: ldrht r5, [r4]
>                  ^
> arch/arm/kernel/entry-armv.S:520:4: note: instruction requires: thumb2
> 2: ldrht r5, [r4]
>    ^
> arch/arm/kernel/entry-armv.S:524:4: error: invalid instruction, any one of the following would fix this:
> 3: ldrht r0, [r2]
>    ^
> arch/arm/kernel/entry-armv.S:524:18: note: too few operands for instruction
> 3: ldrht r0, [r2]
>                  ^
> arch/arm/kernel/entry-armv.S:524:4: note: instruction requires: thumb2
> 3: ldrht r0, [r2]
>    ^
> make[2]: *** [scripts/Makefile.build:364: arch/arm/kernel/entry-armv.o] Error 1
> make[1]: *** [scripts/Makefile.build:500: arch/arm/kernel] Error 2

**Comment by nickdesaulniers** [comment]
> > Can you give me an example of an "LLVM target triple" that you had in mind
> 
> * `-target armv7-linux-gnueabihf`
> 
> is valid for _LLVM_ but there is no such match for GCC https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html and thus setting `CROSS_COMPILE=armv7-linux-gnueabihf` fails the build

Ah, that's because `CROSS_COMPILE` is used for both:
1. the target triple.
2. the prefix for GNU binutils.

When these differ, as they do for Android because Android made up some prefix for their distribution of GNU binutils, then you need to apply another patch to the kernel's build system to disambiguate these two, requiring you to pass yet another variable to differentiate between 1 and 2 above.  But why would you do this, unless you really want to rename your tools against the prevailing convention?  Follow convention; problem solved.

> 
> > I'd expect the target triple to be the same between GCC and Clang.
> 
> That does not seem to be the case.
> 
> > setting the `--target=` triple
> 
> the syntax appears to be wrong, least on my node with _clang-10_ it prints on the cli
> 
> > clang: error: unsupported option '--target'; did you mean '-target'?
> 
> the correct syntax would seem to be `-target`

`--target=arm-linux-gnueabihf-` is equivalent to `-target arm-linux-gnueabihf`.  The first case is less work for the command line argument parser, IIRC via @MaskRay .

> Instead with

No `CROSS_COMPILE` which is required for 1 and 2 above.  Also `make LLVM=1` should help so you don't need to set all of those command line arguments to `make`.

**Comment by n8v8R** [comment]
> Also `make LLVM=1` should help so you don't need to set all of those command line arguments to `make`

Does not work with distros that provide CLANG|LLVM in different versions, e.g. 9 | 10 | 11 and each such binary carrying a version suffix, e.g. `clang-10`. With `LLVM=1` only binaries without such suffix are discovered through system's env path variable, unless either setting softlinks or aliases which I am not keen on.
___
> then you need to apply another patch to the kernel's build system to disambiguate these two, requiring you to pass yet another variable to differentiate between 1 and 2 above. But why would you do this, unless you really want to rename your tools against the prevailing convention? Follow convention; problem solved.

Not sure I follow your chain of thought. `armv7-linux-gnueabihf` follows the LLVM convention and as the documentation points out:

>**LLVM has substitutes for GNU binutils utilities**. Kbuild supports LLVM=1 to enable them

Why should one follow _binutils*  convention then, if that is what you are implying?

**Comment by nickdesaulniers** [comment]
> Does not work with distros that provide CLANG|LLVM in different versions, e.g. 9 | 10 | 11 and each such binary carrying a version suffix, e.g. clang-10

We discussed this when adding support for `LLVM=1` upstream. Those versioned binaries are symlinks to binaries in a dir where the dir has suffixes and the binaries are not.  Add that to your `$PATH`.

> Why should one follow binutils convention then, if that is what you are implying?

Again, because that's how binutils naming convention works, which LLVM is hard coded to look up when you say `-no-integrated-as`.  See 1 and 2 above; it serves two purposes with one convention.

**Comment by n8v8R** [comment]
> > Does not work with distros that provide CLANG|LLVM in different versions, e.g. 9 | 10 | 11 and each such binary carrying a version suffix, e.g. clang-10
> 
> We discussed this when adding support for `LLVM=1` upstream. Those versioned binaries are symlinks to binaries in a dir where the dir has suffixes and the binaries are not. Add that to your `$PATH`.

sure

```
stat /usr/bin/clang-10
  File: /usr/bin/clang-10 -> ../lib/llvm-10/bin/clang
```

I went another way at it - modifying the Makefile instead but adding to the path might be the cleaner solution, that is until more then one version of the compiler tools gets installed. I will probably compile LLVM anyway from source and be done with it.
____

> > Why should one follow binutils convention then, if that is what you are implying?
> 
> Again, because that's how binutils naming convention works, which LLVM is hard coded to look up when you say `-no-integrated-as`. See 1 and 2 above; it serves two purposes with one convention.

Perhaps you are missing the point, I am compiling expressively with `-fintegrated-as`. Why should one be following the _gnu_ convention in such case when compiling with _llvm_'s asm and according to their convention https://github.com/llvm/llvm-project/blob/master/llvm/include/llvm/ADT/Triple.h?

**Comment by n8v8R** [comment]
there is accentually no difference in the conventions between _gnu_ and _llvm_ it was just that the _gcc_ toolchain not been installed on this node as compiling with _llvm_ there would no need for it, that is except for the declarations in the Makefile. 

For that reason please (re-)consider the approach in the Makefile since there is no need for _llvm_ having to revert unnecessarily to some _gcc_ code snippets.

**Comment by nathanchance** [comment]
I suspect `PATH=/usr/lib/llvm-10/bin:${PATH} make -j12 ARCH=arm CROSS_COMPILE=armv7-linux-gnueabihf LLVM=1 LLVM_IAS=1` would work fine, if you must insist on using an LLVM target triple as `CROSS_COMPILE` instead of the more standard `arm-linux-gnueabihf-`. This would be the standard way that we would recommend compiling how you are looking to do it.

**Comment by n8v8R** [comment]
> I suspect `PATH=/usr/lib/llvm-10/bin:${PATH} make -j12 ARCH=arm CROSS_COMPILE=armv7-linux-gnueabihf LLVM=1 LLVM_IAS=1` would work fine

It does.
____
> if you must insist on using an LLVM target triple

It is not about insisting but rather questioning of why imposing GCC code snippet when LLVM does fine without it. 

IMHO it would make sense to about it something like

```
+  ifneq ($(GCC_TOOLCHAIN),)
+- CLANG_FLAGS	+= --gcc-toolchain=$(GCC_TOOLCHAIN)
++ CLANG_FLAGS	+= --target=$(CROSS_COMPILE)
+ endif
```
