### ISSUE TITLE
[LLVM_IAS] wrong clang flag

### ISSUE THREAD

**Issue by n8v8R** [ClangBuiltLinux/linux#1128]
https://github.com/ClangBuiltLinux/linux/blob/master/Makefile#L578 sets

`CLANG_FLAGS	+= -no-integrated-as`

This appears to be actually disabling the integrated assembler when `LLVM_IAS=1` 

>You can pass LLVM_IAS=1 to enable it

 instead of enabling it with `CLANG_FLAGS	+= -fintegrated-as`

https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fintegrated-as

**Comment by nathanchance** [comment]
`ifneq ($(LLVM_IAS),1)`

Is right above that statement, which means it is not triggered when `LLVM_IAS=1` is passed. There has been extensive testing of this flag, it does work.

**Comment by n8v8R** [comment]
That does not match the documentation https://www.kernel.org/doc/html/latest/kbuild/llvm.html#llvm-utilities

>Currently, the integrated assembler is disabled by default. **You can pass LLVM_IAS=1 to enable it.**

**Comment by E5ten** [comment]
It's ifneq, so when LLVM_IAS doesn't equal 1, it passes -no-integrated-as, and when it does equal one, it enables the integrated assembler by not passing the flag.
