### ISSUE TITLE
[kernel 5.9 x86_64] does not compile with llvm asm

### ISSUE THREAD

**Issue by n8v8R** [ClangBuiltLinux/linux#1133]
trying to compile 5.9-rc1 on a linux x86_64 node (_llvm-10_) with `make -j8 LLVM=1 LLVM_IAS=1` and this kconfig [.config.txt](https://github.com/ClangBuiltLinux/linux/files/5087033/default.config.txt)

the process is hitting several stumbling blocks

```
  CC      init/version.o
  CC      kernel/sched/core.o
  CC      kernel/sched/loadavg.o
  CC      kernel/sched/clock.o
Cannot find symbol for section 2: .text.
init/initramfs.o: failed
make[1]: *** [scripts/Makefile.build:283: init/initramfs.o] Error 1
make[1]: *** Deleting file 'init/initramfs.o'
make[1]: *** Waiting for unfinished jobs....
  CC      kernel/sched/cputime.o
  CC      kernel/sched/idle.o
  CC      arch/x86/entry/vdso/vdso32-setup.o
  LDS     arch/x86/entry/vdso/vdso.lds
make: *** [Makefile:1789: init] Error 2
```

```
  AS      arch/x86/entry/entry_64.o
<instantiation>:2:2: error: unknown use of instruction mnemonic without a size suffix
 lsl %rax, %rax
 ^
<instantiation>:2:2: note: while in macro instantiation
 LOAD_CPU_AND_NODE_SEG_LIMIT %rax
 ^
<instantiation>:1:1: note: while in macro instantiation
ALTERNATIVE "LOAD_CPU_AND_NODE_SEG_LIMIT %rax", "RDPID  %rax", (16*32+22)
^
<instantiation>:2:2: note: while in macro instantiation
 GET_PERCPU_BASE %rax
 ^
arch/x86/entry/entry_64.S:846:2: note: while in macro instantiation
 SAVE_AND_SET_GSBASE scratch_reg=%rax save_reg=%rbx
 ^
make[2]: *** [scripts/Makefile.build:364: arch/x86/entry/entry_64.o] Error 1
make[1]: *** [scripts/Makefile.build:500: arch/x86/entry] Error 2
make: *** [Makefile:1789: arch/x86] Error 2
```
```
  CC      kernel/elfcore.o
  CC      kernel/irq_work.o
  CC      kernel/padata.o
  CC      kernel/jump_label.o
  CC      kernel/iomem.o
  CC      kernel/rseq.o
Cannot find symbol for section 2: .text.
kernel/elfcore.o: failed
make[1]: *** [scripts/Makefile.build:283: kernel/elfcore.o] Error 1
make[1]: *** Deleting file 'kernel/elfcore.o'
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1789: kernel] Error 2
```

the process with `-d` flag producing this [build.log](https://github.com/ClangBuiltLinux/linux/files/5087121/build.log)
___
`make -j8 LLVM=1` builds the kernel with a mere two warnings

```
arch/x86/hyperv/hv_apic.c:225:13: warning: stack frame size of 1072 bytes in function 'hv_send_ipi_mask_allbutself' [-Wframe-larger-than=]
static void hv_send_ipi_mask_allbutself(const struct cpumask *mask, int vector)
            ^
arch/x86/hyperv/hv_apic.c:238:13: warning: stack frame size of 1072 bytes in function 'hv_send_ipi_allbutself' [-Wframe-larger-than=]
static void hv_send_ipi_allbutself(int vector)
            ^
2 warnings generated.
```

```
drivers/cpufreq/cpufreq_ondemand.c:413:13: warning: stack frame size of 1072 bytes in function 'od_set_powersave_bias' [-Wframe-larger-than=]
static void od_set_powersave_bias(unsigned int powersave_bias)
            ^
1 warning generated.
```

**Comment by nathanchance** [comment]
> ```
>   CC      init/version.o
>   CC      kernel/sched/core.o
>   CC      kernel/sched/loadavg.o
>   CC      kernel/sched/clock.o
> Cannot find symbol for section 2: .text.
> init/initramfs.o: failed
> make[1]: *** [scripts/Makefile.build:283: init/initramfs.o] Error 1
> make[1]: *** Deleting file 'init/initramfs.o'
> make[1]: *** Waiting for unfinished jobs....
>   CC      kernel/sched/cputime.o
>   CC      kernel/sched/idle.o
>   CC      arch/x86/entry/vdso/vdso32-setup.o
>   LDS     arch/x86/entry/vdso/vdso.lds
> make: *** [Makefile:1789: init] Error 2
> ```

#981 (kernel bug?)

> ```
>   AS      arch/x86/entry/entry_64.o
> <instantiation>:2:2: error: unknown use of instruction mnemonic without a size suffix
>  lsl %rax, %rax
>  ^
> <instantiation>:2:2: note: while in macro instantiation
>  LOAD_CPU_AND_NODE_SEG_LIMIT %rax
>  ^
> <instantiation>:1:1: note: while in macro instantiation
> ALTERNATIVE "LOAD_CPU_AND_NODE_SEG_LIMIT %rax", "RDPID  %rax", (16*32+22)
> ^
> <instantiation>:2:2: note: while in macro instantiation
>  GET_PERCPU_BASE %rax
>  ^
> arch/x86/entry/entry_64.S:846:2: note: while in macro instantiation
>  SAVE_AND_SET_GSBASE scratch_reg=%rax save_reg=%rbx
>  ^
> make[2]: *** [scripts/Makefile.build:364: arch/x86/entry/entry_64.o] Error 1
> make[1]: *** [scripts/Makefile.build:500: arch/x86/entry] Error 2
> make: *** [Makefile:1789: arch/x86] Error 2
> ```

Fixed in LLVM 11, cannot be fixed in LLVM 10 due to EOL status: #1079

> ```
>   CC      kernel/elfcore.o
>   CC      kernel/irq_work.o
>   CC      kernel/padata.o
>   CC      kernel/jump_label.o
>   CC      kernel/iomem.o
>   CC      kernel/rseq.o
> Cannot find symbol for section 2: .text.
> kernel/elfcore.o: failed
> make[1]: *** [scripts/Makefile.build:283: kernel/elfcore.o] Error 1
> make[1]: *** Deleting file 'kernel/elfcore.o'
> make[1]: *** Waiting for unfinished jobs....
> make: *** [Makefile:1789: kernel] Error 2
> ```

Same as above.

> ```
> arch/x86/hyperv/hv_apic.c:225:13: warning: stack frame size of 1072 bytes in function 'hv_send_ipi_mask_allbutself' [-Wframe-larger-than=]
> static void hv_send_ipi_mask_allbutself(const struct cpumask *mask, int vector)
>             ^
> arch/x86/hyperv/hv_apic.c:238:13: warning: stack frame size of 1072 bytes in function 'hv_send_ipi_allbutself' [-Wframe-larger-than=]
> static void hv_send_ipi_allbutself(int vector)
>             ^
> 2 warnings generated.
> ```
> 
> ```
> drivers/cpufreq/cpufreq_ondemand.c:413:13: warning: stack frame size of 1072 bytes in function 'od_set_powersave_bias' [-Wframe-larger-than=]
> static void od_set_powersave_bias(unsigned int powersave_bias)
>             ^
> 1 warning generated.
> ```

Weird, default frame warn for x86_64 should be 2048 but I assume your config changes that.

**Comment by n8v8R** [comment]
> Weird, default frame warn for x86_64 should be 2048 but I assume your config changes that.

Probably due to workflow `make oldconfig` where the limit appears to diverge from the default 2048. Thank you for the pointer, sorted it now.
___
As for the LLVM v11 the distro (kali linux) does not package it currently, will test once I get around to compile LLVM from source.
___
> #981 (kernel bug?)

The kernel developers at least seems to have stalled on the patchset https://lore.kernel.org/lkml/20200409135341.zczgrpbi3pwayicb@treble/, seeing the ping on 9 Apr 2020 from the patch submitter not being responded too.

Anyway, since it appears to be a dup on this part closing this issue.

**Comment by nickdesaulniers** [comment]
> The kernel developers at least seems to have stalled on the patchset

It can be helpful to respond on the thread (lore provides how to at the bottom) with information that you tested a series.  That can help show there's interest, and that it does work for others.
