### ISSUE TITLE
objtool: unreachable instruction

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1148]
It looks like since Jul 30, I've seen a few reports from 0day bot about unreachable instructions. They looks randconfig based.

A bunch of reports aug 31, two on aug 6, two on Jul 30.

**Comment by ihalip** [comment]
I found a possible cause for this (maybe there are multiple?). The `BUG()` macro inserts 2 `ud2` instructions on x86_64. From `arch/x86/include/asm/bug.h`:
```c
#define BUG()							\
do {								\
	_BUG_FLAGS(ASM_UD2, 0);					\
	unreachable();						\
} while (0)
```

objtool considers the second `ud2` as unreachable.

**Comment by nickdesaulniers** [comment]
@ihalip your previous version of your comment hinting at UBSAN was correct. Specifically, it seems this may be related to:
CONFIG_UBSAN_TRAP.

**Comment by ihalip** [comment]
W.r.t. the `arch/x86/kernel/sev-es.o: warning: objtool: ist_exc_vmm_communication()+0x12: unreachable instruction` case that's been talked about on the mailing list, this is what happens in short:
```
call panic
ud2
```
, where `panic()` is marked as noreturn. This could easily be fixed in objtool, since it already has a way to check if a function is a "dead end".

```diff
diff --git a/tools/objtool/check.c b/tools/objtool/check.c
index e034a8f24f46..9224e6565ba2 100644
--- a/tools/objtool/check.c
+++ b/tools/objtool/check.c
@@ -2612,9 +2612,10 @@ static bool is_ubsan_insn(struct instruction *insn)
                        "__ubsan_handle_builtin_unreachable"));
 }
 
-static bool ignore_unreachable_insn(struct instruction *insn)
+static bool ignore_unreachable_insn(struct objtool_file *file, struct instruction *insn)
 {
        int i;
+       struct instruction *prev_insn;
 
        if (insn->ignore || insn->type == INSN_NOP)
                return true;
@@ -2640,7 +2641,8 @@ static bool ignore_unreachable_insn(struct instruction *insn)
         * the UD2, which causes GCC's undefined trap logic to emit another UD2
         * (or occasionally a JMP to UD2).
         */
-       if (list_prev_entry(insn, list)->dead_end &&
+       prev_insn = list_prev_entry(insn, list);
+       if ((prev_insn->dead_end || dead_end_function(file, prev_insn->call_dest)) &&
            (insn->type == INSN_BUG ||
             (insn->type == INSN_JUMP_UNCONDITIONAL &&
              insn->jump_dest && insn->jump_dest->type == INSN_BUG)))
@@ -2767,7 +2769,7 @@ static int validate_reachable_instructions(struct objtool_file *file)
                return 0;
 
        for_each_insn(file, insn) {
-               if (insn->visited || ignore_unreachable_insn(insn))
+               if (insn->visited || ignore_unreachable_insn(file, insn))
                        continue;
 
                WARN_FUNC("unreachable instruction", insn->sec, insn->offset);
```

**Comment by ihalip** [comment]
I sent this patch with an updated comment.

**Comment by dileks** [comment]
@ihalip 

Shouldn't `objtool maintainers` be CCed?
Did you run `./scripts/get_maintainer.pl $patch`?

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/MAINTAINERS#n12503

**Comment by ihalip** [comment]
I didn't add them in the commit message, but they are CCd on the actual e-mail.

**Comment by nickdesaulniers** [comment]
patch: https://lore.kernel.org/lkml/20200917084905.1647262-1-ilie.halip@gmail.com/

**Comment by dileks** [comment]
@ihalip 

Always good to point to the message-id of <lore.k.o> or give patchwork LKML link.

**Comment by dileks** [comment]
Cool, first time using `b4`:
```
root# apt-get update && apt-get install -t testing b4

dileks$ git checkout tags/v5.9-rc5 -b for-5.9/objtool-unreachable-trap-ihalip

dileks$ b4 am https://lore.kernel.org/lkml/20200917084905.1647262-1-ilie.halip@gmail.com/ -o - | git am
```

[1] https://github.com/ClangBuiltLinux/linux/wiki/Command-line-tips-and-tricks > "For fetching a patch series from the mailing list"

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=14db1f0a93331d0958e90da522c429ff0890d2d6

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=14db1f0a93331d0958e90da522c429ff0890d2d6
