### ISSUE TITLE
Warning: ignoring changed section attributes for .data..read_mostly

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1153]
```
/tmp/io_uring-32c837.s: Assembler messages:
/tmp/io_uring-32c837.s:33061: Warning: ignoring changed section attributes for .data..read_mostly
```
linux-next
https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/384539804
probably not ppc specific

Likely section flags are missing or wrong on a `.section` directive.

**Comment by ihalip** [comment]
From the generated assembly:
```
	.type	io_uring_fops,@object           # @io_uring_fops
	.section	.data..read_mostly,"a",@progbits
	.p2align	3
io_uring_fops:
	[ ... ]

	.type	io_op_defs,@object              # @io_op_defs
	.section	.data..read_mostly,"a",@progbits
	.p2align	2
io_op_defs:
	[ ... ]
```

The alignment differs. This can also be seen in the generated LLVM bitcode:

```
@io_uring_fops = internal constant %struct.file_operations { ... }, section ".data..read_mostly", align 8
@io_op_defs = internal constant [ .... ], section ".data..read_mostly", align 4
```

**Comment by nickdesaulniers** [comment]
Does the GNU as behavior differ per target?  Seems like a bug in gas; I didn't change the section attributes, right?

**Comment by ihalip** [comment]
> Does the GNU as behavior differ per target?
Doesn't look like it, x86 has the same issue. The code where this warning originates is not arch-specific.

> Seems like a bug in gas

I'd say so too, but this behavior is quite old it seems.

TBH, I don't see the point of commit 5a9ea05954a52, which marked these 2 symbols as __read_mostly. `io_op_defs` is already being placed in `.rodata`, and `io_uring_fops` in `.data.rel.ro`.

**Comment by nathanchance** [comment]
Linus noticed this and Jens said the commit would be reverted:

https://lore.kernel.org/lkml/CAHk-=wgUjjxhe2qREhdDm5VYYmLJWG2e_-+rgChf1aBkBqmtHw@mail.gmail.com/

https://lore.kernel.org/lkml/7f2c7699-b8f4-3b50-d1c9-beeb429e32e4@kernel.dk/

**Comment by nathanchance** [comment]
Patch is sitting in the branch destined for 5.10: https://git.kernel.org/axboe/linux-block/c/9a0d486c78942c738433daa739359c990eb73a43

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/linus/0918682be432b85ccd49285832221d9b65831ef5
