### ISSUE TITLE
-Wpointer-bool-conversion in net/decnet/dn_dev.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#116]
```
net/decnet/dn_dev.c:1366:10: warning: address of array 'dev->name' will always evaluate to 'true' [-Wpointer-bool-conversion]
                                dev->name ? dev->name : "???",
                                ~~~~~^~~~ ~
1 warning generated.
```

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20180921193034.808-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=5b9b0a80aa1aefecb0273563652fb373288a21cb

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5b9b0a80aa1aefecb0273563652fb373288a21cb
