### ISSUE TITLE
arch/powerpc/kernel/vdso32/gettimeofday.S:40: Error: syntax error; found `@', expected `,'

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1160]
CONFIG_VDSO32 is broken when building w/ Clang.

specifically a 64b issue.  The compat vdso seems to be built with `--target powerpc64le-linux-gnu` and `-m32` but it seems that Clang may be generating invalid assembler for the 64b target.  see this thread: https://groups.google.com/g/clang-built-linux/c/ayNmi3HoNdY/m/XJAGj_G2AgAJ

**Comment by nickdesaulniers** [comment]
```diff
diff --git a/arch/powerpc/platforms/Kconfig.cputype b/arch/powerpc/platforms/Kconfig.cputype
index e74ec220b5d6..452423e0a15b 100644
--- a/arch/powerpc/platforms/Kconfig.cputype
+++ b/arch/powerpc/platforms/Kconfig.cputype
@@ -491,6 +491,7 @@ endmenu
 config VDSO32
        def_bool y
        depends on PPC32 || COMPAT
+       depends on !CC_IS_CLANG
        help
          This symbol controls whether we build the 32-bit VDSO. We obviously
          want to do that if we're building a 32-bit kernel. If we're building
```
to disable this for now.

**Comment by nathanchance** [comment]
I think that should be combined with the `COMPAT` one. Something like `depends on PPC32 || (COMPAT && !CC_IS_CLANG)`? Presumably we have no issues with any of the 32-bit configs because of the target.

**Comment by nathanchance** [comment]
https://github.com/llvm/llvm-project/commits/2288319733cd5f525bf7e24dece08bfcf9d0ff9e fixes this problem.

We have a few different options for resolving this on the kernel side:

1. Do nothing. `CONFIG_VDSO32` is broken with `CONFIG_COMPAT` and that should be obvious to the user but this option does not make it clear WHAT is broken.
2. Disable `CONFIG_COMPAT` when `CONFIG_CLANG_VERSION` is less than `120000`. This is a large hammer but it is the simplest fix available and one could argue the proper one because it allows the user the chance to upgrade their toolchain to have `CONFIG_COMPAT` available again.
3. Go with Nick's patch above, changing `!CC_IS_CLANG` to `(!CC_IS_CLANG || CLANG_VERSION >= 120000)`. This will involve a couple of other changes because `CONFIG_COMPAT` implicitly relies on `CONFIG_VDSO32`:
```
../arch/powerpc/perf/callchain_32.c:63:13: error: use of undeclared identifier 'vdso32_offset_sigtramp32'
            nip == VDSO32_SYMBOL(current->mm->context.vdso, sigtramp32))
                   ^
../arch/powerpc/include/asm/vdso.h:22:61: note: expanded from macro 'VDSO32_SYMBOL'
#define VDSO32_SYMBOL(base, name) ((unsigned long)(base) + (vdso32_offset_##name))
                                                            ^
<scratch space>:145:1: note: expanded from here
vdso32_offset_sigtramp32
^
../arch/powerpc/perf/callchain_32.c:74:13: error: use of undeclared identifier 'vdso32_offset_sigtramp_rt32'
            nip == VDSO32_SYMBOL(current->mm->context.vdso, sigtramp_rt32))
                   ^
../arch/powerpc/include/asm/vdso.h:22:61: note: expanded from macro 'VDSO32_SYMBOL'
#define VDSO32_SYMBOL(base, name) ((unsigned long)(base) + (vdso32_offset_##name))
                                                            ^
<scratch space>:146:1: note: expanded from here
vdso32_offset_sigtramp_rt32
^
2 errors generated.
```
```
../arch/powerpc/kernel/signal_32.c:805:11: error: use of undeclared identifier 'vdso32_offset_sigtramp_rt32'
                tramp = VDSO32_SYMBOL(tsk->mm->context.vdso, sigtramp_rt32);
                        ^
../arch/powerpc/include/asm/vdso.h:22:61: note: expanded from macro 'VDSO32_SYMBOL'
#define VDSO32_SYMBOL(base, name) ((unsigned long)(base) + (vdso32_offset_##name))
                                                            ^
<scratch space>:108:1: note: expanded from here
vdso32_offset_sigtramp_rt32
^
../arch/powerpc/kernel/signal_32.c:905:11: error: use of undeclared identifier 'vdso32_offset_sigtramp32'
                tramp = VDSO32_SYMBOL(tsk->mm->context.vdso, sigtramp32);
                        ^
../arch/powerpc/include/asm/vdso.h:22:61: note: expanded from macro 'VDSO32_SYMBOL'
#define VDSO32_SYMBOL(base, name) ((unsigned long)(base) + (vdso32_offset_##name))
                                                            ^
<scratch space>:159:1: note: expanded from here
vdso32_offset_sigtramp32
^
2 errors generated.
```
Additionally, `CONFIG_VDSO32` is not a user selectable symbol so it is a poor user experience to make it depend on Clang 12 without giving them the obvious chance to see it.

My personal vote is for option 2. It disables more of the kernel with older versions of `clang` but I am not so sure that is a bad thing, given `clang` was obviously broken before this.

**Comment by nickdesaulniers** [comment]
> https://github.com/llvm/llvm-project/commits/2288319733cd5f525bf7e24dece08bfcf9d0ff9e fixes this problem.

is in remotes/origin/release/12.x.

> My personal vote is for option 2.

SGTM; so this bug is concerned then just with clang < 12.

**Comment by nickdesaulniers** [comment]
```diff
diff --git a/arch/powerpc/Kconfig b/arch/powerpc/Kconfig
index 386ae12d8523..3f4bc52cb553 100644
--- a/arch/powerpc/Kconfig
+++ b/arch/powerpc/Kconfig
@@ -280,6 +280,7 @@ config PANIC_TIMEOUT
 config COMPAT
        bool "Enable support for 32bit binaries"
        depends on PPC64
+       depends on CLANG_VERSION >= 120000
        default y if !CPU_LITTLE_ENDIAN
        select ARCH_WANT_OLD_COMPAT_IPC
        select COMPAT_OLD_SIGACTION
```
thoughts?

**Comment by nathanchance** [comment]
Will probably need a `!CC_IS_CLANG ||` as well but otherwise, LGTM.

**Comment by nickdesaulniers** [comment]
submitted: https://lore.kernel.org/lkml/20210518205858.2440344-1-ndesaulniers@google.com/T/#u

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?id=6fcb574125e673f33ff058caa54b4e65629f3a08

**Comment by nickdesaulniers** [comment]
6fcb574125e673f33ff058caa54b4e65629f3a08
