### ISSUE TITLE
fs/gfs2/util.o: warning: objtool: gfs2_assert_warn_i()+0x184: unreachable instruction

### ISSUE THREAD

**Issue by ihalip** [ClangBuiltLinux/linux#1167]
https://groups.google.com/g/clang-built-linux/c/1zNwopRPH_k

Similar to #1148, but this is another case to be handled, when both UBSAN_MISC (-fsanitize=unreachable) and UBSAN_TRAP are enabled. Generated code looks like this:
```
    115a:       31 c0                   xor    %eax,%eax
    115c:       ff 34 24                pushq  (%rsp)
    115f:       e8 00 00 00 00          callq  1164 <gfs2_assert_warn_i+0x184>
                        1160: R_X86_64_PLT32    panic-0x4
    1164:       48 83 c4 08             add    $0x8,%rsp
    1168:       0f 0b                   ud2    
```

objtool complains about the `add` instruction between `call` and `ud2`, which is being added in there by `-fsanitize=unreachable`.

**Comment by nickdesaulniers** [comment]
```sh
$ curl -L https://groups.google.com/group/clang-built-linux/attach/97ec78aff51fb/.config.gz\?part\=0.1 | gunzip > .config
$ make LLVM=1 LLVM_IAS=1 -j72 olddefconfig
$ make LLVM=1 LLVM_IAS=1 -j72 -s fs/gfs2/util.o
```
I no longer observe this warning with linux @ 18a3c5f7abfdf97f88536d35338ebbee119c355c and llvm @ bdd68357901d2ccdd110cf35746703ac8e46de3c.
