### ISSUE TITLE
-z force-bti: file does not have GNU_PROPERTY_AARCH64_FEATURE_1_BTI property

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1168]
```
ld.lld: warning: arch/arm64/kernel/vdso/vgettimeofday.o: -z force-bti: file does not have GNU_PROPERTY_AARCH64_FEATURE_1_BTI property
```
on mainline, testing @samitolvanen 's [LTO patches](https://lore.kernel.org/lkml/20200929214631.3516445-1-samitolvanen@google.com/) but not enabled (just a defconfig) I observe the above warning.  I haven't tried removing the LTO patches, or retesting linux-next.  Filing a bug for now to follow up on.  cc @DanielKristofKiss @broonie 

(It's also possible my checkout of LLVM is slightly behind ToT and is missing recent patches. Running 69c6f6be07e4db11f2aca91ad7bbc0db1e9044d6)

**Comment by DanielKristofKiss** [comment]
could you spin it with at least a48f6079f288619fcc7656e89e8aa7cd0aac1281? it contain all recent patches that hopefully solve this.

**Comment by nickdesaulniers** [comment]
(not related to LTO; I observe this on linux-next as well).
