### ISSUE TITLE
stress-ng vdso tests failing for vdso's linked with lld

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1175]
forked from #1033, specifically https://github.com/ClangBuiltLinux/linux/issues/1033#issuecomment-632519207, it sounds like

```sh
$ stress-ng --vdso 2
```
fails for aarch64 or x86_64 kernel images linked with ld.lld. cc @nathanchance @ColinIanKing

**Comment by ColinIanKing** [comment]
I'm wondering if this is a bug in stress-ng as this code was rather a hack.  Do you have a binary dump of the vdso so I can see if I can check if it's a stress-ng issue?

**Comment by nathanchance** [comment]
@ColinIanKing here are the `.o` files, if that is good enough?

[arm64-build-artifacts.zip](https://github.com/ClangBuiltLinux/linux/files/5369323/arm64-build-artifacts.zip)

**Comment by ColinIanKing** [comment]
That was useful, but I think I need to test with a kernel built and linked with lld.  Is there a recipe I can follow to build an arm64 or x86-86 kernel this way?

**Comment by nathanchance** [comment]
@ColinIanKing assuming you have `clang` and `ld.lld` in your PATH, you should be able to use `CC=clang LD=ld.lld` in your `make` invocation. If you have all of the LLVM utilities in your PATH, you can just add `LLVM=1` to `make`. If that is not convenient, I can upload a `bzImage`.

**Comment by ColinIanKing** [comment]
Thanks for reporting this, I finally got a kernel built and tested and found the issue. Fix pushed, commit a15707a027d52f7875ca2765317560cff0a9c48f

**Comment by nathanchance** [comment]
@ColinIanKing Thank you for the quick fix, it is much appreciated! I will go ahead and test it as soon as I can.
