### ISSUE TITLE
implement -fstack-usage

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1178]
`$ scripts/stackusage LLVM=1 -j71` fails with:
```
clang-12: error: unknown argument: '-fstack-usage'
```
because the script reinvokes the build with `-fstack-usage`.  We should implement this in clang.

**Comment by pcc** [comment]
See also `-fstack-size-section` which embeds the same information in the object file.

**Comment by nickdesaulniers** [comment]
https://llvm.org/pr44418
https://lists.llvm.org/pipermail/llvm-dev/2021-May/150417.html

**Comment by nickdesaulniers** [comment]
Landed in https://reviews.llvm.org/rGc9b36a041fd70de0617ea7e241f520b345e12cac, @asb that's probably interesting for llvm weekly.
