### ISSUE TITLE
add -Wunreachable-code-* to W=2

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1180]
`-Wunreachable-code-loop-increment`, `-Wunreachable-code-break`, and `-Wunreachable-code-return` are clang specific and might help catch bugs.

**Comment by nickdesaulniers** [comment]
The use of `boot_cpu_has` is tricky because it seems to evaluate to `1` in certain cases so patterns like:
```c
if (!boot_cpu_has(foo))
  return;
```
end up triggering `-Wunreachable-code-return` a lot.

**Comment by tinti** [comment]
OOM seems to have an unreachable return at https://github.com/torvalds/linux/blob/d635a69dd4981cc51f90293f5f64268620ed1565/mm/oom_kill.c#L642

The function signature cannot be changed due to `kthread_run`.

Just adding `unreachable()` just before the return removed the warning for me.

Is this a valid solution?

**Comment by nathanchance** [comment]
I would think that should be fine but I think it would be wise to audit the full list of warnings to see how many of those types of annotations that we will have to do.

Wonder if https://lists.llvm.org/pipermail/llvm-dev/2021-January/148047.html would be relevant to that piece of code.

**Comment by tinti** [comment]
I don't have enough knowledge on LLVM side to say.

About the `boot_cpu_has` I was able to temporarily disable the warnings on it.

I was left with several:

```c
while(1) {
  // ...
}
return 0;
```

```c
shutdown();
return 0;
```

```c
// https://github.com/torvalds/linux/blob/fcadab740480e0e0e9fa9bd272acd409884d431a/net/wireless/util.c#L93

switch(x) {
  // ...
  case A:
    if (y)
      return 1;
    else
      return 0;

    break; // unreachable
  // ...
}
```

I will be adding `unreachable()` on them and see if it fixes.

More info about `__builtin_unreachable` https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html

**Comment by nickdesaulniers** [comment]
Thanks for looking into this @tinti ; it seems like there's nothing interesting found these warnings at this time.
