### ISSUE TITLE
How do I build an AARCH64 Kernel crossover tool chain using "tc-build"

### ISSUE THREAD

**Issue by lina-not-linus** [ClangBuiltLinux/linux#1182]
Did not see the "TC-Build" manual for building the AARCH64 cross tool chain tool chain
How do I build an AARCH64 Kernel cross-tool chain using "TC-Build"

Thanks

**Comment by nathanchance** [comment]
Are you talking about cross compiling LLVM for AArch64? That is outside of the scope of tc-build, it is designed for compiling LLVM only for the host but the LLVM that it creates can cross compile AArch64 kernels.

**Comment by lina-not-linus** [comment]
Sorry my description is too vague
I want to build an AArch64 kernel using Clang on an x86 machine

**Comment by nathanchance** [comment]
tc-build will allow you to do that by default. If you have any specific questions, feel free to ask them here.

**Comment by lina-not-linus** [comment]
Prepare to use clang to cross compile the aarch64 kernel and mips64el kernel on X86 machines
But I use "TC build" on X86 machines“
` ` ` `
./ci.sh  all
` ` ` `
The cross tool chain compiled is the cross tool chain of X86, which can not be used to cross compile aarch64 kernel and mips64el kernel

Thanks

**Comment by lina-not-linus** [comment]
Sorry, what do you need to do to build the kernel for aarch64 and mips64el using clang on X86 machines
Thanks

**Comment by nickdesaulniers** [comment]
Please see: https://www.kernel.org/doc/html/latest/kbuild/llvm.html#cross-compiling

using tc-build to build clang should be no different.
