### ISSUE TITLE
(.data..L__unnamed_X) is being placed in '.data..L__unnamed_X'

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1185]
three reports overnight from 0day bot:
```
(.data..L__unnamed_59) is being placed in '.data..L__unnamed_59'
(.data..L__unnamed_17) is being placed in '.data..L__unnamed_17'
(.data..L__unnamed_8) is being placed in '.data..L__unnamed_8'
```
all were ppc64 randconfig

I'm surprised we're seeing this this often now; makes me wonder if something recently regressed in LLVM to produce these sections?

cc @kees @uweigand

**Comment by samitolvanen** [comment]
I'm not sure if this is related, but I also started seeing `ld.lld: warning: <internal>:(.eh_frame) is being placed in '.eh_frame'` warnings with CFI builds recently.

**Comment by nivedita76** [comment]
Btw, I get tons of the orphan section warnings with LLD 10.0.1 on x86 defconfigs. What's the minimum version when it builds clean?

**Comment by nickdesaulniers** [comment]
@samitolvanen @nivedita76 please file separate bugs and let's try to keep them all focused on individual issues, please.

**Comment by nathanchance** [comment]
This is not reproducible with LLVM 12 or 13 with latest Linux:

```
$ curl -LSs 'https://groups.google.com/group/clang-built-linux/attach/6d4f6f6a96c47/.config.gz?part=0.1' | gunzip > .config

$ make -skj"$(nproc)" ARCH=powerpc CC=clang CROSS_COMPILE=powerpc-linux-gnu- LD=ld.lld olddefconfig all
```
