### ISSUE TITLE
unused label 'error_debugfs'

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1188]
mainline:
```
drivers/usb/dwc2/platform.c:611:1: warning: unused label 'error_debugfs' [-Wunused-label]
error_debugfs:
^~~~~~~~~~~~~~
```
depends on CONFIG_USB_DWC2

**Comment by nathanchance** [comment]
Has an outstanding patch: https://lore.kernel.org/lkml/20201017165012.546729-1-martin.blumenstingl@googlemail.com/

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/190bb01b72d2d5c3654a03c42fb1ad0dc6114c79
