### ISSUE TITLE
Section warnings on x86 with clang-10

### ISSUE THREAD

**Issue by broonie** [ClangBuiltLinux/linux#1193]
Huge numbers of warnings in the form

ld.lld: warning: arch/x86/kernel/head_64.o:(.rela.data) is being placed in '.rela.data'

are being generated on -next builds with clang-10 for an x86_64 defconfig: when built with ld.ldd and LLVM=1. Full report:

https://storage.kernelci.org//next/master/next-20201103/x86_64/x86_64_defconfig/clang-10/build-warnings.log

@gctucker

**Comment by nickdesaulniers** [comment]
dup #1187

**Comment by amfwaddi** [comment]
Hi Mr. Brown,

You are receiving this because I'm greenest of newbs and didn't know where else to put it.

A GIANT KUDO!!

My humble Acer270 has gone from 34fps to 185fps with the new intel-drm gma500drmfb.

Thanks for your work!!

Andrew Waddington
