### ISSUE TITLE
no machine record defined

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1200]
https://groups.google.com/g/clang-built-linux/c/vBrT1kkpoFo/m/3dUCwN_FAQAJ

32b arm randconfig produces:
```
>> ld.lld: error: no machine record defined
>> ld.lld: error: no machine record defined
```

These seem to be coming from `ASSERTS` in the generated linker script arch/arm/kernel/vmlinux.lds (generated from arch/arm/kernel/vmlinux.lds.S).

**Comment by nickdesaulniers** [comment]
arch/arm/kernel/vmlinux.lds.S:
```
171 /*                                                                                                                                                                                                                                     
172  * These must never be empty                                                                                                                                                                                                           
173  * If you have to comment these two assert statements out, your                                                                                                                                                                        
174  * binutils is too old (for other reasons as well)                                                                                                                                                                                     
175  */                                                                                                                                                                                                                                    
176 ASSERT((__proc_info_end - __proc_info_begin), "missing CPU support")                                                                                                                                                                   
177 ASSERT((__arch_info_end - __arch_info_begin), "no machine record defined")  
```

**Comment by nickdesaulniers** [comment]
possibly there's no `MACHINE_START` called for this randconfig

**Comment by nickdesaulniers** [comment]
cc @arndb

**Comment by arndb** [comment]
Correct, this is a problem that has been known for a long time, and nobody has come up with a good solution. It should not happen on the modern 'CONFIG_ARCH_MULTIPLATFORM' configurations that are used most of the time, but for the legacy platforms, you must choose between any combination of boards that are enabled, and if all of them happen to be disabled, we run into the assertion that tells us the kernel will be unable to boot on any hardware.

In my randconfig tests, I use a private patch that encloses the ASSERT() in #ifndef CONFIG_COMPILE_TEST.

**Comment by nickdesaulniers** [comment]
And then you always build with CONFIG_COMPILE_TEST? Does 0 day bot set CONFIG_COMPILE_TEST as well (cc @rli9 )?  If so, is it worthwhile to upstream that private patch, @arndb ?

**Comment by arndb** [comment]
My build scripts enforce CONFIG_COMPILE_TEST=y, not sure what other build bots do.

**Comment by nickdesaulniers** [comment]
Going to close as wontfix then, since this is a known issue that's not LLVM specific.

**Comment by rli9** [comment]
> And then you always build with CONFIG_COMPILE_TEST? Does 0 day bot set CONFIG_COMPILE_TEST as well (cc @rli9 )?
FYI, 0-day bot will have this CONFIG_COMPILE_TEST enabled in some randconifg since it is randomly generated.

**Comment by arndb** [comment]
> FYI, 0-day bot will have this CONFIG_COMPILE_TEST enabled in some randconifg since it is randomly generated.

Having it enabled sometimes would not help here, the patch I have only helps if CONFIG_COMPILE_TEST is always force-enabled when running randconfig tests, to avoid the cases that are known to fail in some random configurations but cannot be fixed in general.
