### ISSUE TITLE
track compiler.h: fix barrier_data() on clang

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1202]
the upstream patch needs to get backported, but there seems to be a few follow ups. cc @nivedita76 to help track the follow ups that all need to get backported.

**Comment by nickdesaulniers** [comment]
For example, I think https://lore.kernel.org/lkml/20201117013951.7827-1-rdunlap@infradead.org/ is related, because of https://lore.kernel.org/r/87sg999ot0.fsf@igel.home/.

also: https://lore.kernel.org/stable/20201101173105.1723648-1-nivedita@alum.mit.edu/.

**Comment by nickdesaulniers** [comment]
Fix for 815f0ddb346c ("include/linux/compiler*.h: make compiler-*.h mutually exclusive") which first landed in v4.19-rc1. That commit does not exist in v4.14.y or older.

1. 3347acc6fcd4ee71ad18a9ff9d9dac176b517329 ("compiler.h: fix barrier_data() on clang") which first landed in v5.10-rc4.
2. 30aca1bacb398dec6c1ed5eeca33f355bd7b6203 ("RISC-V: fix barrier() use in <vdso/processor.h>") which first landed in v5.10-rc6, and mentions fixing ad5d1122b82fbd6a816d1b9d26ee01a6dbc2d757 ("riscv: use vDSO common flow to reduce the latency of the time-related functions") which first landed in v5.8-rc1.

So it sounds like I need to send backports to:
1. linux-5.9.y
2. linux-5.4.y
3. linux-4.19.y

Specifically the above need:
1. 3347acc6fcd4ee71ad18a9ff9d9dac176b517329 and 30aca1bacb398dec6c1ed5eeca33f355bd7b6203.
2. 3347acc6fcd4ee71ad18a9ff9d9dac176b517329
3. 3347acc6fcd4ee71ad18a9ff9d9dac176b517329

Though I should check to see if the RISCV vdso exists/has this issue prior to v5.8-rc1 so that 3347acc6fcd4ee71ad18a9ff9d9dac176b517329 does not regress it.

**Comment by nickdesaulniers** [comment]
30aca1b already exists in linux-5.9.y as 038c5ea51f026b1b7b4ff9e4d511d28ae3577c9f, which first shipped in v5.9.12.

**Comment by nickdesaulniers** [comment]
Noting the test for this is:
```sh
$ make LLVM=1 -j71 defconfig
$ make LLVM=1 -j71 lib/crypto/sha256.o
$ llvm-objdump -Dr --disassemble-symbols=sha256_update lib/crypto/sha256.o | grep memset
```

**Comment by nickdesaulniers** [comment]
conflicts in linux-5.4.y due to missing:
1. e506ea451254a ("compiler.h: Split {READ,WRITE}_ONCE definitions out into rwonce.h") which first landed in v5.9-rc1.
2. d08b9f0ca6605 ("scs: Add support for Clang's Shadow Call Stack (SCS)") which first landed in v5.8-rc1.
Addition conflict in linux-4.19.y due to missing:
1. a3f8a30f3f0079 ("Compiler Attributes: use feature checks instead of version checks") which first landed in v4.20-rc1.

In linux-4.19.y, `memzero_explicit` was not a `static inline` function defined in a header, so a more appropriate test there is:
```sh
$ make LLVM=1 -j71 defconfig
$ make LLVM=1 -j71 crypto/authenc.o
$ llvm-objdump -Dr --disassemble-symbols=crypto_authenc_setkey crypto/authenc.o | grep memzero_explicit
```

**Comment by nickdesaulniers** [comment]
Sent backports (in reply to https://lore.kernel.org/lkml/CAKwvOdnrMdMjuJcRuPg6CgeGZds_td2DNrPNaReFuyg9NEMExQ@mail.gmail.com/).
[3347acc6fcd4.4.19.patch.txt](https://github.com/ClangBuiltLinux/linux/files/5681586/3347acc6fcd4.4.19.patch.txt)
[3347acc6fcd4.5.4.patch.txt](https://github.com/ClangBuiltLinux/linux/files/5681587/3347acc6fcd4.5.4.patch.txt)
[3347acc6fcd4.5.9.patch.txt](https://github.com/ClangBuiltLinux/linux/files/5681588/3347acc6fcd4.5.9.patch.txt)

**Comment by dileks** [comment]
Looks like Linux `v5.4.y` and `v5.9.y` has it accepted.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.9.y&id=54ddef488732546219d457830641e6452d8056f9
[2] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.4.y&id=c2c5dc84ac51da90cadcb12554c69bdd5ac7aeeb

**Comment by nickdesaulniers** [comment]
Yeah, I figure it's just slow down around the holidays.  Let's keep an eye out for 4.19 though; the current release is 4.19.163. If it's not in 4.19.164 I will send a friendly reminder. Thanks @dileks !

**Comment by nickdesaulniers** [comment]
Here it is in the linux-stable-rc tree's 4.19 branch: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/commit/?h=queue/4.19&id=de0a73a5db2397a2c28da2c020fb3ad2cbd33534 (but let's wait to close this out until it's in the stable tree).

**Comment by dileks** [comment]
Hopefully, this will happen with Linux `v4.19.164` release.

**Comment by dileks** [comment]
`Linux v4.19.164` released.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v4.19.164&id=b207caff4176e3a6ba273243da2db2e595e4aad2

**Comment by dileks** [comment]
@nickdesaulniers 

Note: I did not add `[FIXED][LINUX] 5.9` as Linux `v5.9.16` is marked `EOL` (EndOfLive @ 2020-12-21).

Link: https://www.kernel.org/

**Comment by nickdesaulniers** [comment]
SGTM thanks @dileks (Happy new year!)

**Comment by dileks** [comment]
@nickdesaulniers 

Happy new year!
