### ISSUE TITLE
x32 objcopy failed to link section

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1205]
I get this build failure with CC=clang-12 and GNU objcopy:

/home/arnd/cross/x86_64/gcc-10.1.0-nolibc/x86_64-linux/bin/x86_64-linux-objcopy: arch/x86/entry/vdso/vclock_gettime-x32.o: failed to find link section for section 12
/home/arnd/cross/x86_64/gcc-10.1.0-nolibc/x86_64-linux/bin/x86_64-linux-objcopy: arch/x86/entry/vdso/vclock_gettime-x32.o: failed to find link section for section 12
/home/arnd/cross/x86_64/gcc-10.1.0-nolibc/x86_64-linux/bin/x86_64-linux-objcopy: arch/x86/entry/vdso/vgetcpu-x32.o: failed to find link section for section 11
/home/arnd/cross/x86_64/gcc-10.1.0-nolibc/x86_64-linux/bin/x86_64-linux-objcopy: arch/x86/entry/vdso/vgetcpu-x32.o: failed to find link section for section 11
arch/x86/entry/thunk_64.o: warning: objtool: missing symbol for insn at offset 0x3e

**Comment by arndb** [comment]
Uploaded .config to https://pastebin.com/jLByy0pE

**Comment by nickdesaulniers** [comment]
```sh
$ wget https://pastebin.com/raw/jLByy0pE -O .config
$ make LLVM=1 LLVM_IAS=1 -j72 olddefconfig
$ make LLVM=1 LLVM_IAS=1 -j72 -s
```
I'm unable to reproduce with linux @ 18a3c5f7abfdf97f88536d35338ebbee119c355c and llvm @ bdd68357901d2ccdd110cf35746703ac8e46de3c. Please reopen if you have more info on how to reproduce.
