### ISSUE TITLE
objtool crashes when using x86 IAS

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1207]
I get lots of objtool crashes on clang-11 and clang-12 building x86 randconfig kernels when using the integrated assembler

Segmentation fault (core dumped)
make[4]: *** [/git/arm-soc/scripts/Makefile.build:283: kernel/entry/common.o] Error 139
make[4]: *** Deleting file 'kernel/entry/common.o'
make[4]: Target '__build' not remade because of errors.
make[3]: *** [/git/arm-soc/scripts/Makefile.build:500: kernel/entry] Error 2
Segmentation fault (core dumped)
make[5]: *** [/git/arm-soc/scripts/Makefile.build:283: arch/x86/kernel/apic/apic.o] Error 139
make[5]: *** Deleting file 'arch/x86/kernel/apic/apic.o'
make[5]: Target '__build' not remade because of errors.
make[4]: *** [/git/arm-soc/scripts/Makefile.build:500: arch/x86/kernel/apic] Error 2
arch/x86/kernel/signal.o: warning: objtool: __setup_rt_frame()+0x478: call to memset() with UACCESS enabled
Segmentation fault (core dumped)
make[4]: *** [/git/arm-soc/scripts/Makefile.build:283: arch/x86/kernel/smp.o] Error 139
make[4]: *** Deleting file 'arch/x86/kernel/smp.o'
Segmentation fault (core dumped)
make[3]: *** [/git/arm-soc/scripts/Makefile.build:283: kernel/softirq.o] Error 139
make[3]: *** Deleting file 'kernel/softirq.o'
make[4]: Target '__build' not remade because of errors.
make[3]: *** [/git/arm-soc/scripts/Makefile.build:500: arch/x86/kernel] Error 2
arch/x86/ia32/ia32_signal.o: warning: objtool: ia32_setup_rt_frame()+0x1de: call to memset() with UACCESS enabled
make[3]: Target '__build' not remade because of errors.

email report https://lore.kernel.org/lkml/CAK8P3a20LXgEQkYSpbFFrJs1mdg19W72dp3pbebH9Pkpib2g-g@mail.gmail.com/T/
example .config https://pastebin.com/e4Kr9mWq

**Comment by nickdesaulniers** [comment]
Josh has a patch: https://groups.google.com/g/clang-built-linux/c/1C6YoJKBsQQ/m/a8IS1NjGAgAJ

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/44f6a7c0755d8dd453c70557e11687bb080a6f21
