### ISSUE TITLE
unrecognized opcode zext.b a1,a0

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1220]
I don't have a reproducer yet, but there's a few 0day reports from riscv randconfigs that look like:
```
>> /tmp/do_mounts-997907.s:184: Error: unrecognized opcode `zext.b a1,a0'
   clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)
```
Looks like clang is producing an instruction that either GAS or the integrated assembler doesn't like. (I can't tell from the reports which was used).

**Comment by nickdesaulniers** [comment]
oh boy close to 30 reports overnight. cc @topperc

**Comment by topperc** [comment]
I suspect its GAS that doesn't like it. New aliases were just recently added to the spec. Maybe we need to not print those aliases and only parse them.

**Comment by jrtc27** [comment]
You are probably about the only people in the world testing Clang/LLVM RISC-V without the integrated assembler... is there a feature in it you're missing?

**Comment by nickdesaulniers** [comment]
>  is there a feature in it you're missing?

Yes; clang's integrated assembler for most architectures cannot be used for assembling the Linux kernel, so for the past ~4 years, we've built all targets with `-no-integrated-as`.  See also [link](https://github.com/ClangBuiltLinux/linux/issues?q=is%3Aissue+label%3A%22%5BTOOL%5D+integrated-as%22+) for fixed and open issues related to `-no-integrated-as`.

> You are probably about the only people in the world testing Clang/LLVM RISC-V without the integrated assembler

So x86_64, arm64, 32b arm v7, and riscv were being built with the integrated assembler (at build time of the kernel, we can turn it on) and prefer to do so when possible.  The email reports are from Intel's 0day bot team (@rli9 ) which is not testing riscv with `LLVM_IAS=1`; which is ok, since the compatibility matrix for architectures we can build with clang's integrated assembler is both convoluted, and is frequently regressing.

> Maybe we need to not print those aliases and only parse them.

That sounds like it would do it; maybe a comment in the sources to "undo" that once GNU binutils version X.XX is more commonplace?  While it makes sense that the latest clang with the integrated assembler works, `-no-integrated-as` means we're at the mercy of other distros and how frequently they update.

**Comment by lenary** [comment]
@topperc has been working on a fix for this that should land shortly on `main`.

**Comment by topperc** [comment]
Fix has landed in llvm 249d7de1190f50178181d2477aa661cd252e294c

**Comment by nickdesaulniers** [comment]
Thanks @topperc @lenary !

**Comment by lenary** [comment]
I coded the break, @topperc coded the fix, so all the thanks should go in his direction.
