### ISSUE TITLE
unknown argument '-ffixed-a2'

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1224]
```
$ ARCH=m68k CROSS_COMPILE=m68k-linux-gnu- make CC=clang -j71 defconfig
$ ARCH=m68k CROSS_COMPILE=m68k-linux-gnu- make CC=clang -j71
...
clang-12: error: unknown argument '-ffixed-a2'; did you mean '-ffixed-x2'?
```
(see also: https://github.com/ClangBuiltLinux/linux/wiki/M68k-experimental-backend-support)
cc @mshockwave.  These flags were used when building the Linux kernel for aarch64 to reserve the use of GPRs from the compiler's register allocator.

**Comment by nickdesaulniers** [comment]
Reopening until this is fixed in the upstream linux kernel proper.

Note: it's probably important to support `-ffixed-a2`: the kernel must be reserving it for some global storage of some value.  Disabling that flag may break the kernel at runtime.

Also, `CONFIG_CC_IS_GCC` should be used rather than "not clang."

**Comment by nickdesaulniers** [comment]
still reproducible with llvm @ c440b97d89994feb965a9026bc121d154f7b4584.

**Comment by mshockwave** [comment]
Patch for this issue has been put on Phab: https://reviews.llvm.org/D102805

**Comment by nathanchance** [comment]
https://github.com/llvm/llvm-project/commit/e620bea21199791513f3193a71b819b20a707ab1
