### ISSUE TITLE
cfi: ld.lld: warning: <internal>:(.eh_frame) is being placed in '.eh_frame'

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/linux#1227]
CC @samitolvanen @MaskRay 

I pulled in `cfi-5.10` releases tag on top of `Linux v5.10.3`.

My `LLVM toolchain` is version `11.0.1-rc2`.

Note: `CFI` (and LTO) feature requires `LLVM=1` and `LLVM_IAS=1` to be used and `LLVM toolchain >= v11` (see `CONFIG_HAS_LTO_CLANG`).

In my logs I see (beyond usual known CFI warnings):
```
+ ld.lld-11 -m elf_x86_64 --thinlto-cache-dir=.thinlto-cache -mllvm -import-instr-limit=5 --emit-relocs --discard-none -z max-page-size=0x200000 --build-id=sha1 -X --orphan-handling=warn --strip-debug -o .tmp_vmlinux.kallsyms1 -T ./arch/x86/kernel/vmlinux.lds --whole-archive vmlinux.o --no-whole-archive
ld.lld-11: warning: <internal>:(.eh_frame) is being placed in '.eh_frame'
+ kallsyms .tmp_vmlinux.kallsyms1 .tmp_vmlinux.kallsyms1.S

+ ld.lld-11 -m elf_x86_64 --thinlto-cache-dir=.thinlto-cache -mllvm -import-instr-limit=5 --emit-relocs --discard-none -z max-page-size=0x200000 --build-id=sha1 -X --orphan-handling=warn --strip-debug -o .tmp_vmlinux.kallsyms2 -T ./arch/x86/kernel/vmlinux.lds --whole-archive vmlinux.o --no-whole-archive .tmp_vmlinux.kallsyms1.o
ld.lld-11: warning: <internal>:(.eh_frame) is being placed in '.eh_frame'
+ kallsyms .tmp_vmlinux.kallsyms2 .tmp_vmlinux.kallsyms2.S

+ ld.lld-11 -m elf_x86_64 --thinlto-cache-dir=.thinlto-cache -mllvm -import-instr-limit=5 --emit-relocs --discard-none -z max-page-size=0x200000 --build-id=sha1 -X --orphan-handling=warn -o vmlinux -T ./arch/x86/kernel/vmlinux.lds --whole-archive vmlinux.o --no-whole-archive .tmp_vmlinux.kallsyms2.o
ld.lld-11: warning: <internal>:(.eh_frame) is being placed in '.eh_frame'
```

Link: https://github.com/samitolvanen/linux/releases/tag/cfi-5.10

**Comment by dileks** [comment]
Feel free to change `subject` and `labels`.

**Comment by samitolvanen** [comment]
Thanks for filing the issue. I also see this on arm64 builds and with ToT LLVM.

**Comment by nickdesaulniers** [comment]
These warnings are coming from the linker flag `--orphan-handling=warn`. It seems the linker scripts being passed after `-T` maybe don't mention where to place these sections explicitly? Usually we disable `.eh_frame` via `-fno-asynchronous-unwind-tables` (https://stackoverflow.com/a/26302715/1027966).

**Comment by samitolvanen** [comment]
As Nathan pointed out in issue #1069, defining `SANITIZER_DISCARDS` also with `CONFIG_CFI_CLANG` removes the warning. This is now fixed in the current CFI trees.
