### ISSUE TITLE
Issue submitting guidelines

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#123]
I have been submitting a lot of issues lately, but not really paying attention to individual cases (not reading the related code, just copypasting the message generated by clang), hoping that someone could give it a more detailed look.
Now I have a list of warnings that can make about 50 more items in this issue tracker (I checked for uniqueness, they are not duplicates), but most of them are `-Wparentheses-equality` and `-Wenum-conversion`. All issues about warnings are given a "low priority" label, so it's easy to filter them out, but still it can be hard to navigate.
Maybe it's a good idea to create master issues for common and not important stuff like `-Wparentheses-equality` and `-Wenum-conversion` reporting all the occurrences of the warning in comments to those master issues, while more rare and important will be submitted as separate issues.

**Comment by nickdesaulniers** [comment]
I was thinking maybe labels for the exact warning (eg. `[-Wparenthesis-equality]`?  That might help with filtering.  It's important to track what's been fixed (and when).  I'm not opposed to master issues, they'd just need to keep track of which have been fixed or not, which might get messy.

**Comment by tpimh** [comment]
Tracking the patches with master issues can be a problem. So I'm okay with submitting 50+ individual issues with appropriate labels to allow easy filtering.

**Comment by nickdesaulniers** [comment]
Reposting since I just looked this up; to filter out a label, prefix the `label` part of the query with `-`, ie. `-label:-Wparentheses-equality` via https://help.github.com/articles/searching-issues-and-pull-requests/#search-by-label

**Comment by dileks** [comment]
Thanks for opening this issue. I just followed the recent issue via smartphone during my holidays. Personally, I would like to have the information or label of which Linux kernel release and LLVM/Clang version was used.
Furthermore some "dangerous" means BROKEN Kconfigs should be collected.
Here, I am very close to the Linux kernel-config provided by the Debian Kernel Team.

Currently, I am playing with Linux v4.19-rcN and LLVM/Clang v7 final release from <apt.llvm.org>.

**Comment by dileks** [comment]
Is it possible to have the "compiler-attributes" work of Miguel Ojeda as a seperate issue?

https://github.com/ojeda/linux/tree/compiler-attributes-v4
https://github.com/ojeda/linux/tree/compiler-attributes-for-next

**Comment by nickdesaulniers** [comment]
Issues are as cheap to create as new branches; please feel free to create both as you wish.  I don't think those patches need one per se, as they're not fixing a known bug, but it doesn't hurt to create an issue to track something.  They are an enhancement for sure.

**Comment by tpimh** [comment]
Just submitted a bunch of low priority issues. This is still not all, but a lot. I hope that someone will have the time to go through them.

**Comment by nickdesaulniers** [comment]
Please invite friends that are looking to start contributing to the kernel to help out. These are all good beginner bugs.

**Comment by tpimh** [comment]
Do you think "good first issue" and "help wanted" labels are not that informative anymore? I personally stopped adding them, as there is `no:assignee` filter that will show all the bugs that need attention and help and anything is a "good first issue" for you as long if you can get something fixed.

**Comment by nickdesaulniers** [comment]
I've definitely been conflating "good first issue" and "help wanted."  I think we can de duplicate them.  "Good first issue" is an important signal to newbies looking to get started.  IIRC, Rust had a similar set of labels that worked well.  I've also linked to "good first issue" from: https://www.reddit.com/r/kernel/comments/9ghkzs/some_beginner_bugs/

**Comment by tpimh** [comment]
I think I made it better by cleaning the labels a little: "good first issue" now is only for issues without a [PATCH] and as soon it's [FIXED] then [PATCH] is no longer needed. Makes the list more clear and easy to navigate in my opinion.

**Comment by nickdesaulniers** [comment]
Looks like all the action items from here are concluded. Closing for now.  Don't hesitate to file new bugs discussing process. 🚶 🐕
