### ISSUE TITLE
Sections not merged

### ISSUE THREAD

**Issue by gwelymernans** [ClangBuiltLinux/linux#1231]
I'm encountering an interesting issue when using our version of livepatch with clang's integrated assembler. It has to do with our ELF file "diffing" tool (it generates a new ELF file that includes the binary diff of the old and new files). During processing, it expects each section to be unique, but clang produces two sections with the same name in some situations. This occurs in `arch/x86/kernel/early_printk.c`, but is applicable in other places. This is an example of the code:

```
$ cat init.rodata.c
static int __attribute__((__section__(".init.text")))
foo(char *idx)
{
	static const int __attribute__((__section__(".init.rodata"))) bases[] = { 0x3f8, 0x2f8 };

	return bases[idx ? 0 : 1];
}

struct obs_kernel_param {
	const char *str;
	int (*setup_func)(char *);
	int early;
};

static const char __setup[]
	__attribute__((__section__(".init.rodata")))
       	__attribute__((aligned(1))) = "section test";
static struct obs_kernel_param __setup_setup
	__attribute__((__used__))
       	__attribute__((__section__(".init.setup")))
	__attribute__((aligned((sizeof(long))))) = {
		__setup, foo, 1
	};
```

Clang compiles this to:

<pre>
$ clang -fno-strict-aliasing -fno-common -fshort-wchar -fno-addrsig -fno-PIE -fexperimental-new-pass-manager \
  -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -mno-80387 -mstack-alignment=8 -mtune=generic \
  -mno-red-zone -mcmodel=kernel -funit-at-a-time -pipe -fno-asynchronous-unwind-tables -mretpoline-external-thunk \
  -DRETPOLINE -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -fstack-protector-strong \
  -mno-global-merge -fno-omit-frame-pointer -fno-optimize-sibling-calls -mfentry -ffunction-sections -fdata-sections \
  -fno-merge-all-constants -fno-stack-check -o - -S init.rodata.c
	.text
	.file	"init.rodata.c"
	.section	.init.text,"ax",@progbits
	.p2align	4, 0x90                         # -- Begin function foo
	.type	foo,@function
foo:                                    # @foo
# %bb.0:
	pushq	%rbp
	movq	%rsp, %rbp
	xorl	%eax, %eax
	testq	%rdi, %rdi
	sete	%al
	movl	foo.bases(,%rax,4), %eax
	popq	%rbp
	retq
.Lfunc_end0:
	.size	foo, .Lfunc_end0-foo
                                        # -- End function
	.type	__setup,@object                 # @__setup
	.section	.init.rodata,"a",@progbits
__setup:
	.asciz	"section test"
	.size	__setup, 13

	.type	__setup_setup,@object           # @__setup_setup
	<b>.section	.init.setup,"aw",@progbits</b>
	.p2align	3
__setup_setup:
	.quad	__setup
	.quad	foo
	.long	1                               # 0x1
	.zero	4
	.size	__setup_setup, 24

	.type	foo.bases,@object               # @foo.bases
	<b>.section	.init.rodata,"aM",@progbits,8,unique,1</b>
	.p2align	2
foo.bases:
	.long	1016                            # 0x3f8
	.long	760                             # 0x2f8
	.size	foo.bases, 8

	.ident	"clang version google3-trunk (cf5df40c4cf1a53a02ab1d56a488642e3dda8f6d)"
	.section	".note.GNU-stack","",@progbits
</pre>

Notice the two `.init.rodata` sections:

<pre>
$ readelf -SW init.rodata.o
There are 12 section headers, starting at offset 0x280:

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .strtab           STRTAB          0000000000000000 0001f0 00008a 00      0   0  1
  [ 2] .text             PROGBITS        0000000000000000 000040 000000 00  AX  0   0  4
  [ 3] .init.text        PROGBITS        0000000000000000 000040 000015 00  AX  0   0 16
  [ 4] .rela.init.text   RELA            0000000000000000 0001a8 000018 18     11   3  8
  <b>[ 5] .init.rodata      PROGBITS        0000000000000000 000055 00000d 00   A  0   0  1</b>
  [ 6] .init.setup       PROGBITS        0000000000000000 000068 000018 00  WA  0   0  8
  [ 7] .rela.init.setup  RELA            0000000000000000 0001c0 000030 18     11   6  8
  <b>[ 8] .init.rodata      PROGBITS        0000000000000000 000080 000008 08  AM  0   0  4</b>
  [ 9] .comment          PROGBITS        0000000000000000 000088 000048 01  MS  0   0  1
  [10] .note.GNU-stack   PROGBITS        0000000000000000 0000d0 000000 00      0   0  1
  [11] .symtab           SYMTAB          0000000000000000 0000d0 0000d8 18      1   9  8
</pre>

GCC helpfully combines those sections. Clang doesn't, because one has the `SHF_MERGE` flag while the other doesn't. They're of course merged later on, but the tool we're using is looking at the `.o` files as they're generated. One of the differences between GCC and Clang is that GCC uses the `-fmerge-constants` flag, while I don't think Clang supports that flag yet.

Is there a way to force Clang to combine them? From what I gather, they need the same section flags in order to be combined without a linker script.

BTW, I know the obvious answer is to fix the tool. 😄 I would just rather not do that if necessary, and instead get the compilers to generate similar code.

**Comment by nickdesaulniers** [comment]
> One of the differences between GCC and Clang is that GCC uses the -fmerge-constants flag, while I don't think Clang supports that flag yet.

Is https://github.com/ClangBuiltLinux/linux/commit/4c207c50ea35abf98f087bbcda8c95b23c4bb3b1#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52 related? Do you have that recent commit in your tree?

**Comment by gwelymernans** [comment]
We don't have that commit, but adding it doesn't remove the error...

**Comment by nickdesaulniers** [comment]
I don't think the sections can be merged because they differ in "entity size" (ES).  One is an array of `int`, while the other is an array of `char`. This probably comes from https://reviews.llvm.org/D72194 or https://reviews.llvm.org/D53056.  Maybe we should just be leaving off the entity size?

**Comment by nickdesaulniers** [comment]
@gwelymernans can you please help test https://reviews.llvm.org/D93948 to see if it helps resolve this particular issue?  Looks to me like it might?

**Comment by gwelymernans** [comment]
We were able to bypass this on our end. I didn't try the D93948 patch, but it looks promising.
