### ISSUE TITLE
objtool: "call without frame pointer save/setup" in crypto/jitterentropy.o

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1236]
This file gets built with -O0, which triggers unexpected code generation:

crypto/jitterentropy.o: warning: objtool: tsan.module_ctor()+0x0: call without frame pointer save/setup

[0x7DCCCE5C-config.gz](https://github.com/ClangBuiltLinux/linux/files/5772484/0x7DCCCE5C-config.gz)

**Comment by nickdesaulniers** [comment]
submitted: https://reviews.llvm.org/D101016
