### ISSUE TITLE
objtool: warning: objtool: asan.module_ctor()+0xc: call without frame pointer save/setup

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1238]
I see this in basically every file for some configurations:

init/noinitramfs.o: warning: objtool: asan.module_ctor()+0xc: call without frame pointer save/setup
init/noinitramfs.o: warning: objtool: asan.module_dtor()+0xc: call without frame pointer save/setup
init/main.o: warning: objtool: asan.module_ctor()+0xc: call without frame pointer save/setup
init/main.o: warning: objtool: asan.module_dtor()+0xc: call without frame pointer save/setup
init/do_mounts.o: warning: objtool: asan.module_ctor()+0xc: call without frame pointer save/setup
init/do_mounts.o: warning: objtool: asan.module_dtor()+0xc: call without frame pointer save/setup
init/calibrate.o: warning: objtool: asan.module_ctor()+0xc: call without frame pointer save/setup
init/calibrate.o: warning: objtool: asan.module_dtor()+0xc: call without frame pointer save/setup
init/init_task.o: warning: objtool: asan.module_ctor()+0xc: call without frame pointer save/setup
init/init_task.o: warning: objtool: asan.module_dtor()+0xc: call without frame pointer save/setup
init/version.o: warning: objtool: asan.module_ctor()+0xc: call without frame pointer save/setup
init/version.o: warning: objtool: asan.module_dtor()+0xc: call without frame pointer save/setup
arch/x86/entry/vdso/vma.o: warning: objtool: asan.module_ctor()+0xc: call without frame pointer save/setup
arch/x86/entry/vdso/vma.o: warning: objtool: asan.module_dtor()+0xc: call without frame pointer save/setup
arch/x86/entry/vsyscall/vsyscall_64.o: warning: objtool: asan.module_ctor()+0xc: call without frame pointer save/setup
arch/x86/entry/vsyscall/vsyscall_64.o: warning: objtool: asan.module_dtor()+0xc: call without frame pointer save/setup
arch/x86/events/amd/core.o: warning: objtool: asan.module_ctor()+0xc: call without frame pointer save/setup
arch/x86/events/amd/core.o: warning: objtool: asan.module_dtor()+0xc: call without frame pointer save/setup
arch/x86/events/amd/uncore.o: warning: objtool: asan.module_ctor()+0xc: call without frame pointer save/setup
arch/x86/events/amd/uncore.o: warning: objtool: asan.module_dtor()+0xc: call without frame pointer save/setup
...

[0x9B0BA556-config.gz](https://github.com/ClangBuiltLinux/linux/files/5772508/0x9B0BA556-config.gz)

**Comment by MaskRay** [comment]
Related to #955.

The compiler synthesized functions may not respect some attributes, like `"frame-pointer"="none"`(TargetOptions::DisableFramePointerElim), dso_local (recent R_386_PLT32), and many others (x86 IBT/aarch64 BTI directly come into mind). For important ones, e.g. dso_local, we can use a module metadata. But for various random features, investing a module metadata for each seems too burdensome on the compiler side for relatively small benefit (to appease objtool).

**Comment by MaskRay** [comment]
Created https://reviews.llvm.org/D101016 for this (asan) and #1236 (tsan).

I'll fix gcov (#955) as well once D101016 is accepted.
