### ISSUE TITLE
using r15 results in unpredictable behaviour

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1247]
I thought we already had a bug open for this...but refiling anyways.

KernelCI reports for 32b arm allmodconfig:
```
   /tmp/test-arm-446f12.s:18717: Warning: using r15 results in unpredictable behaviour
   /tmp/test-arm-446f12.s:18792: Warning: using r15 results in unpredictable behaviour
```

**Comment by nathanchance** [comment]
For what it's worth, I see this with GCC 10.2.0 too (and KernelCI sees it with [GCC 8](https://storage.kernelci.org/next/master/next-20210113/arm/allmodconfig/gcc-8/build.log)).

```
$ make -skj"$(nproc)" ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- allmodconfig arch/arm/probes/kprobes/test-arm.o
/tmp/ccFLUiKa.s: Assembler messages:
/tmp/ccFLUiKa.s:18123: Warning: using r15 results in unpredictable behaviour
/tmp/ccFLUiKa.s:18195: Warning: using r15 results in unpredictable behaviour
```

**Comment by nickdesaulniers** [comment]
r15 is the program counter on arm.  Using it as the destination operand is...probably not a good idea as the warning allude to.

**Comment by nathanchance** [comment]
https://lore.kernel.org/r/20210211025149.3544593-2-ndesaulniers@google.com/

**Comment by nathanchance** [comment]
Patch has been accepted: https://git.kernel.org/next/linux-next/c/e9d54be9ad5ee2eed3056d8901ac4b3b115d95a5

**Comment by nickdesaulniers** [comment]
duping this to #1271
