### ISSUE TITLE
-Wcompare-distinct-pointer-types in drivers/spi/spi-cadence-quadspi.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1248]
kernelci reports:
```
    drivers/spi/spi-cadence-quadspi.c:1153:24: warning: comparison of distinct pointer types ('typeof (len) *' (aka 'unsigned long *') and 'typeof (500U) *' (aka 'unsigned int *')) [-Wcompare-distinct-pointer-types]
```
for arm64 defconfigs.

**Comment by nathanchance** [comment]
Someone sent a patch independently that has been picked up, it should be in the next `-next` version: https://git.kernel.org/broonie/spi/c/2ef0170e90391f1adb31c449059b8efdc923707c

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/next/linux-next/c/2ef0170e90391f1adb31c449059b8efdc923707c
