### ISSUE TITLE
unsupported GNU_PROPERTY_TYPE in drivers/media/tuners/tuner-types.ko

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1249]
similar to #1054 

kernelci reports:
```
    aarch64-linux-gnu-strip: warning: /scratch/linux/_modules_/lib/modules/5.11.0-rc2-next-20210111/kernel/drivers/media/tuners/tuner-types.ko: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
```
for arm64 defconfigs.

**Comment by nathanchance** [comment]
Isn't this #1054?

**Comment by nathanchance** [comment]
Wow I did not read the actual body, sorry...

**Comment by nathanchance** [comment]
This appears to be a KernelCI specific issue. The resolution to #1054 was to disable `CONFIG_ARM64_PTR_AUTH` when binutils were too old. KernelCI uses `LLVM=1` but specifically changes `STRIP` to be `aarch64-linux-gnu-strip` during the `modules_install` step ([build output](https://storage.kernelci.org/next/master/next-20210113/arm64/defconfig/clang-11/build.log) and [commit making the change](https://github.com/kernelci/kernelci-core/commit/e4843915f9d99fca0e824d2c3ba1a94f5a52152e)), which is clearly too old to support the PAC ELF notes. That `STRIP` assignment should not be necessary, it should rely on the default value in the main Makefile, which will be `$(CROSS_COMPILE)strip` if `LLVM=1` is not present, `llvm-strip` if it is. If there is something wrong with `llvm-strip`, we should fix it.

**Comment by nickdesaulniers** [comment]
cc @gctucker @khilman @broonie
