### ISSUE TITLE
arch/x86/entry/thunk_64.o: warning: objtool: missing symbol table

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1254]
This could be related to #1209 although I am filing a different issue for two reasons:

1. This is with GNU as, not the integrated assembler.
2. Neither [Nick's patch](https://lore.kernel.org/lkml/CAKwvOdnAMsYF-v1LAqttBV3e3rHhSFZmPcRRV0+v=+9AyMFgNA@mail.gmail.com/) nor [Josh's patch](https://lore.kernel.org/lkml/9638ee49574226218d978ce7e26f7a107021f509.1609990368.git.jpoimboe@redhat.com/) for #1209 resolve it.

When building with ToT LLVM and binutils, I see the following warning (which is actually an error):

```
$ make -skj"$(nproc)" LLVM=1 defconfig arch/x86/entry/thunk_64.o
arch/x86/entry/thunk_64.o: warning: objtool: missing symbol table
make[3]: *** [scripts/Makefile.build:360: arch/x86/entry/thunk_64.o] Error 1
make[3]: *** Deleting file 'arch/x86/entry/thunk_64.o'
...
```

I have uploaded the `.o` file here: https://github.com/nathanchance/bug-files/blob/7442f4c76efc096b02cb750b8c553de93fdcf409/cbl-1254/thunk_64.o

LLVM is built from https://github.com/llvm/llvm-project/commit/202d359753d1f130a228c3ad52dfaabf384250d1 and binutils are built from https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=58eadc4b691b5c943a9b8879420242ffc6d498c7.

cc @jpoimboe

**Comment by nickdesaulniers** [comment]
general question; is it possible to make these warnings from objtool non-fatal so that they don't kill our builds/CI @jpoimboe?

**Comment by nathanchance** [comment]
Once I figured out how to consistently reproduce (`ccache`...), bisect landed on https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=d1bcae833b32f1408485ce69f844dcd7ded093a8, which would certainly make sense. Guessing that commit is more aggressive about removing symbols than the integrated assembler is?

**Comment by jpoimboe** [comment]
Ha, this is an empty .o file (no text, data or symbols) because CONFIG_PREEMPTION isn't set.

@nickdesaulniers See https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=644592d32837 for an explanation of why objtool fails the build on some kind of errors.  These fatal errors tend to be rare, but perhaps becoming less rare these days now that the matrix of supported toolchains is growing.  I agree it's annoying though.  I can post a revert and see what Peter and Boris think.

**Comment by nathanchance** [comment]
Thank you for the quick fix Josh!

https://lore.kernel.org/lkml/a96c3f76173c7021a2298bd73362313736e674b6.1610663051.git.jpoimboe@redhat.com/

**Comment by MaskRay** [comment]
LLVM integrated assembler creates `.symtab` with an index 0 undefined symbol regardless. GNU as since https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=d1bcae833b32f1408485ce69f844dcd7ded093a8 just omits `.symtab`

**Comment by MaskRay** [comment]
I think `tools/objtool/elf.c` `missing symbol table` is overly aggressive. It can be removed if the warning/error can be folded into a subsequent error checking. Alternatively, if there is no interesting content for objtool, ignore an absent `.symtab`

**Comment by jpoimboe** [comment]
Yes, the upstream fix removes that warning.

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/linus/1d489151e9f9d1647110277ff77282fe4d96d09b

**Comment by bwendling** [comment]
This is happening again. Should I be turning off Werrors or something?

```
arch/x86/entry/thunk_64.o: warning: objtool: missing symbol table
make[2]: *** [scripts/Makefile.build:360: arch/x86/entry/thunk_64.o] Error 1
make[2]: *** Deleting file 'arch/x86/entry/thunk_64.o'
make[1]: *** [scripts/Makefile.build:496: arch/x86/entry] Error 2
make: *** [Makefile:1805: arch/x86] Error 2
```

**Comment by jpoimboe** [comment]
@gwelymernans What kernel?  That error was removed starting with Linux 5.11.
