### ISSUE TITLE
warning: DWARF2 only supports one section per compilation unit

### ISSUE THREAD

**Issue by roxell** [ClangBuiltLinux/linux#1256]
Hi,

I can see this warning on next, mainline and the stable builds:

make --silent --keep-going --jobs=8 O=/home/tuxbuild/.cache/tuxmake/builds/1/tmp ARCH=mips CROSS_COMPILE=mips-linux-gnu- 'HOSTCC=sccache clang' 'CC=sccache clang'
/builds/1n60brJr0d3GdL8iXnGJT3nVgMs/arch/mips/vdso/elf.S:14:1: warning: DWARF2 only supports one section per compilation unit
.pushsection .note.Linux, "a",@note ; .balign 4 ; .long 2f - 1f ; .long 4484f - 3f ; .long 0 ; 1:.asciz "Linux" ; 2:.balign 4 ; 3:
^
/builds/1n60brJr0d3GdL8iXnGJT3nVgMs/arch/mips/vdso/elf.S:34:2: warning: DWARF2 only supports one section per compilation unit
 .section .mips_abiflags, "a"
 ^

To reproduce the build [1]:
tuxmake --runtime docker --target-arch mips --toolchain clang-11 --kconfig tinyconfig

[1] https://builds.tuxbuild.com/1n60brJr0d3GdL8iXnGJT3nVgMs/tuxmake_reproducer.sh

**Comment by nickdesaulniers** [comment]
Similar to #716, but likely a result of #618, which is common for vdsos.  The mips vdso Makefile should add `-no-integrated-as` unless `LLVM_IAS` is defined.

Is there a config that turns on the mips vdso config quickly that you're using to test with?

**Comment by roxell** [comment]
in arch/mips/Kconfig
I see this: 
config MIPS
...
       select HAVE_GENERIC_VDSO
...

**Comment by nathanchance** [comment]
I believe this is the better solution: https://lore.kernel.org/r/20210115192622.3828545-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/mips/c/76d7fff22be3e4185ee5f9da2eecbd8188e76b2c

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/76d7fff22be3
