### ISSUE TITLE
stable-v4.19: modpost: Section mismatches detected

### ISSUE THREAD

**Issue by roxell** [ClangBuiltLinux/linux#1257]
Hi,

I can see this build issue on stable v4.19, building with clang-11.
This can't be seen when building with gcc.

WARNING: modpost: Found 2 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
FATAL: modpost: Section mismatches detected.
Set CONFIG_SECTION_MISMATCH_WARN_ONLY=y to allow them.
make[2]: *** [/builds/1n6bqDqp9N4VblVaTGRnjbVVuDQ/scripts/Makefile.modpost:98: vmlinux.o] Error 1
make[1]: *** [/builds/1n6bqDqp9N4VblVaTGRnjbVVuDQ/Makefile:1057: vmlinux] Error 2
make[1]: Target '_all' not remade because of errors.
make: *** [Makefile:146: sub-make] Error 2
make: Target '_all' not remade because of errors.
E: expected artifact arch/mips/boot/uImage.gz does not exist!
make --silent --keep-going --jobs=8 O=/home/tuxbuild/.cache/tuxmake/builds/1/tmp ARCH=mips CROSS_COMPILE=mips-linux-gnu- 'HOSTCC=sccache clang' 'CC=sccache clang' vmlinux
WARNING: modpost: Found 2 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
FATAL: modpost: Section mismatches detected.
Set CONFIG_SECTION_MISMATCH_WARN_ONLY=y to allow them.
make[2]: *** [/builds/1n6bqDqp9N4VblVaTGRnjbVVuDQ/scripts/Makefile.modpost:98: vmlinux.o] Error 1
make[1]: *** [/builds/1n6bqDqp9N4VblVaTGRnjbVVuDQ/Makefile:1057: vmlinux] Error 2
make: *** [Makefile:146: sub-make] Error 2
make: Target 'vmlinux' not remade because of errors.
E: expected artifact vmlinux.xz does not exist!
E: expected artifact System.map does not exist!

To see the full log see [1].
To reproduce the build [2]:
tuxmake --runtime docker --target-arch mips --toolchain clang-11 --kconfig tinyconfig

[1] https://builds.tuxbuild.com/1n6bqDqp9N4VblVaTGRnjbVVuDQ/build.log
[2] https://builds.tuxbuild.com/1n6bqDqp9N4VblVaTGRnjbVVuDQ/tuxmake_reproducer.sh

**Comment by nathanchance** [comment]
```
$ tuxmake --runtime podman --target-arch mips --toolchain clang-11 --kconfig tinyconfig --kconfig-add CONFIG_DEBUG_SECTION_MISMATCH=y
...
WARNING: vmlinux.o(.text+0x1ce88): Section mismatch in reference from the function r4k_cache_init() to the function .init.text:loongson3_sc_init()
The function r4k_cache_init() references
the function __init loongson3_sc_init().
This is often because r4k_cache_init lacks a __init
annotation or the annotation of loongson3_sc_init is wrong.

WARNING: vmlinux.o(.text+0x21600): Section mismatch in reference from the function mips_sc_init() to the function .init.text:mips_sc_probe_cm3()
The function mips_sc_init() references
the function __init mips_sc_probe_cm3().
This is often because mips_sc_init lacks a __init
annotation or the annotation of mips_sc_probe_cm3 is wrong.
...
```

Looks like #787?

**Comment by nickdesaulniers** [comment]
I've been adding "Needs Backport" label to existing bugs, but keeping them closed.  I then remove the label when backports have landed. Thoughts?

**Comment by nathanchance** [comment]
I think that is fine. It is hard to judge what is and is not a stable worthy fix. I have been tempted to start adding "Cc: stable" to everything that I send but that just makes maintainers irritated.
