### ISSUE TITLE
-Wuninitialized in mm/zswap.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1262]
Reported-by: "kernelci.org bot" <bot@kernelci.org>

on linux-next:
```
    6    mm/zswap.c:947:17: warning: variable 'entry' is uninitialized when used here [-Wuninitialized]
    6    mm/zswap.c:933:27: note: initialize the variable 'entry' to silence this warning
```

**Comment by nathanchance** [comment]
Also reported by the 0day bot to the patch author, who would probably be the best person to address this: https://lore.kernel.org/linux-mm/202101210209.TKDZ1sTU-lkp@intel.com/

**Comment by nathanchance** [comment]
Patch submitted: https://lore.kernel.org/linux-mm/1611223030-58346-1-git-send-email-tiantao6@hisilicon.com/

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/next/linux-next/c/594c49d9f57d62bc60a3f97cb9dcca17ea3f02c2
