### ISSUE TITLE
-Wsometimes-uninitialized in mm/zswap.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1263]
similar to #1262 
Reported-by: "kernelci.org bot" bot@kernelci.org
```
   6    mm/zswap.c:1271:6: warning: variable 'ret' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
    6    mm/zswap.c:1259:9: note: initialize the variable 'ret' to silence this warning
```

**Comment by nathanchance** [comment]
I think that these two issues can be combined since they are caused by the same patch and have the same root cause.

**Comment by nathanchance** [comment]
Actually, this is a separate issue but was caused by the same patch as #1262, sorry for not paying attention.

Patch sent: https://lore.kernel.org/linux-mm/20210121214804.926843-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/next/linux-next/c/43263dd803c10c514cb207216152ff4ebc840f1d
