### ISSUE TITLE
s390 CONFIG_MARCH_ZEC12 "invalid operand in inline asm"

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1264]
Initially reported at https://gitlab.com/cki-project/pipeline-definition/-/merge_requests/1085#note_482753075, this blocks RedHat from enabling s390x for CKI.

```
$ make -skj"$(nproc)" ARCH=s390 CC=clang CROSS_COMPILE=s390x-linux-gnu- defconfig

$ scripts/config -d CONFIG_MARCH_Z196 -e CONFIG_MARCH_ZEC12

$ make -skj"$(nproc)" ARCH=s390 CC=clang CROSS_COMPILE=s390x-linux-gnu- olddefconfig arch/s390/kernel/time.o
In file included from arch/s390/kernel/time.c:18:
In file included from ./include/linux/kernel_stat.h:5:
In file included from ./include/linux/smp.h:12:
In file included from ./include/linux/list.h:9:
In file included from ./include/linux/kernel.h:11:
In file included from ./include/linux/bitops.h:32:
./arch/s390/include/asm/bitops.h:69:4: error: invalid operand in inline asm: 'oi        $0,${1:b}'
                        "oi     %0,%b1\n"
                        ^
./arch/s390/include/asm/bitops.h:90:4: error: invalid operand in inline asm: 'ni        $0,${1:b}'
                        "ni     %0,%b1\n"
                        ^
./arch/s390/include/asm/bitops.h:69:4: error: invalid operand in inline asm: 'oi        $0,${1:b}'
                        "oi     %0,%b1\n"
                        ^
./arch/s390/include/asm/bitops.h:90:4: error: invalid operand in inline asm: 'ni        $0,${1:b}'
                        "ni     %0,%b1\n"
                        ^
./arch/s390/include/asm/bitops.h:69:4: error: invalid operand in inline asm: 'oi        $0,${1:b}'
                        "oi     %0,%b1\n"
                        ^
./arch/s390/include/asm/bitops.h:69:4: error: invalid operand in inline asm: 'oi        $0,${1:b}'
./arch/s390/include/asm/bitops.h:90:4: error: invalid operand in inline asm: 'ni        $0,${1:b}'
                        "ni     %0,%b1\n"
                        ^
7 errors generated.
make[2]: *** [scripts/Makefile.build:279: arch/s390/kernel/time.o] Error 1
make[2]: Target '__build' not remade because of errors.
make[1]: *** [scripts/Makefile.build:496: arch/s390/kernel] Error 2
make[1]: Target '__build' not remade because of errors.
make: *** [Makefile:1805: arch/s390] Error 2
make: Target 'arch/s390/kernel/time.o' not remade because of errors.
```

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/s390/include/asm/bitops.h

```
$ cat time.i
int online_store_caddr;
void online_store(void) {
  asm("ni       %0,%b1\n" : "+Q"(online_store_caddr) : "i"(0));
  asm("oi       %0,%b1\n" : "+Q"(online_store_caddr) : "i"(0));
}

$ s390x-linux-gcc -march=zEC12 -c -o /dev/null time.i

$ clang --target=s390x-linux-gnu -march=zEC12 -c -o /dev/null time.i
time.i:3:7: error: invalid operand in inline asm: 'ni   $0,${1:b}'
  asm("ni       %0,%b1\n" : "+Q"(online_store_caddr) : "i"(0));
      ^
time.i:3:7: error: unknown token in expression
<inline asm>:1:12: note: instantiated into assembly here
        ni      0(%r1),
                       ^
time.i:4:7: error: invalid operand in inline asm: 'oi   $0,${1:b}'
  asm("oi       %0,%b1\n" : "+Q"(online_store_caddr) : "i"(0));
      ^
time.i:4:7: error: unknown token in expression
<inline asm>:1:12: note: instantiated into assembly here
        oi      0(%r1),
                       ^
4 errors generated.
```

cc @uweigand (I can file an upstream LLVM issue if need be).

**Comment by nathanchance** [comment]
Introduced by https://git.kernel.org/linus/4ae803253e4649803dc6e972bb5e59fc107cf474.

**Comment by nickdesaulniers** [comment]
cc @uweigand

**Comment by uweigand** [comment]
I think in this case, the %b modifier is a no-op anyway (the operator truncates an immediate to 8 bits, but in this case the immediate always fits in 8 bits to begin with), so it can be simply removed.

**Comment by nickdesaulniers** [comment]
Relevant code: https://github.com/ClangBuiltLinux/linux/blob/83d09ad4b950651a95d37697f1493c00d888d0db/arch/s390/include/asm/bitops.h#L59-L121 (there's three functions using `%b` modifier).

`arch_clear_bit` doesn't look to me like it truncates to 8b.

**Comment by uweigand** [comment]
> `arch_clear_bit` doesn't look to me like it truncates to 8b.

Right, in this case you'd have to change it to use
`"i" ((1 << (nr & 7)) ^ 0xff) 
`
instead.

**Comment by nickdesaulniers** [comment]
I don't think it's the `%b` output template: https://godbolt.org/z/orKWGe

**Comment by uweigand** [comment]
Well, it's an "i" constraint so you have to use a compile-time immediate.  This means you cannot compile that function stand-alone, you can only compile it (with optimization on and) inlined into a caller that provides a compile-time immediate "nr" argument.  That's why the block is guarded by a __builtin_constant_p predicate in the first place. (That restriction is present on GCC just the same, the instruction itself only supports an immediate argument.)

**Comment by nathanchance** [comment]
Well, that is funny: http://git.kernel.org/s390/c/6110ccecd3c0c025ab7d5224a5feba5a664e084e

I will leave this open until that commit is merged into mainline so that CKI can enable it.

**Comment by nathanchance** [comment]
Merged into mainline:

https://git.kernel.org/linus/6110ccecd3c0c025ab7d5224a5feba5a664e084e
https://git.kernel.org/linus/efe5e0fea4b24872736c62a0bcfc3f99bebd2005

@veruu I think mainline can build the Fedora s390x config if you guys wanted to try testing them now :)

**Comment by veruu** [comment]
Can confirm the kernel builds now! I'll adjust the CKI config to enable s390x.
