### ISSUE TITLE
clang-12: error: unsupported option '-fpatchable-function-entry=8' for target 'riscv64-unknown-linux-gnu'

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1268]
```Reported-by: kernel test robot <lkp@intel.com>```

Report: https://lists.01.org/hyperkitty/list/kbuild-all@lists.01.org/message/3CGDPP7DCJOXJSPBVAZF53BP3OVXMNWZ/

**Comment by nathanchance** [comment]
https://reviews.llvm.org/D98610

I will send a patch tomorrow to avoid this build error with older versions of LLVM.

**Comment by MaskRay** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/6ab8927931851bb42b2c93a00801dc499d7d9b1e (D98610) (target: clang 13.0.0)

**Comment by nickdesaulniers** [comment]
Thanks @MaskRay !!! Reopening for the kernel patch @nathanchance mentioned.

**Comment by nathanchance** [comment]
https://lore.kernel.org/r/20210325223807.2423265-1-nathan@kernel.org/

**Comment by nathanchance** [comment]
Accepted: https://git.kernel.org/riscv/linux/c/2c475caf72f37c565c03c2f6b9b9e86ec29932e2

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/linus/2c475caf72f37c565c03c2f6b9b9e86ec29932e2
