### ISSUE TITLE
clang ias: failure to build arch/arm/mach-ep93xx/crunch-bits.S

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1272]
This is yet another old FPU format, enabled with CONFIG_CRUNCH:

/git/arm-soc/arch/arm/mach-ep93xx/crunch-bits.S:94:2: error: invalid instruction
 cfstr64 mvdx0, [r1, #0] @ save 64b registers
 ^
/git/arm-soc/arch/arm/mach-ep93xx/crunch-bits.S:95:2: error: invalid instruction
 cfstr64 mvdx1, [r1, #8]
 ^
/git/arm-soc/arch/arm/mach-ep93xx/crunch-bits.S:96:2: error: invalid instruction
 cfstr64 mvdx2, [r1, #16]
 ^
/git/arm-soc/arch/arm/mach-ep93xx/crunch-bits.S:97:2: error: invalid instruction
 cfstr64 mvdx3, [r1, #24]
 ^
/git/arm-soc/arch/arm/mach-ep93xx/crunch-bits.S:98:2: error: invalid instruction
...

This is way more obscure than iWMMXt, we can probably just turn this off for clang, or for clang-ias

**Comment by nickdesaulniers** [comment]
or force `-no-integrated-as` when using clang, or do similar macro tricks with open coding the instruction.

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/lkml/141f3098744ea8d1cc39abcdce89c0e513bfbc70.camel@gmail.com/

**Comment by nickdesaulniers** [comment]
I've pinged on the list.

**Comment by nickdesaulniers** [comment]
@arndb what's the status here?

**Comment by arndb** [comment]
Fixed now by [removing crunch support](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=12c3dca25d2fa17a101de0d80bf3f238b1cecbae).
