### ISSUE TITLE
clang ias: armv7-m builds fail

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1274]
This immediately fails with

clang: error: Architecture 'armv7-m' does not support 'ARM' execution mode
clang: error: Architecture 'armv7-m' does not support 'ARM' execution mode
make[4]: *** [/git/arm-soc/scripts/Makefile.build:287: scripts/mod/empty.o] Error 1
make[4]: *** [/git/arm-soc/scripts/Makefile.build:117: scripts/mod/devicetable-offsets.s] Error 1

**Comment by nickdesaulniers** [comment]
Does armv7-m only support thumb (or thumb2)?

**Comment by arndb** [comment]
Correct, ARMv7-M (Cortex-M) is THUMB2-only, so '-march=armv7-a -marm' is not a valid combination. I have not yet looked into what tells clang to use arm instructions though.

**Comment by nickdesaulniers** [comment]
Clang might default to `-marm` for `--target=arm-linux-gnueabi` IIRC; maybe `-mthumb` is not being passed in addition to `-march=armv7-m`? https://llvm.org/pr48894 so I would be surprised that `armv7-m` isn't changing the mode to `-mthumb`.

**Comment by arndb** [comment]
I suspect the symptom I reported here was a side-effect of a partial workaround that I had added to Kconfig, forbidding THUMB2_KERNEL when building with CLANG_IAS, but not forbidding ARMv7-M. In normal builds we should always pass -mthumb when building for ARMv7-M or any other configuration that has CONFIG_THUMB2_KERNEL enabled, but with my workaround, Kbuild ended up passing "-march=armv7-M -marm".

I have now verified that ARMv7-M builds work in principle but they run into the same problems that I mentioned in https://github.com/ClangBuiltLinux/linux/issues/1270#issuecomment-768967867

**Comment by nickdesaulniers** [comment]
Closing this then as unreproducible?
