### ISSUE TITLE
clang ias: warning: argument unused during compilation: '-march=armv7-a' [-Wunused-command-line-argument]

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1275]
This seems to happen multiple times during a kernel build:

clang: warning: argument unused during compilation: '-march=armv7-a' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-Wa,-march=armv7-a' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-march=armv7-a' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-Wa,-march=armv7-a' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-march=armv7-a' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-Wa,-march=armv7-a' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-march=armv7-a' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-Wa,-march=armv7-a' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-march=armv7-a' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-Wa,-march=armv7-a' [-Wunused-command-line-argument]

I believe this warning is disabled by default and only enabled in my local tree that has a couple of extra ones, but the option normally does not cause any output.

**Comment by nickdesaulniers** [comment]
Does this look like a dup of https://github.com/ClangBuiltLinux/linux/issues/1195?

**Comment by arndb** [comment]
Yes, closing this one.
