### ISSUE TITLE
clang ias: build failure for CONFIG_SMP_ON_UP

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1277]
This seems to trigger a compile-time assertion in the ALT_SMP() macro:

/git/arm-soc/arch/arm/mm/proc-v7.S:169:111: error: expected absolute expression
 .pushsection ".alt.smp.init", "a" ; .long 9998b - . ;9997: orr r1, r1, #((1 << 0) | (1 << 6))|(3 << 3) ; .if . - 9997b == 2 ; nop ; .endif ; .if . - 9997b != 4 ; .error "ALT_UP() content must assemble to exactly 4 bytes"; .endif ; .popsection
                                                                                                              ^
/git/arm-soc/arch/arm/mm/proc-v7.S:169:147: error: expected absolute expression
 .pushsection ".alt.smp.init", "a" ; .long 9998b - . ;9997: orr r1, r1, #((1 << 0) | (1 << 6))|(3 << 3) ; .if . - 9997b == 2 ; nop ; .endif ; .if . - 9997b != 4 ; .error "ALT_UP() content must assemble to exactly 4 bytes"; .endif ; .popsection
                                                                                                                                                  ^
/git/arm-soc/arch/arm/mm/proc-v7.S:169:164: error: ALT_UP() content must assemble to exactly 4 bytes
 .pushsection ".alt.smp.init", "a" ; .long 9998b - . ;9997: orr r1, r1, #((1 << 0) | (1 << 6))|(3 << 3) ; .if . - 9997b == 2 ; nop ; .endif ; .if . - 9997b != 4 ; .error "ALT_UP() content must assemble to exactly 4 bytes"; .endif ; .popsection

**Comment by nathanchance** [comment]
This looks like #742.

**Comment by arndb** [comment]
Sorry, I was building with clang-11 at first, changed to clang-12 now and don't see this any more.
