### ISSUE TITLE
-Wself-assign in drivers/net/fddi/skfp/pcmplc.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#128]
```
drivers/net/fddi/skfp/pcmplc.c:1257:6: warning: explicitly assigning value of variable
      of type 'int' to itself [-Wself-assign]
        phy = phy ; on_off = on_off ;
        ~~~ ^ ~~~
drivers/net/fddi/skfp/pcmplc.c:1257:21: warning: explicitly assigning value of variable
      of type 'int' to itself [-Wself-assign]
        phy = phy ; on_off = on_off ;
                    ~~~~~~ ^ ~~~~~~
2 warnings generated.
```

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20180920223632.14113-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=6b8e327cfa2dfb9da2bd70326494a1f5ca9968f7

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6b8e327cfa2dfb9da2bd70326494a1f5ca9968f7
