### ISSUE TITLE
clang ias: invalid instruction in arch/arm/mach-omap1/ams-delta-fiq-handler.S:

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1281]
omap1_defconfig builds fail with

```
arch/arm/mach-omap1/ams-delta-fiq-handler.S:249:2: error: invalid instruction, any one of the following would fix this:
 mov r10, #(1 << (((NR_IRQS_LEGACY + 12) - NR_IRQS_LEGACY) % 32)) @ set deferred_fiq bit
 ^
arch/arm/mach-omap1/ams-delta-fiq-handler.S:249:2: note: instruction requires: armv6t2
 mov r10, #(1 << (((NR_IRQS_LEGACY + 12) - NR_IRQS_LEGACY) % 32)) @ set deferred_fiq bit
 ^
arch/arm/mach-omap1/ams-delta-fiq-handler.S:249:2: note: instruction requires: thumb2
 mov r10, #(1 << (((NR_IRQS_LEGACY + 12) - NR_IRQS_LEGACY) % 32)) @ set deferred_fiq bit
 ^

```

I'm not sure what is going wrong here. This is an ARMv4T processor, and kernels are built in arm
mode (thumb1 is not used in the kernel), so the suggested  ".arch armv6t2" would not work.

**Comment by nickdesaulniers** [comment]
`mov` with a register destination and immediate operand has to be the most basic instruction there is on ARM; not sure why it would be restricted to thumb2 mode or the armv6t2 sub arches.

**Comment by nickdesaulniers** [comment]
I wasn't able to reproduce this with ToT LLVM, I suspect this is a dup of #1195 . (Missing `-Wa,-march=` support)

**Comment by nickdesaulniers** [comment]
@arndb sent: https://lore.kernel.org/linux-arm-kernel/20210308153430.2530616-1-arnd@kernel.org/

**Comment by nickdesaulniers** [comment]
perhaps this is reproducible with release versions of clang before the fix from #1195 landed in clang-13?

**Comment by nickdesaulniers** [comment]
huh, I still can reproduce with older clang's I have around...

**Comment by arndb** [comment]
Ah, I think I know what is happening now: my tree contains a few patches to clean up the omap1 platform, and that must have removed an indirect header include. gcc didn't care about that change, but clang (legitimately) complained about it.

**Comment by nickdesaulniers** [comment]
28399a5a6d569c9bdb612345e4933046ca37cde5 v5.12-rc7
