### ISSUE TITLE
Remove unreachable code in fs/ext4/namei.c

### ISSUE THREAD

**Issue by tinti** [ClangBuiltLinux/linux#1282]
Original issue: https://github.com/ClangBuiltLinux/linux/issues/1180

Found by Clang -Wunreachable-code-aggressive.

https://github.com/ClangBuiltLinux/linux/blob/83d09ad4b950651a95d37697f1493c00d888d0db/fs/ext4/namei.c#L830

**Comment by tinti** [comment]
Patch sent.

**Comment by nathanchance** [comment]
We generally want a link to the patch in the tracker and an update to the label to show this has a patch: https://lore.kernel.org/r/20210129185856.158310-1-viniciustinti@gmail.com

**Comment by nickdesaulniers** [comment]
@tinti can you create a label for -Wunreachable-code-aggressive (like we have for other warnings) and tag this and #1284.

**Comment by tinti** [comment]
Patch sent.

https://lore.kernel.org/linux-ext4/20210129185856.158310-1-viniciustinti@gmail.com/

**Comment by tinti** [comment]
> @tinti can you create a label for -Wunreachable-code-aggressive (like we have for other warnings) and tag this and #1284.

done

**Comment by tinti** [comment]
Patch approved.

ext4: factor out htree rep invariant check

**Comment by dileks** [comment]
Now in `<ext4.git#dev>`.

[1] https://git.kernel.org/tytso/ext4/c/c6c818e50d1982ebac4dcd3ae18c1b49a66ebacb
[2] https://git.kernel.org/pub/scm/linux/kernel/git/tytso/ext4.git/log/?h=dev

Update: Use shorter link and add link to <ext4.git#dev>.

**Comment by nickdesaulniers** [comment]
commit: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c6c818e50d1982ebac4dcd3ae18c1b49a66ebacb
merge: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6f9972bbfef57019519e1685254e876913a70463
congrats @tinti !
