### ISSUE TITLE
Remove unreachable code in drivers/gpu/drm/i915/

### ISSUE THREAD

**Issue by tinti** [ClangBuiltLinux/linux#1284]
Original issue: https://github.com/ClangBuiltLinux/linux/issues/1180

Found by Clang -Wunreachable-code-aggressive.

https://github.com/ClangBuiltLinux/linux/blob/83d09ad4b950651a95d37697f1493c00d888d0db/drivers/gpu/drm/i915/display/intel_sdvo.c#L1767
https://github.com/ClangBuiltLinux/linux/blob/83d09ad4b950651a95d37697f1493c00d888d0db/drivers/gpu/drm/i915/display/intel_sdvo.c#L1851

* Becomes unused after removing the code above: https://github.com/ClangBuiltLinux/linux/blob/83d09ad4b950651a95d37697f1493c00d888d0db/drivers/gpu/drm/i915/display/intel_sdvo.c#L696

Found by Clang -Wunreachable-code-aggressive.

https://github.com/ClangBuiltLinux/linux/blob/83d09ad4b950651a95d37697f1493c00d888d0db/drivers/gpu/drm/i915/gt/intel_workarounds.c#L882
https://github.com/ClangBuiltLinux/linux/blob/83d09ad4b950651a95d37697f1493c00d888d0db/drivers/gpu/drm/i915/i915_gpu_error.c#L319

**Comment by tinti** [comment]
Patch sent.

**Comment by nathanchance** [comment]
We generally want a link to the patch in the tracker and an update to the label to show this has a patch: https://lore.kernel.org/r/20210129181519.69963-1-viniciustinti@gmail.com/

**Comment by nickdesaulniers** [comment]
Not sure that there was a follow up that was accepted? Close as wontfix?

**Comment by tinti** [comment]
No follow up.

I agree to close as won't fix.
