### ISSUE TITLE
lld: armv4: ld.lld: warning: lld uses blx instruction, no object with architecture supporting feature detected

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1287]
I get many instances of this warning when building a kernel with CONFIG_CPU_32v4 enabled, e.g. "make moxart_defconfig"

ld.lld: warning: lld uses blx instruction, no object with architecture supporting feature detected
ld.lld: warning: lld uses blx instruction, no object with architecture supporting feature detected
ld.lld: warning: lld uses blx instruction, no object with architecture supporting feature detected
ld.lld: warning: lld uses blx instruction, no object with architecture supporting feature detected

**Comment by nickdesaulniers** [comment]
sounds like LLD warning that it doesn't support ARMv4, since `blx` must have been added later?

**Comment by arndb** [comment]
I use 'ld --fix-v4bx' to turn 'blx' instructions into 'bl' on a combined v4/v4t kernel, which should avoid the use of blx and make it work on pre-v4t processors. It seems that my patch to introduce this was never merged upstream and I should resend that, see https://patchwork.kernel.org/project/linux-arm-kernel/patch/12678426.5oeMNXL25J@wuerfel/

What I found now is that the $(call ld-option, ...) means we silently skip that flag on lld because it is not supported there. I suspect it would actually be easy to support the flag in order to make ARMv4 kernels work with lld.

There are still users on ARMv4 (pre-T) processors, both the Faraday FA526 and the Intel StrongARM, though it is getting fairly rare.

**Comment by nickdesaulniers** [comment]
Can I run linux on my Gameboy Advance? Pretty sure that was arm7tdmi which I think is ARMv4? 🎮 

> gcc-6.0 marks support for ARMv3 and ARMv4 as 'deprecated'

Oh?

> I suspect it would actually be easy to support the flag in order to make ARMv4 kernels work with lld.

I wonder why the linker fixes this up (or warns about it).  Shouldn't the compiler not select such instructions if told `-march=armv4`?

**Comment by arndb** [comment]
> Can I run linux on my Gameboy Advance? Pretty sure that was arm7tdmi which I think is ARMv4? 

It is an "arm7tdmi", but the 't' means that this s ARMv4T, not ARMv4, so it's not relevant here because it has the bx/blx instructions.

While we still support ARM720T, which is an ARM7TDMI with MMU and cache, support for the bare ARM7TDMI was dropped several years ago, so you are out of luck there. ;-)

> > gcc-6.0 marks support for ARMv3 and ARMv4 as 'deprecated'
> 
> Oh?
> 
> > I suspect it would actually be easy to support the flag in order to make ARMv4 kernels work with lld.
> 
> I wonder why the linker fixes this up (or warns about it). Shouldn't the compiler not select such instructions if told `-march=armv4`?

I think the idea is to let you write assembler code that is portable between ARMv4 and ARMv4T: With ARMv4T you have to use bx/blx for every branch that the linker resolves because the branch destination might be in thumb code, while in ARMv4, bx/blx are undefined. Since this is the only difference between the two, it also helps for running code on ARMv4 when the compiler produces ARMv4T code, you just do the conversion during the final link.

**Comment by arndb** [comment]
Correction: ARMv4T added only the BX instruction, while BLX was added later with ARMv5, so both ARMv4 and ARMv4T are currently broken with lld. Also, the warning is apparently not just for BX/BLX instructions from object files passed into the linker, but is about instructions added by the linker itself, which just always uses BLX here.

I suppose we can treat this the same way as big-endian support, which is just fundamentally unsupported in lld until someone has an interest in implementing it.

**Comment by nathanchance** [comment]
Closing since #964 was first.
