### ISSUE TITLE
clang-12: error: unsupported option '--64'

### ISSUE THREAD

**Issue by staalmannen** [ClangBuiltLinux/linux#1289]
This happens at the first instance of the use of "CC":

`CC     scripts/mod/empty.o` 

Arch: x86_64
Kernel : 5.10.11
Clang: 12.0.0 (a855c9403fbac6be8acaf1651932084645a00d11)

Make flags : LLVM=1 LLVM_IA=1

I have been grepping all over the place but i can not find "--64" anywhere. The custom Linux distro (Aalbus) that I am using only has Clang, and the HOSTCC stage is working.

Any ideas where the problem might be?

**Comment by nathanchance** [comment]
Can you run:

```
( set -x; <your_full_regular_make_command> V=1 ) &>build.log
```

And upload the build.log here?

Example:

```
( set -x; make -j8 LLVM=1 LLVM_IAS=1 V=1 ) &>build.log
```

Also, your config would be helpful.

**Comment by nickdesaulniers** [comment]
> Make flags : LLVM=1 LLVM_IA=1

Should be `LLVM_IAS=1` (missing `S`); not sure if that was a typo, or how that would manifest in the observed error.

**Comment by staalmannen** [comment]
> > Make flags : LLVM=1 LLVM_IA=1
> 
> Should be `LLVM_IAS=1` (missing `S`); not sure if that was a typo, or how that would manifest in the observed error.

Oops that was just a typo here on Github. In my make file script (my custom OS uses pkgsrc to package) it is correct.

**Comment by nathanchance** [comment]
`--64` comes from the call to the assembler, which is added by clang based on the target triple:

```
$ make -skj"$(nproc)" LLVM=1 KCFLAGS=-v distclean defconfig init/main.o
...
End of search list.
 "/home/nathan/cbl/toolchains/llvm-binutils/bin/as" --64 -I ./arch/x86/include -I ./arch/x86/include/generated -I ./include -I ./arch/x86/include/uapi -I ./arch/x86/include/generated/uapi -I ./include/uapi -I ./include/generated/uapi -o init/main.o /tmp/main-6aa4ba.s
```

https://github.com/llvm/llvm-project/blob/98768bab19b27db71f497b0e5d87dfa9e5a0f05a/clang/lib/Driver/ToolChains/Gnu.cpp#L725-L730

That `--64` should not be involved with the integrated assembler if I am reading the code correctly. Please make sure that `LLVM_IAS=1` is being properly passed along to `make` so that the integrated assembler is invoked, not an external assembler that might be having other issues.

**Comment by staalmannen** [comment]
> `--64` comes from the call to the assembler, which is added by clang based on the target triple:
> 
> ```
> $ make -skj"$(nproc)" LLVM=1 KCFLAGS=-v distclean defconfig init/main.o
> ...
> End of search list.
>  "/home/nathan/cbl/toolchains/llvm-binutils/bin/as" --64 -I ./arch/x86/include -I ./arch/x86/include/generated -I ./include -I ./arch/x86/include/uapi -I ./arch/x86/include/generated/uapi -I ./include/uapi -I ./include/generated/uapi -o init/main.o /tmp/main-6aa4ba.s
> ```
> 
> https://github.com/llvm/llvm-project/blob/98768bab19b27db71f497b0e5d87dfa9e5a0f05a/clang/lib/Driver/ToolChains/Gnu.cpp#L725-L730
> 
> That `--64` should not be involved with the integrated assembler if I am reading the code correctly. Please make sure that `LLVM_IAS=1` is being properly passed along to `make` so that the integrated assembler is invoked, not an external assembler that might be having other issues.

Thank you! For some reason it was not correctly passed to the make command. I now pass this error and hit another one :) Hopefully one that will be easier to solve by myself.
