### ISSUE TITLE
-Wself-assign in drivers/net/usb/lan78xx.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#129]
```
drivers/net/usb/lan78xx.c:952:11: warning: explicitly assigning value of variable
      of type 'u32' (aka 'unsigned int') to itself [-Wself-assign]
                        offset = offset;
                        ~~~~~~ ^ ~~~~~~
1 warning generated.
```

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20180920224829.17072-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=94e7c844990f0db92418586b107be135b4963b66

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=94e7c844990f0db92418586b107be135b4963b66
