### ISSUE TITLE
Assertion in mm/memcontrol.c when building x86_64 allyesconfig with -O3

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1295]
See upstream bug for more details: https://llvm.org/pr49085

**Comment by nathanchance** [comment]
Patch proposed: https://reviews.llvm.org/D96288

**Comment by dileks** [comment]
@nathanchance 

Are you able to build `x86_64 allyesconfig` with `-O3` optimization :-)?

**Comment by nathanchance** [comment]
Fixed: https://github.com/llvm/llvm-project/commit/0eda4547969e0f5c12af6b4e26afd34ff8c95015

@dileks yes, if I disable `CONFIG_VIDEO_TI_CAL` due to https://github.com/ClangBuiltLinux/linux/issues/1116.
