### ISSUE TITLE
gcc invoked even with passing CC=clang to make

### ISSUE THREAD

**Issue by tstellar** [ClangBuiltLinux/linux#1303]
I'm trying to build the Fedora kernel with clang and the build system is still invoking gcc even when I pass CC=clang to make.  The failing command is:

/usr/bin/make V=1 CC=clang 'HOSTCFLAGS=-O2  -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS --config /usr/lib/rpm/redhat/redhat-hardened-clang.cfg -fstack-protector-strong   -fcommon -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'HOSTLDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now  ' ARCH=x86_64 olddefconfig

gcc: error: unrecognized command-line option '--config'; did you mean '-mpconfig'?
make[1]: *** [scripts/Makefile.host:95: scripts/basic/fixdep] Error 1
make: *** [Makefile:539: scripts_basic] Error 2

The Fedora build scripts runs a lot of commands before this, so I've attached the full [build.log](https://github.com/ClangBuiltLinux/linux/files/5973990/build.log).

**Comment by nathanchance** [comment]
CC is used for compiling the kernel, HOSTCC is used for compiling the host utilities like the `kconfig` tool, which is what is happening in this instance. Specify `HOSTCC=clang` in addition to `CC=clang` for the intended result. Additionally, `LLVM=1` will do that automatically and use all of the LLVM utilities.

**Comment by nickdesaulniers** [comment]
Yes; you should either be doing:

```sh
$ make CC=clang HOSTCC=clang ...
```
or
```sh
$ make LLVM=1 ...
```

**Comment by dileks** [comment]
@tstellar 
Details see [1].

`make LLVM=1` has some benefits but I am not very happy with it.
`make LLVM=1` points to `clang`, `ld.lld`, `llvm-ar`, `llvm-nm` means `without version-suffix` etc.

Cannot speak for Red Hat based distros, but Debian offers the opportunity to co-install several `LLVM toolchain` versions.
`llvm-toolchain-XX` is a meta-package whereof Debian packages like `llvm-12`,  `clang-12` and  `lld-12` (here: XX=12) are generated.
This means in your system's and user's path you will have `clang-12` etc.
Of course you can install `llvm`, `clang` and `lld` metapages, but they differ in XX for Debian stable/testing/unstable/experimental and I suggest not to install them when you plan to use more than one `llvm-toolchain-XX`.
Example: `clang` meta-package in `Debian/bullseye` symlinks to `clang-11`.
@tstellar
How is your distribution organizing its LLVM packages for misc LLVM versions?

To fullfill and as a workaround I added to my linux-kernel build-script:
```sh
### GCC and LLVM version settings
GCC_MAJOR_VER="10"
LLVM_MAJOR_VER="12"

### LLVM toolchain path options
# Explicitly set PATH to simplify LLVM=1 handling (see LLVM tools options)
# Option-1: Use system's LLVM toolchain
# Option-2: Use selfmade LLVM toolchain (here: ThinLTO+PGO optimized via tc-build)
# Option-3: Set custom PATH in ~/.bashrc
##LLVM_TOOLCHAIN_PATH="/usr/lib/llvm-${LLVM_MAJOR_VER}/bin"
LLVM_TOOLCHAIN_PATH="/opt/llvm-toolchain/bin"
if [ -d ${LLVM_TOOLCHAIN_PATH} ]; then
   export PATH="${LLVM_TOOLCHAIN_PATH}:${PATH}"
fi
```
XXX: TODO: Distinguish install-path for misc selfmade llvm-toolchain-XX?

Each time I want to test something in bash with my selfmade LLVM toolchain v12.0.0-rc1 and `make LLVM=1` I have to be very careful.
Mostly, I do a cut'n'paste from my build-script.

Currently, I switched to and use my selfmade `LLVM toolchain v12.0.0-rc1` and will upgrade with each `v12.0.0-rcX` until `v12.0.0 final`.

Why a selfmade LLVM toolchain?
1. stage1-toolchain approx. 10% faster than Debian's equivalent
1. ThinLTO+PGO optimized multistage-toolchain saves here approx. 33% of build-time.

I would like to have an whatever option to pass a custom `LLVM_VER_SUFFIX` to `make`.

[1] https://www.kernel.org/doc/html/latest/kbuild/llvm.html#llvm-utilities
[2] https://sources.debian.org/search/llvm-toolchain-12/
[3] https://packages.debian.org/bullseye/clang

**Comment by tstellar** [comment]
@dileks In Fedora, we just ship one version of the clang/llvm toolchain.  We do provide compatibility packages with older versions of the clang/llvm libraries, but without the executables, like clang, llc, etc.

**Comment by dileks** [comment]
@tstellar
Thanks for the info.
Sometimes it is good to focus on one release/thing.
`Do One Thing And Do It Well.` (Unix philosophy)

**Comment by nickdesaulniers** [comment]
@tstellar please reopen if you still observe GCC invoked when building via `make LLVM=1`, otherwise feel free to open new issues for different bugs.
