### ISSUE TITLE
lld warning "no symbols"

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1306]
ld.lld warns when linking empty object files:

arch/x86/entry/vdso/vdso-note.o: no symbols
ipc/syscall.o: no symbols
mm/highmem.o: no symbols

A lot of these are in fact interesting findings and I have prepared patches to address them by not building source files when all the contents are hidden inside of an #ifdef.

However, the first one above (vdso-note.o) is interesting because it was never meant to contain symbols but only have "note" section. I don't know what triggers the warning from lld, but I am looking for a way to disable it here.

**Comment by MaskRay** [comment]
`no symbols` is a nm/llvm-nm diagnostic. ld.lld does not warn, e.g. `as /dev/null -o a.o; ld.lld a.o`

**Comment by arndb** [comment]
I can see this happening because of CONFIG_TRIM_UNUSED_KSYMS, with both gcc and clang. However, I can no longer make it not happen, so I have absolutely no idea why I never saw it earlier. Closing this report, as it is unrelated to clangbuiltlinux.
