### ISSUE TITLE
undefined symbol: __field_overflow

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1308]
looks like mainline x86 allyesconfig
https://github.com/ClangBuiltLinux/continuous-integration2/runs/1955873191?check_suite_focus=true
and allmodconfig
https://github.com/ClangBuiltLinux/continuous-integration2/runs/1955873540?check_suite_focus=true
have been failing for the past couple days with:
```
ERROR: modpost: "__field_overflow" [drivers/net/ipa/ipa.ko] undefined!
```
(for allmodconfig)
```
ld.lld: error: undefined symbol: __field_overflow
>>> referenced by ipa_main.c
>>>               net/ipa/ipa_main.o:(ipa_probe) in archive drivers/built-in.a
```
(for allyesconfig)

**Comment by nathanchance** [comment]
This is most likely the same problem as #1293, as it is only visible with clang-10.
