### ISSUE TITLE
arch/arm/probes/kprobes/test-thumb.c doesn't build with IAS

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1309]
forked from #1271
CONFIG_ARM_KPROBES_TEST+CONFIG_THUMB2_KERNEL
There's a few errors here, see https://lore.kernel.org/linux-arm-kernel/20210128193422.241155-1-ndesaulniers@google.com/.
https://reviews.llvm.org/D97236 addresses the two easier ones, but I think the rest of the failures are due to IAS missing support for the optional Rd operand. cc @DavidSpickett

**Comment by nickdesaulniers** [comment]
Ok, so two separate issues it looks like.

1. `tbh`, `strexd`, and `ldrexd` do not have optional operands as per the Arm ARM (`F5.1.257 TBB, TBH`, `F5.1.238 STREXD T1 variant`, `F5.1.84 LDREXD T1 variant`). I think this should be fixed in the kernel as per my lore link above.
2. `orns.w`/`orn.w` (`F5.1.128 ORN, ORNS (register) T1  shift or rotate by value variant`), and `rsb.w`/`rsbs.w` (`F5.1.167 RSB, RSBS (register) T1  shift or rotate by value variant` seem to be missing `.w` suffix support.

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D99538 for `ORN`/`ORNS`.

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D99542 for `RSB`/`RSBS`.

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/lkml/20210329221209.1718079-1-ndesaulniers@google.com/T/#u for kernel patch.

**Comment by nickdesaulniers** [comment]
submitted https://www.armlinux.org.uk/developer/patches/viewpatch.php?id=9087/1 to RMK's queue.

**Comment by nathanchance** [comment]
Accepted: http://git.armlinux.org.uk/cgit/linux-arm.git/commit/?id=1500fbc77bd80b4a71569022c0c46af91e22190e

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/linus/8b95a7d90ce8160ac5cffd5bace6e2eba01a871e
