### ISSUE TITLE
__aeabi_ldivmod/__aeabi_uldivmod undefined

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1312]
CI on -next is failing: https://github.com/ClangBuiltLinux/continuous-integration2/runs/1986696432?check_suite_focus=true
```
ERROR: modpost: "__aeabi_ldivmod" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: modpost: "__aeabi_uldivmod" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
```
I suspect someone isn't using the `do_div` macros, breaking 32b? cc @arndb

**Comment by nathanchance** [comment]
Arnd sent a patch for this and someone from AMD replied that they were fixing it themselves:

https://lore.kernel.org/amd-gfx/20210225143339.3693838-1-arnd@kernel.org/

https://lore.kernel.org/amd-gfx/EB1143CA-884E-43A2-A14E-6B909D29F5E8@amd.com/

**Comment by nathanchance** [comment]
Fixed:

https://git.kernel.org/next/linux-next/c/783bf4035cb7f2707ad760fbc06f6be01a553f0a
https://git.kernel.org/next/linux-next/c/a8a2e13486343fe84c54681dd3c43ff926eb5927
