### ISSUE TITLE
Issue around hyp_panic while building aarch64 allmodconfig with ThinLTO

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1317]
On latest ToT Linux (http://git.kernel.org/linus/7a7fd0de4a98):

```
$ cat <<'EOF' > allmod.config
CONFIG_KASAN=n
CONFIG_GCOV_KERNEL=n
CONFIG_LTO_CLANG_THIN=y
EOF

$ make -skj"$(nproc)" ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KCONFIG_ALLCONFIG=1 LLVM=1 LLVM_IAS=1 O=build/aarch64 distclean allmodconfig vmlinux
ld.lld: error: irqbypass.c:(function __guest_enter: .text+0x21CC): relocation R_AARCH64_CONDBR19 out of range: 2031220 is not in [-1048576, 1048575]; references hyp_panic
>>> defined in vmlinux.o

ld.lld: error: irqbypass.c:(function __guest_enter: .text+0x21E0): relocation R_AARCH64_ADR_PREL_LO21 out of range: 2031200 is not in [-1048576, 1048575]; references hyp_panic
>>> defined in vmlinux.o
```

I am guessing this is due to the kernel being sufficiently big although this does not happen as soon as `CONFIG_LTO_CLANG_THIN=y` is dropped from the config.

cc @MaskRay  @samitolvanen

**Comment by samitolvanen** [comment]
Hmm, building arm64 allmodconfig + LTO for commit 7a7fd0de4a9804299793e564a555a49c1fc924cb fails for me a bit earlier with an error about a missing header file:
```
In file included from ../net/bpfilter/main.c:6:
In file included from /usr/include/sys/socket.h:33:
/usr/include/bits/socket.h:354:11: fatal error: 'asm/socket.h' file not found
# include <asm/socket.h>
          ^~~~~~~~~~~~~~
```
Is there a patch I'm missing?

Anyway, I wonder if disabling LTO for `arch/arm64/kvm/hyp` would fix the issue? Something like this:
```diff
diff --git a/arch/arm64/kvm/hyp/Makefile b/arch/arm64/kvm/hyp/Makefile
index 687598e41b21..7f4c84373c08 100644
--- a/arch/arm64/kvm/hyp/Makefile
+++ b/arch/arm64/kvm/hyp/Makefile
@@ -11,3 +11,5 @@ subdir-ccflags-y := -I$(incdir)                               \
                    $(DISABLE_STACKLEAK_PLUGIN)
 
 obj-$(CONFIG_KVM) += vhe/ nvhe/ pgtable.o
+
+KBUILD_CFLAGS := $(filter-out $(CC_FLAGS_LTO), $(KBUILD_CFLAGS))
```

**Comment by samitolvanen** [comment]
OK, disabling `CONFIG_BPFILTER_UMH` allowed me to reproduce the error and disabling LTO for the `hyp` directory fixes this for me.

**Comment by nathanchance** [comment]
Yes, that fixes it for me as well. Feel free to use

```
Reported-by: Nathan Chancellor <nathan@kernel.org>
Tested-by: Nathan Chancellor <nathan@kernel.org>
```

if you send it upstream.

**Comment by samitolvanen** [comment]
https://lore.kernel.org/lkml/20210304184544.2014171-1-samitolvanen@google.com/

**Comment by samitolvanen** [comment]
An actual fix: https://lore.kernel.org/lkml/20210305202124.3768527-1-samitolvanen@google.com/

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/dbaee836d60a8e1b03e7d53a37893235662ba124
