### ISSUE TITLE
powerpc: incorrect offsets in .got or asm

### ISSUE THREAD

**Issue by aik** [ClangBuiltLinux/linux#1318]
Here is the problem asm chunk:
```
start_here_multiplatform:                                          
        /* set up the TOC */                                       
        bl      relative_toc                                       
                                                                   
        /* Clear out the BSS. It may have been done in prom_init,  
         * already but that's irrelevant since prom_init will soon 
         * be detached from the kernel completely. Besides, we need
         * to clear it now for kexec-style entry.                  
         */                                                        
        LOAD_REG_ADDR(r11,__bss_stop)                              
        LOAD_REG_ADDR(r8,__bss_start)                              
```
which becomes this after `lld`:
```
c00000000000cc90 <start_here_multiplatform>:
c00000000000cc90:       f9 f9 ff 4b     bl      c00000000000c688 <relative_toc>
c00000000000cc94:       30 80 62 e9     ld      r11,-32720(r2)
c00000000000cc98:       38 80 02 e9     ld      r8,-32712(r2)
```
The loaded r8 is `0xc000000000000038` (expected `c000000001520000` at `0x8000-32712=0x38`) and r11 is `0xc000000001144380` (expected `c00000000168ae28`) because this is what gets into the `.got` section:
```
/home/aik/pbuild/kernel-llvm/vmlinux:     file format elf64-powerpcle  
Contents of section .got:                                              
 c00000000149eb00 58eb4901 000000c0 00eb4901 000000c0  X.I.......I.....
 c00000000149eb10 28ae6801 000000c0 00005201 000000c0  (.h.......R.....
 c00000000149eb20 6c04dc00 000000c0 00006901 000000c0  l.........i.....
 c00000000149eb30 80431401 000000c0 38000000 000000c0  .C......8.......
```

These are __bss_start/stop and toc values:
```
[fstn1-p1 ~]$ nm ~/pbuild/kernel-llvm/vmlinux | grep __bss_
c000000001520000 D __bss_start
c00000000168ae28 B __bss_stop
[fstn1-p1 ~]$ nm ~/pbuild/kernel-llvm/vmlinux | grep __toc_st
c00000000149eb00 D __toc_start
```
The `relative_toc` correctly returns `0x14a6b00` (which is __toc_start + 0x8000). So it is wrong offsets. These are generated from:
```
#define LOAD_REG_ADDR(reg,name) 
        ld      reg,name@got(r2)
```
It is not just these 2 symbols, every address from `.got` is calculated incorrectly - static strings, for example, __bss_start is just the first one in the booting process.

Building as `~/p/kernel-llvm$ make CC=clang-11 LD=ld.lld-11 AR=llvm-ar-11 NM=llvm-nm-11 STRIP=llvm-strip-11 OBJCOPY=llvm-objcopy-11 OBJDUMP=llvm-objdump-11 READELF=llvm-readelf-11 HOSTCC=clang-11 HOSTCXX=clang++-11 HOSTAR=llvm-ar-11 HOSTLD=ld.lld-11 LLVM_IAS=1  O=~/pbuild/kernel-llvm  -j40 vmlinux`.

The kernel is loaded at 0 and no relocation happened by then.

Removing `LD=ld.lld-11` (i.e. reverting to the binutils' `ld`) FIXES the problem - r8/r11 get expected values and the entire `.got` section gets 200x smaller than with `lld`, and the kernel boots just fine.

I also tried the upstream `lld`, the same broken output. Is this something known? Any hack to try?

**Comment by aik** [comment]
with a bit more digging, in `uint64_t InputSection::getVA() const { return parent->addr + outSecOff; }`, `outSecOff` is set to `0x58` so the actual content of `.got` is shifted by this much, however the assembler does not know that. Is this a useful bit of information?

**Comment by aik** [comment]
```diff --git a/arch/powerpc/kernel/vmlinux.lds.S b/arch/powerpc/kernel/vmlinux.lds.S
index 72fa3c00229a..d101e2d1b37d 100644                                           
--- a/arch/powerpc/kernel/vmlinux.lds.S                                           
+++ b/arch/powerpc/kernel/vmlinux.lds.S                                           
@@ -331,7 +331,7 @@ SECTIONS                                                      
                __toc_start = .;                                                  
 #ifndef CONFIG_RELOCATABLE                                                       
                __prom_init_toc_start = .;                                        
-               arch/powerpc/kernel/prom_init.o*(.toc .got)                       
+               arch/powerpc/kernel/prom_init.o*(.got)
```
fixes the problem which somehow is not a problem with `ld`.

**Comment by nathanchance** [comment]
I wonder if this is in any way related to #811?

cc @MaskRay for LLD and integrated assembler input.

**Comment by MaskRay** [comment]
> Building as `~/p/kernel-llvm$ make CC=clang-11 LD=ld.lld-11 AR=llvm-ar-11 NM=llvm-nm-11 STRIP=llvm-strip-11 OBJCOPY=llvm-objcopy-11 OBJDUMP=llvm-objdump-11 READELF=llvm-readelf-11 HOSTCC=clang-11 HOSTCXX=clang++-11 HOSTAR=llvm-ar-11 HOSTLD=ld.lld-11 LLVM_IAS=1 O=~/pbuild/kernel-llvm -j40 vmlinux`.

Which config do you use? I'll need to play with the output to know the offsets.

OK, from the description my guess is that GNU ld uses the output section `.got` plus 0x8000 as the TOC base while LLD uses the input section `.got` plus 0x8000 as the TOC base.

The ELFv2 ABI says:

> The symbol .TOC. may be used to access the GOT or in TOC-relative addressing to other data constructs, such as the procedure linkage table. The symbol may be offset by 0x8000 bytes, or another offset, from the start of the .got section.

It does not say whether `.got` is the linker synthesized section (input section), or the output section.

I have checked that on both aarch64 and x86-64 ld, their GOT relocations are relative to the linker synthesized section. So for something like:

```
SECTIONS {
  .got : {
     QUAD(1)
     *(.got) /* relative to the linker synthesized .got */
  }
}
```

The computation is relative to `*(.got)`. However, powerpc64 ld diverges here. I'd argue that the linker synthesized section (LLD and ld.bfd on other archs' choice) definitely makes more sense, because you can rename the output section `.got` to something different.

Since ld.lld always uses input section .got + 0x8000 as the TOC base, its computation is consistent, i.e. linker computed r2 value with linker computed TOC offset can give you the correct address into a .toc/.got entry, even if the TOC base is selected differently from GNU ld.

**Comment by aik** [comment]
`0x8000` is expected, `0x8058` is not. I dug a bit more.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/powerpc/kernel/vmlinux.lds.S?h=v5.11#n334 :
```		
		__prom_init_toc_start = .;
		arch/powerpc/kernel/prom_init.o*(.toc .got)
		__prom_init_toc_end = .;
```

There is `.toc` in `prom_init.o`:
```
aik@u2004:~/p/kernel-llvm$ objdump -D -s -j .toc ~/pbuild/kernel-llvm-ld/arch/powerpc/kernel/prom_init.o                                                          
                                                                                 
/home/aik/pbuild/kernel-llvm-ld/arch/powerpc/kernel/prom_init.o:     file format 
elf64-powerpcle                                                                  
                                                                                 
Contents of section .toc:                                                        
 0000 00000000 00000000 00000000 00000000  ................                      
 0010 00000000 00000000 00000000 00000000  ................                      
 0020 00000000 00000000 00000000 00000000  ................                      
 0030 00000000 00000000 00000000 00000000  ................                      
 0040 00000000 00000000 00000000 00000000  ................                      
 0050 00000000 00000000                    ........                              
                                                                                 
Disassembly of section .toc:                                                     
                                                                                 
0000000000000000 <.toc>:                                                         
        ...                                                                      
```
which is not empty. but the result `vmlinux` does not include no `.toc` nor `.got` WHEN LINKED BY `ld`:
```
aik@u2004:~/p/kernel-llvm$ nm ~/pbuild/kernel-llvm-ld/vmlinux | grep _toc_
c00000000149eb00 D __prom_init_toc_end                                    
c00000000149eb00 D __prom_init_toc_start 
c00000000149eb00 D __toc_start
```
but `ld.lld` does include those:
```
aik@u2004:~/p/kernel-llvm$ nm ~/pbuild/kernel-llvm/vmlinux | grep _toc_
c00000000149eb58 D __prom_init_toc_end                                 
c00000000149eb00 D __prom_init_toc_start
c00000000149eb00 D __toc_start                    
```
and this breaks vmlinux.

What is the correct behavior?

My kernel is here: https://github.com/aik/linux/commits/llvm
The latest patch is the config and the exact command line for llvm, the patch before that is "the fix" (i.e. remove `.toc`).
When comparing `ld` and `lld`, I replace `LD=ld.lld-11` with `LD=ld` so the rest - `clang`, `nm`, `ar`, etc are from llvm.

**Comment by aik** [comment]
this works too:
```
--- a/arch/powerpc/kernel/vmlinux.lds.S                    
+++ b/arch/powerpc/kernel/vmlinux.lds.S                    
@@ -328,12 +328,12 @@ SECTIONS                             
        . = ALIGN(256);                                    
        .got : AT(ADDR(.got) - LOAD_OFFSET) {              
-               __toc_start = .;                           
 #ifndef CONFIG_RELOCATABLE                                
                __prom_init_toc_start = .;                 
                arch/powerpc/kernel/prom_init.o*(.toc .got)
                __prom_init_toc_end = .;                   
 #endif                                                    
+               __toc_start = .;                           
                *(.got)                                    
                *(.toc)
```
but i guess it only works as nothing really references `.toc` in prom_init.o as `ld` optimizes it out to zero ( __prom_init_toc_start == __prom_init_toc_end when `ld` is used).

**Comment by aik** [comment]
Looks like reordering input sections messes up the final output from `lld`

**Comment by aik** [comment]
Doing things like this:
```
diff --git a/arch/powerpc/kernel/vmlinux.lds.S b/arch/powerpc/kernel/vmlinux.ld
s.S                                                                            
index 72fa3c00229a..de44c19d93b4 100644                                        
--- a/arch/powerpc/kernel/vmlinux.lds.S                                        
+++ b/arch/powerpc/kernel/vmlinux.lds.S                                        
@@ -329,6 +329,7 @@ SECTIONS                                                   
        . = ALIGN(256);                                                        
        .got : AT(ADDR(.got) - LOAD_OFFSET) {                                  
                __toc_start = .;                                               
+               arch/powerpc/kernel/head_64.o*(.toc .got)                      
 #ifndef CONFIG_RELOCATABLE                                                    
                __prom_init_toc_start = .;                                     
                arch/powerpc/kernel/prom_init.o*(.toc .got)                    
```
breaks it:
```
 LD      .tmp_vmlinux.kallsyms1
ld.lld-11: error: arch/powerpc/kernel/head_64.o:(.text+0x144): relocation R_PPC64_TOC16_DS out of range: -32864 is not in [-32768, 32767]
ld.lld-11: error: arch/powerpc/kernel/head_64.o:(.text+0x374): relocation R_PPC64_TOC16_DS out of range: -32864 is not in [-32768, 32767]                           
ld.lld-11: error: arch/powerpc/kernel/head_64.o:(.text+0x6E4): relocation R_PPC64_TOC16_DS out of range: -32864 is not in [-32768, 32767]
```

**Comment by MaskRay** [comment]
Given the GOT relocation semantics on other architectures, I feel that GNU ld powerpc64 is not doing the right thing. I'd also feel uncomfortable if we have to work around this case in LLD.

To make both GNU ld and LLD work, we can use asm label:
```
% cat a.c
// __attribute__((visibility("hidden")))  optional, the linker defined symbol is hidden anyway.
extern const char __toc_start[] asm(".TOC.");

const char *foo() {
  return __toc_start;
}
```

As long as the source code usage of `__toc_start` matches the linker `.TOC`, the actual TOC base value does not matter.

**Comment by MaskRay** [comment]
What about this? I am not versed in kernel testing. The following works fine for me.

```zsh
PATH=/tmp/RelA/bin:$PATH make -k -j 50 ARCH=powerpc CROSS_COMPILE=powerpc64le-linux-gnu- LLVM=1 O=/tmp/out/ppc64 -j 50 powernv_defconfig zImage.epapr V=1
# Enable CONFIG_PPC_OF_BOOT_TRAMPOLINE=y
~/Dev/ClangBuiltLinux/boot-utils/boot-qemu.sh -a ppc64le -k /tmp/out/ppc64
```

```patch
From 6b019dc26a997bb9d5021067189e191d15910d35 Mon Sep 17 00:00:00 2001
From: Fangrui Song <>
Date: Fri, 5 Mar 2021 19:28:05 -0800
Subject: [PATCH] Replace __toc_start + 0x8000 with .TOC.

Unlike other architectures, GNU ld's ppc64 port defines .TOC. relative
to the .got output section instead of the linker synthesized .got input
section. LLD defines .TOC. as the .got input section plus 0x8000.  When
CONFIG_PPC_OF_BOOT_TRAMPOLINE=y, arch/powerpc/kernel/prom_init.o is
built, and LLD computed .TOC. can be different from __toc_start defined
by the linker script.

Simplify kernel_toc_addr with asm label .TOC. so that we can get rid of
__toc_start, and make the linker script work with both GNU ld and LLD.

Link: https://github.com/ClangBuiltLinux/linux/issues/1318
Reported-by: Alexey Kardashevskiy <>
Signed-off-by: Fangrui Song <>
---
 arch/powerpc/boot/crt0.S            |  2 +-
 arch/powerpc/boot/zImage.lds.S      |  1 -
 arch/powerpc/include/asm/sections.h | 10 ++--------
 arch/powerpc/kernel/head_64.S       |  2 +-
 arch/powerpc/kernel/vmlinux.lds.S   |  1 -
 5 files changed, 4 insertions(+), 12 deletions(-)

diff --git a/arch/powerpc/boot/crt0.S b/arch/powerpc/boot/crt0.S
index 1d83966f5ef6..e45907fe468f 100644
--- a/arch/powerpc/boot/crt0.S
+++ b/arch/powerpc/boot/crt0.S
@@ -28,7 +28,7 @@ p_etext:	.8byte	_etext
 p_bss_start:	.8byte	__bss_start
 p_end:		.8byte	_end
 
-p_toc:		.8byte	__toc_start + 0x8000 - p_base
+p_toc:		.8byte	.TOC. - p_base
 p_dyn:		.8byte	__dynamic_start - p_base
 p_rela:		.8byte	__rela_dyn_start - p_base
 p_prom:		.8byte	0
diff --git a/arch/powerpc/boot/zImage.lds.S b/arch/powerpc/boot/zImage.lds.S
index d6f072865627..32cf7816292f 100644
--- a/arch/powerpc/boot/zImage.lds.S
+++ b/arch/powerpc/boot/zImage.lds.S
@@ -39,7 +39,6 @@ SECTIONS
   . = ALIGN(256);
   .got :
   {
-    __toc_start = .;
     *(.got)
     *(.toc)
   }
diff --git a/arch/powerpc/include/asm/sections.h b/arch/powerpc/include/asm/sections.h
index 324d7b298ec3..bd22ca0b5eca 100644
--- a/arch/powerpc/include/asm/sections.h
+++ b/arch/powerpc/include/asm/sections.h
@@ -48,14 +48,8 @@ static inline int in_kernel_text(unsigned long addr)
 
 static inline unsigned long kernel_toc_addr(void)
 {
-	/* Defined by the linker, see vmlinux.lds.S */
-	extern unsigned long __toc_start;
-
-	/*
-	 * The TOC register (r2) points 32kB into the TOC, so that 64kB of
-	 * the TOC can be addressed using a single machine instruction.
-	 */
-	return (unsigned long)(&__toc_start) + 0x8000UL;
+	extern unsigned long toc asm(".TOC.");
+	return (unsigned long)(&toc);
 }
 
 static inline int overlaps_interrupt_vector_text(unsigned long start,
diff --git a/arch/powerpc/kernel/head_64.S b/arch/powerpc/kernel/head_64.S
index ece7f97bafff..9542d03b2efe 100644
--- a/arch/powerpc/kernel/head_64.S
+++ b/arch/powerpc/kernel/head_64.S
@@ -899,7 +899,7 @@ _GLOBAL(relative_toc)
 	blr
 
 .balign 8
-p_toc:	.8byte	__toc_start + 0x8000 - 0b
+p_toc:	.8byte	.TOC. - 0b
 
 /*
  * This is where the main kernel code starts.
diff --git a/arch/powerpc/kernel/vmlinux.lds.S b/arch/powerpc/kernel/vmlinux.lds.S
index 72fa3c00229a..c28f4e5bae3f 100644
--- a/arch/powerpc/kernel/vmlinux.lds.S
+++ b/arch/powerpc/kernel/vmlinux.lds.S
@@ -328,7 +328,6 @@ SECTIONS
 
 	. = ALIGN(256);
 	.got : AT(ADDR(.got) - LOAD_OFFSET) {
-		__toc_start = .;
 #ifndef CONFIG_RELOCATABLE
 		__prom_init_toc_start = .;
 		arch/powerpc/kernel/prom_init.o*(.toc .got)
-- 
2.30.1.766.gb4fecdf3b7-goog

```

**Comment by aik** [comment]
This is quite a change, huh.

With this change, `ld` keeps producing bootable `vmlinux`, `lld` still produces `vmlinux` which does not boot, however it runs much further now and fails when copying from `ibm_architecture_vec_template` which is `__initconst` (==`.init.rodata`?) and which is zeroes by the time we reach https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/powerpc/kernel/prom_init.c?h=v5.11#n1323

**Comment by MaskRay** [comment]
Thanks for the testing. That issue may be unrelated to the .got issue.

Sent [[PATCH] Replace __toc_start + 0x8000 with .TOC.](https://lore.kernel.org/linuxppc-dev/20210307051433.2756645-1-maskray@google.com/)

**Comment by aik** [comment]
It seems it is.
```
aik@u2004:~/p/kernel-llvm$ nm ~/pbuild/kernel-llvm/vmlinux | grep _bss_
c000000001520000 D __bss_start                                         
c00000000168ae28 B __bss_stop                                          
```
The kernel is loaded at `0x40.0000` but at https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/powerpc/kernel/prom_init.c?h=v5.11#n3340 `&__bss_start` is still `c000000001520000` and not `c000000001920000`. So `memset` clears `.init.rodata`.

**Comment by aik** [comment]
We have a better candidate which works with `ld` and `lld`: https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20210309045638.GI6042@bubble.grove.modra.org/

**Comment by MaskRay** [comment]
`__toc_ptr = DEFINED (.TOC.) ? .TOC. : ADDR (.got) + 0x8000;` needs https://reviews.llvm.org/D98306 (target: LLD 13.0.0)

> I've also changed the way .got is aligned in vmlinux.lds and zImage.lds, mostly so that dumping out section info by objdump or
readelf plainly shows the alignment is 256.  This linker script feature was added 2005-09-27, available in FSF binutils releases from 2.17 onwards.  Should be safe to use in the kernel, I think.

This clarified a question puzzling me for some time :) Why do the kernel linker scripts prefer `. = ALIGN(something); section : { ...}` to `section : ALIGN(something) { ... }`? Because this is a binutils 2.17 feature (when the early `. = ALIGN(...);` were added, binutils 2.17 did not exist yet)

**Comment by nickdesaulniers** [comment]
> Because this is a binutils 2.17 feature (when the early . = ALIGN(...); were added, binutils 2.17 did not exist yet)

If the kernel's minimum supported version of GNU binutils is 2.23, should we send a cleanup to LKML for the linker scripts?

**Comment by MaskRay** [comment]
> > Because this is a binutils 2.17 feature (when the early . = ALIGN(...); were added, binutils 2.17 did not exist yet)
> 
> If the kernel's minimum supported version of GNU binutils is 2.23, should we send a cleanup to LKML for the linker scripts?

`. = ALIGN(align); section : { ...}` has a minor nice property: by comparing the output sh_addralign value and the specified `align` value, you can know whether a section is overaligned. With `section : ALIGN(align) { ... }`, it is difficult to know it. So I do not know whether we do the cleanup.

https://lld.llvm.org/ELF/linker_script.html#output-section-alignment

**Comment by nickdesaulniers** [comment]
@aik [sent this patch](https://lore.kernel.org/llvm/20211221055904.555763-2-aik@ozlabs.ru/) from Alan Modra that addresses this. @mpe [accepted it into powerpc/next](https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?h=next&id=a3ad84da076009c94969fa97f604257667e2980f).

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/a3ad84da076009c94969fa97f604257667e2980f
