### ISSUE TITLE
CFI: warning: objtool: .text.__cfi_check_fail: unexpected end of section

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/linux#1319]
I reported the issue in [1].

With `clang-cfi` Git on top of `Linux v5.12-rc1` I still see on `x86-64`:
```
$ grep warning: build-log_5.12.0-rc1-6-amd64-clang13-cfi.txt | grep 'unexpected end of section' | wc -l
3892
```

Example:
```
virt/lib/irqbypass.lto.o: warning: objtool: .text.__cfi_check_fail: unexpected end of section
```

[1] https://groups.google.com/g/clang-built-linux/c/sJ4ZToNEMI0/m/MIuUYKgqAAAJ

**Comment by dileks** [comment]
@samitolvanen 

Attached is my linux-config.

[config-5.12.0-rc1-6-amd64-clang13-cfi.txt](https://github.com/ClangBuiltLinux/linux/files/6079503/config-5.12.0-rc1-6-amd64-clang13-cfi.txt)

**Comment by dileks** [comment]
My LLVM/Clang version:
```
$ /opt/llvm-toolchain/bin/clang -v
dileks clang version 13.0.0 (https://github.com/llvm/llvm-project.git 1e46b6f4012399a2fef5fbbb4ed06fc919835414)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm-toolchain/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```

**Comment by dileks** [comment]
With `clang-lto` (`CONFIG_LTO_CLANG=y` and `CONFIG_LTO_CLANG_THIN=y`) in `Linux v5.12-rc1` I do not see these warnings.

**Comment by dileks** [comment]
CC @jpoimboe

**Comment by nathanchance** [comment]
I think that is what this patch is supposed to fix:

https://lore.kernel.org/r/d743f4b36e120c06506567a9f87a062ae03da47f.1611263462.git.jpoimboe@redhat.com/

but Josh did not have time to deal with the segfaulting that you and Sami reported:

https://lore.kernel.org/r/CABCJKueaW1BEEBKLQzyp77VwTL+bE4x=kOLV3TWmc1s6-r3PeQ@mail.gmail.com/
https://lore.kernel.org/r/20210123022609.n7xsj2a4potoijz7@treble/

**Comment by dileks** [comment]
Can re-test `[PATCH v2 11/20] objtool: Add CONFIG_CFI_CLANG support` (if it fits here) after my current build has finished.

**Comment by dileks** [comment]
With `LLVM` version `12.0.0-rc3` I do not see these warnings.

**Comment by samitolvanen** [comment]
I added commit c64324916d6be72b188b923e60aabd62a52aab3d to the CFI tree. It's similar to Josh's patch, but looks up the symbol from the relocation in the jump table instead of relying on the name. It should fix this issue as well.

**Comment by nickdesaulniers** [comment]
@samitolvanen credit @dileks with a reported by tag and link to this issue?

**Comment by dileks** [comment]
@samitolvanen @nickdesaulniers 

Thanks for the patch.
All what I can say (like Forrest G.) when checking for all warnings:
```
$ grep -i warning: build-log_5.12.0-rc6-5-amd64-clang12-cfi.txt 
19:WARNING: unmet direct dependencies detected for ADI_AXI_ADC
31:dpkg-architecture: warning: specified GNU system type x86_64-linux-gnu does not match CC system type x86_64-unknown-linux-gnu, try setting a correct CC environment variable
52132:arch/x86/crypto/chacha-x86_64.lto.o: warning: objtool: chacha_2block_xor_avx512vl() falls through to next function chacha_8block_xor_avx512vl()
52133:arch/x86/crypto/chacha-x86_64.lto.o: warning: objtool: chacha_4block_xor_avx512vl() falls through to next function chacha_8block_xor_avx512vl()
```
All known warnings.

The good news:
The warning reported in this BR is gone.

The bad news:
I applied latest `clang-cfi` and can NOT boot on bare metal.
On top of my setup with identical custom patchset (includes latest net and some x86 stuff) which works with `clang-lto`.
In QEMU it stops with not showing the call-trace I see when I boot on bare metal.

**Comment by dileks** [comment]
The call-trace on my screen when booted on bare metal:
```
? stop_self
? __cond_resched
? mutex_lock
perf_event_exit_cpu
? acpi_processor_notifier
perf_reboot
blocking_notifier_call_chain
? do_thaw_all
? __xas_next.cfi_jt
process_one_work
worker_thread
? kswapd
? kswapd
? kswapd
kthread
? xenbus_thread
ret_from_fork
...
```
This loops and I see again above block.

If this is a different issue I can open a new issue.

**Comment by dileks** [comment]
I have generate a `vmlinux.map` with `CONFIG_VMLINUX_MAP=y`:
```
ffffffff81c3f190          1c3f190       20    16         vmlinux.o:(.text..L.cfi.jumptable.7583)
ffffffff81c3f190          1c3f190       20     1                 xas_find_conflict.cfi_jt
ffffffff81c3f198          1c3f198       20     1                 xas_load.cfi_jt
ffffffff81c3f1a0          1c3f1a0       20     1                 __xas_prev.cfi_jt
ffffffff81c3f1a8          1c3f1a8       20     1                 __xas_next.cfi_jt
```

I can provide the full `vmlinux.map` file if desired.

**Comment by nathanchance** [comment]
Building with `CONFIG_CFI_PERMISSIVE=y` should make it easier to dump a dmesg for full analysis.

**Comment by dileks** [comment]
@nathanchance 

Damn.
Yeah, I have `CONFIG_CFI_PERMISSIVE=n`.
Will retry...

**Comment by dileks** [comment]
NOPE on bare metal (same call-trace I typed manually ^^^) and NOPE with QEMU.

**Comment by nathanchance** [comment]
Do you have a config handy?

**Comment by samitolvanen** [comment]
> credit @dileks with a reported by tag and link to this issue?

This isn't the bug that the patch fixes, this one was caused by the incomplete earlier objtool workaround that's dropped now. Happy to credit Sedat for testing and reporting bugs, of course!

**Comment by dileks** [comment]
Here we go.

[config-5.12.0-rc6-6-amd64-clang12-cfi.txt](https://github.com/ClangBuiltLinux/linux/files/6287389/config-5.12.0-rc6-6-amd64-clang12-cfi.txt)
[start-build_5.12.0-rc6-6-amd64-clang12-cfi.txt](https://github.com/ClangBuiltLinux/linux/files/6287391/start-build_5.12.0-rc6-6-amd64-clang12-cfi.txt)
[v5.12-rc6..5.12.0-rc6-6-amd64-clang12-cfi.diff.gz](https://github.com/ClangBuiltLinux/linux/files/6287392/v5.12-rc6.5.12.0-rc6-6-amd64-clang12-cfi.diff.gz)
[patches_series.txt](https://github.com/ClangBuiltLinux/linux/files/6287393/patches_series.txt)

**Comment by samitolvanen** [comment]
> The call-trace on my screen when booted on bare metal:

Thank you again for testing! This is most likely caused by CFI jump tables not being mapped with entry code anymore. If the kernel boots without PTI, or bringing back commit 98817a81b62561e8cd7e8b896cc2959647341044 fixes the boot issue, that would confirm it.

I'm guessing we need `function_nocfi()` in a few other places too, probably in ACPI code somewhere. See commit b4af5a96b020f10499cbbf46e3e6ae39ec13565f for other examples. I will take a closer look at the configs next week.

**Comment by dileks** [comment]
Did not notice you dropped `[PATCH] x86: map CFI jump tables in pti_clone_entry_text`.

Hmmm, header file changed.

Complete new build for me.

**Comment by dileks** [comment]
Above applies cleanly.

Is `[PATCH] x86: avoid jump tables in IDT and entry points` mandory or optional?
It does not appy cleanly against latest clang-cfi Git.

[1] https://github.com/ClangBuiltLinux/linux/commit/b4af5a96b020f10499cbbf46e3e6ae39ec13565f.patch

**Comment by samitolvanen** [comment]
> Did not notice you dropped "[PATCH] x86: map CFI jump tables in pti_clone_entry_text".

Yes, that was a temporary fix to allow x86 to boot with PTI + CFI, but mapping jump tables is not exactly ideal for security here. We also previously ended up storing jump table addresses in IDT and syscall entry point registers, which did work when the jump tables were mapped, but also hurt performance.

**Comment by samitolvanen** [comment]
> Is `[PATCH] x86: avoid jump tables in IDT and entry points` mandory or optional?
> It does not appy cleanly against latest clang-cfi Git.

Commit b4af5a96b020f10499cbbf46e3e6ae39ec13565f is part of the clang-cfi tree already. It's needed, so we don't need commit 98817a81b62561e8cd7e8b896cc2959647341044.

**Comment by dileks** [comment]
Before I build a new kernel I need clear instrucrions: Do I need both patches?

**Comment by samitolvanen** [comment]
> Before I build a new kernel I need clear instrucrions: Do I need both patches?

Yes, please test with both patches. I suspect we are still pointing some entry point to the jump table, which means applying `x86: map CFI jump tables in pti_clone_entry_text` should fix the boot issue. If it doesn't, this is caused by something else.

**Comment by dileks** [comment]
OK, I see:
```
$ git log --oneline v5.12-rc6..for-5.12/clang-cfi-samitolvanen-20210408 | grep 'x86: avoid jump tables in IDT and entry points'
b4af5a96b020 x86: avoid jump tables in IDT and entry points
```

So, I only need `x86: map CFI jump tables in pti_clone_entry_text`.

**Comment by dileks** [comment]
@samitolvanen 

With that patch applied I can boot.

**Comment by samitolvanen** [comment]
Thanks for confirming!

The reason this fails to boot is that `CONFIG_XEN_PV` still points some interrupt handlers to the jump table. Disabling CFI for `kernel/paravirt.o` and `xen/enlighten_pv.o` (see commit ba0764bd9c57b35713908d3dca1ef5315e5de2b3) fixes the boot issue for me in qemu, but I suspect there still might be some CFI failures when one actually uses Xen.

@dileks please let me know if you see any further issues with the latest [clang-cfi](https://github.com/samitolvanen/linux/commits/clang-cfi) tree.

**Comment by dileks** [comment]
@samitolvanen 

Yes, I can confirm I was able to build and boot on bare metal with latest `clang-cfi` up to `commit d90ea82de0bf ("kconfig: add LTO and CFI config fragments")`.
Thanks!

**Comment by dileks** [comment]
@samitolvanen 

Feel free to add my `Tested-by: Sedat Dilek <sedat.dilek@gmail.com>` to `commit ba0764b`.

**Comment by samitolvanen** [comment]
Great, thank you for testing!
