### ISSUE TITLE
implement -Wa,--version

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1320]
https://lore.kernel.org/linux-kbuild/20210303183333.46543-3-masahiroy@kernel.org/ from @masahir0y mentions that clang doesn't support -Wa,--version.  We should implement this and test it works w/ and w/o `-no-integrated-as`. (cc @jcai19 )

**Comment by nathanchance** [comment]
Should it just output the same thing as `clang --version`?

**Comment by jcai19** [comment]
-Wa,--version works with "clang --no-integrated-as". I have submitted a patch for review to support this flag with -integrated-as: https://reviews.llvm.org/D99556

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/rG3cc3c0f8352ec33ca2f2636f94cb1d85fc57ac16 thanks @jcai19 !
