### ISSUE TITLE
Faild to build qcacld-3.0 on msm-5.4 kernel

### ISSUE THREAD

**Issue by atomsand** [ClangBuiltLinux/linux#1323]
Hi, so sorry to disturb you. I recently failed to compile qcacld-3.0 drivers on a msm-5.4 kernel using clang-13. Here's the error I encountered:
```../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:26:10: fatal error: 'wlan_hdd_includes.h' file not found```
The tag of the qcacld is `LA.UM.9.14.r1-12600-LAHAINA.0`, and I try to use other tag for msm-4.19 platform which have no problem in msm-4.19 tree but still encountered the same error, I presumed it's related to some changes in the linux-5.4.
The source I'm using is  https://github.com/atomsand/android_kernel_xiaomi_sm8350/tree/wip
and the build script is:
```
#!/bin/bash
set -e
CBL_PATH=${HOME}/ClangBuiltLinux/bin
export ARCH=arm64
export PATH=${CBL_PATH}:${PATH}
args="-j$(nproc --all) \
O=out \
CROSS_COMPILE=aarch64-linux-gnu- \
CLANG_TRIPLE=aarch64-linux-gnu- \
CC=clang \
LD=ld.lld"
make ${args} haydn-qgki_defconfig
make ${args} 2>&1 | tee build.log
```
Thanks in advance for your help.

**Comment by nathanchance** [comment]
Your script can be much simpler:

```shell
#!/bin/bash

set -e

export PATH=${HOME}/ClangBuiltLinux/bin:${PATH}

make \
-j$(nproc --all) \
O=out \
ARCH=arm64 \
CROSS_COMPILE=aarch64-linux-gnu- \
CLANG_TRIPLE=aarch64-linux-gnu- \
CC=clang \
LD=ld.lld \
haydn-qgki_defconfig all 2>&1 | tee build.log
```

No target to `make` means the `all`  target is used so you can avoid multiple calls to `make` by just adding the defconfig and all targets.

As for your actual build error, I am not sure. Does it work with older versions of clang, as I cannot imagine that this is a compiler issue. Based on Xiaomi's README, it seems like the version of qcacld-3.0 that you should be using is `LA.UM.9.14.r1-11500-LAHAINA.0`, unless you have based on a newer tag. Getting qcacld-3.0 to build properly in tree has gotten harder and harder over time.

**Comment by atomsand** [comment]
Doesn't work with older tags nor Xiaomi's OSS either😭, maybe I should just load the prebuilt kernel module in the system...
