### ISSUE TITLE
-Walign-mismatch in include/linux/efi.h

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1327]
New warning from ToT LLVM (https://github.com/llvm/llvm-project/commit/7e5cea5b509f5535eab6d1ea9b90e033570758a6):

```
In file included from drivers/firmware/efi/mokvar-table.c:35:
include/linux/efi.h:1093:34: warning: passing 1-byte aligned argument to 4-byte aligned parameter 2 of 'get_var' may result in an unaligned pointer access [-Walign-mismatch]
        status = get_var(L"SecureBoot", &EFI_GLOBAL_VARIABLE_GUID, NULL, &size,
                                        ^
include/linux/efi.h:1101:24: warning: passing 1-byte aligned argument to 4-byte aligned parameter 2 of 'get_var' may result in an unaligned pointer access [-Walign-mismatch]
        get_var(L"SetupMode", &EFI_GLOBAL_VARIABLE_GUID, NULL, &size, &setupmode);
                              ^
2 warnings generated.
```

This is the only instance of this warning that I see so far but it is crazy noisy as `include/linux/efi.h` appears to be included a lot so once that is fixed, others might come forward.

I can try to take a look at resolving this tomorrow unless someone beats me to it.

cc @ardbiesheuvel

**Comment by nathanchance** [comment]
I am testing https://lore.kernel.org/r/20210310081210.95147-1-ardb@kernel.org/.

**Comment by dileks** [comment]
Compile-tested `efi: use 32-bit alignment for efi_guid_t literals` from [1] with `LLVM/Clang v12.0.0-rc3` on x86-64.

[1] https://git.kernel.org/ardb/c/295a2a7d5fd9ff0e1fd50d5265297464888cbfef

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=fb98cc0b3af2ba4d87301dff2b381b12eee35d7d

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/fb98cc0b3af2ba4d87301dff2b381b12eee35d7d
