### ISSUE TITLE
-Walign-mismatch in block/blk-mq.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1328]
```
block/blk-mq.c:630:39: warning: passing 8-byte aligned argument to 32-byte aligned parameter 2 of 'smp_call_function_single_async' may result in an unaligned pointer access [-Walign-mismatch]
                smp_call_function_single_async(cpu, &rq->csd);
                                                    ^
1 warning generated.
```

Reported upstream due to the history behind it: https://lore.kernel.org/r/20210310182307.zzcbi5w5jrmveld4@archlinux-ax161/

**Comment by nathanchance** [comment]
Some links:

https://git.kernel.org/linus/966a967116e69
https://git.kernel.org/linus/4ccafe032005
https://lore.kernel.org/r/a9beb452-7344-9e2d-fc80-094d8f5a0394@kernel.dk/

My suggestion for a fix:

https://lore.kernel.org/r/20210310225240.4epj2mdmzt4vurr3@archlinux-ax161/

**Comment by nickdesaulniers** [comment]
@jcai19 also sent a patch for this: https://lore.kernel.org/lkml/20210330230249.709221-1-jiancai@google.com/

@groeck links to: http://crbug.com/1193732

**Comment by nickdesaulniers** [comment]
@davidbolvansky cc'ed me on https://reviews.llvm.org/D100037 which looks somewhat related to this.

**Comment by groeck** [comment]
On 4/7/21 11:34 AM, Nick Desaulniers wrote:
> @davidbolvansky <https://github.com/davidbolvansky> cc'ed me on https://reviews.llvm.org/D100037 which looks somewhat related to this.
> 
I can't comment there, but from the context it appears that "was introduces"
should be "was introduced", not "introduces".

Guenter

**Comment by nathanchance** [comment]
Patch sent to disable the warning for the one problematic translation unit: https://lore.kernel.org/r/20210408194458.501617-1-nathan@kernel.org/

**Comment by jcai19** [comment]
cc @m-gupta

**Comment by jcai19** [comment]
cc @cjdb

**Comment by nickdesaulniers** [comment]
If creating an unaligned pointer is UB...

> 6.3.2.3 Pointers 7 (N2176 ISO/IEC 9899:2017)
> A pointer to an object type may be converted to a pointer to a different object type. If the resulting
pointer is not correctly aligned) for the referenced type, the behavior is undefined.

I wonder if we should be detecting whether the address of the pointer is at runtime a multiple of the larger aligned type and casting else `memcpy`ing the unaligned struct to an aligned-alloc'ed struct of the larger alignment, then passing a pointer to that, then `free`ing it.

How else do you solve such issues trying to use data that that's currently underaligned from what a caller expects, safely? Making a copy of the data is the only thing that comes to mind.

**Comment by arndb** [comment]
Posted a new patch: https://lore.kernel.org/lkml/20210429150940.3256656-1-arnd@kernel.org/

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=locking/urgent&id=1139aeb1c521eb4a050920ce6c64c36c4f2a3ab7

(Will need to backport to stable)

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/1139aeb1c521eb4a050920ce6c64c36c4f2a3ab7

I can do the backports tomorrow.

**Comment by nathanchance** [comment]
Backports submitted: https://lore.kernel.org/r/YJmneuxxFWIrqyWN@archlinux-ax161/

I expect these to be picked up and released within the next couple of weeks so I am closing this up for now.
