### ISSUE TITLE
mcount problem on RISC-V

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1331]
While investigating the kernel solution to #1268, I uncovered an issue with `mcount` for RISC-V that is visible prior to https://git.kernel.org/linus/afc76b8b80112189b6f11e67e19cf58301944814:

```
$ make -skj"$(nproc)" ARCH=riscv CC=clang CROSS_COMPILE=riscv64-linux-gnu- O=build/riscv distclean defconfig all
...
riscv64-linux-gnu-ld: init/main.o: in function `__traceiter_initcall_level':
(.text+0xe): undefined reference to `mcount'
riscv64-linux-gnu-ld: init/main.o: in function `__traceiter_initcall_start':
(.text+0x4e): undefined reference to `mcount'
riscv64-linux-gnu-ld: init/main.o: in function `__traceiter_initcall_finish':
(.text+0x92): undefined reference to `mcount'
riscv64-linux-gnu-ld: init/main.o: in function `.LBB32_28':
main.c:(.text+0x30c): undefined reference to `mcount'
riscv64-linux-gnu-ld: init/main.o: in function `free_initmem':
(.text+0x54c): undefined reference to `mcount'
riscv64-linux-gnu-ld: init/main.o:main.c:(.text+0x6c2): more undefined references to `mcount' follow
```

This appears to be because `scripts/recordmcount.pl` expects `_mcount`, which is the name of the symbol that GCC uses:

```
$ echo 'int main(void) { return 0; }' | riscv64-linux-gcc -c -mno-relax -pg -o tmp.o -x c -

$ llvm-objdump -dr tmp.o

tmp.o:  file format elf64-littleriscv


Disassembly of section .text:

0000000000000000 <main>:
       0: 41 11         addi    sp, sp, -16
       2: 06 e4         sd      ra, 8(sp)
       4: 22 e0         sd      s0, 0(sp)
       6: 00 08         addi    s0, sp, 16
       8: 86 87         mv      a5, ra
       a: 3e 85         mv      a0, a5
       c: 97 00 00 00   auipc   ra, 0
                000000000000000c:  R_RISCV_CALL _mcount
      10: e7 80 00 00   jalr    ra
      14: 81 47         mv      a5, zero
      16: 3e 85         mv      a0, a5
      18: a2 60         ld      ra, 8(sp)
      1a: 02 64         ld      s0, 0(sp)
      1c: 41 01         addi    sp, sp, 16
      1e: 82 80         ret

$ echo 'int main(void) { return 0; }' | clang -c -mno-relax -pg -o tmp.o --target=riscv64-linux-gnu -x c -

$ llvm-objdump -dr tmp.o

tmp.o:  file format elf64-littleriscv


Disassembly of section .text:

0000000000000000 <main>:
       0: 01 11         addi    sp, sp, -32
       2: 06 ec         sd      ra, 24(sp)
       4: 22 e8         sd      s0, 16(sp)
       6: 00 10         addi    s0, sp, 32
       8: 97 00 00 00   auipc   ra, 0
                0000000000000008:  R_RISCV_CALL_PLT     mcount
       c: e7 80 00 00   jalr    ra
      10: 01 45         mv      a0, zero
      12: 23 26 a4 fe   sw      a0, -20(s0)
      16: 42 64         ld      s0, 16(sp)
      18: e2 60         ld      ra, 24(sp)
      1a: 05 61         addi    sp, sp, 32
      1c: 82 80         ret
```

There are two fixes that will be needed for this it seems, both of which I have local fixes for, I just need to do more involved testing.

1. clang should emit `_mcount` instead of `mcount`. We will still probably need to work around this in `scripts/recordmcount.pl` with the following change

```diff
diff --git a/scripts/recordmcount.pl b/scripts/recordmcount.pl
index 867860ea57da..7b83a1aaec98 100755
--- a/scripts/recordmcount.pl
+++ b/scripts/recordmcount.pl
@@ -392,7 +392,7 @@ if ($arch eq "x86_64") {
     $mcount_regex = "^\\s*([0-9a-fA-F]+):.*\\s_mcount\$";
 } elsif ($arch eq "riscv") {
     $function_regex = "^([0-9a-fA-F]+)\\s+<([^.0-9][0-9a-zA-Z_\\.]+)>:";
-    $mcount_regex = "^\\s*([0-9a-fA-F]+):\\sR_RISCV_CALL\\s_mcount\$";
+    $mcount_regex = "^\\s*([0-9a-fA-F]+):\\sR_RISCV_CALL\\s_?mcount\$";
     $type = ".quad";
     $alignment = 2;
 } elsif ($arch eq "nds32") {
```

but I think that clang and GCC should match in case that gets rejected. Tentative diff:

```diff
diff --git a/clang/lib/Basic/Targets/OSTargets.h b/clang/lib/Basic/Targets/OSTargets.h
index 539466c4f678..66d14a70658c 100644
--- a/clang/lib/Basic/Targets/OSTargets.h
+++ b/clang/lib/Basic/Targets/OSTargets.h
@@ -417,6 +417,7 @@ public:
     case llvm::Triple::ppcle:
     case llvm::Triple::ppc64:
     case llvm::Triple::ppc64le:
+    case llvm::Triple::riscv64:
       this->MCountName = "_mcount";
       break;
     case llvm::Triple::x86:
```

2. There is a `R_RISCV_CALL_PLT` relocation to `mcount` instead of `R_RISCV_CALL`, which will be missed by `scripts/recordmcount.pl`. This change should work I believe, although I am not sure if there are any unintended consequences with this:

```diff
diff --git a/scripts/recordmcount.pl b/scripts/recordmcount.pl
index 867860ea57da..7b83a1aaec98 100755
--- a/scripts/recordmcount.pl
+++ b/scripts/recordmcount.pl
@@ -392,7 +392,7 @@ if ($arch eq "x86_64") {
     $mcount_regex = "^\\s*([0-9a-fA-F]+):.*\\s_mcount\$";
 } elsif ($arch eq "riscv") {
     $function_regex = "^([0-9a-fA-F]+)\\s+<([^.0-9][0-9a-zA-Z_\\.]+)>:";
-    $mcount_regex = "^\\s*([0-9a-fA-F]+):\\sR_RISCV_CALL\\s_mcount\$";
+    $mcount_regex = "^\\s*([0-9a-fA-F]+):\\sR_RISCV_CALL(_PLT)?\\s_mcount\$";
     $type = ".quad";
     $alignment = 2;
 } elsif ($arch eq "nds32") {
```

**Comment by nickdesaulniers** [comment]
> There is a R_RISCV_CALL_PLT relocation to mcount instead of R_RISCV_CALL
> I am not sure if there are any unintended consequences with this

Probably worth discussing upstream (LLVM) with @topperc @jrtc27 @MaskRay , it might be nice to avoid trips through the PLT.

**Comment by nathanchance** [comment]
LLVM patch submitted: https://reviews.llvm.org/D98881

Kernel patch series to follow.

**Comment by nathanchance** [comment]
Tentative series: https://git.kernel.org/pub/scm/linux/kernel/git/nathan/linux.git/log/?h=riscv-ftrace-fixes

I would like the LLVM patch to be merged before I send it due to the fourth patch.

**Comment by jrtc27** [comment]
Re https://git.kernel.org/pub/scm/linux/kernel/git/nathan/linux.git/commit/?h=riscv-ftrace-fixes&id=725a0d669b68b2a5fd3ca4a1366c38300f4c0505: would it not be better/simpler to just provide `mcount` as an alias for `_mcount`? Then you can drop the changes to ftrace.h (and don't need version detection, it can unconditionally exist until the baseline is sufficiently high).

**Comment by nathanchance** [comment]
Thank you for the suggestion! Something like this maybe? Forgive me, my assembly is not good at all.

```diff
diff --git a/arch/riscv/kernel/mcount.S b/arch/riscv/kernel/mcount.S
index 8a5593ff9ff3..b69a7e5e18e9 100644
--- a/arch/riscv/kernel/mcount.S
+++ b/arch/riscv/kernel/mcount.S
@@ -49,6 +49,8 @@ ENTRY(ftrace_stub)
 #ifdef CONFIG_DYNAMIC_FTRACE
        .global _mcount
        .set    _mcount, ftrace_stub
+       .global mcount
+       .set    mcount, _mcount
 #endif
        ret
 ENDPROC(ftrace_stub)
@@ -78,6 +80,7 @@ ENDPROC(return_to_handler)
 #endif

 #ifndef CONFIG_DYNAMIC_FTRACE
+SYM_FUNC_START_ALIAS(mcount)
 ENTRY(_mcount)
        la      t4, ftrace_stub
 #ifdef CONFIG_FUNCTION_GRAPH_TRACER
@@ -125,5 +128,7 @@ do_trace:
        RESTORE_ABI_STATE
        ret
 ENDPROC(_mcount)
+SYM_FUNC_END_ALIAS(mcount)
 #endif
+EXPORT_SYMBOL(mcount)
 EXPORT_SYMBOL(_mcount)
```

**Comment by MaskRay** [comment]
> > There is a R_RISCV_CALL_PLT relocation to mcount instead of R_RISCV_CALL
> > I am not sure if there are any unintended consequences with this
> 
> Probably worth discussing upstream (LLVM) with @topperc @jrtc27 @MaskRay , it might be nice to avoid trips through the PLT.

The difference does not matter (there is some hard-to-explain GNU ld implementation difference which should not be relied upon by any application). R_RISCV_CALL could be deprecated in the future. https://github.com/riscv/riscv-elf-psabi-doc/issues/98

> Thank you for the suggestion! Something like this maybe? Forgive me, my assembly is not good at all.

I don't know the implication of `EXPORT_SYMBOL(mcount)`... If it does something quite special, then I might prefer the previous version. If `EXPORT_SYMBOL` is not that special, `.set    mcount, _mcount` looks good to me.

**Comment by nathanchance** [comment]
`EXPORT_SYMBOL` is for making the symbol available to kernel modules. You can see the logic here, I am not sure what the implications of it are in relation to the `.set mcount, _mcount`:

https://elixir.bootlin.com/linux/v5.11.7/source/include/asm-generic/export.h#L35

https://elixir.bootlin.com/linux/v5.11.7/source/include/asm-generic/export.h#L82

**Comment by MaskRay** [comment]
I prefer the previous patch that only one `EXPORT_SYMBOL` is added. Having two `EXPORT_SYMBOL` can be confusing... given that its pros (slightly simplified code) is outweighed by the cons...

**Comment by nathanchance** [comment]
Sure, I am fine with the first version of that patch, which I do not think is too invasive. I will send that series after https://reviews.llvm.org/D98881 is merged (I will push an updated version of that patch shortly).

**Comment by nathanchance** [comment]
LLVM side is done: https://github.com/llvm/llvm-project/commit/ef58ae86ba778ed7d01cd3f6bd6d08f943abab44

I will push the kernel patches tomorrow.

**Comment by nathanchance** [comment]
https://lore.kernel.org/r/20210325223807.2423265-1-nathan@kernel.org/

**Comment by nathanchance** [comment]
Linux kernel patches accepted:

https://git.kernel.org/riscv/c/c7f5f5e5b4026b69acf9ae2b92e86edfba9f7750
https://git.kernel.org/riscv/c/f426c499144676eda4f74c21b2de325eb9ea5737

**Comment by nathanchance** [comment]
Merged into mainline:

https://git.kernel.org/torvalds/c/2f095504f4b9
https://git.kernel.org/torvalds/c/7ce047715030
https://git.kernel.org/torvalds/c/adebc8817b5c
