### ISSUE TITLE
-Wunused-function in kernel/sched/fair.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1335]
Building an arm64 allnoconfig kernel image results in the warning on -next:
```
kernel/sched/fair.c:8387:13: warning: unused function 'update_nohz_stats' [-Wunused-function]
static bool update_nohz_stats(struct rq *rq)
            ^
```

**Comment by tinti** [comment]
Patch submitted https://lore.kernel.org/patchwork/patch/1404596/

**Comment by dileks** [comment]
@tinti 

In which official Git tree was `v2` `Accepted`?
If yes, do you have a link?
( I expected to see v2 in tip Git. )

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=sched/core&id=3f5ad91488e813026f8c5f46b839e91a83912703

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/3f5ad91488e813026f8c5f46b839e91a83912703
