### ISSUE TITLE
-Wunused-function in arch/powerpc/boot/inffast.c

### ISSUE THREAD

**Issue by tinti** [ClangBuiltLinux/linux#1339]
Building a powerpc ppc44x_defconfig kernel image results in the warning on mainline:

arch/powerpc/boot/inffast.c:20:1: warning: unused function 'get_unaligned16' [-Wunused-function]

**Comment by tinti** [comment]
Similar issue different solution https://lore.kernel.org/r/9e4edaa0061c4de2b3b1a7aa53987b94@AcuMS.aculab.com/

**Comment by nathanchance** [comment]
Pretty sure this is a duplicate of #664.

**Comment by tinti** [comment]
Indeed. Thanks Nathan.
