### ISSUE TITLE
inconsistent ORC unwind table entries in file: vmlinux in /scripts/sorttable vmlinux

### ISSUE THREAD

**Issue by tpgxyz** [ClangBuiltLinux/linux#1341]
I'm compiling kernel-5.11.11 with `CONFIG_UNWINDER_ORC=y` and it fails with below error only if `ld.lld` is default linker.

```
+ '[' -n y -a -n y ']'
+ info BTFIDS vmlinux
+ '[' '' '!=' silent_ ']'
  BTFIDS  vmlinux
+ printf '  %-7s %s\n' BTFIDS vmlinux
+ ./tools/bpf/resolve_btfids/resolve_btfids vmlinux
+ '[' -n y ']'
+ info SORTTAB vmlinux
+ '[' '' '!=' silent_ ']'
+ printf '  %-7s %s\n' SORTTAB vmlinux
  SORTTAB vmlinux
+ sorttable vmlinux
+ ./scripts/sorttable vmlinux
inconsistent ORC unwind table entries in file: vmlinux
+ echo Failed to sort kernel tables
Failed to sort kernel tables
+ exit 1
+ on_exit
+ '[' 1 -ne 0 ']'
+ cleanup
+ rm -f .btf.vmlinux.bin.o
+ rm -f .tmp_System.map
+ rm -f .tmp_vmlinux.btf .tmp_vmlinux.kallsyms1 .tmp_vmlinux.kallsyms1.S .tmp_vmlinux.kallsyms1.o .tmp_vmlinux.kallsyms2 .tmp_vmlinux.kallsyms2.S .tmp_vmlinux.kallsyms2.o
+ rm -f System.map
+ rm -f vmlinux
+ rm -f vmlinux.o
make: *** [Makefile:1169: vmlinux] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.KO6cPq (%build)
```

More logs can be found here https://abf.openmandriva.org/build_lists/35417

**Comment by nathanchance** [comment]
Relevant piece of code: https://github.com/torvalds/linux/blob/2d743660786ec51f5c1fefd5782bbdee7b227db0/scripts/sorttable.h#L278-L286

**Comment by nickdesaulniers** [comment]
If we split those 3 cases into 3 distinct prints, then we can tell perhaps which we were failing.

**Comment by nathanchance** [comment]
Can you please post the configuration file? I cannot really decipher your build system's output to generate it. I would appreciate you doing that in the future :)

**Comment by tpgxyz** [comment]
@nathanchance Our source is here https://github.com/OpenMandrivaAssociation/kernel-release
There you can find defconfig for this kernel build flavour:
https://github.com/OpenMandrivaAssociation/kernel-release/blob/master/x86_64-desktop-gcc-omv-defconfig

**Comment by nathanchance** [comment]
Appears to be caused by turning on `--icf=safe` by default. I broke down your LLD defaults patches into individual pieces and bisected them:

```
$ git bisect log
# bad: [55aa0a97bd2e564b5dd1006bf183c8e27321896d] optimize
# good: [d28af7c654d8db0b68c175db5ce212d74fb5e9bc] remove -fpch-codegen and -fpch-debuginfo from Clang 12.0 release notes
git bisect start 'HEAD' 'origin/release/12.x'
# good: [b352c148083ace4331eb5a69862a4600103c15f1] gnuHash
git bisect good b352c148083ace4331eb5a69862a4600103c15f1
# bad: [39adb0f87c754045b1789f9b9938fd4c4b474dd0] icf
git bisect bad 39adb0f87c754045b1789f9b9938fd4c4b474dd0
# good: [070357666fefba0dde748f0cd6766f2c096727de] warnCommon
git bisect good 070357666fefba0dde748f0cd6766f2c096727de
# first bad commit: [39adb0f87c754045b1789f9b9938fd4c4b474dd0] icf

$ git log --oneline origin/release/12.x^..
55aa0a97bd2e (HEAD -> release/12.x) optimize
a955943d862c buildId
39adb0f87c75 icf
070357666fef warnCommon
b352c148083a gnuHash
388a6260a17b gcSections
60ef9d325f57 enableNewDtags
f5b72abeda59 asNeeded
d28af7c654d8 (tag: llvmorg-12.0.0-rc5, origin/release/12.x) remove -fpch-codegen and -fpch-debuginfo from Clang 12.0 release notes
```

The second condition (`orc_size % sizeof(struct orc_entry) != 0`) is the one that is getting tripped over.

**Comment by nickdesaulniers** [comment]
consider adding `--icf=none` to your kernel builds if you're going to turn on `--icf=safe` by default.

**Comment by nickdesaulniers** [comment]
@broonie suggested we just explicitly use `--icf=none` explicitly upstream. Reopening.

**Comment by nathanchance** [comment]
If I remember correctly, adding `--icf=none` did not resolve the issue for me when I was bisecting but I did not make a note of it here so I could be wrong. @tpgxyz noted in the mentioned issue that there might be places where `KBUILD_LDFLAGS` is getting overwritten so adding this option to the global linker flags might not prevent the issue. We should audit `KBUILD_LDFLAGS` to make sure they are not getting overwritten anywhere then add this flag.

**Comment by samzeter** [comment]
I don't mind having a look at this again, but I'm having a hard time working out the build steps necessary to reproduce this issue. The original https://abf.openmandriva.org/build_lists/35417 is broken, and I'm not sure on which patches are needed on the Mandriva side to make this happen.

**Comment by nathanchance** [comment]
@samzeter You will need to apply OpenMadriva's `--icf=safe` patch to your LLVM build: https://raw.githubusercontent.com/OpenMandrivaAssociation/llvm/9242aee530e63358611629c222a1a971047dbb0a/lld-default-settings.patch

Then you should be able to use [their config](https://raw.githubusercontent.com/OpenMandrivaAssociation/kernel-release/81a938352b03c71b7d2d869b87ad5ca24ba8cab8/x86_64-desktop-gcc-omv-defconfig) to reproduce it with `LLVM=1`.

If that does not reproduce, let me know!

**Comment by tpgxyz** [comment]
@samzeter Hi, we fixed it differently, as we want to keep `--icf=safe --gc-sections` as global setting, so overwriting these for specific build did the trick.

```
		BUILD_LD="ld.lld --icf=none --no-gc-sections"
		BUILD_KBUILD_LDFLAGS="-Wl,--icf=none -Wl,--no-gc-sections"
```

See here:
https://github.com/OpenMandrivaAssociation/kernel-release/blob/2d51a203f51edd270b4126fc329febd20299d53e/kernel-release.spec#L1204
and one patch that is needed
https://github.com/OpenMandrivaAssociation/kernel-release/blob/master/linux-5.11-disable-ICF-for-CONFIG_UNWINDER_ORC.patch
