### ISSUE TITLE
fail nicer when clang-tidy isn't installed and `make clang-analyzer` is invoked

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1342]
via: https://lore.kernel.org/lkml/20210407190727.GN25319@zn.tnic/T/#m1aa816a19eb4f8b7ba2ddc082e8c3efe2c55b8c9
Suggested-by: Borislav Petkov <bp@alien8.de>

when trying to use clang's static analyzers to build the linux kernel via:
$ make LLVM=1 clang-analyzer

if the user doesn't have clang-tidy installed, their build will fail with a python trace.  We should be able to fail nicer with a clearer error message that the user needs to install clang-tidy.

**Comment by nickdesaulniers** [comment]
I believe @MontigyFerriot has patches for this. Probably worth sending to the list.

**Comment by nickdesaulniers** [comment]
series: https://lore.kernel.org/lkml/20210520231821.12272-1-maciej.falkowski9@gmail.com/

@masahir0y had feedback for @MontigyFerriot to address.

**Comment by nickdesaulniers** [comment]
wontfix based on https://lore.kernel.org/lkml/53282d70-c217-d65e-2d30-7a5593d6c585@gmail.com/. Thanks anyways for the patches @MontigyFerriot !

**Comment by m-falkowski** [comment]
I think this issue is still valid @nickdesaulniers. The mentioned series is related to a second part of the patchset that is dropped, unfortunately. This issue hasn't got any attention from Kbuild maintainers, as I hadn't cc them. I think I might just resent the patch.

**Comment by nickdesaulniers** [comment]
> I think I might just resent the patch.

Sure, feel free to reopen this issue if you resend and we'll track it.
