### ISSUE TITLE
undefined symbol: __compiletime_assert_177 in firmware/stratix10-rsu.o

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1346]
32b arm allmodconfig/allyesconfig builds are failing with:
```
ld.lld: error: undefined symbol: __compiletime_assert_177
>>> referenced by stratix10-rsu.c
>>>               firmware/stratix10-rsu.o:(rsu_status_callback) in archive drivers/built-in.a

ld.lld: error: undefined symbol: __compiletime_assert_192
>>> referenced by stratix10-rsu.c
>>>               firmware/stratix10-rsu.o:(rsu_status_callback) in archive drivers/built-in.a
```

**Comment by nathanchance** [comment]
I just looked into this and was about to file an issue myself :)

Not a clang problem and should be fixed on latest -next:

https://lore.kernel.org/r/20210321184650.10926-1-krzysztof.kozlowski@canonical.com/

https://git.kernel.org/next/linux-next/c/38ad957b04c5c2c9effc6336365187dae1301051
