### ISSUE TITLE
"error: expected assembly-time absolute expression" in arch/arm64/kernel/entry.S

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1347]
From CI: https://github.com/ClangBuiltLinux/continuous-integration2/runs/2310456680?check_suite_focus=true

In a similar manner to #1078, commit [`747aa9f8ebffa`](https://git.kernel.org/arm64/c/747aa9f8ebffa897c013ae745e52449406c48259) ("arm64: mte: Ensure TIF_MTE_ASYNC_FAULT is set atomically") in the arm64 tree breaks the integrated assembler:

```
$ make -skj"$(nproc)" ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1 O=build/arm64 distclean defconfig arch/arm64/kernel/entry.o
...
<instantiation>:5:7: error: expected assembly-time absolute expression
 .org . - (664b-663b) + (662b-661b)
      ^
<instantiation>:6:7: error: expected assembly-time absolute expression
 .org . - (662b-661b) + (664b-663b)
      ^
<instantiation>:5:7: error: expected assembly-time absolute expression
 .org . - (664b-663b) + (662b-661b)
      ^
...
```

Reading back through #1078, it seems it is the `.arch_extension lse` that causes the issues although it seems like https://reviews.llvm.org/D69411 should have resolved this?

Applying a similar fix as before (moving the `.org` before the `.previous`) to the `alternative_endif` macro works (although I have no idea if that has other side effects in this case).

```diff
diff --git a/arch/arm64/include/asm/alternative-macros.h b/arch/arm64/include/asm/alternative-macros.h
index 5df500dcc627..98e2ab2b6b6c 100644
--- a/arch/arm64/include/asm/alternative-macros.h
+++ b/arch/arm64/include/asm/alternative-macros.h
@@ -169,11 +169,11 @@
  */
 .macro alternative_endif
 664:
+       .org    . - (664b-663b) + (662b-661b)
+       .org    . - (662b-661b) + (664b-663b)
        .if .Lasm_alt_mode==0
        .previous
        .endif
-       .org    . - (664b-663b) + (662b-661b)
-       .org    . - (662b-661b) + (664b-663b)
 .endm

 /*
```

cc @jcai19 @samitolvanen @willdeacon

**Comment by samitolvanen** [comment]
> Reading back through #1078, it seems it is the `.arch_extension lse` that causes the issues although it seems like https://reviews.llvm.org/D69411 should have resolved this?

I don't believe this was ever completely fixed, because it wasn't entirely trivial due to the one-pass assembler design. Please correct me if I'm wrong @jcai19.
 
> Applying a similar fix as before (moving the `.org` before the `.previous`) to the `alternative_endif` macro works (although I have no idea if that has other side effects in this case).

Your patch looks good to me. The `.org` statements are here only to ensure that the alternative sequences have the exact same length. Moving them into the subsection is perfectly fine, because they don't change anything in the binary.

**Comment by jcai19** [comment]
> > Reading back through #1078, it seems it is the `.arch_extension lse` that causes the issues although it seems like https://reviews.llvm.org/D69411 should have resolved this?
> 
> I don't believe this was ever completely fixed, because it wasn't entirely trivial due to the one-pass assembler design. Please correct me if I'm wrong @jcai19.

Agreed. IAS represents a section as a link list of data blocks called fragments before finalizing it. https://reviews.llvm.org/D69411 only supports cases when .foo and .bar in .foo - .bar are both in the same fragment. My guess is that the two symbols in the reported failures are in different fragments, whose differences of offsets within the enclosing section may be subject to changes and therefore cannot be resolved until their finalization. I will take a further look and see if there's anything we can do in LLVM.

**Comment by nickdesaulniers** [comment]
Reduced test case:
```asm
 .subsection 1
661:
 .align 2
662:
663:
664:
 .previous
 .org . - (662b-661b) + (664b-663b)
 .org . - (662b-661b)
 .org . - (664b-663b)
```

**Comment by nathanchance** [comment]
Is it worth making that change everywhere that it might be relevant in the future or should I just send that patch as is (with an appropriate commit message)?

**Comment by nickdesaulniers** [comment]
The only other use I see is arch/riscv/include/asm/alternative-macros.h? Oh, arch/arm64/include/asm/alternative-macros.h also has that pattern in assembler macros (3 groups of 2 in total in that file). Probably worth making the same change for `alternative_insn` on L92-104 and `__ALTERNATIVE_CFG` on L46-61.  `__ALTERNATIVE_CFG` has a comment above it that the `.org` directives are meant to be more portable to older versions of GAS.

**Comment by nathanchance** [comment]
Patch submitted: https://lore.kernel.org/r/20210414000803.662534-1-nathan@kernel.org/

**Comment by jcai19** [comment]
In the repo from https://github.com/ClangBuiltLinux/linux/issues/1347#issuecomment-818257147, .subsection creates a new subsection and pushes it onto the top of subsection stack, and then .previous swaps the then top subsection before the .subsection call back, and therefore label 661 locates in a different subsection from 662, 663 and 664. The differences of labels in different subsections are not fixed at parsing time, as technically the code being parsed could call .subsection later and inserts data into either subsection, which would change the offset of labels. This again boils down to the limitation of the one-pass nature of IAS unfortunately.

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git/commit/?id=22315a2296f4

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/22315a2296f4
