### ISSUE TITLE
arch/arm64/kernel/vdso/gettimeofday.S in stable/linux-4.19.y failed to build with LLVM_IAS=1

### ISSUE THREAD

**Issue by jcai19** [ClangBuiltLinux/linux#1349]
Building failed with the "error: too many positional arguments".

Steps for reproduce:
$ ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- make LLVM=1 LLVM_IAS=1 defconfig
$ ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- make -j32 LLVM=1 LLVM_IAS=1 V=1 arch/arm64/kernel/vdso/gettimeofday.o

arch/arm64/kernel/vdso/gettimeofday.S:230:24: error: too many positional arguments
 clock_gettime_return, shift=1
                       ^
arch/arm64/kernel/vdso/gettimeofday.S:253:24: error: too many positional arguments
 clock_gettime_return, shift=1
                       ^
arch/arm64/kernel/vdso/gettimeofday.S:274:24: error: too many positional arguments
 clock_gettime_return, shift=1

**Comment by jcai19** [comment]
cc @nathanchance

It seems like IAS cannot parse the comma between macro name and arguments. The following diff fixed the problem.

```diff
---
 arch/arm64/kernel/vdso/gettimeofday.S | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/arch/arm64/kernel/vdso/gettimeofday.S b/arch/arm64/kernel/vdso/gettimeofday.S
index 856fee6d3512..7ee685d9adfc 100644
--- a/arch/arm64/kernel/vdso/gettimeofday.S
+++ b/arch/arm64/kernel/vdso/gettimeofday.S
@@ -122,7 +122,7 @@ x_tmp		.req	x8
 9998:
 	.endm
 
-	.macro clock_gettime_return, shift=0
+	.macro clock_gettime_return shift=0
 	.if \shift == 1
 	lsr	x11, x11, x12
 	.endif
@@ -227,7 +227,7 @@ realtime:
 	seqcnt_check fail=realtime
 	get_ts_realtime res_sec=x10, res_nsec=x11, \
 		clock_nsec=x15, xtime_sec=x13, xtime_nsec=x14, nsec_to_sec=x9
-	clock_gettime_return, shift=1
+	clock_gettime_return shift=1
 
 	ALIGN
 monotonic:
@@ -250,7 +250,7 @@ monotonic:
 		clock_nsec=x15, xtime_sec=x13, xtime_nsec=x14, nsec_to_sec=x9
 
 	add_ts sec=x10, nsec=x11, ts_sec=x3, ts_nsec=x4, nsec_to_sec=x9
-	clock_gettime_return, shift=1
+	clock_gettime_return shift=1
 
 	ALIGN
 monotonic_raw:
@@ -271,7 +271,7 @@ monotonic_raw:
 		clock_nsec=x15, nsec_to_sec=x9
 
 	add_ts sec=x10, nsec=x11, ts_sec=x13, ts_nsec=x14, nsec_to_sec=x9
-	clock_gettime_return, shift=1
+	clock_gettime_return shift=1
 
 	ALIGN
 realtime_coarse:
-- 
```

**Comment by nathanchance** [comment]
This is "fixed" by the rewrite of the vDSO into C: https://git.kernel.org/linus/28b1a824a4f44da46983cd2c3249f910bd4b797b

That diff seems fine to carry downstream if you do not want to do something similar to Android (which was a pretty massive backport series): https://android-review.googlesource.com/c/kernel/common/+/1294668

**Comment by jcai19** [comment]
@m-gupta @groeck 

Ah I see! Thanks for the link. The backports do look massive. Edited: I sent a patch for stable 4.19 branch: https://lore.kernel.org/stable/CA+SOCLL28Hej9zMmKJpU5vffVGviDo59uG=kWm0zPtCyZodR5g@mail.gmail.com/T/#t

**Comment by nathanchance** [comment]
I provided some feedback to try and move this along upstream: https://lore.kernel.org/r/YJMJAiwMPqlWmr8Y@archlinux-ax161/

**Comment by jcai19** [comment]
Thanks for the feedback! Will update the patch.

**Comment by nathanchance** [comment]
Patch is accepted and queued for the next 4.19 release in a couple of days: https://lore.kernel.org/r/16206352882063@kroah.com/

**Comment by nickdesaulniers** [comment]
4.19.y: a921d014868c5ab97f286efcf3149999d76765be
