### ISSUE TITLE
-Wenum-conversion in drivers/net/wireless/realtek/rtlwifi/btcoexist/halbtcoutsrc.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#135]
```
drivers/net/wireless/realtek/rtlwifi/btcoexist/halbtcoutsrc.c:1327:34: warning: implicit
      conversion from enumeration type 'enum btc_chip_interface' to different
      enumeration type 'enum wifionly_chip_interface' [-Wenum-conversion]
                wifionly_cfg->chip_interface = BTC_INTF_PCI;
                                             ~ ^~~~~~~~~~~~
drivers/net/wireless/realtek/rtlwifi/btcoexist/halbtcoutsrc.c:1330:34: warning: implicit
      conversion from enumeration type 'enum btc_chip_interface' to different
      enumeration type 'enum wifionly_chip_interface' [-Wenum-conversion]
                wifionly_cfg->chip_interface = BTC_INTF_USB;
                                             ~ ^~~~~~~~~~~~
drivers/net/wireless/realtek/rtlwifi/btcoexist/halbtcoutsrc.c:1333:34: warning: implicit
      conversion from enumeration type 'enum btc_chip_interface' to different
      enumeration type 'enum wifionly_chip_interface' [-Wenum-conversion]
                wifionly_cfg->chip_interface = BTC_INTF_UNKNOWN;
                                             ~ ^~~~~~~~~~~~~~~~
3 warnings generated.
```

**Comment by nathanchance** [comment]
Real patch: https://lore.kernel.org/lkml/20180921220824.18344-1-natechancellor@gmail.com/

Staging patch: https://lore.kernel.org/lkml/20180921221202.20448-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
v2 sent because apparently I can't focus when writing commit messages

https://lore.kernel.org/lkml/20180923063114.11446-1-natechancellor@gmail.com/

https://lore.kernel.org/lkml/20180923063300.12202-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Staging patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/staging.git/commit/?id=8de447ea9d0196d5ce54d96ab19e2a9c5d763ad8

Main driver patch has been acked, I'm assuming Kalle will pick it up soon.

**Comment by nathanchance** [comment]
Main driver patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/kvalo/wireless-drivers-next.git/commit/?id=31138a827d1b3d6e4855bddb5a1e44e7b32309c0

**Comment by nathanchance** [comment]
Main driver patch merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=31138a827d1b3d6e4855bddb5a1e44e7b32309c0

Will close when the staging patch makes it in.

**Comment by nathanchance** [comment]
Staging patch merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8de447ea9d0196d5ce54d96ab19e2a9c5d763ad8
