### ISSUE TITLE
[LTO] objtool: unsupported stack pointer realignment

### ISSUE THREAD

**Issue by telans** [ClangBuiltLinux/linux#1352]
```
vmlinux.o: warning: objtool: aesni_gcm_init_avx_gen2()+0x12: unsupported stack pointer realignment
vmlinux.o: warning: objtool: aesni_gcm_enc_update_avx_gen2()+0x12: unsupported stack pointer realignment
vmlinux.o: warning: objtool: aesni_gcm_dec_update_avx_gen2()+0x12: unsupported stack pointer realignment
vmlinux.o: warning: objtool: aesni_gcm_finalize_avx_gen2()+0x12: unsupported stack pointer realignment
vmlinux.o: warning: objtool: aesni_gcm_init_avx_gen4()+0x12: unsupported stack pointer realignment
vmlinux.o: warning: objtool: aesni_gcm_enc_update_avx_gen4()+0x12: unsupported stack pointer realignment
vmlinux.o: warning: objtool: aesni_gcm_dec_update_avx_gen4()+0x12: unsupported stack pointer realignment
vmlinux.o: warning: objtool: aesni_gcm_finalize_avx_gen4()+0x12: unsupported stack pointer realignment
vmlinux.o: warning: objtool: sha1_transform_avx2()+0xc: unsupported stack pointer realignment
vmlinux.o: warning: objtool: sha1_ni_transform()+0x7: unsupported stack pointer realignment
vmlinux.o: warning: objtool: sha256_transform_rorx()+0x13: unsupported stack pointer realignment
vmlinux.o: warning: objtool: sha512_transform_ssse3()+0x13: unsupported stack pointer realignment
vmlinux.o: warning: objtool: sha512_transform_avx()+0x13: unsupported stack pointer realignment
vmlinux.o: warning: objtool: sha512_transform_rorx()+0x7: unsupported stack pointer realignment
```

With `make LLVM=1 LLVM_IAS=1 -j17`
Building 5.12-rc7 with LLVM and friends 12.0.0
Using a custom `.config` that suits my needs. I only see these when using either Thin LTO or Full LTO

[.config](https://github.com/ClangBuiltLinux/linux/files/6328566/default.config.txt)

**Comment by dileks** [comment]
AFAICS, that is a duplicate but I cannot find the origin CBL bug-no.

Try @jpoimboe `objtool-crypto` Git see [1].

I tried with Linux `v5.12-rc7` and LLVM toolchain `v12.0.0` final successfully.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/jpoimboe/linux.git/log/?h=objtool-crypto

**Comment by dileks** [comment]
@telans

That Git tree is what I have in my latest custom patchset to fix these warnings.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/jpoimboe/linux.git/log/?h=objtool/core

**Comment by telans** [comment]
Confirmed, thanks. Sorry for the noise. I assume this will be merged sometime soon? I'm not familiar with the kernel patch/branch workflow

Should this be labelled `[PATCH] Accepted` or should I just close the issue?

**Comment by nathanchance** [comment]
That thread might need to be pinged, I do not see that patchset in [linux-next](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/) or [tip](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/).

**Comment by dileks** [comment]
@telans
Yes, this is with Clang-ThinLTO.

@nathanchance 
I have this stuff approx. 6 weeks in my custom patchset, but was not aware this is not in tip-x86 or linux-next Git.

@jpoimboe
What is your plan with your `objtool-crypto` fixes?

**Comment by jpoimboe** [comment]
Thanks for the reminder, we'll try to get the objtool crypto patches in for the upcoming 5.13 merge window.

**Comment by dileks** [comment]
@jpoimboe

Cool, Thanks.

**Comment by dileks** [comment]
Nice update in <tip.git#objtool/core>.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/log/?h=objtool/core

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/03b2cd72aad1103127282f39c614e4722e5d9e8f

Thanks @jpoimboe!
