### ISSUE TITLE
CFI: Fix inline assembly references to static functions

### ISSUE THREAD

**Issue by samitolvanen** [ClangBuiltLinux/linux#1354]
With ThinLTO+CFI, the compiler renames all static functions because it relies on unique names to build the jump table. This breaks inline assembly code that refers to these functions by name. In some cases we can work around the issue by marking the function global, or by adding a global wrapper with a stable name, but sometimes neither of these workarounds are acceptable to upstream maintainers (e.g. #1330).

Solution: Peter suggests changing the compiler to automatically add local aliases to the translation unit for renamed static functions, so inline assembly can still refer to them using the original name. Perhaps this could also be extended to similar situations where LTO renames functions?

cc @nickdesaulniers @kees @pcc

**Comment by samitolvanen** [comment]
https://reviews.llvm.org/D104058

**Comment by samitolvanen** [comment]
Committed: https://reviews.llvm.org/rG4474958d3a97

**Comment by samitolvanen** [comment]
And reverted for now due to a test failure.

**Comment by samitolvanen** [comment]
Second attempt: https://reviews.llvm.org/rGe3d24b45b8f8

**Comment by samitolvanen** [comment]
Reverted again, broke Chromium this time.

**Comment by samitolvanen** [comment]
The Chromium issue is in `LowerTypeTestsModule` / `ScopedSaveAliaseesAndUsed`.

[D104058](https://reviews.llvm.org/D104058) adds an alias for a promoted function to `llvm.compiler.used` and after [the RAUW](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/IPO/LowerTypeTests.cpp#L1109) in `LowerTypeTestsModule::importFunction()`, it has zero uses as expected, and is added to `AliasesToErase` to be removed.

However, as [we saved `llvm.compiler.used` earlier](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/IPO/LowerTypeTests.cpp#L362) in `ScopedSaveAliaseesAndUsed`, the alias again gains a use after [the `appendToCompilerUsed` call](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/IPO/LowerTypeTests.cpp#L376) in `~ScopedSaveAliaseesAndUsed`. We then proceed to [erase everything stored in `AliasesToErase`](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/IPO/LowerTypeTests.cpp#L1872), and immediately trip [an assertion in `Value::~Value`](https://github.com/llvm/llvm-project/blob/main/llvm/lib/IR/Value.cpp#L103) because the use list for our alias is not empty.

@pcc Any thoughts on how to correctly fix this without introducing other subtle issues in process...?

**Comment by samitolvanen** [comment]
Third attempt! https://reviews.llvm.org/rG8e3b5cb39eef

**Comment by samitolvanen** [comment]
Aaaand reverted again because tests that require a target triple should probably also require that specific target to be registered.

**Comment by samitolvanen** [comment]
https://reviews.llvm.org/rG7ce1c4da7726 has been in for a couple of days now and I believe nothing has broken this time. I'll reopen if it ends up getting reverted again.

**Comment by nickdesaulniers** [comment]
This was [backported](https://bugs.llvm.org/show_bug.cgi?id=51588) to llvm-13: 1828e57eb586
