### ISSUE TITLE
llvm-NN-linker-tools Debian package

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/linux#1357]
@sylvestre 

As you know the ClangBuiltLinux infrastructure uses Debian and/or packages from <apt.llvm.org> to do CI testing and builds.

For x86-64 I see there is a new package called `llvm-12-linker-tools` which contains `libLTO.so.12` (see [1]):
```
/usr/lib/llvm-12/lib/LLVMPolly.so
/usr/lib/llvm-12/lib/LLVMgold.so
/usr/lib/llvm-12/lib/libLTO.so.12
```

The changelog in [2] says:
```
llvm-toolchain-12 (1:12.0.0-2) experimental; urgency=medium

  [ Matthias Klose ]
  * Improve the clean rule
  * Disable again LTO
  * Create a new package llvm-12-linker-tools:
    Contains the LLVMgold and LLVMPolly linker plugins.

 -- Sylvestre Ledru <sylvestre@debian.org>  Thu, 15 Apr 2021 13:27:57 +0200
```

What does this mean especially to people wanting to build with `Clang-(Thin)LTO` support?

Note: There exist also a `llvm-12-linker-tools` from <apt.llvm.org> repository.

[1] https://packages.debian.org/experimental/amd64/llvm-12-linker-tools/filelist
[2] https://metadata.ftp-master.debian.org/changelogs//main/l/llvm-toolchain-12/llvm-toolchain-12_12.0.0-2_changelog

**Comment by dileks** [comment]
Hmm, that's strange `llvm-12-dev` package contains `libLTO.so`.

From the file-list in [1]:
```
/usr/lib/llvm-12/lib/libLTO.so
```

Is that the same shared-library as from `llvm-12-linker-tools` package?

[1] https://packages.debian.org/experimental/amd64/llvm-12-dev/filelist

**Comment by dileks** [comment]
`Multi-phase communication between libLTO and linker`says:
> The linker collects information about symbol definitions and uses in various link objects which is more accurate than any information collected by other tools during typical build cycles. The linker collects this information by looking at the definitions  and uses of symbols in native .o files and using symbol visibility information. The linker also uses user-supplied information, such as a list of exported symbols. LLVM optimizer collects control flow information, data flow information and knows much  more about program structure from the optimizer’s point of view. Our goal is to take advantage of tight integration between the linker and the optimizer by sharing this information during various linking phases.

So, linking with `LLD` requires `LibLTO` to be installed.

[1] https://llvm.org/docs/LinkTimeOptimization.html#multi-phase-communication-between-liblto-and-linker

**Comment by dileks** [comment]
I would have expected a `Depends` on `llvm-12-linker-tools` for `lld-12` package.

[1] https://packages.debian.org/experimental/lld-12

**Comment by dileks** [comment]
`libLTO`
> libLTO is a shared object that is part of the LLVM tools, and is intended for use by a linker. libLTO provides an abstract C interface to use the LLVM interprocedural optimizer without exposing details of LLVM’s internals. The intention is to keep the interface as stable as possible even when the LLVM optimizer continues to evolve. It should even be possible for a completely different compilation technology to provide a different libLTO that works with their object files and the standard linker tool.

[1] https://llvm.org/docs/LinkTimeOptimization.html#liblto

**Comment by nathanchance** [comment]
> I would have expected a `Depends` on `llvm-12-linker-tools` for `lld-12` package.
> 
> [1] https://packages.debian.org/experimental/lld-12

That seems like something to consider filing on Debian's issue tracker. I assume they did not include an explicit depends because you can use `ld.lld` without those shared libraries.

At any rate, ClangBuiltLinux is not affected by that change because `llvm-12-linker-tools` is installed via a `Depends` when installing `llvm-12` and `tuxmake` [installs `llvm-12` when building the Docker images](https://gitlab.com/Linaro/tuxmake/-/blob/e8364eb5ba5b0cd973eec077f4304bc416215da8/tuxmake/runtime/docker.ini#L187). We are testing LTO in our CI so we would have noticed breakage around this.

Thanks for bringing it up though! I am going to close this up for now, feel free to reopen if you disagree.
