### ISSUE TITLE
5.12 boot failure when ThinLTO is enabled

### ISSUE THREAD

**Issue by CdeMills** [ClangBuiltLinux/linux#1365]
Hello,
I compiled and booted a kernel as reported in https://github.com/ClangBuiltLinux/linux/issues/1362

Now I went one step further:
env MAKEFLAGS="LLVM=1 LLVM_IAS=1" rpmbuild ...
and choosing the "ThinLTO" option, which enables the
CONFIG_ARCH_SUPPORTS_LTO_CLANG_THIN=y
in the .config file

The kernel compiles and install. Yet, at boot, it fails early while trying to mount one of the hard drive partition. I get strange errors messages, as if the system was trying to restart from an hibernation file, which is not the case. Did anybody successfully managed to boot with ThinLTO enabled ?

Thanks in advance

Pascal Dupuis

**Comment by torvic9** [comment]
Hello,

are you trying to boot on a AMD Zen platform?
I remember I couldn't boot any LTO kernel on my Zen2, but that was a few months ago already. The boot process failed very early on and didn't leave any log messages.
No such issue on my Skylake platform, both types of LTO compile, boot and work correctly.

**Comment by CdeMills** [comment]
Hello,
thanks for your answer. Processor is x86_64 (Quad-Core i5-4570, Haswell architecture), CentOS8-Stream, 
clang version 11.0.0 (Red Hat 11.0.0-1.module_el8.4.0+587+5187cac0)
UEFI boot, managed by grub2. Any hints on where to look ?

Regards

Pascal

**Comment by torvic9** [comment]
Sorry, I'm not a developer and I'm only doing this out of curiosity and interest :-)
However, you could try using a newer clang (12.0.x) and see whether it makes a difference.

**Comment by dileks** [comment]
Please attach your full Linux `.config` file.
This contains more than ThinLTO is enabled - like LLVM/Clang/LLD versions etc.

Show us your full make line (invocation).

Here I can build and boot:
```
root# cat /proc/version 
Linux version 5.12.0-1-amd64-clang12-lto (sedat.dilek@gmail.com@iniza) (dileks clang version 12.0.0 (https://github.com/llvm/llvm-project.git d28af7c654d8db0b68c175db5ce212d74fb5e9bc), LLD 12.0.0 (https://github.com/llvm/llvm-project.git d28af7c654d8db0b68c175db5ce212d74fb5e9bc)) #1~bullseye+dileks1 SMP 2021-04-26
```
[config-5.12.0-1-amd64-clang12-lto.txt](https://github.com/ClangBuiltLinux/linux/files/6404462/config-5.12.0-1-amd64-clang12-lto.txt)

**Comment by dileks** [comment]
@CdeMills 

Can you boot in QEMU?

**Comment by ms178** [comment]
@CdeMills It has been a long time that I've seen similar issues with Clang/LTO, but I am currently seeing such an issue with Andi Kleen's 5.12-3 patchset of GCC LTO (see: https://github.com/andikleen/linux-misc/issues/37). 

I am running 5.12.0-Xanmod right now on a Haswell-EP system which was compiled with LLVM=1 LLVM_IAS=1 and LLVM/Clang 12 with ThinLTO and some other fancy compiler flags (O3 and various Polly-related flags). I've also tweaked my config, there are a couple of known issue, e.g. you need disable "trim unused kernel symbols" to get it to compile at all and you might have hit just another more subtle issue. I've seen some problems with a couple of modules which missed some symbols but I haven't noticed fallout from this yet. I have attached my current Xanmod config which works fine on my system (beware, I disable a lot of stuff which I don't need, you might have to do a couple of adjustments depending on your hardware).

[config.txt](https://github.com/ClangBuiltLinux/linux/files/6405280/config.txt)

**Comment by nathanchance** [comment]
@CdeMills let's start with some basic isolation questions.

1. Does the exact same configuration and build command work without `CONFIG_LTO_CLANG_THIN=y`? In other words, it is ONLY changing that config that causes the issue? Can you post your config?

2. Are there any dmesg errors when booting? If you do not see any, you might need to adjust the default log level in Kconfig.

3. Can you try booting in QEMU? We have a simple boot script [here](https://github.com/ClangBuiltLinux/boot-utils) that should work something like this: `boot-qemu.sh -a x86_64 -k <path_to_your_build_output_folder>`.

For the record, I have booted several servers using ThinLTO without any problems.

**Comment by CdeMills** [comment]
Hello,

the first file was compiled with
env MAKEFLAGS="LLVM=1" rpmbuild nice -n 20 rpmbuild  --noclean --nocheck --nodebuginfo --without bpftool --without perf --without tools -ba SPECS/kernel-ml-5.12.
 and resulted in a bootable kernel; 

the second file was compiled with
env MAKEFLAGS="LLVM=1 LLVM_IAS=1" rpmbuild [...] and resulted in a non-bootable kernel
The build log for the second case is attached too

The diff list is quite small:
```
-- config-5.12.0-x86_64	2021-04-30 19:21:48.830610674 +0200
+++ config-5.12.thinlto.0-x86_64	2021-04-30 19:21:11.847281633 +0200
@@ -796,8 +796,8 @@
 CONFIG_ARCH_SUPPORTS_LTO_CLANG_THIN=y
 CONFIG_HAS_LTO_CLANG=y
 # CONFIG_LTO_NONE is not set
-CONFIG_LTO_CLANG_FULL=y
-# CONFIG_LTO_CLANG_THIN is not set
+# CONFIG_LTO_CLANG_FULL is not set
+CONFIG_LTO_CLANG_THIN=y
 CONFIG_HAVE_ARCH_WITHIN_STACK_FRAMES=y
 CONFIG_HAVE_CONTEXT_TRACKING=y
 CONFIG_HAVE_CONTEXT_TRACKING_OFFSTACK=y
```

I'm trying the qemu stuff; I'll keep you posted

Regards

Pascal 


[config-5.12.0-x86_64.txt](https://github.com/ClangBuiltLinux/linux/files/6407063/config-5.12.0-x86_64.txt)
[config-5.12.thinlto.0-x86_64.txt](https://github.com/ClangBuiltLinux/linux/files/6407065/config-5.12.thinlto.0-x86_64.txt)



[kernel-ml-5.12.spec-thinlto.rpmbuild.txt](https://github.com/ClangBuiltLinux/linux/files/6407081/kernel-ml-5.12.spec-thinlto.rpmbuild.txt)

**Comment by nickdesaulniers** [comment]
> The diff list is quite small:

That looks like a diff from full LTO to thin LTO.  I suspect @nathanchance was asking about going from no LTO (CONFIG_LTO_NONE) to thin LTO.

**Comment by nickdesaulniers** [comment]
> config-5.12.thinlto.0-x86_64.txt

Actually triggers an assertion failure for me! So yeah, it's probably haunted AF trying to boot that!
```
$ wget https://github.com/ClangBuiltLinux/linux/files/6407065/config-5.12.thinlto.0-x86_64.txt -O .config
$ make LLVM=1 LLVM_IAS=1 -j72 olddefconfig all
...
  LTO     vmlinux.o
ld.lld: ../include/llvm/CodeGen/SelectionDAGNodes.h:1105: llvm::SDValue::SDValue(llvm::SDNode *, unsigned int): Assertion `(!Node || !ResNo || ResNo < Node->getNumValues()) && "Invalid result number for the given node!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Running pass 'Function Pass Manager' on module 'arch/x86/built-in.a(ds.o at 6982)'.
1.      Running pass 'X86 DAG->DAG Instruction Selection' on function '@intel_pmu_enable_bts'
LLVM ERROR: Failed to rename temporary file .thinlto-cache/Thin-a649b0.tmp.o to .thinlto-cache/llvmcache-BBAD78301FE676ABEB67E833A3CE6EBBA27D349A: No such file or directory

scripts/link-vmlinux.sh: line 74: 788153 Aborted                 ${LD} ${KBUILD_LDFLAGS} -r -o ${1} ${lds} ${objects}
make: *** [Makefile:1196: vmlinux] Error 134
```

**Comment by nathanchance** [comment]
> > config-5.12.thinlto.0-x86_64.txt
> 
> 
> 
> Actually triggers an assertion failure for me! So yeah, it's probably haunted AF trying to boot that!
> 
> ```
> 
> $ wget https://github.com/ClangBuiltLinux/linux/files/6407065/config-5.12.thinlto.0-x86_64.txt -O .config
> 
> $ make LLVM=1 LLVM_IAS=1 -j72 olddefconfig all
> 
> ...
> 
>   LTO     vmlinux.o
> 
> ld.lld: ../include/llvm/CodeGen/SelectionDAGNodes.h:1105: llvm::SDValue::SDValue(llvm::SDNode *, unsigned int): Assertion `(!Node || !ResNo || ResNo < Node->getNumValues()) && "Invalid result number for the given node!"' failed.
> 
> PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
> 
> Stack dump:
> 
> 0.      Running pass 'Function Pass Manager' on module 'arch/x86/built-in.a(ds.o at 6982)'.
> 
> 1.      Running pass 'X86 DAG->DAG Instruction Selection' on function '@intel_pmu_enable_bts'
> 
> LLVM ERROR: Failed to rename temporary file .thinlto-cache/Thin-a649b0.tmp.o to .thinlto-cache/llvmcache-BBAD78301FE676ABEB67E833A3CE6EBBA27D349A: No such file or directory
> 
> 
> 
> scripts/link-vmlinux.sh: line 74: 788153 Aborted                 ${LD} ${KBUILD_LDFLAGS} -r -o ${1} ${lds} ${objects}
> 
> make: *** [Makefile:1196: vmlinux] Error 134
> 
> ```

Looks like that might be https://reviews.llvm.org/D91722#2724321 again? Same file I think unless you have the fixes already. Does that reproduce with LLVM 12.0.0?

**Comment by nathanchance** [comment]
I was also trying to see if `LLVM=1 LLVM_IAS=1` with `CONFIG_LTO_NONE=y` worked fine, not just `LLVM=1`.

**Comment by CdeMills** [comment]
[kernel-ml-5.12.spec-thinlto.rpmbuild.txt](https://github.com/ClangBuiltLinux/linux/files/6409531/kernel-ml-5.12.spec-thinlto.rpmbuild.txt)
Hello,
I tried to compile using the config.txt sent by ms178. There is a buid failure, as enclosed in the log file

Regards

Pascal

**Comment by CdeMills** [comment]
And for qemu ... well, under CentOS, it's complicated. The official virtualization tool is KVM. There is a GUI, but which permits only to create a disk image and boot from some iso file, which is in charge of installing the OS. I didn't see how to bootstrap a VM using a test kernel

Regards

Pascal

**Comment by nickdesaulniers** [comment]
> I tried to compile using the config.txt sent by ms178. There is a buid failure, as enclosed in the log file

```
+ /usr/bin/xargs /usr/sbin/modinfo -l
+ /usr/bin/grep -E -v 'GPL( v2)?$|Dual BSD/GPL$|Dual MPL/GPL$|GPL and additional rights$'
modinfo: ERROR: missing module or filename.****
```
do you have an out of tree module with a curious license, perhaps?

> Looks like that might be https://reviews.llvm.org/D91722#2724321 again?

Ah yeah with that reverted the config builds and boots just fine for me. (It loops booting it as i386 without a visible panic though FWIW).

**Comment by ms178** [comment]
@nickdesaulniers 

Ups, revisiting my config posted above, I've had Barry Song's patchset on top with the title [RFC PATCH v6 0/4] scheduler: expose the topology of clusters and add cluster scheduler [https://lore.kernel.org/r/20210420001844.9116-1-song.bao.hua@hisilicon.com/].

Xanmod also differs from mainline quite a bit, carrying a couple of performance-oriented patches on top.

**Comment by nickdesaulniers** [comment]
> Xanmod also differs from mainline quite a bit

Is this issue specific to Xanmod then, or can it be reproduced using mainline (or next, or stable)?

**Comment by ms178** [comment]
@nickdesaulniers 

From looking at the provided log from CdeMills the error seems to come from "cat: k-d.list: No such file or directory" and "/usr/bin/sed: can't read /home/padupuis/rpmbuild/BUILDROOT/kernel-ml-5.12.thinlto.0-1.el8.cfi.x86_64/k-d.list: No such file or directory". It seems to me that my modified Xanmod config is not compatible with his build script which expects such a file or directory which is not present but is expected to be present by his script.

The comment you quoted from me was just meant as a general statement. By the way, I've posted my own observations here: https://github.com/ClangBuiltLinux/linux/issues/1367

I haven't tested it yet with Vanilla sources but will do so now, I expect that the ones reported there are not Xanmod specific.

**Comment by CdeMills** [comment]
Hello,
next round: make LLVM=1 LLVM_IAS=1 and selecting 'CONFIG_LTO=NONE' in the .config, results in boot failure.
Symptoms are the same as selecting LLVM=1 LLVM_IAS=1with ThinLTO: devices are probed and detected, but then mounting the root filesystem, xfs formatted, seems to hang forever.
Even CTRL-ALT-DEL repeated quickly a few times seems to not break the mount loop. At this point, my observation is that the common factor is 'LLVM_IAS=1'

Regards

Pascal

**Comment by CdeMills** [comment]
@nickdesaulniers
> + /usr/bin/xargs /usr/sbin/modinfo -l
> + /usr/bin/grep -E -v 'GPL( v2)?$|Dual BSD/GPL$|Dual MPL/GPL$|GPL and additional rights$'
> modinfo: ERROR: missing module or filename.****
>
> do you have an out of tree module with a curious license, perhaps?

This is pristine 5.12 source from kernel.org; not a single patch applied.

There is a small non-standard build step: after compiling modules, they are splits into two sets: 'modules' and 'modules-extra', the latter being considered as less frequently used.

Regards

Pascal

**Comment by nickdesaulniers** [comment]
> selecting 'CONFIG_LTO=NONE' in the .config, results in boot failure.

So the title of the bug is wrong, at the least.

> At this point, my observation is that the common factor is 'LLVM_IAS=1'

Have you tested with thinlto disabled and LLVM_IAS=1 not set yet to confirm? Sounds like perhaps LLVM_IAS=1 is affecting xfs somehow if so.

**Comment by nathanchance** [comment]
> > At this point, my observation is that the common factor is 'LLVM_IAS=1'
> 
> Have you tested with thinlto disabled and LLVM_IAS=1 not set yet to confirm? Sounds like perhaps LLVM_IAS=1 is affecting xfs somehow if so.

Building with `LLVM_IAS=1` and this patch applied would help confirm that:

```diff
git dh
diff --git a/fs/xfs/Makefile b/fs/xfs/Makefile
index 04611a1068b4..7d4e8c542cbc 100644
--- a/fs/xfs/Makefile
+++ b/fs/xfs/Makefile
@@ -6,6 +6,7 @@

 ccflags-y += -I $(srctree)/$(src)              # needed for trace events
 ccflags-y += -I $(srctree)/$(src)/libxfs
+ccflags-y += -fno-integrated-as

 obj-$(CONFIG_XFS_FS)           += xfs.o


```

**Comment by nickdesaulniers** [comment]
Hi @CdeMills can you please test [the suggestion above](https://github.com/ClangBuiltLinux/linux/issues/1365#issuecomment-832276938)?

**Comment by microcai** [comment]
> Zen2

uses UART console to extraced the exact reason.  crashed on jump_label.c

**Comment by microcai** [comment]
> Hello,
> 
> are you trying to boot on a AMD Zen platform?
> I remember I couldn't boot any LTO kernel on my Zen2, but that was a few months ago already. The boot process failed very early on and didn't leave any log messages.
> No such issue on my Skylake platform, both types of LTO compile, boot and work correctly.

uses UART console to extraced the exact reason. crashed on jump_label.c
