### ISSUE TITLE
Lots of depmod warnings with "needs unknown symbol"-errors and two other observations

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#1367]
Hi, I am on Ubuntu 21.04, with 5.12.0-Xanmod sources, LLVM/Clang 12 from the [v3 toolchain-r repo](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/x86-64-v3) and my custom Makefile (I've used custom compiler flags at around line 417 - 474) and the attached config, I get a lot of depmod warnings during the end of the compilation stage. 

[config.txt](https://github.com/ClangBuiltLinux/linux/files/6411471/config.txt)
[Makefile.txt](https://github.com/ClangBuiltLinux/linux/files/6411472/Makefile.txt)

One example: depmod: WARNING: /mnt/linux-5.12.0-xanmod1/debian/linux-image/lib/modules/5.12.0-xanmod1-llvm-5/kernel/drivers/mtd/ubi/ubi.ko.xz needs unknown symbol get_mtd_device

I am attaching the others which I could grab from the console, there are more though.
[depmod-warnings.txt](https://github.com/ClangBuiltLinux/linux/files/6411468/depmod-warnings.txt)

Are these known issues? The Kernel still boots and works fine for me so far. [**edit**: I also get these issue if I don't use Polly].

A couple of other observations (which I could file separate issues for, if you'd like me to):

1) If I use -polly-vectorizer=polly instead of -polly-vectorizer=stripmine with the same config and Makefile from above, I get:
[  +0,017083] SQUASHFS error: xz decompression failed, data probably corrupt
[  +0,000004] SQUASHFS error: Failed to read block 0x60: -5
[  +0,000011] SQUASHFS error: xz decompression failed, data probably corrupt
[  +0,000001] SQUASHFS error: Failed to read block 0x60: -5
[dmesg2.txt](https://github.com/ClangBuiltLinux/linux/files/6411479/dmesg2.txt)

2) FullLTO with the attached Makefile and config from above errors out with:
  LTO     vmlinux.o
ld.lld: error: Invalid record (Producer: 'LLVM12.0.0' Reader: 'LLVM 12.0.0')
make[3]: *** [Makefile:1202: vmlinux] Fehler 1
make[2]: *** [debian/rules:7: build-arch] Fehler 2
dpkg-buildpackage: Fehler: Unterprozess debian/rules binary lieferte Exitstatus 2
make[1]: *** [scripts/Makefile.package:83: bindeb-pkg] Fehler 2
make: *** [Makefile:1582: bindeb-pkg] Fehler 2

This is the line I use for the compilation: make LLVM=1 LLVM_IAS=1 bindeb-pkg -j24

**Comment by ms178** [comment]
@MaskRay I just saw your comment in https://github.com/ClangBuiltLinux/linux/issues/1269#issuecomment-802400502 
Is the patch (https://reviews.llvm.org/D98762) which you mentioned there related to the depmod warnings seen here?

**Comment by ms178** [comment]
As a continuation of https://github.com/ClangBuiltLinux/linux/issues/1365#issuecomment-831611705, I can confirm that I also see a lot of depmod warnings with the Vanilla 5.12.1 sources with the config and Makefile from https://github.com/ClangBuiltLinux/linux/issues/1367#issue-873950801

Hence the issue presented here is not Xanmod specific. See the attached file with the errors from the Vanilla build which I could grab from the console:

[depmod-warnings_vanilla.txt](https://github.com/ClangBuiltLinux/linux/files/6418510/depmod-warnings_vanilla.txt)

**Comment by nathanchance** [comment]
I can't reproduce this on a vanilla kernel with LLVM 18 and kmod 31.

```
$ curl -LSso .config https://github.com/ClangBuiltLinux/linux/files/6411471/config.txt

$ make -skj"$(nproc)" ARCH=x86_64 INSTALL_MOD_PATH=$PWD/rootfs LLVM=1 olddefconfig all modules_install
<some other irrelevant warnings>
```

If you are still seeing this with your custom compiler flags, consider bisecting those to figure out which one causes it and reopen this with a more specific reproducer.
