### ISSUE TITLE
How to Build External Kernel module with CLANG ( sample Makefile)

### ISSUE THREAD

**Issue by alokprasad** [ClangBuiltLinux/linux#1373]

**Comment by nathanchance** [comment]
Not quite sure what is being asked here. You can build an external module with clang just like a regular kernel with the use of `CC=clang` or `LLVM=1` for all of the LLVM tools.

**Comment by nickdesaulniers** [comment]
Perhaps provide a list of command you tried @alokprasad , and what errors you observed.
