### ISSUE TITLE
no_sanitize fn attr

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1376]
via @melver : https://llvm.org/pr49035

**Comment by melver** [comment]
Under review: https://reviews.llvm.org/D102772

**Comment by melver** [comment]
https://github.com/llvm/llvm-project/commit/280333021e9550d80f5c1152a34e33e81df1e178

**Comment by melver** [comment]
Reopen. We're still missing the kernel-side patch. Will send that shortly.

**Comment by melver** [comment]
Patch sent: https://lkml.kernel.org/r/20210525175819.699786-1-elver@google.com

**Comment by melver** [comment]
Picked up into -mm tree.

**Comment by nickdesaulniers** [comment]
reopening until this is in mainline

**Comment by nickdesaulniers** [comment]
accepted: https://ozlabs.org/~akpm/mmotm/broken-out/kcov-add-__no_sanitize_coverage-to-fix-noinstr-for-all-architectures-v3.patch

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/linus/540540d06e9d9b3769b46d88def90f7e7c002322
