### ISSUE TITLE
riscv boot failure on next-20210601

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1389]
As pointed out by CI: https://github.com/ClangBuiltLinux/continuous-integration2/runs/2717606254?check_suite_focus=true

```
$ git bisect log
git bisect log
# bad: [392d24c0d06bc89a762ba66977db41e53c21bfb5] Add linux-next specific files for 20210601
# good: [c2131f7e73c9e9365613e323d65c7b9e5b910f56] Merge tag 'gfs2-v5.13-rc2-fixes' of git://git.kernel.org/pub/scm/linux/kernel/git/gfs2/linux-gfs2
git bisect start '392d24c0d06bc89a762ba66977db41e53c21bfb5' 'c2131f7e73c9e9365613e323d65c7b9e5b910f56'
# bad: [4e3422fa49067cf38e4a0eeb3064be41acba0c73] Merge remote-tracking branch 'drm/drm-next'
git bisect bad 4e3422fa49067cf38e4a0eeb3064be41acba0c73
# bad: [59c763b52d1e4d6ca812dcfef0ccdca8858e2555] Merge remote-tracking branch 'v4l-dvb/master'
git bisect bad 59c763b52d1e4d6ca812dcfef0ccdca8858e2555
# good: [12a4b9f95b9cb9509470e44f9d37007a7f775cc0] Merge remote-tracking branch 'csky/linux-next'
git bisect good 12a4b9f95b9cb9509470e44f9d37007a7f775cc0
# bad: [3bf43bf33a88ebb10018d50eca74a4a7cdf3e106] Merge remote-tracking branch 'v9fs/9p-next'
git bisect bad 3bf43bf33a88ebb10018d50eca74a4a7cdf3e106
# bad: [6cef58580b9c0a42b90c79a068d0733185b953e3] Merge remote-tracking branch 'btrfs/for-next'
git bisect bad 6cef58580b9c0a42b90c79a068d0733185b953e3
# bad: [2201218e2efb0ff556d50dab7fe867645a2551fc] Merge remote-tracking branch 'risc-v/for-next'
git bisect bad 2201218e2efb0ff556d50dab7fe867645a2551fc
# good: [61374ef68d5eb81d310a0a8a3cca49c1e5c173e6] Merge remote-tracking branch 'mips/mips-next'
git bisect good 61374ef68d5eb81d310a0a8a3cca49c1e5c173e6
# good: [5b75bd763d369e43e6d09e85eaea22fde37c0e89] powerpc/sstep: Add emulation support for ‘setb’ instruction
git bisect good 5b75bd763d369e43e6d09e85eaea22fde37c0e89
# good: [37a7a2a10ec525a79d733008bc7fe4ebbca34382] riscv: Turn has_fpu into a static key if FPU=y
git bisect good 37a7a2a10ec525a79d733008bc7fe4ebbca34382
# good: [192539c4f5887951f6e4bd599ff412fa664e304b] Merge remote-tracking branch 'powerpc/next'
git bisect good 192539c4f5887951f6e4bd599ff412fa664e304b
# bad: [010623568222bd144eb73aa9f3b46c79b63d7676] riscv: mm: init: Consolidate vars, functions
git bisect bad 010623568222bd144eb73aa9f3b46c79b63d7676
# good: [3df952ae2ac81fbc5d44b014e5462b53d1decbb5] riscv: Add __init section marker to some functions again
git bisect good 3df952ae2ac81fbc5d44b014e5462b53d1decbb5
# first bad commit: [010623568222bd144eb73aa9f3b46c79b63d7676] riscv: mm: init: Consolidate vars, functions
```

https://git.kernel.org/riscv/c/010623568222bd144eb73aa9f3b46c79b63d7676

It appears to be the change to `load_pa` that breaks everything, specifically making it `static`. I have gone ahead and reported this upstream for more insight: https://lore.kernel.org/r/YLaWseLdg5JYElVx@Ryzen-9-3900X.localdomain/

**Comment by nickdesaulniers** [comment]
Did you verify it was just `static` and not also the new/additional `__initdata` annotation?  Having something stop booting due to adding `__initdata` (perhaps mistakenly) seems more likely to results in boot failures.

**Comment by nathanchance** [comment]
Yes. Just removing `static` is enough to restore boot.

**Comment by nickdesaulniers** [comment]
Is `CONFIG_XIP_KERNEL` enabled in the defconfig?

**Comment by nathanchance** [comment]
No, this is just `ARCH=riscv defconfig`.

**Comment by nickdesaulniers** [comment]
ok, I can repro. Trying to compare the disassemblies with `llvm-objdump` was not helpful; a lot changes just from make `load_pa` extern; or at least `diff -u` cant seem to thread output very well.  Looking at differences in ir, I do see two differences:

`@setup_vm`:
```diff
-  store i1 true, i1* @load_pa, align 8
+  store i64 ptrtoint ([0 x i8]* @_start to i64), i64* @load_pa, align 8
```

`@create_kernel_page_table`:
```diff
-  %.b = load i1, i1* @load_pa, align 8
-  %3 = select i1 %.b, i64 ptrtoint ([0 x i8]* @_start to i64), i64 0
-  %sub = sub i64 %add26, %.pre
-  %add1 = add i64 %sub, %3
+  %3 = load i64, i64* @load_pa, align 8
+  %sub = add i64 %3, %add26
+  %add1 = sub i64 %sub, %.pre
```

seems odd that before we were storing `true` into `@load_pa` IIUC. That corresonds to the C code:
```c
load_pa = (uintptr_t)(&_start);
```
and `@create_kernel_page_table` seemed to be loading from `@load_pa` but then chosing either `@_start` or `0` based on the value of `@load_pa`.  Not really sure what's wrong there, but the "or `0`" sounds fishy, though that was for the code that worked.

@nathanchance mentions `setup_vm_final` which has a statement using `__pa_symbol` which uses `RELOC_HIDE` which isn't defined for the same for clang; that's curious but perhaps a red herring?

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/linux-riscv/20210603195418.21fded50@xhacker/ has a similar question about the "store 1 to `load_pa` in `setup_vm` in the broken case."

**Comment by nathanchance** [comment]
https://git.kernel.org/next/linux-next/c/658e2c5125bbbc9b9b5eac23b3c35b87df3c30b8 in -next tangentially works around this by eliminating `load_pa`. This is still probably worth investigating but marking as low priority for now because it is not breaking us.

**Comment by nickdesaulniers** [comment]
Let's reopen if this occurs again.
