### ISSUE TITLE
-Wunused-but-set-variable in fs/btrfs/delayed-inode.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1391]
```
fs/btrfs/delayed-inode.c:684:6: warning: variable 'total_data_size' set but not used [-Wunused-but-set-variable]
        int total_data_size = 0, total_size = 0;
            ^
1 warning generated.
```

Patch submitted: https://lore.kernel.org/r/20210603174311.1008645-1-nathan@kernel.org/

**Comment by nickdesaulniers** [comment]
accepted: https://github.com/kdave/btrfs-devel/commit/3f3a096a4d671b4ba20ffc8bcd7dde08c0efa7ee

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/torvalds/c/bfaa324e9a80
