### ISSUE TITLE
relocation R_AARCH64_CALL26 out of range

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1394]
LLVM_VERSION=11
https://github.com/ClangBuiltLinux/continuous-integration2/runs/2792794303?check_suite_focus=true

LLVM_VERSION=android
https://github.com/ClangBuiltLinux/continuous-integration2/runs/2792792051?check_suite_focus=true

**Comment by nickdesaulniers** [comment]
LLVM_VERSION=12
https://github.com/ClangBuiltLinux/continuous-integration2/runs/2801874400?check_suite_focus=true

version 11 is green though:
https://github.com/ClangBuiltLinux/continuous-integration2/runs/2801873195?check_suite_focus=true

version 13 is green:
https://github.com/ClangBuiltLinux/continuous-integration2/runs/2801875809?check_suite_focus=true

**Comment by nathanchance** [comment]
I am closing this as unreproducible for now. I could never reproduce it locally, even with the `tuxmake` reproducers provided by `tuxsuite` and none of our CI has this failure currently.
