### ISSUE TITLE
CONFIG_STACK_VALIDATION=y HOSTCC=clang

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#14]
It was reported that the following error was encountered:

```sh
$ make HOSTCC=clang CC=clang  -j32 ARCH=x86_64 prepare
...
scripts/kconfig/conf  --silentoldconfig Kconfig
Makefile:965: *** "Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel".  Stop.
```

But the latest libelf-dev has been installed with version 0.170-0.4.

Reported-by: Hao, Shun <shun.hao@intel.com>

**Comment by nickdesaulniers** [comment]
So the Makefile has the code:

```make
 960 ifdef CONFIG_STACK_VALIDATION                                                   
 961   has_libelf := $(call try-run,\                                                
 962     echo "int main() {}" | $(HOSTCC) -xc -o /dev/null -lelf -,1,0)              
 963   ifeq ($(has_libelf),1)                                                        
 964     objtool_target := tools/objtool FORCE                                       
 965   else                                                                          
 966     ifdef CONFIG_UNWINDER_ORC                                                   
 967       $(error "Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel")
...
```

So it looks like it's running:

```sh
$(echo "int main() {}" | $(HOSTCC) -xc -o /dev/null -lelf -,1,0)
```

I *think* this is wrong because:

```sh
➜  kernel-all git:(master) ✗ HOSTCC=/android1/llvm/build/bin/clang-7.0; $(echo "int main() {}" | $(HOSTCC) -xc -o /dev/null -lelf -,1,0)
zsh: command not found: HOSTCC
zsh: command not found: -xc
```

it seems that HOSTCC is not defined for the subshell?

```bash
HOSTCC=/android1/llvm/build/bin/clang-7.0; $(echo "int main() {}" | $HOSTCC -xc -o /dev/null -lelf -)
```

seems to work.

**Comment by tpimh** [comment]
You are right, creating subshell here is a mistake. Probably the original author meant `${HOSTCC}`, not `$(HOSTCC)`. But this is not the only mistake here.
If your `.config` has `CONFIG_STACK_VALIDATION=y` and `# CONFIG_UNWINDER_ORC is not set`. It will still print an error as if `CONFIG_UNWINDER_ORC` is defined (but actually it should just print a warning and set `SKIP_STACK_VALIDATION` variable). Do you have `CONFIG_UNWINDER_ORC` set in your `.config`?
Btw, last time I tried building libelf with clang, it was a pain (had to completely rewrite some gcc-specific parts).

**Comment by nickdesaulniers** [comment]
I'm no longer able to reproduce.  I wonder if the CONFIG_STACK_VALIDATION check is no longer running at all?

**Comment by tpimh** [comment]
Which version are you building? I'm on  5211da9 and it is still there. The stranger thing is that my `.config` is:
```
CONFIG_STACK_VALIDATION=y
# CONFIG_UNWINDER_ORC is not set
```
And I'm still given an error, not a warning. Relevant part of the Makefile:
```Makefile
ifdef CONFIG_STACK_VALIDATION                         
  has_libelf := $(call try-run,\      
                echo "int main() {}" | $(HOSTCC) -xc -o /dev/null -lelf -,1,0)
  ifeq ($(has_libelf),1)                                    
    objtool_target := tools/objtool FORCE
  else                                                            
    ifdef CONFIG_UNWINDER_ORC
      $(error "Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel")
    else
      $(warning "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel")
    endif                                                           
    SKIP_STACK_VALIDATION := 1                                
    export SKIP_STACK_VALIDATION        
  endif
endif                                   
```

**Comment by nathanchance** [comment]
This should be fixed as of https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ef7cfd00b2caf6edeb7f169682b64be2d0a798cf.

@tpimh can you test and close this issue if that is the case?

**Comment by tpimh** [comment]
Yes, now it behaves how it should. Tested with `CONFIG_STACK_VALIDATION` and `CONFIG_UNWINDER_ORC` (errors and stops), with `CONFIG_STACK_VALIDATION` and no `CONFIG_UNWINDER_ORC` (warns and continues) and without both `CONFIG_STACK_VALIDATION` and `CONFIG_UNWINDER_ORC` (no warning). These are expected behaviors.

**Comment by nickdesaulniers** [comment]
Thanks @masahir0y  !
