### ISSUE TITLE
invalid reassignment of non-absolute variable 'fs_label'

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1416]
working around #672, I see:
```
$ ARCH=powerpc CROSS_COMPILE=powerpc64le-linux-gnu- make LLVM=1 LLVM_IAS=1 -j72 powernv_defconfig arch/powerpc/kernel/head_64.o
...
arch/powerpc/kernel/head_64.S:193:12: error: invalid reassignment of non-absolute variable 'fs_label'
fs_label = start_first_256B; fs_start = first_256B_start; use_ftsec first_256B;; . = first_256B_len; end_first_256B:
           ^
```

**Comment by nemanjai** [comment]
Would it be possible to attach the pre-processed file (`arch/powerpc/kernel/head_64.S`) so I can hopefully see why the assembly parser thinks that `fs_label` is being reassigned?

**Comment by nathanchance** [comment]
@nemanjai here you go: https://gist.github.com/5156857c4ce772ade48165ecaf9c1c5c

**Comment by nickdesaulniers** [comment]
We should reduce the preprocessed input with cvise; cvise can reduce non-C/C++ code with the `--not-c` flag.

Perhaps we can use `__COUNTER__` to get unique identifiers for `fs_label`. We need to find which macro produces `fs_label`.

It looks like the integrated assembler has incompatibilities with reassignment of labels; eager vs lazy evaluation is probably not being relied on here.

**Comment by nickdesaulniers** [comment]
@aik [sent a patch](https://lore.kernel.org/llvm/20211221055904.555763-5-aik@ozlabs.ru/) from @daxtens . @mpe [accepted it into powerpc/next](https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?h=next&id=d72c4a36d7ab560127885473a310ece28988b604).

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/d72c4a36d7ab560127885473a310ece28988b604
