### ISSUE TITLE
error: deprecated

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1417]
working around #672, I see:
```
$ ARCH=powerpc CROSS_COMPILE=powerpc64le-linux-gnu- make LLVM=1 LLVM_IAS=1 -j72 powernv_defconfig arch/powerpc/mm/mmu_context.o
...
arch/powerpc/mm/mmu_context.c:84:17: error: deprecated [-Werror,-Winline-asm]
                asm volatile ("dssall");
                              ^
<inline asm>:1:2: note: instantiated into assembly here
        dssall
        ^
```

**Comment by nickdesaulniers** [comment]
https://github.com/llvm/llvm-project/commit/0096dbd50df50a08d729e1219f78d43f3e1583b3

**Comment by nickdesaulniers** [comment]
@mpe any idea what the alternative to `dssall` is if it's deprecated? (or is LLVM incorrect about the deprecation warning?)

**Comment by nickdesaulniers** [comment]
cc @nemanjai

**Comment by mpe** [comment]
It is deprecated, I don't think there's an alternative, but it's required to be implemented as a nop on newer CPUs, so it's pretty harmless. Possibly we can remove it, but it would require some archaeology to confirm it's not needed on old CPUs we still support (eg. G5).

**Comment by nemanjai** [comment]
It it worth macro guarding it for CPU's which implement it as a `nop`? Or just leaving it and not marking it deprecated since it is a `nop` after all?

**Comment by nemanjai** [comment]
Can you just add
```
#ifdef __clang__
#pragma GCC diagnostic ignored "-Winline-asm"
#endif
```
on the line immediately preceding that one?

**Comment by nickdesaulniers** [comment]
it might be interesting to do more git archaeology to see why `dssall` was ever added.

**Comment by nathanchance** [comment]
https://git.kernel.org/tglx/history/c/04879b04bf500585d6b015e440be3ee7bdaf9cd4 added `dssall` back in 2004.

**Comment by nickdesaulniers** [comment]
> it's required to be implemented as a nop on newer CPUs

Do we know when or for which CPUs that transition occurred? Maybe we could emit `dssall` for the older cpus, but `nop` or no inline assembler at all for newer CPUs?

**Comment by nickdesaulniers** [comment]
@aik [sent a patch for this](https://lore.kernel.org/llvm/20211221055904.555763-6-aik@ozlabs.ru/). @mpe [accepted it into powerpc/next](https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?h=next&id=d51f86cfd8e378d4907958db77da3074f6dce3ba).

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/d51f86cfd8e378d4907958db77da3074f6dce3ba
