### ISSUE TITLE
unsupported directive '.stabs'

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1418]
```
$ ARCH=powerpc CROSS_COMPILE=powerpc64le-linux-gnu- make LLVM=1 LLVM_IAS=1 -j72 pseries_defconfig arch/powerpc/kernel/vdso32/gettimeofday.o
...
arch/powerpc/kernel/vdso32/gettimeofday.S:72:8: error: unsupported directive '.stabs'
.stabs "_restgpr_31_x:F-1",36,0,0,_restgpr_31_x; .globl _restgpr_31_x; _restgpr_31_x:
       ^
arch/powerpc/kernel/vdso32/gettimeofday.S:73:8: error: unsupported directive '.stabs'
.stabs "_rest32gpr_31_x:F-1",36,0,0,_rest32gpr_31_x; .globl _rest32gpr_31_x; _rest32gpr_31_x:
       ^
```
https://sourceware.org/binutils/docs/as/Stab.html

**Comment by nickdesaulniers** [comment]
`.stabs` is also used in arch/powerpc/lib/copy_32.S.

**Comment by paulmenzel** [comment]
The LLVM developers say in bug report[[inline asm] .stabs directive support ](https://bugs.llvm.org/show_bug.cgi?id=31134),  STABS is replaced by DWARF.

**Comment by nickdesaulniers** [comment]
@segher mentions on IRC:
> stabs is an older debug format, like dwarf
> it will be good to have it eradicated :-)
> you need to figure out what it does, instead [of just removing it]

**Comment by segher** [comment]
"to have it eradicated"...  I was talking about the GCC support for STABS.  This has no
bearing on the VDSO issue.

**Comment by nickdesaulniers** [comment]
cc @aik

**Comment by nathanchance** [comment]
Patch removing these annotations has been picked up: https://git.kernel.org/powerpc/c/12318163737cd8808d13faa6e2393774191a6182

**Comment by nickdesaulniers** [comment]
(Noting that we should revisit https://github.com/ClangBuiltLinux/continuous-integration2/pull/321 once this is closed out)

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/12318163737cd8808d13faa6e2393774191a6182
