### ISSUE TITLE
invalid operand for instruction `cmpli`

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1419]
working around #675
```
$ ARCH=powerpc CROSS_COMPILE=powerpc64le-linux-gnu- make LLVM=1 LLVM_IAS=1 -j72 ppc44x_defconfig arch/powerpc/sysdev/dcr-low.o
...
arch/powerpc/sysdev/dcr-low.S:27:10: error: invalid operand for instruction
 cmpli 0,%r3,1024; rlwinm %r3,%r3,4,18,27; lis %r5,__mfdcr_table@h; ori %r5,%r5,__mfdcr_table@l; add %r3,%r3,%r5; bge- 1f; mtctr %r3; bctr; 1: trap; EMIT_BUG_ENTRY 1b,"arch/powerpc/sysdev/dcr-low.S",27,0; blr
         ^
arch/powerpc/sysdev/dcr-low.S:31:10: error: invalid operand for instruction
 cmpli 0,%r3,1024; rlwinm %r3,%r3,4,18,27; lis %r5,__mtdcr_table@h; ori %r5,%r5,__mtdcr_table@l; add %r3,%r3,%r5; bge- 1f; mtctr %r3; bctr; 1: trap; EMIT_BUG_ENTRY 1b,"arch/powerpc/sysdev/dcr-low.S",31,0; blr
         ^
```
It looks like the diagnostic is referring to the `cmpli` instructions.

I think `cmpli` should have 4 operands, not 3?

**Comment by mpe** [comment]
Yeah. Looks like gas will accept an implied L=0 when building in 32-bit mode.

I do see some mention of a three-argument version in some old docs, but that's for omitting the CR field, not the L field.

Sent a kernel patch for it: https://lore.kernel.org/linuxppc-dev/20211014024424.528848-1-mpe@ellerman.id.au/T/#u

**Comment by paulmenzel** [comment]
Thank you for the patch and adding the URL here. Maybe you could also add the URL of the GitHub issue to the commit message.

> BugLink: https://github.com/ClangBuiltLinux/linux/issues/1419

**Comment by mpe** [comment]
Fix is now in [my next branch](https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?id=fef071be57dc43679a32d5b0e6ee176d6f12e9f2).

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=fef071be57dc43679a32d5b0e6ee176d6f12e9f2
