### ISSUE TITLE
upstream AutoFDO directions

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1425]
similar to #1074 , we should send kernel docs for building the kernel with AutoFDO.  IIRC, we don't need ANY kernel patches, we can use `KCFLAGS` at the command line invocation of `make`.  But @gwelymernans had really good documentation in https://git.kernel.org/pub/scm/linux/kernel/git/kees/linux.git/diff/Documentation/dev-tools/pgo.rst?h=for-next/clang/pgo&id=3bc68891829b776b9a5dd9174de05e69138af7b6 that we should strive to match in quality.

**Comment by nickdesaulniers** [comment]
Yabin added directions for simpleperf on Android in:
https://android-review.googlesource.com/c/platform/system/extras/+/1753107
https://android.googlesource.com/platform/system/extras/+/master/simpleperf/doc/collect_etm_data_for_autofdo.md

**Comment by nickdesaulniers** [comment]
Issues with autofdo processing perf.data: https://github.com/google/autofdo/issues/144
Issues with LBR on Zen2: https://www.spinics.net/lists/linux-perf-users/msg23103.html

**Comment by ptr1337** [comment]
I think we can close this now :)
Really glad to see to have it merged soon.

**Comment by nathanchance** [comment]
We will close this up when it is merged into mainline.

I should link to the accepted version in the Kbuild tree and mark this as accepted, I forgot we had an issue open about it :)

http://git.kernel.org/masahiroy/linux-kbuild/l/0dcc2d1066150787017a71f035145c566597dec7

**Comment by nathanchance** [comment]
This has been merged into mainline with the 6.13 Kbuild pull request: https://git.kernel.org/linus/6a34dfa15d6edf7e78b8118d862d2db0889cf669
