### ISSUE TITLE
`llvm-objdump: error: 'vmlinux': not a dynamic object` with pseries_defconfig

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1427]
After commit [24d33ac5b8ff](https://git.kernel.org/linus/24d33ac5b8ffb7a0e697344fea8591376162548f) ("powerpc/64s: Make prom_init require RELOCATABLE") in mainline, I see the following error after `arch/powerpc/tools/relocs_check.sh` runs:

```
$ make -skj"$(nproc)" ARCH=powerpc CROSS_COMPILE=powerpc64-linux-gnu- LD=powerpc64-linux-gnu-ld LLVM=1 O=build/powerpc distclean pseries_defconfig vmlinux
...
llvm-objdump: error: 'vmlinux': not a dynamic object
...
```

It appears to be related to the fact that `CONFIG_RELOCATABLE` is enabled now and there appears to be some history behind that `-R` flag that is notated in commit [`6b1992bcdee8`](https://git.kernel.org/linus/6b1992bcdee8b86a74362192d4d8906731918bcc) ("powerpc: unrel_branch_check.sh: enable the use of llvm-objdump v9, 10 or 11").

@mpe I am guessing that `relocs_check.sh` might need to be modified in a similar way or is there something else going on here?

**Comment by MaskRay** [comment]
`llvm-objdump -R` doesn't support `ET_EXEC` (position-dependent executable) yet. I'll resurrect  https://reviews.llvm.org/D60250 whose author may be inactive on LLVM now.

Prefer `readelf/llvm-readelf -r` to read relocations.

Uploaded https://reviews.llvm.org/D110595 to improve `llvm-objdump -R`

**Comment by nathanchance** [comment]
https://github.com/llvm/llvm-project/commit/74a47e54be7992b6ccad36b53b6808a7032607c7
