### ISSUE TITLE
BTI issues with allmodconfig on mainline with LLVM 11

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1428]
https://github.com/ClangBuiltLinux/continuous-integration2/runs/3010034514?check_suite_focus=true

**Comment by nathanchance** [comment]
Patch submitted: https://lore.kernel.org/r/20210709000627.3183718-1-nathan@kernel.org/

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/8cdd23c23c3d481a43b4aa03dcb5738812831115
