### ISSUE TITLE
-Wimplicit-fallthrough needlessly warning about unreachable code

### ISSUE THREAD

**Issue by kees** [ClangBuiltLinux/linux#1429]
There are some places in the kernel where the "fallthrough;" annotation is used after a portion of code that may get elided at build time:

```
case 1:
    if (something || !IS_ENALBED(CONFIG_SOMETHING))
        return blah;
    fallthrough;
case 2:
```

This looks like:

```
case 1:
    fallthrough;
case 2:
```

And a warning is generated:

```warning: fallthrough annotation in unreachable code [-Wimplicit-fallthrough]```

But isn't a useful warning in this case, and should likely be silenced or adjust to not warn where there was actually code there before getting elided. At the least, this warning would be best moved to a separate flag so it can be disabled on kernel builds (i.e. GCC does not warn about these cases).

Some specific examples:

- https://github.com/ClangBuiltLinux/continuous-integration2/runs/3058126539?check_suite_focus=true#step:5:120
- https://github.com/ClangBuiltLinux/continuous-integration2/runs/3058126329?check_suite_focus=true#step:5:92

@GustavoARSilva

**Comment by kees** [comment]
LLVM bug: https://llvm.org/pr51094

**Comment by kees** [comment]
This bug is now directly blocking Clang's use of -Wimplicit-fallthrough in the kernel:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d936eb23874433caa3e3d841cfa16f5434b85dcf

**Comment by kees** [comment]
Probably a solution like this is needed:
https://reviews.llvm.org/D31069

Though it's still very strange that this warning doesn't say what line of code the problem happens at...

**Comment by nathanchance** [comment]
Initial stab: https://reviews.llvm.org/D107933

**Comment by nathanchance** [comment]
https://github.com/llvm/llvm-project/commit/9ed4a94d6451046a51ef393cd62f00710820a7e8
