### ISSUE TITLE
arch/arm64/include/asm/archrandom.h giving build errors

### ISSUE THREAD

**Issue by ffainelli** [ClangBuiltLinux/linux#1430]
Hello,

Trying to build Linus' master with Ubuntu clang version 11.0.0-2~ubuntu20.04.1 is currently resulting in the following build failures:

`./arch/arm64/include/asm/stack_pointer.h:8:51: error: register 'sp' unsuitable for global register variables on this target
register unsigned long current_stack_pointer asm ("sp");
                                                  ^
In file included from arch/arm64/kernel/asm-offsets.c:10:
In file included from ./include/linux/arm_sdei.h:8:
In file included from ./include/acpi/ghes.h:5:
In file included from ./include/acpi/apei.h:9:
In file included from ./include/linux/acpi.h:13:
In file included from ./include/linux/irqdomain.h:35:
In file included from ./include/linux/of.h:17:
In file included from ./include/linux/kobject.h:20:
In file included from ./include/linux/sysfs.h:16:
In file included from ./include/linux/kernfs.h:12:
In file included from ./include/linux/mutex.h:19:
In file included from ./arch/arm64/include/asm/processor.h:36:
In file included from ./arch/arm64/include/asm/pointer_auth.h:7:
In file included from ./include/linux/random.h:121:
./arch/arm64/include/asm/archrandom.h:20:2: error: unknown register name 'r0' in asm
        arm_smccc_1_1_invoke(ARM_SMCCC_TRNG_VERSION, &res);
        ^
./include/linux/arm-smccc.h:537:4: note: expanded from macro 'arm_smccc_1_1_invoke'
                        arm_smccc_1_1_hvc(__VA_ARGS__);                 \
                        ^
./include/linux/arm-smccc.h:503:32: note: expanded from macro 'arm_smccc_1_1_hvc'
#define arm_smccc_1_1_hvc(...)  __arm_smccc_1_1(SMCCC_HVC_INST, __VA_ARGS__)
                                ^
./include/linux/arm-smccc.h:460:33: note: expanded from macro '__arm_smccc_1_1'
                register unsigned long r0 asm("r0");                    \
                                              ^
In file included from arch/arm64/kernel/asm-offsets.c:10:
In file included from ./include/linux/arm_sdei.h:8:
In file included from ./include/acpi/ghes.h:5:
In file included from ./include/acpi/apei.h:9:
In file included from ./include/linux/acpi.h:13:
In file included from ./include/linux/irqdomain.h:35:
In file included from ./include/linux/of.h:17:
In file included from ./include/linux/kobject.h:20:
In file included from ./include/linux/sysfs.h:16:
In file included from ./include/linux/kernfs.h:12:
In file included from ./include/linux/mutex.h:19:
In file included from ./arch/arm64/include/asm/processor.h:36:
In file included from ./arch/arm64/include/asm/pointer_auth.h:7:
In file included from ./include/linux/random.h:121:
./arch/arm64/include/asm/archrandom.h:20:2: error: unknown register name 'r1' in asm
./include/linux/arm-smccc.h:537:4: note: expanded from macro 'arm_smccc_1_1_invoke'
                        arm_smccc_1_1_hvc(__VA_ARGS__);                 \
                        ^
`

And list keeps on going for each and every register specified. To reproduce:

- checkout Linus' master branch at v5.13-12730-g50be9417e23a
- ARCH=arm64 LLVM=1 make defconfig
- ARCH=arm64 LLVM=1 make -j9

**Comment by nathanchance** [comment]
@ffainelli thanks for the report! Is this a cross compile or native build? If cross compile, you appear to be missing `CROSS_COMPILE=aarch64-linux-gnu-`, unless that exported in your environment? We are looking to eliminate the need for `CROSS_COMPILE` with `LLVM=1 LLVM_IAS=1` (no GNU tools) but that series is not in master yet: https://github.com/ClangBuiltLinux/linux/issues/1399

I believe that

```
$ make -j9 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1 defconfig all
```

should work with no issues but let us know if not.

**Comment by ffainelli** [comment]
@nathanchance yes your suggested command works nicely, I did not have CROSS_COMPILE set in my environment and that was a mistake. Thanks!
