### ISSUE TITLE
Infinite loop in drivers/hwmon/aspeed-pwm-tacho.c on ARCH=riscv allmodconfig

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1431]
When building `ARCH=riscv allmodconfig` with LLVM 13, clang hangs while compiling `drivers/hwmon/aspeed-pwm-tacho.c`. I bisected this down to [[RISCV] Add DAG combine to detect opportunities to replace (i64 (any_extend (i32 X)) with sign_extend.](https://github.com/llvm/llvm-project/commit/d4f4a1ba626d7c3e4442d6f68feb79d56eba9601) and I have reported it upstream [on Phabricator](https://reviews.llvm.org/D104581).

**Comment by nathanchance** [comment]
Craig submitted a patch that resolves this for me: https://reviews.llvm.org/D106754

**Comment by nathanchance** [comment]
This has been resolved in main (LLVM 14) but needs to be cherry-picked to `release/13.x`. Craig already added the PR as a release blocker: https://llvm.org/pr51206

**Comment by nickdesaulniers** [comment]
From the bug:
> Merged: 9ac5717f9de6
