### ISSUE TITLE
default on LLVM_IAS=1

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1434]
now that we have LLVM_IAS=1 enabled for MIPS in CI, that leaves just s390 and powerpc without LLVM_IAS=1 support. Let's turn it on by default and have uses opt out explicitly via LLVM_IAS=0.

**Comment by nathanchance** [comment]
Something to keep in mind is that `ARCH=arm` and `ARCH=riscv` did not become buildable with `LLVM_IAS=1` until LLVM 13.0.0. `ARCH=arm64` and `ARCH=x86_64` are buildable with `LLVM_IAS=1` since LLVM 11.0.0 so a rhetorical question: should this be version dependent?

**Comment by nickdesaulniers** [comment]
It's a good point and question.

> should this be version dependent?

I think we can simply require folks set `LLVM_IAS=0 CROSS_COMPILE=arm-linux-gnueabihf-` etc for those older toolchains.  This encourages folks to upgrade their tools to have nice things; in this case, a shorter command line.

**Comment by nickdesaulniers** [comment]
v1: https://lore.kernel.org/lkml/20210802234304.3519577-1-ndesaulniers@google.com/

**Comment by nathanchance** [comment]
We should also check the various CI systems and see what versions of LLVM they are using along with how they are building the kernel, otherwise that patch could end up breaking them.

**Comment by nickdesaulniers** [comment]
I mentioned this to @gctucker on Tuesday's KernelCI meeting. If they're not using LLVM=1 when building s390 or ppc, they should be fine.

Perhaps worthwhile to reach out to 0day folks as well.

**Comment by nathanchance** [comment]
> If they're not using LLVM=1 when building s390 or ppc, they should be fine.

Unless I am reading that patch wrong, that impacts `CC=clang` too.

**Comment by nickdesaulniers** [comment]
v2: https://lore.kernel.org/lkml/20210806172701.3993843-1-ndesaulniers@google.com/

(probably should have added a Link tag to here)

**Comment by nickdesaulniers** [comment]
accepted
1: https://git.kernel.org/pub/scm/linux/kernel/git/masahiroy/linux-kbuild.git/commit/?h=for-next&id=52cc02b910284d6bddba46cce402044ab775f314
2: https://git.kernel.org/pub/scm/linux/kernel/git/masahiroy/linux-kbuild.git/commit/?h=for-next&id=f12b034afeb3a977bbb1c6584dedc0f3dc666f14

**Comment by nickdesaulniers** [comment]
1. 52cc02b910284d6bddba46cce402044ab775f314
2. f12b034afeb3a977bbb1c6584dedc0f3dc666f14
