### ISSUE TITLE
/tmp/sm4-c916c8.s:677: Warning: ignoring changed section attributes for .data..cacheline_aligned

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1441]
```
$ make -skj"$(nproc)" CC=clang LLVM_IAS=0 distclean allmodconfig lib/crypto/sm4.o
/tmp/sm4-c916c8.s: Assembler messages:
/tmp/sm4-c916c8.s:677: Warning: ignoring changed section attributes for .data..cacheline_aligned
```

Why this does not happen with the integrated assembler, I have no idea.

Patch submitted: https://lore.kernel.org/r/20210825203859.416449-1-nathan@kernel.org/

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/herbert/cryptodev-2.6.git/commit/?id=4a7e1e5fc294687a8941fa3eeb4a7e8539ca5e2f

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/4a7e1e5fc294687a8941fa3eeb4a7e8539ca5e2f
