### ISSUE TITLE
-Werror turned on by default in 5.15-rc1

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1449]
https://git.kernel.org/linus/3fe617ccafd6f5bb33c2391d6f4eeb41c1fd0151

Some of our builds are not warning free even on mainline, meaning this is going to bite us quite hard. We can turn it off in CI wherever necessary but we should prioritize getting them cleaned up. I think most noisy warnings are the `-Wframe-larger-than=` warnings that we get with `CONFIG_KASAN`, which we are tracking as #39.

**Comment by nathanchance** [comment]
I sent out a report about this: https://lore.kernel.org/r/YTbOs13waorzamZ6@Ryzen-9-3900X.localdomain/

**Comment by nickdesaulniers** [comment]
LKML discussion: https://lore.kernel.org/lkml/20210907183843.33028-1-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment]
b339ec9c229aaf399296a120d7be0e34fbc355ca by @melver demoted this to just default on CONFIG_COMPILE_TEST=y.

**Comment by nathanchance** [comment]
I have added a `CONFIG_WERROR` label for things that break `allmodconfig`/`allyesconfig` so that we can try to prioritize fixing those things and re-enabling it in CI.

**Comment by dileks** [comment]
"kbuild: Only default to -Werror if COMPILE_TEST"

https://git.kernel.org/linus/b339ec9c229aaf399296a120d7be0e34fbc355ca
