### ISSUE TITLE
multiple -Wsometimes-uninitialized in drivers/net/ethernet/mellanox/mlx5/core/en/rep/bridge.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1450]
via: https://github.com/ClangBuiltLinux/continuous-integration2/runs/3548891300?check_suite_focus=true
```
Error: /builds/linux/drivers/net/ethernet/mellanox/mlx5/core/en/rep/bridge.c:157:11: error: variable 'err' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
Error: /builds/linux/drivers/net/ethernet/mellanox/mlx5/core/en/rep/bridge.c:262:7: error: variable 'err' is used uninitialized whenever switch case is taken [-Werror,-Wsometimes-uninitialized]
Error: /builds/linux/drivers/net/ethernet/mellanox/mlx5/core/en/rep/bridge.c:257:7: error: variable 'err' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
```

**Comment by nathanchance** [comment]
This has been pending for net for a while: https://lore.kernel.org/r/20210907212420.28529-2-saeed@kernel.org/

Upstream report: https://lore.kernel.org/r/CA+G9fYsV7sTfaefGj3bpkvVdRQUeiWCVRiu6ovjtM=qri-HJ8g@mail.gmail.com/

Sorry, forgot to file an issue (I have been really bad about that for warnings lately).

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/8343268ec3cf4e097aa8b2071f0cd6779e2c4953
