### ISSUE TITLE
drivers/infiniband/hw/qib/qib_sysfs.c:413:1: error: static_assert expression is not an integral constant expression

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1452]
After https://git.kernel.org/linus/84f969e1c48ed3825986e91a0786e363d57f69d1, which is now in mainline:

```
$ make -skj"$(nproc)" LLVM=1 allmodconfig drivers/infiniband/hw/qib/qib_sysfs.o
drivers/infiniband/hw/qib/qib_sysfs.c:413:1: error: static_assert expression is not an integral constant expression
QIB_DIAGC_ATTR(rc_resends);
^~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/infiniband/hw/qib/qib_sysfs.c:406:16: note: expanded from macro 'QIB_DIAGC_ATTR'
        static_assert(&((struct qib_ibport *)0)->rvp.n_##N != (u64 *)NULL);    \
        ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:77:50: note: expanded from macro 'static_assert'
#define static_assert(expr, ...) __static_assert(expr, ##__VA_ARGS__, #expr)
                                 ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:78:56: note: expanded from macro '__static_assert'
#define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
                                                       ^~~~
drivers/infiniband/hw/qib/qib_sysfs.c:413:1: note: cannot access field of null pointer
drivers/infiniband/hw/qib/qib_sysfs.c:406:43: note: expanded from macro 'QIB_DIAGC_ATTR'
        static_assert(&((struct qib_ibport *)0)->rvp.n_##N != (u64 *)NULL);    \
                                                 ^
...
```

GCC back to at least 7.5.0 has no issues with this construct.

**Comment by nathanchance** [comment]
I am guessing the `note: cannot access field of null pointer` is the crux of the matter.

**Comment by nickdesaulniers** [comment]
Should this be changed to `BUILD_BUG_ON` instead of using `static_assert`?

**Comment by nathanchance** [comment]
I'll test it to see if it fixes it.

**Comment by nathanchance** [comment]
Ah, `BUILD_BUG_ON` won't work as these structures are not declared within a function but globally within the file so the `do { ... } while (0)` from `__compiletime_assert` does not work.

**Comment by nickdesaulniers** [comment]
I don't understand the check; they're testing the offset of a member isn't 0? Sounds like they should be using offset of, not pointer comparisons.

**Comment by nathanchance** [comment]
They do use `offsetof`. Are they making sure the member of the structure is the size of a `u64 *`?

**Comment by nickdesaulniers** [comment]
Upstream thread: https://lore.kernel.org/llvm/20210913165317.GX2505917@nvidia.com/.

**Comment by dileks** [comment]
I can confirm this issue with `Linux v5.15-rc1+` and `LLVM v13.0.0-rc3`.
Happily, it is the only error breaking my 1st build.

**Comment by nathanchance** [comment]
We have a solution pending: https://lore.kernel.org/r/0-v1-1b789bd4dbd4+14b16-clang-fix_jgg@nvidia.com/

**Comment by dileks** [comment]
Thanks.
That is what I applied as a diff and was able to continue building.
```
$ cat /proc/version 
Linux version 5.15.0-rc1-1-amd64-clang13-lto (sedat.dilek@gmail.com@iniza) (dileks clang version 13.0.0 (https://github.com/llvm/llvm-project.git 1f27fe6128769f00197925c3b8f6abb9d0e5cd2e), LLD 13.0.0 (https://github.com/llvm/llvm-project.git 1f27fe6128769f00197925c3b8f6abb9d0e5cd2e)) #1~bookworm+dileks1 SMP 2021-09-15
```

**Comment by dileks** [comment]
Patch is in `rdma` Git tree.

[1] https://git.kernel.org/rdma/rdma/c/1b789bd4dbd48a92f5427d9c37a72a8f6ca17754

Update 2021-09-23: Commit-ID changed in `rdma.git#for-rc`.

[1] https://git.kernel.org/rdma/rdma/c/3110b942d36b961858664486d72f815d78c956c3

**Comment by dileks** [comment]
Now in Linus Git.

[1] https://git.kernel.org/linus/3110b942d36b961858664486d72f815d78c956c3
