### ISSUE TITLE
Higher stack use with KASAN on 32-bit ARM

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1454]
As initially reported on [the mailing list](https://lore.kernel.org/r/YTkjJPCdR1VGaaVm@archlinux-ax161/), the following warnings are only seen with `CONFIG_KASAN` on `allmodconfig` (i.e. I do not see them with `allmodconfig`+`CONFIG_KASAN=n` AND `CONFIG_KASAN_STACK` is not set):

```
crypto/wp512.c:782:13: warning: stack frame size (1176) exceeds limit (1024) in function 'wp512_process_buffer' [-Wframe-larger-than]
static void wp512_process_buffer(struct wp512_ctx *wctx) {
            ^
1 warning generated.

drivers/staging/rtl8723bs/core/rtw_security.c:1288:5: warning: stack frame size (1040) exceeds limit (1024) in function 'rtw_aes_decrypt' [-Wframe-larger-than]
u32 rtw_aes_decrypt(struct adapter *padapter, u8 *precvframe)
    ^
1 warning generated.

drivers/mtd/chips/cfi_cmdset_0001.c:1872:12: warning: stack frame size (1064) exceeds limit (1024) in function 'cfi_intelext_writev' [-Wframe-larger-than]
static int cfi_intelext_writev (struct mtd_info *mtd, const struct kvec *vecs,
           ^
1 warning generated.

drivers/ntb/hw/idt/ntb_hw_idt.c:1041:27: warning: stack frame size (1032) exceeds limit (1024) in function 'idt_scan_mws' [-Wframe-larger-than]
static struct idt_mw_cfg *idt_scan_mws(struct idt_ntb_dev *ndev, int port,
                          ^
1 warning generated.

drivers/staging/fbtft/fbtft-core.c:992:5: warning: stack frame size (1064) exceeds limit (1024) in function 'fbtft_init_display' [-Wframe-larger-than]
int fbtft_init_display(struct fbtft_par *par)
    ^
drivers/staging/fbtft/fbtft-core.c:902:12: warning: stack frame size (1072) exceeds limit (1024) in function 'fbtft_init_display_from_property' [-Wframe-larger-than]
static int fbtft_init_display_from_property(struct fbtft_par *par)
           ^
2 warnings generated.
```

These are all fairly close to the limit so it should be possible to modify the source to resolve these and @arndb [tested gcc-11 with `CONFIG_KASAN_STACK`](https://lore.kernel.org/r/CAK8P3a2--kfvs-+qkZdpea94ccgcY6QpdHMfVFgY0F2Z=GBhyw@mail.gmail.com/) and found that some of the same source locations result in higher stack usage as well

**Comment by nathanchance** [comment]
NOTE: I did not file this under #39 as `CONFIG_KASAN_STACK` is not enabled but these warnings are still visible. Feel free to collapse if warranted.

**Comment by nathanchance** [comment]
@arndb has this in his randconfig tree: https://git.kernel.org/arnd/playground/c/88061f9f28780bb03a4609c63cc847b732371054

Is this something that could be submitted upstream?

**Comment by arndb** [comment]
There is another patch in the same tree that raises the limit to 1400 bytes with KASAN. I think we could do that and it would work with KASAN on clang and with KASAN_STACK on gcc, but not KASAN_STACK with clang.

**Comment by nathanchance** [comment]
I think that until #39 is dealt with, it is probably work marking `CONFIG_KASAN_STACK` as completely broken with clang.

**Comment by nickdesaulniers** [comment]
duplicating this to #39.  Once the two issues identified by https://github.com/ClangBuiltLinux/linux/issues/39#issuecomment-1756321689 are fixed in clang, we can reopen this if necessary.

2 additional things are conspiring here (that are unavoidable):
1. [AAPC32 6.4 Result Return](https://github.com/ARM-software/abi-aa/blob/main/aapcs32/aapcs32.rst#result-return) "A Composite Type larger than 4 bytes, or whose size cannot be determined statically by both caller and callee, is stored in memory at an address passed as an extra argument when the function was called" which is leading to issues, particularly in AMDGPU.
2. KASAN requires ~8x the stack size; so any excessive stack usages is exacerbated
