### ISSUE TITLE
boot failure in -next, cfi, tip

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1461]
example:
https://github.com/ClangBuiltLinux/continuous-integration2/runs/3647206606?check_suite_focus=true

@andyhhp on irc mentions that it might be fixed by:
https://lore.kernel.org/lkml/CADYN=9K1BdyupzcDAbyk2JTio1A98J9tsBS_LeOH4=GVG=7FqQ@mail.gmail.com/
cc @roxell 

And that it looks like kvm isn't being used on these bots, FWIW.
https://github.com/ClangBuiltLinux/boot-utils/blob/2edbca214f9a4cabd3f138ea029015d6cf52d110/boot-qemu.sh#L278-L288

**Comment by nathanchance** [comment]
I could only reproduce with Debian's QEMU version (my self built or Arch Linux versions did not show it) but I never tried without KVM. I will test that diff too.

**Comment by nickdesaulniers** [comment]
it fixes the issue, I'm reporting that upstream now.

**Comment by nickdesaulniers** [comment]
I think this may also be affecting CFI now, too.
https://github.com/ClangBuiltLinux/continuous-integration2/runs/3657928762?check_suite_focus=true
I should probably pull this down into the CI, once https://github.com/ClangBuiltLinux/continuous-integration2/pull/203 is merged.

**Comment by nickdesaulniers** [comment]
oh, -next is also broken now, too. Not just tip and cfi:
https://github.com/ClangBuiltLinux/continuous-integration2/runs/3663307375?check_suite_focus=true

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=724fc0248d450224b19ef5b5ee41e392348f6704
