### ISSUE TITLE
using -fno-discard-value-names

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1467]
I was thinking of adding:
```diff
diff --git a/scripts/Makefile.build b/scripts/Makefile.build
index 3efc984d4c69..3447fe86bbe0 100644
--- a/scripts/Makefile.build
+++ b/scripts/Makefile.build
@@ -145,7 +145,8 @@ $(obj)/%.symtypes : $(src)/%.c FORCE
 # LLVM assembly
 # Generate .ll files from .c
 quiet_cmd_cc_ll_c = CC $(quiet_modtag)  $@
-      cmd_cc_ll_c = $(CC) $(c_flags) -emit-llvm -S -o $@ $<
+      cmd_cc_ll_c = \
+      $(CC) $(c_flags) -fno-discard-value-names -emit-llvm -S -o $@ $<
 
 $(obj)/%.ll: $(src)/%.c FORCE
        $(call if_changed_dep,cc_ll_c)
```
but this doesn't seem to change the output of `make LLVM=1 -j72 lib/string.ll` though the flag is passed. Adding `-fdiscard-value-names` does; I wonder if there's some config in LLVM that controls this, and whether it's set for debian builds, too?

**Comment by nathanchance** [comment]
The code in LLVM that controls the default:

https://github.com/llvm/llvm-project/blob/ebeb191b65feec74d54cec574e6bcae9f269cf8b/clang/lib/Driver/ToolChains/Clang.cpp#L4822-L4832

**Comment by nathanchance** [comment]
https://lore.kernel.org/20221007203236.1750890-1-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment]
v3: https://lore.kernel.org/llvm/20221014165302.845203-1-ndesaulniers@google.com/

**Comment by nathanchance** [comment]
https://git.kernel.org/linus/c67a85bee78db74c6889a5ca645c3763ad23d863
