### ISSUE TITLE
-Wbitwise-instead-of-logical in arch/x86/kvm/mmu/mmu.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1474]
@torvic9 reported: https://lore.kernel.org/lkml/1446878298.170497.1633338512925@office.mailbox.org/
```
In file included from arch/x86/kvm/mmu/mmu.c:27:
arch/x86/kvm/mmu/spte.h:318:9: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
        return __is_bad_mt_xwr(rsvd_check, spte) |
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                 ||
arch/x86/kvm/mmu/spte.h:318:9: note: cast one or both operands to int to silence this warning
```

**Comment by torvic9** [comment]
Is it possible to work around this warning?
Can I use something like `-Wnobitwise-instead-of-logical`, and if so, where?

**Comment by nathanchance** [comment]
Perhaps this?

```
diff --git a/arch/x86/kvm/mmu/spte.h b/arch/x86/kvm/mmu/spte.h
index eb7b227fc6cf..9a8f20612dc7 100644
--- a/arch/x86/kvm/mmu/spte.h
+++ b/arch/x86/kvm/mmu/spte.h
@@ -313,9 +313,10 @@ static __always_inline bool is_rsvd_spte(struct rsvd_bits_validate *rsvd_check,
        /*
         * Use a bitwise-OR instead of a logical-OR to aggregate the reserved
         * bits and EPT's invalid memtype/XWR checks to avoid an extra Jcc
-        * (this is extremely unlikely to be short-circuited as true).
+        * (this is extremely unlikely to be short-circuited as true). The cast
+        * to int silences a clang warning about the use of a bitwise-OR here.
         */
-       return __is_bad_mt_xwr(rsvd_check, spte) |
+       return (int)__is_bad_mt_xwr(rsvd_check, spte) |
               __is_rsvd_bits_set(rsvd_check, spte, level);
 }

```

**Comment by nickdesaulniers** [comment]
> Can I use something like -Wnobitwise-instead-of-logical, and if so, where?

`make LLVM=1 ... KCFLAGS=-Wnobitwise-instead-of-logical`
for now

**Comment by torvic9** [comment]
@nathanchance, yes, casting to integer fixes this.

**Comment by nickdesaulniers** [comment]
perhaps should be unsigned for bitwise operations

**Comment by nickdesaulniers** [comment]
this is affecting CI: https://github.com/ClangBuiltLinux/continuous-integration2/runs/3854417767?check_suite_focus=true

**Comment by nickdesaulniers** [comment]
also `s/a clang warning about the use of a bitwise-OR/-Wbitwise-instead-of-logical/`

**Comment by nathanchance** [comment]
Paolo sent https://lore.kernel.org/r/20211015085148.67943-1-pbonzini@redhat.com/.

**Comment by nathanchance** [comment]
Paolo's fix was rejected at pull time, it sounds like he is just going to change `|` to `||`: https://lore.kernel.org/r/93d4156f-4d81-da15-b93e-79f3ec9bebdb@redhat.com/

**Comment by nathanchance** [comment]
Paolo's new fix: https://git.kernel.org/pub/scm/virt/kvm/kvm.git/commit/?id=3d5e7a28b1ea2d603dea478e58e37ce75b9597ab

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/3d5e7a28b1ea2d603dea478e58e37ce75b9597ab

**Comment by nickdesaulniers** [comment]
I think we need to chase backports of this into stable?

**Comment by nathanchance** [comment]
Ah yes, I do not usually chase backports for warning fixes but I forgot that `-Werror` is now a thing AND `arch/x86/kvm` has `-Werror` separately from https://git.kernel.org/linus/ead68df94d248c80fdbae220ae5425eb5af2e753, which showed up in 5.6 so it needs to go back at least that far. I can take care of this tomorrow.

**Comment by nathanchance** [comment]
Backport submitted: https://lore.kernel.org/r/YYQjyo%2FdKfDb%2Fno3@archlinux-ax161/

**Comment by nathanchance** [comment]
Backport is now queued up for the next stable releases:

https://git.kernel.org/stable/stable-queue/c/cc9ccdbfd4434eeb8b66f9905b5def5067c31be6
https://git.kernel.org/stable/stable-queue/c/180ba858fc653604722b21cdd525a6a95406d0b0
https://git.kernel.org/stable/stable-queue/c/ba0406c24845cdd2e9bf99093e768b97a0061de9
