### ISSUE TITLE
unexpected end of section

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1480]
via https://github.com/ClangBuiltLinux/continuous-integration2/runs/3927890481?check_suite_focus=true:
```
Warning: sound/pci/trident/snd-trident.lto.o: warning: objtool: .text.snd_trident_free_voice: unexpected end of section
Warning: drivers/video/fbdev/intelfb/intelfb.lto.o: warning: objtool: .text.intelfbhw_validate_mode: unexpected end of section
Warning: drivers/net/ethernet/wiznet/w5100.lto.o: warning: objtool: .text.w5100_tx_skb: unexpected end of section
Warning: drivers/net/ethernet/wiznet/w5100.lto.o: warning: objtool: .text.w5100_readbuf: unexpected end of section
```
I'm surprised to see `.lto.o` files as part of allmodconfig. Isn't LTO disabled for allmodconfig?

**Comment by nathanchance** [comment]
That is an allmodconfig + ThinLTO build.

**Comment by nickdesaulniers** [comment]
ah, right, the "kconfig" is printed from the build.json (otherwise the config/build name is cutoff in github UI for me).

**Comment by nathanchance** [comment]
Reported upstream: https://reviews.llvm.org/D105169#3116810

I believe current ToT should be fine, as it has a revert of that change: https://github.com/llvm/llvm-project/commit/fd9b099906c61e46574d1ea2d99b973321fe1d21

**Comment by nathanchance** [comment]
Closing as the problematic commit has been reverted and we have a reproducer so that it is fixed in the next revision.

**Comment by nathanchance** [comment]
This is [likely going to come back](https://reviews.llvm.org/D105169#3246378) so I am preemptively reopening this.

On Monday, I will try to distill down [some of the warnings I see](https://reviews.llvm.org/D105169#3244624) and start a thread with Josh and Peter upstream to see if there is any way to minimize the impact of this change in `objtool`.

**Comment by nathanchance** [comment]
https://github.com/llvm/llvm-project/commit/1b1c8d83d3567a60280291c0adb95d1d60335509

**Comment by nickdesaulniers** [comment]
`-Xclang -disable-noundef-analysis` might be able to get us back to the previous state, for now.

**Comment by nathanchance** [comment]
I am pretty sure all of these were a result of `CONFIG_UBSAN_DIV_ZERO` (LTO enables `-ffunction-sections` so "fallthrough" warnings become "unexpected end of section" warnings), so I am going to dedup this for #1657, which has more information.
