### ISSUE TITLE
[kernel5.10] [clang] [ glibc 2.32] report "junk at end of line, first unrecognized character is `0'"

### ISSUE THREAD

**Issue by heyg** [ClangBuiltLinux/linux#1489]
After update glibc 2.32 it will report error when clang-13 build kernel5.10 
"
  CC      arch/arm64/kernel/vdso/vgettimeofday.o
/tmp/vgettimeofday-3dfdde.s: Assembler messages:
/tmp/vgettimeofday-3dfdde.s:25: Error: file number less than one
/tmp/vgettimeofday-3dfdde.s:25: Error: junk at end of line, first unrecognized character is `0'
/tmp/vgettimeofday-3dfdde.s:362: Error: file number less than one
/tmp/vgettimeofday-3dfdde.s:362: Error: junk at end of line, first unrecognized character is `2'
/tmp/vgettimeofday-3dfdde.s:519: Error: file number less than one
/tmp/vgettimeofday-3dfdde.s:519: Error: junk at end of line, first unrecognized character is `0'
/tmp/vgettimeofday-3dfdde.s:794: Error: file number less than one
/tmp/vgettimeofday-3dfdde.s:794: Error: junk at end of line, first unrecognized character is `2'
/tmp/vgettimeofday-3dfdde.s:852: Error: file number less than one
/tmp/vgettimeofday-3dfdde.s:852: Error: junk at end of line, first unrecognized character is `0'
/tmp/vgettimeofday-3dfdde.s:985: Error: file number less than one
/tmp/vgettimeofday-3dfdde.s:985: Error: junk at end of line, first unrecognized character is `2'
/tmp/vgettimeofday-3dfdde.s:1014: Error: file number less than one
/tmp/vgettimeofday-3dfdde.s:1014: Error: junk at end of line, first unrecognized character is `2'
/tmp/vgettimeofday-3dfdde.s: Internal error (Segmentation fault).
Please report this bug.
clang-13: error: assembler command failed with exit code 1 (use -v to see invocation)
scripts/Makefile.build:280: recipe for target 'arch/arm64/kernel/vdso/vgettimeofday.o' failed
make[1]: *** [arch/arm64/kernel/vdso/vgettimeofday.o] Error 1
arch/arm64/Makefile:189: recipe for target 'vdso_prepare' failed
make: *** [vdso_prepare] Error 2

"

**Comment by nathanchance** [comment]
What configuration, kernel tree, and exact clang version?

**Comment by nickdesaulniers** [comment]
> Error: file number less than one

Is likely related to generating DWARF v5, but then using a version of GAS that doesn't understand this new DWARF v5 addition. (I filed a bug about that, it was fixed in newer releases of GAS).

So this is likely not using `clang` as the assembler, but GAS. I'll have to look at the 5.10 sources to see if the DWARF v5 kernel support I added was available back then; there's kconfigs to just use DWARF v4 debug info. I also wonder if we had the integrated assembler working for 5.10, including for the vdso. Might be missing a backport necessary for 5.10.

**Comment by heyg** [comment]
> exact clang version




@nathanchance 
Hi Nathan,
What configuration?
	CONFIG_ARM64_VA_BITS_48=y  ---> arm64 config
	CONFIG_ARCH_MESON=y --> AMLOGIC bsp config
it should dosn't matter with vendor chip, report error code is common code.


kernel tree?	
  -> Linux version 5.10.56

exact clang version?
  -> Chromium OS 12.0_pre422132_p20210405-r4 clang version 13.0.0

**Comment by heyg** [comment]
@nickdesaulniers 
Hi Nick,
Thanks,  i thing your anaysis is right.

Here have more info,Maybe this info more useful.
clang 12 is ok for kernel 5.10, 
```
CONFIG_CC_VERSION_TEXT="Chromium OS 12.0_pre408248_p20201125-r7 clang version 12.0.0 (/var/tmp/portage/sys-devel/llvm-12.0_pre408248_p20201125-r7/work/llvm-12.0_pre408248_p20201125/clang f402e682d0ef5598eeffc9a21a691b03e602ff58)"

```

**Comment by nickdesaulniers** [comment]
@heyg are you building with `CC=clang` or `LLVM=1`? Do you set `LLVM_IAS=1` during your invocation of `make`?

**Comment by heyg** [comment]
Hi @nickdesaulniers ,
This issue had fixed.
solution "CONFIG_DEBUG_INFO_DWARF4=y“

Thanks a lot.
