### ISSUE TITLE
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: .text.amdgpu_amdkfd_gpuvm_alloc_memory_of_gpu: unexpected end of section

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#1499]
Hi, I see the mentioned new objtool error on 5.15.0 with the following config and makefile with LLVM/Clang-14 (63fff0f5bffe20fa2c84a45a41161afa0043cb34).

[config.txt](https://github.com/ClangBuiltLinux/linux/files/7490469/config.txt)
[Makefile.txt](https://github.com/ClangBuiltLinux/linux/files/7490470/Makefile.txt)

I haven't seen it yet in the issue section, hence I wanted to let you know.

**Comment by nathanchance** [comment]
I think this might be a duplicate of #1480?

**Comment by ms178** [comment]
Possibly, but that particular warning wasn't mentioned there and the one I found was with a Full LTO build.

**Comment by nathanchance** [comment]
Reported upstream: https://reviews.llvm.org/D105169#3116810

I believe current ToT should be fine, as it has a revert of that change: https://github.com/llvm/llvm-project/commit/fd9b099906c61e46574d1ea2d99b973321fe1d21

**Comment by nickdesaulniers** [comment]
If upstream reverted, should we close this as `[FIXED] llvm (main)`?

**Comment by nathanchance** [comment]
Sure, we can reopen if it comes back.
