### ISSUE TITLE
error: initializer element is not a compile-time constant

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1501]
In -next after both https://git.kernel.org/next/linux-next/c/facfe0a4fdce3f545a4a883358eda3078b0425c7 and https://git.kernel.org/next/linux-next/c/f155dfeaa4ee21bce3f8f76b2addaec396b41b39, KernelCI reports that clang-13 allmodconfig errors:

```
$ make -skj$(nproc) LLVM=1 distclean allmodconfig drivers/platform/chrome/cros_ec_ishtp.o 
drivers/platform/chrome/cros_ec_ishtp.c:778:4: error: initializer element is not a compile-time constant
        { cros_ish_guid },
          ^~~~~~~~~~~~~
1 error generated.

$ make -skj$(nproc) LLVM=1 distclean allmodconfig drivers/platform/x86/intel/ishtp_eclite.o
drivers/platform/x86/intel/ishtp_eclite.c:685:4: error: initializer element is not a compile-time constant
        { ecl_ishtp_guid },
          ^~~~~~~~~~~~~~
1 error generated.
```

Playing around on Compiler Explorer, it looks like GCC 5 through 7 all exhibit the same issue as Clang does (GCC 8 is where it got smart enough to figure out this is known at compile time): https://godbolt.org/z/5vnxY5Y6h

Perhaps Clang should do the same? Regardless, because it breaks older GCCs, it should worked around in the kernel so I have reported it upstream: https://lore.kernel.org/r/YYv22iWQ7yTfMNC5@archlinux-ax161/

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D76096

**Comment by nathanchance** [comment]
Arnd sent https://lore.kernel.org/r/20211111085842.2846422-1-arnd@kernel.org.

**Comment by nathanchance** [comment]
Arnd's patch has been accepted: https://git.kernel.org/hid/hid/c/b763dc3f17a2081312ac0b400916b05ae6056ac5

**Comment by nathanchance** [comment]
Fixed now: https://git.kernel.org/next/linux-next/c/bf9167a8b40c9cf463521da05342db81808c1b6e
