### ISSUE TITLE
arch/x86/crypto/chacha-x86_64.lto.o: warning: objtool fall through errors

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#1504]
Are these two objtool warnings known? A quick search did not yield anything. I've seen these with LLVM/Clang-14 @ llvm-project 5b4bfd8c2415cb38983a56007bb424e063778460 and Linux Kernel 5.15.2.

Here are my customized config/Makefile:
[config.txt](https://github.com/ClangBuiltLinux/linux/files/7533569/config.txt)
[Makefile.txt](https://github.com/ClangBuiltLinux/linux/files/7533570/Makefile.txt)

arch/x86/crypto/chacha-x86_64.lto.o: warning: objtool: chacha_2block_xor_avx512vl() falls through to next function chacha_8block_xor_avx512vl()
arch/x86/crypto/chacha-x86_64.lto.o: warning: objtool: chacha_4block_xor_avx512vl() falls through to next function chacha_8block_xor_avx512vl()

**Comment by nathanchance** [comment]
cc @samitolvanen

**Comment by nickdesaulniers** [comment]
also observed with the config from #1612 , but with thinLTO rather than full

**Comment by nathanchance** [comment]
I think this will go away with Peter’s patch: https://lore.kernel.org/r/20220322115125.737671717@infradead.org/

**Comment by nickdesaulniers** [comment]
ah right, a few reports: https://lore.kernel.org/linux-next/?q=chacha_2block_xor_avx512vl

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/4327d168515fd8b5b92fa1efdf1d219fb6514460
