### ISSUE TITLE
ERROR: modpost: "__compiletime_assert_451" [drivers/net/phy/marvell10g.ko] undefined!

### ISSUE THREAD

**Issue by roxell** [ClangBuiltLinux/linux#1506]
build error on linux-next ARCH=arm64 and toolchain=clang-10 LLVM_IAS=0 https://builds.tuxbuild.com/20w3nK9R51fgYROXYljln032iD9/build.log.

4075a6a047bb ("net: phy: marvell10g: add downshift tunable support") is the offending patch.
Change builds "fine" http://ix.io/3FaL, but http://ix.io/3FaM fails. 

ERROR: modpost: "__compiletime_assert_451" [drivers/net/phy/marvell10g.ko] undefined!
make[2]: *** [/builds/linux/scripts/Makefile.modpost:134: modules-only.symvers] Error 1
make[2]: *** Deleting file 'modules-only.symvers'
make[2]: Target '__modpost' not remade because of errors.
make[1]: *** [/builds/linux/Makefile:1911: modules] Error 2
make[1]: Target '__all' not remade because of errors.
make: *** [Makefile:226: __sub-make] Error 2
make: Target '__all' not remade because of errors.

**Comment by nathanchance** [comment]
It is one of the `BUILD_BUG_ON()` calls in `__BF_FIELD_CHECK()` failing. This only happens with clang-10 I believe, likely for the same reason as #1293 (I do not really have time to reverse bisect to find out). It is possible that we could work around this in the kernel sources but I would really prefer to pursue bumping the minimum required version of LLVM to build the kernel to 11.x, as that is generally well available at this point.

**Comment by nickdesaulniers** [comment]
I've kicked off an automated bisection so that we can at least identify+understand what "fixed" this in LLVM.

**Comment by nickdesaulniers** [comment]
https://github.com/llvm/llvm-project/commit/fa496ce3c6774097080c8a9cb808da56f383b938

first release branch containing the above is remotes/origin/release/11.x as expected.

**Comment by nathanchance** [comment]
Good to know that it is the same fix as #1293.

**Comment by nathanchance** [comment]
I think that https://github.com/ClangBuiltLinux/linux/issues/1511 is the right way to resolve this, instead of inserting hacks in the kernel to work around the issues with DCE with older `clang` versions. I am going to close this up for now, feel free to reopen if you disagree with my assessment.
