### ISSUE TITLE
.init.data has both ordered and unordered sections

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1507]
@roxell reported on IRC:

```
$ make -skj"$(nproc)" ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- distclean defconfig

$ scripts/config -e FTRACE  -e STACK_TRACER

$ make -skj"$(nproc)" ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- olddefconfig vmlinux
aarch64-linux-gnu-ld: .init.data has both ordered [`__patchable_function_entries' in init/main.o] and unordered [`.meminit.data' in mm/sparse.o] sections
aarch64-linux-gnu-ld: final link failed: bad value
...

$ aarch64-linux-gnu-ld --version
GNU ld (GNU Binutils for Debian) 2.35.2
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

$ clang --version
Debian clang version 13.0.1-++20211029101439+08e3a5ccd952-1~exp1~20211029222017.20
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

I reproduced it via the TuxMake arm64 clang-13 image (`docker.io/tuxmake/arm64_clang-13`) and it is reproducible on the `clang-nightly` image as well. A locally produced `clang-13` image based on Ubuntu 21.10 did not reproduce the issue:

```
$ aarch64-linux-gnu-ld --version
GNU ld (GNU Binutils for Ubuntu) 2.37
Copyright (C) 2021 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

$ clang --version
Ubuntu clang version 13.0.0-2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

The issue is not present with `LLVM=1`.

**Comment by ihalip** [comment]
Could be related to the binutils version? https://sourceware.org/bugzilla/show_bug.cgi?id=26256 apparently fixed in 2.36.
I reproduced this too with 2.34.

**Comment by nathanchance** [comment]
Yes, that is what I was thinking and that seems very likely as the root cause of the issue. It is possible that we can turn off this combination of configuration options in Kconfig, or just recommend `LLVM=1` over `CC=clang`.

**Comment by nickdesaulniers** [comment]
Is this an issue with newer GCC that supports -fpatchable-function-entries and older GNU binutils (2.34)? Or just newer clang plus older binutils? If the former, then perhaps the kconfig for -fpatchable-function-entries can be tied to binutils version. Otherwise, we may need kconfig checks for clang plus (lld or newer bfd).

**Comment by nathanchance** [comment]
This problem was also reported by Will Deacon:

https://lore.kernel.org/20220408115407.GA27685@willie-the-truck/

I suggested a diff to resolve it:

https://lore.kernel.org/YlBuH2ScVeRO93AG@dev-arch.thelio-3990X/

**Comment by nathanchance** [comment]
Further information: https://lore.kernel.org/YlCA5PoIjF6nhwYj@dev-arch.thelio-3990X/

**Comment by nickdesaulniers** [comment]
please cc the ML!

**Comment by nathanchance** [comment]
> please cc the ML!

Sorry, I did for [this comment](https://lore.kernel.org/YlBPGFs2PMNX6est@dev-arch.thelio-3990X/) but then I replied to Will in a separate subthread and forgot to do it there :( will make sure to include it for any subsequent follow ups and patches.

**Comment by nathanchance** [comment]
I have sent https://lore.kernel.org/20220413181420.3522187-1-nathan@kernel.org/.

**Comment by nathanchance** [comment]
Patch accepted for the current merge window: https://git.kernel.org/arm64/c/45bd8951806eb5e857772c593de021b09057950d

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/45bd8951806eb5e857772c593de021b09057950d
