### ISSUE TITLE
Both LLVM_IAS=1 and =0 fail with ARCH=powerpc (kernel 5.16rc3)

### ISSUE THREAD

**Issue by emojifreak** [ClangBuiltLinux/linux#1525]
Kernel is 5.16rc3. With `LLVM_IAS=1` we hit https://github.com/ClangBuiltLinux/linux/issues/1451.
In https://github.com/ClangBuiltLinux/linux/issues/1451#issuecomment-915819258 `LLVM_IAS=0` is suggested. Then we have the following error at the very beginning.

```
make --keep-going ARCH=powerpc LLVM=1 LLVM_IAS=0 CROSS_COMPILE=powerpc64le-linux-gnu- all
  SYNC    include/config/auto.conf.cmd
clang --target=powerpc64le-linux-gnu -fno-integrated-as --prefix=powerpc64le-linux-gnu- -Werror=unknown-warning-option -Werror=ignored-optimization-argument: unknown assembler invoked
scripts/Kconfig.include:50: Sorry, this assembler is not supported.
make[2]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[1]: *** [Makefile:619: syncconfig] Error 2
make: *** [Makefile:732: include/config/auto.conf.cmd] Error 2
```

**Comment by nathanchance** [comment]
Do you have the powerpc64le binutils installed or available in PATH?

**Comment by emojifreak** [comment]
Thank you for quick response. That's the exactly cause of this failure. Sorry for my silly mistake.
