### ISSUE TITLE
`CONFIG_CPU_LOONGSON2F=y` and `LLVM_IAS=1` fails with `arch/mips/loongson2ef/Platform:36: *** only binutils >= 2.20.2 have needed option -mfix-loongson2f-nop.  Stop.`

### ISSUE THREAD

**Issue by emojifreak** [ClangBuiltLinux/linux#1529]
32-bit MIPS build with `CONFIG_CPU_LOONGSON2F=y` and `LLVM_IAS=1` immediately fails with `arch/mips/loongson2ef/Platform:36: *** only binutils >= 2.20.2 have needed option -mfix-loongson2f-nop.  Stop.` But this seems nonsense, as `LLVM_IAS=1` does not use binutils. This can be reproduced with

```
#!/bin/sh

KVER=5.16-rc3
LANG=C.UTF-8
export LANG
cd /var/tmp/tmp11mips64el_5

  cat >/tmp/config$$.txt <<EOF
CONFIG_FTRACE_MCOUNT_USE_RECORDMCOUNT=n
CONFIG_KASAN=n
CONFIG_GCOV_KERNEL=n
CONFIG_COMPILE_TEST=n
CONFIG_LD_DEAD_CODE_DATA_ELIMINATION=n
CONFIG_INIT_STACK_ALL_ZERO=y
CONFIG_KVM=y
CONFIG_PREEMPT=y
CONFIG_PREEMPT_DYNAMIC=y

CONFIG_WERROR=n
CONFIG_RUNTIME_TESTING_MENU=n
CONFIG_XFS_FS=n
CONFIG_OVERLAY_FS=n
CONFIG_EMBEDDED=n

CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_INFO_DWARF5=y

CONFIG_ACPI=y
CONFIG_EFI_STUB=y
CONFIG_EFI=y
CONFIG_DMI=y
CONFIG_NUMA=y
CONFIG_MEMORY_HOTPLUG=y
CONFIG_HOTPLUG_PCI=y
CONFIG_HOTPLUG_PCI_PCIE=y
CONFIG_HOTPLUG_CPU=y

CONFIG_KEXEC=n
CONFIG_CPU_LITTLE_ENDIAN=y
CONFIG_CPU_BIG_ENDIAN=n
CONFIG_32BIT=y
CONFIG_64BIT=n

CONFIG_MACH_LOONGSON2EF=y
CONFIG_CPU_LOONGSON2F=y
CONFIG_LEMOTE_MACH2F=y
CONFIG_HIGHMEM=y
CONFIG_HIGHPTE=y
EOF


for a in mips; do
  rm -rf /var/tmp/tmp11mips64el_5/$a
  mkdir /var/tmp/tmp11mips64el_5/$a
  cd /var/tmp/tmp11mips64el_5/$a
  exec </dev/null >build-log-${KVER}-${a}.txt 2>&1
  set -xe
  tar zxf /var/tmp/linux-${KVER}.tar.gz
  cd linux-${KVER}

  cp /tmp/config$$.txt .config
  make LLVM=1 LLVM_IAS=1 CROSS_COMPILE=mips64el-linux-gnuabi64- allmodconfig
  cat /tmp/config$$.txt >>.config

  yes '' |
    chrt --idle 0 nice -19 make --keep-going ARCH=$a LLVM=1 LLVM_IAS=1 CROSS_COMPILE=mipsel-linux-gnu- KCFLAGS="-mllvm -polly-ast-use-context -mllvm -polly-invariant-load-hoisting -mllvm -polly-opt-fusion=max -mllvm -polly-run-inliner -mllvm -polly-vectorizer=stripmine -mllvm -polly-run-dce"  all &
  exec </dev/null >/dev/null 2>&1
done 
wait
```

**Comment by nathanchance** [comment]
This is really saying that `-Wa,-mfix-loongson2f-nop` does not work with the integrated assembler, which is true; the Loongson developers have only contributed the errata fixes to GCC, not LLVM: https://llvm.org/bz49611

Realistically, the `as-option` calls should be removed as binutils 2.23 or newer is required to build the kernel but that won't fix this issue, as the flag is not implemented; it will just make the error a little bit more obvious.

**Comment by nathanchance** [comment]
Patch submitted to resolve this version of this error: https://lore.kernel.org/r/20211207175951.135400-1-nathan@kernel.org/

I plan to close this issue when that is merged, I do not think it is worth tracking the implementation of those flags, as there is already an upstream issue (and I would expect someone from Loongson or an interest in it to do it, given it is their bug).

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/mips/c/13ceb48bc19c563e05f407e663aaa4105fdfd408

**Comment by nickdesaulniers** [comment]
https://lists.llvm.org/pipermail/llvm-dev/2021-December/154371.html

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/13ceb48bc19c563e05f407e663aaa4105fdfd408
