### ISSUE TITLE
LLVM 13 release cycle [dup]

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/linux#1549]
Due to the bugzilla -> GitHub migration the `LLVM version 13.0.1` was delayed.

Tom says in [1]:
> If you have patches you want backported to the release/13.x branch, please
> file an issue and add it to the "LLVM 13.0.1 release" milestone.
>
> Also, if you emailed me a backport request and haven't seen an issue created for
> it yet, please ping me on the email thread, so I don't forget about it.

Deadlines:
> I'm back on track with the release after the buzilla migration, so I'm
> going to accept backport requests until Monday, Dec 20, and then
> I'll try to tag -rc2 on Wed Dec 21.

For the `LLVM version 13.0.1 milestone` see [2].

[1] https://lists.llvm.org/pipermail/llvm-dev/2021-December/154383.html
[2] https://github.com/llvm/llvm-project/milestone/2

**Comment by dileks** [comment]
Follow the `release/13.x` Git branch and `llvmorg-13.0.1-rc2` will be tagged in [2].

[1] https://github.com/llvm/llvm-project/commits/release/13.x
[2] https://github.com/llvm/llvm-project/tags

**Comment by nickdesaulniers** [comment]
dup of #1465 

(These announcements are a useful heads up about approaching deadlines; I find them informative and appreciate them).
