### ISSUE TITLE
'-outline-atomics' is not a recognized feature for this target

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1552]
After commit [dd03762ab608](https://git.kernel.org/arm64/c/dd03762ab608e058c8f390ad9cf667e490089796) ("arm64: Enable KCSAN") in -next, there is a warning when building `kernel/kcsan/core.c` for x86_64:

```
# Flip on CONFIG_KCSAN in menuconfig
$ make -skj"$(nproc)" LLVM=1 distclean defconfig menuconfig kernel/kcsan/core.o
'-outline-atomics' is not a recognized feature for this target (ignoring feature)
'-outline-atomics' is not a recognized feature for this target (ignoring feature)
'-outline-atomics' is not a recognized feature for this target (ignoring feature)
```

This is because `clang` only warns when `-moutline-atomics` is used without backend support, not `-mno-outline-atomics`, so the cc-option check does not work for clang.

```
$ echo | clang -mno-outline-atomics -x c -c -o /dev/null -
'-outline-atomics' is not a recognized feature for this target (ignoring feature)

$ echo | clang -moutline-atomics -x c -c -o /dev/null -
clang-14: warning: 'x86_64' does not support '-moutline-atomics'; flag ignored [-Woption-ignored]
```

This contrasts with GCC:

```
$ echo | gcc -mno-outline-atomics -x c -c -o /dev/null -
gcc: error: unrecognized command-line option ‘-mno-outline-atomics’; did you mean ‘-fno-inline-atomics’?

$ echo | gcc -mno-outline-atomics -x c -c -o /dev/null -
gcc: error: unrecognized command-line option ‘-moutline-atomics’; did you mean ‘-finline-atomics’?

$ echo | aarch64-linux-gnu-gcc -mno-outline-atomics -x c -c -o /dev/null -

$ echo | aarch64-linux-gnu-gcc -moutline-atomics -x c -c -o /dev/null -
```

This can be fixed on the kernel side with something like:

```diff
diff --git a/kernel/kcsan/Makefile b/kernel/kcsan/Makefile
index 4f35d1bced6a..c0a8b4a6ebbd 100644
--- a/kernel/kcsan/Makefile
+++ b/kernel/kcsan/Makefile
@@ -8,9 +8,12 @@ CFLAGS_REMOVE_debugfs.o = $(CC_FLAGS_FTRACE)
 CFLAGS_REMOVE_report.o = $(CC_FLAGS_FTRACE)

 CFLAGS_core.o := $(call cc-option,-fno-conserve-stack) \
-       $(call cc-option,-mno-outline-atomics) \
        -fno-stack-protector -DDISABLE_BRANCH_PROFILING

+ifdef CONFIG_ARM64
+CFLAGS_core.o += $(call cc-option,-mno-outline-atomics)
+endif
+
 obj-y := core.o debugfs.o report.o

 KCSAN_INSTRUMENT_BARRIERS_selftest.o := y
```

but should `clang` be modified to warn when `-mno-outline-atomics` is being used with a non-AArch64 triple or only add `-outline-atomics` to the target features if using an AArch64 triple? The code in question in `clang/lib/Driver/ToolChains/Clang.cpp`:

```cpp
  if (Arg *A = Args.getLastArg(options::OPT_moutline_atomics,
                               options::OPT_mno_outline_atomics)) {
    if (A->getOption().matches(options::OPT_moutline_atomics)) {
      // Option -moutline-atomics supported for AArch64 target only.
      if (!Triple.isAArch64()) {
        D.Diag(diag::warn_drv_moutline_atomics_unsupported_opt)
            << Triple.getArchName();
      } else {
        CmdArgs.push_back("-target-feature");
        CmdArgs.push_back("+outline-atomics");
      }
    } else {
      CmdArgs.push_back("-target-feature");
      CmdArgs.push_back("-outline-atomics");
    }
  } else if (Triple.isAArch64() &&
             getToolChain().IsAArch64OutlineAtomicsDefault(Args)) {
    CmdArgs.push_back("-target-feature");
    CmdArgs.push_back("+outline-atomics");
  }
```

cc @melver for any input you might have.

**Comment by melver** [comment]
I think this is a more fundamental problem with Clang and the fact it silently accepts certain options, which breaks cc-option.

I think Clang shouldn't silently accept options like this, otherwise `cc-option` will just not work. Do we have to improve cc-option for Clang as a workaround (`-Werror=option-ignored`)? We really ought to try and make cc-option behave the same for Clang as it does for GCC.

(Note: I don't like seeing `ifdef CONFIG_ARM64` in kernel/kcsan/Makefile, as that shouldn't be required.)

**Comment by melver** [comment]
Also, which version of LLVM? Is this only LLVM-git?

I can't repro this with Clang 11.

Because if it's only LLVM-git, we should probably fix in LLVM.

**Comment by nathanchance** [comment]
> Do we have to improve cc-option for Clang as a workaround (`-Werror=option-ignored`)? We really ought to try and make cc-option behave the same for Clang as it does for GCC.

[We do add `-Werror` to `cc-option`](https://git.kernel.org/linus/c3f0d0bc5b01ad90c45276952802455750444b4f) so that we can catch instances like this; the primary issue here is that there is not a warning from `clang` with `-mno-outline-atomics` unlike `-moutline-atomics`.

Something like this works for me:

```diff
diff --git a/clang/include/clang/Basic/DiagnosticDriverKinds.td b/clang/include/clang/Basic/DiagnosticDriverKinds.td
index 2aeb987725e1..06ab7e5617f8 100644
--- a/clang/include/clang/Basic/DiagnosticDriverKinds.td
+++ b/clang/include/clang/Basic/DiagnosticDriverKinds.td
@@ -559,7 +559,7 @@ def warn_drv_moutline_unsupported_opt : Warning<
   InGroup<OptionIgnored>;

 def warn_drv_moutline_atomics_unsupported_opt : Warning<
-  "'%0' does not support '-moutline-atomics'; flag ignored">,
+  "'%0' does not support '%1'; flag ignored">,
   InGroup<OptionIgnored>;

 def warn_drv_darwin_sdk_invalid_settings : Warning<
diff --git a/clang/lib/Driver/ToolChains/Clang.cpp b/clang/lib/Driver/ToolChains/Clang.cpp
index 2a3723975568..8c4d1d349fb6 100644
--- a/clang/lib/Driver/ToolChains/Clang.cpp
+++ b/clang/lib/Driver/ToolChains/Clang.cpp
@@ -7011,14 +7011,19 @@ void Clang::ConstructJob(Compilation &C, const JobAction &JA,
       // Option -moutline-atomics supported for AArch64 target only.
       if (!Triple.isAArch64()) {
         D.Diag(diag::warn_drv_moutline_atomics_unsupported_opt)
-            << Triple.getArchName();
+            << Triple.getArchName() << "-moutline-atomics";
       } else {
         CmdArgs.push_back("-target-feature");
         CmdArgs.push_back("+outline-atomics");
       }
     } else {
-      CmdArgs.push_back("-target-feature");
-      CmdArgs.push_back("-outline-atomics");
+      if (!Triple.isAArch64()) {
+        D.Diag(diag::warn_drv_moutline_atomics_unsupported_opt)
+            << Triple.getArchName() << "-mno-outline-atomics";
+      } else {
+        CmdArgs.push_back("-target-feature");
+        CmdArgs.push_back("-outline-atomics");
+      }
     }
   } else if (Triple.isAArch64() &&
              getToolChain().IsAArch64OutlineAtomicsDefault(Args)) {
```

```
$ echo | build/stage1/bin/clang -mno-outline-atomics -x c -c -o /dev/null -
clang-14: warning: 'x86_64' does not support '-mno-outline-atomics'; flag ignored [-Woption-ignored]
```

> I can't repro this with Clang 11.

It looks like `-m{,no-}outline-atomics` was added in Clang 12 so this is something that we will have to solve this for Clang 12 through 14.

https://github.com/llvm/llvm-project/commit/4d7df43ffdb460dddb2877a886f75f45c3fee188

**Comment by melver** [comment]
Feel free to send the LLVM patch, it looks like the right thing to do to match GCC here. I'd also propose that the fix should reach LLVM stable branches.

But I think we don't need to "fix" this in the kernel, given the build is unaffected and merely a cosmetic issue.

**Comment by nathanchance** [comment]
> Feel free to send the LLVM patch, it looks like the right thing to do to match GCC here. I'd also propose that the fix should reach LLVM stable branches.

Thanks, submitted: https://reviews.llvm.org/D116128

I am not sure we will be able to get it into LLVM 13.0.1, as backport requests were closed as of yesterday but I can ping Tom on Discord to get his opinion.

> But I think we don't need to "fix" this in the kernel, given the build is unaffected and merely a cosmetic issue.

Sure, that is fine with me; if others complain, we can deal with it at that time :)

**Comment by nathanchance** [comment]
https://github.com/llvm/llvm-project/commit/be8180af5854806a343c3dd334d97ba2c4bfadfa

**Comment by nickdesaulniers** [comment]
Is this going to be a problem for clang < 14? Are there kernel changes necessary here?

**Comment by nathanchance** [comment]
I suggested a kernel change above that would work but Marco was not a fan. Since it is a small cosmetic issue (one translation unit with one set of warnings) and it will only be seen with `CONFIG_KCSAN`, I don't think it is a big deal.
