### ISSUE TITLE
Usage of deprecated function

### ISSUE THREAD

**Issue by Divyanshu-Modi** [ClangBuiltLinux/linux#1555]
https://github.com/ClangBuiltLinux/linux/blob/83d09ad4b950651a95d37697f1493c00d888d0db/scripts/extract-cert.c#L46
 Recently while building kernel on ubuntu jammy I came across this warn 

as shown here this function is deprecated https://github.com/openssl/openssl/commit/af2f14ace581d30b186429cb3f9f5d14c0b5b4ec

**Comment by nathanchance** [comment]
Thank you for the report! I don't think this is a `clang` specific issue, can you see if this is reproducible with GCC? We generally try to track `clang` specific kernel issues here (this should still be reported upstream in any case).

**Comment by Divyanshu-Modi** [comment]
> Thank you for the report! I don't think this is a `clang` specific issue, can you see if this is reproducible with GCC? We generally try to track `clang` specific kernel issues here (this should still be reported upstream in any case).

yes it is reproducible with gcc. Ok i will report to upstream thx for guidance sir. : )
