### ISSUE TITLE
missing support for tlbiel with 2 args

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1560]
@gwelymernans [had a patch](https://reviews.llvm.org/D92156), but @aik [worked around it](https://lore.kernel.org/llvm/20211221055904.555763-7-aik@ozlabs.ru/) which was [accepted](https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?h=next&id=62479e6e26ef18f00e2e540c0e30156254533a43) by @mpe.

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/62479e6e26ef18f00e2e540c0e30156254533a43
