### ISSUE TITLE
AOSP LLVM r437112 is missing d7e089f2d6a5cd5f283a90ab29241d20d4fc3ed1

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1561]
Initially reported by CI: https://github.com/ClangBuiltLinux/continuous-integration2/runs/4682178291?check_suite_focus=true

```
# Enable CONFIG_THUMB2_KERNEL
$ make -skj"$(nproc)" ARCH=arm LLVM=1 O=/tmp/build defconfig menuconfig vmlinux
...
ld.lld: error: undefined symbol: __aeabi_read_tp
>>> referenced by main.c
>>>               main.o:(do_one_initcall) in archive init/built-in.a
>>> referenced by main.c
>>>               main.o:(trace_initcall_start_cb) in archive init/built-in.a
>>> referenced by main.c
>>>               main.o:(start_kernel) in archive init/built-in.a
>>> referenced 6071 more times
...
```

This was resolved by https://github.com/llvm/llvm-project/commit/d7e089f2d6a5cd5f283a90ab29241d20d4fc3ed1 (https://github.com/ClangBuiltLinux/linux/issues/1485) but that commit is not in AOSP LLVM, which appears to be based on https://github.com/llvm/llvm-project/commit/79d58b4d3017d159bf09a77398c9a116128de193, if I am reading [this commit](https://android.googlesource.com/toolchain/llvm-project/+/8671348b81b95fc603505dfc881b45103bee1731) right in relation to the version string:

```
$ clang --version
Android (7917927, based on r437112) clang version 14.0.0 (https://android.googlesource.com/toolchain/llvm-project 8671348b81b95fc603505dfc881b45103bee1731)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

We currently assume any 14.0.0 toolchain has that commit, as that has always been our policy with regards to tip of tree versions in the kernel.

I tried to take a whack at applying and testing https://github.com/llvm/llvm-project/commit/d7e089f2d6a5cd5f283a90ab29241d20d4fc3ed1 myself but [`cherrypick_cl.py`](https://android.googlesource.com/toolchain/llvm_android/+/refs/heads/master/cherrypick_cl.py) has not been updated for the new `PATCHES.json` scheme that was introduced by [aosp/1912396](https://android-review.googlesource.com/c/toolchain/llvm_android/+/1912396).

```
$ ./cherrypick_cl.py --create-cl --reason "Thumb2 kernel builds" --sha d7e089f2d6a5cd5f283a90ab29241d20d4fc3ed1 --verify-merge
Traceback (most recent call last):
  File "/home/nathan/cbl/src/aosp-llvm/toolchain/llvm_android/./cherrypick_cl.py", line 190, in <module>
    main()
  File "/home/nathan/cbl/src/aosp-llvm/toolchain/llvm_android/./cherrypick_cl.py", line 175, in main
    patch_list = PatchList.load_from_file()
  File "/home/nathan/cbl/src/aosp-llvm/toolchain/llvm_android/./cherrypick_cl.py", line 112, in load_from_file
    return PatchList(PatchItem.from_dict(d) for d in array)
  File "/home/nathan/cbl/src/aosp-llvm/toolchain/llvm_android/./cherrypick_cl.py", line 112, in <genexpr>
    return PatchList(PatchItem.from_dict(d) for d in array)
  File "/home/nathan/cbl/src/aosp-llvm/toolchain/llvm_android/./cherrypick_cl.py", line 71, in from_dict
    comment=d['comment'],
KeyError: 'comment'
```

I don't want to mess up the order of values in `PATCHES.json` (unless someone can tell me exactly where it should go).

cc @nickdesaulniers @stephenhines

**Comment by stephenhines** [comment]
There are a few things here that should probably be handled/tracked separately. 

- [ ] The versioning problem is somewhat expected. We use upstream TOT LLVM for our updates, and they bump the version number before the official release happens (usually it gets bumped right after the old release goes out). Thus Android LLVM 14.0.0 is really from before the 14.0.0 release from LLVM itself. I think if you're planning on using this toolchain for the kernel build, you need to detect that it's the Android version too, and handle that appropriately. @nathanchance @nickdesaulniers - how do you want to proceed here?
- [ ] We can add that patch into a subsequent toolchain respin (we have one going in this week, but this would require us to recreate the prebuilts that we put together and tested before the holidays). I'm checking with the rest of my team too to make sure that this is acceptable.
- [ ] We should fix up the `cherrypick_cl.py` script to work with the latest json updates. I'll go poke at this today.

**Comment by nathanchance** [comment]
> * [ ]  The versioning problem is somewhat expected. We use upstream TOT LLVM for our updates, and they bump the version number before the official release happens (usually it gets bumped right after the old release goes out). Thus Android LLVM 14.0.0 is really from before the 14.0.0 release from LLVM itself. I think if you're planning on using this toolchain for the kernel build, you need to detect that it's the Android version too, and handle that appropriately. @nathanchance @nickdesaulniers - how do you want to proceed here?

Yes, this is indeed expected and I am not really sure that there is a point to working around this deficiency, as I don't think there is a clean way to do this (do we downgrade AOSP's version to the last stable release?). Nick might have a different opinion on that though. We test AOSP LLVM builds against the upstream kernel in our CI to shake out issues like this so that when you guys do upgrades, the toolchain just keeps working for the kernel developers that actively use it (such as the Android Common Kernel and device kernel teams). We can easily patch this up within our CI until you guys respin with that change and I am not sure that there is anyone who uses AOSP LLVM to build 32-bit ARM kernels upstream. However, this deficiency could impact `kernel/common` in a different way, see below...

> * [ ]  We can add that patch into a subsequent toolchain respin (we have one going in this week, but this would require us to recreate the prebuilts that we put together and tested before the holidays). I'm checking with the rest of my team too to make sure that this is acceptable.

When would the next respin happen? This change is not mission critical IMHO BUT I know that there is some build breakage in linux-next with the current AOSP LLVM for a similar reason (missing relocations that are [supported with current ToT](https://reviews.llvm.org/D114172), see [this CI build](https://github.com/ClangBuiltLinux/continuous-integration2/runs/4703269749?check_suite_focus=true)), which I believe will impact the android-mainline branch of `kernel/common` in a few weeks when the patch making use of those relocations is merged with them gated on LLVM 14.0.0 or newer. I do not mind handling tracking down all of the patches, testing them, and pushing them to Gerrit for review once `cherrypick_cl.py` is fixed.

**Comment by nickdesaulniers** [comment]
> We should fix up the cherrypick_cl.py script to work with the latest json updates. I'll go poke at this today.

Yes.

> We can add that patch into a subsequent toolchain respin

If possible, that would be preferred.

**Comment by stephenhines** [comment]
Adding in @chih-hung as well.

**Comment by nickdesaulniers** [comment]
@chih-hung has https://android-review.googlesource.com/c/toolchain/llvm_android/+/1933984. Might we need a few more patches though here?
2caf85ad7ab83c441cb8e3550916d7028dfb8525
a19da876ab93d54ebc20aadd12820f74220d2f50
24772720c54500714e2d48b9109bb62d5867ad95
89453ed6f2059b5cec576fc41914def713fe38f7
9f95bc7dc18390199553cf2ea3bfcdc6a95717ef
73ee4e1cbd643028d63200f05199a128609aba5f
cd284b7ac0615afc6e0f1a30da2777e361de27a3

**Comment by nickdesaulniers** [comment]
> Might we need a few more patches though here?

I just built AOSP LLVM with https://android-review.googlesource.com/c/toolchain/llvm_android/+/1933984 then built mainline. Looks like that one patch is enough.

**Comment by nathanchance** [comment]
https://android.googlesource.com/toolchain/llvm_android/+/563b6d01b304f17cdfa2c38a1b7add4a3b05b54a

https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/81474db580d1be88de16fecf706dc1b5e74553f3

https://gitlab.com/Linaro/tuxmake/-/merge_requests/227

https://github.com/ClangBuiltLinux/continuous-integration2/pull/274
