### ISSUE TITLE
net/core/skbuff.o: unreachable instruction

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1563]
In `x86_64_defconfig` with tip of tree LLVM:

```
$ make -skj"$(nproc)" ARCH=x86_64 LLVM=1 defconfig net/core/skbuff.o
net/core/skbuff.o: warning: objtool: skb_copy()+0x12d: unreachable instruction
```

This was exposed by https://github.com/llvm/llvm-project/commit/a8c2ba105d47fd9e085ee6f2154005de9888609b (not sure I would say "caused by", given it is just flipping a switch).

```
$ git bisect log
# bad: [eb2cad8329b0526b6b4e9deaf7187530012a64f1] [DSE] Make isRemovable() for calls more robust (NFCI)
# good: [89ebd35daabee5bd5b6baab7230072316ee252b6] Fix flang tests after MLIR changes on the handling of declarative assembly
git bisect start 'eb2cad8329b0526b6b4e9deaf7187530012a64f1' '89ebd35daabee5bd5b6baab7230072316ee252b6'
# good: [312c51406da68aa512641d444cb7e369b2c4f1cf] [mlir][sparse] python driven test for SDDMM
git bisect good 312c51406da68aa512641d444cb7e369b2c4f1cf
# good: [11c2af04f27a293de974ffdfc8faefe247a4e722] Remove redundant check (NFC)
git bisect good 11c2af04f27a293de974ffdfc8faefe247a4e722
# bad: [fac18d7377b1f9dc161ed049ff7ee0b06521a364] [Bazel] Add LLVM_BUILD_* variables to llvm-config.h to mirror ec37e0bbafab75fa64f1ddb4cdeceb5400491ef8
git bisect bad fac18d7377b1f9dc161ed049ff7ee0b06521a364
# bad: [9fa15e0073b97dc2aa3482f297c13cb9509238e4] [CodeGen] Remove an unused MakeAddrLValue() overload (NFC)
git bisect bad 9fa15e0073b97dc2aa3482f297c13cb9509238e4
# good: [3ee44cb775ebe58e833c668c03b6fcf0a850e5c7] [PDLL] Add a `rewrite` statement to enable complex rewrites
git bisect good 3ee44cb775ebe58e833c668c03b6fcf0a850e5c7
# good: [c209b7e3d5b61262bfe868ae064758d047da4c15] [sanitizer] Update global_symbols.txt
git bisect good c209b7e3d5b61262bfe868ae064758d047da4c15
# good: [02fc8d5c9eb0703bb1863f22c2d27ff7a580f537] [ORC] Add custom object interface support to StaticLibaryDefinitionGenerator.
git bisect good 02fc8d5c9eb0703bb1863f22c2d27ff7a580f537
# bad: [cce93b339724a34928f0630fa8ed6b09b4ba753b] [MachineVerifier] Undef subreg operands do not require subranges
git bisect bad cce93b339724a34928f0630fa8ed6b09b4ba753b
# bad: [a8c2ba105d47fd9e085ee6f2154005de9888609b] [Inline] Disable deferred inlining
git bisect bad a8c2ba105d47fd9e085ee6f2154005de9888609b
# good: [f66803457ec7f88fa86376d9aef677dea107818c] [clang][deps] Squash caches for original and minimized files
git bisect good f66803457ec7f88fa86376d9aef677dea107818c
# first bad commit: [a8c2ba105d47fd9e085ee6f2154005de9888609b] [Inline] Disable deferred inlining
```

`cvise` spits out:

```
$ cat skbuff.i
struct sk_buff {
  int tail;
  int end;
} skb_panic_skb;
struct {
  char name[6];
} * skb_panic_skb_0_0_0_0;
int skb_panic_skb_2, skb_panic_skb_1, skb_copy___trans_tmp_1;
char skb_panic_skb_4, skb_panic_skb_3;
void _printk();
void skb_put();
void skb_panic() {
  _printk(skb_panic_skb, skb_panic_skb_3, skb_panic_skb_4, skb_panic_skb_1,
          skb_panic_skb_2 ? skb_panic_skb_0_0_0_0->name : "");
  asm("452"
      ":\n\t"
      ".pushsection .discard.unreachable\n\t"
      ".long "
      "452"
      "b - .\n\t"
      ".popsection\n\t"
      :
      : "i"(2));
  __builtin_unreachable();
}
static void skb_over_panic() { skb_panic(); }
void skb_copy() {
  skb_put();
  if (__builtin_expect(skb_copy___trans_tmp_1, 0)) {
    asm(".byte 15, 0x0b");
    __builtin_unreachable();
  }
}
void skb_put(struct sk_buff *skb) {
  if (__builtin_expect(skb->end, 0))
    skb_over_panic();
}

$ clang -O1 -c skbuff.i

$ ./objtool orc generate --no-fp --uaccess skbuff.o
skbuff.o: warning: objtool: skb_copy()+0x1b: unreachable instruction

$ clang -O1 -mllvm -inline-deferral -c skbuff.i

$ ./objtool orc generate --no-fp --uaccess skbuff.o
```

I do see a warning without optimizations as well, which I suppose is expected?

```
$ clang -c skbuff.i

$ ./objtool orc generate --no-fp --uaccess skbuff.o
skbuff.o: warning: objtool: skb_over_panic()+0x9: unreachable instruction
```

An LLVM IR reproducer:

```
$ cat reduced.ll

%struct.sk_buff = type { i32, i32 }
%struct.anon = type { [6 x i8] }

@skb_panic_skb = external global %struct.sk_buff
@skb_panic_skb_3 = external global i8
@skb_panic_skb_4 = external global i8
@skb_panic_skb_1 = external global i32
@skb_panic_skb_2 = external global i32
@skb_panic_skb_0_0_0_0 = external global %struct.anon*
@.str = external dso_local constant [1 x i8]
@skb_copy___trans_tmp_1 = external global i32

define void @skb_panic() {
entry:
  %0 = load i8, i8* @skb_panic_skb_3, align 1
  %conv = sext i8 %0 to i32
  %1 = load i8, i8* @skb_panic_skb_4, align 1
  %conv1 = sext i8 %1 to i32
  %2 = load i32, i32* @skb_panic_skb_1, align 4
  %3 = load i32, i32* @skb_panic_skb_2, align 4
  %tobool = icmp ne i32 %3, 0
  br i1 %tobool, label %cond.true, label %cond.false

cond.true:                                        ; preds = %entry
  %4 = load %struct.anon*, %struct.anon** @skb_panic_skb_0_0_0_0, align 8
  %name = getelementptr inbounds %struct.anon, %struct.anon* %4, i32 0, i32 0
  %arraydecay = getelementptr inbounds [6 x i8], [6 x i8]* %name, i64 0, i64 0
  br label %cond.end

cond.false:                                       ; preds = %entry
  br label %cond.end

cond.end:                                         ; preds = %cond.false, %cond.true
  %cond = phi i8* [ %arraydecay, %cond.true ], [ null, %cond.false ]
  %5 = load i64, i64* bitcast (%struct.sk_buff* @skb_panic_skb to i64*), align 4
  call void (i64, i32, i32, i32, i8*, ...) bitcast (void (...)* @_printk to void (i64, i32, i32, i32, i8*, ...)*)(i64 %5, i32 %conv, i32 %conv1, i32 %2, i8* %cond)
  call void asm sideeffect "452:\0A\09.pushsection .discard.unreachable\0A\09.long 452b - .\0A\09.popsection\0A\09", "i,~{dirflag},~{fpsr},~{flags}"(i32 0)
  unreachable
}

declare void @_printk(...)

define void @skb_copy(i32* %skb_copy___trans_tmp_1, i32 %0, i64 %conv, i64 %expval, i1 %tobool) {
entry:
  call void (...) bitcast (void (%struct.sk_buff*)* @skb_put to void (...)*)()
  %1 = load i32, i32* %skb_copy___trans_tmp_1, align 4
  %conv1 = sext i32 %0 to i64
  %expval2 = call i64 @llvm.expect.i64(i64 %conv, i64 0)
  %tobool3 = icmp ne i64 %conv, 0
  br i1 %tobool, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void asm sideeffect ".byte 15, 0x0b", "~{dirflag},~{fpsr},~{flags}"()
  unreachable

if.end:                                           ; preds = %entry
  ret void
}

define internal void @skb_over_panic() {
entry:
  call void @skb_panic()
  ret void
}

attributes #0 = { nofree nosync nounwind readnone willreturn }

$ opt -O1 -o skbuff.bc reduced.ll

$ llc -filetype=obj skbuff.bc

$ ./objtool orc generate --no-fp --uaccess skbuff.o
skbuff.o: warning: objtool: skb_copy()+0x1a: unreachable instruction

$ opt -O1 -inline-deferral -o skbuff.bc reduced.ll

$ llc -filetype=obj skbuff.bc

$ ./objtool orc generate --no-fp --uaccess skbuff.o
```

**Comment by nickdesaulniers** [comment]
I expect having functions unconditionally call `__builtin_unreachable` is going to be a problem.  Perhaps the test case was over-reduced? Or are these functions actually calling `__builtin_unreachable` unconditionally?

**Comment by nathanchance** [comment]
`skb_panic()` calls `BUG()`, which is defined in `arch/x86/include/asm/bug.h` as

```
#define BUG()							\
do {								\
	instrumentation_begin();				\
	_BUG_FLAGS(ASM_UD2, 0);					\
	unreachable();						\
} while (0)
```

and `unreachable` is defined in `include/linux/compiler.h` as

```
# define unreachable() do {		\
	annotate_unreachable();		\
	__builtin_unreachable();	\
} while (0)
```

so I don't think the test case was overreduced.

**Comment by nickdesaulniers** [comment]
I still see this even with https://lore.kernel.org/lkml/20220202205557.2260694-1-ndesaulniers@google.com/, so #1483 is a distinct issue.

In this case, we have 2 `BUG`s, with 2 `__builtin_unreachable`s. They get rotated to the end of the `MachineBasicBlock` by the `branch-folder` pass.

With the above patch applied, I get:
```
net/core/skbuff.o: warning: objtool: skb_copy()+0x12d: unreachable instruction
0000000000002f10 <skb_copy>:
$ python -c 'print(hex(0x2f10+0x12d))'
0x303d
```
```asm
    3030: 48 8b 54 24 18                movq    24(%rsp), %rdx
    3035: 48 89 df                      movq    %rbx, %rdi
    3038: e8 e3 10 00 00                callq   0x4120 <skb_over_panic>
    303d: e9 4a ff ff ff                jmp     0x2f8c <skb_copy+0x7c>
    3042: 0f 0b                         ud2
    3044: 0f 0b                         ud2
```
so objtool thinks that the `jmp` is unreachable. This object file contains no `.discard.unreachable` annotations (because of my patch), and IIUC none of the `.discard.reachable` annotations reference instructions within this function.

Tracing the control flow of the disassembly:
```asm
    2f86: 0f 87 a4 00 00 00             ja      0x3030 <skb_copy+0x120>
...
    3030: 48 8b 54 24 18                movq    24(%rsp), %rdx
    3035: 48 89 df                      movq    %rbx, %rdi
    3038: e8 e3 10 00 00                callq   0x4120 <skb_over_panic>
    303d: e9 4a ff ff ff                jmp     0x2f8c <skb_copy+0x7c>
```
but `skb_over_panic` ends in a bug.  I wonder if these need to be marked as noreturn?
```diff
diff --git a/net/core/skbuff.c b/net/core/skbuff.c
index 0118f0afaa4f..13b433d316be 100644
--- a/net/core/skbuff.c
+++ b/net/core/skbuff.c
@@ -103,8 +103,8 @@ EXPORT_SYMBOL(sysctl_max_skb_frags);
  *     Keep out of line to prevent kernel bloat.
  *     __builtin_return_address is not used because it is not always reliable.
  */
-static void skb_panic(struct sk_buff *skb, unsigned int sz, void *addr,
-                     const char msg[])
+static void __noreturn
+skb_panic(struct sk_buff *skb, unsigned int sz, void *addr, const char msg[])
 {
        pr_emerg("%s: text:%px len:%d put:%d head:%px data:%px tail:%#lx end:%#lx dev:%s\n",
                 msg, addr, skb->len, sz, skb->head, skb->data,
```
seems to help.

**Comment by nickdesaulniers** [comment]
with that, the above disassembly now looks like
```asm
    303f: e8 4c 88 00 00                callq   0xb890 <skb_panic>
    3044: 0f 0b                         ud2
    3046: 0f 0b                         ud2
```
I'm surprised we still `call` rather than `jmp`. 🤷

**Comment by nathanchance** [comment]
> ```diff
> diff --git a/net/core/skbuff.c b/net/core/skbuff.c
> index 0118f0afaa4f..13b433d316be 100644
> --- a/net/core/skbuff.c
> +++ b/net/core/skbuff.c
> @@ -103,8 +103,8 @@ EXPORT_SYMBOL(sysctl_max_skb_frags);
>   *     Keep out of line to prevent kernel bloat.
>   *     __builtin_return_address is not used because it is not always reliable.
>   */
> -static void skb_panic(struct sk_buff *skb, unsigned int sz, void *addr,
> -                     const char msg[])
> +static void __noreturn
> +skb_panic(struct sk_buff *skb, unsigned int sz, void *addr, const char msg[])
>  {
>         pr_emerg("%s: text:%px len:%d put:%d head:%px data:%px tail:%#lx end:%#lx dev:%s\n",
>                  msg, addr, skb->len, sz, skb->head, skb->data,
> ```
> 
> seems to help.

That doesn't seem unreasonable.

> with that, the above disassembly now looks like
> 
> ```assembly
>     303f: e8 4c 88 00 00                callq   0xb890 <skb_panic>
>     3044: 0f 0b                         ud2
>     3046: 0f 0b                         ud2
> ```
> 
> I'm surprised we still `call` rather than `jmp`. 🤷

I think this is https://github.com/llvm/llvm-project/issues/53118, which ultimately came from the patch that causes #1480.

**Comment by nickdesaulniers** [comment]
actually, I wonder if this could be a bug in LLVM's attributor.  It should be able to infer that a function that ends unconditionally with `__builtin_unreachable` is inherently `noreturn`.  This example does:
https://godbolt.org/z/nzzn5TT6r
But in the IR, for `@skb_over_panic`, it does not have the `noreturn` function attribute.

**Comment by nickdesaulniers** [comment]
PostOrderFunctionAttrsPass is what infers `noreturn` in the basic case.
`opt -passes=function-attrs /tmp/x.ll -S -o -`
If I use `llvm-extract` to rip out `@skb_over_panic` and run `function-attrs` on that, it's able to determine that `@skb_over_panic` is noreturn...I wonder why not when it's with the rest of the TU?

**Comment by nickdesaulniers** [comment]
EDIT: the below was likely over-reduced. Probably don't want to drop the __builtin_unreachable from skb_over_panic.

cvise says:
```c
skb_panic_skb, skb_panic_skb_0_0_0_0, skb_panic_skb_2, skb_panic_skb_1,
    skb_panic_skb_4, skb_panic_skb_3, skb_put_skb_2;
static skb_over_panic() {
  _printk(skb_panic_skb, skb_panic_skb_3, skb_panic_skb_4, skb_panic_skb_1,
          skb_panic_skb_2, skb_panic_skb_0_0_0_0 ?: "");
}
skb_put() {
  if (__builtin_expect(skb_put_skb_2, 0)) skb_over_panic();
}
```
is enough to confuse `function-attrs`

**Comment by nathanchance** [comment]
The fact that both my initial reproducer and yours have `__builtin_expect()` (which the kernel uses as `likely` and `unlikely`) is interesting... Removing the `unlikely` from `skb_put()` and `skb_push()` hides the warning:

```diff
diff --git a/net/core/skbuff.c b/net/core/skbuff.c
index 0118f0afaa4f..181546800f4a 100644
--- a/net/core/skbuff.c
+++ b/net/core/skbuff.c
@@ -1984,7 +1984,7 @@ void *skb_put(struct sk_buff *skb, unsigned int len)
        SKB_LINEAR_ASSERT(skb);
        skb->tail += len;
        skb->len  += len;
-       if (unlikely(skb->tail > skb->end))
+       if (skb->tail > skb->end)
                skb_over_panic(skb, len, __builtin_return_address(0));
        return tmp;
 }
@@ -2003,7 +2003,7 @@ void *skb_push(struct sk_buff *skb, unsigned int len)
 {
        skb->data -= len;
        skb->len  += len;
-       if (unlikely(skb->data < skb->head))
+       if (skb->data < skb->head)
                skb_under_panic(skb, len, __builtin_return_address(0));
        return skb->data;
 }
```

**Comment by nickdesaulniers** [comment]
oh, I wonder if all call sites gets attributed as cold, and thus the callee is not optimized.

**Comment by nickdesaulniers** [comment]
```c
skb_panic_skb, skb_panic_skb_0_0_0_0, skb_panic_skb_2, skb_panic_skb_1,
    skb_panic_skb_4, skb_panic_skb_3, skb_put_skb_2;
static skb_panic() {
  _printk(skb_panic_skb, skb_panic_skb_3, skb_panic_skb_4, skb_panic_skb_1,
          skb_panic_skb_2, skb_panic_skb_0_0_0_0 ?: "");
  __builtin_unreachable();
}
static skb_over_panic() { skb_panic(); }
skb_put() {
  if (__builtin_expect(skb_put_skb_2, 0)) skb_over_panic();
}
```
via
```sh
clang -O2 skbuff.i -w -emit-llvm -S -o temp.ll && \
  llvm-extract --func=skb_over_panic temp.ll -o temp2.bc && \
  llvm-dis temp2.bc -o - | grep unreachable && \
  clang -O2 skbuff.i -w -emit-llvm -S -o - | grep "define internal fastcc void @skb_over_panic" | grep "#0" && \
  clang -O2 skbuff.i -w -emit-llvm -S -o - | grep "attributes #0" | grep -v noreturn -q
```

**Comment by nickdesaulniers** [comment]
@jdoerfert pointed to this [TODO](https://github.com/llvm/llvm-project/blob/19aa2db023c0128913da223d4fb02c474541ee22/llvm/lib/Transforms/IPO/FunctionAttrs.cpp#L1626).

**Comment by jdoerfert** [comment]
> @jdoerfert pointed to this [TODO](https://github.com/llvm/llvm-project/blob/19aa2db023c0128913da223d4fb02c474541ee22/llvm/lib/Transforms/IPO/FunctionAttrs.cpp#L1626).

FWIW, here is the [minimal reproducer](https://godbolt.org/z/fosKGnP8P). My guess is that the issue originates with the inliner not cleaning up the resulting IR. So the rest of the code that was after the call is not removed even though it's unreachable. Now that I think about it, one could reasonably look for that situation there and simply delete that block. And here is confirmation: https://godbolt.org/z/chbfxcYcP

Edit: Remove the `InlinedMustTailCalls &&` [here](https://github.com/llvm/llvm-project/blob/19aa2db023c0128913da223d4fb02c474541ee22/llvm/lib/Transforms/Utils/InlineFunction.cpp#L2621) and you get what you want. I have not tested if this impacts tests etc. I doubt it will have a negative impact though. Not sure why https://reviews.llvm.org/D3491 did only erase the block for the must tail call case, maybe @rnk can comment?

**Comment by nickdesaulniers** [comment]
> Edit: Remove the InlinedMustTailCalls && [here](https://github.com/llvm/llvm-project/blob/19aa2db023c0128913da223d4fb02c474541ee22/llvm/lib/Transforms/Utils/InlineFunction.cpp#L2621) and you get what you want.

Yes. We then hit https://github.com/llvm/llvm-project/issues/53118 for [my test case above](https://github.com/ClangBuiltLinux/linux/issues/1563#issuecomment-1028529265). (i.e. for codegen, we emit `callq   _printk` when I expect `jmpq   _printk`.

https://github.com/llvm/llvm-project/issues/53118 will fix the overall issue regardless, but @jdoerfert 's suggested modification to `llvm::InlineFunction` is possibly also worthwhile.

**Comment by nickdesaulniers** [comment]
(via irc):
> @jdoerfert : if you test and it doesn't work, can u get the IR before function-attrs? 

```llvm
  %4 = load i32, i32* @skb_panic_skb_2, align 4, !tbaa !3
  %5 = load i32, i32* @skb_panic_skb_0_0_0_0, align 4, !tbaa !3
  %tobool = icmp ne i32 %5, 0
  br i1 %tobool, label %cond.true, label %cond.false
...skipping...
*** IR Dump Before PostOrderFunctionAttrsPass on (skb_panic) ***
; ModuleID = 'skbuff.i'
source_filename = "skbuff.i"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@skb_put_skb_2 = dso_local local_unnamed_addr global i32 0, align 4
@skb_panic_skb = dso_local local_unnamed_addr global i32 0, align 4
@skb_panic_skb_0_0_0_0 = dso_local local_unnamed_addr global i32 0, align 4
@skb_panic_skb_2 = dso_local local_unnamed_addr global i32 0, align 4
@skb_panic_skb_1 = dso_local local_unnamed_addr global i32 0, align 4
@skb_panic_skb_4 = dso_local local_unnamed_addr global i32 0, align 4
@skb_panic_skb_3 = dso_local local_unnamed_addr global i32 0, align 4
@.str = private unnamed_addr constant [1 x i8] zeroinitializer, align 1

; Function Attrs: nounwind uwtable
define dso_local i32 @skb_put() local_unnamed_addr #0 {
entry:
  %0 = load i32, i32* @skb_put_skb_2, align 4, !tbaa !3
  %tobool.not = icmp eq i32 %0, 0
  br i1 %tobool.not, label %if.end, label %if.then, !prof !7

if.then:                                          ; preds = %entry
  call fastcc void @skb_over_panic()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret i32 undef
}

; Function Attrs: nounwind uwtable
define internal fastcc void @skb_over_panic() unnamed_addr #0 {
entry:
  call fastcc void @skb_panic()
  ret void
}

; Function Attrs: nounwind uwtable
define internal fastcc void @skb_panic() unnamed_addr #0 {
entry:
  %0 = load i32, i32* @skb_panic_skb, align 4, !tbaa !3
  %1 = load i32, i32* @skb_panic_skb_3, align 4, !tbaa !3
  %2 = load i32, i32* @skb_panic_skb_4, align 4, !tbaa !3
  %3 = load i32, i32* @skb_panic_skb_1, align 4, !tbaa !3
  %4 = load i32, i32* @skb_panic_skb_2, align 4, !tbaa !3
  %5 = load i32, i32* @skb_panic_skb_0_0_0_0, align 4, !tbaa !3
  %tobool.not = icmp eq i32 %5, 0
  %conv = sext i32 %5 to i64
  %6 = inttoptr i64 %conv to i8*
  %cond = select i1 %tobool.not, i8* getelementptr inbounds ([1 x i8], [1 x i8]* @.str, i64 0, i64 0), i8* %6
  %call = call i32 (i32, i32, i32, i32, i32, i8*, ...) bitcast (i32 (...)* @_printk to i32 (i32, i32, i32, i32, i32, i8*, ...)*)(i32 noundef %0, i32 noundef %1, i32 noundef %2, i32 noundef %3, i32 noundef %4, i8* noundef %cond) #2
  unreachable
}
declare dso_local i32 @_printk(...) local_unnamed_addr #1

attributes #0 = { nounwind uwtable "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { "frame-pointer"="none" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #2 = { nounwind }

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"uwtable", i32 1}
!2 = !{!"Nick Desaulniers clang version 15.0.0 (git@github.com:llvm/llvm-project.git 66dea85b360db2309a516e223335402ef2a7deae)"}
!3 = !{!4, !4, i64 0}
!4 = !{!"int", !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C/C++ TBAA"}
!7 = !{!"branch_weights", i32 2000, i32 1}
```
afterwards `skb_panic` is attributed `noreturn`.

**Comment by rnk** [comment]
Regarding https://reviews.llvm.org/D3491, I think I made that logic specific to inlining musttail calls because in that case, AfterCallBB must not have any successors, it will only have a bitcast and a return, so it's sufficient to just delete a single block.

If you want to clean up all unreachable blocks after inlining a call site without any returns (throw or abort only), you need to do a full DFS to be sure you've removed all unreachable code in case there are loops.

The inliner expects to run concurrently with the pass simplification pipeline, which will remove unreachable code. Passes in this pipeline should tolerate unreachable blocks or remove them if they don't.

**Comment by jdoerfert** [comment]
> Regarding https://reviews.llvm.org/D3491, I think I made that logic specific to inlining musttail calls because in that case, AfterCallBB must not have any successors, it will only have a bitcast and a return, so it's sufficient to just delete a single block.

The key is, no calls are in the remainder of the block so deleting it will not invalidate call inst pointers in the Inliner. If the inliner would be tolerant to that (e.g., use WeakVH) we could delete those blocks also for non-must tails. Dead code might still exist but not the trivial dead code former by the remainder of the block in which the noreturn call site was located.

Apparently this gets the noreturn back but there is still not enough to fix the real problem here. One can keep this in mind though as a small inliner improvement.

**Comment by nickdesaulniers** [comment]
I'm going to focus on https://github.com/llvm/llvm-project/issues/53118; as noted, there's many related regressions related to that change. They will all need to be solved separately to close out the issue, I suspect.

**Comment by nickdesaulniers** [comment]
Copying a comment from @jpoimboe from IRC:

> jpoimboe> ndesaulniers: I agree with [that github comment](https://github.com/llvm/llvm-project/issues/53118#issuecomment-1033185276), a tail call to noreturn will still remove the caller from the backtrace, even on ORC

I'm not sure then the best way to proceed.  Either we want an additional frame in the trace of such a call to `skb_panic` or we don't care.  I don't really see any way forward here other than one of the following:
1. [fix llvm generally](https://github.com/llvm/llvm-project/issues/53118)
2. [fix this case locally](https://github.com/ClangBuiltLinux/linux/issues/1563#issuecomment-1028481807)
3. disable objtool from warning in such cases

**Comment by nickdesaulniers** [comment]
Looking back at [this comment](https://github.com/ClangBuiltLinux/linux/issues/1563#issuecomment-1028481807), it's the `jmp` that gets placed after the noreturn `call`. If we properly carry the `noreturn` ir fn attr, then we shouldn't place the `jmp` (or wind up with such control flow I suspect).

**Comment by nickdesaulniers** [comment]
submitted: https://reviews.llvm.org/D119571

**Comment by nickdesaulniers** [comment]
I've [requested](https://github.com/llvm/llvm-project/issues/53834) a backport for the fix into clang-14.

**Comment by nathanchance** [comment]
Merged into `release/14.x`: https://github.com/llvm/llvm-project/commit/7d8e83dab37af0516bd9bbaafe818c29fbab7062
