### ISSUE TITLE
make tinyconfig and turning on LTO (HAS_LTO_CLANG depends appears to have bug)

### ISSUE THREAD

**Issue by 2themaxx** [ClangBuiltLinux/linux#1568]
I'm somewhat new to kernel development, compiling the kernel, etc. however I have done some basic things. I'm trying to find the minimum requirements to compile a tinyconfig with clang and LTO turned on to benchmark the potentially smallest linux kernel we can get. The platform is x86 (Ubuntu 18.04, X86-64), I'm running Clang-12 (installed from automation script on llvm website, softlinks manually created based on errors encountered when compiling kernel with "make LLVM=1 LLVM_IAS=1 defconfig" followed by "make LLVM=1 LLVM_IAS=1"), Kernel code is 5.16.0 downloaded from tarball off of kernel.org. 

Kernel compiles successfully with:
make LLVM=1 LLVM_IAS=1 defconfig
make LLVM=1 LLVM_IAS=1

Can't seem to select LTO with:
make LLVM=1 LLVM_IAS=1 tinyconfig
make LLVM=1 LLVM_IAS=1 menuconfig

but cannot select LTO_CLANG_FULL or LTO_CLANG_THIN due to HAS_LTO_CLANG depends:

 Symbol: HAS_LTO_CLANG [=n]                                                                                      │
  │ Type  : bool                                                                                                    │
  │ Defined at arch/Kconfig:649
  │   Depends on: CC_IS_CLANG [=y] && CLANG_VERSION [=120001]>=110000 && LD_IS_LLD [=y] && AS_IS_LLVM [=y] && n && y && ARCH_SUPPORTS_LTO_CLANG [=y] && !FTRACE_MCOUNT_USE_RECORDMCOUNT [=n] && (!KASAN [=n] || KASAN_HW_TAGS [=n]) && !GCOV_KERNEL [=n]

Am I missing something? It doesn't look like something is turned on but I can't chase down what it is with the "n" and "y" in between AS_IS_LLVM and AARCH_SUPPORTS_LTO_CLANG. Is there a good way to chase down what else needs to be turned on? Or, is this a bug in the configuration file?

**Comment by nathanchance** [comment]
The `&& n && y` in the `Depends on` correspond to:

```
	depends on $(success,$(NM) --help | head -n 1 | grep -qi llvm)
	depends on $(success,$(AR) --help | head -n 1 | grep -qi llvm)
```

in the `HAS_LTO_CLANG` entry in `init/Kconfig`.

> softlinks manually created based on errors encountered when compiling kernel with "make LLVM=1 LLVM_IAS=1 defconfig" followed by "make LLVM=1 LLVM_IAS=1"

What errors were those? It is likely that your softlinks are messed up.

The apt.llvm.org Debian packages install to `/usr/lib/llvm-#`, so you can add that path to your make invocation like:

```
$ PATH=/usr/lib/llvm-12/bin:$PATH make LLVM=1 LLVM_IAS=1 ...
```

to avoid having to muck around with symlinks and such.

**Comment by 2themaxx** [comment]
Sorry, I thought I'd written about this and closed the issue.  Yes, it was the llvm-nm softlink. I'm running Ubuntu 18.04
