### ISSUE TITLE
Clang built kernel with DKMS

### ISSUE THREAD

**Issue by FCLC** [ClangBuiltLinux/linux#1572]
Hi ladies and gents; 

I've been running kernel 5.16.2 built with Clang 13.0 for ~ a week now with no apparent issues until now.

uname -a: ```Linux 5.16.2 #3 SMP Thu Jan 20 21:54:13 EST 2022 x86_64 GNU/Linux ```

It seems issues with DKMS continue to rear their ugly head, this time with V4L2 loopback. 

Specifically in the domain of 
```
DKMS make.log for v4l2loopback-0.12.5 for kernel 5.16.2 (x86_64)
Wed 26 Jan 2022 12:48:54 PM EST
Building v4l2-loopback driver...
make -C /lib/modules/5.16.2/build M=/var/lib/dkms/v4l2loopback/0.12.5/build modules
make[1]: Entering directory '/home/felix/kernel/5.16/linux-5.16.2'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: Debian clang version 13.0.1-+rc1-1~exp4
  You are using:           gcc (Debian 11.2.0-14) 11.2.0
  CC [M]  /var/lib/dkms/v4l2loopback/0.12.5/build/v4l2loopback.o
gcc: error: unrecognized argument to ‘-fsanitize=’ option: ‘array-bounds’
gcc: error: unrecognized command-line option ‘-Qunused-arguments’
gcc: error: unrecognized command-line option ‘-mretpoline-external-thunk’
gcc: error: unrecognized command-line option ‘-mno-global-merge’
make[2]: *** [scripts/Makefile.build:287: /var/lib/dkms/v4l2loopback/0.12.5/build/v4l2loopback.o] Error 1
make[1]: *** [Makefile:1846: /var/lib/dkms/v4l2loopback/0.12.5/build] Error 2
make[1]: Leaving directory '/home/felix/kernel/5.16/linux-5.16.2'
make: *** [Makefile:43: v4l2loopback.ko] Error 2
```

where the relevant line is the compiler mismatch. 

It looked like this would have been solved in https://github.com/dell/dkms/pull/169 but that does not seem to be the case?

Think @nickdesaulniers might be the guy to ask on this one?

**Comment by nathanchance** [comment]
It looks like Nick's change was released in 3.0.2, what version of `dkms` is being used here?

**Comment by FCLC** [comment]
Using the latest from Debian SID, looks like they haven't pushed past dkms-2.8.7 as of yet. :thinking: 

So for now might be to send a request for Debian experimental/upstream to consider 3.0.3, which is considered a stable release? 

May also be worth the addition to the read me or something of the sort with how popular DKMS is these days

**Comment by nickdesaulniers** [comment]
> May also be worth the addition to the read me

Probably; another sharp edge is that dkms has a explicit PATH list it checks for clang; folks with clang binaries outside of those few paths will also get spooky bugs.

We can add something to our wiki easily enough. Or did you mean the DKMS readme?

**Comment by FCLC** [comment]
> Probably; another sharp edge is that dkms has a explicit PATH list it checks for clang; folks with clang binaries outside of those few paths will also get spooky bugs. 

Oof, with the release having come after October I'd been hoping we were in the clear :sweat_smile: 

Ideally those folks would also soft link to typical locations just in case?

Otherwise I don't see a world where we store explicit path to the original compiler used for the installed kernel in .config or another relevant file. ~~(Let alone store the actual binary itself)~~

> We can add something to our wiki easily enough. Or did you mean the DKMS readme?

The Clang built Linux readme/Wiki should help for search ability. As of now Duck duck go doesn't find many if any relevant results without a fair bit of keyword tinkering.

As for the DKMS readme, not certain if that's something that would belong on main page. Maybe something in the Man or help files? 

In the mean time I've reached out to the Debian DKMS maintainers about bumping sid to 3.0.2+

**Comment by nickdesaulniers** [comment]
> Ideally those folks would also soft link to typical locations just in case?

That's what I do.

> The Clang built Linux readme/Wiki should help for search ability.

SGTM

**Comment by nickdesaulniers** [comment]
I wrote [this](https://github.com/ClangBuiltLinux/linux/wiki/DKMS-and-clang) up quickly. Please help revise. In particular, if you added the error messages you observed, that would be very helpful from an internet search perspective!

**Comment by FCLC** [comment]
> I wrote [this](https://github.com/ClangBuiltLinux/linux/wiki/DKMS-and-clang) up quickly. Please help revise. In particular, if you added the error messages you observed, that would be very helpful from an internet search perspective!

See https://github.com/ClangBuiltLinux/linux/wiki/Clang-Linux-kernels-and-DKMS. 

Feel free to edit into whatever the current project wiki/format standards are!
