### ISSUE TITLE
which: no ...-gcc in (...) when cleaning

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1573]
Commit [cebdb7374577](https://git.kernel.org/linus/cebdb7374577ac6e14afb11311af8c2c44a259fa) ("tools: Help cross-building with clang") introduced an annoying warning when running `make clean` with `CROSS_COMPILE` set:

```
$ make -skj"$(nproc)" ARCH=powerpc CROSS_COMPILE=powerpc-linux-gnu- LLVM=1 LLVM_IAS=0 clean
which: no powerpc-linux-gnu-gcc in (...)
```

**Comment by nathanchance** [comment]
Reported upstream: https://lore.kernel.org/r/YfSUAPnZX%2FwP8U+p@archlinux-ax161/

**Comment by nathanchance** [comment]
https://lore.kernel.org/r/20220201093119.1713207-1-jean-philippe@linaro.org/

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf.git/commit/?id=b7892f7d5cb2

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/b7892f7d5cb2b8187c603dd8ea3a7c44059ccfc2
