### ISSUE TITLE
invalid string offset 1 >= 1 for section `.strtab'

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1580]
android4.14 branches are failing for [aarch64](https://github.com/ClangBuiltLinux/continuous-integration2/runs/5086951566?check_suite_focus=true) and [x86](https://github.com/ClangBuiltLinux/continuous-integration2/runs/5086951398?check_suite_focus=true)

```
aarch64-linux-gnu-ar: arch/arm64/lib/lib-ksyms.o: invalid string offset 1 >= 1 for section `.strtab'
aarch64-linux-gnu-ar: arch/arm64/lib/lib-ksyms.o: invalid string offset 1 >= 1 for section `.strtab'
aarch64-linux-gnu-ar: lib/lib-ksyms.o: invalid string offset 1 >= 1 for section `.strtab'
aarch64-linux-gnu-ar: lib/lib-ksyms.o: invalid string offset 1 >= 1 for section `.strtab'
Error: ld.lld: error: built-in.o(arch/arm64/lib/lib-ksyms.o): invalid symbol name offset
```

**Comment by nathanchance** [comment]
https://github.com/ClangBuiltLinux/linux/issues/1578#issuecomment-1030523755?

**Comment by nickdesaulniers** [comment]
sure, but this regressed in LLD, I suspect. It would be good to know _why_ the generated objects are invalid, rather than simply dropping out of tree patches.

**Comment by nathanchance** [comment]
I have adding some further analysis to #1578. Closing this one as a duplicate issue.
