### ISSUE TITLE
Enable -fzero-call-used-regs for ARM architectures

### ISSUE THREAD

**Issue by isanbard** [ClangBuiltLinux/linux#1586]
Now that we have `-fzero-call-used-regs` for x86, we need to enable it for ARM.

**Comment by nathanchance** [comment]
AArch64: https://reviews.llvm.org/D124836

**Comment by nickdesaulniers** [comment]
AArch64: https://reviews.llvm.org/rG6e00a34cdb49ba1d4b72ec274e52260da9c52380

Leaving open for 32b ARM.
