### ISSUE TITLE
"ld.lld: error: section type mismatch for .plt" after LLVM commit 66f8ac8d3604d67599734c3fd272032e9448aca2

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1597]
https://github.com/llvm/llvm-project/commit/66f8ac8d3604d67599734c3fd272032e9448aca2

As I [reported on Phabricator](https://reviews.llvm.org/D118840), linking modules with `ld.lld` when `CONFIG_ARM64_MODULE_PLTS` is enabled is now broken:

```
$ make -skj"$(nproc)" ARCH=arm64 LLVM=1 mrproper defconfig all
...
ld.lld: error: section type mismatch for .plt
>>> <internal>:(.plt): SHT_PROGBITS
>>> output section .plt: SHT_NOBITS
...
```

The following change was suggested on Phabricator, which builds, but I am not sure what the runtime implications of this are.

```diff
diff --git a/arch/arm64/include/asm/module.lds.h b/arch/arm64/include/asm/module.lds.h
index a11ccadd47d2..2c9a5219aa33 100644
--- a/arch/arm64/include/asm/module.lds.h
+++ b/arch/arm64/include/asm/module.lds.h
@@ -1,6 +1,6 @@
 SECTIONS {
 #ifdef CONFIG_ARM64_MODULE_PLTS
-       .plt 0 (NOLOAD) : { BYTE(0) }
+       .plt 0 : { BYTE(0) }
        .init.plt 0 (NOLOAD) : { BYTE(0) }
        .text.ftrace_trampoline 0 (NOLOAD) : { BYTE(0) }
 #endif
```

**Comment by nathanchance** [comment]
Fangrui sent https://lore.kernel.org/r/20220218081209.354383-1-maskray@google.com/.

I requested the removal of this error until the kernel can be fully patched so that groups like LKFT and 0day do not get bitten by this: https://reviews.llvm.org/D118840#3332118

**Comment by nickdesaulniers** [comment]
@MaskRay also sent https://lore.kernel.org/linux-riscv/20220218082611.396353-1-maskray@google.com/ for riscv.

**Comment by MaskRay** [comment]
@nathanchance Will a warning be fine? The link still proceeds.

**Comment by nathanchance** [comment]
> @nathanchance Will a warning be fine? The link still proceeds.

Yes, I think a warning would be fine. Groups might still notice but I think it is better than outright breaking the build and we will still push forward with your patch or @ardbiesheuvel's suggestion to get it cleaned up.

**Comment by MaskRay** [comment]
> > @nathanchance Will a warning be fine? The link still proceeds.
> 
> Yes, I think a warning would be fine. Groups might still notice but I think it is better than outright breaking the build and we will still push forward with your patch or @ardbiesheuvel's suggestion to get it cleaned up.

Thanks! llvm/llvm-project@cb0a4bb5be10636aaec3ecb56ed586dee3eb0b9e changed `(NOLOAD)` mismatch to a warning.

**Comment by nathanchance** [comment]
> Thanks! [llvm/llvm-project@cb0a4bb](https://github.com/llvm/llvm-project/commit/cb0a4bb5be10636aaec3ecb56ed586dee3eb0b9e) changed `(NOLOAD)` mismatch to a warning.

Thank you a lot for the compromise and sending the fixes! We'll make sure they get picked up and backported, hopefully in a timely manner.

**Comment by nathanchance** [comment]
arm64 patch has been accepted: https://git.kernel.org/arm64/c/4013e26670c590944abdab56c4fa797527b74325

**Comment by nickdesaulniers** [comment]
commit 4013e26670c5 ("arm64: module: remove (NOLOAD) from linker script")
is now in 5.18-rc1 (when rc1 gets tagged).

So just waiting on the riscv change to hit mainline before closing (though maybe we'll need backports).

**Comment by nickdesaulniers** [comment]
riscv accepted: https://git.kernel.org/pub/scm/linux/kernel/git/palmer/linux.git/commit/?id=60210a3d86dc57ce4a76a366e7841dda746a33f7

**Comment by nathanchance** [comment]
Both arm64 and RISC-V patches are in 5.18-rc1:

https://git.kernel.org/linus/4013e26670c590944abdab56c4fa797527b74325
https://git.kernel.org/linus/60210a3d86dc57ce4a76a366e7841dda746a33f7

The RISC-V change is currently queued for the next round of stable releases of 5.10 and newer, the arm64 one is queued up for 5.15 and newer.

I have sent a backport for all relevant stable versions:

https://lore.kernel.org/r/Ykytcg+xI%2FMRSLue@dev-arch.thelio-3990X/
