### ISSUE TITLE
-Wunused-but-set-variable in fs/btrfs/block-group.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1614]
```
fs/btrfs/block-group.c:2949:6: error: variable 'num_started' set but not used [-Werror,-Wunused-but-set-variable]
        int num_started = 0;
            ^
fs/btrfs/block-group.c:3116:6: error: variable 'num_started' set but not used [-Werror,-Wunused-but-set-variable]
        int num_started = 0;
            ^
2 errors generated.
```

Patch submitted: https://lore.kernel.org/r/20220324153644.4079376-1-nathan@kernel.org/

**Comment by nickdesaulniers** [comment]
Sounds like this was accepted and should appear on this branch once pushed: https://github.com/kdave/btrfs-devel/commits/misc-next

**Comment by nathanchance** [comment]
Now in -next: https://git.kernel.org/kdave/c/f737c6257f113595fccf51370f4fe23818d95d86

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/6d4a6b515c39f1f8763093e0f828959b2fbc2f45

This should go back to stable automatically.
