### ISSUE TITLE
I am facing CFI failure issues because of xmit_one()

### ISSUE THREAD

**Issue by SHREEDHARBg** [ClangBuiltLinux/linux#1622]
Here I am facing cfi failure because of xmit_one function please any one help me out for this one

Below I attached dmesg.

[    5.563902] CFI failure (target: tcf_chain_put_by_act.cfi_jt+0x4/0x8):
[    5.563915] WARNING: CPU: 2 PID: 0 at kernel/cfi.c:30 __cfi_check_fail+0x4c/0x54
[    5.563918] Modules linked in: nmtp_plugin microchip_hub thfsplus(O) tntfs(PO) texfat(PO) ecdh_generic ecc dmatest ccm arc4
[    5.563931] (AND OS)CPU: 2 PID: 0 Comm: swapper/2 Tainted: P        W  O      5.4.61-android11-2-gd4a626af17cf-ab647 #1
[    5.563934] Hardware name: Samsung ExynosAuto9 SADK Android IVI VM (DT)
[    5.563938] pstate: 60400005 (nZCv daif +PAN -UAO)
[    5.563942] pc : __cfi_check_fail+0x4c/0x54
[    5.563945] lr : __cfi_check_fail+0x4c/0x54
[    5.563948] sp : ffffffc010043760
[    5.563950] x29: ffffffc010043760 x28: 0000003375e084d0 
[    5.563953] x27: ffffffc011d16018 x26: 0000000000000000 
[    5.563956] x25: ffffffc011d57158 
[    5.563960] type=1400 audit(1546344005.747:470): avc: denied { open } for comm="trc-logcat-main" path="/proc/878/cmdline" dev="proc" ino=28868 scontext=u:r:traceserver:s0 tcontext=u:r:esoinputservd:s0 tclass=file permissive=1
[    5.563962] x24: ffffff8b499ae180 
[    5.563966] x23: ffffffc010386000 x22: 0000000000000001 
[    5.563968] x21: fb5758f90df1e592 x20: ffffffc012049500 
[    5.563971] x19: ffffffc011108f94 x18: ffffffc0100350b0 
[    5.563974] x17: 0000000000000041 x16: ffffffc0110ea020 
[    5.563976] x15: 0000000000000004 x14: 0000000000000064 
[    5.563979] x13: 000000000007a87c x12: 0000000000000000 
[    5.563981] x11: 0000000000000001 x10: ffffffc011d16018 
[    5.563984] x9 : 236c34d494744800 x8 : 236c34d494744800 
[    5.563987] x7 : 632e7463615f7962 x6 : ffffffc012865177 
[    5.563990] x5 : ff00000000000000 x4 : 000000000000000c 
[    5.563992] x3 : 0a3a293878302f34 x2 : 0000000000000007 
[    5.563995] x1 : 0000000000000006 x0 : 000000000000003a 
[    5.563998] Call trace(AND OS):
[    5.564001] __cfi_check_fail+0x4c/0x54
[    5.564006] __cfi_check+0x5ed80/0x663f0
[    5.564010] xmit_one+0x2d8/0x2dc
[    5.564013] dev_hard_start_xmit+0x58/0xa4
[    5.564017] sch_direct_xmit+0xd4/0x314

**Comment by nathanchance** [comment]
See Nick's response in #1620.
