### ISSUE TITLE
arm64: error: unknown register name 'x16' in asm

### ISSUE THREAD

**Issue by michaelopdenacker** [ClangBuiltLinux/linux#1632]
Hello,
FYI, I got this error while trying to compile Linux 5.18-rc6 with Clang 14 on Ubuntu 22.04.
export ARCH=arm64
export LLVM=1
make Image.gz

---
./arch/arm64/include/asm/archrandom.h:156:3: error: unknown register name 'x16' in asm
./include/linux/arm-smccc.h:558:4: note: expanded from macro 'arm_smccc_1_1_invoke'
                        __fail_smccc_1_1(__VA_ARGS__);                  \
                        ^
./include/linux/arm-smccc.h:528:13: note: expanded from macro '__fail_smccc_1_1'
                asm ("" : __constraints(__count_args(__VA_ARGS__)));    \
                          ^
./include/linux/arm-smccc.h:466:30: note: expanded from macro '__constraints'
#define __constraints(count)    ___constraints(count)
                                ^
./include/linux/arm-smccc.h:465:4: note: expanded from macro '___constraints'
        : smccc_sve_clobbers "memory"
          ^
./include/linux/arm-smccc.h:389:28: note: expanded from macro 'smccc_sve_clobbers'
#define smccc_sve_clobbers "x16", "x30", "cc",
                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
23 warnings and 20 errors generated.
make[1]: *** [scripts/Makefile.build:120: arch/arm64/kernel/asm-offsets.s] Error 1
make: *** [Makefile:1194: prepare0] Error 2

**Comment by michaelopdenacker** [comment]
Eventually, I don't have this error anymore.
If you have something similar, double check your environment variables
Closing this bug.

**Comment by nathanchance** [comment]
Just a tip, some variables don't work when exported before running `make`. I always recommend specifying your variables as arguments to `make` to avoid issues like this:

```
$ make ARCH=arm64 LLVM=1 Image.gz
```

**Comment by michaelopdenacker** [comment]
Hey, thanks for the tip!
