### ISSUE TITLE
__mulodi4 in lib/overflow_kunit.o

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1636]
Initial reported by CI: https://github.com/ClangBuiltLinux/continuous-integration2/runs/6426504602?check_suite_focus=true

For versions of clang that do not have https://github.com/llvm/llvm-project/commit/5c91b98c5d45243352bf10262454bcac77cd3fed (i.e. older than clang 14.0.0), `ARCH=arm allmodconfig` breaks:

```
Error: ld.lld: error: undefined symbol: __mulodi4
>>> referenced by overflow_kunit.c
>>>               overflow_kunit.o:(s64_overflow_test) in archive lib/built-in.a
```

Caused by https://git.kernel.org/kees/c/3b0492c33634ac2cc9ff3cb32e20205c4f8977c1. This problem has come up before: #1438.

cc @kees

**Comment by nickdesaulniers** [comment]
__mulodi4 is a 64b mutliply with overflow check helper that only exists in compiler-rt and not libgcc.

I thought I removed the cases of this from LLVM, but as I have to do so in a backend specific manner, I may have missed arm32.

**Comment by nathanchance** [comment]
> I thought I removed the cases of this from LLVM

You did, hence the comment:

> For versions of clang that do not have [llvm/llvm-project@5c91b98](https://github.com/llvm/llvm-project/commit/5c91b98c5d45243352bf10262454bcac77cd3fed) (i.e. older than clang 14.0.0)

This issue is not visible with `clang-14` or `clang-15`:

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/2319559588
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/2319477162

**Comment by nickdesaulniers** [comment]
ah, with old clangs BEFORE I fixed this in LLVM. ok, then we should either disable the test, or those two 64b test cases with older releases of clang.

**Comment by nathanchance** [comment]
Kees dropped the problematic patch so closing.
