### ISSUE TITLE
error: casting from randomized structure pointer type in fs/incfs/data_mgmt.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1652]
Looks like an ARCH=arm allmodconfig of android-mainline
https://github.com/ClangBuiltLinux/continuous-integration2/runs/6857619625?check_suite_focus=true#step:5:240
```
Error: /builds/linux/fs/incfs/data_mgmt.c:240:10: error: casting from randomized structure pointer type 'struct dentry *' to 'struct data_file *'
                return (struct data_file *)index_file_dentry;
                       ^
Error: /builds/linux/fs/incfs/data_mgmt.c:257:12: error: casting from randomized structure pointer type 'struct file *' to 'struct data_file *'
                result = (struct data_file *)bf;
                         ^
```

**Comment by kees** [comment]
This code should be using ERR_CAST() instead of an open-coded cast.

https://android-review.googlesource.com/c/kernel/common/+/1995750/comments/23072fd8_57137ba0

**Comment by nathanchance** [comment]
Change submitted: https://android-review.googlesource.com/c/kernel/common/+/2134978

**Comment by nathanchance** [comment]
Fixed: https://android.googlesource.com/kernel/common/+/483887d651ebea298740f7fe895dd948df452d9f
