### ISSUE TITLE
ubsan divide by zero non-recoverable

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1662]
not sure if we already have a bug open, but filing one to track
https://lore.kernel.org/llvm/CAHk-=wj1qhf7y3VNACEexyp5EbkNpdcu_542k-xZpzmYLOjiCg@mail.gmail.com/
will fill in more notes later

**Comment by nathanchance** [comment]
I think #1657 was intended to track this unless there are two separate issues?
