### ISSUE TITLE
implement -mindirect-branch-cs-prefix

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1665]
via https://lore.kernel.org/lkml/YtEs9H+JEDUq6NNm@worktop.programming.kicks-ass.net/

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D130754

**Comment by nathanchance** [comment]
We'll need to submit a patch to the kernel to move that flag out of the GCC block:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/x86/Makefile?h=v5.19#n17

**Comment by nathanchance** [comment]
https://lore.kernel.org/20220817185410.1174782-1-nathan@kernel.org/

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D134915 is tangentially related. clang-16.

**Comment by nathanchance** [comment]
Resent: https://lore.kernel.org/20230120165826.2469302-1-nathan@kernel.org/

**Comment by dileks** [comment]
Missing link in the resend?

commit eac3e5c3fb7c
"[X86] Do not emit JCC to __x86_indirect_thunk"

BTW, what commid-id is a good choice for LLVM-16?

[1] https://github.com/llvm/llvm-project/commit/eac3e5c3fb7c

**Comment by nathanchance** [comment]
Kernel patch accepted: https://git.kernel.org/tip/27b5de622ea3fe0ad5a31a0ebd9f7a0a276932d1

**Comment by nathanchance** [comment]
In mainline: https://git.kernel.org/linus/27b5de622ea3fe0ad5a31a0ebd9f7a0a276932d1
