### ISSUE TITLE
./kernel/smp.c an unaligned pointer access [-Walign-mismatch]

### ISSUE THREAD

**Issue by edgars-cirulis** [ClangBuiltLinux/linux#1673]
./kernel/smp.c:344:33: warning: passing 8-byte aligned argument to 32-byte aligned parameter 2 of 'generic_exec_single' may result in an unaligned pointer access [-Walign-mismatch]
        err = generic_exec_single(cpu, csd, csd->func, csd->info);

**Comment by nathanchance** [comment]
What tree is this in? If you don’t have https://git.kernel.org/linus/1139aeb1c521eb4a050920ce6c64c36c4f2a3ab7, see if cherry picking that resolves it.

**Comment by edgars-cirulis** [comment]
> What tree is this in? If you don’t have https://git.kernel.org/linus/1139aeb1c521eb4a050920ce6c64c36c4f2a3ab7, see if cherry picking that resolves it.

https://github.com/Spectrum-Kernel/kernel_xiaomi_sm6250/commit/580a1408e07993ddf604be4f5078d377bee15f9f 

Custom kernel, and caused by this commit.

**Comment by nathanchance** [comment]
The prototype of `generic_exec_single` in `include/linux/smp.h` likely needs to be adjusted to have `struct  __call_single_data` be the type of the second parameter instead of `call_single_data_t`.

**Comment by edgars-cirulis** [comment]
> The prototype of `generic_exec_single` in `include/linux/smp.h` likely needs to be adjusted to have `struct __call_single_data` be the type of the second parameter instead of `call_single_data_t`.

Alright, Thanks for the suggestion, Thank you :)
