### ISSUE TITLE
cc-option failures after LLVM commit 8f0c901c1a172313a32bc06a1fcface76cd1220f

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1674]
After https://github.com/llvm/llvm-project/commit/8f0c901c1a172313a32bc06a1fcface76cd1220f, certain ARM and PowerPC builds are polluted with `-Waddress-of-packed-member`, which means `cc-option` has failed.

Looking into `arch/arm/Makefile` and `arch/powerpc/Makefile`, there are `-mtune` flags that are unconditionally called; these need to be wrapped in `cc-option` (or have their values implemented in LLVM).

```diff
diff --git a/arch/arm/Makefile b/arch/arm/Makefile
index c8e3633f5434..583fabcee502 100644
--- a/arch/arm/Makefile
+++ b/arch/arm/Makefile
@@ -97,7 +97,7 @@ tune-$(CONFIG_CPU_V6)         =-mtune=arm1136j-s
 tune-$(CONFIG_CPU_V6K)         =-mtune=arm1136j-s

 # Evaluate tune cc-option calls now
-tune-y := $(tune-y)
+tune-y := $(call cc-option, $(tune-y))

 ifeq ($(CONFIG_AEABI),y)
 CFLAGS_ABI     :=-mabi=aapcs-linux -mfpu=vfp
diff --git a/arch/powerpc/Makefile b/arch/powerpc/Makefile
index a0cd70712061..65efbfc8718f 100644
--- a/arch/powerpc/Makefile
+++ b/arch/powerpc/Makefile
@@ -166,7 +166,7 @@ CFLAGS-$(CONFIG_PPC32)      += $(call cc-option,-mno-readonly-in-sdata)
 ifdef CONFIG_PPC_BOOK3S_64
 ifdef CONFIG_CPU_LITTLE_ENDIAN
 CFLAGS-$(CONFIG_GENERIC_CPU) += -mcpu=power8
-CFLAGS-$(CONFIG_GENERIC_CPU) += $(call cc-option,-mtune=power9,-mtune=power8)
+CFLAGS-$(CONFIG_GENERIC_CPU) += $(call cc-option,-mtune=power9,$(call cc-option,-mtune=power8))
 else
 CFLAGS-$(CONFIG_GENERIC_CPU) += $(call cc-option,-mtune=power7,$(call cc-option,-mtune=power5))
 CFLAGS-$(CONFIG_GENERIC_CPU) += $(call cc-option,-mcpu=power5,-mcpu=power4)
```

@MaskRay can that change be reverted for the time being while we clean this up? It will take a while for these changes to trickle down into the stable branches and having our builds polluted with these warnings will make it harder to see other failures (and potentially affect other CI systems).

**Comment by MaskRay** [comment]
The argument reverting the change isn't really strong.

That said, for arm, if needed, we can ignore -mtune in `clang/lib/Driver/ToolChains/Arch/ARM.cpp`.
For PowerPC, implementing this option is probably not hard and I will try doing it...

**Comment by nathanchance** [comment]
Alright. Ignoring `-mtune` for ARM explicitly and implementing it for PowerPC seems reasonable. If not, I can just send patches for the above diff and deal with the fallout in the meantime.

**Comment by nathanchance** [comment]
This is no longer an issue after https://github.com/llvm/llvm-project/commit/1d23f6c5a4f6ebb101c282f8f506588fe4d9e92f.
