### ISSUE TITLE
-Wbitfield-constant-conversion in sound/soc/atmel/mchp-spdiftx.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1686]
```
sound/soc/atmel/mchp-spdiftx.c:505:20: error: implicit truncation from 'int' to bit-field changes value from 1 to -1 [-Werror,-Wbitfield-constant-conversion]
        dev->gclk_enabled = 1;
                          ^ ~
1 error generated.
```

Exposed by https://github.com/llvm/llvm-project/commit/82afc9b169a67e8b8a1862fb9c41a2cd974d6691.

Patch submitted: https://lore.kernel.org/20220810010809.2024482-1-nathan@kernel.org/

**Comment by nickdesaulniers** [comment]
https://github.com/llvm/llvm-project/issues/53253

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/broonie/sound/c/eab9100d9898cbd37882b04415b12156f8942f18

**Comment by nathanchance** [comment]
New SHA, as this is now targeting 6.0: https://git.kernel.org/broonie/sound/c/5c5c2baad2b55cc0a4b190266889959642298f79

**Comment by nathanchance** [comment]
Patch is merged into mainline: https://git.kernel.org/linus/5c5c2baad2b55cc0a4b190266889959642298f79

I have asked for a stable backport: https://lore.kernel.org/Yxyga8k1jee5A9Vs@dev-arch.thelio-3990X/
