### ISSUE TITLE
unable to write nop sequence of ... bytes after LLVM commit 73a9dfcee24df959b59a46d75dcbdc0bcfb50fe6

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1693]
After https://github.com/llvm/llvm-project/commit/73a9dfcee24df959b59a46d75dcbdc0bcfb50fe6, I see compiler crashes when building `ARCH=riscv defconfig` along the lines of:

```
fatal error: error in backend: unable to write nop sequence of 7 bytes
```

I did the initial bisect last night but I have not had time to run `cvise` for a simplified reproducer. I will do that now then report it upstream.

**Comment by nickdesaulniers** [comment]
cc @compnerd

**Comment by nathanchance** [comment]
Reported upstream: https://reviews.llvm.org/D131270

**Comment by nickdesaulniers** [comment]
reverted in https://reviews.llvm.org/rG443d9a46a879991e09bc723e64bdb1484ca1b94a.
