### ISSUE TITLE
as-option broken?

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1699]
I'm testing adding something with `as-option` in a Makfile. I think `as-option` is failing because it's using KBUILD_CFLAGS and internally we get lots of `-Werror,-Wunused-command-line-argument`.

**Comment by nickdesaulniers** [comment]
```diff
diff --git a/scripts/Makefile.compiler b/scripts/Makefile.compiler
index 94d0d40cddb3..b3e62f153900 100644
--- a/scripts/Makefile.compiler
+++ b/scripts/Makefile.compiler
@@ -32,7 +32,7 @@ try-run = $(shell set -e;             \
 # Usage: cflags-y += $(call as-option,-Wa$(comma)-isa=foo,)
 
 as-option = $(call try-run,\
-       $(CC) $(KBUILD_CFLAGS) $(1) -c -x assembler /dev/null -o "$$TMP",$(1),$(2))
+       $(CC) $(KBUILD_AFLAGS) $(1) -c -x assembler /dev/null -o "$$TMP",$(1),$(2))
 
 # as-instr
 # Usage: cflags-y += $(call as-instr,instr,option1,option2)
```
seems to make `as-option` work as I'd expect.

**Comment by nathanchance** [comment]
Hmmm, `as-option` is sometimes used to append to `KBUILD_CFLAGS`, although it does seem more correct to query the assembler using the flags that would be used for `.S` files, rather than `.c` files. That seems to line up with [the documentation](https://www.kernel.org/doc/html/latest/kbuild/makefiles.html#cc-support-functions) too.

```
    as-option
        as-option is used to check if $(CC) -- when used to compile
        assembler (`*.S`) files -- supports the given option.
```

**Comment by nathanchance** [comment]
I suspect the reason that this hasn't been noticed before is due to the fact that clang warns about flags that are supported but unused in whatever mode it is being invoked in (e.g., invoking just the compiler but passing in a linker flag).

**Comment by nickdesaulniers** [comment]
specifically, the full list of errors:
```
clang-15: error: argument unused during compilation: '-fno-strict-aliasing' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-fno-common' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-fshort-wchar' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-fcf-protection=none' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-falign-loops=1' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-mstack-alignment=8' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-mskip-rax-setup' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-mtune=generic' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-mno-red-zone' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-mcmodel=kernel' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-fno-asynchronous-unwind-tables' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-mfunction-return=thunk-extern' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-fno-delete-null-pointer-checks' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-fstack-protector-strong' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-fomit-frame-pointer' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-ftrivial-auto-var-init=zero' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-fno-stack-clash-protection' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-fno-strict-overflow' [-Werror,-Wunused-command-line-argument]
clang-15: error: argument unused during compilation: '-fno-stack-check' [-Werror,-Wunused-command-line-argument]
```

**Comment by nickdesaulniers** [comment]
I think this maybe depends on when we try to invoke as-option.

For example:
```
arch/x86/boot/compressed/Makefile
52:KBUILD_CFLAGS += $(call as-option,-Wa$(comma)-mrelax-relocations=no)
```

appears to be working, but KBUILD_CFLAGS also uses a different value of KBUILD_CFLAGS.  I'm guessing that KBUILD_CFLAGS gets added to KBUILD_AFLAGS somewhere, but I haven't found where quite yet.

**Comment by nathanchance** [comment]
> I'm guessing that KBUILD_CFLAGS gets added to KBUILD_AFLAGS somewhere

I don't think it does. If you assemble a `.S` file, you'll notice that the list of flags is way smaller than `KBUILD_CFLAGS`.

**Comment by nickdesaulniers** [comment]
I sent https://lore.kernel.org/llvm/20220826181035.859042-2-ndesaulniers@google.com/ for this.

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/masahiroy/linux-kbuild.git/commit/?h=fixes&id=97f72ed7a6b5a6bbac628f1f6e91cf06d1ea2cb5

**Comment by nathanchance** [comment]
I don't see that patch in Masahiro's branch anymore, did it get dropped?

**Comment by nickdesaulniers** [comment]
Yeah, there's way more users of as-option adding the results to cflags than the one place in x86... (I asked @masahir0y to drop it after a report from 0day while we were at plumbers).  I can revisit the fixup at some point.

**Comment by nathanchance** [comment]
This should now be fixed: https://git.kernel.org/linus/d5c8d6e0fa61401a729e9eb6a9c7077b2d3aebb0
