### ISSUE TITLE
missing gcov support

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#17]
Report from QC:

```sh
xyz.c:(.text+0x1804): undefined reference to `llvm_gcda_emit_function'

xyz.c:(.text+0x1814): undefined reference to `llvm_gcda_emit_arcs'

xyz.c:(.text+0x1834): undefined reference to `llvm_gcda_emit_function'

xyz.c:(.text+0x1844): undefined reference to `llvm_gcda_emit_arcs'

xyz.c:(.text+0x1848): undefined reference to `llvm_gcda_summary_info'

xyz.c:(.text+0x1858): undefined reference to `llvm_gcda_end_file'

xyz.o: In function `__llvm_gcov_init':

xyz.c:(.text+0x1a28): undefined reference to `llvm_gcov_init'
```

**Comment by gwelymernans** [comment]
As Nick mentioned in the email thread, this came up before. Linking in 'compiler_rt' should resolve the missing symbols.

  https://groups.google.com/forum/#!topic/llvm-dev/4AlWT2VrkMk

**Comment by nickdesaulniers** [comment]
Maybe the kernel needs to add `--rtlib=compiler-rt` to CFLAGS when gcov is configured and CC==clang?

**Comment by nickdesaulniers** [comment]
Here's the first patch needed: https://lore.kernel.org/r/20180426212807.196279-1-ndesaulniers@google.com/

will need another for the missing symbols.

**Comment by nickdesaulniers** [comment]
Temp patches have been created to add kernel helper functions for runtime support of gcov in the kernel. QC is testing, but they could use more polish before trying to upstream.  Will try to get around to it with more time.

**Comment by nickdesaulniers** [comment]
Pushed patches to https://github.com/ClangBuiltLinux/linux/tree/gcov.  Still testing.

```
CONFIG_GCOV_KERNEL=y
CONFIG_ARCH_HAS_GCOV_PROFILE_ALL=y
CONFIG_GCOV_PROFILE_ALL=y
# CONFIG_GCOV_FORMAT_4_7 is not set
CONFIG_GCOV_FORMAT_CLANG=y
```

```sh
$ mount -t debugfs none /sys/kernel/debug
$ ls /sys/kernel/debug/gcov/<path/to/>*.gcda
```

**Comment by nickdesaulniers** [comment]
@vo4 just sent patches upstream: https://lore.kernel.org/r/20190114210426.177543-1-trong@android.com/

**Comment by nickdesaulniers** [comment]
v3: https://lore.kernel.org/r/20190122233749.42220-1-trong@android.com/

**Comment by vo4** [comment]
[v4](https://lore.kernel.org/r/20190318025411.98014-1-trong@android.com/) was added to mm tree.

**Comment by nickdesaulniers** [comment]
reopening until this hits mainline.

**Comment by bulwahn** [comment]
👍 🎉 This was the last topic I have seen to reach allyesconfig on x86 from the kernel side. Now, only asm-goto needs to get into clang-9. 👍

**Comment by nickdesaulniers** [comment]
Tri's fix for CONFIG_MODULES=n was just accepted.  Will post link once I can find it.

**Comment by vo4** [comment]
Btw, how are cross-tree patches are handled in linux? CONFIG_MODULES=n fix will probably be in modules tree. Should we ask akpm to take gcov patches into mm tree?

**Comment by nickdesaulniers** [comment]
> Btw, how are cross-tree patches are handled in linux?

Good question; it would be great not to have to wait for the modules patch to hit mainline.  Would you responding to the thread w/ Jessice cc'ing akpm and ask them?

**Comment by nathanchance** [comment]
> Btw, how are cross-tree patches are handled in linux?

Usually, maintainer A gives their "Acked-by"  and maintainer B carries the patch. In this instance, Andrew should probably carry the modules patch with Jessica's ack since the gcov series is bigger.

**Comment by nathanchance** [comment]
Merged into mainline!

https://git.kernel.org/linus/e178a5beb36960902379040ee0b667fb0a8eee93
