### ISSUE TITLE
Poor performance with `Retbleed: Mitigation; IBPB` compared to gcc-built kernels

### ISSUE THREAD

**Issue by WOnder93** [ClangBuiltLinux/linux#1708]
I noticed this on a physical machine with `AMD Opteron(TM) Processor 6272` (reports `Retbleed: Mitigation; IBPB` in `lscpu`). The performance of a clang-built kernel is significantly worse than gcc-built, presumably due to the IBPB Retbleed mitigation.

When I run `htop` while running a gcc-built kernel, I can see `htop` itself consuming just a few % CPU as expected. When I run it on a clang-built kernel, it consumes about 25% CPU on the same machine. Running `htop` under `perf record` identified `entry_ibpb` as the culprit, taking up about 93% of the CPU time used by `htop`.

This happens with at least kernels 5.19 and 6.0-rc5 (didn't test other versions) and clang 14.0.5 (also didn't test other versions).

**Comment by nathanchance** [comment]
Just to make sure, is the type of mitigation used for this machine the same between `clang` and GCC? In other words, is the GCC kernel using IBPB as well or is it using the return thunk mitigation? Clang 14.0.5 won't have the compiler flag for return thunks but your version of GCC might.

**Comment by WOnder93** [comment]
Ah, I forgot to check that, sorry :facepalm: Indeed on the gcc-built kernel I get `Retbleed: Mitigation; untrained return thunk; SMT vulnerable`. So the only problem is probably the missing compiler flag, which as I can see should be already available in clang 15+ (https://github.com/llvm/llvm-project/commit/2240d72f15f3b7b9d9fb65450f9bf635fd310f6f).

Thank you for pointing me in the right direction :)
