### ISSUE TITLE
CFI: asan.module_ctor is missing a type hash

### ISSUE THREAD

**Issue by samitolvanen** [ClangBuiltLinux/linux#1742]
From Mark Rutland:
> Looks like CFI && KASAN is borked on both arm64 and x86; the implicitly-generated asan.module_ctor functions aren't given a type hash by the compiler, so when those get invoked by do_ctors() the calls fail

cc @kees @nickdesaulniers @nathanchance @lvwr

**Comment by samitolvanen** [comment]
The `asan.module_ctor` function is created in the `asan` LLVM pass using `createSanitizerCtor`. Since this happens outside of Clang, it's a bit awkward to generate a type hash for the function at this point.

The reason we didn't have this problem earlier was that `do_ctors` is an `__init` function and CFI was disabled for it. I'm leaning towards simply marking the function `__nocfi` instead of hardcoding a type hash for these functions or hacking something together in LLVM to compute a hash. Thoughts?

**Comment by samitolvanen** [comment]
Perhaps setting the types in LLVM is reasonable after all, as we'd have to deal with module constructors as well otherwise. Here's an alternative solution: https://reviews.llvm.org/D138945

**Comment by samitolvanen** [comment]
The remaining issue with CFI+KASAN is that `asan.module_ctor` still won't have a type hash in object files that were not compiled with `-fsanitize=kcfi`. With x86/arm64 defconfigs, it looks like only the constructor in `kernel/cfi.o` trips KASAN, but I don't see any reason we couldn't now enable CFI also for `kernel/cfi.c`.

**Comment by samitolvanen** [comment]
https://lore.kernel.org/lkml/20221222225747.3538676-1-samitolvanen@google.com/

**Comment by nathanchance** [comment]
https://github.com/llvm/llvm-project/commit/3b14862f0a968dc079530acbce4f2ca4aa7c1492

https://git.kernel.org/linus/cf8016408d880afe9c5dc495af40dc2932874e77

**Comment by samitolvanen** [comment]
CFI+KASAN still fails on x86 because `asan.module_ctor` doesn't have the same `patchable-function-prefix` as the other functions, and KCFI assumes all functions have the same number of prefix nops, as discussed in #1744.

**Comment by samitolvanen** [comment]
https://reviews.llvm.org/rGfd5e26270660 fixes the `patchable-function-prefix` issue on x86.

However... when x86 implemented FineIBT, they also added CFI hash randomization, which is still broken with KASAN. This is because even though objtool is run against `vmlinux.o` to build the `.cfi_sites` section that contains hash locations, there are two additional object files linked into the final `vmlinux` binary that both contain `asan.module_ctor` constructors: `.vmlinux.export.o` and `init/version-timestamp.o`. Since objtool didn't see these files, any type hashes in them are not in `.cfi_sites`, and thus they won't get randomized, which leads to a CFI failure as soon as `do_ctors` calls them.

`cfi=norand` can be used to work around this issue, but I suspect we should just disable KASAN for these files. Or perhaps make sure objtool processes them too?

**Comment by samitolvanen** [comment]
https://lore.kernel.org/lkml/20230112224948.1479453-2-samitolvanen@google.com/

**Comment by samitolvanen** [comment]
https://git.kernel.org//torvalds/c/42633ed852deadc14d44660ad71e2f6640239120
