### ISSUE TITLE
Huge build time performance regression with f35b5d7d676e

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1746]
After upgrading my workstation's kernel from 6.0 to 6.1-rc1, my full set of kernel builds went from 2 hours and 20 minutes or so to over 3 hours. I was able to bisect this performance regression down to commit [f35b5d7d676e](https://git.kernel.org/linus/f35b5d7d676e59e401690b678cd3cfec5e785c23) ("mm: align larger anonymous mappings on THP boundaries"). The LTP folks noticed this regression as well so I [jumped in to report my findings there](https://lore.kernel.org/Y1GCYXGtEVZbcv%2F5@dev-arch.thelio-3990X/). I see this regression when the host kernel is built with GCC, so this is not an LLVM issue when building the kernel that will actually run on the system. The thread will likely have further follow ups, I am only making this issue in case people wonder why their build times with LLVM might be worse on a current mainline kernel.

**Comment by nathanchance** [comment]
The revert landed in 6.1-rc8.

https://git.kernel.org/linus/0ba09b1733878afe838fe35c310715fda3d46428

I will try to work with upstream to bring it back in a form that does not regress build time performance with clang.

**Comment by nickdesaulniers** [comment]
Do you have a link to where Linus decided to revert? @kees and I were wondering how Linus got involved?

**Comment by nathanchance** [comment]
Yeah, he reverted it due to my report appearing in the regression tracking report that Thorsten regularly sends:

https://lore.kernel.org/CAHk-=wgCHBWN5VbCAc6=bKMnEBjdumqDGYG=X1E27VWG2H_WQQ@mail.gmail.com/

It was going to get there via Andrew Morton originally:

https://lore.kernel.org/20221201212952.5C0ADC433D6@smtp.kernel.org/
