### ISSUE TITLE
CONFIG_PARAVIRT_SPINLOCKS=y lead to an error that section flags changed

### ISSUE THREAD

**Issue by courageJin** [ClangBuiltLinux/linux#1753]
after I compile the newest Linux which supports Rust by the command "make LLVM=-11", an error happened, and when I use the gcc to compile the linux, this error didn't exist.

The config is x86_64_defconfig with CONFIG_PARAVIRT_SPINLOCKS=y and rust configs.

`<inline asm>:16:1: error: changed section flags for .spinlock.text, expected: 0x6
.pushsection .spinlock.text;
.globl __raw_callee_save___pv_queued_spin_unlock;
.type __raw_callee_save___pv_queued_spin_unlock, @function;
.align 4,0x90;
__raw_callee_save___pv_queued_spin_unlock: 
push  %rdx;
mov   $0x1,%eax;
xor   %edx,%edx;.
pushsection .smp_locks,"a"`

**Comment by nathanchance** [comment]
I don't have a suitable environment for compiling Rust in the kernel at the moment. Does this happen with just `x86_64_defconfig` + `CONFIG_PARAVIRT_SPINLOCKS=y` for you? It doesn't for me, which means it might be related to the Rust support. Additionally, you say

> the newest Linux which supports Rust

but what revision are you using?

**Comment by nathanchance** [comment]
https://lore.kernel.org/20221108060126.2505-1-guoj17@chinatelecom.cn/

https://lore.kernel.org/Y2rayPgDfL2NYcjQ@dev-arch.thelio-3990X/

**Comment by nathanchance** [comment]
https://git.kernel.org/tip/23df39fc6a36183af5e6e4f47523f1ad2cdc1d30

**Comment by nathanchance** [comment]
https://git.kernel.org/linus/23df39fc6a36183af5e6e4f47523f1ad2cdc1d30
