### ISSUE TITLE
ld.lld switch to '--no-undefined-version' breaks RISC-V and x86 vDSO builds

### ISSUE THREAD

**Issue by unicornx** [ClangBuiltLinux/linux#1756]
hello,  I'm trying build riscv linux with the clang built with tc-linux.  I follow the guide from tc-linux and run the build-llvm.py.

linux version: 6.0

make ARCH=riscv CC=clang CROSS_COMPILE=riscv64-linux-gnu- LLVM=1 O=../build-riscv-clang/ defconfig
make ARCH=riscv CC=clang CROSS_COMPILE=riscv64-linux-gnu- LLVM=1 O=../build-riscv-clang/ -j 1

```
ld.lld: error: version script assignment of 'LINUX_4.15' to symbol '__vdso_gettimeofday' failed: symbol not defined
ld.lld: error: version script assignment of 'LINUX_4.15' to symbol '__vdso_clock_gettime' failed: symbol not defined
ld.lld: error: version script assignment of 'LINUX_4.15' to symbol '__vdso_clock_getres' failed: symbol not defined
  VDSOSYM include/generated/compat_vdso-offsets.h
llvm-nm: error: arch/riscv/kernel/compat_vdso/compat_vdso.so.dbg: No such file or directory
  CHK     include/generated/compile.h
  CC      init/main.o
  CC      init/version.o
  CC      init/do_mounts.o
  CC      init/do_mounts_initrd.o
  CC      init/initramfs.o
  CC      init/calibrate.o
  CC      init/init_task.o
  AR      init/built-in.a
  HOSTCC  usr/gen_init_cpio
  GEN     usr/initramfs_data.cpio
  COPY    usr/initramfs_inc_data
  AS      usr/initramfs_data.o
  AR      usr/built-in.a
  AR      arch/riscv/kernel/probes/built-in.a
  OBJCOPY arch/riscv/kernel/vdso/vdso.so
  AS      arch/riscv/kernel/vdso/vdso.o
  AR      arch/riscv/kernel/vdso/built-in.a
  VDSOLD  arch/riscv/kernel/compat_vdso/compat_vdso.so.dbg
ld.lld: error: version script assignment of 'LINUX_4.15' to symbol '__vdso_gettimeofday' failed: symbol not defined
ld.lld: error: version script assignment of 'LINUX_4.15' to symbol '__vdso_clock_gettime' failed: symbol not defined
ld.lld: error: version script assignment of 'LINUX_4.15' to symbol '__vdso_clock_getres' failed: symbol not defined
  OBJCOPY arch/riscv/kernel/compat_vdso/compat_vdso.so
llvm-objcopy: error: 'arch/riscv/kernel/compat_vdso/compat_vdso.so.dbg': No such file or directory
make[3]: *** [arch/riscv/kernel/compat_vdso/Makefile:48: arch/riscv/kernel/compat_vdso/compat_vdso.so] Error 1
make[2]: *** [scripts/Makefile.build:465: arch/riscv/kernel/compat_vdso] Error 2
make[1]: *** [scripts/Makefile.build:465: arch/riscv/kernel] Error 2
make: *** [Makefile:1852: arch/riscv] Error 2
```

**Comment by nathanchance** [comment]
Thank you for the report! This is a very recent regression, caused by https://github.com/llvm/llvm-project/commit/eedbe44b8755f7d162eee43cb3e8c9da1e61ebad. You can either revert that change in the LLVM sources then pass `--no-update` to `build-llvm.py` or apply this diff to the kernel (which I plan to send later today):

```diff
diff --git a/arch/riscv/kernel/compat_vdso/Makefile b/arch/riscv/kernel/compat_vdso/Makefile
index 260daf3236d3..1df0d75e4807 100644
--- a/arch/riscv/kernel/compat_vdso/Makefile
+++ b/arch/riscv/kernel/compat_vdso/Makefile
@@ -37,7 +37,8 @@ $(obj)/compat_vdso.o: $(obj)/compat_vdso.so
 $(obj)/compat_vdso.so.dbg: $(obj)/compat_vdso.lds $(obj-compat_vdso) FORCE
        $(call if_changed,compat_vdsold)
 LDFLAGS_compat_vdso.so.dbg = -shared -S -soname=linux-compat_vdso.so.1 \
-       --build-id=sha1 --hash-style=both --eh-frame-hdr
+       --build-id=sha1 --hash-style=both --eh-frame-hdr \
+       $(call ld-option, --undefined-version)
 
 $(obj-compat_vdso): %.o: %.S FORCE
        $(call if_changed_dep,compat_vdsoas)
diff --git a/arch/riscv/kernel/vdso/Makefile b/arch/riscv/kernel/vdso/Makefile
index f2e065671e4d..ca12102f3f0a 100644
--- a/arch/riscv/kernel/vdso/Makefile
+++ b/arch/riscv/kernel/vdso/Makefile
@@ -45,7 +45,8 @@ $(obj)/vdso.o: $(obj)/vdso.so
 $(obj)/vdso.so.dbg: $(obj)/vdso.lds $(obj-vdso) FORCE
        $(call if_changed,vdsold)
 LDFLAGS_vdso.so.dbg = -shared -S -soname=linux-vdso.so.1 \
-       --build-id=sha1 --hash-style=both --eh-frame-hdr
+       --build-id=sha1 --hash-style=both --eh-frame-hdr \
+       $(call ld-option, --undefined-version)
 
 # strip rule for the .so file
 $(obj)/%.so: OBJCOPYFLAGS := -S
```

**Comment by nathanchance** [comment]
Actually, I think this is a better fix:

https://lore.kernel.org/20221108171324.3377226-1-nathan@kernel.org/

**Comment by ConchuOD** [comment]
> Actually, I think this is a better fix:
> https://lore.kernel.org/20221108171324.3377226-1-nathan@kernel.org/

In the middle of re-setting up my machine but I'll give you some sort of tag on this once I've got it up and running.

**Comment by nathanchance** [comment]
I just ran into another one in x86: https://lore.kernel.org/20221109000306.1407357-1-nathan@kernel.org/

**Comment by unicornx** [comment]
> Actually, I think this is a better fix:
> 
> https://lore.kernel.org/20221108171324.3377226-1-nathan@kernel.org/

Thanks, I tried this patch and kernel build works for me now. Will this patch enter 6.1?

**Comment by nathanchance** [comment]
> Thanks, I tried this patch and kernel build works for me now. Will this patch enter 6.1?

I hope so but I am not the person who gets to make that call. Worst case, it gets punted to 6.2-rc1 and we backport it to the eventual linux-6.1.y branch.

**Comment by nathanchance** [comment]
[The `ld.lld` change has been reverted](https://github.com/llvm/llvm-project/commit/b1fdeeec1a5a570be57bca17fcc647892d2030ab) but I fully expect it to come back eventually so we should still push to get these changes accepted

**Comment by ConchuOD** [comment]
> [The `ld.lld` change has been reverted](https://github.com/llvm/llvm-project/commit/b1fdeeec1a5a570be57bca17fcc647892d2030ab) but I fully expect it to come back eventually so we should still push to get these changes accepted

Great commit message, really helps me understand why it was reverted :heart_eyes_cat:

**Comment by nathanchance** [comment]
The RISC-V change has been accepted: https://git.kernel.org/riscv/c/fcae44fd36d052e956e69a64642fc03820968d78

Hopefully, the x86 one can be picked up relatively quickly, it [sounds like they have a big backlog](https://lore.kernel.org/2993a60c-edaa-a29a-2644-3ee86c622847@intel.com/).

**Comment by nathanchance** [comment]
RISC-V change is in 6.1-rc5: https://git.kernel.org/linus/fcae44fd36d052e956e69a64642fc03820968d78

I will handle backports for it soon; as I mentioned above, the `ld.lld` change has been reverted so this is lower priority because it's not breaking us for now.

**Comment by nathanchance** [comment]
The default change is back so x86 is now broken again because my change has not been picked up:

https://github.com/llvm/llvm-project/commit/241dbd310599e3c1a0f1b0c9ced14c8b8760539e

I've pinged the patch.

**Comment by nathanchance** [comment]
x86 patch is now accepted: https://git.kernel.org/tip/45be2ad007a9c6bea70249c4cf3e4905afe4caeb

**Comment by nathanchance** [comment]
x86 patch is now in mainline: https://git.kernel.org/linus/45be2ad007a9c6bea70249c4cf3e4905afe4caeb

I will handle stable backports later, if it does not get AUTOSEL'd by then.
