### ISSUE TITLE
unknown argument: '-mapcs' and '-mno-sched-prolog' when compiling with frame pointers

### ISSUE THREAD

**Issue by agners** [ClangBuiltLinux/linux#176]
When building with `CONFIG_FRAME_POINTER` building fails with

```
clang-7: error: unknown argument: '-mapcs'
clang-7: error: unknown argument: '-mno-sched-prolog'
make[2]: *** [scripts/Makefile.build:306: scripts/mod/empty.o] Error 1                                                                     
make[2]: *** Waiting for unfinished jobs....
clang-7: error: unknown argument: '-mapcs'
clang-7: error: unknown argument: '-mno-sched-prolog'
make[2]: *** [scripts/Makefile.build:131: scripts/mod/devicetable-offsets.s] Error 1                                                       
make[1]: *** [scripts/Makefile.build:546: scripts/mod] Error 2
make: *** [Makefile:1065: scripts] Error 2
```

**Comment by agners** [comment]
See also:
https://lore.kernel.org/r/20180320231832.GK2743@n2100.armlinux.org.uk/
Clang probably won't support the necessary frame format. There is new stack unwinding support for ARM EABI which should be used with Clang. Patches to prevent users from selecting `CONFIG_FRAME_BUFFER` are in the works:

**Comment by nickdesaulniers** [comment]
https://llvm.org/pr18505 is the LLVM bug, for reference.  Looks like @eugenis knows more about this.  Also, cc @mkaehlcke .

**Comment by agners** [comment]
`ARM: 8800/1: use choice for kernel unwinders` prevents Linux from selecting frame pointers when using Clang.

**Comment by nickdesaulniers** [comment]
Sorry, @agners is that a commit message of a patch? Looks like it hasn't landed in torvalds/linux.  Is it in an ARM tree? Can you provide a tree/sha?

**Comment by agners** [comment]
It is in -next. It is in Russels git tree:
http://git.armlinux.org.uk/cgit/linux-arm.git/commit/?h=for-next&id=f9b58e8c7d031b0daa5c9a9ee27f5a4028ba53ac

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f9b58e8c7d031b0daa5c9a9ee27f5a4028ba53ac
