### ISSUE TITLE
libbpf: BTF header not found Kernel compile issue with Clang-16 and BPF

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#1762]
With a bpf-configured clang 16.0.0 (f49c2a8c365917a704d2f9af49c83892b9ae167f), pahole-git (1.24.r29.g02d67c5) and bpf from the Arch community repo, I see the following compilation error with my 6.0.9 Kernel:

```
libbpf: BTF header not found
pahole: .tmp_vmlinux.btf: Invalid argument
  LD      .tmp_vmlinux.kallsyms1
  KSYMS   .tmp_vmlinux.kallsyms1.S
  AS      .tmp_vmlinux.kallsyms1.S
  LD      .tmp_vmlinux.kallsyms2
  KSYMS   .tmp_vmlinux.kallsyms2.S
  AS      .tmp_vmlinux.kallsyms2.S
  LD      .tmp_vmlinux.kallsyms3
  KSYMS   .tmp_vmlinux.kallsyms3.S
  AS      .tmp_vmlinux.kallsyms3.S
  LD      vmlinux
  BTFIDS  vmlinux
FAILED: load BTF from vmlinux: Invalid argument
```
Here is my config:
[config_bpf.txt](https://github.com/ClangBuiltLinux/linux/files/10050200/config_bpf.txt)

Some context: This issue blocks usage of new BPF functionality for lower-latency Proton gaming within [ananicy-cpp-git](https://gitlab.com/ananicy-cpp/ananicy-cpp/-/commits/master) which mandates the presence of BPF and certain Kernel debug options. That BPF functionality works with the stock CachyOS-Kernel, but I could not get it to work with my custom-compiled Kernel and Clang-16 due to the issue reported here. The stock Kernel is compiled with a fatter [config](https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos-bore/config) and Clang-14.0.6, but the relevant config options are identical.

**Comment by nathanchance** [comment]
Is this a `pahole` or toolchain regression? Has it ever worked? I have not seen this with my configuration, which does turn on `CONFIG_DEBUG_INFO_BTF`, but I am on mainline and I think my `pahole` is a little older than yours.

**Comment by ms178** [comment]
As I only began playing around with this very recently, I cannot tell for sure if that is a regression in `pahole` or the toolchain. I use my custom Clang-16 toolchain and cannot test the default toolchain. The only thing I can report in addition is that I also saw a compile issue with the default `pahole` distro package.

As there were some other Clang/Pahole-issues fixed recently, I hoped `pahole-git` might have cured this, but it is still there. 

At least the CachyOS maintainers could make this work in Kernel 6.0.9 with Clang-14.0.6 and the default `pahole`. I am right now on their distro-provided cachyos-bore-lto Kernel and with that, the ananicy-cpp BPF feature works as expected.

**Comment by ms178** [comment]
A source of failure could be my custom CFLAGS. I'll try it with the standard flags, without some additional patches and could also try out the CachyOS-provided Clang-15-BOLT (https://aur.cachyos.org/) next.

Edit: The standard CFLAGS also show the same issue.

**Comment by ms178** [comment]
Progress! With the Clang-15.0.5-BOLT from the linked repo, the Kernel build succeeded with config-bpf (using `pahole-git`). I am now testing my own Clang-16-BOLT which is built differently than my LLVM-git toolchain (to rule out a potential issue with my LLVM-git PKGBUILD).

**Comment by ms178** [comment]
As I've now also manged to build the Kernel successfully with that config and pahole-git with Clang-16-BOLT (9e14ffa444cdef7ab6fbebb0a4e61474d3f5df09), the issue seems to come from my LLVM-git Toolchain, hence I am closing this.

**Comment by ms178** [comment]
I cheered a bit too soon, the Kernel compiled but did not boot successfully. It hanged right after load from the boot loader.

**Comment by ms178** [comment]
Trying this again on a fresh install and with a newer Clang-16 build succeeded with a booting Kernel. Unfortunately ananicy-cpp-git still threw out a segfault when built with the new BPF-functionality enabled. As I don't get that problem with the distribution-provided Kernel, I am out of ideas why that happens.

**Comment by nathanchance** [comment]
It might be worth reaching out to the BPF folks on the mailing list. They pretty much own the BPF stack in LLVM and they may be able to help?



```
$ scripts/get_maintainer.pl kernel/bpf
Alexei Starovoitov <ast@kernel.org> (supporter:BPF [GENERAL] (Safe Dynamic Programs and Tools))
Daniel Borkmann <daniel@iogearbox.net> (supporter:BPF [GENERAL] (Safe Dynamic Programs and Tools))
Andrii Nakryiko <andrii@kernel.org> (supporter:BPF [GENERAL] (Safe Dynamic Programs and Tools))
Martin KaFai Lau <martin.lau@linux.dev> (reviewer:BPF [GENERAL] (Safe Dynamic Programs and Tools))
Song Liu <song@kernel.org> (reviewer:BPF [GENERAL] (Safe Dynamic Programs and Tools))
Yonghong Song <yhs@fb.com> (reviewer:BPF [GENERAL] (Safe Dynamic Programs and Tools))
John Fastabend <john.fastabend@gmail.com> (reviewer:BPF [GENERAL] (Safe Dynamic Programs and Tools))
KP Singh <kpsingh@kernel.org> (reviewer:BPF [GENERAL] (Safe Dynamic Programs and Tools))
Stanislav Fomichev <sdf@google.com> (reviewer:BPF [GENERAL] (Safe Dynamic Programs and Tools))
Hao Luo <haoluo@google.com> (reviewer:BPF [GENERAL] (Safe Dynamic Programs and Tools))
Jiri Olsa <jolsa@kernel.org> (reviewer:BPF [GENERAL] (Safe Dynamic Programs and Tools))
bpf@vger.kernel.org (open list:BPF [GENERAL] (Safe Dynamic Programs and Tools))
linux-kernel@vger.kernel.org (open list)
```

Otherwise, someone else around here might be familiar with BPF to know what is going on here.

**Comment by ms178** [comment]
Re-visiting this, I cannot reproduce the issue any longer with a slightly trimmed down CachyOS config and newer LLVM/Clang-16 revision.
