### ISSUE TITLE
objtool memory usage regression in -tip tree after call depth tracking

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1768]
Initially reported at https://gitlab.com/Linaro/tuxsuite/-/issues/183.

After the call depth tracking series was merged into -tip, we see a noticeable increase in memory usage when building `allyesconfig` (my initial measurements on an EPYC server shows max RSS going from 18GB to 25GB or so), which causes builds on TuxSuite to come to a screeching halt due to memory pressure.

My initial bisect attempts make it seem like this is related to the new function alignment configuration introduced in https://git.kernel.org/tip/d49a0626216b95cd4bf696f6acf55f39a16ab0bb, which gets selected by `CONFIG_CALL_THUNKS` in https://git.kernel.org/tip/8f7c0d8b23c3f5f740a48db31ebadef28af17a22. I am still trying to get some smoking gun for what exactly is going on here but `allyesconfig` is not the quickest to build and I only recently thought of parsing the output of `time -v` to try and automate bisecting.

**Comment by nickdesaulniers** [comment]
We need to remember to re-enable x86_64 allyesconfig (https://github.com/ClangBuiltLinux/continuous-integration2/pull/482) once this is resolved.

**Comment by nathanchance** [comment]
I forgot to mention that this will only be visible with LLVM 15 and newer, due to call depth tracking depending on return thunks (`CONFIG_RETHUNK` and `CC_HAS_RETURN_THUNK`).

**Comment by nathanchance** [comment]
Peter has a series that resolves this for me:

https://lore.kernel.org/20230208171756.898991570@infradead.org/

https://lore.kernel.org/Y+PrYVKwXIyutFEl@dev-arch.thelio-3990X/

**Comment by nathanchance** [comment]
That series is now in tip: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/log/?h=objtool/core

**Comment by nathanchance** [comment]
That series is now in mainline: https://git.kernel.org/linus/857f1268a591147f7be7509f249dbb3aba6fc65c
