### ISSUE TITLE
error: unknown target CPU '405'

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1771]
After LLVM commit [1fdbe5c573b9](https://github.com/llvm/llvm-project/commit/1fdbe5c573b920f00e5bfdbcea0e837833ae77a0) ("[clang][PPC] Checking Unknown Values Passed to -mcpu"), I see the following errors when building `ppc44x_defconfig` (NOTE: this config is also broken due to #1679; to see this issue, you may need to use a tree older than 6.0 or revert the change that caused #1679):

```
error: unknown target CPU '405'
note: valid target CPU values are: generic, 440, 450, 601, 602, 603, 603e, 603ev, 604, 604e, 620, 630, g3, 7400, g4, 7450, g4+, 750, 8548, 970, g5, a2, e500, e500mc, e5500, power3, pwr3, power4, pwr4, power5, pwr5, power5x, pwr5x, power6, pwr6, power6x, pwr6x, power7, pwr7, power8, pwr8, power9, pwr9, power10, pwr10, powerpc, ppc, ppc32, powerpc64, ppc64, powerpc64le, ppc64le, future
make[3]: *** [arch/powerpc/boot/Makefile:228: arch/powerpc/boot/4xx.o] Error 1
```

This seems expected, based on the commit message of that change; prior to it, we were silently accepting `405` as a valid CPU target even though LLVM does not support it.

You can see what files are built with `-mcpu=405` in `arch/powerpc/boot/Makefile`:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/powerpc/boot/Makefile#n84

**Comment by nickdesaulniers** [comment]
cc @nemanjai is 405 something we can add support for to clang's list of known CPUs? Or is it old enough to have codegen implications?

**Comment by nemanjai** [comment]
We previously accepted anything and just reverted back to the default. If there were codegen implications, I'm sure we would have hit them. So I think it is fine to add it.

**Comment by qiongsiwu** [comment]
https://github.com/llvm/llvm-project/commit/de8deb5189c948db89c753ff2dff65b8e7840e8b has landed to accept `-mcpu=405`.

**Comment by nathanchance** [comment]
Thanks for the quick fix! This should be resolved.

**Comment by nickdesaulniers** [comment]
Yes thanks @qiongsiwu and @nemanjai !

**Comment by nickdesaulniers** [comment]
#675 is a similar issue but for `-Wa,-m405` rather than `-mcpu=405`.
