### ISSUE TITLE
-Wfortify-source in drivers/vdpa/solidrun/snet_main.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1773]
```
  drivers/vdpa/solidrun/snet_main.c:561:2: error: 'snprintf' size argument is too large; destination buffer has size 25, but size argument is 256 [-Werror,-Wfortify-source]
          snprintf(name, SNET_NAME_SIZE, "psnet[%s]-bars", pci_name(pdev));
          ^
  drivers/vdpa/solidrun/snet_main.c:581:2: error: 'snprintf' size argument is too large; destination buffer has size 20, but size argument is 256 [-Werror,-Wfortify-source]
          snprintf(name, SNET_NAME_SIZE, "snet[%s]-bar", pci_name(pdev));
          ^
  2 errors generated.
```

I have reported this upstream: https://lore.kernel.org/Y6HjpvDfIusAz2uS@dev-arch.thelio-3990X/

**Comment by nickdesaulniers** [comment]
submitted: https://lore.kernel.org/virtualization/20221221072003.551091-1-alvaro.karsz@solid-run.com/

**Comment by nathanchance** [comment]
This is now applied:

https://git.kernel.org/mst/vhost/c/47897ed42d6e6dade252fd6edb6f79694485cc5e

Given that -next is not seeing updates for the next two weeks, I am just going to preemptively close this; it will certainly in the next release, as it will likely be in mainline by then:

https://lore.kernel.org/20221222144343-mutt-send-email-mst@kernel.org/
