### ISSUE TITLE
LLVM 16 release cycle

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1788]
https://discourse.llvm.org/t/llvm-weekly-471-january-9th-2023/67573 mentions that:

> The 16.x branch is scheduled to be created on Jan 24th.

**Comment by dileks** [comment]
Branched 25-Jan-2023: `release/16.x`

https://github.com/llvm/llvm-project/tree/release/16.x

**Comment by dileks** [comment]
[LLVM 16.0.0-rc1 has been tagged](https://discourse.llvm.org/t/llvm-16-0-0-rc1-has-been-tagged/68019)

[1] https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.0-rc1

**Comment by beakthoven** [comment]
LLVM 16.0.0-rc2 has been tagged

https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.0-rc2

**Comment by dileks** [comment]
LLVM 16.0.0-rc3 has been tagged

@tstellar says:
> Hi,
>
> I’ve tagged LLVM 16.0.0-rc3. There will be an -rc4, because we still have a number of outstanding issues.
> Please test out -rc3 and report results here.

[1] https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.0-rc3
[2] https://discourse.llvm.org/t/llvm-16-0-0-rc3-has-been-tagged/68667

**Comment by nathanchance** [comment]
16.0.0-rc4: https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.0-rc4

This is tentatively the last release candidate before final: https://discourse.llvm.org/t/llvm-16-0-0-rc4-has-been-tagged/69150

**Comment by nathanchance** [comment]
16.0.0: https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.0

**Comment by beakthoven** [comment]
16.0.1: https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.1

**Comment by beakthoven** [comment]
16.0.2: https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.2

**Comment by nathanchance** [comment]
16.0.2 uploaded to kernel.org: https://lore.kernel.org/20230419180635.GA1965688@dev-arch.thelio-3990X/

**Comment by nathanchance** [comment]
16.0.3: https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.3

I will build and upload to kernel.org tomorrow.

**Comment by dileks** [comment]
@nathanchance 

Thanks for the prebuilt toolchains on `https://kernel.org/pub/tools/llvm/`

Is it possible to have 1. file-size(s) 2. checksum(s) or a single checksum like SHA256sum of these files?

**Comment by nathanchance** [comment]
@dileks Yes, it is all in the `files` subdirectory: https://mirrors.edge.kernel.org/pub/tools/llvm/files/

**Comment by dileks** [comment]
Hmm, OK - a bit hidden... maybe a pointer in the LLVM RST file?

Did a simple rebuild of the last linux-kernel I had built on 30-Jan-2023:
```
$ cat /proc/version 
Linux version 6.2.0-rc6-2-amd64-clang16-kcfi (sedat.dilek@gmail.com@iniza) (ClangBuiltLinux clang version 16.0.3, ClangBuiltLinux LLD 16.0.3) #2~bookworm+dileks1 SMP PREEMPT_DYNAMIC 2023-05-05
```
(... and a successful test using selfmade pahole `v1.25`)

**Comment by nathanchance** [comment]
> maybe a pointer in the LLVM RST file?

Sure, I added

> Past releases, checksums, and file sizes can be viewed under [the files subdirectory](https://mirrors.edge.kernel.org/pub/tools/llvm/files/).

to the "Downloads" section of the README. It may take some time to show up as the frontends sync the change.

**Comment by beakthoven** [comment]
16.0.4: https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.4

**Comment by dileks** [comment]
@nathanchance 

Are you planning to release a fast and slim LLVM toolchain version 16.0.4?
It works like a charm here.
Thanks.

[0] https://kernel.org/pub/tools/llvm/
[1] https://kernel.org/pub/tools/llvm/files/

**Comment by nathanchance** [comment]
> Are you planning to release a fast and slim LLVM toolchain version 16.0.4?

Yes, I have been out for the last week and a half due to my wedding and honeymoon, so I will build and upload it at some point this week (maybe tomorrow, certainly by Wednesday).

**Comment by dileks** [comment]
Cool.

Congrats - when will you change your avatar s/Dad/Wife?

**Comment by nathanchance** [comment]
16.0.4 uploaded to kernel.org: https://lore.kernel.org/20230523231250.GA894339@dev-arch.thelio-3990X/

> Congrats - when will you change your avatar s/Dad/Wife?

Hopefully as soon as we get our photos back :)

**Comment by dileks** [comment]
Plan to try Linux `v6.4-rc4` with LLVM `16.0.4` but cannot promise to do so.

**Comment by beakthoven** [comment]
16.0.5: https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.5

**Comment by beakthoven** [comment]
16.0.6: https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.6

**Comment by nathanchance** [comment]
16.0.6 should not affect the kernel in any way, it just appears to include a WebAssembly fix for `ld.lld`. However, since I have the build resources, I uploaded 16.0.6 to [kernel.org](https://kernel.org/pub/tools/llvm/). I am not going to formally announce it on the mailing list.

[Tom says this is the last planned 16.x release](https://discourse.llvm.org/t/16-0-6-release/71344) so I will close this up for now.

**Comment by beakthoven** [comment]
I've opened #1896 for 17.x releases. Still requires appropriate label.
