### ISSUE TITLE
clang (LLVM option parsing): for the --replexitval option: may only occur zero or one times!

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1792]
a few of the clang-14 builds are failing in CI with:

```
clang (LLVM option parsing): for the --replexitval option: may only occur zero or one times!
```
this is likely related to my patch from #1666

**Comment by nickdesaulniers** [comment]
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/3888512897/jobs/6638165379#step:5:192
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/3888512897/jobs/6638165279#step:5:192

**Comment by nathanchance** [comment]
I think the patch is getting applied twice because 6.1.4 already included your change. We should audit CI for this patch and see where it is getting applied even though it is already present in the base tree.

**Comment by nickdesaulniers** [comment]
oh, right, I just need to drop some stable patches. Ok, I'll take care of that

**Comment by nickdesaulniers** [comment]
oops, didn't mean to push to main. I'll go turn on branch protection...

**Comment by nickdesaulniers** [comment]
it...looks like we have branch protection turned on...?
https://github.com/ClangBuiltLinux/continuous-integration2/settings/branch_protection_rules/18909666

**Comment by nathanchance** [comment]
That’s odd… I do not see a clear option to block pushes to main but I might be missing something…

Regardless, pushed change looks good to me.
