### ISSUE TITLE
"Error: non-constant .uleb128 is not supported" in mm/kfence/kfence_test.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1816]
When building `ARCH=riscv allmodconfig` with GNU as and a version of clang that defaults to DWARF5, I see the following failure:

```
$ make -skj"$(nproc)" ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- LLVM=1 LLVM_IAS=0 O=build mrproper allmodconfig mm/kfence/kfence_test.o
/tmp/kfence_test-08a0a0.s: Assembler messages:
/tmp/kfence_test-08a0a0.s:14627: Error: non-constant .uleb128 is not supported
/tmp/kfence_test-08a0a0.s:14628: Error: non-constant .uleb128 is not supported
/tmp/kfence_test-08a0a0.s:14632: Error: non-constant .uleb128 is not supported
/tmp/kfence_test-08a0a0.s:14633: Error: non-constant .uleb128 is not supported
/tmp/kfence_test-08a0a0.s:14639: Error: non-constant .uleb128 is not supported
...
```

This is the same issue as https://github.com/ClangBuiltLinux/linux/issues/1719, which was worked around in mainline with https://git.kernel.org/linus/0a6de78cff600cb991f2a1b7ed376935871796a0 but `-g` is unconditionally added to `kfence_test.c`, which is how it has been since it was introduced in https://git.kernel.org/linus/bc8fbc5f305aecf63423da91e5faf4c0ce40bf38.

@elver, is it intentional that those flags are added to the test file or are they leftover from debugging?

**Comment by nathanchance** [comment]
Whoops, that should be @melver in the OP...

**Comment by melver** [comment]
> When building `ARCH=riscv allmodconfig` with GNU as and a version of clang that defaults to DWARF5, I see the following failure:
> 
> ```
> $ make -skj"$(nproc)" ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- LLVM=1 LLVM_IAS=0 O=build mrproper allmodconfig mm/kfence/kfence_test.o
> /tmp/kfence_test-08a0a0.s: Assembler messages:
> /tmp/kfence_test-08a0a0.s:14627: Error: non-constant .uleb128 is not supported
> /tmp/kfence_test-08a0a0.s:14628: Error: non-constant .uleb128 is not supported
> /tmp/kfence_test-08a0a0.s:14632: Error: non-constant .uleb128 is not supported
> /tmp/kfence_test-08a0a0.s:14633: Error: non-constant .uleb128 is not supported
> /tmp/kfence_test-08a0a0.s:14639: Error: non-constant .uleb128 is not supported
> ...
> ```
> 
> This is the same issue as #1719, which was worked around in mainline with https://git.kernel.org/linus/0a6de78cff600cb991f2a1b7ed376935871796a0 but `-g` is unconditionally added to `kfence_test.c`, which is how it has been since it was introduced in https://git.kernel.org/linus/bc8fbc5f305aecf63423da91e5faf4c0ce40bf38.
> 
> @melver, is it intentional that those flags are added to the test file or are they leftover from debugging?

I think that was because it's possible to build the kernel w/o debug info, but still enable the test. At one point or another that caused the test to fail, but I have no idea if that still happens.

We could just remove the `-g`, and see when the test fails. There is another such case in kernel/kcsan.

I'm currently testing a patch that removes those `-g`.

**Comment by nathanchance** [comment]
https://lore.kernel.org/20230316155104.594662-1-elver@google.com/

**Comment by nickdesaulniers** [comment]
v2: https://lore.kernel.org/all/20230316224705.709984-1-elver@google.com/

**Comment by nathanchance** [comment]
Fixed in mainline and I saw backports for stable fly by:

https://git.kernel.org/linus/2e08ca1802441224f5b7cc6bffbb687f7406de95
