### ISSUE TITLE
-Wincompatible-pointer-type in drivers/cdx/cdx.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1828]
Reported-by: KernelCI Bot `<bot@kernelci.org>`

```
    1    drivers/cdx/cdx.c:393:8: error: incompatible function pointer types initializing 'ssize_t (*)(const struct bus_type *, const char *, size_t)' (aka 'long (*)(const struct bus_type *, const char *, unsigned long)') with an expression of type 'ssize_t (struct bus_type *, const char *, size_t)' (aka 'long (struct bus_type *, const char *, unsigned long)') [-Wincompatible-function-pointer-types]
```

**Comment by nathanchance** [comment]
Is that an old report? It is not a clang specific issue, I [reported it](https://lore.kernel.org/20230403155147.GA239124@dev-arch.thelio-3990X/) to Stephen and Greg and [it should be resolved in newer -next versions](https://lore.kernel.org/20230404085224.21843f6e@canb.auug.org.au/).

**Comment by nickdesaulniers** [comment]
oops, yeah it's obsolete.

`Mon, Apr 3, 7:07 AM (4 days ago)`
