### ISSUE TITLE
-Wbitwise-instead-of-logical in fs/namei.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1832]
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/4667394776/jobs/8267646356#step:5:2173

```
Warning: /builds/linux/fs/namei.c:2173:13: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
        } while (!(has_zero(a, &adata, &constants) | has_zero(b, &bdata, &constants)));
                  ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   ||
/builds/linux/fs/namei.c:2173:13: note: cast one or both operands to int to silence this warning
```
looks like an arm64 big endian build of mainline.

**Comment by nathanchance** [comment]
Huh, I thought we had an existing issue around this but I guess not :) I looked into this a while ago but never wrote anything down. `has_zero()` returns a boolean for big endian builds but it returns `unsigned long` for little endian builds (https://git.kernel.org/linus/36126f8f2ed8168eb13aa0662b9b9585cba100a9, https://git.kernel.org/linus/a6e2f029ae34f41adb6ae3812c32c5d326e1abd2). I suspect the cast would make people unhappy and I was not clear to me why there is this discrepancy around return types.

**Comment by nickdesaulniers** [comment]
> has_zero() returns a boolean for big endian builds

Sounds like that should be changed to return an unsigned long `0UL` rather than `false`.

**Comment by nathanchance** [comment]
This is the current `return` statement, it is not a simple constant: https://elixir.bootlin.com/linux/v6.3-rc6/source/include/asm-generic/word-at-a-time.h#L45. `has_zero()` is always used within a boolean context though so changing the return type should not matter for all current use cases but it could matter in other contexts?

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=36126f8f2ed8168eb13aa0662b9b9585cba100a9 has uses of `has_zero` with bitwise operations, which would imply non-boolean context usage.  If that usage persists, then it looks like `bool` is incorrect.

**Comment by nickdesaulniers** [comment]
Sent: https://lore.kernel.org/llvm/20230801-bitwise-v1-1-799bec468dc4@google.com/

**Comment by nathanchance** [comment]
https://git.kernel.org/linus/79e8328e5acbe691bbde029a52c89d70dcbc22f3
