### ISSUE TITLE
init[42]: segfault (11) at 50 nip 12d03a920 lr 12d03a91c code 1 in busybox[12cfd0000+100000]

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1835]
last night's run of mainline had a segfault in userspace on ppc

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/4689098432/jobs/8311496577#step:5:484

**Comment by nathanchance** [comment]
Also #1833.
