### ISSUE TITLE
Linux boot testing using Qemu

### ISSUE THREAD

**Issue by agners** [ClangBuiltLinux/linux#184]
Guenter Roeck maintains a git repository with scripts to launch Qemu and minimal initramfs for various architectures. This can be helpful to check whether LLVM/Clang builds actually work:

https://github.com/groeck/linux-build-test

**Comment by tpimh** [comment]
I also used qemu to boot test my builds (x86_64 only for now), but nothing fancy. Maybe we can make good CI with these scripts. Can we use Travis for the purpose?

**Comment by nickdesaulniers** [comment]
Also, I met with Guenter in person to discuss those scripts and other ideas for testing.  Going to roll this bug into #2 , though we should look into CI as well.
