### ISSUE TITLE
boot failure w/ clang-13 KCSAN mainline

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1840]
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/4786226259/jobs/8511005589#logs

**Comment by nathanchance** [comment]
I think this is a transient failure, it does not reappear on a re-run with the same kernel image :/

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/4786226259/jobs/8516267386

**Comment by nickdesaulniers** [comment]
ok, let's reopen if we observe this again.
