### ISSUE TITLE
boot failure mainline llvm-12 x86_64 UBSAN

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1841]
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/4789674197/jobs/8519215758#step:5:431

**Comment by nathanchance** [comment]
Re-running the job does not show the same problem:

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/4789674197/jobs/8522384887

It is probably a similar, non-deterministic issue like #1840 and #1702 from some time ago. I do not see it locally with or without KVM either.

**Comment by nickdesaulniers** [comment]
hmm...non-determinism or haunted AF compiler...
