### ISSUE TITLE
New instances of -Wbuiltin-macro-redefined after LLVM commit 0123deb3a6f0

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1855]
https://github.com/llvm/llvm-project/commit/0123deb3a6f0a83095287f51b07c77b7b43ab847

I have started an upstream discussion around this: https://reviews.llvm.org/D144654#4376428

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D151741 might fix this?

**Comment by nathanchance** [comment]
I am currently testing [D151741](https://reviews.llvm.org/D151741) and the `ARCH=arm` warnings have already disappeared, so I do expect that change to resolve this issue.

**Comment by nickdesaulniers** [comment]
Fixed: https://reviews.llvm.org/rG844e9534c6d99ddb6bada740839760fa24d17cb6
