### ISSUE TITLE
arm64 big endian broken in vDSO after LLVM commit d81ce04587c00

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1859]
After LLVM commit https://github.com/llvm/llvm-project/commit/d81ce04587c006b6731198956c522c93d0df1050, arm64 big endian fails to build:

```
# Turn on CONFIG_CPU_BIG_ENDIAN in menuconfig
$ make -skj"$(nproc)" ARCH=arm LLVM=1 O=build mrproper virtconfig menuconfig arch/arm64/kernel/vdso/
...
clang: error: unsupported option '-mbig-endian' for target 'x86_64-pc-linux-gnu'
make[3]: *** [.../scripts/Makefile.build:387: arch/arm64/kernel/vdso/vdso.lds] Error 1
...
```

arm64 adds `-mbig-endian` and `-mlittle-endian` to `KBUILD_CPPFLAGS` but `--target` is only added to `KBUILD_CFLAGS` and `KBUILD_AFLAGS`, so `-mbig-endian` is present when preprocessing `arch/arm64/kernel/vdso/vdso.lds.S` but `--target` is not.

A quick fix would be something like:

```diff
diff --git a/arch/arm64/kernel/vdso/Makefile b/arch/arm64/kernel/vdso/Makefile
index fe7a53c6781f..cceff7ea30a9 100644
--- a/arch/arm64/kernel/vdso/Makefile
+++ b/arch/arm64/kernel/vdso/Makefile
@@ -56,7 +56,7 @@ endif
 GCOV_PROFILE := n

 targets += vdso.lds
-CPPFLAGS_vdso.lds += -P -C -U$(ARCH)
+CPPFLAGS_vdso.lds += $(CLANG_FLAGS) -P -C -U$(ARCH)

 # Link rule for the .so file, .lds has to be first
 $(obj)/vdso.so.dbg: $(obj)/vdso.lds $(obj-vdso) FORCE
```

The proper fix is to move `--target` to `KBUILD_CPPFLAGS` as well so that this is fixed everywhere, which Masahiro did [send a patch to do](https://lore.kernel.org/20230409145358.2538266-1-masahiroy@kernel.org/) but there was a [new build failure](https://lore.kernel.org/202304100319.Wfcfuyqz-lkp@intel.com/) with it applied that it does not look like ever got commented on or resolved. I will see if I can look into that soon.

**Comment by nathanchance** [comment]
Masahiro picked up his patch: https://git.kernel.org/masahiroy/linux-kbuild/c/feb843a469fb0ab00d2d23cfb9bcc379791011bb

I am not sure this will make 6.4 because it is in the `kbuild` branch but we will already need backports back to 4.14 for this, so I do not think that it is that big of a deal.

**Comment by nickdesaulniers** [comment]
I guess we'll need to track the fixups then for 4.14+, too?

**Comment by nathanchance** [comment]
Right, I will handle those when they are all in mainline.

**Comment by nathanchance** [comment]
Fix is now in mainline: https://git.kernel.org/linus/feb843a469fb0ab00d2d23cfb9bcc379791011bb

I have requested stable backports here: https://lore.kernel.org/20230703150339.GA1975402@dev-arch.thelio-3990X/

For some reason, they are not required for 6.1 and older (maybe kbuild refactoring made this visible in 6.2+?).

Closing this up for now.
