### ISSUE TITLE
modpost warnings create_kpti_ng_temp_pgd -> early_pgtable_alloc

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1864]
[full](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/5155374350/jobs/9285928779#step:5:175) and [thinlto](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/5155374350/jobs/9285929535#step:5:181) arm64 are reporting (on mainline):
```
WARNING: modpost: vmlinux.o: section mismatch in reference: create_kpti_ng_temp_pgd (section: .text.create_kpti_ng_temp_pgd.23) -> early_pgtable_alloc (section: .init.text)
```
I don't see this in just the [defconfig](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/5155374350/jobs/9285928271)

**Comment by nathanchance** [comment]
That's #1838, I guess the warning now references the alias function?
