### ISSUE TITLE
RISC-V '.got' linker orphan warning after LLVM commit a178ba9fbd0a

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1865]
After https://github.com/llvm/llvm-project/commit/a178ba9fbd0a27057dc2fa4cb53c76caa013caac, I see the following when building `ARCH=riscv defconfig` on 6.3, which has [support for `CONFIG_LD_ORPHAN_WARN=y`](https://git.kernel.org/linus/f4b71bff8d8580eaaf56ec6c5305542a3d3a04bd) without handling of the `.got` in `arch/riscv/kernel/vmlinux.lds.S` which was added by [39b33072941f](https://git.kernel.org/linus/39b33072941f8bab82aa2c802044062385a046bf) and made unconditional in [26e7aacb83df](https://git.kernel.org/linus/26e7aacb83dfd04330673c5c9ac336560da52bb3) in 6.4-rc1:

```
$ make -skj"$(nproc)" ARCH=riscv LLVM=1 mrproper defconfig vmlinux
ld.lld: warning: <internal>:(.got) is being placed in '.got'
ld.lld: warning: <internal>:(.got) is being placed in '.got'
ld.lld: warning: <internal>:(.got) is being placed in '.got'
```

Neither of those changes seem suitable for stable. I think sending a `linux-6.3.y` only patch is the best move here, with the following diff:

```
diff --git a/arch/riscv/kernel/vmlinux.lds.S b/arch/riscv/kernel/vmlinux.lds.S
index 53a8ad65b255..db56c38f0e19 100644
--- a/arch/riscv/kernel/vmlinux.lds.S
+++ b/arch/riscv/kernel/vmlinux.lds.S
@@ -129,6 +129,8 @@ SECTIONS
                *(.sdata*)
        }

+       .got : { *(.got*) }
+
 #ifdef CONFIG_EFI
        .pecoff_edata_padding : { BYTE(0); . = ALIGN(PECOFF_FILE_ALIGNMENT); }
        __pecoff_data_raw_size = ABSOLUTE(. - __pecoff_text_end);
```

I will do this Monday unless someone wants to beat me to it.

cc @palmer-dabbelt @ConchuOD, just an FYI in case you see this too.

**Comment by ConchuOD** [comment]
@nathanchance Yeah, maybe I've just been an eejit about it - I saw that it was fixed in linux-next ages ago and figured it'd been explicitly fixed in the kbuild tree or something...

**Comment by nathanchance** [comment]
https://lore.kernel.org/20230605-6-3-riscv-got-orphan-warning-llvm-17-v1-1-72c4f11e020f@kernel.org/

**Comment by nathanchance** [comment]
This is now in review for 6.3, so I am going to close this up, since it will be in 6.3.7: https://lore.kernel.org/20230607200932.590767678@linuxfoundation.org/
