### ISSUE TITLE
-Wparentheses-equality in arch/x86/kernel/cpu/amd.c

### ISSUE THREAD

**Issue by bulwahn** [ClangBuiltLinux/linux#187]
```
arch/x86/kernel/cpu/amd.c:925:14: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
        if ((c->x86 == 6)) {
             ~~~~~~~^~~~
arch/x86/kernel/cpu/amd.c:925:14: note: remove extraneous parentheses around the comparison to silence this warning
        if ((c->x86 == 6)) {
            ~       ^   ~
arch/x86/kernel/cpu/amd.c:925:14: note: use '=' to turn this equality comparison into an assignment
        if ((c->x86 == 6)) {
                    ^~
                    =
```

The warning is reported when compiling allnoconfig and tinyconfig. That warning should be easy to fix.

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20181002224511.14929-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=88296bd42b4e9d24e138a68b337c235b5cac89a7

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=88296bd42b4e9d24e138a68b337c235b5cac89a7
