### ISSUE TITLE
Tracking issue for CONFIG_RELOCATABLE on LoongArch

### ISSUE THREAD

**Issue by xen0n** [ClangBuiltLinux/linux#1883]
Follow-up issue for #1787.

Currently one cannot build a working kernel with `CONFIG_RELOCATABLE=y` and with Clang/LLD, both because of attempts to take cross-section address differences, and LLD reportedly not writing the pre-relocated values in GOT (reported by @heiher). This issue tracks the work towards enabling relocatable LoongArch kernels.

**Comment by heiher** [comment]
Fixed: https://lore.kernel.org/loongarch/20231116130331.241395-1-wangrui@loongson.cn/

**Comment by nathanchance** [comment]
Accepted: https://git.kernel.org/chenhuacai/linux-loongson/c/aa0cbc1b506b090c3a775b547c693ada108cc0d7

Hash may change, I'll close this when it reaches Linus's tree.

**Comment by xen0n** [comment]
This is already mainlined since v6.7-rc3, and the commit hash didn't change: https://github.com/torvalds/linux/commit/aa0cbc1b506b090c3a775b547c693ada108cc0d7

Please feel free to label the issue as resolved, and I'll just close it now. Thanks to everyone involved!
