### ISSUE TITLE
Tracking issue for CONFIG_MODULES on LoongArch

### ISSUE THREAD

**Issue by xen0n** [ClangBuiltLinux/linux#1884]
Follow-up issue for #1787.

Currently one cannot build a working kernel with `CONFIG_MODULES=y` and with Clang/LLD, because of missing Clang support for `__attribute__((model("extreme")))`. This issue tracks the work towards support for said attribute and enabling modular LoongArch kernel builds.

Implementing this may require deep plumbing inside LLVM/Clang (straight down to LLVM IR-level addition), per [the recent discussion](https://discourse.llvm.org/t/how-to-best-implement-code-model-overriding-for-certain-values/71816), and I expect the relevant changes to hit LLVM 18 (LLVM 17 will branch later this month so it's probably not good to rush an LLVM IR change into it).

**Comment by heiher** [comment]
[[RFC] Add per-global code model attribute](https://discourse.llvm.org/t/rfc-add-per-global-code-model-attribute/74944)

**Comment by nathanchance** [comment]
Is the plan for Linux to use the `large` code model attribute instead of `extreme` or will there be a follow up commit to add `extreme` for the kernel later?

**Comment by heiher** [comment]
> Is the plan for Linux to use the `large` code model attribute instead of `extreme` or will there be a follow up commit to add `extreme` for the kernel later?

https://github.com/heiher/linux/commit/e540e0ffdef4bced95c9115debc26276f0dff3f8

Perhaps there could be aliases to eliminate differences.

**Comment by xen0n** [comment]
> > Is the plan for Linux to use the `large` code model attribute instead of `extreme` or will there be a follow up commit to add `extreme` for the kernel later?
> 
> https://github.com/heiher/linux/commit/e540e0ffdef4bced95c9115debc26276f0dff3f8
> 
> Perhaps there could be aliases to eliminate differences.

Yeah I'd suggest adding support for `model("extreme")` as alias of `large` in the LoongArch Clang frontend (if that's the proper way to go).

**Comment by heiher** [comment]
Fixed by:
https://github.com/llvm/llvm-project/pull/72077
https://github.com/llvm/llvm-project/pull/72078
https://github.com/llvm/llvm-project/pull/72079

**Comment by nathanchance** [comment]
Indeed, I can confirm that with ToT LLVM, we are now able to build and boot `ARCH=loongarch defconfig` without disabling any configurations :)

I wonder if we can deal with https://github.com/ClangBuiltLinux/linux/issues/1941 now by setting the minimum supported version of `clang` for `ARCH=loongarch` to `18.0.0`?

**Comment by xen0n** [comment]
> Indeed, I can confirm that with ToT LLVM, we are now able to build and boot `ARCH=loongarch defconfig` without disabling any configurations :)
> 
> I wonder if we can deal with https://github.com/ClangBuiltLinux/linux/issues/1941 now by setting the minimum supported version of `clang` for `ARCH=loongarch` to `18.0.0`?

Yeah I think so, as all that Huacai asked for is working `defconfig` builds, which we just achieved before the LLVM 18 code freeze.
