### ISSUE TITLE
"error: initializer element is not constant" in drivers/regulator/max77857-regulator.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1889]
```
drivers/regulator/max77857-regulator.c:312:16: error: initializer element is not a compile-time constant
  312 |         .ramp_delay = max77857_ramp_table[0][0],
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Reported upstream: https://lore.kernel.org/20230718155502.GA3542993@dev-arch.thelio-3990X/

**Comment by nathanchance** [comment]
https://reviews.llvm.org/D151587 + https://reviews.llvm.org/D76096 resolves this (i.e., makes `clang` match the behavior of GCC 8 and newer), but the kernel code should still be adjusted for older toolchains.

**Comment by nickdesaulniers** [comment]
The first patch landed in release/17.x, the second I just landed in main (clang-18). I've [requested a backport](https://github.com/llvm/llvm-project/issues/44502#issuecomment-1663065980) for clang-17 though.

EDIT: seems like the author hasn't followed up with a fix yet.

**Comment by nathanchance** [comment]
https://git.kernel.org/broonie/regulator/c/93083725e1ed86c07ea9846bb573b9340985853f

**Comment by nickdesaulniers** [comment]
backport picked up to clang-17: https://github.com/llvm/llvm-project-release-prs/commit/0b2d5b967d98375793897295d651f58f6fbd3034

**Comment by nickdesaulniers** [comment]
This issue never hit mainline.
