### ISSUE TITLE
"error: cannot jump from this indirect goto statement to one of its possible targets" in drivers/gpu/drm/tests/drm_exec_test.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1890]
After https://github.com/llvm/llvm-project/commit/20219106060208f0c2f5d096eb3aed7b712f5067 (the reland of the patch that exposed #1887), I see what appears to be a legitimate error in -next:

```
drivers/gpu/drm/tests/drm_exec_test.c:41:3: error: cannot jump from this indirect goto statement to one of its possible targets
   41 |                 drm_exec_retry_on_contention(&exec);
      |                 ^
include/drm/drm_exec.h:96:4: note: expanded from macro 'drm_exec_retry_on_contention'
   96 |                         goto *__drm_exec_retry_ptr;             \
      |                         ^
drivers/gpu/drm/tests/drm_exec_test.c:39:2: note: possible target of indirect goto statement
   39 |         drm_exec_until_all_locked(&exec) {
      |         ^
include/drm/drm_exec.h:79:33: note: expanded from macro 'drm_exec_until_all_locked'
   79 |                 __label__ __drm_exec_retry;                     \
      |                                                                 ^
drivers/gpu/drm/tests/drm_exec_test.c:39:2: note: jump enters a statement expression
```

https://git.kernel.org/next/linux-next/c/09593216bff15866f95c8ad406cb7fdcec1ee40a
https://git.kernel.org/next/linux-next/c/9710631cc8f367da04879760b892a8fc7aac9f45

I brought this up on Phabricator in case something with the error should be changed but I think the kernel is doing something that is documented as explicit undefined behavior according to [GCC's documentation](https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html):

> Jumping into a statement expression with a computed goto (see [Labels as Values](https://gcc.gnu.org/onlinedocs/gcc/Labels-as-Values.html)) has undefined behavior.

So it seems legitimate for clang to error on it and if that is indeed the case, I will bring it up on the upstream thread to see how the code can be reworked to avoid this undefined behavior.

**Comment by nathanchance** [comment]
Report send upstream to the kernel developer who wrote this code: https://lore.kernel.org/20230722220637.GA138486@dev-arch.thelio-3990X/

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/lkml/20230727-amdgpu-v2-1-7fc66bc52bf6@google.com/

**Comment by nathanchance** [comment]
Alternative fix: https://lore.kernel.org/20230731123625.3766-1-christian.koenig@amd.com/

**Comment by nathanchance** [comment]
https://cgit.freedesktop.org/drm/drm-misc/commit/?id=616bceae250d0bab7ab2cbcb0791d820434ffb71
