### ISSUE TITLE
-Wconstant-conversion in lib/test_scanf.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1899]
After https://github.com/llvm/llvm-project/commit/610ec954e1f81c0e8fcadedcd25afe643f5a094e, I see:

```
lib/test_scanf.c:661:2: warning: implicit conversion from 'int' to 'unsigned char' changes value from -168 to 88 [-Wconstant-conversion]
  661 |         test_number_prefix(unsigned char,       "0xA7", "%2hhx%hhx", 0, 0xa7, 2, check_uchar);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/test_scanf.c:609:29: note: expanded from macro 'test_number_prefix'
  609 |         T result[2] = {~expect[0], ~expect[1]};                                 \
      |                       ~            ^~~~~~~~~~
1 warning generated.
```

Patch submitted: https://lore.kernel.org/20230803-test_scanf-wconstant-conversion-v1-1-74da994dedbc@kernel.org/

**Comment by nickdesaulniers** [comment]
v2: https://lore.kernel.org/20230807-test_scanf-wconstant-conversion-v2-1-839ca39083e1@kernel.org/
cc @DavidSpickett

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/printk/c/92382d744176f230101d54f5c017bccd62770f01

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/92382d744176f230101d54f5c017bccd62770f01

It has a stable tag so it should be backported automatically after the merge window closes.
