### ISSUE TITLE
CFI violation when reading amd_pstate/status

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1901]
cc @nathanchance @samitolvanen 

via: https://bugzilla.kernel.org/show_bug.cgi?id=217765

`Reported-by: Jannik Glückert <jannik.glueckert@gmail.com>`

**Comment by nathanchance** [comment]
https://lore.kernel.org/20230807-amd-pstate-cfi-v1-1-0263daa13bc3@weissschuh.net/

**Comment by nathanchance** [comment]
https://git.kernel.org/rafael/linux-pm/c/5e720f8c8c9d959283c3908bbf32a91a01a86547

**Comment by nathanchance** [comment]
https://git.kernel.org/linus/5e720f8c8c9d959283c3908bbf32a91a01a86547
