### ISSUE TITLE
[SRSO] ld.lld fails with "at least one side of the expression must be absolute" after SRSO mitigation

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1907]
After https://git.kernel.org/linus/fb3bd914b3ec28f5fb697ac55c4846ac2d542855, x86_64 builds fail to link with:

```
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:210: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:211: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:210: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:211: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:210: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:211: at least one side of the expression must be absolute
```

With LTO enabled, I additionally see:

```
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:35: unable to move location counter backward for: .text
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:210: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:211: at least one side of the expression must be absolute
ld.lld: error: SRSO function pair won't alias
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:35: unable to move location counter backward for: .text
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:210: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:211: at least one side of the expression must be absolute
ld.lld: error: SRSO function pair won't alias
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:35: unable to move location counter backward for: .text
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:210: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:211: at least one side of the expression must be absolute
ld.lld: error: SRSO function pair won't alias
```

The linker script is https://gist.github.com/nathanchance/1c57035608e9363b3c11a1d8a781c558, as the line numbers correspond to the preprocessed source.

**Comment by nickdesaulniers** [comment]
cc @MaskRay

**Comment by nickdesaulniers** [comment]
At least for defconfig:
```diff
diff --git a/arch/x86/kernel/vmlinux.lds.S b/arch/x86/kernel/vmlinux.lds.S
index e76813230192..2556ebb7aa6f 100644
--- a/arch/x86/kernel/vmlinux.lds.S
+++ b/arch/x86/kernel/vmlinux.lds.S
@@ -531,10 +531,14 @@ INIT_PER_CPU(irq_stack_backing_store);
 /*
  * GNU ld cannot do XOR so do: (A | B) - (A & B) in order to compute the XOR
  * of the two function addresses:
+ *
+ * LLVM lld cannot evaluate this expression.
  */
+#ifdef CONFIG_LD_IS_BFD
 . = ASSERT(((srso_untrain_ret_alias | srso_safe_ret_alias) -
                (srso_untrain_ret_alias & srso_safe_ret_alias)) == ((1 << 2) | (1 << 8) | (1 << 14) | (1 << 20)),
                "SRSO function pair won't alias");
 #endif
+#endif
 
 #endif /* CONFIG_X86_64 */
```

**Comment by nickdesaulniers** [comment]
Perhaps this for LTO:
```diff
diff --git a/arch/x86/kernel/vmlinux.lds.S b/arch/x86/kernel/vmlinux.lds.S
index e76813230192..8a080d5be1ee 100644
--- a/arch/x86/kernel/vmlinux.lds.S
+++ b/arch/x86/kernel/vmlinux.lds.S
@@ -152,7 +152,7 @@ SECTIONS
                 * See the comment above srso_untrain_ret_alias()'s
                 * definition.
                 */
-               . = srso_untrain_ret_alias | (1 << 2) | (1 << 8) | (1 << 14) | (1 << 20);
+               ALIGN(srso_untrain_ret_alias | 0x104104);
                *(.text.__x86.rethunk_safe)
 #endif
                ALIGN_ENTRY_TEXT_END
```

**Comment by nickdesaulniers** [comment]
Edit: looks like we need to keep a specific distance (of 0x104104 B) between these two symbols:
```
$ llvm-readelf -s vmlinux | grep -e ' srso_safe_ret_alias' -e ' srso_untrain_ret_alias'
132516: ffffffff82001fdb     6 FUNC    GLOBAL DEFAULT     1 srso_safe_ret_alias
132991: ffffffff82000000    10 FUNC    GLOBAL DEFAULT     1 srso_untrain_ret_alias
```

**Comment by nickdesaulniers** [comment]
Boris on IRC says:
```
113499: ffffffff81d04104     6 FUNC    GLOBAL DEFAULT    1 srso_safe_ret_alias
148347: ffffffff81c00000    10 FUNC    GLOBAL DEFAULT    1 srso_untrain_ret_alias
```
is what's expected. I suspect that `. = srso_untrain_ret_alias | (1 << 2) | (1 << 8) | (1 << 14) | (1 << 20);` is trying to place `srso_safe_ret_alias` `0x104104` bytes after `srso_untrain_ret_alias`.

**Comment by nickdesaulniers** [comment]
I think we can do the padding in assembler.

Or rather than deal with symbols in the linker script, I think `srso_safe_ret_alias` is in its own section (`.text.__x86.rethunk_safe`) and so is `srso_untrain_ret_alias` (`.text.__x86.rethunk_untrain`).  Maybe it's easier to specify alignment between these two sections in linkerscript.

**Comment by nickdesaulniers** [comment]
```diff
diff --git a/arch/x86/kernel/vmlinux.lds.S b/arch/x86/kernel/vmlinux.lds.S
index e76813230192..d6ecdf6e69bb 100644
--- a/arch/x86/kernel/vmlinux.lds.S
+++ b/arch/x86/kernel/vmlinux.lds.S
@@ -152,7 +152,7 @@ SECTIONS
                 * See the comment above srso_untrain_ret_alias()'s
                 * definition.
                 */
-               . = srso_untrain_ret_alias | (1 << 2) | (1 << 8) | (1 << 14) | (1 << 20);
+               . = srso_untrain_ret_alias + (1 << 2) | (1 << 8) | (1 << 14) | (1 << 20);
                *(.text.__x86.rethunk_safe)
 #endif
                ALIGN_ENTRY_TEXT_END
@@ -532,9 +532,14 @@ INIT_PER_CPU(irq_stack_backing_store);
  * GNU ld cannot do XOR so do: (A | B) - (A & B) in order to compute the XOR
  * of the two function addresses:
  */
+#ifdef CONFIG_LD_IS_BFD
 . = ASSERT(((srso_untrain_ret_alias | srso_safe_ret_alias) -
                (srso_untrain_ret_alias & srso_safe_ret_alias)) == ((1 << 2) | (1 << 8) | (1 << 14) | (1 << 20)),
                "SRSO function pair won't alias");
+#else
+. = ASSERT(srso_untrain_ret_alias ^ srso_safe_ret_alias == ((1 << 2) | (1 << 8) | (1 << 14) | (1 << 20)),
+               "SRSO function pair won't alias");
+#endif
 #endif
 
 #endif /* CONFIG_X86_64 */
```

**Comment by nickdesaulniers** [comment]
I'm thinking this might work. `0x104104` is the magic constant `((1 << 2) | (1 << 8) | (1 << 14) | (1 << 20))`. I don't yet understand why `0x14` is necessary (some kind of function or symbol alignment, perhaps).
```diff
diff --git a/arch/x86/kernel/vmlinux.lds.S b/arch/x86/kernel/vmlinux.lds.S
index e76813230192..4715c7a4cc31 100644
--- a/arch/x86/kernel/vmlinux.lds.S
+++ b/arch/x86/kernel/vmlinux.lds.S
@@ -146,15 +146,6 @@ SECTIONS
 #endif
 
                ENTRY_TEXT
-
-#ifdef CONFIG_CPU_SRSO
-               /*
-                * See the comment above srso_untrain_ret_alias()'s
-                * definition.
-                */
-               . = srso_untrain_ret_alias | (1 << 2) | (1 << 8) | (1 << 14) | (1 << 20);
-               *(.text.__x86.rethunk_safe)
-#endif
                ALIGN_ENTRY_TEXT_END
                *(.gnu.warning)

 @@ -532,9 +523,14 @@ INIT_PER_CPU(irq_stack_backing_store);
  * GNU ld cannot do XOR so do: (A | B) - (A & B) in order to compute the XOR
  * of the two function addresses:
  */
+#ifdef CONFIG_LD_IS_BFD
 . = ASSERT(((srso_untrain_ret_alias | srso_safe_ret_alias) -
                (srso_untrain_ret_alias & srso_safe_ret_alias)) == ((1 << 2) | (1 << 8) | (1 << 14) | (1 << 20)),
                "SRSO function pair won't alias");
+#else
+. = ASSERT(srso_untrain_ret_alias ^ srso_safe_ret_alias == ((1 << 2) | (1 << 8) | (1 << 14) | (1 << 20)),
+               "SRSO function pair won't alias");
+#endif
 #endif
 
 #endif /* CONFIG_X86_64 */
diff --git a/arch/x86/lib/retpoline.S b/arch/x86/lib/retpoline.S
index 2cff585f22f2..f1ae299db60b 100644
--- a/arch/x86/lib/retpoline.S
+++ b/arch/x86/lib/retpoline.S
@@ -157,8 +157,7 @@ SYM_START(srso_untrain_ret_alias, SYM_L_GLOBAL, SYM_A_NONE)
        jmp __x86_return_thunk
 SYM_FUNC_END(srso_untrain_ret_alias)
 __EXPORT_THUNK(srso_untrain_ret_alias)
-
-       .section .text.__x86.rethunk_safe
+.fill (. - srso_untrain_ret_alias + 0x104104 - 0x14), 1, 0xcc
 #endif
 
 /* Needs a definition for the __x86_return_thunk alternative below. */
```
The idea is rather than try to have the linker place one section relative to another, have the assembler place the symbols a specific distance apart.

**Comment by nickdesaulniers** [comment]
https://github.com/ClangBuiltLinux/linux/issues/1907#issuecomment-1670475621 works for me, boots, and is 0x104104 apart in both cases.

Besides fixing those awful hex magic constants, another concern is this comment:
arch/x86/lib/retpoline.S:139
```
139  * - srso_untrain_ret_alias() is 2M aligned                                     
```

uh, under defconfig maybe, but under CONFIG_LTO_CLANG_THIN=y I don't think so.

```
$ llvm-readelf -s vmlinux | grep -e ' srso_safe_ret_alias' -e ' srso_untrain_ret_alias'
159108: ffffffff81109444     6 FUNC    GLOBAL DEFAULT     1 srso_safe_ret_alias
159475: ffffffff81005340    10 FUNC    GLOBAL DEFAULT     1 srso_untrain_ret_alias
```

Also, `SYM_START(srso_safe_ret_alias, SYM_L_GLOBAL, SYM_A_NONE)` -> `SYM_FUNC_START_NOALIGN(srso_safe_ret_alias)`

By grace of god that works for gcc 12.2 and binutils 2.40.

@sinkap is reporting that maybe isn't working for older releases of lld though.  I checked out release/11.x and built lld, and could reproduce:
```
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:195: , expected, but got ^
>>> . = ASSERT(srso_untrain_ret_alias ^ srso_safe_ret_alias == ((1 << 2) | (1 << 8) | (1 << 14) | (1 << 20)),
>>>                                   
```
I'll need to bisect lld to see when this starts working.

Another problem with my approach is that I suspect the original patch is trying to keep `srso_safe_ret_alias` on one side of `ENTRY_TEXT`; if `ENTRY_TEXT` is larger than `.text.__x86.rethunk_untrain` + `0x104104` that seems like a problem.

**Comment by q66** [comment]
i get the same error on lld 16:

```
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:190: , expected, but got ^
>>> . = ASSERT(srso_untrain_ret_alias ^ srso_safe_ret_alias == ((1 << 2) | (1 << 8) | (1 << 14) | (1 << 20)),
```

```
root@cbuild: ~$ ld.lld --version
LLD 16.0.6 (compatible with GNU linkers)
```

**Comment by thyrc** [comment]
Not sure if helps, but: The ^ and ^= operators where added in the release/17.x branch w/ https://github.com/llvm/llvm-project/commit/fae96104d4378166cbe5c875ef8ed808a356f3fb.

@nickdesaulniers: With your changes to retpoline.S do we really need to check for CONFIG_LD_IS_BFD? The original ASSERT() should still work, although with ABSOLUTE():
```
diff --git a/arch/x86/kernel/vmlinux.lds.S b/arch/x86/kernel/vmlinux.lds.S
index 8f06ab08f51e..d4c5040410de 100644
--- a/arch/x86/kernel/vmlinux.lds.S
+++ b/arch/x86/kernel/vmlinux.lds.S
@@ -509,8 +509,8 @@ INIT_PER_CPU(irq_stack_backing_store);
  * GNU ld cannot do XOR so do: (A | B) - (A & B) in order to compute the XOR
  * of the two function addresses:
  */
-. = ASSERT(((srso_untrain_ret_alias | srso_safe_ret_alias) -
-		(srso_untrain_ret_alias & srso_safe_ret_alias)) == ((1 << 2) | (1 << 8) | (1 << 14) | (1 << 20)),
+. = ASSERT(((ABSOLUTE(srso_untrain_ret_alias) | srso_safe_ret_alias) -
+		(ABSOLUTE(srso_untrain_ret_alias) & srso_safe_ret_alias)) == ((1 << 2) | (1 << 8) | (1 << 14) | (1 << 20)),
 		"SRSO function pair won't alias");
 #endif
```

I got
```
$ llvm-readelf -s vmlinux |grep -e ' srso_safe_ret_alias' -e ' srso_untrain_ret_alias'
129233: ffffffff8108ae60    10 FUNC    GLOBAL DEFAULT     1 srso_untrain_ret_alias
135137: ffffffff8118ef64     6 FUNC    GLOBAL DEFAULT     1 srso_safe_ret_alias
```

Edit: Insert diff

**Comment by q66** [comment]
there is also a large patchset overhauling this code: https://lore.kernel.org/lkml/20230809071218.000335006@infradead.org/

besides other things this removes `CONFIG_CPU_SRSO` entirely, i wonder what effect it has on the build

**Comment by nickdesaulniers** [comment]
>> @sinkap is reporting that maybe isn't working for older releases of lld though. I checked out release/11.x and built lld, and could reproduce:

> Not sure if helps, but: The ^ and ^= operators where added in the release/17.x branch w/ https://github.com/llvm/llvm-project/commit/fae96104d4378166cbe5c875ef8ed808a356f3fb.

Yes, thank you; you've saved me a bisection.

> @nickdesaulniers: With your changes to retpoline.S do we really need to check for CONFIG_LD_IS_BFD? The original ASSERT() should still work, although with ABSOLUTE():

Ah, nice!  That BFD condition is itself a workaround since (as the commit you linked to points out) BFD only gained xor support very very recently.

> there is also a large patchset overhauling this code: https://lore.kernel.org/lkml/20230809071218.000335006@infradead.org/

Good find. I'll keep an eye on how that's progressing to see if we need something to land sooner than that.

**Comment by nathanchance** [comment]
> > there is also a large patchset overhauling this code: https://lore.kernel.org/lkml/20230809071218.000335006@infradead.org/
> 
> Good find. I'll keep an eye on how that's progressing to see if we need something to land sooner than that.

I browsed that series and I don't see how this issue would disappear, the code in `arch/x86/kernel/vmlinux.lds.S` is largely untouched from what I can tell.

For the record, our matrix will go super red, as stable released the patches at the same time as mainline.

**Comment by nathanchance** [comment]
I was not able to apply that series with `b4 shazam` for some reason, patch 11 does not apply cleanly... but I was able to grab it from [Peter's repo](https://git.kernel.org/pub/scm/linux/kernel/git/peterz/queue.git/log/?h=x86/srso) and yeah, this issue is still present:

```
$ make -skj"$(nproc)" ARCH=x86_64 LLVM=1 defconfig vmlinux
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:203: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:204: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:203: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:204: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:203: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:204: at least one side of the expression must be absolute

# Turn on CONFIG_LTO_CLANG_THIN in menuconfig
$ make -skj"$(nproc)" ARCH=x86_64 LLVM=1 defconfig menuconfig vmlinux
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:35: unable to move location counter backward for: .text
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:203: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:204: at least one side of the expression must be absolute
ld.lld: error: SRSO function pair won't alias
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:35: unable to move location counter backward for: .text
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:203: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:204: at least one side of the expression must be absolute
ld.lld: error: SRSO function pair won't alias
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:35: unable to move location counter backward for: .text
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:203: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:204: at least one side of the expression must be absolute
ld.lld: error: SRSO function pair won't alias
```

**Comment by nickdesaulniers** [comment]
Ok, I'm going to package up @thyrc 's [suggestion](https://github.com/ClangBuiltLinux/linux/issues/1907#issuecomment-1671179915) and send it.  Will work on LTO separately.

@thyrc 's what's your email address for a suggested-by tag?

**Comment by nickdesaulniers** [comment]
Sent https://lore.kernel.org/lkml/20230809-gds-v1-1-eaac90b0cbcc@google.com/ to unbreak defconfig for now. Thanks all for the support, recommendations, support, etc.. :)

**Comment by nathanchance** [comment]
Feel free to split this issue up if it makes sense to track the LTO issue separately.

**Comment by nickdesaulniers** [comment]
Done #1909

**Comment by torvic9** [comment]
~~With Nick's patch mentioned above, I can build and run a 6.4.9 kernel with clang-16 and ThinLTO.~~

**EDIT**

Please disregard the above, I mistakenly built with the wrong config which had SRSO disabled.
With it enabled, I do run into the LTO problem.

**Comment by xdevs23** [comment]
I can confirm this happens for 6.4.9 which really confused me and I thought my system was broken because I've never seen these errors before.

LTO is enabled and this is the output:

```
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:35: unable to move location counter backward for: .text            
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:211: at least one side of the expression must be absolute          
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:210: at least one side of the expression must be absolute          
ld.lld: error: SRSO function pair won't alias                                                                   
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:35: unable to move location counter backward for: .text            
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:211: at least one side of the expression must be absolute          
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:210: at least one side of the expression must be absolute          
ld.lld: error: SRSO function pair won't alias                                                                   
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:35: unable to move location counter backward for: .text            
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:211: at least one side of the expression must be absolute          
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:210: at least one side of the expression must be absolute          
ld.lld: error: SRSO function pair won't alias 
```

Clang version:

```
clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

I guess I can just pick the patch for now.

**EDIT**:

As said before, this won't fix the LTO issue but the errors are reduced:

```
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:35: unable to move location counter backward for: .text
ld.lld: error: SRSO function pair won't alias
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:35: unable to move location counter backward for: .text
ld.lld: error: SRSO function pair won't alias
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:35: unable to move location counter backward for: .text
ld.lld: error: SRSO function pair won't alias
```

**Comment by nickdesaulniers** [comment]
> I guess I can just pick the patch for now.

You'll either need to disable LTO and pick up [the patch](https://lore.kernel.org/lkml/20230809-gds-v1-1-eaac90b0cbcc@google.com/) or disable LTO and SRSO mitigations (until #1909 is solved).

**Comment by autogris** [comment]
Building 

> > I guess I can just pick the patch for now.
> 
> You'll either need to disable LTO and pick up [the patch](https://lore.kernel.org/lkml/20230809-gds-v1-1-eaac90b0cbcc@google.com/) or disable LTO and SRSO mitigations (until #1909 is solved).

Building 6.1.44 from Slackware-current scripts, with this patch, throws the following error on dmesg (though no abnormal system behavior noticed so far):

```
------------[ cut here ]------------
 missing return thunk: __ret+0x5/0x7e-__ret+0x0/0x7e: e9 f6 ff ff ff
 WARNING: CPU: 0 PID: 0 at arch/x86/kernel/alternative.c:574 apply_returns+0x1c5/0x3b0
 Modules linked in:
 CPU: 0 PID: 0 Comm: swapper/0 Not tainted 6.1.44 #1
Hardware name: .....
 RIP: 0010:apply_returns+0x1c5/0x3b0
Code: ff ff 0f 0b e9 ac fe ff ff c6 05 52 aa 77 01 01 48 c7 c7 fd 68 44 a7 4c 89 fe 4c 89 ea b9 05 00 00 00 4d 89 f8 e8 ab 3b 07 00 <0f> 0b e9 84 fe ff ff c6 84 24 90 00 00 00 c3 44 0f b6 6c 24 6a 49
....
Call Trace:
  <TASK>
  ? __warn+0xcb/0x1c0
  ? apply_returns+0x1c5/0x3b0
  ? report_bug+0x175/0x220
  ? handle_bug+0x3d/0x80
  ? exc_invalid_op+0x16/0x50
  ? asm_exc_invalid_op+0x16/0x20
  ? __ret+0x5/0x7e
  ? zen_untrain_ret+0x1/0x1
  ? srso_safe_ret+0x20/0x20
  ? apply_returns+0x1c5/0x3b0
  ? __ret+0x5/0x7e
  ? __ret+0x14/0x7e
  ? __ret+0xa/0x7e
  alternative_instructions+0x48/0x104
  arch_cpu_finalize_init+0x37/0x70
  start_kernel+0x3b0/0x4e3
  secondary_startup_64_no_verify+0xd4/0xdb
  </TASK>
---[ end trace 0000000000000000 ]---
```

**Comment by nathanchance** [comment]
> Building 6.1.44 from Slackware-current scripts, with this patch, throws the following error on dmesg (though no abnormal system behavior noticed so far):
> 
> 
> 
> ```
> 
> ------------[ cut here ]------------
> 
>  missing return thunk: __ret+0x5/0x7e-__ret+0x0/0x7e: e9 f6 ff ff ff
> 
>  WARNING: CPU: 0 PID: 0 at arch/x86/kernel/alternative.c:574 apply_returns+0x1c5/0x3b0
> 
>  Modules linked in:
> 
>  CPU: 0 PID: 0 Comm: swapper/0 Not tainted 6.1.44 #1
> 
> Hardware name: .....
> 
>  RIP: 0010:apply_returns+0x1c5/0x3b0
> 
> Code: ff ff 0f 0b e9 ac fe ff ff c6 05 52 aa 77 01 01 48 c7 c7 fd 68 44 a7 4c 89 fe 4c 89 ea b9 05 00 00 00 4d 89 f8 e8 ab 3b 07 00 <0f> 0b e9 84 fe ff ff c6 84 24 90 00 00 00 c3 44 0f b6 6c 24 6a 49
> 
> ....
> 
> Call Trace:
> 
>   <TASK>
> 
>   ? __warn+0xcb/0x1c0
> 
>   ? apply_returns+0x1c5/0x3b0
> 
>   ? report_bug+0x175/0x220
> 
>   ? handle_bug+0x3d/0x80
> 
>   ? exc_invalid_op+0x16/0x50
> 
>   ? asm_exc_invalid_op+0x16/0x20
> 
>   ? __ret+0x5/0x7e
> 
>   ? zen_untrain_ret+0x1/0x1
> 
>   ? srso_safe_ret+0x20/0x20
> 
>   ? apply_returns+0x1c5/0x3b0
> 
>   ? __ret+0x5/0x7e
> 
>   ? __ret+0x14/0x7e
> 
>   ? __ret+0xa/0x7e
> 
>   alternative_instructions+0x48/0x104
> 
>   arch_cpu_finalize_init+0x37/0x70
> 
>   start_kernel+0x3b0/0x4e3
> 
>   secondary_startup_64_no_verify+0xd4/0xdb
> 
>   </TASK>
> 
> ---[ end trace 0000000000000000 ]---
> 
> ```

This is #1911.

To everyone in this thread, I have pushed https://github.com/ClangBuiltLinux/linux/commits/srso-fixes for further testing, the top two commits are the fixes for this issue and #1909.

**Comment by xdevs23** [comment]
> You'll either need to disable LTO and pick up [the patch](https://lore.kernel.org/lkml/20230809-gds-v1-1-eaac90b0cbcc@google.com/) or disable LTO and SRSO mitigations (until https://github.com/ClangBuiltLinux/linux/issues/1909 is solved).

I already picked it and for LTO I'll await the patch. Thanks.

**Comment by autogris** [comment]
> This is #1911.
> 
> To everyone in this thread, I have pushed https://github.com/ClangBuiltLinux/linux/commits/srso-fixes for further testing, the top two commits are the fixes for this issue and #1909.

That's strange, I've tried with both patches and with just the "vmlinux.lds.S" one and both produces this error. Did you solved this without disabling IAS?

**Comment by nathanchance** [comment]
> 
> 
> > This is #1911.
> 
> > 
> 
> > To everyone in this thread, I have pushed https://github.com/ClangBuiltLinux/linux/commits/srso-fixes for further testing, the top two commits are the fixes for this issue and #1909.
> 
> 
> 
> That's strange, I've tried with both patches and with just the "vmlinux.lds.S" one and both produces this error. Did you solved this without disabling IAS?

I suppose I should have been more clear. When I meant "this issue", I meant #1907, not #1911. #1911 stills need further investigation and has no patch currently, I was just saying it is a known problem that has its own issue.

**Comment by nathanchance** [comment]
Patch has been picked up: https://git.kernel.org/tip/cbe8ded48b939b9d55d2c5589ab56caa7b530709

**Comment by autogris** [comment]
> > > This is #1911.
> > 
> > 
> > > 
> > 
> > 
> > > To everyone in this thread, I have pushed https://github.com/ClangBuiltLinux/linux/commits/srso-fixes for further testing, the top two commits are the fixes for this issue and #1909.
> > 
> > 
> > That's strange, I've tried with both patches and with just the "vmlinux.lds.S" one and both produces this error. Did you solved this without disabling IAS?
> 
> I suppose I should have been more clear. When I meant "this issue", I meant #1907, not #1911. #1911 stills need further investigation and has no patch currently, I was just saying it is a known problem that has its own issue.

Sorry, my bad. Thanks!

**Comment by nickdesaulniers** [comment]
Boris plans to send the fix to Linus (mainline) tomorrow. (Sat Aug 12)

**Comment by nathanchance** [comment]
Patch now in mainline: https://git.kernel.org/linus/cbe8ded48b939b9d55d2c5589ab56caa7b530709

It has been picked up for all the affected stable trees, so I am closing this out for now.

https://git.kernel.org/stable/stable-queue/c/bf22d201b84af4a40b018306e33ad76ea3544ad6
https://git.kernel.org/stable/stable-queue/c/abaf223121e61bfa43bd1a6d01f8b58f1d3a8f0a
https://git.kernel.org/stable/stable-queue/c/709d94ea40074b4df7e5e64fde5407da36095f1c
https://git.kernel.org/stable/stable-queue/c/e77913f67089b011824bea9b9d025b24fc61c990
