### ISSUE TITLE
Promote -Wvoid-pointer-to-enum-cast from W=1

### ISSUE THREAD

**Issue by JustinStitt** [ClangBuiltLinux/linux#1910]
Let's try to enable this warning for non W=1 builds (is this W=0?).

I currently have patches for #1902, #1903 and #1904.

Has anyone ran some other builds across various configs and have some other instances of this warning appearing? @nathanchance perhaps?

**Comment by JustinStitt** [comment]
Also, I don't think I am able to add labels to new issues. So, sorry about the lack of labels here.

**Comment by nathanchance** [comment]
I have not done any recent builds with `-Wvoid-pointer-to-enum-cast` to see how clean the tree is. I can take your patches for the instances noted above and turn my matrix on it to see how many more instances there are at some point before the end of the week.

**Comment by JustinStitt** [comment]
> I have not done any recent builds with `-Wvoid-pointer-to-enum-cast` to see how clean the tree is. I can take your patches for the instances noted above and turn my matrix on it to see how many more instances there are at some point before the end of the week.

OK. Patches coming soon on llvm@lists.linux.dev

**Comment by JustinStitt** [comment]
Here are a few patches:

1) https://lore.kernel.org/all/20230809-cbl-1902-v1-1-92def12d1dea@google.com/ 

2) https://lore.kernel.org/all/20230809-cbl-1903-v1-1-df9d66a3ba3e@google.com/

3) https://lore.kernel.org/all/20230809-cbl-1903-v1-2-df9d66a3ba3e@google.com/

**Comment by nathanchance** [comment]
I noticed that Krzysztof Kozlowski sent a recent flurry of these patches: https://lore.kernel.org/all/?q=f%3Akrzysztof.kozlowski%40linaro.org+Wvoid-pointer-to-enum-cast

Seems like there are still quite a few instances of this warning, I will see if I can apply all those changes and do a series of builds to see what other warnings are out there.

**Comment by JustinStitt** [comment]
@nathanchance He opted for "uintptr_t"? What is the general opinion on that vs "unsigned long"

**Comment by nathanchance** [comment]
> What is the general opinion on that vs "unsigned long"

Not really sure there is one, you can get two different answers depending on the maintainer, as you have already kind of seen:

https://lore.kernel.org/20230810085632.xzonkmse27mu4yew@intel.intel/

https://lore.kernel.org/2023081004-lapped-handbag-0324@gregkh/

**Comment by nathanchance** [comment]
With all of those patches applied, I still see:

```
     12 drivers/devfreq/event/exynos-ppmu.c:530:21: warning: cast to smaller integer type 'enum exynos_ppmu_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
      8 drivers/dma/owl-dma.c:1119:14: warning: cast to smaller integer type 'enum owl_dma_id' from 'const void *' [-Wvoid-pointer-to-enum-cast]
      9 drivers/gpu/drm/mediatek/mtk_disp_ovl_adaptor.c:429:10: warning: cast to smaller integer type 'enum mtk_ovl_adaptor_comp_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
      9 drivers/gpu/drm/mediatek/mtk_drm_drv.c:832:15: warning: cast to smaller integer type 'enum mtk_ddp_comp_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
     20 drivers/gpu/drm/pl111/pl111_versatile.c:487:24: warning: cast to smaller integer type 'enum versatile_clcd' from 'const void *' [-Wvoid-pointer-to-enum-cast]
     20 drivers/gpu/drm/pl111/pl111_versatile.c:507:26: warning: cast to smaller integer type 'enum versatile_clcd' from 'const void *' [-Wvoid-pointer-to-enum-cast]
     15 drivers/gpu/drm/tiny/repaper.c:952:11: warning: cast to smaller integer type 'enum repaper_model' from 'const void *' [-Wvoid-pointer-to-enum-cast]
     20 drivers/i2c/busses/i2c-pxa.c:1267:15: warning: cast to smaller integer type 'enum pxa_i2c_types' from 'const void *' [-Wvoid-pointer-to-enum-cast]
     22 drivers/input/touchscreen/mms114.c:470:15: warning: cast to smaller integer type 'enum mms_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
     23 drivers/leds/leds-pca955x.c:487:15: warning: cast to smaller integer type 'enum pca955x_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
     11 drivers/mtd/maps/physmap-versatile.c:209:25: warning: cast to smaller integer type 'enum versatile_flashprot' from 'const void *' [-Wvoid-pointer-to-enum-cast]
     11 drivers/mtd/nand/raw/vf610_nfc.c:853:17: warning: cast to smaller integer type 'enum vf610_nfc_variant' from 'const void *' [-Wvoid-pointer-to-enum-cast]
     18 drivers/net/ethernet/ni/nixge.c:1273:12: warning: cast to smaller integer type 'enum nixge_version' from 'const void *' [-Wvoid-pointer-to-enum-cast]
     21 drivers/net/mdio/mdio-xgene.c:338:13: warning: cast to smaller integer type 'enum xgene_mdio_id' from 'const void *' [-Wvoid-pointer-to-enum-cast]
      8 drivers/pci/controller/pcie-iproc-platform.c:55:15: warning: cast to smaller integer type 'enum iproc_pcie_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
      5 drivers/power/reset/vexpress-poweroff.c:124:10: warning: cast to smaller integer type 'enum vexpress_reset_func' from 'const void *' [-Wvoid-pointer-to-enum-cast]
     11 drivers/soc/renesas/rmobile-sysc.c:193:22: warning: cast to smaller integer type 'enum pd_types' from 'const void *' [-Wvoid-pointer-to-enum-cast]
     22 sound/soc/codecs/rt5677.c:5581:19: warning: cast to smaller integer type 'enum rt5677_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
```

So not too bad, we could probably have this turned on by 6.7.

**Comment by JustinStitt** [comment]
> With all of those patches applied, I still see:
> 
> 
> 
> ```
> 
>      12 drivers/devfreq/event/exynos-ppmu.c:530:21: warning: cast to smaller integer type 'enum exynos_ppmu_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>       8 drivers/dma/owl-dma.c:1119:14: warning: cast to smaller integer type 'enum owl_dma_id' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>       9 drivers/gpu/drm/mediatek/mtk_disp_ovl_adaptor.c:429:10: warning: cast to smaller integer type 'enum mtk_ovl_adaptor_comp_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>       9 drivers/gpu/drm/mediatek/mtk_drm_drv.c:832:15: warning: cast to smaller integer type 'enum mtk_ddp_comp_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>      20 drivers/gpu/drm/pl111/pl111_versatile.c:487:24: warning: cast to smaller integer type 'enum versatile_clcd' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>      20 drivers/gpu/drm/pl111/pl111_versatile.c:507:26: warning: cast to smaller integer type 'enum versatile_clcd' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>      15 drivers/gpu/drm/tiny/repaper.c:952:11: warning: cast to smaller integer type 'enum repaper_model' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>      20 drivers/i2c/busses/i2c-pxa.c:1267:15: warning: cast to smaller integer type 'enum pxa_i2c_types' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>      22 drivers/input/touchscreen/mms114.c:470:15: warning: cast to smaller integer type 'enum mms_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>      23 drivers/leds/leds-pca955x.c:487:15: warning: cast to smaller integer type 'enum pca955x_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>      11 drivers/mtd/maps/physmap-versatile.c:209:25: warning: cast to smaller integer type 'enum versatile_flashprot' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>      11 drivers/mtd/nand/raw/vf610_nfc.c:853:17: warning: cast to smaller integer type 'enum vf610_nfc_variant' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>      18 drivers/net/ethernet/ni/nixge.c:1273:12: warning: cast to smaller integer type 'enum nixge_version' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>      21 drivers/net/mdio/mdio-xgene.c:338:13: warning: cast to smaller integer type 'enum xgene_mdio_id' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>       8 drivers/pci/controller/pcie-iproc-platform.c:55:15: warning: cast to smaller integer type 'enum iproc_pcie_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>       5 drivers/power/reset/vexpress-poweroff.c:124:10: warning: cast to smaller integer type 'enum vexpress_reset_func' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>      11 drivers/soc/renesas/rmobile-sysc.c:193:22: warning: cast to smaller integer type 'enum pd_types' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
>      22 sound/soc/codecs/rt5677.c:5581:19: warning: cast to smaller integer type 'enum rt5677_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
> 
> ```
> 
> 
> 
> So not too bad, we could probably have this turned on by 6.7.

Got it. I'll work towards this goal. I think im going to go for "uintptr_t" since I've seen more instances of that pattern.

**Comment by krzk** [comment]
Some of the warnings above were already fixed.

**Comment by JustinStitt** [comment]
> Some of the warnings above were already fixed.

Noted.

**Comment by JustinStitt** [comment]
There's now a patch for each of the -Wvoid-pointer-to-enum-cast warnings as reported by Nathan

>      12 drivers/devfreq/event/exynos-ppmu.c:530:21: warning: cast to smaller integer type 'enum exynos_ppmu_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230816-void-drivers-devfreq-event-exynos-ppmu-v1-1-3fac11083742@google.com/
>       8 drivers/dma/owl-dma.c:1119:14: warning: cast to smaller integer type 'enum owl_dma_id' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230816-void-drivers-dma-owl-dma-v1-1-a0a5e085e937@google.com/
>       9 drivers/gpu/drm/mediatek/mtk_disp_ovl_adaptor.c:429:10: warning: cast to smaller integer type 'enum mtk_ovl_adaptor_comp_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230621075421.1982-1-jason-jh.lin@mediatek.com/
>       9 drivers/gpu/drm/mediatek/mtk_drm_drv.c:832:15: warning: cast to smaller integer type 'enum mtk_ddp_comp_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230621075421.1982-1-jason-jh.lin@mediatek.com/
>      20 drivers/gpu/drm/pl111/pl111_versatile.c:487:24: warning: cast to smaller integer type 'enum versatile_clcd' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230816-void-drivers-gpu-drm-pl111-pl111_versatile-v1-1-92125dd9e6d4@google.com/
>      20 drivers/gpu/drm/pl111/pl111_versatile.c:507:26: warning: cast to smaller integer type 'enum versatile_clcd' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230816-void-drivers-gpu-drm-pl111-pl111_versatile-v1-1-92125dd9e6d4@google.com/
>      15 drivers/gpu/drm/tiny/repaper.c:952:11: warning: cast to smaller integer type 'enum repaper_model' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230816-void-drivers-gpu-drm-tiny-repaper-v1-1-9d8d10f0d52f@google.com/
>      20 drivers/i2c/busses/i2c-pxa.c:1267:15: warning: cast to smaller integer type 'enum pxa_i2c_types' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230816-void-drivers-i2c-busses-i2c-pxa-v1-1-931634b931ec@google.com/
>      22 drivers/input/touchscreen/mms114.c:470:15: warning: cast to smaller integer type 'enum mms_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230810095936.123432-1-krzysztof.kozlowski@linaro.org/
>      23 drivers/leds/leds-pca955x.c:487:15: warning: cast to smaller integer type 'enum pca955x_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230816-void-drivers-leds-leds-pca955x-v1-1-2967e4c1bdcc@google.com/
>      11 drivers/mtd/maps/physmap-versatile.c:209:25: warning: cast to smaller integer type 'enum versatile_flashprot' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230816-void-drivers-mtd-maps-physmap-versatile-v2-1-433a25272bfa@google.com/
>      11 drivers/mtd/nand/raw/vf610_nfc.c:853:17: warning: cast to smaller integer type 'enum vf610_nfc_variant' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230815-void-drivers-mtd-nand-raw-vf610_nfc-v1-1-7cc65314c56c@google.com/
>      18 drivers/net/ethernet/ni/nixge.c:1273:12: warning: cast to smaller integer type 'enum nixge_version' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230815-void-drivers-net-ethernet-ni-nixge-v1-1-f096a6e43038@google.com/
>      21 drivers/net/mdio/mdio-xgene.c:338:13: warning: cast to smaller integer type 'enum xgene_mdio_id' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230815-void-drivers-net-mdio-mdio-xgene-v1-1-5304342e0659@google.com/
>       8 drivers/pci/controller/pcie-iproc-platform.c:55:15: warning: cast to smaller integer type 'enum iproc_pcie_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230814-void-drivers-pci-controller-pcie-iproc-platform-v1-1-81a121607851@google.com/
>       5 drivers/power/reset/vexpress-poweroff.c:124:10: warning: cast to smaller integer type 'enum vexpress_reset_func' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230814-void-drivers-power-reset-vexpress-poweroff-v1-1-c3d9b0107e5d@google.com/
>      11 drivers/soc/renesas/rmobile-sysc.c:193:22: warning: cast to smaller integer type 'enum pd_types' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230814-void-drivers-soc-renesas-rmobile-sysc-v1-1-6648dfd854de@google.com/
>      22 sound/soc/codecs/rt5677.c:5581:19: warning: cast to smaller integer type 'enum rt5677_type' from 'const void *' [-Wvoid-pointer-to-enum-cast]
https://lore.kernel.org/all/20230814-void-sound-soc-codecs-rt5677-v1-1-5c468c60fa37@google.com/

**Comment by nickdesaulniers** [comment]
I'm sorry for not providing this feedback sooner; I acknowledge that makes me a jerk, but I'm not super happy with the approach taken for most of the above patches (and note I've been busy with srso issues, 2 machine failures, and attending an internal llvm conf).

The intent of `-Wvoid-pointer-to-enum-cast` is that you may be truncating data when converting from an arbitrary `void*` to an enum (the sizeof an enum depends on its definition, in the most common case `sizeof(enum arbitrary) != sizeof(void*)` though); a human may be able to verify that all assignments to the `void*` from those same enums, but a compiler cannot do such inter-function semantic analysis in a reasonable time.

As such, the safest bet is to explicit check for the possibility of truncation before laundering data through a truncating conversion.

i.e. I prefer something like:
```c
enum foo {
  x, y,
};
enum foo launder (void *z) {
    if ((long)z > INT_MAX || (long)z < INT_MIN)
        WARN_ONCE("truncating data!")
    return (enum foo)(intptr_t)z;
}
void my_driver (void) {
  ...
  driver->foo = launder(data->foo);
  ...
```
(And note, that check probably doesn't need to be bidirectional if the enum values were explicitly all unsigned literals, which is why maybe having an explicit launder function is nice to have one place to carefully review such checks)

I'll note that `-fsanitize=integer` seems capable of detecting mistaken truncations, but sadly:
1. the kernel doesn't appear to use `-fsanitize=integer` (perhaps another `-fsanitize` flag implies that)?
2. `-fsantize=integer` doesn't do such checks for this exact case when using enums rather than standard integer types.

**Comment by nickdesaulniers** [comment]
It looks like the kernel does have support for `-fsanitize=enum` (`CONFIG_UBSAN_ENUM`) but from my tests that doesn't catch such cases.  I think we should either:
- decide that we should check for truncation always in kernel sources (using a pattern like `launder` described above) or
- fix -fsanitize=enum to catch these cases, disable  `-Wvoid-pointer-to-enum-cast` always, then tell folks to use `CONFIG_UBSAN_ENUM` to catch these when/if there actually are problematic truncations at runtime.
  - `fsanitize=enum` is documented to only check for loads, not stores or conversions that may truncate
  - https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#available-checks
  - https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fsanitize_003denum

**Comment by nickdesaulniers** [comment]
> fix -fsanitize=enum to catch these cases

That might not even be necessary; it seems the existing implementation does bounds checks on the access/reads/uses, not stores/writes.  Perhaps then we should just permanantly disable `-Wvoid-pointer-to-enum-cast` and encourage the use of `CONFIG_UBSAN_ENUM` instead.

`CONFIG_UBSAN_ENUM` for instance does catch cases where you have something like:
```c

int a (void *v) {
  int x = (enum foo)v;
  return x;
}
```
(sigh, in clang, but not gcc)

**Comment by nickdesaulniers** [comment]
One point I discussed with @JustinStitt regarding the current state of -fsanitize=enum:

`-fsanitize=enum` only checks the access of enums, so it's possible for it to miss a truncating store:

Imagine an enum where INT_MAX is a valid enumeration value.  Imagine a long with a value greater than INT_MAX is stored to such an enum.  This would result in truncation/data loss, but then on first access the sanitizer would find that the value of INT_MAX is a valid enum value.  So there's missing coverage IMO of either `-fsanitize=integer` or `-fsanitize=enum` that should be fixed in clang.

---

Another thing to note is that safely checking for proper conversion can be complex.  For most enum definitions, 2 bounds checks suffices.  If we could force the enum to be unsigned only, then 1 bounds check suffices.  But once you start having sparse enum values, validating that any unsigned long converts to a valid enum value may be expensive.

**Comment by JustinStitt** [comment]
Should `-fsanitize=enum` also check for stores that aren't within the enum's enumerated values?

For example:
```c
enum DIR { north=0, east, south, west };

void foo(int bar) {
  enum DIR direction = (enum DIR)4; // enum has fields: 0 1 2 3 ... not 4
}
```

Or, for compile-time cases should this be a warning: `-Wenum-bounds`?

Is there _ever_ an instance where you'd want to misrepresent an enum with a value that is simply not present in the enumeration of said enum?

@nickdesaulniers

**Comment by nickdesaulniers** [comment]
> Should -fsanitize=enum also check for stores that aren't within the enum's enumerated values?

Yes; the compiler can not tell that a variable may have a value outside the enum values at runtime.

> For example:
> Or, for compile-time cases should this be a warning: -Wenum-bounds?

If you remove the cast, `-Wassign-enum` already will catch that obviously incorrect case at runtime.  Does the kernel enable that?  Does GCC support that or have an equivalent?  Perhaps it's worth turning that on in the kernel since it's not enabled by -Wall or -Wextra FWICT.

> Is there ever an instance where you'd want to misrepresent an enum with a value that is simply not present in the enumeration of said enum?

Sounds like some shady shit.

**Comment by JustinStitt** [comment]
After speaking with @nathanchance and @nickdesaulniers the general consensus is that we should probably just disable this warning.

Developers that add casts are showing intent and patches "fixing" the warning just decrease readability for no real benefit.

I think the outstanding patches are fine and may or may not get picked up but I'm closing this issue nonetheless.
