### ISSUE TITLE
issue with split debug info on riscv for clang-14 and older

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1914]
via: https://lore.kernel.org/llvm/ZNSWMgFF529bGy14@yujie-X299/

it seems like there's some issue with split debug info for riscv for clang-14 and older. If we bisect llvm, we can update kconfig to avoid it being selectable by randconfig

**Comment by nathanchance** [comment]
> If we bisect llvm

Currently working on it.

**Comment by nathanchance** [comment]
My bisect landed on https://github.com/llvm/llvm-project/commit/80a4e6fd31a06143b83947785ea3bd5c04344ea6, which just prevents `CONFIG_DEBUG_INFO_SPLIT` from being selected with `-mrelax`, which is the default as far as I understand.

I am not really sure how to restrict `CONFIG_DEBUG_INFO_SPLIT` based on this though. That change came out of https://github.com/llvm/llvm-project/issues/56642 and based on some of the comments in that thread, it seems like GCC silently produces broken `.dwo` files, so maybe we just want something like

```diff
diff --git a/lib/Kconfig.debug b/lib/Kconfig.debug
index d6798513a8c2..52a75c51b158 100644
--- a/lib/Kconfig.debug
+++ b/lib/Kconfig.debug
@@ -355,6 +355,9 @@ endchoice # "Compressed Debug information"
 config DEBUG_INFO_SPLIT
        bool "Produce split debuginfo in .dwo files"
        depends on $(cc-option,-gsplit-dwarf)
+       # RISC-V linker relaxation is not currently compatible with split DWARF:
+       # https://github.com/llvm/llvm-project/issues/56642
+       depends on !RISCV
        help
          Generate debug info into separate .dwo files. This significantly
          reduces the build directory size for builds with DEBUG_INFO,
```

? Would be nice to have a GCC bug report to go with that...

**Comment by MaskRay** [comment]
> My bisect landed on https://github.com/llvm/llvm-project/commit/80a4e6fd31a06143b83947785ea3bd5c04344ea6, which just prevents CONFIG_DEBUG_INFO_SPLIT from being selected with -mrelax, which is the default as far as I understand.

Yes. RISC-V linker relaxation doesn't work well with some debug info features in LLVM/Clang. In addition, DWARF v5 `-gdwarf-5`/`-fdebug-dwarf-version=5` can currently be incorrect. I changed Clang main branch and 17.x to default to v4 (https://github.com/llvm/llvm-project-release-prs/commit/3c0e8be5ba492a8fb1d7aa9af7509c80d64865ec).

> ? Would be nice to have a GCC bug report to go with that...

I think GCC's `-gsplit-dwarf` has been correct since 12.0 (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99090).

**Comment by nathanchance** [comment]
Thanks a lot for the extra info, I have sent https://lore.kernel.org/20230816-riscv-debug_info_split-v1-1-d1019d6ccc11@kernel.org/ to avoid this error.

**Comment by nathanchance** [comment]
The workaround is in mainline: https://git.kernel.org/linus/89775a27ff6d0396b44de0d6f44dcbc25221fdda

There is an issue upstream for this problem, so I'll close this one up.
