### ISSUE TITLE
-Wunused-variable in arch/riscv/kernel/ptrace.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1927]
kernelci is [reporting](https://lore.kernel.org/linux-next/64f03ea1.170a0220.d3dbf.11fd@mx.google.com/):
    3    arch/riscv/kernel/ptrace.c:123:11: warning: unused variable 'size' [-Wunused-variable]
That's from [here](https://lore.kernel.org/linux-riscv/20230825050248.32681-1-andy.chiu@sifive.com/).

[Reported](https://lore.kernel.org/linux-riscv/ZPDIQEVaEJHXR5IW@google.com/)

**Comment by nickdesaulniers** [comment]
Fix: https://lore.kernel.org/linux-riscv/20230830203754.24940-1-palmer@rivosinc.com/

**Comment by nathanchance** [comment]
This was fixed in the final change that hit mainline: https://git.kernel.org/linus/9300f00439743c4a34d735e1a27118eb68a1504e
