### ISSUE TITLE
-Wshift-overflow in arch/x86/kernel/head32.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#193]
```
arch/x86/kernel/head32.c:83:20: warning: signed shift result (0x100000000) requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow]
                (PAGE_TABLE_SIZE(LOWMEM_PAGES) << PAGE_SHIFT);
                                 ^~~~~~~~~~~~
./arch/x86/include/asm/pgtable_32.h:109:27: note: expanded from macro 'LOWMEM_PAGES'
#define LOWMEM_PAGES ((((2<<31) - __PAGE_OFFSET) >> PAGE_SHIFT))
                         ~^ ~~
./arch/x86/include/asm/pgtable_32.h:98:34: note: expanded from macro 'PAGE_TABLE_SIZE'
#define PAGE_TABLE_SIZE(pages) ((pages) / PTRS_PER_PGD)
                                 ^~~~~
1 warning generated.
```

Seen with `defconfig` + `# CONFIG_64BIT is not set`.

I am not sure if this warning is legitimate or not, will look into it tomorrow unless someone beats me to it.

**Comment by nathanchance** [comment]
I think this warning might be one of the "semantic analysis before optimization" type because while `2<<31` is indeed larger than UINT_MAX, the page shifts should cancel out, `__PAGE_OFFSET` is `0xC0000000`, and `PTRS_PER_PGD` is at worst 4, meaning that entire expression is way lower than UINT_MAX.

**Comment by nathanchance** [comment]
Arnd sent a patch to fix this and it was accepted: https://git.kernel.org/tip/26515699863d68058e290e18e83f444925920be5

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=26515699863d68058e290e18e83f444925920be5
