### ISSUE TITLE
-Wself-assign in fs/bcachefs/io_misc.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1934]
ci: https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/6235508429/job/16929304156#step:6:1853

```
  fs/bcachefs/io_misc.c:467:6: error: explicitly assigning value of
  variable of type 'int' to itself [-Werror,-Wself-assign]
    467 |         ret = ret;
        |         ~~~ ^ ~~~
```
sent: https://lore.kernel.org/llvm/20230919-bcachefs_self_assign-v1-1-830936792fc9@google.com/

**Comment by nathanchance** [comment]
https://git.kernel.org/next/linux-next/c/248d7139c94a67b9eecca31d2065b2235dfc349d
