### ISSUE TITLE
loongarch build fails for clang-14

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1941]
@TanzHasan mentioned hitting errors related to `-msoft-float` when trying to build ARCH=loongarch. I noticed he was using clang-14.  I suspect we need to update the version checking script to limit loongarch builds with clang to an explicit newer version.

**Comment by nathanchance** [comment]
This has come up before, Huacai was not a fan of adding a version check prior to defconfig working it seems: https://lore.kernel.org/CAAhV-H7MeiZpSh28j2TDSwS1ae0L+rGMA7hi+MV2Z3uCiguLkw@mail.gmail.com/

**Comment by nickdesaulniers** [comment]
submitted: https://lore.kernel.org/llvm/20240108033138.217032-1-wangrui@loongson.cn/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/chenhuacai/linux-loongson/c/e5517d5359715638f404c4d51418cd4431c64df6

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/f58b0abae839f06be9d791d16196922a4b281777
