### ISSUE TITLE
RISC-V configs with CONFIG_DEBUG_INFO_DWARF5=y broken after LLVM commit 1df5ea29b4369

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1961]
After https://github.com/llvm/llvm-project/commit/1df5ea29b43690b6622db2cad7b745607ca4de6a, RISC-V configurations that enable DWARF5 (such as [OpenSUSE's RISC-V configuration](https://github.com/openSUSE/kernel-source/raw/master/config/riscv64/default)) are broken because LLVM generates `R_RISCV_SET_ULEB128` and `R_RISCV_SUB_ULEB128` but `ld.lld` does not understand it.

```
$ make -skj"$(nproc)" ARCH=riscv LLVM=1 mrproper defconfig

$ scripts/config -d DEBUG_INFO_NONE -e DEBUG_INFO_DWARF5

$ make -skj"$(nproc)" ARCH=riscv LLVM=1 olddefconfig all
...
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_rnglists+0x375): unknown relocation (60) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_rnglists+0x375): unknown relocation (61) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_loclists+0xd8f): unknown relocation (60) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_rnglists+0x377): unknown relocation (60) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_loclists+0xd8f): unknown relocation (61) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_rnglists+0x377): unknown relocation (61) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_rnglists+0x37a): unknown relocation (60) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_loclists+0xd94): unknown relocation (60) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_rnglists+0x37a): unknown relocation (61) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_rnglists+0x37c): unknown relocation (60) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_loclists+0xd94): unknown relocation (61) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_rnglists+0x37c): unknown relocation (61) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_rnglists+0x37f): unknown relocation (60) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_loclists+0xd96): unknown relocation (60) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_rnglists+0x37f): unknown relocation (61) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_rnglists+0x381): unknown relocation (60) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_loclists+0xd96): unknown relocation (61) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_loclists+0xd9b): unknown relocation (60) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_rnglists+0x381): unknown relocation (61) against symbol
ld.lld: error: drivers/gpu/drm/drm_atomic_helper.o:(.debug_rnglists+0x385): unknown relocation (60) against symbol
...
```

While I am aware that this is less likely to happen in practice because `clang` defaults to DWARF4 for RISC-V after https://github.com/llvm/llvm-project/commit/bbc0f99f3bc96f1db16f649fc21dd18e5b0918f6 and there is an escape hatch with `-mllvm -riscv-uleb128-reloc=false`, I think this update should have been more atomic (or `-riscv-uleb128-reloc` should have defaulted to `false`)... Is there something that the kernel should do here? If it is going to be fixed in `ld.lld` quickly, it does not seem worth shipping a workaround for this but if it is going to take time, then we should do something so that others do not hit this.

cc @MaskRay @asb

**Comment by MaskRay** [comment]
Sorry for the breakage but I think I have made the decision to default it on because:

* Clang's DWARF v5 generation for RISC-V is incorrect in the presence of relaxation
* Clang defaulted to `-fdebug-default-version=4` for riscv*- triples
* GCC/binutils already generated ULEB128 relocations and LLD support is broken

`DEBUG_INFO_DWARF5` has always been incorrect and the Linux kernel should probably avoid using this configuration for now.

We probably should have rejected `-gdwarf-5` for RISC-V `-mrelax` very early to prevent reliance in the first place, but we failed to do it.

---

https://reviews.llvm.org/D142880 is a pending lld/ELF patch, but it does a lot of things and may take time. We probably should have a non-SHF_ALLOC version that does not handle relocation overflow, which is not that difficult to support.

**Comment by MaskRay** [comment]
I have created https://github.com/llvm/llvm-project/pull/72610 to handle non-SHF_ALLOC sections. It is probably good enough for code without using exceptions (`.gcc_except_table`; GCC C++ -fexceptions)

**Comment by nathanchance** [comment]
Thanks a lot! I can confirm that change will fix the kernel's build. I will send something like this to restrict DWARF5 to either versions that do not use relaxation or using `ld.lld` 18+.

```diff
diff --git a/arch/riscv/Kconfig b/arch/riscv/Kconfig
index afdf05ad78ad..61b98623bbbe 100644
--- a/arch/riscv/Kconfig
+++ b/arch/riscv/Kconfig
@@ -176,6 +176,11 @@ config GCC_SUPPORTS_DYNAMIC_FTRACE
 	def_bool CC_IS_GCC
 	depends on $(cc-option,-fpatchable-function-entry=8)
 
+config RISCV_USE_LINKER_RELAXATION
+	def_bool y
+	# https://github.com/llvm/llvm-project/commit/6611d58f5bbcbec77262d392e2923e1d680f6985
+	depends on !LD_IS_LLD || LLD_VERSION >= 150000
+
 config HAVE_SHADOW_CALL_STACK
 	def_bool $(cc-option,-fsanitize=shadow-call-stack)
 	# https://github.com/riscv-non-isa/riscv-elf-psabi-doc/commit/a484e843e6eeb51f0cb7b8819e50da6d2444d769
diff --git a/arch/riscv/Makefile b/arch/riscv/Makefile
index a74be78678eb..e383aa9e2757 100644
--- a/arch/riscv/Makefile
+++ b/arch/riscv/Makefile
@@ -43,8 +43,7 @@ else
 	KBUILD_LDFLAGS += -melf32lriscv
 endif
 
-ifeq ($(CONFIG_LD_IS_LLD),y)
-ifeq ($(call test-lt, $(CONFIG_LLD_VERSION), 150000),y)
+ifndef CONFIG_RISCV_USE_LINKER_RELAXATION
 	KBUILD_CFLAGS += -mno-relax
 	KBUILD_AFLAGS += -mno-relax
 ifndef CONFIG_AS_IS_LLVM
@@ -52,7 +51,6 @@ ifndef CONFIG_AS_IS_LLVM
 	KBUILD_AFLAGS += -Wa,-mno-relax
 endif
 endif
-endif
 
 ifeq ($(CONFIG_SHADOW_CALL_STACK),y)
 	KBUILD_LDFLAGS += --no-relax-gp
diff --git a/lib/Kconfig.debug b/lib/Kconfig.debug
index cc7d53d9dc01..32708be26e2f 100644
--- a/lib/Kconfig.debug
+++ b/lib/Kconfig.debug
@@ -282,7 +282,8 @@ config DEBUG_INFO_DWARF4
 config DEBUG_INFO_DWARF5
 	bool "Generate DWARF Version 5 debuginfo"
 	select DEBUG_INFO
-	depends on !CC_IS_CLANG || AS_IS_LLVM || (AS_IS_GNU && AS_VERSION >= 23502 && AS_HAS_NON_CONST_LEB128)
+	# !RISCV_USE_LINKER_RELAXATION || LLD_VERSION >= 180000: https://github.com/ClangBuiltLinux/linux/issues/1961
+	depends on !CC_IS_CLANG || (AS_IS_LLVM && (!RISCV_USE_LINKER_RELAXATION || LLD_VERSION >= 180000)) || (AS_IS_GNU && AS_VERSION >= 23502 && AS_HAS_NON_CONST_LEB128)
 	help
 	  Generate DWARF v5 debug info. Requires binutils 2.35.2, gcc 5.0+ (gcc
 	  5.0+ accepts the -gdwarf-5 flag but only had partial support for some
```

**Comment by nathanchance** [comment]
With https://github.com/llvm/llvm-project/commit/7ffabb61a5569444b5ac9322e22e5471cc5e4a77, the immediate issue of build errors is resolved. I will still send along the patch above at some point over the next week but I am going to close this up for now.

**Comment by nathanchance** [comment]
> I will still send along the patch above at some point over the next week but I am going to close this up for now.

https://lore.kernel.org/20231129-riscv-restrict-dwarf5-llvm-v1-0-ec0d368fb538@kernel.org/
