### ISSUE TITLE
evaluate -Wcomma

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1968]
existing issues need to be fixed first.

https://lore.kernel.org/all/20230630192825.GA2745548@dev-arch.thelio-3990X/

https://lore.kernel.org/llvm/20231218190055.GB2863043@dev-arch.thelio-3990X/

**Comment by JustinStitt** [comment]
Hi, is the usage of the comma operator just bad taste or is there a functional problem caused by some of its use scenarios?

**Comment by nathanchance** [comment]
Little column A, little column B in my opinion. In particular, it can result in problems like https://github.com/ClangBuiltLinux/linux/issues/390 and https://lore.kernel.org/58466.1688074499@warthog.procyon.org.uk/.

**Comment by nickdesaulniers** [comment]
Going to close this as wontfix (but feel free to reopen).  The issues I looked at from x86 and arm defconfigs seem to be people avoiding the use of block statements (via comma operator) or as loop conditions (which possibly could have been statements within the loop), but none of the cases looked like bugs or anything worthwhile to address IMO.
