### ISSUE TITLE
"error: .uleb128 expression is not absolute" in LoongArch vDSO after LLVM commit a8081ed8ff0fd11fb8d5f4c83df49da909e49612

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1970]
See the upstream report for more information:

https://github.com/llvm/llvm-project/pull/72960#issuecomment-1866844679

**Comment by MQ-mengqing** [comment]
I find `.uleb128` is generated in `.debug_loclists` section when O2(at least O1) optimization enabled. I think we need generate R_LARCH_{ADD,SUB}_ULEB128 relocation types for `.uleb128`. But first I have to figure out why the `.debug_loclists` section is generated, and why O0 not.

**Comment by MQ-mengqing** [comment]
Seem RISCV had solved this problem by https://reviews.llvm.org/D157657. And solved potential lld problem by https://github.com/ClangBuiltLinux/linux/issues/1961. I'll follow them.

**Comment by nathanchance** [comment]
https://github.com/llvm/llvm-project/pull/76433

**Comment by nathanchance** [comment]
https://github.com/llvm/llvm-project/commit/b57159cb19cdc06ec5733f93f0975aa6f40595cb
