### ISSUE TITLE
Fortify warning in net/xfrm/xfrm_user.c after LLVM commit 90ba33099cbb1

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1985]
After https://github.com/llvm/llvm-project/commit/90ba33099cbb17e7c159e9ebc5a512037db99d6d, I am seeing a new fortify warning in arm64 configurations (and only arm64 configurations interestingly...) in `net/xfrm/xfrm_user.c`:

```
In file included from net/xfrm/xfrm_user.c:14:
In file included from include/linux/compat.h:10:
In file included from include/linux/time.h:60:
In file included from include/linux/time32.h:13:
In file included from include/linux/timex.h:67:
In file included from arch/arm64/include/asm/timex.h:8:
In file included from arch/arm64/include/asm/arch_timer.h:12:
In file included from arch/arm64/include/asm/hwcap.h:9:
In file included from arch/arm64/include/asm/cpufeature.h:26:
In file included from include/linux/cpumask.h:12:
In file included from include/linux/bitmap.h:12:
In file included from include/linux/string.h:292:
include/linux/fortify-string.h:438:4: error: call to '__write_overflow_field' declared with 'warning' attribute: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror,-Wattribute-warning]
  438 |                         __write_overflow_field(p_size_field, size);
      |                         ^
1 error generated.
```

This is specifically the `memset()` in [`copy_to_user_tmpl()`](https://elixir.bootlin.com/linux/v6.7.1/source/net/xfrm/xfrm_user.c#L2012):

```c
static int copy_to_user_tmpl(struct xfrm_policy *xp, struct sk_buff *skb)
{
	struct xfrm_user_tmpl vec[XFRM_MAX_DEPTH];
	int i;

	if (xp->xfrm_nr == 0)
		return 0;

	for (i = 0; i < xp->xfrm_nr; i++) {
		struct xfrm_user_tmpl *up = &vec[i];
		struct xfrm_tmpl *kp = &xp->xfrm_vec[i];

		memset(up, 0, sizeof(*up));
		memcpy(&up->id, &kp->id, sizeof(up->id));
		up->family = kp->encap_family;
		memcpy(&up->saddr, &kp->saddr, sizeof(up->saddr));
		up->reqid = kp->reqid;
		up->mode = kp->mode;
		up->share = kp->share;
		up->optional = kp->optional;
		up->aalgos = kp->aalgos;
		up->ealgos = kp->ealgos;
		up->calgos = kp->calgos;
	}

	return nla_put(skb, XFRMA_TMPL,
		       sizeof(struct xfrm_user_tmpl) * xp->xfrm_nr, vec);
}
```

While I believe this is a false positive based on my understanding of the code, I think `clang` is pointing out that `vec` has `XFRM_MAX_DEPTH` (`6`) elements but there is no check in this function that makes sure that `xp->xfrm_nr` is not more than that, which would result in accessing memory outside of that array. Doing something like this clears up the warning for me but I am not sure if this is a proper fix or would be accepted upstream.

```diff
diff --git a/net/xfrm/xfrm_user.c b/net/xfrm/xfrm_user.c
index ad01997c3aa9..cd2596e2c6ae 100644
--- a/net/xfrm/xfrm_user.c
+++ b/net/xfrm/xfrm_user.c
@@ -2017,6 +2017,9 @@ static int copy_to_user_tmpl(struct xfrm_policy *xp, struct sk_buff *skb)
        if (xp->xfrm_nr == 0)
                return 0;

+       if (xp->xfrm_nr > XFRM_MAX_DEPTH)
+               return -ENOBUFS;
+
        for (i = 0; i < xp->xfrm_nr; i++) {
                struct xfrm_user_tmpl *up = &vec[i];
                struct xfrm_tmpl *kp = &xp->xfrm_vec[i];
```

cc @kees just to double check my understanding.

**Comment by nathanchance** [comment]
As far as I can tell, `xfrm_nr` is only ever assigned from [`copy_templates()`](https://elixir.bootlin.com/linux/latest/source/net/xfrm/xfrm_user.c#L1756), which in turn is only called in functions after [`validate_tmpl()`](https://elixir.bootlin.com/linux/latest/source/net/xfrm/xfrm_user.c#L1781), which checks that the number assigned to `xfrm_nr`  is less than `XFRM_MAX_DEPTH`, hence the false positive aspect of this warning. However, I think it is really hard to expect the compile to know this based on the way the code is written, so I am not sure that warning in this case is entirely unreasonable.

I am still curious why this only shows up on arm64. Perhaps there is an arm64 performance optimization that messed something up here or causes some other change?

Regardless, maybe that diff I have above would be a good defense in depth measure, as it would ensure that somehow `xfrm_nr` can't get changed somewhere in the pipeline and cause a buffer overwrite when copying templates back to user space. I will send it along soon and see what upstream thinks.

**Comment by nathanchance** [comment]
I need to tease out a reproducer for this. However, this is now visible with x86_64:

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/7838258377/job/21391994325

**Comment by kees** [comment]
Yeah, I think it's a reasonable patch to add to the kernel. I still don't understand why this LLVM change manifests this way. It hasn't suddenly started doing value range tracking...

**Comment by nathanchance** [comment]
I bisected the LLVM change that exposed this for `x86_64` because it was not the same one as arm64 and I landed on https://github.com/llvm/llvm-project/commit/ffd79b3312cea51c0787aad479ce285771470397. I had a theory that loop unrolling was involved... Further proof of that is that

```diff
diff --git a/net/xfrm/xfrm_user.c b/net/xfrm/xfrm_user.c
index f037be190bae..307b69d909eb 100644
--- a/net/xfrm/xfrm_user.c
+++ b/net/xfrm/xfrm_user.c
@@ -2017,6 +2017,7 @@ static int copy_to_user_tmpl(struct xfrm_policy *xp, struct sk_buff *skb)
        if (xp->xfrm_nr == 0)
                return 0;

+#pragma clang loop unroll(disable)
        for (i = 0; i < xp->xfrm_nr; i++) {
                struct xfrm_user_tmpl *up = &vec[i];
                struct xfrm_tmpl *kp = &xp->xfrm_vec[i];
```

silences it. I wonder if this is somehow related to https://github.com/ClangBuiltLinux/linux/issues/1781 because that one can also be silenced with the same pragma...

I will see if I can drum up a trivial reproducer for this based of that.

**Comment by nathanchance** [comment]
I send my earlier diff as a formal patch: https://lore.kernel.org/20240221-xfrm-avoid-clang-fortify-warning-copy_to_user_tmpl-v1-1-254a788ab8ba@kernel.org/

I came up with some reproducers from `cvise` but I am not really sure they demonstrate much. I think there really should just be a bounds check here, otherwise the compiler can't know there won't be any undefined behavior here.

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/klassert/ipsec/c/1a807e46aa93ebad1dfbed4f82dc3bf779423a6e

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/1a807e46aa93ebad1dfbed4f82dc3bf779423a6e
