### ISSUE TITLE
[LD/LTO] Error when building Linux 6.7 with Clang-18 and ThinLTO

### ISSUE THREAD

**Issue by torvic9** [ClangBuiltLinux/linux#1987]
``` 
[...]
  LD      vmlinux.o
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Running pass 'Function Pass Manager' on module 'vmlinux.a(ip6_input.o at 1126398)'.
1.      Running pass 'X86 DAG->DAG Instruction Selection' on function '@ip6_rcv_core'
LLVM ERROR: Failed to rename temporary file /tmp/thinlto/.thinlto-cache/Thin-9fd8ee.tmp.o to /tmp/thinlto/.thinlto-cache/llvmcache-793C60E3B43AB478844F44E24AE756CE26CEDE23: No such file or directory
```

This weird build error appears when building Linux.6.7 with Clang-18 (from 18.x release tree) and ThinLTO. No such issue with Clang-17.

**Comment by nathanchance** [comment]
Seems like https://github.com/llvm/llvm-project/issues/72026, which you will hit if you are using `-march` with a Zen value.

**Comment by torvic9** [comment]
Yes, I'm using `-march=znver2`.

I can also confirm that building with generic arch works fine.

**Comment by KyunLFA** [comment]
For the people who are people keeping up with it, the issue still present in Clang 19 compiled today the 27th (commit 57a20d2d09bbd3cc501fc6d8b4746be2040c99b7).

**Comment by KyunLFA** [comment]
Workaround: Add `KBUILD_CFLAGS := $(filter-out -march=foo, $(KBUILD_CFLAGS))` one line above `obj-$(CONFIG_IPV6) += ipv6.o` in net/ipv6/Makefile , where "foo" is your -march value.

**Comment by torvic9** [comment]
Some more information:

``` 
  LD      vmlinux.o
ld.lld: error: vmlinux.a(ip6_input.o at 1130482) <inline asm>:1:21: base register is 64-bit, but index register is not
        addq %rdx, %gs:256(%r8,%di)
                           ^


ld.lld: error: vmlinux.a(ip6_input.o at 1130482) <inline asm>:1:26: expected absolute expression
        addq %rdx, %gs:256(%rdi,$1)
                                ^
```

**Comment by berolinux** [comment]
Reduced test case (doesn't even need LTO):

```c
long a[1];
char b();
void c() { asm("" : "+m"(a[1 + (b() & 1)])); }
```

**Comment by torvic9** [comment]
Also happens with `-mtune=znver2` with latest clang-18.

As per @KyunLFA 's advice, I use the following to work around this issue:

```
diff --git a/net/ipv6/Makefile b/net/ipv6/Makefile
index d283c59df4c1..3840ded8c34a 100644
--- a/net/ipv6/Makefile
+++ b/net/ipv6/Makefile
@@ -3,6 +3,13 @@
 # Makefile for the Linux TCP/IP (INET6) layer.
 #
 
+# temporary workaround for clang/lld-18 with -march/-mtune=znver2
+# clangbuiltlinux issue 1987
+ifeq ($(call test-ge, $(CONFIG_CLANG_VERSION), 180000),y)
+badparms = -march=znver2 -mtune=znver2
+KBUILD_CFLAGS :=	$(filter-out $(badparams), $(KBUILD_CFLAGS))
+endif
+
 obj-$(CONFIG_IPV6) += ipv6.o
 
 ipv6-y :=	af_inet6.o anycast.o ip6_output.o ip6_input.o addrconf.o \
```

**Comment by nathanchance** [comment]
This should be resolved in LLVM main now: https://github.com/llvm/llvm-project/commit/46505b3cbfc5f48f28431b9141085c5d71ddf1c4

I tested at https://github.com/llvm/llvm-project/commit/3fae5551de72756c3bb9fb2e5a29c95f02cbbd6b, which built fine.

**Comment by Connor-GH** [comment]
Just for SEO I want to confirm as well that this also happens on znver3, not just 2 (as the patch would suggest).
