### ISSUE TITLE
unreachable instruction objtool warning in arch/x86/kernel/platform-quirks.o

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#199]
`arch/x86/kernel/platform-quirks.o: warning: objtool: x86_early_init_platform_quirks()+0x8e: unreachable instruction
`

**Comment by nickdesaulniers** [comment]
tools/objtool/Documentation/stack-validation.txt has this to say about this warning:

```
2. file.o: warning: objtool: .text+0x53: unreachable instruction

   Objtool couldn't find a code path to reach the instruction.

   If the error is for an asm file, and the instruction is inside (or
   reachable from) a callable function, the function should be annotated
   with the ENTRY/ENDPROC macros (ENDPROC is the important one).
   Otherwise, the code should probably be annotated with the unwind hint
   macros in asm/unwind_hints.h so objtool and the unwinder can know the
   stack state associated with the code.

   If you're 100% sure the code won't affect stack traces, or if you're
   a just a bad person, you can tell objtool to ignore it.  See the
   "Adding exceptions" section below.

   If it's not actually in a callable function (e.g. kernel entry code),
   change ENDPROC to END.
```

**Comment by nickdesaulniers** [comment]
I seem to no longer able to reproduce this warning.

**Comment by nickdesaulniers** [comment]
Thanks for the report.  Don't hesitate to reopen if you can repro.

Also, curious if https://lore.kernel.org/r/20181015172221.35709-1-ndesaulniers@google.com/ fixes this, too?

**Comment by nickdesaulniers** [comment]
I sent:
[part 1](https://lore.kernel.org/r/20181015172221.35709-1-ndesaulniers@google.com/)
[part 2](https://lore.kernel.org/r/20181015212428.260810-1-ndesaulniers@google.com/)

ping @ojeda for review.

**Comment by nathanchance** [comment]
Just FYI, part 1 is in torvalds/linux already: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=fe0640eb30b7da261ae84d252ed9ed3c7e68dfd8

**Comment by nickdesaulniers** [comment]
then that patch was not a fix, because I still see the warning:
https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/162224335
> arch/x86/kernel/platform-quirks.o: warning: objtool: x86_early_init_platform_quirks()+0x8e: unreachable instruction

**Comment by nickdesaulniers** [comment]
looks like both patches are in mainline...

**Comment by nathanchance** [comment]
That patch fixed #204 but it didn't fix this one.

**Comment by nickdesaulniers** [comment]
Still an issue w/ `kvmconfig` in 5.2-rc1.

**Comment by nickdesaulniers** [comment]
@jpoimboe posted a patch: https://lore.kernel.org/r/20190710232244.to73phlufdetf5os@treble/
I tested it but the issue still was observed: https://lore.kernel.org/r/CAKwvOdmSQUjDUeL-rG5q=EyfhWstHeCVDn+=9spEQmw5BJGaaA@mail.gmail.com/
I sent @jpoimboe the object file as a test case.

**Comment by nickdesaulniers** [comment]
@jpoimboe  has sent a series fixing this:
https://lore.kernel.org/r/cover.1563150885.git.jpoimboe@redhat.com/
specifically
https://lore.kernel.org/r/4db0cb4d1065c8714ee64f0bfc9fc8b7d6331124.1563150885.git.jpoimboe@redhat.com/

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b68b9907069a8d3a65bc16a35360bf8f8603c8fa
