### ISSUE TITLE
ppc64 crossbuild fails

### ISSUE THREAD

**Issue by naguam** [ClangBuiltLinux/linux#1999]
Hello,

I am not yet knowledgeable on kernel internals, however I was curious about building a kernel with clang.

I followed instructions here https://docs.kernel.org/kbuild/llvm.html

And made my tests on a clean debian stable vm with llvm/clang 14 and 18 (the later from apt-llvm)

The kernel 6.7.5 built perfectly with clang for my native x86 pc and crossbuild with ARCH=riscv

However the ppc64 build failed on both :
```
make LLVM=1 ARCH=powerpc defconfig
make LLVM=1 ARCH=powerpc -j4
```
(debian system clang 14)

and

```
make LLVM=-18 ARCH=powerpc defconfig
make LLVM=-18 ARCH=powerpc -j4
```
(apt llvm)

I hope I gave enough info to reproduce.

(I used `apt build-dep linux` to install the dependencies and ensured the kernel could be built with gcc. so not a dependency problem)

I am happy to contribute at my level,

(And sorry I don't have the build log/error anymore, but it is very fast to reproduce)

**Comment by naguam** [comment]
Ok in a debian container where I am now I was able to reproduce an output for llvm-14 and llvm-18 which have the same error (I tried llvm-18 thinking that for other arch than x86, llvm minimum versions could be higher)

```
objcopy: Unable to recognise the format of the input file `vmlinux'
make[2]: *** [arch/powerpc/boot/Makefile:399: arch/powerpc/boot/zImage.pseries] Error 1
make[1]: *** [arch/powerpc/Makefile:238: zImage] Error 2
```

**Comment by nathanchance** [comment]
Thanks for the report! With `ARCH=powerpc`, there is still a dependency on GNU binutils in `arch/powerpc/boot/wrapper`, so you will need to install `binutils-powerpc64le-linux-gnu` and provide `CROSS_COMPILE=powerpc64le-linux-gnu-` to your make command (#1601)

**Comment by naguam** [comment]
Ok thanks I did not see that issue.

Maybe the Linux kernel documentation should be changed so it does not state LLVM=1 in the chart :).

**Comment by nathanchance** [comment]
Well `LLVM=1` works for the main kernel build up through `vmlinux` and `modules`, so I don't think recommending `CC=clang` is fair, but I agree the documentation could be clearer around this situation... I'll think about how to do that.
