### ISSUE TITLE
-fzero-call-used-regs=used-gpr

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#20]
gcc is adding a way to specify that certain registers should be zero'd.  Let's see if llvm will entertain such a feature.

gcc patch: https://github.com/clearlinux-pkgs/gcc/blob/master/zero-regs-gcc8.patch
llvm feature request: https://llvm.org/pr37880

@kees

**Comment by nickdesaulniers** [comment]
@gwelymernans has submitted an RFC for this to llvm-dev: https://lists.llvm.org/pipermail/llvm-dev/2020-August/144082.html

**Comment by nickdesaulniers** [comment]
Clearing assignees in case someone else wants to pick this up.

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/kees/linux.git/commit/?h=kspp/hardening/options&id=a82adfd5c7cb4b8bb37ef439aed954f9972bb618

I don't think all values for this flag are equal priority. It looks like the kernel is using `-fzero-call-used-regs=used-gpr`. Maybe the issue title should be updated to reflect that?

**Comment by nickdesaulniers** [comment]
@gwelymernans posted: https://reviews.llvm.org/D110869

**Comment by nickdesaulniers** [comment]
(the kernel's Kconfig checks will have to be tightened up; CONFIG_CC_HAS_ZERO_CALL_USED_REGS in security/Kconfig.hardening only checks for the presence of `-fzero-call-used-regs=used-gpr` but the initial implementation in LLVM only supports x86)

**Comment by kees** [comment]
> (the kernel's Kconfig checks will have to be tightened up; CONFIG_CC_HAS_ZERO_CALL_USED_REGS in security/Kconfig.hardening only checks for the presence of `-fzero-call-used-regs=used-gpr` but the initial implementation in LLVM only supports x86)

Will clang not just error out for -fzero-call-used... on non-x86?

**Comment by isanbard** [comment]
GCC has a default implementation for zeroing out registers. It's easier for them to implement this feature, because of how they keep track of registers.

Anyway, I suppose we should emit an error in the case where we don't support the feature...

**Comment by nickdesaulniers** [comment]
initial support for this will ship for x86_64 in clang-15. We'll pursue enabling more backends, but it's a fair amount of work per arch to get this working. Should be easier now that clang supports the flags and some support is arch agnostic.

https://reviews.llvm.org/rGdeaf22bc0e306bc44c70d2503e9364b5ed312c49

closing, but perhaps we want to track different backend support somehow? Happy to have new issues somewhere for those.
