### ISSUE TITLE
Fedora Rawhide kernel builds fails with `unkown symbol errors`.

### ISSUE THREAD

**Issue by tstellar** [ClangBuiltLinux/linux#2006]
After upgrading from clang-17 to clang-18, the Fedora Rawhide kernel builds started to fail with many errors like:

`nfsv4.ko needs unknown symbol __pcpu_unique_nfs4_callback_count1`

Full build log is [here](https://s3.amazonaws.com/arr-cki-prod-trusted-artifacts/trusted-artifacts/1201391372/build_aarch64/6320322082/artifacts/build.log)

**Comment by tstellar** [comment]
@nathanchance  Here is the config file we were using for the last successful build with clang-17: [config.txt](https://github.com/ClangBuiltLinux/linux/files/14528591/config.txt)

**Comment by nikic** [comment]
I suspect that the key part of the config is `CONFIG_DEBUG_FORCE_WEAK_PER_CPU=y`.

**Comment by nikic** [comment]
test.c:
```
__attribute__((__section__(".discard"))) __attribute__((unused)) char __pcpu_unique_foo;
```
module.lds:
```
SECTIONS {
 /DISCARD/ : {
  *(.discard)
  *(.discard.*)
 }
}
```
Then:
```
build/bin/clang test.c -c
build/bin/ld.lld -r -T module.lds test.o -o test
objdump -t test
```
Produces:
```
0000000000000000       O *UND*	0000000000000000 __pcpu_unique_foo
```

With old ld.lld and ld.bfd, the undefined symbol was not present.

**Comment by nikic** [comment]
This regressed in https://github.com/llvm/llvm-project/commit/1981b1b6b92f7579a30c9ed32dbdf3bc749c1b40, cc @MaskRay

**Comment by nikic** [comment]
Filed an upstream issue: https://github.com/llvm/llvm-project/issues/85048

**Comment by nikic** [comment]
Issue has been fixed and backported to the 18.x branch, so this can be closed.
