### ISSUE TITLE
"copy source size is too small" after LLVM commit 3589cacfa8da89b9b5051e4dba659caa575e6b3f

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#2007]
After https://github.com/llvm/llvm-project/commit/3589cacfa8da89b9b5051e4dba659caa575e6b3f, I see the following error when building `ARCH=x86_64 allmodconfig`, which enables `CONFIG_KCSAN` (i.e, `-fsanitize=thread`):

```
$ make -skj"$(nproc)" ARCH=x86_64 LLVM=1 clean allmodconfig net/bluetooth/sco.o
In file included from net/bluetooth/sco.c:27:
In file included from include/linux/module.h:13:
In file included from include/linux/stat.h:19:
In file included from include/linux/time.h:60:
In file included from include/linux/time32.h:13:
In file included from include/linux/timex.h:67:
In file included from arch/x86/include/asm/timex.h:6:
In file included from arch/x86/include/asm/tsc.h:10:
In file included from arch/x86/include/asm/msr.h:15:
In file included from include/linux/percpu.h:7:
In file included from include/linux/smp.h:118:
include/linux/thread_info.h:244:4: error: call to '__bad_copy_from' declared with 'error' attribute: copy source size is too small
  244 |                         __bad_copy_from();
      |                         ^
1 error generated.
```

which comes from [`check_copy_size()`](https://elixir.bootlin.com/linux/v6.8/source/include/linux/thread_info.h#L237) in [`copy_to_user()`](https://elixir.bootlin.com/linux/v6.8/source/include/linux/uaccess.h#L188). I also see the same error emitted in `net/bluetooth/l2cap_sock.c`. If I disable CONFIG_KCSAN, there is no error. The parent of 3589cacfa8da89b9b5051e4dba659caa575e6b3f does not show this error and GCC does not show an error either, so I am not sure the kernel code is at fault here but I could be missing something obvious.

I tried adding `0 && ` to the `if` statements with `copy_to_user()` in [`net/bluetooth/sco.c`](https://elixir.bootlin.com/linux/v6.8/source/net/bluetooth/sco.c) to see if it was one particular statement causing an issue but applying it to either `if (copy_to_user(optval, (char *)&opts, len))` or `if (copy_to_user(optval, (char *)&cinfo, len))` prevents the error from appearing, which seems rather strange to me.

I am still working on teasing out a small reproducer. If this seems like an non-Linux kernel specific issue, I am happy to file a report upstream.

cc @dtcxzyw @nikic

**Comment by nathanchance** [comment]
`cvise` spits out:

```c
struct {
  short hci_handledev_class[3];
} sco_sock_getsockopt_old_cinfo;
typeof(__builtin_choose_expr(
    sizeof(char), 0,
    __builtin_choose_expr(
        sizeof(short), 0,
        __builtin_choose_expr(sizeof(int), 0,
                              __builtin_choose_expr(sizeof(long), 0, 0)))))
    sco_sock_getsockopt_old___val_gu;
void kmsan_unpoison_memory(void *address) {}
void __attribute__((__error__("copy source size is too small")))
__bad_copy_from();
long copy_to_user(void *from, long n) {
  void *addr = from;
  long bytes = n;
  int sz = __builtin_object_size(addr, 0);
  if (__builtin_expect(sz >= 0 && sz < bytes, 0))
    __bad_copy_from();
  return 0;
}
int sco_sock_getsockopt_old() {
  int len;
  long __tmp = sco_sock_getsockopt_old___val_gu;
  kmsan_unpoison_memory(&__tmp);
  len = __tmp;
  len = __builtin_choose_expr(
      0, 0, ({
        typeof(0) __UNIQUE_ID___x1646 = len;
        unsigned __UNIQUE_ID___y1647 = sizeof(sco_sock_getsockopt_old_cinfo);
        __UNIQUE_ID___x1646 < __UNIQUE_ID___y1647 ? __UNIQUE_ID___x1646 : 0;
      }));
  copy_to_user(&sco_sock_getsockopt_old_cinfo, len);
  return 0;
}
```

GCC 13.2.0:

```
$ x86_64-linux-gcc -O2 -Wall -c -o /dev/null sco.i

$ x86_64-linux-gcc -O2 -Wall -fsanitize=thread -c -o /dev/null sco.i
```

Clang @ https://github.com/llvm/llvm-project/commit/0cbbcf1ef006ce13a1fa94960067723982ae955a:

```
$ clang -O2 -Wall -c -o /dev/null sco.i

$ clang -O2 -Wall -fsanitize=thread -c -o /dev/null sco.i
```

Clang @ https://github.com/llvm/llvm-project/commit/3589cacfa8da89b9b5051e4dba659caa575e6b3f:

```
$ clang -O2 -Wall -c -o /dev/null sco.i

$ clang -O2 -Wall -fsanitize=thread -c -o /dev/null sco.i
sco.i:19:5: error: call to '__bad_copy_from' declared with 'error' attribute: copy source size is too small
   19 |     __bad_copy_from();
      |     ^
1 error generated.
```

**Comment by dtcxzyw** [comment]
@nathanchance Great! Could you please file this issue in llvm-project?

**Comment by nathanchance** [comment]
Done, thanks! https://github.com/llvm/llvm-project/issues/85647

**Comment by nathanchance** [comment]
https://lore.kernel.org/20240401-bluetooth-fix-len-type-getsockopt_old-v1-1-c6b5448b5374@kernel.org/

**Comment by nathanchance** [comment]
Patch has been accepted: https://git.kernel.org/bluetooth/bluetooth-next/c/0ef86e9051d7e6f0d56b3a07ad851e4a2a65860d

**Comment by nathanchance** [comment]
This is now resolved in Linus's tree and it should go back to stable automatically.

https://git.kernel.org/linus/9bf4e919ccad613b3596eebf1ff37b05b6405307

I will close this issue but leave the upstream report open.

**Comment by nathanchance** [comment]
I got a message that this has been queued up for the next series of stable releases.
