### ISSUE TITLE
-Wbounds-safety-counted-by-elt-type-unknown-size in drivers/gpu/drm/radeon/pptable.h

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#2028]
After https://github.com/llvm/llvm-project/commit/cef6387e52578366c2332275dad88b9953b55336, I see the following warning many times in trees that contain https://git.kernel.org/linus/781d41fed19caf900c8405064676813dc9921d32:

```
In file included from drivers/gpu/drm/radeon/radeon_device.c:48:
In file included from drivers/gpu/drm/radeon/atom.h:165:
In file included from drivers/gpu/drm/radeon/atombios.h:7980:
drivers/gpu/drm/radeon/pptable.h:442:5: warning: 'counted_by' should not be applied to an array with element of unknown size because 'ATOM_PPLIB_STATE_V2' (aka 'struct _ATOM_PPLIB_STATE_V2') is a struct type with a flexible array member. This will be an error in a future compiler version [-Wbounds-safety-counted-by-elt-type-unknown-size]
  442 |     ATOM_PPLIB_STATE_V2 states[] __counted_by(ucNumEntries);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

This one seems legitimate and I think Bill brought this up to the author of that change (although we should probably be the ones to send the patch since it is clang changing here):

```
typedef struct _ATOM_PPLIB_STATE_V2
{
      //number of valid dpm levels in this state; Driver uses it to calculate the whole 
      //size of the state: struct_size(ATOM_PPLIB_STATE_V2, clockInfoIndex, ucNumDPMLevels)
      UCHAR ucNumDPMLevels;
      
      //a index to the array of nonClockInfos
      UCHAR nonClockInfoIndex;
      /**
      * Driver will read the first ucNumDPMLevels in this array
      */
      UCHAR clockInfoIndex[] __counted_by(ucNumDPMLevels);
} ATOM_PPLIB_STATE_V2;

typedef struct _StateArray{
    //how many states we have 
    UCHAR ucNumEntries;
    
    ATOM_PPLIB_STATE_V2 states[] __counted_by(ucNumEntries);
}StateArray;
```

cc @kees @bwendling

**Comment by bwendling** [comment]
Yeah. I suggested foregoing the use of `__counted_by` for the time being.

**Comment by nathanchance** [comment]
This is now breaking CI because of `-Werror`: https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/9261999992

**Comment by nathanchance** [comment]
Patch submitted: https://lore.kernel.org/20240529-drop-counted-by-radeon-states-state-array-v1-1-5cdc1fb29be7@kernel.org/

**Comment by nathanchance** [comment]
Patch accepted: https://gitlab.freedesktop.org/agd5f/linux/-/commit/0f2fd37c141110e2763742376c9f6c9dd21b7416

**Comment by nathanchance** [comment]
Now merged into mainline: https://git.kernel.org/linus/2bac084468847cfe5bbc7166082b2a208514bb1c

This will go back to stable automatically (although it may take a little bit due to the merge window and such).
