### ISSUE TITLE
ld.lld: error: undefined symbol: __sync_val_compare_and_swap_1

### ISSUE THREAD

**Issue by lag-google** [ClangBuiltLinux/linux#2030]
When building `v6.9`, the Android build fails with:

```
ERROR: /mnt/disks/build-disk/src/android/common-android-mainline/common/BUILD.bazel:1099:19: Linking common/kselftest_rtc_rtctest failed: (Exit 1): clang failed: error executing CppLink command (from target //common:kselftest_rtc_rtctest) prebuilts/clang/host/linux-x86/clang-r510928/bin/clang -o bazel-out/k8-fastbuild-ST-1d1f3f988a8c/bin/common/kselftest_rtc_rtctest ... (remaining 6 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
ld.lld: error: undefined symbol: __sync_val_compare_and_swap_1
>>> referenced by rtctest.c
>>>               bazel-out/k8-fastbuild-ST-1d1f3f988a8c/bin/common/_objs/kselftest_rtc_rtctest/rtctest.o:(wrapper_rtc_date_read)
>>> referenced by rtctest.c
>>>               bazel-out/k8-fastbuild-ST-1d1f3f988a8c/bin/common/_objs/kselftest_rtc_rtctest/rtctest.o:(wrapper_rtc_date_read)
>>> referenced by rtctest.c
>>>               bazel-out/k8-fastbuild-ST-1d1f3f988a8c/bin/common/_objs/kselftest_rtc_rtctest/rtctest.o:(wrapper_rtc_date_read_loop)
>>> referenced 1 more times
```

It appears to have started with this commit:
```
commit fff37bd32c7605d93bf900c4c318d56d12000048
Author: Mickaël Salaün <mic@digikod.net>
Date:   Sat May 11 19:14:38 2024 +0200

    selftests/harness: Fix fixture teardown
    
    Make sure fixture teardowns are run when test cases failed, including
    when _metadata->teardown_parent is set to true.
    
    Make sure only one fixture teardown is run per test case, handling the
    case where the test child forks.
    
    Cc: Jakub Kicinski <kuba@kernel.org>
    Cc: Shengyu Li <shengyu.li.evgeny@gmail.com>
    Cc: Shuah Khan <skhan@linuxfoundation.org>
    Fixes: 72d7cb5c190b ("selftests/harness: Prevent infinite loop due to Assert in FIXTURE_TEARDOWN")
    Fixes: 0710a1a73fb4 ("selftests/harness: Merge TEST_F_FORK() into TEST_F()")
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Link: https://lore.kernel.org/r/20240511171445.904356-4-mic@digikod.net
    Rule: add
    Link: https://lore.kernel.org/stable/20240506165518.474504-4-mic%40digikod.net
    Signed-off-by: Mickaël Salaün <mic@digikod.net>
---
 tools/testing/selftests/kselftest_harness.h | 14 +++++++++-----
 1 file changed, 9 insertions(+), 5 deletions(-)

diff --git a/tools/testing/selftests/kselftest_harness.h b/tools/testing/selftests/kselftest_harness.h
index d98702b6955d..55699a762c45 100644
--- a/tools/testing/selftests/kselftest_harness.h
+++ b/tools/testing/selftests/kselftest_harness.h
@@ -382,7 +382,10 @@
                FIXTURE_DATA(fixture_name) self; \
                pid_t child = 1; \
                int status = 0; \
-               bool jmp = false; \
+               /* Makes sure there is only one teardown, even when child forks again. */ \
+               bool *teardown = mmap(NULL, sizeof(*teardown), \
+                       PROT_READ | PROT_WRITE, MAP_SHARED | MAP_ANONYMOUS, -1, 0); \
+               *teardown = false; \
                memset(&self, 0, sizeof(FIXTURE_DATA(fixture_name))); \
                if (setjmp(_metadata->env) == 0) { \
                        /* Use the same _metadata. */ \
@@ -399,15 +402,16 @@
                                _metadata->exit_code = KSFT_FAIL; \
                        } \
                } \
-               else \
-                       jmp = true; \
                if (child == 0) { \
-                       if (_metadata->setup_completed && !_metadata->teardown_parent && !jmp) \
+                       if (_metadata->setup_completed && !_metadata->teardown_parent && \
+                                       __sync_bool_compare_and_swap(teardown, false, true)) \
                                fixture_name##_teardown(_metadata, &self, variant->data); \
                        _exit(0); \
                } \
-               if (_metadata->setup_completed && _metadata->teardown_parent) \
+               if (_metadata->setup_completed && _metadata->teardown_parent && \
+                               __sync_bool_compare_and_swap(teardown, false, true)) \
                        fixture_name##_teardown(_metadata, &self, variant->data); \
+               munmap(teardown, sizeof(*teardown)); \
                if (!WIFEXITED(status) && WIFSIGNALED(status)) \
                        /* Forward signal to __wait_for_test(). */ \
                        kill(getpid(), WTERMSIG(status)); \
(END)
```

**Comment by nickdesaulniers** [comment]
cc @kees

**Comment by nickdesaulniers** [comment]
I *think* that `__sync_val_compare_and_swap_1` is a magic symbol that is produced from the compiler builtin `__sync_val_compare_and_swap` (or perhaps in this case `__sync_bool_compare_and_swap` since `sizeof(bool) == 1`) with the suffix depending on the size of the parameters.  I *think* this is provided usually by the compiler runtime, which the kernel explicitly doesn't link against. IIRC, for Android, we set `--rtlib=none` (but I may be misremembering).  Perhaps GCC is able to elide the libcall, but clang is not?

**Comment by nathanchance** [comment]
This is a selftest linking failure, is `--rtlib=none` passed to that build? I would expect that to cause issues, as the selftests could be relying on compiler runtime functions (and should be allowed to, as they are userspace programs).

**Comment by nickdesaulniers** [comment]
> as they are userspace programs

ah, I couldn't remember if they were, or if they were linked directly into the kernel image itself.

**Comment by nickdesaulniers** [comment]
https://android-review.googlesource.com/c/kernel/common/+/3099719 is the patch in question.

Not sure yet that kleaf _is_ setting `--rtlib=none`. I found code in kleaf that's setting `--rtlib=compiler-rt`.

**Comment by nickdesaulniers** [comment]
Interesting, https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/_005f_005fsync-Builtins.html calls these "legacy interfaces."

>  They should not be used for new code which should use the ‘__atomic’ builtins instead.

I think the kernel code should be using __atomic_compare_exchange instead

**Comment by nickdesaulniers** [comment]
ok, I can get clang to generate these libcalls when targeting 32b ARM: https://godbolt.org/z/8ceMz6qbW 

are the kselftests being built for 32b ARM despite the failures observed being all aarch64 kernel builds?

**Comment by nickdesaulniers** [comment]
@jyknight points out that the libcall can be avoided by setting `-march=armv6` or newer.  Dunno if we should do that in the tools/ Makefile for clang+arm.

---

> I think the kernel code should be using __atomic_compare_exchange instead

I think this is how we'd transform the kernel code to use `__atomic_compare_exchange`, though I get a warning with clang.

https://godbolt.org/z/9Toa6sq15

> <source>:11:12: warning: large atomic operation may incur significant performance penalty; the access size (1 bytes) exceeds the max lock-free size (0  bytes) [-Watomic-alignment]

**Comment by nickdesaulniers** [comment]
https://gist.github.com/nickdesaulniers/a178d58ad473ca1bb962d35172381c93 perhaps ? 🤷

**Comment by nickdesaulniers** [comment]
Further findings; clang emits `__sync_bool_compare_and_swap` as:
1. a libcall to `__atomic_compare_exchange_1` for `--target=arm-none-eabi`
2. a libcall to `__sync_val_compare_and_swap_1` for `--target=aarch64-linux-gnu -m32`
3. a bunch of inline instructions for `--target=arm-linux-gnueabihf`

The pass `atomic-expand` seems to be the pass where the libcall is expanded from the `cmpxchg` IR instruction, for `--target=arm-none-eabi`, otherwise `arm-isel` is choosing `__sync_val_compare_and_swap_1` for `--target=aarch64-linux-gnu -m32`.

If I add `-mfloat-abi=hard -mcpu=cortex-a72` to `--target=aarch64-linux-gnu -m32`, then llvm avoids any libcall.  So another approach than the change I have is to explicitly set which float-abi we intend to use when building the selftests for 32b AND pick a CPU explicitly.  I don't have enough knowledge of the tools/ dir build system to know where to make that incision though.

**Comment by nickdesaulniers** [comment]
Carlos was able to extract the command line invocation from kleaf.  `'--target=arm-linux-androideabi31'` was being set. Explicitly setting a cpu (like via `-mcpu=cortex-a8`) avoids this issue.

**Comment by thebigcako** [comment]
Hello,

Why did you tag me?.

I am no expert on the insides of linux, sorry 😅

**Comment by nickdesaulniers** [comment]
ah, sorry! Wrong Carlos Llamas!

The fix ended up being: https://android-review.googlesource.com/c/kernel/common/+/3101462
