### ISSUE TITLE
"value is too large for field of 1 byte" in linux-6.6.y after LLVM commit 1a47f3f3db665

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#2044]
See my upstream report for more information: https://github.com/llvm/llvm-project/issues/100283

I was able to do some more investigation and found this is only reproducible in `linux-6.6.y` after commit [e40f32f17642](https://git.kernel.org/stable/c/e40f32f17642a1ea36c79d102e0b680f79793cbc) ("x86/bugs: Fix the SRSO mitigation on Zen3/4") but it does not appear at the upstream version of that change, commit [4535e1a4174c](https://git.kernel.org/linus/4535e1a4174c4111d92c5a9a21e542d232e0fcaa) ("x86/bugs: Fix the SRSO mitigation on Zen3/4"). I will see if I can see what commit implicitly fixes this issue between 6.6 and 6.9-rc2 where that change originally landed to see what is going on here, in case there is nothing wrong with the mentioned LLVM change.

**Comment by nathanchance** [comment]
This is showing up for 6.6 in multiple configurations:

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/10149526943

@MaskRay did you notice the upstream issue?

**Comment by MaskRay** [comment]
Thanks for the reproduce. I think there is an existing issue related to how MC relaxes `MCFillFragment`.
The issue was exposed by my fragment layout algorithm change.

I have a fix.

**Comment by nathanchance** [comment]
This was fixed by reverting the original change: https://github.com/llvm/llvm-project/commit/4eb5450f630849ee0518487de38d857fbe5b1aee
