### ISSUE TITLE
sh_entsize is different between GNU ld and ld.lld after linking

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#2057]
Initial report from PeterZ after a 0day build report: https://lore.kernel.org/20241108141600.GB6497@noisy.programming.kicks-ass.net/

I reduced this down with `cvise`, which spits out:

```c
asm("__SCT__tp_func_ufshcd_profile_hibern8"
    ":                  \n"
    "911:\n\t"
    ".pushsection .discard.annotate,\"M\",@progbits,8\n\t"
    ".long 911b - .\n\t"
    ".long "
    "1"
    "\n\t"
    ".popsection\n\t"
    ".byte 15, 185, c                           \n"
    ".type "
    "__SCT__tp_func_ufshcd_profile_hibern8"
    ", @function        \n"
    ".size "
    "__SCT__tp_func_ufshcd_profile_hibern8"
    ", . - "
    "__SCT__tp_func_ufshcd_profile_hibern8");
```

When linking with `ld.lld`, `sh_entsize` of `.discard.annotate` goes from `8` to `0`.

```
$ clang --target=x86_64-linux-gnu -O2 -c -o cc.o ufshcd.i

$ llvm-readelf -WS cc.o | grep -F '.discard.annotate PROGBITS'
  [ 4] .discard.annotate PROGBITS        0000000000000000 000043 000008 08   M  0   0  1

$ ld.lld -m elf_x86_64 -z noexecstack -r -o ld.o cc.o

$ llvm-readelf -S ld.o | grep -F '.discard.annotate PROGBITS'
  [ 3] .discard.annotate PROGBITS        0000000000000000 000060 000008 00   M  0   0  1
```

That does not happen when linking the same object file with GNU ld

```
$ rm ld.o

$ x86_64-linux-ld -m elf_x86_64 -z noexecstack -r -o ld.o cc.o

$ llvm-readelf -S ld.o | grep -F '.discard.annotate PROGBITS'
  [ 4] .discard.annotate PROGBITS        0000000000000000 0000c0 000008 08   M  0   0  1
```

[A work in progress series for `objtool`](https://lore.kernel.org/all/20241111125218.113053713@infradead.org/) is going to warn when `ld.lld`'s current behavior is detected.

cc @MaskRay

**Comment by MaskRay** [comment]
Thanks for the detailed reproduce and apology for the late reply.

The generic ABI specifies:

> sh_entsize
> Some sections hold a table of fixed-size entries, such as a symbol table. For such a section, this member gives the size in bytes of each entry. The member contains 0 if the section does not hold a table of fixed-size entries.

lld's `sh_entsize=0` behavior for SHF_MERGE sections with relocations in -r links is correct, but not useful.
lld retains the non-zero `sh_entsize` in non-r links. The latest lld now ports the behavior to -r links.

**Comment by nathanchance** [comment]
Thanks a lot for the fix! Would it make sense to backport this to `release/19.x`?

**Comment by MaskRay** [comment]
The prerequisite commit (43e3871a327b8e2ff57e16b46d5bc44beb430d91) does not apply cleanly to release/19.x because some `Ctx &ctx` changes missing. It's difficult to get this backport to `release/19.x`.

**Comment by nathanchance** [comment]
Thanks, I am sure we can live with this.

https://github.com/llvm/llvm-project/commit/d4bed617f4378873d7ddf4b53c041e7b39d1a9ca for the record

**Comment by bjackman** [comment]
(**edit - user error** - see [comment below](https://github.com/ClangBuiltLinux/linux/issues/2057#issuecomment-2634705076)) 

Hi folks,

```
❯❯  clang --version
clang version 20.1.0-rc1 (https://github.com/llvm/llvm-project.git af7f483a9d801252247b6c72e3763c1f55c5a506)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin

❯❯  git rev-parse HEAD  # (kernel tree)
0de63bb7d91975e73338300a57c54b93d3cc151c

❯❯  tools/testing/kunit/kunit.py build --arch=x86_64 --make_options "LLVM=1" --make_options "CC=clang" --kunitconfig ./fs/fat/.kunitconfig
[14:42:55] Configuring KUnit Kernel ...
Generating .config ...
Populating config with:
$ make ARCH=x86_64 O=.kunit olddefconfig LLVM=1 CC=clang
[14:43:00] Building KUnit Kernel ...
Populating config with:
$ make ARCH=x86_64 O=.kunit olddefconfig LLVM=1 CC=clang
Building with:
$ make all compile_commands.json ARCH=x86_64 O=.kunit --jobs=96 LLVM=1 CC=clang
vmlinux.o: warning: objtool: .discard.annotate_insn: dodgy linker, sh_entsize != 8

[14:43:23] Elapsed time: 23.180s
```

Afraid I'm a bit clueless about the specifics here, does this (`dodgy linker, sh_entsize != 8`) suggest there's still something wrong?

**Comment by nathanchance** [comment]
@bjackman Thanks for bringing this up. Is `ld.lld` also built from source in `/usr/local/bin` or just `clang`? I am surprised to see this warning still with 20.1.0-rc1 as the fix was landed there and I have not seen it in any of my builds.

**Comment by bjackman** [comment]
Agh - you're right my `ld.ldd` is not coming from my LLVM build. I wil figure out how to install that and get back to you!

**Comment by bjackman** [comment]
Yeah it was just that I was missing `lld` from this build flag: `-DLLVM_ENABLE_PROJECTS="clang;lld;clang-tools-extra"`. And, it's fixed with the updated linker. Sorry for the noise :)
