### ISSUE TITLE
The LLVM Linux Project

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#219]
Since the LLVM Linux Project is deprecated, maybe we can get some exposure on @lll-project or llvm.linuxfoundation.org? Since @ClangBuiltLinux is a spiritual successor of that project with similar goals and active community, we can ask for a link from their pages.

**Comment by dileks** [comment]
A new project name is desired - probably "ClangBuiltLinux". Personally, I name my linux-kernels with the suffix "cbl" like in my latest version "4.19.0-rc6-1-amd64-cbl".

**Comment by nickdesaulniers** [comment]
Also, we're going to pay someone to do some vector art for the project soon.  That way we can have a logo for a site, die cut stickers, and t shirts for our 🔥 contributors.

**Comment by tpimh** [comment]
Possibly we can just create a `ClangBuiltLinux.github.io` repo and use a simple clean template from what GitHub Pages provides.

**Comment by nickdesaulniers** [comment]
@behanw had sent me this note:

```
Hey. So Linux Foundation just forwarded the llvm.linuxfoundation.org URL to https://clangbuiltlinux.github.io/ , which is fine by me.

Again, I’m happy for you to use the “llvmlinux” name if you want to.
```

Closing this issue for now, as we have the links from Linux Foundation.  But happy to reopen the discussion if folks feel passionately about this.
