### ISSUE TITLE
implement `__attribute__((fallthrough))`

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#235]
https://bugs.llvm.org/show_bug.cgi?id=37135

@ojeda is looking to possibly add this to the Linux kernel.

**Comment by ojeda** [comment]
We will wait a bit (few months?) until we get slightly better widespread support in non-compiler tools.

**Comment by nickdesaulniers** [comment]
Sounds good, I think this is low hanging fruit in Clang and will revisit after we have some CI setup.

**Comment by davidbolvansky** [comment]
Candidate patch:
https://reviews.llvm.org/D63260

**Comment by nickdesaulniers** [comment]
Huck is looking into this as well.  Looks like some fun parsing bugs: https://reviews.llvm.org/D64838

**Comment by nickdesaulniers** [comment]
merged: https://reviews.llvm.org/rL369414
