### ISSUE TITLE
4.19 common kernel built with clang for x86_64 emits popcnt instructions

### ISSUE THREAD

**Issue by ajs1984** [ClangBuiltLinux/linux#238]
(This bug probably affects more kernels and more toolchains. Just documenting what I tested.)

Built a kernel from https://android.googlesource.com/kernel/common experimental/android-4.19 using CC=clang. Clang was r339409b from AOSP prebuilts. Booted the kernel like this:

$ qemu-system-x86_64 -kernel arch/x86/boot/bzImage -serial stdio -display none

[    1.083629] invalid opcode: 0000 [#1] PREEMPT SMP NOPTI
[    1.084054] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 4.19.0-00015-g1d9d1df4a742 #1
[    1.084394] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.10.2-1 04/01/2014
[    1.084865] RIP: 0010:acpi_rs_get_list_length+0x1ee/0x2ee

$ objdump -d drivers/acpi/acpica/rscalc.o | grep popcnt
 3a9:   66 f3 0f b8 c0          popcnt %ax,%ax
 43a:   66 f3 43 0f b8 44 35    popcnt 0x0(%r13,%r14,1),%ax

popcnt shouldn't be emitted when building Linux for x86_64 because not all x86_64 systems (including the default qemu 64-bit CPU apparently) will have the popcnt instruction. It was added to Nehalem alongside SSE 4.2, but as the wikipedia article is quick to point out, popcnt is not actually part of the SSE 4.2 instruction set.

This can be worked around by starting qemu-system-x86_64 with -enable-kvm or that flag plus -cpu host which both enable popcnt implicitly.

I noticed that GCC has an "mpopcnt" flag documented, perhaps suggesting that it does not emit popcnt instructions by default.

**Comment by nickdesaulniers** [comment]
@niravhdave I assume this is another case of maybe -mno-popcount not being implicitly enabled by a -mno-sse4 flag in Clang?

**Comment by niravhdave** [comment]
Looks like it. I have a patch which I'll send upstream tomorrow.

**Comment by niravhdave** [comment]
Scratch that. Clang is doing the correct thing. popcnt is distinct from SSE4.2 and will only be enabled if given an explicit popcnt flag or cpu with the instruction. The build must be setting that somewhere.

**Comment by nathanchance** [comment]
Could this have been fixed in a newer version of Clang? I built from the experimental/android-4.19 branch with x86_64_cuttlefish_defconfig and a version of Clang synced at r345111 and I can boot with that qemu command no problem.

**Comment by nickdesaulniers** [comment]
Interesting find @nathanchance , thanks for testing. :weight_lifting_man: 

The following commits between r339409 and r345111 mention `popcnt` in their commit messages and aren't arm related.

[r344348](https://github.com/ClangBuiltLinux/llvm/commit/c4e53cf2f6736bb5ff869810f26b30daacb5f78c) ("[X86][SSE] LowerVectorCTPOP - pull out repeated byte sum stage.")

but that looks like it simply generates `vpopcnt` in more cases.

`acpi_rs_get_list_length` is defined in drivers/acpi/acpica/rscalc.c.  drivers/acpi/acpica/.rscalc.o.cmd shows that drivers/acpi/acpica/rscalc.o was compiled with:

```
cmd_drivers/acpi/acpica/rscalc.o := clang -Wp,-MD,drivers/acpi/acpica/.rscalc.o.d  -nostdinc -isystem /android1/llvm/build/lib/clang/8.0.0/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Qunused-arguments -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -no-integrated-as -fno-PIE -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -mno-80387 -mstack-alignment=8 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -Wno-sign-compare -fno-asynchronous-unwind-tables -mretpoline-external-thunk -DRETPOLINE -Wa,arch/x86/kernel/macros.s -fno-delete-null-pointer-checks -O2 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-format-invalid-specifier -Wno-gnu -Wno-address-of-packed-member -Wno-tautological-compare -mno-global-merge -Wno-unused-const-variable -fomit-frame-pointer -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fno-stack-check -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Wno-initializer-overrides -Wno-unused-value -Wno-format -Wno-sign-compare -Wno-format-zero-length -Wno-uninitialized -Os -D_LINUX -DBUILDING_ACPICA    -DKBUILD_BASENAME='"rscalc"' -DKBUILD_MODNAME='"acpi"' -c -o drivers/acpi/acpica/rscalc.o drivers/acpi/acpica/rscalc.c
```

Of interest are:
```
-mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -mno-80387 -mtune=generic
```

Note that `-mno-popcnt` is not set.

**Comment by niravhdave** [comment]
Given that the -no-integrated-as flag is set, this is almost certainly an issue with an inline asm block explicitly calling popcnt and clang not being unable to diagnose the problem without the integrated assembler. 

If we get the intermediate .s files via -save-temps I'd expect to see the calls sandwiched in inline asm start/end blocks

**Comment by nathanchance** [comment]
Grepping for popcnt reveals some stuff in `arch/x86/include/asm/arch_hweight.h`, added by commit d61931d89be5 ("x86: Add optimized popcnt variants") and further modified by commit f5967101e9de ("x86/hweight: Get rid of the special calling convention"). Not sure how that plays in, I'll try to get some intermediate .s files here shortly.

**Comment by nathanchance** [comment]
@niravhdave Here are all of the .o and intermediate .s files for all of the files above (from `CC="clang -save-temps"`), zipped up for ease of upload. Let me know if you need anything else!

[files.zip](https://github.com/ClangBuiltLinux/linux/files/2517053/files.zip)

**Comment by niravhdave** [comment]
Looking at this in more depth and talking with folks, here's what appears to be happening:

1. The kernel inserts popcnt by way of .byte annotations which sidesteps any assembler / compiler checking. 
2. This is inserted via the alternative macro mechanism which also takes a backup call based version of popcnt and makes sure that we pad these two possibility to the same size and records on the side where we want our popcnt implementation. All places are defaulted with the byte-level popcnt instruction 
3. Dynamically, when the kernel determines popcnt is not valid (X86_FEATURE_POPCNT is false), the kernel will modify all instances of popcnt with the safe alternative. 

So finding popcnt in the object files is actually fine, we won't see it in a real execution if it's not valid. 

I'm going to mark this is as closed.

**Comment by nickdesaulniers** [comment]
Thanks @niravhdave . @ajs1984 please reopen if you think there's more we can do here on the kernel side? Meanwhile `-cpu host` in qemu is a recommended workaround.
