### ISSUE TITLE
Cannot build powerpc vector instructions

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/linux#239]
From https://bugs.llvm.org/show_bug.cgi?id=38887#c4

> When we enabled soft-float for ppc64, we chose to disable altivec!
> 
> http://llvm.org/viewvc/llvm-project?view=revision&revision=283060
> 
> This change enables soft-float for PowerPC64, and also makes soft-float disable
> all vector instruction sets for both 32-bit and 64-bit modes. This latter part
> is necessary because the PPC backend canonicalizes many Altivec vector types to
> floating-point types, and so soft-float breaks scalarization support for many
> operations. Both for embedded targets and for operating-system kernels desiring
> soft-float support, it seems reasonable that disabling hardware floating-point
> also disables vector instructions (embedded targets without hardware floating
> point support are unlikely to have Altivec, etc. and operating system kernels
> desiring not to use floating-point registers to lower syscall cost are unlikely
> to want to use vector registers either). If someone needs this to work, we'll
> need to change the fact that we promote many Altivec operations to act on
> v4f32. To make it possible to disable Altivec when soft-float is enabled,
> hardware floating-point support needs to be expressed as a positive feature,
> like the others, and not a negative feature, because target features cannot
> have dependencies on the disabling of some other feature. So +soft-float has
> now become -hard-float.

We can work around this when building the powerpc64 defconfigs by disabling options that use vector instructions:
```
./scripts/config -d BTRFS_FS -d MD_RAID456
```

References:
- https://bugs.llvm.org/show_bug.cgi?id=31177
- https://bugs.llvm.org/show_bug.cgi?id=38887
- https://bugs.llvm.org/show_bug.cgi?id=38886

**Comment by shenki** [comment]
Workaround posted: https://patchwork.ozlabs.org/patch/991268/

**Comment by nickdesaulniers** [comment]
@shenki did your patch ever land?

**Comment by nathanchance** [comment]
Workaround patch merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e213574a449f7a57d4202c1869bbc7680b6b5521

Do we want to close this?

**Comment by nickdesaulniers** [comment]
Hopefully the llvm bug gets resolved, but this is no longer technically a blocker.
