### ISSUE TITLE
ld.lld: error: ./arch/powerpc/kernel/vmlinux.lds:73: unknown section directive: 0

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/linux#253]
Building Linus tree with clang trunk, powernv_defconfig:

```
make CC=/scratch/joel/llvm-build/bin/clang-8  HOSTCC=/scratch/joel/llvm-build/bin/clang-8 LD=/scratch/joel/llvm-build/bin/ld.lld -j176
...
ld.lld -EL -m elf64lppc -Bstatic --orphan-handling=warn --build-id -o .tmp_vmlinux1 -T ./arch/powerpc/kernel/vmlinux.lds --whole-archive built-in.a --no-whole-archive --start-group lib/lib.a --end-group
ld.lld: error: ./arch/powerpc/kernel/vmlinux.lds:73: unknown section directive: 0
>>>  .text BLOCK(0) : AT(ADDR(.text) - (0xc000000000000000 -0x00000000)) {
>>>        ^
```

**Comment by shenki** [comment]
arch/powerpc/kernel/vmlinux.lds.S:
```
        /*
         * BLOCK(0) overrides the default output section alignment because
         * this needs to start right after .head.text in order for fixed
         * section placement to work.
         */
        .text BLOCK(0) : AT(ADDR(.text) - LOAD_OFFSET) {
```

**Comment by martell** [comment]
@shenki I'm not sure if we would want to either
A. enable block support as an alias for align in lld
or
B. change the linker script to use align.

Anyway here is the lld patch.
https://reviews.llvm.org/D56060

**Comment by shenki** [comment]
There is some use of the [`BLOCK` syntax](https://github.com/search?utf8=✓&q=BLOCK%280%29+extension%3Ald+extension%3AldS+fork%3Atrue&type=Code&ref=advsearch&l=&l=) in the wild, but we probably don't have to care about supporting them.

I have written a patch that I will submit to the upstream kernel:

http://ozlabs.org/~joel/0001-powerpc-Use-ALIGN-instead-of-BLOCK.patch

**Comment by nickdesaulniers** [comment]
@shenki LGTM, did you send that patch yet?

**Comment by nickdesaulniers** [comment]
Patch sent: https://lists.ozlabs.org/pipermail/linuxppc-dev/2019-January/183899.html

**Comment by nickdesaulniers** [comment]
patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?id=a652758ac1475f69d28d11b3528c4f48

**Comment by martell** [comment]
What do we do from here?
@shenki can you get the patch backported to LTS and co?

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/a652758ac1475f69d28d11b3528c4f48
