### ISSUE TITLE
ld.lld: error: discarding .rela.plt section is not allowed

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/linux#254]
```
make CC=/scratch/joel/llvm-build/bin/clang-8  HOSTCC=/scratch/joel/llvm-build/bin/clang-8 -j176 LD=/scratch/joel/llvm-build/bin/ld.lld V=1

...

+ /scratch/joel/llvm-build/bin/ld.lld -EL -m elf64lppc -Bstatic --orphan-handling=warn --build-id -o .tmp_vmlinux1 -T ./arch/powerpc/kernel/vmlinux.lds --whole-archive built-in.a --no-whole-archive --start-group lib/lib.a --end-group
ld.lld: error: discarding .rela.plt section is not allowed
ld.lld: warning: <internal>:(.bss.rel.ro) is being placed in '.bss.rel.ro'
ld.lld: warning: <internal>:(.symtab) is being placed in '.symtab'
ld.lld: warning: <internal>:(.symtab_shndxr) is being placed in '.symtab_shndxr'
ld.lld: warning: <internal>:(.shstrtab) is being placed in '.shstrtab'
ld.lld: warning: <internal>:(.strtab) is being placed in '.strtab'
```

**Comment by martell** [comment]
Created an upstream patch for this, unsure if it is as simple as that but will see.
https://reviews.llvm.org/D54871

**Comment by nickdesaulniers** [comment]
Why was it unsupported in the first place? I'm curious if the commit messages of those lines gives more details?  Just deleting the check is kind of surprising for a fix.  Maybe if the original error message was "discarding X is not allowed **because Y**" ...

**Comment by martell** [comment]
> Why was it unsupported in the first place?
I'm not sure. Maybe they were just all disabled by default?
If there is a good reason the lld devs will probably tell me I'm not allowed to do that.
but for now just hoping it is this simple. :)

**Comment by martell** [comment]
I committed it upstream
https://reviews.llvm.org/rLLD348258
