### ISSUE TITLE
__compiletime_assert in arch/x86/platform/efi/efi_64.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#256]
`CONFIG_NO_AUTO_INLINE` is a new config option in -next ([commit](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=9b76795cc32426e68ca1c647b6d31c7148940719)) that prevents compilers from inlining any functions not marked as inline. It gets enabled in an allyesconfig build for x86_64.

The fail I noticed after this is

```
ld: arch/x86/platform/efi/efi_64.o: in function `efi_sync_low_kernel_mappings':
(.text+0x8e5): undefined reference to `__compiletime_assert_277'
```

I think it is one of the `MAYBE_BUILD_BUG_ON` because they involve `__builtin_constant_p`, relating it to #7. We might not have to worry about this on 4.20/5.0 but we'll see. Will try to look into this over the next few days unless someone else beats me to it.

As a workaround:

```diff
diff --git a/lib/Kconfig.debug b/lib/Kconfig.debug
index 2a4274b756dc..12a9ade3aecb 100644
--- a/lib/Kconfig.debug
+++ b/lib/Kconfig.debug
@@ -213,6 +213,7 @@ config GDB_SCRIPTS
 
 config NO_AUTO_INLINE
        bool "Disable compiler auto-inline optimizations"
+       depends on !CC_IS_CLANG
        help
          This will prevent the compiler from optimizing the kernel by
          auto-inlining functions not marked with the inline keyword.
```

**Comment by nickdesaulniers** [comment]
If you comment out the `BUILD_BUG_ON` and `MAYBE_BUILD_BUG_ON`, you can bisect which one specifically is failing.

**Comment by nathanchance** [comment]
I finally got around to sitting down commenting out the `BUILD_BUG_ON`s to figure out which one causes the error and it is `BUILD_BUG_ON(p4d_index(EFI_VA_END) != p4d_index(MODULES_END));`.

`p4d_index` is marked as `inline` in `arch/x86/include/asm/pgtable.h`:

```c
static inline unsigned long p4d_index(unsigned long address)
{
        return (address >> P4D_SHIFT) & (PTRS_PER_P4D - 1);
}
```

I assume that the reason the `BUILD_BUG_ON` fails is because without inlining, `p4d_index` isn't evaluated as a constant expression? According to the help text, functions marked `inline` are supposed to be inlined still but that doesn't appear to be the case with Clang.

From `lib/Frontend/CompilerInvocation.cpp`:

```c
  // At O0 we want to fully disable inlining outside of cases marked with
  // 'alwaysinline' that are required for correctness.
  Opts.setInlining((Opts.OptimizationLevel == 0)
                       ? CodeGenOptions::OnlyAlwaysInlining
                       : CodeGenOptions::NormalInlining);
  // Explicit inlining flags can disable some or all inlining even at
  // optimization levels above zero.
  if (Arg *InlineArg = Args.getLastArg(
          options::OPT_finline_functions, options::OPT_finline_hint_functions,
          options::OPT_fno_inline_functions, options::OPT_fno_inline)) {
    if (Opts.OptimizationLevel > 0) {
      const Option &InlineOpt = InlineArg->getOption();
      if (InlineOpt.matches(options::OPT_finline_functions))
        Opts.setInlining(CodeGenOptions::NormalInlining);
      else if (InlineOpt.matches(options::OPT_finline_hint_functions))
        Opts.setInlining(CodeGenOptions::OnlyHintInlining);
      else
        Opts.setInlining(CodeGenOptions::OnlyAlwaysInlining);
    }
  }
```

If I'm reading this correctly, when `-fno-inline-functions` is supplied, only functions that are marked `__always_inline` will be inlined. This fixes this particular fail, wonder if this would be accepted upstream (or would people claim Clang is broken and needs to be compatible with GCC lol):

```diff
diff --git a/arch/x86/include/asm/pgtable.h b/arch/x86/include/asm/pgtable.h
index 40616e805292..f78e53382498 100644
--- a/arch/x86/include/asm/pgtable.h
+++ b/arch/x86/include/asm/pgtable.h
@@ -918,7 +918,7 @@ static inline int p4d_bad(p4d_t p4d)
 }
 #endif  /* CONFIG_PGTABLE_LEVELS > 3 */
 
-static inline unsigned long p4d_index(unsigned long address)
+static __always_inline unsigned long p4d_index(unsigned long address)
 {
        return (address >> P4D_SHIFT) & (PTRS_PER_P4D - 1);
 }
```

**Comment by nickdesaulniers** [comment]
> when -fno-inline-functions is supplied

Is the kernel using that for `CONFIG_NO_AUTO_INLINE`? I get the feeling that they may be hitting quite a few of these kind of errors.

I think some commit message explaining that `-fno-inline-functions` from `CONFIG_NO_AUTO_INLINE` causes this specific bug to longer be ICE with Clang is fine.

**Comment by nickdesaulniers** [comment]
I'm curious too what the point of `CONFIG_NO_AUTO_INLINE` is.  Maybe the commit message says why it's useful.

**Comment by nathanchance** [comment]
> > when -fno-inline-functions is supplied
> 
> Is the kernel using that for `CONFIG_NO_AUTO_INLINE`? I get the feeling that they may be hitting quite a few of these kind of errors.

Yes:

```make
ifdef CONFIG_NO_AUTO_INLINE
KBUILD_CFLAGS   += $(call cc-option, -fno-inline-functions) \
		   $(call cc-option, -fno-inline-small-functions) \
		   $(call cc-option, -fno-inline-functions-called-once)
endif
```

> I think some commit message explaining that `-fno-inline-functions` from `CONFIG_NO_AUTO_INLINE` causes this specific bug to longer be ICE with Clang is fine.

Sounds reasonable, thanks!

> I'm curious too what the point of `CONFIG_NO_AUTO_INLINE` is. Maybe the commit message says why it's useful.

https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=9b76795cc32426e68ca1c647b6d31c7148940719

I personally think this is something that should not be selectable by the user (so `allyesconfig` can't explicitly turn it on), rather being selected by options that require it and that was [suggested by Stephen Rothwell](https://lore.kernel.org/lkml/20181206095815.6e814057@canb.auug.org.au/).

As an aside, there's another issue exacerbated by this config in a staging module:

```
ERROR: "is_broadcast_mac_addr" [drivers/staging/rtl8723bs/r8723bs.ko] undefined!
ERROR: "is_zero_mac_addr" [drivers/staging/rtl8723bs/r8723bs.ko] undefined!
ERROR: "is_multicast_mac_addr" [drivers/staging/rtl8723bs/r8723bs.ko] undefined!
```

The root cause is `extern` functions in a header that is never actually included in any of the files that the function is used in...

```c
extern __inline int is_multicast_mac_addr(const u8 *addr)
{       
        return ((addr[0] != 0xff) && (0x01 & addr[0]));
}              

extern __inline int is_broadcast_mac_addr(const u8 *addr)
{       
        return ((addr[0] == 0xff) && (addr[1] == 0xff) && (addr[2] == 0xff) &&   \
                (addr[3] == 0xff) && (addr[4] == 0xff) && (addr[5] == 0xff));
}              

extern __inline int is_zero_mac_addr(const u8 *addr)
{       
        return ((addr[0] == 0x00) && (addr[1] == 0x00) && (addr[2] == 0x00) &&   \
                (addr[3] == 0x00) && (addr[4] == 0x00) && (addr[5] == 0x00));
}
```

Going to need to mull over how to properly fix that one at some time other than 3am lol.

**Comment by nathanchance** [comment]
Patch submitted: https://lore.kernel.org/lkml/20181210234538.5405-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch rejected by Thomas Gleixner: https://lore.kernel.org/lkml/alpine.DEB.2.21.1901161848560.1642@nanos.tec.linutronix.de/

It's a moot point currently because `CONFIG_NO_AUTO_INLINE` doesn't exist in mainline or next but if it comes back, I think that we should either add `depends on CC_IS_GCC` or `-finline-hint-functions` instead of `-fno-inline-functions`, which is what `-fno-inline-functions` means for GCC.

I'm closing this with won't fix for now. If it becomes an issue in the future, I'll reopen.

**Comment by arndb** [comment]
The problem here is that ptrs_per_p4d is not a compile-time constant on x86 when CONFIG_X86_5LEVEL is set. I don't know how it's possible to compiles this with gcc though.

**Comment by arndb** [comment]
I sent a patch: https://lore.kernel.org/lkml/20210107223424.4135538-1-arnd@kernel.org/T/#u

**Comment by nathanchance** [comment]
Because this is now relevant again due to `CONFIG_UBSAN_UNSIGNED_OVERFLOW`, I am reopening.

I agree with Arnd's patch, the reduction makes it pretty obvious although I am still confused as to how this code works in the current state without that `CONFIG_`: https://github.com/nathanchance/creduce-files/tree/7c5b59c29fdb94e558929d100fdb2d7a3f9c709c/cbl-256-ubsan

**Comment by dileks** [comment]
Alternative `[PATCH] x86/efi: Remove EFI PGD build time checks` from `Boris Petkov`.

[1] https://lore.kernel.org/lkml/20210205113930.GD17488@zn.tnic/

**Comment by nathanchance** [comment]
Merged into `x86/urgent`: https://git.kernel.org/tip/816ef8d7a2c4182e19bc06ab65751cb9e3951e94

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/816ef8d7a2c4182e19bc06ab65751cb9e3951e94
