### ISSUE TITLE
[ppc32] unknown argument '-ffixed-r2', unknown argument: '-mmultiple'

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/linux#261]
```
make CC=clang-8 ARCH=powerpc CROSS_COMPILE=powerpc-linux-gnu-  ppc44x_defconfig
make CC=clang-8 ARCH=powerpc CROSS_COMPILE=powerpc-linux-gnu-

clang: error: unknown argument '-ffixed-r2', did you mean '-ffixed-r9'?
clang: error: unknown argument: '-mmultiple'
```

We can disable them, and the kernel builds and boots. We need to understand if it's okay to omit them.

**Comment by shenki** [comment]
http://ozlabs.org/~joel/0001-Revert-powerpc-HACK-Disable-unsupported-flags.patch

**Comment by shenki** [comment]
r2 is always reserved by clang on ppc32:

```
  // The SVR4 ABI reserves r2 and r13
  if (Subtarget.isSVR4ABI()) {
    // We only reserve r2 if we need to use the TOC pointer. If we have no
    // explicit uses of the TOC pointer (meaning we're a leaf function with
    // no constant-pool loads, etc.) and we have no potential uses inside an
    // inline asm block, then we can treat r2 has an ordinary callee-saved
    // register.
    const PPCFunctionInfo *FuncInfo = MF.getInfo<PPCFunctionInfo>();
    if (!TM.isPPC64() || FuncInfo->usesTOCBasePtr() || MF.hasInlineAsm())
      markSuperRegs(Reserved, PPC::R2);  // System-reserved register
    markSuperRegs(Reserved, PPC::R13); // Small Data Area pointer register
  }
```

So we can omit the `-ffixed-r2` flag safely.

**Comment by shenki** [comment]
We speculated that the kernel uses `-mmultiple` on CPUs that support it (ppc32be) for compact and nicer code, so it is safe to leave out with clang. It's not clear that clang 8 generates the multi-word instructions (I think not).

**Comment by shenki** [comment]
https://patchwork.ozlabs.org/patch/992185/

**Comment by nathanchance** [comment]
Hmmm looks like you might have forgot to uncomment the `CFLAGS` line.

I'd probably just hide them behind `cc-option` (that's what it's there for) but I guess if you know that Clang is never going to support them then just gating them is equivalent.

**Comment by shenki** [comment]
llvm bug requesting a -ffixed-r2: https://llvm.org/pr39555

**Comment by shenki** [comment]
llvm bug requesting -mmultiple: https://llvm.org/pr39556

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=72e7bcc2cdf82bf03caaa5e6c9b0134c2fc2ee7d
