### ISSUE TITLE
llvm-ar is not able to produce proper thin archives

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#279]
When linking the following error is produced when using malformed thin archive:
    - with ld.bfd: `ld: built-in.a: member init/built-in.a in archive is not an object`
    - with ld.lld: `ld.lld: error: init/built-in.a: invalid data encoding`

I will check the difference between GNU ar and llvm-ar produced archives and post my findings here.

**Comment by tpimh** [comment]
https://llvm.org/pr37530

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D56508

**Comment by rupprecht** [comment]
Fix committed to llvm-ar in r351120. Do you mind re-testing with llvm-ar from trunk and opening another bug if there are still issues (aside from the other P option bug)?

**Comment by nickdesaulniers** [comment]
AaronBallman says that llvm-8 is being branched Wednesday, so this should make the cut (I'm still trying to confirm).  Thanks @rupprecht !!

**Comment by rupprecht** [comment]
A fix found while testing llvm-ar for the kernel has been fixed in r353424

**Comment by nickdesaulniers** [comment]
Thanks so much @rupprecht !

**Comment by nickdesaulniers** [comment]
sounds like this got reverted. Reopening.

**Comment by gwelymernans** [comment]
I'm having an issue with the patch as well. (It may be related to what people are seeing.) I reported it on D56508. Basically this doesn't work:

```
$ mkdir -p foo/bar
$ cat > foo/bar/a.c <<EOF
int bar() { return 42; }
EOF
$ rm -f built-in.o foo/built-in.o foo/bar/built-in.o ; llvm-ar rcSTD foo/bar/built-in.o foo/bar/a.o ; llvm-ar rcSTD foo/built-in.o foo/bar/built-in.o ; llvm-ar rcSTD built-in.o foo/built-in.o
./llvm.opt.install/bin/llvm-ar: error: 'a.o': No such file or directory.
```

**Comment by nickdesaulniers** [comment]
Sounds like this is all set?
https://lore.kernel.org/r/CAK7LNATY8-hJ6QouGjO4wvsw8+W60HhLfNk60RZWyNz4s5fv_w@mail.gmail.com/

@tpimh can you test/confirm/close this issue if so? (I mean @masahir0y could, too, doesn't matter, but would be good to get 2 confirmations)

**Comment by nickdesaulniers** [comment]
So fixed in 353424, reverted in 353507, re-fixed in:
Fixed in https://reviews.llvm.org/rL353995

WFM w/ arm64.  Thanks @rupprecht !
