### ISSUE TITLE
lld unable to link arm64 KASLR

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#280]
`CONFIG_RANDOMIZE_BASE=y` selects `CONFIG_RELOCATABLE` which adds `-pie -shared` to `LDFLAGS_vmlinux` which produces the following linkage error:

```sh
ld.lld: error: -shared and -pie may not be used together
```

**Comment by nickdesaulniers** [comment]
https://llvm.org/pr39810

**Comment by nickdesaulniers** [comment]
Additionally, there are the following warnings with that config:
```sh
ld.lld: error: discarding .dynamic section is not allowed
ld.lld: error: discarding .dynsym section is not allowed
ld.lld: error: discarding .dynstr section is not allowed
```
Seems to come from commit 08cc55b2afd97a654f71b3bebf8bb0ec89fdc498 ("arm64: relocatable: suppress R_AARCH64_ABS64 relocations in vmlinux"). TODO: file another bug about these, but I have a feeling they're all related.

**Comment by nickdesaulniers** [comment]
Three patches posted upstream:
https://github.com/ClangBuiltLinux/continuous-integration/pull/87/files

**Comment by nickdesaulniers** [comment]
LLVM patches:
https://reviews.llvm.org/D55211
https://reviews.llvm.org/D55218
https://reviews.llvm.org/D55215
https://reviews.llvm.org/D55423

Kernel patches:
https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git/commit/?h=for-next/core&id=dd6846d774693bfa27d7db4dae5ea67dfe373fa1
https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git/commit/?h=for-next/core&id=3bbd3db86470c701091fb1d67f1fab6621debf50

**Comment by nickdesaulniers** [comment]
Assigning to @GeorgiiR , since they have the 4 outstanding fixes to land.

**Comment by nickdesaulniers** [comment]
Additional lld patch: https://reviews.llvm.org/D55550

**Comment by nickdesaulniers** [comment]
So I think the final two patches have landed for this (https://reviews.llvm.org/D55423, https://reviews.llvm.org/D55550), I need to verify.  Thanks @GeorgiiR @rui314 and @smithp35 for the work and thought that went into this support.  Assuming those 2 are good, then I think #340 is the FINAL issue for LLD + aarch64.

**Comment by nickdesaulniers** [comment]
https://llvm.org/pr39857

**Comment by tpimh** [comment]
https://github.com/ClangBuiltLinux/linux/commit/3bbd3db86470c701091fb1d67f1fab6621debf50 https://github.com/ClangBuiltLinux/linux/commit/dd6846d774693bfa27d7db4dae5ea67dfe373fa1
