### ISSUE TITLE
reloc 58 missing lld+ppc

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#285]
forked from https://github.com/ClangBuiltLinux/linux/issues/255#issuecomment-442259136

cc @shenki @martell 

```c
#define R_PPC64_GOT16_DS	58 /* half16ds* (G + A) >> 2 */
```

**Comment by martell** [comment]
Upstream patch created
https://reviews.llvm.org/D55498

**Comment by martell** [comment]
Should be resolved in https://reviews.llvm.org/rL349511
