### ISSUE TITLE
`--pic-vineer` for arm32 lld

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#286]
https://reviews.llvm.org/D55505

**Comment by nathanchance** [comment]
I tested this patch with `defconfig`, where it works without any issues. However, with `allyesconfig`, I get the following errors:

```
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4410603944 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4411261224 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4411458860 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4408657128 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4392320160 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4412194940 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4412002028 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4410626800 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4392320280 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4410135732 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4410937664 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4375736156 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4411188840 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4412035056 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4392320928 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4410970328 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4375736960 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4411222636 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4392320420 is not in [-2147483648, 2147483647]
ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4411261436 is not in [-2147483648, 2147483647]
ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
```

I'm exhausted so debugging probably isn't a great idea at the moment but I should be able to triage further tomorrow (unless someone beats me to it).

Just an FYI, `lld` without this patch + https://lore.kernel.org/lkml/20181205014213.943-2-natechancellor@gmail.com/ links (with a couple of hacks to work around #35 + #287).

**Comment by nathanchance** [comment]
> I tested this patch with `defconfig`, where it works without any issues. However, with `allyesconfig`, I get the following errors:
> 
> ```
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4410603944 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4411261224 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4411458860 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4408657128 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4392320160 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4412194940 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4412002028 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4410626800 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4392320280 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4410135732 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4410937664 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4375736156 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4411188840 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4412035056 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4392320928 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4410970328 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4375736960 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4411222636 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4392320420 is not in [-2147483648, 2147483647]
> ld.lld: error: relocation R_ARM_MOVT_PREL out of range: -4411261436 is not in [-2147483648, 2147483647]
> ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
> ```
> I'm exhausted so debugging probably isn't a great idea at the moment but I should be able to triage further tomorrow (unless someone beats me to it).
> 
> Just an FYI, `lld` without this patch + https://lore.kernel.org/lkml/20181205014213.943-2-natechancellor@gmail.com/ links (with a couple of hacks to work around #35 + #287).

**Comment by ardbiesheuvel** [comment]
GCC never uses place-relative movw/movt pairs, and while it seems appealing for position independent code, the fact that ARM uses REL type relocations (which put the addend in the place rather in than in the relocation), and the fact that the addend needs to be duplicated between the two instructions (or you wouldn't be able to handle a carry between the low and the high part ), the addend range is only [-32k, 32k), and I am not surprised this breaks when building an allyesconfig kernel (which is huge)

I know Clang does support -mno-movt, but this gets rid of movw/movt pairs entirely, which would be unfortunate.

**Comment by nathanchance** [comment]
Ah, so that particular set of errors is something that needs to fixed/addressed in Clang?

**Comment by smithp35** [comment]
I will take a look when I get back to the office next January. I'm interested to see where the PC-Relative use of movt/movw comes from. They should only be generated from compiled code when position independent, but when -fpic or -fpie is used it looks like care is taken to avoid using movt/movw.

**Comment by smithp35** [comment]
I've submitted https://reviews.llvm.org/D56396 that should fix the relocation overflow problem. The ELF for the ARM Architecture document states that the relocations shouldn't have overflow checking, and it is possible for LLD to inject the values it needs to into the movt/movw pair so I've done that.

**Comment by ardbiesheuvel** [comment]
OK, so the limited range of the addend is not a problem here since we never actually have to deal with the static relocation in the thunk case, right?

**Comment by nathanchance** [comment]
@smithp35 thank you for the fix, I can link an arm32 allyesconfig kernel with D55505 + D56396.

**Comment by smithp35** [comment]
Yes, in this particular case we are just reusing the part of the relocation code that encodes the final result so we don't have to deal with the encoding of the addend in the relocation.

**Comment by nickdesaulniers** [comment]
Looks like both are now fixed.  @smithp35 , will these been in lld-8, or do we need to ask Hans to pick these up?

**Comment by smithp35** [comment]
--pic-veneer just missed the branch. I've created https://llvm.org/pr40352 and linked it to the 8.0 release https://llvm.org/pr40331 as a blocker.

**Comment by nathanchance** [comment]
Added to the 8.0 branch: https://github.com/llvm/llvm-project/commit/37174c6e21dd381fab31e33877865648c8d4088f

Thanks @smithp35!
