### ISSUE TITLE
-Wunknown-warning-option from drivers/pinctrl/aspeed

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#293]
```
warning: unknown warning option '-Woverride-init'; did you mean '-Woverride-module'? [-Wunknown-warning-option]
1 warning generated. 
```

Some more info:

https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/Warning-Options.html#index-Woverride-init

https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/Designated-Inits.html

Patch submitted: https://lore.kernel.org/lkml/20181211000506.7559-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
Sounds like a feature request to clang for `-Woverride-init` as well. :)

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/linusw/linux-pinctrl.git/commit/?id=7f07675c117aac08c403ee02d4a865f76a0ce55a

I'll try to remember to file a Clang bug for this

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7f07675c117aac08c403ee02d4a865f76a0ce55a

I've opened #307 for the feature request.
