### ISSUE TITLE
-m linker option has higher priority than OUTPUT_FORMAT directive

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#30]
Linux kernel uses `OUTPUT_FORMAT` in it's linker scripts. Most of the time `-m` option is passed to the linker with correct architecture, but sometimes (at least for x86_64) the `-m` option contradicts `OUTPUT_FORMAT` directive (which should have higher priority). My fix is crude: just add correct `-m` after incorrect one (it overrides it), so the linker invocation looks like this: `ld -m elf_x86_64  -z max-page-size=0x200000   -m elf_i386 --emit-relocs -T realmode.lds header.o trampoline_64.o stack.o reboot.o -o realmode.elf` (it will also work with GNU ld, because it supports `OUTPUT_FORMAT` and just ignores `-m` options if this directive is in the linker script). Ideal solution would be adding `OUTPUT_FORMAT` support to LLD.

```patch
diff --git a/arch/x86/boot/Makefile b/arch/x86/boot/Makefile
index 9b5adae..e2839b5 100644
--- a/arch/x86/boot/Makefile
+++ b/arch/x86/boot/Makefile
@@ -100,7 +100,7 @@ $(obj)/zoffset.h: $(obj)/compressed/vmlinux FORCE
 AFLAGS_header.o += -I$(objtree)/$(obj)
 $(obj)/header.o: $(obj)/zoffset.h

-LDFLAGS_setup.elf	:= -T
+LDFLAGS_setup.elf	:= -m elf_i386 -T
 $(obj)/setup.elf: $(src)/setup.ld $(SETUP_OBJS) FORCE
 	$(call if_changed,ld)

diff --git a/arch/x86/realmode/rm/Makefile b/arch/x86/realmode/rm/Makefile
index 4463fa7..96cb20d 100644
--- a/arch/x86/realmode/rm/Makefile
+++ b/arch/x86/realmode/rm/Makefile
@@ -47,7 +47,7 @@ $(obj)/pasyms.h: $(REALMODE_OBJS) FORCE
 targets += realmode.lds
 $(obj)/realmode.lds: $(obj)/pasyms.h

-LDFLAGS_realmode.elf := --emit-relocs -T
+LDFLAGS_realmode.elf := -m elf_i386 --emit-relocs -T
 CPPFLAGS_realmode.lds += -P -C -I$(objtree)/$(obj)

 targets += realmode.elf
```

**Comment by nickdesaulniers** [comment]
Just for more info, this is what the failure looks like for realmode:
```sh
  LD      arch/x86/realmode/rm/realmode.elf
ld.lld: error: arch/x86/realmode/rm/header.o is incompatible with elf_x86_64
ld.lld: error: arch/x86/realmode/rm/trampoline_64.o is incompatible with elf_x86_64
ld.lld: error: arch/x86/realmode/rm/stack.o is incompatible with elf_x86_64
ld.lld: error: arch/x86/realmode/rm/reboot.o is incompatible with elf_x86_64
ld.lld: error: arch/x86/realmode/rm/wakeup_asm.o is incompatible with elf_x86_64
ld.lld: error: arch/x86/realmode/rm/wakemain.o is incompatible with elf_x86_64
ld.lld: error: arch/x86/realmode/rm/video-mode.o is incompatible with elf_x86_64
ld.lld: error: arch/x86/realmode/rm/copy.o is incompatible with elf_x86_64
ld.lld: error: arch/x86/realmode/rm/bioscall.o is incompatible with elf_x86_64
ld.lld: error: arch/x86/realmode/rm/regs.o is incompatible with elf_x86_64
ld.lld: error: arch/x86/realmode/rm/video-vga.o is incompatible with elf_x86_64
ld.lld: error: arch/x86/realmode/rm/video-vesa.o is incompatible with elf_x86_64
ld.lld: error: arch/x86/realmode/rm/video-bios.o is incompatible with elf_x86_64
arch/x86/realmode/rm/Makefile:55: recipe for target 'arch/x86/realmode/rm/realmode.elf' failed
```

**Comment by nickdesaulniers** [comment]
LLVM bug: https://llvm.org/pr39290

**Comment by tpimh** [comment]
Possibly again a duplicate of my bug report: https://llvm.org/pr37432

**Comment by tpimh** [comment]
With https://github.com/llvm/llvm-project/commit/ea8cd00a1d1ae8ba47d749ca7bd2c9281e4b1847 and https://github.com/llvm/llvm-project/commit/4ec5d67e49a5df9381b30470b68ebf0d01545dc0 OUTPUT_FORMAT directive is now supported, realmode.elf and setup.elf were linked successfully without adding "-m elf_i386" to LDFLAGS.

**Comment by tpimh** [comment]
Turns out -m option has higher priority than OUTPUT_FORMAT directive, thus OUTPUT_FORMAT is parsed correctly and then overridden. Still applying the same patch to build it. Sorry for closing the issue prematurely, reopening.

**Comment by nickdesaulniers** [comment]
@gwelymernans is also looking into this with: https://reviews.llvm.org/D55311. Still discussing this internally with LLD devs.

**Comment by tpimh** [comment]
It was reported to kernel bugzilla by George Rimar: https://bugzilla.kernel.org/show_bug.cgi?id=194091

**Comment by nickdesaulniers** [comment]
Grimar filed: https://bugzilla.kernel.org/show_bug.cgi?id=194091 with the same patch as suggested by @tpimh . I will try to upstream that patch.

**Comment by nickdesaulniers** [comment]
@vo4 volunteered to help

**Comment by nickdesaulniers** [comment]
@vo4  and I spoke more in person about this.

The kernel is adding `-m elf_x86_64` to the linker command line parameters, but then relying on binutils tie-breaking-behavior by specifying a different architecture via linker script.  So it's ambiguous which arch the kernel is trying to link for, and the kernel gets lucky/relies on the way ld.bfd happens to resolve this ambiguity without warning.  An alternative fix may be to just filter out/remove the `-m elf_x86_64` for this target's linker flags.

@vo4 sent the patch upstream, but I can't seem to find a link.

**Comment by tpimh** [comment]
https://lore.kernel.org/r/CANA+-vBcxF7P1C+zddnqshKwMGuCSb97JC-=3==TwFeEGZP05w@mail.gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/tip/927185c124d62a9a4d35878d7f6d432a166b74e3

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/927185c124d62a9a4d35878d7f6d432a166b74e3

**Comment by nickdesaulniers** [comment]
@MaskRay also fixed this in lld-9: https://bugs.llvm.org/show_bug.cgi?id=37432
