### ISSUE TITLE
integrated assembler does not support security extension using plus syntax

### ISSUE THREAD

**Issue by agners** [ClangBuiltLinux/linux#304]
The integrated assembler does not support selecting the security extension using `+sec`:

```
clang-8: error: the clang compiler does not support '-Wa,-march=armv7-a+sec'
```

This is used by several Arm32 Linux machines (e.g. `arch/arm/mach-bcm/Makefile`).

**Comment by agners** [comment]
Created a feature request in the LLVM bugtracker: https://llvm.org/pr40186

**Comment by nickdesaulniers** [comment]
@agners , does @smithp35 's [suggestion](https://bugs.llvm.org/show_bug.cgi?id=40186) to use `'-Wa,-march=armv7ve'` work for you?

**Comment by nickdesaulniers** [comment]
bump @agners

**Comment by agners** [comment]
@smithp35 suggestion does work, and I guess I could propose a patch making use of this architecture in case the security extension is supported.

However, I came up with an alternative approach which also simplifies things a bit:
https://lore.kernel.org/lkml/9641c58c03720104186a797a96e30a52ae9805e4.1553356359.git.stefan@agner.ch/

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3fe1ee40b2a2db271513a498c475c13572dcb4c6
