### ISSUE TITLE
error: too many positional arguments in arch/arm/lib/copy_template.S

### ISSUE THREAD

**Issue by agners** [ClangBuiltLinux/linux#305]
Using integrated assembler leads to the following error message:

```
<instantiation>:46:47: error: too many positional arguments
  str8w r0, r3, r4, r5, r6, r7, r8, r9, ip, , abort=19f
                                              ^
arch/arm/lib/copy_template.S:277:5: note: while in macro instantiation
18: forward_copy_shift pull=24 push=8
    ^
```

**Comment by agners** [comment]
https://lore.kernel.org/r/e5aa8bda88280b9cc76e52e386b216a4b1eeb557.1546185298.git.stefan@agner.ch/

**Comment by tpimh** [comment]
Should this be considered submitted then?

**Comment by nickdesaulniers** [comment]
v2: https://lore.kernel.org/r/591c1d362838b8a83e1fdfea37f7b48fd85dbf44.1546551693.git.stefan@agner.ch/

**Comment by agners** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=baf2df8e15be22b8bd24bdd6fd4575b6641bcfd1
