### ISSUE TITLE
-Woverride-init for Clang

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#307]
From GCC's manual: https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/Warning-Options.html#index-Woverride-init

@nickdesaulniers who should I cc on the LLVM bug tracker aside from you for Clang issues?

**Comment by nickdesaulniers** [comment]
Probably Richard Smith (code owner for Clang).

**Comment by nathanchance** [comment]
LLVM bug: https://llvm.org/pr40251

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D56522

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/rL350877
