### ISSUE TITLE
-Wstring-plus-int in drivers/isdn/hardware/avm/b1.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#309]
```
/home/nathan/cbl/linux-next/drivers/isdn/hardware/avm/b1.c:426:30: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
                cinfo->version[j] = "\0\0" + 1;
                                    ~~~~~~~^~~
/home/nathan/cbl/linux-next/drivers/isdn/hardware/avm/b1.c:426:30: note: use array indexing to silence this warning
                cinfo->version[j] = "\0\0" + 1;
                                           ^
                                    &      [  ]
1 warning generated.
```

Introduced by https://github.com/ClangBuiltLinux/clang/commit/a11ecd118716ebfbbcf77a48fffe7fa7bddad738. This diff should fix it properly (disassembly shows no difference). Just need to draft up the commit message and send it along (I'm probably going to wait until after -rc1 so that nothing gets lost plus I want to ping old patches).

```diff
diff --git a/drivers/isdn/hardware/avm/b1.c b/drivers/isdn/hardware/avm/b1.c
index 4ac378e48902..7fa8141e2019 100644
--- a/drivers/isdn/hardware/avm/b1.c
+++ b/drivers/isdn/hardware/avm/b1.c
@@ -423,7 +423,7 @@ void b1_parse_version(avmctrl_info *cinfo)
        int i, j;
 
        for (j = 0; j < AVM_MAXVERSION; j++)
-               cinfo->version[j] = "\0\0" + 1;
+               cinfo->version[j] = "\0";
        for (i = 0, j = 0;
             j < AVM_MAXVERSION && i < cinfo->versionlen;
             j++, i += cinfo->versionbuf[i] + 1)
```

**Comment by nickdesaulniers** [comment]
LGTM

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20190108050649.9962-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
Thinking more about this, I think just `= "";` is better since the empty string literal is **still** NULL terminated.

**Comment by nathanchance** [comment]
v2: https://lore.kernel.org/lkml/20190110054107.6069-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted and should be in mainline shortly: https://git.kernel.org/pub/scm/linux/kernel/git/davem/net.git/commit/?id=7afa81c55fca0cad589722cb4bce698b4803b0e1

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/7afa81c55fca0cad589722cb4bce698b4803b0e1
