### ISSUE TITLE
LLD doesn't support common-page-size=value keyword

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#31]
I just remove this option and it works fine without it.

```patch
diff --git a/arch/x86/entry/vdso/Makefile b/arch/x86/entry/vdso/Makefile
index fa3f439..293fa4c 100644
--- a/arch/x86/entry/vdso/Makefile
+++ b/arch/x86/entry/vdso/Makefile
@@ -47,7 +47,7 @@ targets += $(vdso_img_sodbg) $(vdso_img-y:%=vdso%.so)
 CPPFLAGS_vdso.lds += -P -C

 VDSO_LDFLAGS_vdso.lds = -m elf_x86_64 -soname linux-vdso.so.1 --no-undefined \
-                       -z max-page-size=4096 -z common-page-size=4096
+                       -z max-page-size=4096

 $(obj)/vdso64.so.dbg: $(obj)/vdso.lds $(vobjs) FORCE
        $(call if_changed,vdso)
@@ -92,7 +92,7 @@ CFLAGS_REMOVE_vvar.o = -pg

 CPPFLAGS_vdsox32.lds = $(CPPFLAGS_vdso.lds)
 VDSO_LDFLAGS_vdsox32.lds = -m elf32_x86_64 -soname linux-vdso.so.1 \
-                          -z max-page-size=4096 -z common-page-size=4096
+                          -z max-page-size=4096

 # x32-rebranded versions
 vobjx32s-y := $(vobjs-y:.o=-x32.o)
```

**Comment by nickdesaulniers** [comment]
I'd be curious if this can be masked out with `ld-option` or is required.  Will need to take a look at the documentation to see what it does.

**Comment by nickdesaulniers** [comment]
Looks like lld has some strange handling of unknown flags that prevents `ldoption` from detecting support correctly.

```sh
➜  linux git:(master) ✗ ld.lld -z common-page-size=4096 -v                         
LLD 8.0.0 (compatible with GNU linkers)
➜  linux git:(master) ✗ echo $?
0

➜  linux git:(master) ✗ ld.lld -adfasdf -v                
ld.lld: error: unknown argument: -adfasdf
LLD 8.0.0 (compatible with GNU linkers)
➜  linux git:(master) ✗ echo $?                           
1

➜  linux git:(master) ✗ ld.lld -z common-page-size=4096   
ld.lld: error: unknown -z value: common-page-size=4096
➜  linux git:(master) ✗ echo $?                        
1
```

So it seems that `-v` can mask invalid `-z` values, which is problematic for how the Linux kernel's KBUILD build system detects linker flag support.

**Comment by nickdesaulniers** [comment]
LLVM Bugs:
* [Support -z common-page-size=](https://bugs.llvm.org/show_bug.cgi?id=39288)
* [-v can mask unknown -z value errors](https://bugs.llvm.org/show_bug.cgi?id=39289)

**Comment by tpimh** [comment]
I already reported the first one: [Support common-page-size=value keyword](https://bugs.llvm.org/show_bug.cgi?id=38774). Sorry for not linking it here.

**Comment by tpimh** [comment]
This option is also used by the [FreeBSD kernel](https://github.com/freebsd/freebsd/blob/e5f2eb7b67d4eafd7e30ca027e009494867f3d0b/sys/conf/kern.pre.mk#L136).

**Comment by nickdesaulniers** [comment]
I've wrapped your patch above in the commit message:

```
    x86/vdso: drop implicit common-page-size linker flag
    
    These are implied by the target architecture and for x86_64 match the
    max-page-size. The default for non-NaCl x86_64 is 0x1000 (4096).

    In bfd the common page size is defined as 0x1000 (4096) for non-NaCl
    x86_64 targets:
    
    bfd/elf64-x86-64.c:
    4998:#define ELF_COMMONPAGESIZE             0x1000
    
    For gold, the common page size is defined as 0x1000 (4096) for non-NaCl
    x86_64 targets:
    
    gold/x86_64.cc:
    1413:  0x1000, // common_pagesize (overridable by -z common-page-size)
    1442:  0x1000, // common_pagesize (overridable by -z common-page-size)
    
    (ELF_COMMONPAGESIZE also defaults to ELF_MAXPAGESIZE when not set
    explicitly for a target architecture in bfd/elfxx-target.h, but that's
    not relevant for x86_64).
    
    Because it's implied by the target architecture, it's of questionable
    use to implement in LLD.  This patch resolves one of the issues towards
    using LLD to link an x86_64 kernel.
```

Doing some final internal testing and then hope to upstream soon/ASAP.

**Comment by nickdesaulniers** [comment]
@gwelymernans is also helping verify/test.

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/r/20181206191231.192355-1-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/tip/ac3e233d29f7f77f28243af0132057d378d3ea58

**Comment by nickdesaulniers** [comment]
Fix landed in Linux 4.20-rc6 

commit ac3e233d29f7f77f28243af0132057d378d3ea58 ("x86/vdso: Drop implicit common-page-size linker flag")

So this flag is still not supported in LLD, but it seems that this will be ok going forward; a break from binutils that makes sense IMO.

**Comment by tpimh** [comment]
Fix was backported to 4.9, 4.14, 4.19.

**Comment by nickdesaulniers** [comment]
IIRC, this is still an issue for arm32?

**Comment by tpimh** [comment]
Yes, you are right. https://github.com/ClangBuiltLinux/linux/blob/6f0d349d922ba44e4348a17a78ea51b7135965b1/arch/arm/vdso/Makefile#L14

Should a separate issue for arm be created or should we reopen this one?

**Comment by nickdesaulniers** [comment]
Can you please file a new issue?  I had sent a patch for arm32, needs to be rebase/resent.

**Comment by tpimh** [comment]
I couldn't find your patch could you please add link to it to #451?

**Comment by nickdesaulniers** [comment]
FWIW: https://llvm.org/pr38774 support was added to LLD by @smithp35 in https://reviews.llvm.org/rL360593.
