### ISSUE TITLE
Real time conversation method

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#311]
Spin off from https://github.com/ClangBuiltLinux/continuous-integration/issues/66#issuecomment-453158242

There have been times where I've wanted a way to collaborate with contributors in real time rather than playing email ping pong. I am sure everyone is familiar with IRC. Slack is another one that people like to use, mainly because you can have multiple channels in one workspace to discuss different topics and it has some nice integration with [GitHub](https://slack.github.com/) and [Travis CI](https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications). @tapaswenipathak mentioned [Gitter](https://gitter.im/), made by the folks at Gitlab (I have no experience with it though).

This wouldn't be a replacement for GitHub issues and emails because those are great asynchronous methods of communication. However, it could be a good jumping off point for getting more involved with the community, as we can have a way for everyone to join ([e.g. Slack](https://get.slack.help/hc/en-us/articles/201330256-Invite-new-members-to-your-workspace)). I get the feeling that there are some people who get scared by posting to an issue tracker (I know I did initially with the LLVM one), it could be another method of fielding bug reports from other developers/users.

Opinions?

**Comment by nathanchance** [comment]
> my opinion isn't important

I respectfully disagree :)

Thank you for the input, outsider opinions matter too since this will be one tool to get people involved and this isn't a closed project.

**Comment by tapaswenipathak** [comment]
I prefer mails and GitHub tickets anytime, no hassle and clutter free; async always works better for me. Much better than live chat which I least prefer but should have it as an option so I asked. Anything is fine.

If your main task is to get more contributors, try Gitter. It is made with a mindset of open source projects, extremely open and great GitHub integration. Do one thing try Slack integration with some repository and post comments or create pull request and see how Slack publishes it. I prefer less clutter.

**Comment by nathanchance** [comment]
> If your main task is to get more contributors

That's one of the many reasons for this but not the only one.

The more I think about it, I think IRC is the way to go. It's got a low barrier of entry for newbies and it has been an established platform for seasoned developers. But I am willing to hear from others :)

**Comment by tapaswenipathak** [comment]
> It's got a low barrier of entry for newbies and it has been an established platform for seasoned developers. 

About IRC - you really miss out on a lot of useful and needed things. You can't even send a file using IRC, can't indent code. I'm surprised you think it got a low barrier of entry, IRC has the highest barrier of entry. The only reason I see IRC still running is as it's a geekish product.

**Comment by tapaswenipathak** [comment]
> It's got a low barrier of entry for newbies and it has been an established platform for seasoned developers. 

About IRC - you really miss out on a lot of useful and needed things. You can't even send a file using IRC, can't indent code. I'm surprised you think it got a low barrier of entry, it has the highest barrier of entry. The only reason I see IRC still running is as it's a geekish product.

**Comment by nathanchance** [comment]
I more meant it's easy to get in and start chatting with because there are web and terminal clients. However, I agree that one of the more "polished" services like Gitter, Slack, or Discord is easier to use and has all of that nice integration.

You do make a good point about the code indentation and such since this could be used for patch planning and such.

**Comment by tapaswenipathak** [comment]
Ah that's your view, good to know.

**Comment by tapaswenipathak** [comment]
Ah that's your view, good point.

**Comment by shenki** [comment]
I would be happy with IRC.

In OpenBMC land we point people towards Roit/Matrix if they prefer a Slack/Hangouts style UI. This allows them to join the IRC channel from their device of choice, and hopefully lowers the barrier to entry for contributors who aren't familiar with IRC.

**Comment by kragniz** [comment]
I'm in `#clangbuiltlinux` on chat.freenode.net if anyone wants to join.

**Comment by nathanchance** [comment]
Thanks, I'll try to join up when I can figure out IRC :P

Closing this for now.
