### ISSUE TITLE
intent to deprecate our clang/llvm mirrors for new github monorepo

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#312]
Now that llvm has officially moved to github, I'd like to delete our [clang](https://github.com/ClangBuiltLinux/clang) and [llvm](https://github.com/ClangBuiltLinux/llvm) that were forked from an unofficial mirror, in favor of our fork of [the new llvm monorepo from github](https://github.com/ClangBuiltLinux/llvm-project).

Thoughts for/against?

We have no outstanding branches hosting temp patches, so they should be ready for deletion.  I think @tpimh set up auto updaters for those repos; I'm not sure how to turn them off and on for old/new repos.

**Comment by nathanchance** [comment]
I'm fine with it. We turned off the auto updater bot because the email spam was too much. They're being updated via a cron on my server, which I will update shortly for this change.

**Comment by gwelymernans** [comment]
It's the 90's. Go for it.

**Comment by nickdesaulniers** [comment]
[So it is written, so it shall be done](https://www.youtube.com/watch?v=PptHWHfnCnY).
