### ISSUE TITLE
__compiletime_assert_ in arch/x86/kvm/x86.o: In function guest_cpuid_has'`

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#315]
Forked from #6 

```
arch/x86/kvm/x86.o: In function `guest_cpuid_has':
x86.c:(.text+0x11c5c): undefined reference to `__compiletime_assert_64'
x86.c:(.text+0x11cb3): undefined reference to `__compiletime_assert_65'
x86.c:(.text+0x11d93): undefined reference to `__compiletime_assert_89'
```
These linkage failures are failed `BUILD_BUG_ON`s.  Related to asm goto or not?

**Comment by nathanchance** [comment]
It's probably the `BUILD_BUG` and `BUILD_BUG_ON`s in `x86_feature_cpuid` and `guest_cpuid_get_register`.

With https://github.com/nathanchance/linux/commits/no-asm-goto and a build of Clang @ https://github.com/llvm/llvm-project/commit/e50d9cb3649bdf6521f92fd1e4cee3a690638159, I do not see these errors.

I'll see if a build with https://github.com/nathanchance/linux/commits/asm-goto, https://reviews.llvm.org/D53765, and https://reviews.llvm.org/D56571 shows these errors.

**Comment by nickdesaulniers** [comment]
I think I found them.  IIRC, empty `BUILD_BUG();`s are a problem.  Not sure about the others.

```diff

diff --git a/arch/x86/kvm/cpuid.h b/arch/x86/kvm/cpuid.h
index 9a327d5b6d1f..bfc827d96d26 100644
--- a/arch/x86/kvm/cpuid.h
+++ b/arch/x86/kvm/cpuid.h
@@ -61,8 +61,8 @@ static __always_inline struct cpuid_reg x86_feature_cpuid(unsigned x86_feature)
 {
        unsigned x86_leaf = x86_feature / 32;
 
-       BUILD_BUG_ON(x86_leaf >= ARRAY_SIZE(reverse_cpuid));
-       BUILD_BUG_ON(reverse_cpuid[x86_leaf].function == 0);
+       //BUILD_BUG_ON(x86_leaf >= ARRAY_SIZE(reverse_cpuid));
+       //BUILD_BUG_ON(reverse_cpuid[x86_leaf].function == 0);
 
        return reverse_cpuid[x86_leaf];
 }
@@ -86,7 +86,6 @@ static __always_inline int *guest_cpuid_get_register(struct kvm_vcpu *vcpu, unsi
        case CPUID_EDX:
                return &entry->edx;
        default:
-               BUILD_BUG();
                return NULL;
        }
 }
```

**Comment by nickdesaulniers** [comment]
Also, to reproduce, you're going to want to turn on `CONFIG_KVM` which is not part of the defconfig.  `./scripts/config -e CONFIG_KVM` is enough, though you will get prompted for intel vs amd kvm (you can select No for both and still repro).

**Comment by nathanchance** [comment]
Probably something along the lines of #191? Wonder if converting those functions to macros helps.

**Comment by dileks** [comment]
Not sure if this is related as I have `CONFIG_KVM=m` and `CONFIG_KVM_INTEL=m` and see:
```
make -f ./scripts/Makefile.modpost
  find .tmp_versions -name '*.mod' | xargs -r grep -h '\.ko$' | sort -u | sed 's/\.ko$/.o/' | scripts/mod/modpost -m  -o ./Module.symvers    -S    -s -T -
ERROR: "__compiletime_assert_64" [arch/x86/kvm/kvm.ko] undefined!
ERROR: "__compiletime_assert_89" [arch/x86/kvm/kvm.ko] undefined!
ERROR: "__compiletime_assert_65" [arch/x86/kvm/kvm.ko] undefined!
ERROR: "__compiletime_assert_64" [arch/x86/kvm/kvm-intel.ko] undefined!
ERROR: "__compiletime_assert_89" [arch/x86/kvm/kvm-intel.ko] undefined!
ERROR: "__compiletime_assert_65" [arch/x86/kvm/kvm-intel.ko] undefined!
make[4]: *** [scripts/Makefile.modpost:92: __modpost] Error 1
```

For testing purposes I have disabled both Kconfigs.

**Comment by dileks** [comment]
With attached (adapted) patch I do not see the errors in above mentioned in my Linux kvm/x86 setup.

As a side-note:
Comments in the linux-kernel community are done for single-liners by `/* ... */` for multi-liners see `Documentation/process/coding-style.rst` -> `8) Commenting` [1] in case you did not know.

I am using a `#if 0 ... #endif` block for doing such temporary workarounds.
[2] says:

>Lines beginning with a # are preprocessor directives. #if 0 [...] #endif blocks do not make it to the compiler and will generate no machine code.

Last comments suggests to use `#ifdef DEBUG` if you have a DEBUG define.
Does the linux-kernel provide such a define for a debugging case?
Can you comment on this?
[ Yes, I want to improve my skills :-). ]

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/coding-style.rst#n522
[2] https://stackoverflow.com/questions/2852913/what-exactly-does-an-if-0-endif-block-do

[0001-KVM-x86-asm-goto-Workaround-CBL-issue-315-and-316.patch.txt](https://github.com/ClangBuiltLinux/linux/files/2802023/0001-KVM-x86-asm-goto-Workaround-CBL-issue-315-and-316.patch.txt)

**Comment by dileks** [comment]
Fixed by @arndb patch "build_bug.h: add wrapper for _Static_assert"?

[1] https://git.kernel.org/pub/scm/linux/kernel/git/arnd/playground.git/commit/?h=randconfig-5.1-next&id=17f62618a0caea6c381a091789b7042f4d654d9b

**Comment by nickdesaulniers** [comment]
no longer reproducible (I believe the patch @dileks points out is correct)
