### ISSUE TITLE
__compiletime_assert_ in arch/x86/kvm/vmx/vmx.o: In function guest_cpuid_has'

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#316]
Forked from #6 

```
arch/x86/kvm/vmx/vmx.o: In function `guest_cpuid_has':
vmx.c:(.text+0x376c): undefined reference to `__compiletime_assert_64'
vmx.c:(.text+0x37c3): undefined reference to `__compiletime_assert_65'
vmx.c:(.text+0x38a3): undefined reference to `__compiletime_assert_89'
```
is a failed `BUILD_BUG_ON`.  Where is this coming from, and is it related to asm goto?

**Comment by nathanchance** [comment]
It's probably the `BUILD_BUG` and `BUILD_BUG_ON`s in `x86_feature_cpuid` and `guest_cpuid_get_register`.

With https://github.com/nathanchance/linux/commits/no-asm-goto and a build of Clang @ https://github.com/llvm/llvm-project/commit/e50d9cb3649bdf6521f92fd1e4cee3a690638159, I do not see these errors.

I'll see if a build with https://github.com/nathanchance/linux/commits/asm-goto, https://reviews.llvm.org/D53765, and https://reviews.llvm.org/D56571 shows these errors.

**Comment by nickdesaulniers** [comment]
Requires `CONFIG_KVM_INTEL` and `CONFIG_KVM`.  same fix as #315.

**Comment by dileks** [comment]
@nathanchance s/ifndef CONFIG_CC_HAVE_ASM_GOTO/ifndef CONFIG_CC_HA*S*_ASM_GOTO

**Comment by nathanchance** [comment]
@dileks thank you, also fixed in our CI.

**Comment by nickdesaulniers** [comment]
no longer reproducible
