### ISSUE TITLE
reference from the function test_and_clear_bit() to the variable .init.data:nmi_ipi_mask

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#317]
Forked from #6 

```
WARNING: vmlinux.o(.text+0x25bbdc): Section mismatch in reference from the function test_and_clear_bit() to the variable .init.data:nmi_ipi_mask
The function test_and_clear_bit() references
the variable __initdata nmi_ipi_mask.
This is often because test_and_clear_bit lacks a __initdata 
annotation or the annotation of nmi_ipi_mask is wrong.
```
related to asm goto, or just a simple section mismatch bug?

**Comment by nathanchance** [comment]
With https://github.com/nathanchance/linux/commits/no-asm-goto and a build of Clang @ https://github.com/llvm/llvm-project/commit/e50d9cb3649bdf6521f92fd1e4cee3a690638159, I do not see this warning.

**Comment by nickdesaulniers** [comment]
Comes from `CONFIG_DEBUG_NMI_SELFTEST` and `CONFIG_DEBUG_SECTION_MISMATCH`.

`test_and_clear_bit` for x86 probably eventually calls `__GEN_RMWcc` which has two different definitions based on `CONFIG_CC_HAS_ASM_GOTO`. (which would explain why Nathan doesn't observe this with a non asm-goto clang).

I'm not sure who's wrong here (in reference to the DEBUG_SECTION_MISMATCH warning).

**Comment by nickdesaulniers** [comment]
reminds me of @arndb 's commit 4aa64677330b ("ARM: ks8695: fix section mismatch warning").  But why would `test_and_clear_bit` need to be marked `__init`?

**Comment by nickdesaulniers** [comment]
When compiled with clang
```
$ objdump -D -r -j .text arch/x86/kernel/nmi_selftest.o
Disassembly of section .text:

0000000000000000 <test_and_clear_bit>:
   0:   31 c0                   xor    %eax,%eax
   2:   f0 48 0f b3 3c 25 00    lock btr %rdi,0x0
   9:   00 00 00 
                        8: R_X86_64_32S .init.data+0x60
   c:   72 02                   jb     10 <test_and_clear_bit+0x10>
   e:   eb 02                   jmp    12 <test_and_clear_bit+0x12>
  10:   b0 01                   mov    $0x1,%al
  12:   c3                      retq   
```
but with gcc-8, there is no `.text` section in that object file.

```c
  264 static __always_inline bool test_and_clear_bit(long nr, volatile unsigned long *addr)                                                                               
```

so this is probably a result of LLVM's WIP asm goto patch not performing inlining when it observes an asm goto statement.

**Comment by nathanchance** [comment]
So `test_nmi_ipi_callback` calls `cpumask_test_and_clear_cpu` (defined in `include/linux/cpumask.h`, marked with inline) which returns a value from `test_and_clear_bit` (defined in `arch/x86/include/asm/bitops.h`, marked with __always_inline)

So what it looks like is happening is `test_and_clear_bit` isn't getting inlined.

**Comment by nickdesaulniers** [comment]
well now we inline properly so the reproducer is stale.  No longer reproducible.

speaking of `CONFIG_DEBUG_SECTION_MISMATCH`, we should probably disable `-Wsection` unless this config is set.  I guess clang adds `-Wsection` to `-Wall` or some other group (whereas gcc doesn't)?

**Comment by nathanchance** [comment]
`-Wsection` and `CONFIG_DEBUG_SECTION_MISMATCH` warn about two different but similar things.

`-Wsection` warns that a function's declaration and definition have conflicting section attributes.

`CONFIG_DEBUG_SECTION_MISMATCH` warns that an init function is used in an non-init function.

I think `-Wsection` should be always be enabled.
