### ISSUE TITLE
llvm-objcopy is not a drop-in replacement for objcopy from GNU binutils

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#32]
It's possible to use LLVM's implementation of objcopy when compiling Linux: `make OBJCOPY=llvm-objcopy`. However this implementation lacks `-S` flag (which should be synonymous to `-strip-all-gnu` which is unique to this implementation). As a workaround I replace `-S` to `-strip-all-gnu` in `OBJCOPYFLAGS` in kernel's makefiles (will break compatibility with objcopy from GNU binutils).
```patch
diff --git a/arch/x86/boot/Makefile b/arch/x86/boot/Makefile
index 9b5adae9cc40..8f8f3f8987ab 100644
--- a/arch/x86/boot/Makefile
+++ b/arch/x86/boot/Makefile
@@ -81,7 +81,7 @@ $(obj)/bzImage: $(obj)/setup.bin $(obj)/vmlinux.bin $(obj)/tools/build FORCE
 	$(call if_changed,image)
 	@$(kecho) 'Kernel: $@ is ready' ' (#'`cat .version`')'

-OBJCOPYFLAGS_vmlinux.bin := -O binary -R .note -R .comment -S
+OBJCOPYFLAGS_vmlinux.bin := -O binary -R .note -R .comment -strip-all-gnu
 $(obj)/vmlinux.bin: $(obj)/compressed/vmlinux FORCE
 	$(call if_changed,objcopy)

diff --git a/arch/x86/boot/compressed/Makefile b/arch/x86/boot/compressed/Makefile
index 28764dacf018..41836d506e0a 100644
--- a/arch/x86/boot/compressed/Makefile
+++ b/arch/x86/boot/compressed/Makefile
@@ -114,7 +114,7 @@ quiet_cmd_check-and-link-vmlinux = LD      $@
 $(obj)/vmlinux: $(vmlinux-objs-y) FORCE
 	$(call if_changed,check-and-link-vmlinux)

-OBJCOPYFLAGS_vmlinux.bin :=  -R .comment -S
+OBJCOPYFLAGS_vmlinux.bin :=  -R .comment -strip-all-gnu
 $(obj)/vmlinux.bin: vmlinux FORCE
 	$(call if_changed,objcopy)

diff --git a/arch/x86/entry/vdso/Makefile b/arch/x86/entry/vdso/Makefile
index fa3f439f0a92..d1be64895fd2 100644
--- a/arch/x86/entry/vdso/Makefile
+++ b/arch/x86/entry/vdso/Makefile
@@ -109,7 +109,7 @@ $(obj)/%-x32.o: $(obj)/%.o FORCE

 targets += vdsox32.lds $(vobjx32s-y)

-$(obj)/%.so: OBJCOPYFLAGS := -S
+$(obj)/%.so: OBJCOPYFLAGS := -strip-all-gnu
 $(obj)/%.so: $(obj)/%.so.dbg
 	$(call if_changed,objcopy)

```

**Comment by nickdesaulniers** [comment]
Cool, thanks for all of these reports.  I think for CFLAGS, KBUILD has a macro that's something logically, like `cc-option` but says "use this flag if that one is not supported."  We used that for some stack related flag that differed between gcc and clang.  Maybe we need a linker-specific version of that macro, or a simple test to use one or the other.

**Comment by tpimh** [comment]
https://reviews.llvm.org/D52163

**Comment by tpimh** [comment]
I close it, because the patch got accepted.

**Comment by nickdesaulniers** [comment]
Congrats! You can also mark me for a reviewer if you need for any Clang/LLVM code reviews.  Happy to see @stephenhines got some good pointers in to code review.
