### ISSUE TITLE
-Wenum-conversion in drivers/scsi/fnic/fnic_main.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#328]
```
drivers/scsi/fnic/fnic_main.c:763:31: warning: implicit conversion from enumeration type 'enum fip_mode' to different enumeration type 'enum fip_state' [-Wenum-conversion]
                fcoe_ctlr_init(&fnic->ctlr, FIP_MODE_AUTO);
                ~~~~~~~~~~~~~~              ^~~~~~~~~~~~~
drivers/scsi/fnic/fnic_main.c:774:31: warning: implicit conversion from enumeration type 'enum fip_mode' to different enumeration type 'enum fip_state' [-Wenum-conversion]
                fcoe_ctlr_init(&fnic->ctlr, FIP_MODE_NON_FIP);
                ~~~~~~~~~~~~~~              ^~~~~~~~~~~~~~~~
```
from mainline x86_64 allyesconfig.

**Comment by dileks** [comment]
This results in a BROKEN build when using lllvm-toolchain-9 with asm-goto support.
I haven't seen @bulwahn has sent a patch for this (CBL issue #151).
For now I have brutally unset all Kconfigs containing FCOE string.

[1] https://patchwork.kernel.org/patch/10589865/

[BROKEN_fcoe_ctlr.txt](https://github.com/ClangBuiltLinux/linux/files/2847985/BROKEN_fcoe_ctlr.txt)

**Comment by nickdesaulniers** [comment]
dup of #152 which was duped to #151.
