### ISSUE TITLE
llvm-ar doesn't support P option

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#33]
It's possible to use LLVM's implementation of ar when compiling Linux: `make AR=llvm-ar`, but llvm-ar doesn't support P option which is used extensively in kernel's makefiles. Removing all P options helped me to advance in compilation, but ld didn't accept the resulting archives complaining about them not being valid thin archives. I'm not sure if those malformed archives have something to do with the P option or is it a completely different issue.

**Comment by nickdesaulniers** [comment]
Do you have the exact warning produced? I'm curious what a "thin archive" is.

**Comment by tpimh** [comment]
I believe this may be a quote from man ar: "The thin archives don't have actual copy of object files. Instead, they have the paths to object files like symbolic links."

The error messages:
 - with ld.bfd: `ld: built-in.a: member init/built-in.a in archive is not an object`
 - with ld.lld: `ld.lld: error: init/built-in.a: invalid data encoding`

I think I you reproduce the problem like this:
```
clang -c -x c /dev/null -o test1.o
clang -c -x c /dev/null -o test2.o
llvm-ar rcSTD test1.a test1.o
llvm-ar rcsTD test2.a test2.o test1.a
llvm-ar t test2.a
```
Then repeat the same process with ar from binutils and compare the output.

**Comment by tpimh** [comment]
Bug report in LLVM bugzilla: https://llvm.org/pr37530

**Comment by nickdesaulniers** [comment]
That bug report doesn't mention the `-P` flag.  Two bugs here or one?

**Comment by tpimh** [comment]
Yes, actually there is another bug report exclusively about `-P` flag: https://llvm.org/pr37436
Maybe I should create a separate issue here about thin archive incompatibility.

**Comment by nickdesaulniers** [comment]
Yes, please.

**Comment by rupprecht** [comment]
I'm looking at adding support for `-P` to llvm-ar now, but it doesn't look like it matters for this usage, i.e. we could just noop `-P` and it wouldn't make a difference as far as these scripts are concerned. The scripts I looked at were all creating brand new thin archives (i.e. they call `rm -f <archive name>; ar rcsTP <archive name> ...`), and the filename used when creating a thin archive is whatever is passed on the command line regardless of the P option. The other bug about malformed thin archives is probably more relevant to making this work. I'll still try to add it though.

Where it *does* seem to make a difference is in searching for archive members, e.g. creating a thin archive with `/tmp/foo.o` in it will find it with `ar tv archive.a foo.o` but not `ar tvP archive.a foo.o`. But that doesn't seem to be happening in any kernel scripts I looked at.

**Comment by nickdesaulniers** [comment]
@rupprecht do you suggest we remove the use of `P` from the relevant kernel scripts?

**Comment by tpimh** [comment]
In case of binutils it does absolutely nothing, GNU ar just ignores it. I guess it is there for some other less popular version of ar.

**Comment by nickdesaulniers** [comment]
So once #279 is fixed, how many cases of `P` exist to remove from the kernel? `KBUILD_ARFLAGS` doesn't seem to be adding `P`.

```diff
diff --git a/scripts/Makefile.build b/scripts/Makefile.build
index fd03d60f6c5a..f8070571dae4 100644
--- a/scripts/Makefile.build
+++ b/scripts/Makefile.build
@@ -404,7 +404,7 @@ ifdef builtin-target
 # table and index.
 quiet_cmd_ar_builtin = AR      $@
       cmd_ar_builtin = rm -f $@; \
-                     $(AR) rcSTP$(KBUILD_ARFLAGS) $@ $(filter $(real-obj-y), $^)
+                     $(AR) rcST$(KBUILD_ARFLAGS) $@ $(filter $(real-obj-y), $^)
 
 $(builtin-target): $(real-obj-y) FORCE
        $(call if_changed,ar_builtin)
@@ -432,7 +432,7 @@ ifdef lib-target
 quiet_cmd_link_l_target = AR      $@
 
 # lib target archives do get a symbol table and index
-cmd_link_l_target = rm -f $@; $(AR) rcsTP$(KBUILD_ARFLAGS) $@ $(lib-y)
+cmd_link_l_target = rm -f $@; $(AR) rcsT$(KBUILD_ARFLAGS) $@ $(lib-y)
 
 $(lib-target): $(lib-y) FORCE
        $(call if_changed,link_l_target)
```

seems to work for arm64 (need to triple check; I'm hitting #283 now in mainline).

**Comment by rupprecht** [comment]
I can't say if P is needed to support some non-GNU version of ar, but for purposes of local testing, it should be fine to remove from your branch. I'm actually working on #279 instead now since that's a much more interesting bug, I should have a patch for that ready for your testing in a day or two.

**Comment by tpimh** [comment]
If P flag here is really useless, all occurrences of it can be simply removed. If it's needed for some specific version of ar it can be moved to `KBUILD_ARFLAGS` and defined as `$(call ar-option,P)`, so only ar versions that need it will use it. Here are all occurrences of P flag that I have found:
1. https://github.com/ClangBuiltLinux/linux/blob/3bd6e94bec122a951d462c239b47954cf5f36e33/scripts/Makefile.build#L407 and https://github.com/ClangBuiltLinux/linux/blob/3bd6e94bec122a951d462c239b47954cf5f36e33/scripts/Makefile.build#L435
2. https://github.com/ClangBuiltLinux/linux/blob/3bd6e94bec122a951d462c239b47954cf5f36e33/scripts/link-vmlinux.sh#L60
3. https://github.com/ClangBuiltLinux/linux/blob/3bd6e94bec122a951d462c239b47954cf5f36e33/arch/s390/boot/Makefile#L61 (it's s390, but can be fixed in the same commit)
4. https://github.com/ClangBuiltLinux/linux/blob/3bd6e94bec122a951d462c239b47954cf5f36e33/Documentation/kbuild/makefiles.txt#L156 and https://github.com/ClangBuiltLinux/linux/blob/3bd6e94bec122a951d462c239b47954cf5f36e33/Documentation/kbuild/makefiles.txt#L161 (documentation)

**Comment by nickdesaulniers** [comment]
[Here's the reasoning why it was added](https://patchwork.kernel.org/patch/9777185/).

**Comment by masahir0y** [comment]
The effect of 'P' is obscure.

Not sure if it was an appropriate place to answer, but I hope the following info would be helpful. 
https://patchwork.kernel.org/patch/10767545/

I hacked Makefile to build the kernel with llvm-ar,
but it is good to know that people are currently fixing llvm-ar.

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/rL354044
