### ISSUE TITLE
x86_64 allyesconfig build hang

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#330]
forking from #319 ; it seems that D53765 diff 183714 the build seems to be [hanging](https://gist.github.com/nickdesaulniers/f26fccc5a234d731db7bc79084e4ca74).

I'm not sure how to provide feedback to help debug; I feel like I'd need to dump the cycle of optimizations we keep bouncing between?  Maybe a preprocessed source and command line flags are a good starting point?

**Comment by nickdesaulniers** [comment]
[export.zip](https://github.com/ClangBuiltLinux/linux/files/2799649/export.zip) let me know if that works, @topperc

**Comment by nickdesaulniers** [comment]
seems to be KASAN related (cc @dvyukov @ramosian-glider ).

```sh
$ make CC=clang allyesconfig
$ ./scripts/config -d KASAN
$ make CC=clang arch/x86/mm/fault.o
$ file arch/x86/mm/fault.o 
arch/x86/mm/fault.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

(I used menuconfig to turn off KASAN properly)

**Comment by nickdesaulniers** [comment]
> seems to be KASAN related

maybe not, even with KASAN disabled, I'm seeing different hangs:

```sh
➜  ~ ps -ef | grep clang | rev | cut -d " " -f 1 | rev | grep c$ | sort | uniq | wc -l
17
➜  ~ ps -ef | grep clang | rev | cut -d " " -f 1 | rev | grep c$ | sort | uniq        
drivers/ata/sata_dwc_460ex.c
drivers/char/pcmcia/cm4000_cs.c
drivers/extcon/extcon-max77843.c
drivers/i2c/busses/i2c-taos-evm.c
drivers/infiniband/hw/cxgb4/qp.c
drivers/pinctrl/intel/pinctrl-cherryview.c
drivers/spi/spi-topcliff-pch.c
drivers/tty/serial/sh-sci.c
drivers/usb/mtu3/mtu3_gadget.c
net/ipv6/netfilter/ip6t_rt.c
sound/pci/echoaudio/darla20.c
sound/pci/echoaudio/darla24.c
sound/pci/echoaudio/gina20.c
sound/pci/echoaudio/layla20.c
sound/pci/hda/patch_realtek.c
sound/soc/codecs/wm_adsp.c
sound/x86/intel_hdmi_audio.c
```

**Comment by nickdesaulniers** [comment]
[export2.zip](https://github.com/ClangBuiltLinux/linux/files/2799667/export2.zip)

**Comment by nickdesaulniers** [comment]
removing `-fsanitize-coverage=trace-pc` or `-fsanitize-coverage=trace-cmp` seems to help.  Maybe these can't be used together?

**Comment by nickdesaulniers** [comment]
> but it seems the diagnosis is that -fsanitize-coverage=trace-pc or -fsanitize-coverage=trace-cmp is currently broken with the current asm goto patch implementation.

Spoke too soon.  Still seeing hangs... let me see if I can diagnose further.

**Comment by nickdesaulniers** [comment]
so turning off KASAN helped one of the problematic translation units build.  Maybe it's BOTH KCOV AND KASAN that are broken (for different translations).  Let me try that.

**Comment by topperc** [comment]
Just put up a new patch that let me get through export.zip

**Comment by nickdesaulniers** [comment]
w/ D53765 diff 183738 I can no longer repro hangs with the two above cases.  Running an allyesconfig to triple check, but this is likely fixed.  Will then revisit #319 .

**Comment by dileks** [comment]
w/ D53765 diff 183738 I have also no hanging. I can boot into QEMU, but on bare metal I get...

```
Kernel panic - not syncing: stack-protector: Kernel stack is corrupted in intel_idle_probe
```

**Comment by nickdesaulniers** [comment]
That's not good, but I wouldn't bother trying to boot on metal until #319 is solved.

**Comment by dileks** [comment]
> $ make CC=clang arch/x86/mm/fault.o

I had seen such breakage before without `CONFIG_KASAN` and `CONFIG_KCOV` set. My latest build was fine with `D53765 diff 183738` (no breakage in `arch/x86/mm/fault.o`).

Can you comment why I can boot in QEMU (just curious)?
