### ISSUE TITLE
Instructions for building a selfmade llvm-toolchain

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/linux#337]
Especially for testing LLVM/Clang with the (RFC) asm-goto patches I wondered how people build their llvm-toolchain.

What does `llvm-toolchain` mean?
It is a term from the Debian packaging world (pkg-llvm-team maintainers).

A `selfmade llvm-toolchain` means building out of the sources.
This can be Git, SVN or even tarballs (final or rc versions provided by upstream).

AFAICS the minimal `llvm-toolchain`consists of building out of `llvm` and `clang` sources.
[1] has informations on the requirements and lists what is seen `optional`.

Of course there are several possibilities in compiling from sources.
@nathanchance posted his setup with configure and build options (maybe you can add a link?).

I know this is a difficult topic and expect different opinions.

A desired solution is having a consensus and hopefully result in a wiki page with help and instructions.

Personally, I am interested in a fast and x86/x86_64 (optimized) only build.
I can provide my scripts if needed.

What do you think?

[1] https://clang.llvm.org/get_started.html
[2] https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/branches
[3] https://github.com/ClangBuiltLinux/linux/wiki
[4] https://reviews.llvm.org/D53765
[5] https://reviews.llvm.org/D56571
[6] https://releases.llvm.org/
[7] https://prereleases.llvm.org/

**Comment by nathanchance** [comment]
Sure: https://github.com/nathanchance/scripts/blob/34f381c8cf6f/snippets/cbl#L402-L435

The idea behind my configuration is turning off options/backends I don't need to build fewer files thus faster builds.

**Comment by nickdesaulniers** [comment]
@nathanchance looks good, can you put that in a wiki page in this repo's github wiki?

**Comment by nathanchance** [comment]
Sure, I'll do it when I get home from work!

**Comment by nathanchance** [comment]
https://github.com/ClangBuiltLinux/linux/wiki/Building-Clang-from-source

Feel free to edit or leave comments as necessary!

**Comment by nickdesaulniers** [comment]
Thanks @nathanchance
