### ISSUE TITLE
unsupported flag -n in lld

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#340]
forked from: https://github.com/ClangBuiltLinux/continuous-integration/issues/122

llvm bug: https://bugs.llvm.org/show_bug.cgi?id=40542

cc @rupprecht @rui314 @smithp35 @GeorgiiR

**Comment by nathanchance** [comment]
See commit 40507403485fcb56b83d6ddfc954e9b08305054c for why it was added.

`-Wl,-N` may suffice but I assume the text section being read only is desirable for the kernel.

```
  -n, --nmagic                Do not page align data
  -N, --omagic                Do not page align data, do not make text readonly
```

**Comment by nathanchance** [comment]
This is now a hard error as of https://git.kernel.org/arm64/linux/c/691efbedc60d2a7364a90e38882fc762f06f52c4.

https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/192907809

**Comment by smithp35** [comment]
Thanks for the report. For now I've raised https://llvm.org/pr41522 to make sure it is recorded. My suspicion is that -n can be implemented as an alias -zmax-page-size=1, although that wouldn't work for ld.bfd as there is a subtle difference in behaviour of that option (details in the PR).

**Comment by smithp35** [comment]
Sigh, looks like this was already reported as part of  https://llvm.org/pr40542 I'll close my new one as a duplicate.

Just thinking it might be worth an LLD meta-bug for all the existing LLD linux kernel problems.

**Comment by nickdesaulniers** [comment]
I spoke more with @smithp35 about this, sounds like it's feasible to implement.  Should be the final arm64+LLD issue.

**Comment by smithp35** [comment]
I've made an attempt at -n with https://reviews.llvm.org/D61201 proved to be a bit more difficult than I thought. It is also worth mentioning that -n will need a linker script (vdso does have one!) to get a sensible output.

**Comment by nathanchance** [comment]
New patch: https://reviews.llvm.org/D61688

**Comment by nickdesaulniers** [comment]
big thanks @smithp35 : https://reviews.llvm.org/rL360593
