### ISSUE TITLE
GCC_TOOLCHAIN_DIR is selected by LD, making setting LD == ld.lld problematic

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#341]
Forked from: https://github.com/ClangBuiltLinux/continuous-integration/issues/122

The issue was that --gcc-toolchain was being set based on which $(LD), which when LD=ld.lld, resolves to the LLVM path, NOT the GCC path.  This results in clang falling back to aarch64-linux-gnu-ld if installed in /usr/local/bin (which I had locally), but the build server does not (thus the treehugger errors).

This is a bug upstream that I need to fix, and why our CI didn't catch it (our CI server has aarch64-linux-gnu-ld installed).

cc @agners @nathanchance

**Comment by dileks** [comment]
When I see this... Do the introduction of `LD_IS_{BFD,GOLD,LLD}` kconfigs make sense as done for `CC_IS_{GCC,CLANG}` in init/Kconfig (even with a version.sh file in scripst directory)?

**Comment by nathanchance** [comment]
@dileks did you mean to leave that comment here or on #342?

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/r/20190207220155.81351-2-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/masahiroy/linux-kbuild.git/commit/?h=kbuild

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/ad15006cc78459d059af56729c4d9bed7c7fd860

**Comment by tpimh** [comment]
What tools are we missing to cross-compile without `--gcc-toolchain`?

**Comment by nathanchance** [comment]
I assume the integrated assembler is the biggest one, yeah?
