### ISSUE TITLE
Turning on -Wformat for Clang

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#346]
https://lore.kernel.org/lkml/20190201210853.244043-1-jflat@chromium.org/

I am doing a set of builds to see if it picks up any additional warnings, which I'll file separate issues for, then I'll review it upstream (assigning myself for tracking).

**Comment by nickdesaulniers** [comment]
An internal bug was just filed for this this week.

**Comment by nathanchance** [comment]
> which I'll file separate issues for

Or not because... https://gist.github.com/nathanchance/b23edb45743ddfc1d2107d1ffdd46e2a

Doesn't necessarily seem super bad (like the `include/linux/usb/wusb.h` are from one printf line that has 16 specifiers) but at the same time, I wonder how worth it this is.

**Comment by nathanchance** [comment]
Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=927047

**Comment by dileks** [comment]
Patch "kbuild: LLVMLinux: Don't suppress format warnings" now in kbuild.git#kbuild.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/masahiroy/linux-kbuild.git/commit/?h=kbuild&id=f8533b4e86b8ae11f95fe3bafb8c46ae3ece2a92

**Comment by nathanchance** [comment]
Well that's annoying... Guess I'll start fixing them.

**Comment by nathanchance** [comment]
#378 is tracking this now.
