### ISSUE TITLE
x86 error on next-20190205

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#347]
```
In file included from /home/nathan/cbl/linux-next/arch/x86/boot/string.c:16:
In file included from /home/nathan/cbl/linux-next/include/linux/kernel.h:12:
In file included from /home/nathan/cbl/linux-next/include/linux/bitops.h:19:
In file included from /home/nathan/cbl/linux-next/arch/x86/include/asm/bitops.h:508:
/home/nathan/cbl/linux-next/arch/x86/include/asm/arch_hweight.h:51:15: error: invalid input size for constraint 'D'
                         : REG_IN (w));
                                   ^
```

It looks like [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=de50ce20cd05da4d1a7e5709a12fc23bc0b66be9) is what exposed the error but I assume it can't be the root cause.

Additionally, there are a ton of warnings along the lines of:

```
In file included from /home/nathan/cbl/linux-next/arch/x86/boot/string.c:16:
In file included from /home/nathan/cbl/linux-next/include/linux/kernel.h:12:
/home/nathan/cbl/linux-next/include/linux/bitops.h:53:41: warning: shift count >= width of type [-Wshift-count-overflow]
        return sizeof(w) == 4 ? hweight32(w) : hweight64(w);
                                               ^~~~~~~~~~~~
/home/nathan/cbl/linux-next/include/asm-generic/bitops/const_hweight.h:29:49: note: expanded from macro 'hweight64'
#define hweight64(w) (__builtin_constant_p(w) ? __const_hweight64(w) : __arch_hweight64(w))
                                                ^~~~~~~~~~~~~~~~~~~~
/home/nathan/cbl/linux-next/include/asm-generic/bitops/const_hweight.h:21:76: note: expanded from macro '__const_hweight64'
#define __const_hweight64(w) (__const_hweight32(w) + __const_hweight32((w) >> 32))
                                                                           ^  ~~
/home/nathan/cbl/linux-next/include/asm-generic/bitops/const_hweight.h:20:49: note: expanded from macro '__const_hweight32'
#define __const_hweight32(w) (__const_hweight16(w) + __const_hweight16((w) >> 16))
                                                ^
/home/nathan/cbl/linux-next/include/asm-generic/bitops/const_hweight.h:19:48: note: expanded from macro '__const_hweight16'
#define __const_hweight16(w) (__const_hweight8(w)  + __const_hweight8((w)  >> 8 ))
                                               ^
/home/nathan/cbl/linux-next/include/asm-generic/bitops/const_hweight.h:10:9: note: expanded from macro '__const_hweight8'
         ((!!((w) & (1ULL << 0))) +     \
               ^
```

Maybe related to #92?

Full log via [Travis](https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/175327988) and [gist](https://gist.github.com/nathanchance/6825ff816e7ccea7f6f09745b8a4eef2)

**Comment by nickdesaulniers** [comment]
> error: invalid input size for constraint 'D'

via: https://gcc.gnu.org/onlinedocs/gcc/Machine-Constraints.html#Machine-Constraints

> D
> The di register.

> arch/x86/include/asm/arch_hweight.h:51

```c                                                       
    8 #define REG_IN "D"                                                              
...
   51                          : REG_IN (w));                                         
```

I would think "the di register" would be `%rdi` for x86_64.  @niravhdave , thoughts?

**Comment by niravhdave** [comment]
Indeed. Looks like we have the isValid logic for D but not the register
assigning logic. I'll go make a fix

**Comment by niravhdave** [comment]
Okay. Looking at this more, it looks like clang is suppose to translate D
constrinat into the register specific IR constraint {di} which we handle
correctly, so this should work. Can you get me a reproducer of the crash?

**Comment by nathanchance** [comment]
```
git clone --depth=1 --single-branch https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/

git clone https://github.com/ClangBuiltLinux/continuous-integration ci

cd linux-next

git am ../ci/patches/linux/x86_64/*

make -j$(nproc) CC=clang defconfig bzImage
```

Should reproduce it. If not, I'll try to funnel something down in a few hours after work.

**Comment by nickdesaulniers** [comment]
Strange, I thought this would have reproduced the issue: https://godbolt.org/z/02F7Pi

I can try creducing the preprocessed source, maybe.

**Comment by nathanchance** [comment]
Ahhh, it's the `-m16` flag (to compile this code in 16-bit mode) that reproduces this error (Nick's godbolt link fails when adding that).

https://github.com/torvalds/linux/blob/v5.0-rc5/arch/x86/Makefile#L32-L34

https://github.com/torvalds/linux/blob/v5.0-rc5/arch/x86/boot/Makefile#L68

`kernel.h` is not included in any other boot code, which is why we haven't run into this yet.

What's really odd though is Clang has different flags than GCC does... (specifically `-m16` for Clang and `-m32` with GCC). With `V=1`:

```
gcc -Wp,-MD,arch/x86/boot/.string.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -m32 -g -Os -DDISABLE_BRANCH_PROFILING -Wall -Wstrict-prototypes -march=i386 -mregparm=3 -fno-strict-aliasing -fomit-frame-pointer -fno-pic -mno-mmx -mno-sse -ffreestanding -fno-stack-protector -mpreferred-stack-boundary=2 -D_SETUP    -DKBUILD_BASENAME='"string"' -DKBUILD_MODNAME='"string"' -c -o arch/x86/boot/string.o arch/x86/boot/string.c
```

```
clang -Wp,-MD,arch/x86/boot/.string.o.d  -nostdinc -isystem /home/nathan/cbl/usr/lib/clang/9.0.0/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Qunused-arguments -m16 -g -Os -DDISABLE_BRANCH_PROFILING -Wall -Wstrict-prototypes -march=i386 -mregparm=3 -fno-strict-aliasing -fomit-frame-pointer -fno-pic -mno-mmx -mno-sse -ffreestanding -fno-stack-protector -mstack-alignment=4 -D_SETUP    -DKBUILD_BASENAME='"string"' -DKBUILD_MODNAME='"string"' -c -o arch/x86/boot/string.o arch/x86/boot/string.c
```

The bizarre thing is that adding `-m16` to the GCC line in the godbolt link above causes the same error so I don't know what else is going on... I'll try to dig in later though.

**Comment by niravhdave** [comment]
I've fixed the minor ambiguity in the backend issue in rL354042, but there
is sitll an issue with clang, which points to a problem with the input code
isteld.

Since "D" implies the ?di register we can only apply this to values of
32-bits or less before we have to spill to another register. In the example
we're passing in an unsigned long long which is 64-bits.

-Nirav

**Comment by nathanchance** [comment]
FWIW, this is the way I have been working around this issue:

```diff
diff --git a/arch/x86/boot/string.c b/arch/x86/boot/string.c
index 315a67b8896b..f4344132ea5a 100644
--- a/arch/x86/boot/string.c
+++ b/arch/x86/boot/string.c
@@ -13,14 +13,16 @@
  */

 #include <linux/types.h>
-#include <linux/kernel.h>
 #include <linux/errno.h>
+#include <linux/compiler.h>
 #include <asm/asm.h>
 #include "ctype.h"
 #include "string.h"

 #define KSTRTOX_OVERFLOW       (1U << 31)

+#define ULLONG_MAX     (~0ULL)
+
 /*
  * Undef these macros so that the functions that we provide
  * here will have the correct names regardless of how string.h
```

> I can try creducing the preprocessed source, maybe.

I tried doing this and it didn't come up with anything. Part of that might be because I don't actually think `__arch_hweight64` has a caller in this file (at least it doesn't appear so when I search for `"hweight"` in the preprocessed source) or I could have just been doing it wrong.

**Comment by nickdesaulniers** [comment]
Here's the preprocessed source.
```sh
clang -nostdinc -Qunused-arguments -m16 -g -Os -Wall -Wstrict-prototypes -march=i386 -mregparm=3 -fno-strict-aliasing -fomit-frame-pointer -fno-pic -mno-mmx -mno-sse -ffreestanding -fno-stack-protector -mstack-alignment=4 -x c -c -o string.o string.i.txt
```
[string.i.txt](https://github.com/ClangBuiltLinux/linux/files/2907073/string.i.txt)

(we should set `-Oz` for `arch/x86/boot/`, filed #405)

**Comment by nickdesaulniers** [comment]
creduce spat this out (cleaned up a little):

```c
// clang -c -m16 x.c
long long a;
void b() { asm("" : : "D"(a)); }
```

**Comment by nickdesaulniers** [comment]
going back to the preprocessed source:
```c
 105 __extension__ typedef unsigned long long __u64;                                 
...
 911 static inline __attribute__((__gnu_inline__)) __attribute__((__unused__)) __attribute__((no_instrument_function)) __attribute__((__always_inline__)) unsigned long __arch     _hweight64(__u64 w)
 912 {                                                                               
 913  unsigned long res;                                                             
 914                                                                                 
 915  asm ("# ALT: oldnstr\n" "661:\n\t" "call __sw_hweight64" "\n662:\n" "# ALT: padding\n" ".skip -(((" "665""1""f-""664""1""f" ")-(" "662b-661b" ")) > 0) * " "((" "665""1"     "f-""664""1""f" ")-(" "662b-661b" ")),0x90\n" "663" ":\n" ".pushsection .altinstructions,\"a\"\n" " .long 661b - .\n" " .long " "664""1""f - .\n" " .word " "( 4*32+23)"      "\n" " .byte " "663""b-661b" "\n" " .byte " "665""1""f-""664""1""f" "\n" " .byte " "663""b-662b" "\n" ".popsection\n" ".pushsection .altinstr_replacement, \"ax\"\n" "# A     LT: replacement " "1" "\n" "664""1"":\n\t" "popcntq %1, %0" "\n" "665""1" ":\n" ".popsection\n"
 916     : "=""a" (res)                                                              
 917     : "D" (w));
```
oops! `w` was a `__u64` ie. `unsigned long long`.

> In the example we're passing in an unsigned long long which is 64-bits.

Oh, @niravhdave already pointed this out.

**Comment by nickdesaulniers** [comment]
So `arch/x86/include/asm/arch_hweight.h` has two implementations of `__arch_hweight64` based on `CONFIG_X86_32`.  I wonder if `arch/x86/boot/Makefile` should be setting `-DCONFIG_X86_32` or if there's a way to detect via preprocessor that we're being compiled for 16b support (and should take the implementation of `__arch_hweight64` additionally on that?

**Comment by nickdesaulniers** [comment]
Playing with this more, it looks a lot like #3 .  For example:

```c
// gcc -c -m16 y.c
// clang -c -m16 y.c

static inline unsigned long a(unsigned long long w) {
  unsigned long res;

  asm("" : "=a"(res) : "D"(w));

  return res;
}

unsigned long b() {
  return a(42ULL);
}
```
comment out `b`, and gcc is happy, clang is not.  But left in, neither are happy.

I suspect that __arch_hweight might actually be dead code that gcc eliminates before semantic checks; otherwise it too would be unhappy.

**Comment by nathanchance** [comment]
Yeah I grepped through the preprocessed source for `hweight` and there is no caller. I wonder if the x86 maintainers would accept the workaround diff I have above or if they'll just tell us to fix the compiler (which they'd be justified in doing).

**Comment by niravhdave** [comment]
HThis is essentially a slightly niceer case of PR33587. What was the
consensus on that?

**Comment by nickdesaulniers** [comment]
I think I have a fix: https://github.com/ClangBuiltLinux/continuous-integration/pull/124/files

**Comment by nickdesaulniers** [comment]
submitted: https://lore.kernel.org/r/20190302000715.130116-1-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment]
resent as v4, now that de50ce20cd05da4d1a7e5709a12fc23bc0b66be9 is in mainline: https://lore.kernel.org/r/20190314221458.83047-1-ndesaulniers@google.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/tip/a9c640ac96e19b3966357ec9bb586edd2e1e74de

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/a9c640ac96e19b3966357ec9bb586edd2e1e74de

**Comment by tpimh** [comment]
Should it be tagged `[FIXED][LINUX] -next` instead?
