### ISSUE TITLE
cc-ifversion is gcc specific

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#350]
top level Makefile has:
```make
 670 KBUILD_CFLAGS += $(call cc-ifversion, -lt, 0409, \                              
 671       $(call cc-disable-warning,maybe-uninitialized,))  
```

which is GCC specific.  That needs a guard.

**Comment by nathanchance** [comment]
Does it? `-Wmaybe-uninitialized` isn't supported by clang (unless [the docs](https://clang.llvm.org/docs/DiagnosticsReference.html) are wrong) so the whole `$(call cc-disable-warning,maybe-uninitialized,)` should evaluate to empty.

**Comment by nickdesaulniers** [comment]
The whole point of cc-disable-warning (and cc-option) is that you check if the flag is supported, then add it if it is.  So checking the compiler version, then checking again if the feature is supported is not necessary.  Just do the feature checks. (Feature detection is strictly better than version checks (except where feature detection is not possible). The current code **mixes** version checking with feature detection, which is just odd).  cc @masahir0y

**Comment by nathanchance** [comment]
As I understand it, GCC < 4.9 has a lot of false positives when it comes to `-Wmaybe-uninitialized`, hence why it isn't being disabled for all GCC versions. `-Wmaybe-uninitialized` was added in GCC 4.7 according to the docs, hence the `cc-option`.

But fair point, we should probably gate it just to make sure that if Clang implements `-Wmaybe-uninitialized`, it doesn't get disabled.

**Comment by nickdesaulniers** [comment]
ah, clang does not support `-Wmaybe-uninitialized`, so it's fine to leave this check as is, but `cc-ifversion` *is* compiler agnostic, so I think it would still be good to wrap this in a `CONFIG_CC_IS_GCC` block.  Thoughts, @masahir0y ?

**Comment by masahir0y** [comment]
For this particular one in the top Makefile, I want to move the complex logic to Kconfig.
https://lore.kernel.org/patchwork/patch/1044494/

We have two more instances of cc-ifversion
arch/mips/loongson64/Platform
arch/powerpc/Makefile

Perhaps, we can change them to not use cc-ifversion.
(by using CONFIG_GCC_VERSION, or by adding another option etc.)

Or, we can rename it to gcc-ifversion or something if we still think this macro is useful.

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/masahiroy/linux-kbuild.git/commit/?h=kbuild&id=b303c6df80c9f8f13785aa83a0471fca7e38b24d

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/b303c6df80c9f8f13785aa83a0471fca7e38b24d

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/llvm/20220831184408.2778264-4-ndesaulniers@google.com/
