### ISSUE TITLE
objtool warnings in allyesconfig

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#351]
clang asm goto diff 185489
    llvm asm goto diff 185868

```
kernel/trace/ring_buffer.o: warning: objtool: rb_advance_reader()+0x523: return with modified stack frame
kernel/trace/ring_buffer.o: warning: objtool: rb_advance_reader()+0x0: stack state mismatch: cfa1=7+64 cfa2=7+8
drivers/gpu/drm/vmwgfx/vmwgfx_msg.o: warning: objtool: vmw_host_get_guestinfo()+0x40a: stack state mismatch: cfa1=6+16 cfa2=7+8
drivers/gpu/drm/vmwgfx/vmwgfx_msg.o: warning: objtool: vmw_host_log()+0x1e8: stack state mismatch: cfa1=6+16 cfa2=7+8
drivers/pinctrl/pinctrl-ingenic.o: warning: objtool: ingenic_pinconf_group_get()+0x9: undefined stack state
drivers/pinctrl/pinctrl-ingenic.o: warning: objtool: ingenic_pinconf_group_get()+0x0: stack state mismatch: cfa1=6+16 cfa2=7+8
drivers/spi/spi-rockchip.o: warning: objtool: rockchip_spi_max_transfer_size()+0x13: undefined stack state
drivers/spi/spi-rockchip.o: warning: objtool: rockchip_spi_max_transfer_size()+0x0: stack state mismatch: cfa1=6+16 cfa2=7+8
```

cc @topperc  (I will work to provide reproducers)

**Comment by nickdesaulniers** [comment]
ring_buffer doesn't seem to be asm goto related. (attaching creduced output)
[ring_buffer.o.txt](https://github.com/ClangBuiltLinux/linux/files/2843101/ring_buffer.o.txt)
[ring_buffer.i.txt](https://github.com/ClangBuiltLinux/linux/files/2843102/ring_buffer.i.txt)
[ring_buffer.s.txt](https://github.com/ClangBuiltLinux/linux/files/2843108/ring_buffer.s.txt)
`ring_buffer.o: warning: objtool: rb_advance_reader()+0x125: return with modified stack frame`
Stack looks balanced to me via quick eyeballing. cc @jpoimboe

**Comment by nickdesaulniers** [comment]
spi-rockchip was also not asm goto related: https://github.com/ClangBuiltLinux/linux/issues/319#issuecomment-457883360

Checking (c reduce) vmwgfx_msg.o now.

**Comment by nickdesaulniers** [comment]
vmwgfx_msg.o seems also not asm goto related
[vmwgfx_msg.i.txt](https://github.com/ClangBuiltLinux/linux/files/2843124/vmwgfx_msg.i.txt)
[vmwgfx_msg.o.txt](https://github.com/ClangBuiltLinux/linux/files/2843125/vmwgfx_msg.o.txt)

**Comment by jpoimboe** [comment]
The issue with ring_buffer.o seems to be that p() falls through to the next function rb_advance_reader().  Objtool is supposed to give a better error message for that though, not sure why it isn't.

**Comment by jpoimboe** [comment]
I don't see any issues with vmwgfx_msg.o, objtool just might be getting confused by some of the code generation.  I'll be out tomorrow but I can look at it next week.

**Comment by topperc** [comment]
I looked into the ring_buffer issue. We have an "unreachable" basic block a the default dest from a couple switches. When we do address san coverage instrumentation we split all critical edges which picks up the edges to this unreachable basic block. This causes new empty basic blocks to be inserted that just unconditionally jump to the unreachable basic block. Those new basic blocks get instrumented with a coverage function call. But much later when we do code layout we realize they jump to an unreachable block and lay them out in a weird way.

**Comment by topperc** [comment]
I've submitted an llvm patch to fix the ring_buffer issue https://reviews.llvm.org/D57982

**Comment by nickdesaulniers** [comment]
D57982 Diff 186057 indeed fixes ring_buffer. Thank you.

drivers/pinctrl/pinctrl-ingenic.o C reduced to a very basic case:
```c
a() { __builtin_unreachable(); }
ingenic_pinconf_group_get() {}
```
```asm
llvm-objdump -d pinctrl.o 

pinctrl.o:      file format ELF64-x86-64

Disassembly of section .text:
0000000000000000 a:
       0:       e8 00 00 00 00  callq   0 <a+0x5>
       5:       55      pushq   %rbp
       6:       48 89 e5        movq    %rsp, %rbp
       9:       0f 1f 80 00 00 00 00    nopl    (%rax)

0000000000000010 ingenic_pinconf_group_get:
      10:       e8 00 00 00 00  callq   0 <ingenic_pinconf_group_get+0x5>
      15:       55      pushq   %rbp
      16:       48 89 e5        movq    %rsp, %rbp
      19:       e8 00 00 00 00  callq   0 <ingenic_pinconf_group_get+0xe>
      1e:       5d      popq    %rbp
      1f:       c3      retq
```

**Comment by nickdesaulniers** [comment]
I no longer see the errors other than
```
drivers/gpu/drm/vmwgfx/vmwgfx_msg.o: warning: objtool: vmw_host_get_guestinfo()+0x40a: stack state mismatch: cfa1=6+16 cfa2=7+8
drivers/gpu/drm/vmwgfx/vmwgfx_msg.o: warning: objtool: vmw_host_log()+0x1e8: stack state mismatch: cfa1=6+16 cfa2=7+8
```
which we determined are not related to asm goto. Closing.
