### ISSUE TITLE
arm32 vDSO forces ld.bfd

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#356]
Forked from https://github.com/ClangBuiltLinux/linux/issues/342#issuecomment-460122522

https://github.com/ClangBuiltLinux/linux/blob/b23b0ea3708c3dec599966fc856836aca48835b9/arch/arm/vdso/Makefile#L18

Introduced by https://github.com/ClangBuiltLinux/linux/commit/d2b30cd4b7223a96e606dfc8120626f66d81e091

**Comment by nathanchance** [comment]
Fixed by https://git.kernel.org/next/linux-next/c/fe00e50b2db8c60e4ec90befad1f5bab8ca2c800

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/fe00e50b2db8c60e4ec90befad1f5bab8ca2c800

**Comment by nickdesaulniers** [comment]
oh, I guess I should have closed this w/ #342 ?

**Comment by nathanchance** [comment]
Technically yes but no harm no foul :)
