### ISSUE TITLE
-Wreturn-type in arch/x86/boot/compressed/kaslr.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#360]
from https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/176700062

```
arch/x86/boot/compressed/kaslr.c:702:1: warning: control may reach end of non-void function [-Wreturn-type]
```
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/tree/arch/x86/boot/compressed/kaslr.c#n654

Looks like `process_mem_region` has an `return` within an `#ifdef`.  That final return should be placed outside of the `#ifdef`.

**Comment by kragniz** [comment]
patch: https://lore.kernel.org/patchwork/patch/1047383/

**Comment by nickdesaulniers** [comment]
accepted into tip: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=x86/boot

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/e4a0bd0308f05c1354d28feec8439e869eae6372
