### ISSUE TITLE
kselftests try to build with gcc

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#374]
```
$ ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- make CC=clang HOSTCC=clang -j46 quicktest=1 kselftest
...
make[3]: aarch64-linux-gnu-gcc: Command not found
...
```

**Comment by nickdesaulniers** [comment]
They should be using `$(HOSTCC)`, assuming it was exported correctly from the top level Makefile.

**Comment by bulwahn** [comment]
I plan to give this to my student as a good exercise to touch some build scripts and submit his first kernel patch.

**Comment by bulwahn** [comment]
To reproduce the issue, we actually do not need the cross-compile setup. It suffices to run `make CC=clang HOSTCC=clang kselftest` and observe that gcc is used for compiling.

**Comment by nickdesaulniers** [comment]
In particular, the author of the rseq system call mentioned that their kselftests fail to build because they reset `KBUILD_CFLAGS`, thus dropping `-no-integrated-as`.  They should be using `${CLANG_FLAGS}`.

So as part of this issue, it's not just that the `kselftests` build with GCC, but also that they may fail to build with Clang (and we should fix that, too).

**Comment by nickdesaulniers** [comment]
cc @gctucker

**Comment by gctucker** [comment]
Thanks for the heads, up.  We're trying to fix all existing build errors we have in our environment with `gcc` first, then we'll take a look at building kselftests with `clang`.

**Comment by nathanchance** [comment]
Relevant patch/thread: https://lore.kernel.org/r/20201203221005.2813159-1-adelg@google.com/

**Comment by gctucker** [comment]
@nickdesaulniers BTW we've enabled clang builds with kselftest on staging, does this look good?
https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20210211.0/arm64/defconfig+kselftest/clang-11/build.log

**Comment by nathanchance** [comment]
I do see quite a few errors in there but it does look like `clang` is being used.

**Comment by nickdesaulniers** [comment]
yeah cool those are clang warnings all right!

**Comment by gctucker** [comment]
Nice, we're working on splitting out the kselftest build log, in fact having a build log for each step of the build job, and then that will get turned on in production.  It's working on the command line already, hopefully it'll be there by the end of the month.

Then we could include a separate section in the build email reports and on the web dashboard for kselftest errors, or maybe have a "kselftest special" report with both build and test results.  We'll be discussing that once we get there.

**Comment by nathanchance** [comment]
```
$ make -skj"$(nproc)" LLVM=1 LLVM_IAS=1 distclean defconfig quicktest=1 kselftest
```

shows that clang is being used so closing this issue. We can open individual issues for the errors that we see.

**Comment by gctucker** [comment]
FYI we now have separate build steps working on staging, here's a sample kselftest log:
https://storage.staging.kernelci.org/kernelci/staging-mainline/staging-mainline-20210423.0/x86_64/x86_64_defconfig+kselftest/clang-10/logs/kselftest.log

This should get enabled in production by the end of the month.  We could then look into generating a kselftest special email report with both build and runtime issues.

**Comment by nickdesaulniers** [comment]
@gctucker nice! Looks like we have a good list of warnings+errors to start fixing in the kselftests!
