### ISSUE TITLE
LLD removes module version info with CONFIG_LD_DEAD_CODE_DATA_ELIMINATION

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#376]
@kdrag0n has been experimenting with LLD on the Pixel 3 after seeing the work we have done here and whipped up the following commit.

https://github.com/kdrag0n/proton_bluecross/commit/ac2d42e2dd292aecc62b7d467d22e400e3dc1341

This doesn't appear to be something that can currently happen on mainline as only MIPS and PowerPC allow CONFIG_LD_DEAD_CODE_DATA_ELIMINATION to be selected. I wanted to verify if this happens on mainline with LTO but I was only to get through halfway rebasing the v2 patchset before I started running into serious trouble. v3 was supposed to be sent out but I can't find it so I assume it was never sent, has anyone rebased them recently?

**Comment by nickdesaulniers** [comment]
@samitolvanen what's the status of the above patch?  Was the issue (mentioned in the commit message) fixed in a similar way (via linker script)?

https://github.com/ClangBuiltLinux/linux/blob/master/include/linux/module.h#L236

**Comment by samitolvanen** [comment]
I don't remember running into this issue with Pixel 3, but then again, we don't use LLD there. I believe this was fixed upstream in 4.10:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4b89b7f7aad5742523db801b7107598e5b5a42c8

**Comment by nathanchance** [comment]
Hmm I should have check there first before even opening this, thank you for looking into it!
