### ISSUE TITLE
Enable -Wuninitialized

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#381]
29b00e609960ae0fcff382f4c7079dd0874a5311 would have been caught with Clang in its default configuration (and not by GCC due to [a bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=18501)), as pointed out in this thread: https://lore.kernel.org/lkml/86649ee4-9794-77a3-502c-f4cd10019c36@lca.pw/

However, `-Wuninitialized` also disables `-Wsometimes-uninitialized` so this was missed by both compilers :(

I am going to test the following diff then send it along right away if there are no additional warnings:

```diff
diff --git a/scripts/Makefile.extrawarn b/scripts/Makefile.extrawarn
index 768306add591..f4332981ea85 100644
--- a/scripts/Makefile.extrawarn
+++ b/scripts/Makefile.extrawarn
@@ -72,5 +72,6 @@ KBUILD_CFLAGS += $(call cc-disable-warning, format)
 KBUILD_CFLAGS += $(call cc-disable-warning, sign-compare)
 KBUILD_CFLAGS += $(call cc-disable-warning, format-zero-length)
 KBUILD_CFLAGS += $(call cc-disable-warning, uninitialized)
+KBUILD_CFLAGS += $(call cc-option, -Wsometimes-uninitialized)
 endif
 endif
```

Side note, looks like this might be a good time to tell Linus about the KernelCI work that is going on: https://lore.kernel.org/lkml/CAHk-=wggjLsi-1BmDHqWAJPzBvTD_-MQNo5qQ9WCuncnyWPROg@mail.gmail.com/

**Comment by nickdesaulniers** [comment]
heh, wish I was cc'ed on that thread (I'm not subbed to lkml, *ducks*)

**Comment by nathanchance** [comment]
> I'm not subbed to lkml, _ducks_

Neither am I, I happened to stumble across it while browsing https://lore.kernel.org/lkml/. Guess I should be after this.

It is still possible to reply without being CC'd (if you use `mutt`). Otherwise, the link gives reply instructions using `git send-email` at the bottom.

```
$ curl -LSs -o mbox https://lore.kernel.org/lkml/CAHk-=wggjLsi-1BmDHqWAJPzBvTD_-MQNo5qQ9WCuncnyWPROg@mail.gmail.com/raw
$ mutt -f mbox
```

**Comment by nathanchance** [comment]
Unfortunately, introduces a few warnings: https://gist.github.com/nathanchance/59f35754366c7d68141a5f44fe9302b8

Another project like #378 (seems like it could be achieved quicker).

**Comment by nickdesaulniers** [comment]
Yes; and many of those have the same source file (and even the same warning in some cases; like maybe a shared problematic macro).  Thanks for the link; I'll file bugs for all of those, and we'll use this to track enabling the warning.

**Comment by nickdesaulniers** [comment]
12 altogether (including this one)

**Comment by nathanchance** [comment]
Filed some more issues last night that appeared after I quickly hacked up a monolithic patch to address the ones above. I should have just built without `-Werror` the first time, sigh.

Still, only 22 instances it looks like, I'll start working on them in a bit.

**Comment by nickdesaulniers** [comment]
specifically scripts/Makefile.extrawarn has this block:
```make
ifdef CONFIG_CC_IS_CLANG
KBUILD_CFLAGS += $(call cc-disable-warning, initializer-overrides)
KBUILD_CFLAGS += $(call cc-disable-warning, unused-value)
KBUILD_CFLAGS += $(call cc-disable-warning, format)
KBUILD_CFLAGS += $(call cc-disable-warning, sign-compare)
KBUILD_CFLAGS += $(call cc-disable-warning, format-zero-length)
KBUILD_CFLAGS += $(call cc-disable-warning, uninitialized)
endif
```

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20190430010037.6216-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Alright, we are down to three open warnings: #465, #492, and #499.

#465's patch has been picked up, ideally it is merged this cycle.

#492's patch is pending.

#499 has a patch, it just needs to be sent out for review.

It might be worth pulling the trigger and enabling the warnings before these issues are fixed in -next so things like KernelCI and 0day can catch them quicker.

**Comment by nickdesaulniers** [comment]
@nathanchance I think it's time to send the patch enabling this. WDYT?

**Comment by nathanchance** [comment]
#499 and #504 (which has been acked) are the only outstanding warnings. I have been waiting for @arndb to send his patch for #499: https://github.com/nathanchance/patches/blob/71522974ccf011ed721731c14befaae70bf149d2/linux/Wuninitialized/0002-sched-wait-Apply-Arnd-s-__WAIT_QUEUE_HEAD_INIT_ONSTA.patch

I am fine with enabling this now though so we get more coverage on CI.

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20190614165242.79257-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch is in -next: https://git.kernel.org/next/linux-next/c/3a61925e91ba9f0ece1b444eb1aa49caa59e4ae7

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/3a61925e91ba9f0ece1b444eb1aa49caa59e4ae7
