### ISSUE TITLE
-Wsometimes-uninitialized in fs/btrfs/uuid-tree.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#385]
from #381 
```
fs/btrfs/uuid-tree.c:129:13: error: variable 'eb' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
fs/btrfs/uuid-tree.c:129:13: error: variable 'offset' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
```
allyesconfig

**Comment by nickdesaulniers** [comment]
Clang seems confused likely cause of the final `else if` (it's not able to work out that ALL cases are covered).  The final branch should just be an `else`, no `else if`.

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20190307163515.2168-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://github.com/kdave/btrfs-devel/commit/2feb2cbf67fb5e2271ba61c52cdd8499bbe02b2b

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/e8baf7abcf56da68a03df77f51459acddeef4195
