### ISSUE TITLE
-Wsometimes-uninitialized in drivers/iio/adc/stmpe-adc.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#387]
from #381 
```
drivers/iio/adc/stmpe-adc.c:204:13: error: variable 'data' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
```

**Comment by nickdesaulniers** [comment]
driver does not exist yet in mainline.

again (same pattern as #388), separated conditionals Clang can't provide all cases exhausted.  The early return could just be a final `else` clause.

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20190307171604.27791-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/jic23/iio/c/e15146e4d4349b3f309f5591ea8de8d24071265f

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/17104ca2713ba443f9a02a7c4090514ad1e46ee9
