### ISSUE TITLE
-Wsometimes-uninitialized in drivers/acpi/sysfs.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#388]
from #381 
```
drivers/acpi/sysfs.c:667:13: error: variable 'result' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
```

**Comment by nickdesaulniers** [comment]
This one looks tricky on the surface, until you realize that the first and third conditions are either side of what could have been one conditional and an `else`.  This whole function could use a rewrite.

should have the tag:
Fixes commit f18ebc211e259 ("ACPI / sysfs: fix error code in get_status()")

**Comment by nathanchance** [comment]
Rafael sent a patch to fix this function in a better way: https://lore.kernel.org/lkml/53542709.3ZnE1UDn36@aspire.rjw.lan/

**Comment by nickdesaulniers** [comment]
merged: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3fd16d70166194dd0bf0f7a555779a42ee267223
