### ISSUE TITLE
-Wsometimes-uninitialized in net/tipc/node.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#389]
from #381 
```
net/tipc/node.c:831:6: error: variable 'maddr' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
```

**Comment by nickdesaulniers** [comment]
oops! and `__tipc_node_link_down` might not even initialize `maddr` (it has an early return)!  I can't find what initializes `send_msg`, but hopefully it could handle a `NULL` ptr, if we were to give it one (we're not, right now it's sometimes getting uninitialized memory, which is always UB).

**Comment by nathanchance** [comment]
Inquiry sent to the maintainers: https://lore.kernel.org/lkml/20190308001723.GA11197@archlinux-ryzen/

**Comment by nickdesaulniers** [comment]
@arndb has a patch here: https://lore.kernel.org/lkml/CAK8P3a2pGo8HeHS5zcFnc_jLiLkXSPWKe4AYVm4TAmZxc_h2GA@mail.gmail.com/

**Comment by arndb** [comment]
I sent all the -Wuninitialized patches I made now, including this one.

**Comment by nathanchance** [comment]
The maintainer sent a combination of initialization and Arnd's patch: https://git.kernel.org/davem/net/c/737889efe9713a0f20a75fd0de952841d9275e6b

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/737889efe9713a0f20a75fd0de952841d9275e6b
