### ISSUE TITLE
-Wsometimes-uninitialized in arch/powerpc/xmon/ppc-dis.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#390]
from #381 
```
arch/powerpc/xmon/ppc-dis.c:157:7: error: variable 'opcode' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
```

**Comment by nathanchance** [comment]
I'm drafting the commit message for this one now, it's a good one.

**Comment by nathanchance** [comment]
Ah C... https://lore.kernel.org/lkml/20190226053855.7020-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/powerpc/c/e7140639b1de65bba435a6bd772d1349

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/e7140639b1de65bba435a6bd772d1349
