### ISSUE TITLE
support for "r" prefixed variables in ARM inline assembly

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#4]
ARMv8 added support for register prefixes "w" (eg w0, w1) for lower 32b and "x" (eg x0, x1) for full 64b of the same register.  GCC also supports the ARMv7 "r" prefixes, but clang complains for ARMv8 that this is ambiguous.

LLVM Bug: https://bugs.llvm.org/show_bug.cgi?id=36862
Chromium Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=824526
Example Android workaround: https://android-review.googlesource.com/c/kernel/common/+/645181

**Comment by nickdesaulniers** [comment]
temp patch sent upstream to linux by @mkaehlcke: https://patchwork.kernel.org/patch/10302339/

**Comment by nickdesaulniers** [comment]
patch to LLVM started: https://reviews.llvm.org/D44815

**Comment by mkaehlcke** [comment]
https://reviews.llvm.org/D44815 has landed.
