### ISSUE TITLE
-Wparentheses-equality in fs/ocfs2/dlm/dlmthread.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#40]
```sh
  CC      fs/ocfs2/dlm/dlmthread.o
fs/ocfs2/dlm/dlmthread.c:534:18: warning: equality comparison with extraneous
      parentheses [-Wparentheses-equality]
        if ((res->owner == dlm->node_num)) {
             ~~~~~~~~~~~^~~~~~~~~~~~~~~~
fs/ocfs2/dlm/dlmthread.c:534:18: note: remove extraneous parentheses around the
      comparison to silence this warning
        if ((res->owner == dlm->node_num)) {
            ~           ^               ~
fs/ocfs2/dlm/dlmthread.c:534:18: note: use '=' to turn this equality comparison into
      an assignment
        if ((res->owner == dlm->node_num)) {
                        ^~
                        =
```
Probably requires `CONFIG_OCFS2_FS=y` (there's like 6 OCFS2 configs).

**Comment by nathanchance** [comment]
`CONFIG_OCFS2_FS` + `CONFIG_OCFS2_FS_O2CB`

I'll send a patch for this one.

**Comment by nickdesaulniers** [comment]
There's another easy one in:
```sh
  CC      drivers/ata/pata_atiixp.o
drivers/ata/pata_atiixp.c:282:19: warning: equality comparison with extraneous
      parentheses [-Wparentheses-equality]
        if((pdev->device == PCI_DEVICE_ID_ATI_IXP600_IDE))
            ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/ata/pata_atiixp.c:282:19: note: remove extraneous parentheses around the
      comparison to silence this warning
        if((pdev->device == PCI_DEVICE_ID_ATI_IXP600_IDE))
           ~             ^                              ~
drivers/ata/pata_atiixp.c:282:19: note: use '=' to turn this equality comparison into
      an assignment
        if((pdev->device == PCI_DEVICE_ID_ATI_IXP600_IDE))
                         ^~
                         =
```

(should be a separate patch, and probably GH issue).  Bust out your old parallel ATA hard drives! :fireworks:

**Comment by nickdesaulniers** [comment]
```sh
  CC      drivers/block/rsxx/cregs.o
drivers/block/rsxx/cregs.c:279:15: warning: equality comparison with extraneous
      parentheses [-Wparentheses-equality]
        if ((cmd->op == CREG_OP_READ)) {
             ~~~~~~~~^~~~~~~~~~~~~~~
drivers/block/rsxx/cregs.c:279:15: note: remove extraneous parentheses around the
      comparison to silence this warning
        if ((cmd->op == CREG_OP_READ)) {
            ~        ^              ~
drivers/block/rsxx/cregs.c:279:15: note: use '=' to turn this equality comparison into
      an assignment
        if ((cmd->op == CREG_OP_READ)) {
                     ^~
                     =
```

**Comment by nathanchance** [comment]
Patch sent for the first warning: https://lore.kernel.org/lkml/20180911213401.23925-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch sent for the second warning: https://lore.kernel.org/lkml/20180911214338.1109-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch sent for the third warning: https://lore.kernel.org/lkml/20180911215040.7906-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
The second and third patches have been accepted and are currently in -next:

https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=ce42c1768152277658d48196f144aa406a4ea52a

https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=798ef9e70110d0245797526c930beec7fded7b15

I'll resend the first patch on Monday (looks like I need to send it to Andrew Morton based on git history).

**Comment by nathanchance** [comment]
First patch resent: https://lore.kernel.org/lkml/20180924181929.6853-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch has been accepted for a while but it just showed up in -next a few days ago: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=90bb74ee01489f89a2bcf3a191510e26bf1e3a64

**Comment by nathanchance** [comment]
Second and third patches merged into mainline, will close when the fs/ocfs2 one is merged.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=798ef9e70110d0245797526c930beec7fded7b15

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ce42c1768152277658d48196f144aa406a4ea52a

**Comment by nathanchance** [comment]
fs/ocfs2 patch has been applied in mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=32c1b90dcd90c7f6343e1b328801f7be5f7da88d
