### ISSUE TITLE
-Wsometimes-uninitialized in drivers/soc/mediatek/mtk-pmic-wrap.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#401]
Meta: #381 

```
drivers/soc/mediatek/mtk-pmic-wrap.c:1358:6: error: variable 'rdata' is used uninitialized whenever '||' condition is true [-Werror,-Wsometimes-uninitialized]
```

in `pwrap_init_cipher`.

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20190307225650.23001-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/matthias.bgg/linux/c/89e28da82836530f1ac7a3a32fecc31f22d79b3e

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/89e28da82836530f1ac7a3a32fecc31f22d79b3e

**Comment by nickdesaulniers** [comment]
probably should go to stable.  Cc'ing them when sending patches is the easiest, but I always forget to do it myself.

**Comment by nathanchance** [comment]
If this doesn't get picked up Sasha's AUTOSEL tool, I'll try to remember to send it to stable. Ideally, I'd like to cc stable all of these patches but some maintainers are more stringent than others on what goes so I just leave the tag off of everything.
