### ISSUE TITLE
Linking a CONFIG_CFI_CLANG kernel fails after r350949

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#406]
NOTE: This is not a mainline issue for obvious reasons.

I decided to test building the android-4.9 branch of kernel/common with LTO and CFI enabled when testing my 4.9 backport of the missing Clang patches when compared to 4.14 and discovered that when a tip of tree Clang is used, linking fails whereas the current AOSP Clang 8.0.9 is okay.

```
aarch64-linux-gnu-ld.gold: fatal error: LLVM gold plugin: linking module flags 'EnableSplitLTOUnit': IDs have conflicting values
```

I bisected it down to [r350949](https://github.com/llvm/llvm-project/commit/84cecfcb3db7c3275ae2d64c419a752d9f5311d6) (and most likely the previous revision [r350948](https://github.com/llvm/llvm-project/commit/290a8398917a3d4ef521a0cfdb67e65238f0043a)). I have no idea if this has already been reported or where the regression lies (kernel, LLVM/Clang, gold?) but better to get ahead of the curve by reporting it now.

With both those patches reverted (as well as the follow up fixes/dependencies), `CONFIG_CFI_CLANG` works as expected ([monolithic patch](https://gist.github.com/e722c253e954ded0cf87da7d736f7819)).

**Comment by nickdesaulniers** [comment]
cc @samitolvanen

**Comment by nickdesaulniers** [comment]
@pirama-arumuga-nainar pointed me to an internal thread that explicitly mentions that commit by name, which mentions adding the flag `-fsplit-lto-unit`.

**Comment by samitolvanen** [comment]
Adding -fsplit-lto-unit to lto-clang-flags seems to fix this. Just tested with a ToT LLVM.

**Comment by nathanchance** [comment]
> Adding -fsplit-lto-unit to lto-clang-flags seems to fix this.

I can confirm this as well.

```diff
diff --git a/Makefile b/Makefile
index c8f357af63df..d427d267b371 100644
--- a/Makefile
+++ b/Makefile
@@ -674,7 +674,7 @@ KBUILD_CFLAGS       += $(call cc-option,-fdata-sections,)
 endif
 
 ifdef CONFIG_LTO_CLANG
-lto-clang-flags        := -flto -fvisibility=hidden
+lto-clang-flags        := -flto -fvisibility=hidden $(call cc-option, -fsplit-lto-unit)
 
 # allow disabling only clang LTO where needed
 DISABLE_LTO_CLANG := -fno-lto -fvisibility=default
```

However, this seems like broken behavior to me. According to the commit message and the code in `clang/lib/Driver/ToolChains/Clang.cpp`, this flag is supposed to be set when using `-fsanitize=cfi`.

**Comment by nathanchance** [comment]
@samitolvanen Are you planning to push this fix to kernel/common or should I? I've been applying it locally for my build/boot tests, it would be nice to drop it :)

**Comment by nathanchance** [comment]
Patches submitted:

https://android-review.googlesource.com/c/kernel/common/+/941218

https://android-review.googlesource.com/c/kernel/common/+/941220

**Comment by nickdesaulniers** [comment]
Thank you @nathanchance . Looks like this is merged up, closing.
