### ISSUE TITLE
-Wvarargs in security/keys/trusted.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#41]
```
  CC      security/keys/trusted.o
security/keys/trusted.c:146:17: warning: passing an object that undergoes default
      argument promotion to 'va_start' has undefined behavior [-Wvarargs]
        va_start(argp, h3);
                       ^
security/keys/trusted.c:126:37: note: parameter of type 'unsigned char' is declared
      here
                        unsigned char *h2, unsigned char h3, ...)
                                                         ^
```

guessing this requires `CONFIG_TRUSTED_KEYS=y`

**Comment by nickdesaulniers** [comment]
I'm not sure; let's nail down the easier issues first then revisit.

**Comment by nathanchance** [comment]
Completely fine with me, thanks

**Comment by nickdesaulniers** [comment]
- http://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20160418/156432.html
- https://wiki.sei.cmu.edu/confluence/display/cplusplus/EXP58-CPP.+Pass+an+object+of+the+correct+type+to+va_start:

The C Standard, subclause 7.16.1.4, paragraph 4 [ISO/IEC 9899:2011] (and C90: 4.8.1.1):
The parameter parmN is the identifier of the rightmost parameter in the variable parameter list in the function definition (the one just before the ...). If the parameter parmN is declared with the register storage class, with a function or array type, or with **a type that is not compatible with the type that results after application of the default argument promotions**, the behavior is undefined.

>  believe Clang is complaining because varargs' default argument promotion for type char is unsigned char *.

I would have expected `int`.

The `man` page for `va_start` only mentions the promotion behavior for `va_arg()`, not `va_start()`.

I think

```diff
diff --git a/security/keys/trusted.c b/security/keys/trusted.c
index b69d3b1777c2..8e532873429c 100644
--- a/security/keys/trusted.c
+++ b/security/keys/trusted.c
@@ -123,7 +123,7 @@ static int TSS_rawhmac(unsigned char *digest, const unsigned char *key,
  */
 static int TSS_authhmac(unsigned char *digest, const unsigned char *key,
 			unsigned int keylen, unsigned char *h1,
-			unsigned char *h2, unsigned char h3, ...)
+			unsigned char *h2, int h3, ...)
 {
 	unsigned char paramdigest[SHA1_DIGEST_SIZE];
 	struct sdesc *sdesc;
@@ -139,7 +139,7 @@ static int TSS_authhmac(unsigned char *digest, const unsigned char *key,
 		return PTR_ERR(sdesc);
 	}
 
-	c = h3;
+	c = (unsigned char) h3;
 	ret = crypto_shash_init(&sdesc->shash);
 	if (ret < 0)
 		goto out;
```

is the simplest (correct) solution.

**Comment by nathanchance** [comment]
Seems reasonable to me, I'll test it later tonight with the two outstanding issues of this type and prepare a couple of patches, thanks for looking into this.

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/r/CAKwvOdkqtfAyDdxkac=NtfSiskiGyOhN1PPzkxBYpR_JEBTRbw@mail.gmail.com/

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/r/20181011203126.15338-1-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/r/20181022234357.82217-1-ndesaulniers@google.com/: [PATCH v2] [PATCH] KEYS: trusted: fix -Wvarags warning

**Comment by nickdesaulniers** [comment]
bumped the maintainers again.

**Comment by nathanchance** [comment]
Patch accepted: http://git.infradead.org/users/jjs/linux-tpmdd.git/commit/cfb1f7ee3b35e6ba9e9e2de53a8668ced6397f88

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/be24b37e22c20cbaa891971616784dd0f35211e8

**Comment by nickdesaulniers** [comment]
> Merged into mainline

six months later... 💀 ☠️ 👻
