### ISSUE TITLE
LLD: x86_64: Option -z -noreloc-overflow

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/linux#411]
When experimenting with `lld` I saw there is no linker option `-z -noreloc-overflow` set (but with BFD) in `arch/x86/boot/compressed/Makefile`.

Not sure if there is an equivalent option available.

[x86-boot-compressed-Check-available-linker-flags-by-_patch.txt](https://github.com/ClangBuiltLinux/linux/files/2935007/x86-boot-compressed-Check-available-linker-flags-by-_patch.txt)

**Comment by nathanchance** [comment]
Should `-pie` and `--no-dynamic-linker` be added to `ld.lld` when we don't have `-z noreloc-overflow`? That patch discards the current logic.

**Comment by dileks** [comment]
Oops, yupp you are right that both settings are when `CONFIG_X86_32=y`.

**Comment by dileks** [comment]
v2.
[x86-boot-compressed-Check-available-linker-flags-by-ld-option-v2_patch.txt](https://github.com/ClangBuiltLinux/linux/files/2939945/x86-boot-compressed-Check-available-linker-flags-by-ld-option-v2_patch.txt)

**Comment by dileks** [comment]
Grrr, v3 (guess this has space for improvements).
[x86-boot-compressed-Check-available-linker-flags-by-ld-option-v3_patch.txt](https://github.com/ClangBuiltLinux/linux/files/2940036/x86-boot-compressed-Check-available-linker-flags-by-ld-option-v3_patch.txt)

**Comment by dileks** [comment]
That' still wrong. For now I would do:

```
-ifeq ($(CONFIG_X86_64),y)
+ifeq ($(LD_IS_BFD),y)
```

**Comment by dileks** [comment]
Substituting with `ld.bfd`:
```
$ ld.bfd -m elf_x86_64   -pie  --no-dynamic-linker   -T arch/x86/boot/compressed/vmlinux.lds arch/x86/boot/compressed/head_64.o arch/x86/boot/compressed/misc.o arch/x86/boot/compressed/string.o arch/x86/boot/compressed/cmdline.o arch/x86/boot/compressed/error.o arch/x86/boot/compressed/piggy.o arch/x86/boot/compressed/cpuflags.o arch/x86/boot/compressed/early_serial_console.o arch/x86/boot/compressed/kaslr.o arch/x86/boot/compressed/kaslr_64.o arch/x86/boot/compressed/mem_encrypt.o arch/x86/boot/compressed/pgtable_64.o arch/x86/boot/compressed/eboot.o arch/x86/boot/compressed/efi_stub_64.o drivers/firmware/efi/libstub/lib.a arch/x86/boot/compressed/efi_thunk_64.o -o arch/x86/boot/compressed/vmlinux
```

i get:
```
ld.bfd: arch/x86/boot/compressed/head_64.o: relocation R_X86_64_32 against symbol `z_input_len' can not be used when making a PIE object; recompile with -fPIC
ld.bfd: final link failed: nonrepresentable section on output
```

Even I did:
```
[ arch/x86/boot/compressed/Makefile ]
-KBUILD_CFLAGS += -fno-strict-aliasing $(call cc-option, -fPIE, -fPIC)
+KBUILD_CFLAGS += -fno-strict-aliasing $(call cc-option, -fPIC, -fPIE)
```
From [1]:
```
[ arch/x86/boot/compressed/head_64.S ]
/*
 * Do the extraction, and jump to the new kernel..
 */
	pushq	%rsi			/* Save the real mode argument */
	movq	%rsi, %rdi		/* real mode address */
	leaq	boot_heap(%rip), %rsi	/* malloc area for uncompression */
	leaq	input_data(%rip), %rdx  /* input_data */
	movl	$z_input_len, %ecx	/* input_len */
	movq	%rbp, %r8		/* output target address */
	movq	$z_output_len, %r9	/* decompressed length, end of relocs */
	call	extract_kernel		/* returns kernel location in %rax */
	popq	%rsi
```

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/x86/boot/compressed/head_64.S?h=v5.0#n530

**Comment by dileks** [comment]
`readelf -r arch/x86/boot/compressed/head_64.o > /tmp/readelf.txt`

```
Relocation section '.rela.text' at offset 0x1480 contains 9 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000000005  001600000002 R_X86_64_PC32     0000000000000000 _bss - 4
00000000000c  001700000002 R_X86_64_PC32     0000000000000000 _ebss - 4
000000000021  001400000002 R_X86_64_PC32     0000000000000000 .bss - 4
000000000028  002700000002 R_X86_64_PC32     0000000000000000 input_data - 4
00000000002d  002e0000000a R_X86_64_32       0000000000000000 z_input_len + 0
000000000037  002f0000000b R_X86_64_32S      0000000000000000 z_output_len + 0
00000000003c  002500000004 R_X86_64_PLT32    0000000000000000 extract_kernel - 4
000000000046  001a00000002 R_X86_64_PC32     0000000000000000 _got - 4
00000000004d  001800000002 R_X86_64_PC32     0000000000000000 _egot - 4
```

**Comment by dileks** [comment]
Confirmed on IRC by @arndb 
```
[14:11:09] <arnd> I tried replacing the cmd_check-and-link-vmlinux command with a hardcoded ld.bfd, and ended up with "ld.bfd: warning: -z noreloc-overflow ignored. ld.bfd: arch/x86/boot/compressed/head_64.o: relocation R_X86_64_32 against `z_input_len' can not be used when making a shared object; recompile with -fPIC"
```

**Comment by dileks** [comment]
This check has to be...
When `-z -noreloc-overflow` is available for Linker than set `-pie` together with `--no-dynamic-linker`.

**Comment by dileks** [comment]
@GeorgiiR 
```
ld.bfd --help
-z noreloc-overflow         Disable relocation overflow check
```

Can we have this for ld.lld?
Is there a replacement (option) or combination of replacement for lld?

**Comment by GeorgiiR** [comment]
> Is there a replacement (option) or combination of replacement for lld?
What about -noinhibit-exec?

>Can we have this for ld.lld?
I am not sure I understood the scenario completely, but In LLD we welcome any patches with the explanation of the use cases. If -noinhibit-exec does not work for you, please explain why.

**Comment by dileks** [comment]
@GeorgiiR 
I try to find a substitute for the x86-64 case:
```
[ arch/x86/boot/compressed/Makefile ]

KBUILD_LDFLAGS := -m elf_$(UTS_MACHINE)
# Compressed kernel should be built as PIE since it may be loaded at any
# address by the bootloader.
ifeq ($(CONFIG_X86_32),y)
KBUILD_LDFLAGS += $(call ld-option, -pie) $(call ld-option, --no-dynamic-linker)
else
# To build 64-bit compressed kernel as PIE, we disable relocation
# overflow check to avoid relocation overflow error with a new linker
# command-line option, -z noreloc-overflow.
KBUILD_LDFLAGS += $(shell $(LD) --help 2>&1 | grep -q "\-z noreloc-overflow" \
        && echo "-z noreloc-overflow -pie --no-dynamic-linker")
endif
LDFLAGS_vmlinux := -T
```
Can I combine `-noinhibit-exec` with `-pie` and `--no-dynamic-linker`?

**Comment by GeorgiiR** [comment]
-noinhibit-exec is actually some option that just allows ignoring the errors in the linker. We do not have any smart logic for it in LLD. We are not very consistent with GNU ld, but I believe it is because this option is not very popular. So again, what we try to do in LLD is just to allow to produce an output in some cases. Answering your question, neither -pie or --no-dynamic-linker or anything else should prevent us from doing that. If something like that happens we might just want to extend our implementation I think.

**Comment by dileks** [comment]
@GeorgiiR 
Thanks for the explanations. I am trying with `-noinhibit-exec` now and will report.

**Comment by dileks** [comment]
With this change I see:
```
diff --git a/arch/x86/boot/compressed/Makefile b/arch/x86/boot/compressed/Makefile
index 6b84afdd7538..2027218e1137 100644
--- a/arch/x86/boot/compressed/Makefile
+++ b/arch/x86/boot/compressed/Makefile
@@ -48,13 +48,18 @@ KBUILD_LDFLAGS := -m elf_$(UTS_MACHINE)
 # address by the bootloader.
 ifeq ($(CONFIG_X86_32),y)
 KBUILD_LDFLAGS += $(call ld-option, -pie) $(call ld-option, --no-dynamic-linker)
-else
+endif # CONFIG_X86_32
 # To build 64-bit compressed kernel as PIE, we disable relocation
 # overflow check to avoid relocation overflow error with a new linker
 # command-line option, -z noreloc-overflow.
-KBUILD_LDFLAGS += $(shell $(LD) --help 2>&1 | grep -q "\-z noreloc-overflow" \
-       && echo "-z noreloc-overflow -pie --no-dynamic-linker")
-endif
+ifeq ($(CONFIG_X86_64),y)
+ifeq ($(CONFIG_LD_IS_LLD),y)
+KBUILD_LDFLAGS += $(call ld-option, -noinhibit-exec)
+else
+KBUILD_LDFLAGS += $(call ld-option, -z noreloc-overflow)
+endif # CONFIG_LD_IS_LLD
+KBUILD_LDFLAGS += $(call ld-option, -pie) $(call ld-option, --no-dynamic-linker)
+endif # CONFIG_X86_64
 LDFLAGS_vmlinux := -T
 
 hostprogs-y    := mkpiggy
```

I see this...
```
make -f ./scripts/Makefile.build obj=arch/x86/boot arch/x86/boot/bzImage
make -f ./scripts/Makefile.build obj=arch/x86/boot/compressed arch/x86/boot/compressed/vmlinux
        for obj in arch/x86/boot/compressed/head_64.o arch/x86/boot/compressed/misc.o arch/x86/boot/compressed/string.o arch/x86/boot/compressed/cmdline.o arch/x86/boot/compressed/error.o arch/x86/boot/compressed/piggy.o arch/x86/boot/compressed/cpuflags.o arch/x86/boot/compressed/early_serial_console.o arch/x86/boot/compressed/kaslr.o arch/x86/boot/compressed/kaslr_64.o arch/x86/boot/compressed/mem_encrypt.o arch/x86/boot/compressed/pgtable_64.o arch/x86/boot/compressed/acpi.o arch/x86/boot/compressed/eboot.o arch/x86/boot/compressed/efi_stub_64.o arch/x86/boot/compressed/efi_thunk_64.o; do readelf -S $obj | grep -qF .rel.local && { echo "error: $obj has data relocations!" >&2; exit 1; } || true; done; mylinker -m elf_x86_64  -noinhibit-exec  -pie  --no-dynamic-linker   -T arch/x86/boot/compressed/vmlinux.lds arch/x86/boot/compressed/head_64.o arch/x86/boot/compressed/misc.o arch/x86/boot/compressed/string.o arch/x86/boot/compressed/cmdline.o arch/x86/boot/compressed/error.o arch/x86/boot/compressed/piggy.o arch/x86/boot/compressed/cpuflags.o arch/x86/boot/compressed/early_serial_console.o arch/x86/boot/compressed/kaslr.o arch/x86/boot/compressed/kaslr_64.o arch/x86/boot/compressed/mem_encrypt.o arch/x86/boot/compressed/pgtable_64.o arch/x86/boot/compressed/acpi.o arch/x86/boot/compressed/eboot.o arch/x86/boot/compressed/efi_stub_64.o drivers/firmware/efi/libstub/lib.a arch/x86/boot/compressed/efi_thunk_64.o -o arch/x86/boot/compressed/vmlinux
ld.lld: error: can't create dynamic relocation R_X86_64_32 against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
...
```
...which is expected when substituting the last make-line with BFD and its corresponding linker-options.
I also tried to `-z notext` to linker-options and/or `-fPIC` to cflags which did not help.
I will re-check this.

As a summary `-noinhibit-exec`is what we want.
Thanks @GeorgiiR 

[x86-boot-compressed-Makefile_diff.txt](https://github.com/ClangBuiltLinux/linux/files/2960838/x86-boot-compressed-Makefile_diff.txt)
[build-log_noinhibit-exec.txt](https://github.com/ClangBuiltLinux/linux/files/2960841/build-log_noinhibit-exec.txt)

**Comment by dileks** [comment]
Problematic seems to be `-pie`, dropping it from the line below let me link `arch/x86/boot/compressed/vmlinux` successfully.
```
mylinker -m elf_x86_64  -noinhibit-exec  -pie  --no-dynamic-linker   -T arch/x86/boot/compressed/vmlinux.lds arch/x86/boot/compressed/head_64.o arch/x86/boot/compressed/misc.o arch/x86/boot/compressed/string.o arch/x86/boot/compressed/cmdline.o arch/x86/boot/compressed/error.o arch/x86/boot/compressed/piggy.o arch/x86/boot/compressed/cpuflags.o arch/x86/boot/compressed/early_serial_console.o arch/x86/boot/compressed/kaslr.o arch/x86/boot/compressed/kaslr_64.o arch/x86/boot/compressed/mem_encrypt.o arch/x86/boot/compressed/pgtable_64.o arch/x86/boot/compressed/acpi.o arch/x86/boot/compressed/eboot.o arch/x86/boot/compressed/efi_stub_64.o drivers/firmware/efi/libstub/lib.a arch/x86/boot/compressed/efi_thunk_64.o -o arch/x86/boot/compressed/vmlinux
```

**Comment by GeorgiiR** [comment]
If something wrong with the -pie + -noinhibit-exec and you can provide us a patch or at least a --reproduce file (and you're interested in such a patch) then please do and I *think* we would accept it very fast ;) At least it seems to me that accepting additional cases for -noinhibit-exec shouldn't be a problem at all..

**Comment by dileks** [comment]
@GeorgiiR 
How to provide a `--reproduce file`?

**Comment by GeorgiiR** [comment]
> @GeorgiiR
> How to provide a `--reproduce file`?

You can either set an environment variable to LLD_REPRODUCE=filename.tar or pass
the option with a reproduce file name directly to the linker: lld --reproduce filename.tar

**Comment by dileks** [comment]
Snippet from [1]:

```
diff --git a/arch/x86/boot/compressed/Makefile b/arch/x86/boot/compressed/Makefile
index fa42f895fdde..4f24baa8cdeb 100644
--- a/arch/x86/boot/compressed/Makefile
+++ b/arch/x86/boot/compressed/Makefile
@@ -42,16 +42,16 @@ KBUILD_AFLAGS  := $(KBUILD_CFLAGS) -D__ASSEMBLY__
 GCOV_PROFILE := n
 UBSAN_SANITIZE :=n
 
-LDFLAGS := -m elf_$(UTS_MACHINE)
+override LDFLAGS := -m elf_$(UTS_MACHINE)
 # Compressed kernel should be built as PIE since it may be loaded at any
 # address by the bootloader.
 ifeq ($(CONFIG_X86_32),y)
-LDFLAGS += $(call ld-option, -pie) $(call ld-option, --no-dynamic-linker)
+override LDFLAGS += $(call ld-option, -pie) $(call ld-option, --no-dynamic-linker)
 else
 # To build 64-bit compressed kernel as PIE, we disable relocation
 # overflow check to avoid relocation overflow error with a new linker
 # command-line option, -z noreloc-overflow.
-LDFLAGS += $(shell $(LD) --help 2>&1 | grep -q "\-z noreloc-overflow" \
+override LDFLAGS += $(shell $(LD) --help 2>&1 | grep -q "\-z noreloc-overflow" \
 	&& echo "-z noreloc-overflow -pie --no-dynamic-linker")
 endif
 LDFLAGS_vmlinux := -T
```

Recommendation from [2]:
```
make LDFLAGS_KERNEL=...  LDFLAGS_MODULE=...
```


[1] https://lore.kernel.org/r/20180704150857.szamkvy6jx3fqxlf@kshutemo-mobl1/
[2] https://lore.kernel.org/r/CAK7LNARMbt0h4WVdzPzKhMQD-M4ABjffjo4TdtK40RV-NGzTLw@mail.gmail.com/

**Comment by dileks** [comment]
Answer and suggestion from Masahiro Yamada, see [1].

[1] https://lore.kernel.org/r/CAK7LNAQoBs5_0t_FUqRCBm4ir4PuhyW1gSL+xmoM8_uPHrBP1Q@mail.gmail.com/

**Comment by dileks** [comment]
Referenced-by: "x86/boot: Correct relocation destination on old linkers"

[1] https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=x86/boot&id=5214028dd89e49ba27007c3ee475279e584261f0

**Comment by dileks** [comment]
@tpimh 

I looked again at the code.

For `CONFIG_X86_32=y` these linker options `-pie` and `--no-dynamic-linker` are set.
Both options are also available for example ld.lld-10.
What happens when you drop `-pie` and `--no-dynamic-linker`linker settings when using ld.lld?

With `CONFIG_X86_64=y`I do not see the above linker settings as `-z noreloc-overflow` is not available for example `ld.lld-10` which is a pre-condition to set them.

I use `kbuild: add CONFIG_LD_IS_LLD` (see [1]).

[1] https://git.kernel.org/pub/scm/linux/kernel/git/mips/linux.git/commit/?id=b744b43f79cc758127042e71f9ad7b1afda30f84

**Comment by tpimh** [comment]
I will take a look. I found the implementation of `-z noreloc-overflow` for LLD by @GeorgiiR ([D30256](https://reviews.llvm.org/D30256)), maybe I will try building with it.

**Comment by dileks** [comment]
Arvind Sankar says in [1]:
```
"The BFD linker generates runtime relocations for z_input_len and
z_output_len, even though they are absolute symbols.

This is fixed for binutils-2.35 [1]. Work around this for earlier
versions by defining two variables input_len and output_len in addition
to the symbols, and use them via position-independent references.

This eliminates the last two runtime relocations in the head code and
allows us to drop the -z noreloc-overflow flag to the linker."
```
[1] [v2,3/4] x86/boot: Remove runtime relocations from head_{32,64}.S:
https://lore.kernel.org/r/20200525225918.1624470-4-nivedita@alum.mit.edu/
[2] Full series:
https://lore.kernel.org/r/20200524212816.243139-1-nivedita@alum.mit.edu/

**Comment by nickdesaulniers** [comment]
LLD may not support `-z noreloc-overflow`, but I'm not sure it's required. What's the bug?  If there's a relocation overflow error, it sounds like something is going wrong. Disabling those errors doesn't seem like a correct fix to me.

commit 6d92bc9d483aa ("x86/build: Build compressed x86 kernels as PIE") has more info.  We don't observe the decompression error from that commit message.

**Comment by dileks** [comment]
Just FYI:

There is a patchset `x86/boot: Remove runtime relocations from compressed kernel` (here: v5) from Arvind Sankar which makes the use of `-z noreloc-overflow` unnecessary.
Especially see patches 6/7 and 7/7.

I have tested this patchset on top of Linux v5.8-rc5 (with some additional patches).

[1] https://lore.kernel.org/r/20200715004133.1430068-1-nivedita@alum.mit.edu/
