### ISSUE TITLE
invalid instruction pldw.w in arch/arm/include/asm/processor.h

### ISSUE THREAD

**Issue by agners** [ClangBuiltLinux/linux#412]
When compiling an Thumb-2 ARM kernel with the integrated-as the assembler prints the following error:

```
  ./arch/arm/include/asm/processor.h:133:5: error: invalid instruction
                          "pldw.w\t%a0 \n"
                           ^
  <inline asm>:2:1: note: instantiated into assembly here
  pldw.w  [r0]
  ^
  1 error generated.
```

**Comment by agners** [comment]
See also:
https://llvm.org/pr40972
Work around in Linux:
https://lore.kernel.org/r/13835555f8ef44b21d1b7ddfe1c4203d0981f77e.1551824161.git.stefan@agner.ch/

**Comment by ihalip** [comment]
Looks like this was resolved with https://github.com/llvm/llvm-project/commit/b4207e705b2.
