### ISSUE TITLE
-Wempty-body in drivers/atm/eni.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#42]
```sh
  CC      drivers/atm/eni.o
drivers/atm/eni.c:244:48: warning: for loop has empty body [-Wempty-body]
        for (order = 0; (1 << order) < *size; order++);
                                                      ^
drivers/atm/eni.c:244:48: note: put the semicolon on a separate line to silence this
      warning
```

This can probably be replaced with a `while` loop, or the warning disabled unless `W=1` or something in KBUILD.  Probably `CONFIG_ATM_DRIVERS=y`.

**Comment by nathanchance** [comment]
I assume you mean something like this?
```C
order = 0;
while ((1 << order) < *size)
        order++;
```
Looks uglier to me, seems like this would be a decent warning to hide behind `W=`.

**Comment by tpimh** [comment]
Same with zatm.c:
```
drivers/atm/zatm.c:513:7: warning: while loop has empty body [-Wempty-body]
        zwait;
             ^
drivers/atm/zatm.c:513:7: note: put the semicolon on a separate line to silence this warning
drivers/atm/zatm.c:931:7: warning: while loop has empty body [-Wempty-body]
        zwait;
             ^
drivers/atm/zatm.c:931:7: note: put the semicolon on a separate line to silence this warning
2 warnings generated.
```

**Comment by nathanchance** [comment]
Proposed patch for hiding warning behind `W=1`, could even go lower: https://github.com/nathanchance/patches/blob/master/linux/hax/0006-DO-NOT-UPSTREAM-Kbuild-Hide-Clang-s-Wempty-body-behi.patch

**Comment by nickdesaulniers** [comment]
This warning is not helpful if the loop condition has side effects or
advances a value used later such as a pointer or count.

**Comment by nathanchance** [comment]
Will add that to the commit message shortly.

**Comment by nathanchance** [comment]
Patch updated with all examples from the issue tracker.

**Comment by nickdesaulniers** [comment]
cc @kees for thoughts on disabling this warning.

**Comment by nathanchance** [comment]
Patch sent to mailing list for further discussion: https://lore.kernel.org/lkml/20181016021454.11953-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Masahiro's response to disabling the warning: https://lore.kernel.org/lkml/CAK7LNATO+L4-0SpuWrCnYEUVbxmcQkjOQvMB6PEsFv1b-heJOA@mail.gmail.com/

Patches sent.

https://lore.kernel.org/lkml/20181017180334.8640-1-natechancellor@gmail.com/

https://lore.kernel.org/lkml/20181017180419.8955-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patches accepted:

https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=3e73cc5cd8c03ebc930f1799cc984e746780414a

https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=64b9d16e2d02ca6e5dc8fcd30cfd52b0ecaaa8f4

**Comment by nathanchance** [comment]
Merged into mainline:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3e73cc5cd8c03ebc930f1799cc984e746780414a

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=64b9d16e2d02ca6e5dc8fcd30cfd52b0ecaaa8f4
