### ISSUE TITLE
-Wunused-variable in net/netfilter/nf_nat_masquerade.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#433]
when I disabled CONFIG_IPV6, I got a warning:

```
net/netfilter/nf_nat_masquerade.c:15:21: warning:
unused variable 'masq_refcnt6'
      [-Wunused-variable]
static unsigned int masq_refcnt6 __read_mostly;
                    ^
```

Maybe the only use of this var is when CONFIG_IPV6 is enabled, and its definition should also be guarded?

**Comment by nathanchance** [comment]
Looks like @arndb sent a patch for this earlier: https://lore.kernel.org/lkml/20190325135336.2107801-1-arnd@arndb.de/

**Comment by nickdesaulniers** [comment]
Pablo said this was fixed in nf-next: https://lore.kernel.org/lkml/20190430123102.xia5kwlkqsvinqvi@salvia/
but I don't see it: https://git.kernel.org/pub/scm/linux/kernel/git/pablo/nf-next.git/log/
@arndb can you please chase/follow up to see where this landed?

**Comment by nathanchance** [comment]
Should be https://git.kernel.org/linus/610a43149cabd0c7aa7bed19cbcf05a0249ab32a.

**Comment by nickdesaulniers** [comment]
so this is fixed in mainline?
