### ISSUE TITLE
Toolchain build scripts

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#434]
I've gone ahead and created a set of build scripts to build LLVM, `clang`, `ld.lld`, and binutils from source. This was inspired by issues like #337 (which spawned our [wiki page](https://github.com/ClangBuiltLinux/linux/wiki/Building-Clang-from-source)), #358, and [this thread](https://groups.google.com/d/msg/clang-built-linux/dIkPB1NX_Ts/77b-HS14CgAJ). This can help get people involved (since I've designed it to be fairly self contained by default so people don't have to arbitrarily add repos to their package manager to get a newer build of `clang`/`ld.lld`).

The repo is here: https://github.com/nathanchance/tc-build

I'd like to bring this into our organization and I am happy to take ownership of it, I just want people to be okay with that and review it to see if there are any major objections.

**Comment by dileks** [comment]
Rating: Wonder+Full

**Comment by nickdesaulniers** [comment]
> I'd like to bring this into our organization and I am happy to take ownership of it

Sounds great!  Go for it.  Can you create the empty project under the org, then issue a PR so we can do code review (rather than full blown import)?

> I just want people to be okay with that and review it to see if there are any major objections.

Would you mind just putting the license block in a LICENSE file rather than specifying at the top of a new file (I find that a PITA otherwise).

**Comment by nathanchance** [comment]
Sure to both.

**Comment by nathanchance** [comment]
https://github.com/ClangBuiltLinux/tc-build/pull/1

**Comment by nathanchance** [comment]
https://github.com/ClangBuiltLinux/tc-build/pull/2

The scripts were rewritten in Python, if people want to give it a test.

**Comment by nathanchance** [comment]
Updated the wiki accordingly: https://github.com/ClangBuiltLinux/linux/wiki/Building-Clang-from-source
