### ISSUE TITLE
[objcopy] unknown argument '--prefix-alloc-sections=.init'

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#435]
set in drivers/firmware/efi/libstub/Makefile:
```make
75:STUBCOPY_FLAGS-$(CONFIG_ARM64)	+= --prefix-alloc-sections=.init \
```
via: https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/188279167
```
llvm-objcopy-9: error: unknown argument '--prefix-alloc-sections=.init'
make[5]: *** [drivers/firmware/efi/libstub/Makefile:80: drivers/firmware/efi/libstub/arm-stub.stub.o] Error 1
```
cc @rupprecht @ardbiesheuvel @smithp35

**Comment by nickdesaulniers** [comment]
LLVM bug: https://bugs.llvm.org/show_bug.cgi?id=41266

**Comment by rupprecht** [comment]
Filed as an upstream bug for you: https://llvm.org/pr41266. I haven't looked but it's probably straightforward to add.

btw, elsewhere in that file is a silent failure (it may fail in a later build step):

```
STUBCOPY_RM-y			:= -R *ksymtab* -R *kcrctab*
...
cmd_stubcopy = if $(STRIP) --strip-debug $(STUBCOPY_RM-y) -o $@ $<; \
```

By default, llvm-objcopy/strip doesn't support globs, and only supports removing by regex (and then only with the --regex flag). So either you'll have to change that to:

`STUBCOPY_RM-y			:= --regex -R .*ksymtab.* -R .*kcrctab.*`

or someone will have to support globs in llvm-objcopy.

A second issue is that efi targets are not supported, see https://llvm.org/pr40618. I'm not sure if this affects you -- there doesn't seem to be an explicit `efi-*` target listed anywhere, but EFI is listed elsewhere in that file. Just something to take note of.

**Comment by rupprecht** [comment]
Filed https://llvm.org/pr41268 so that you'll know that `-R *ksymtab*` doesn't actually work.

**Comment by ardbiesheuvel** [comment]
I wonder if we still need to strip ksymtab and kcrctab sections now that I have added -D__DISABLE_EXPORTS

**Comment by nickdesaulniers** [comment]
Note to self: @ardbiesheuvel sent a patch to remove ksymtab/kcrctab stripping: https://git.kernel.org/pub/scm/linux/kernel/git/efi/efi.git/commit/?h=next&id=a72f65180feb446cc59616aab400475679b6ffce

I still think it would be good to fail hard in the presence of wildcard characters until it (or something else) is implemented, but the functionality itself is now less important than `--prefix-alloc-sections=`.

**Comment by nickdesaulniers** [comment]
patch: https://reviews.llvm.org/D60042

**Comment by nickdesaulniers** [comment]
landed: https://reviews.llvm.org/rL360233

**Comment by nickdesaulniers** [comment]
looks resolved locally for arm64 defconfig. 😺 😈
