### ISSUE TITLE
llvm-objcopy: error: --set-section-flags=.text conflicts with --rename-section=.text=.rodata

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#448]
From https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/misc/lkdtm/Makefile?h=v5.1-rc4

To reproduce:

```
make -j$(nproc) ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- OBJCOPY=llvm-objcopy allyesconfig drivers/misc/lkdtm/
```

This is not architecture specific, arm64 is just the easiest to test because it requires no additional patches.

**Comment by nickdesaulniers** [comment]
cc @rupprecht

**Comment by rupprecht** [comment]
The usage linked above is:
```
			--set-section-flags .text=alloc,readonly \
			--rename-section .text=.rodata
```
which should be equivalent to:
```
			--rename-section .text=.rodata,alloc,readonly
```
which is also, IMHO, a much better way to do it as it's less confusing: you don't have to worry about whether --set-section-flags applies to the section name before or after --rename-section is applied.

We _could_ add this for compatibility, but I think it would be easier to fix the objcopy usage here. I'll ask some others if this is reasonable to add.

**Comment by nickdesaulniers** [comment]
Requires `CONFIG_LKDTM` to repro. Patch sent: https://lore.kernel.org/r/20190513222109.110020-1-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment]
v3: https://lore.kernel.org/r/20190515182441.30990-1-ndesaulniers@google.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/gregkh/char-misc/c/e9e08a07385e08f1a7f85c5d1e345c21c9564963

**Comment by nickdesaulniers** [comment]
mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e9e08a07385e08f1a7f85c5d1e345c21c9564963
