### ISSUE TITLE
%c inline assembly output template unrecognized on non-x86 architectures

### ISSUE THREAD

**Issue by kees** [ClangBuiltLinux/linux#449]
The Kconfig test for asm-goto support appears to be cross-compiler unaware, which means that building an arm64 target on an x86 host leads to build failures since Kconfig thinks asm-goto is supported (when CONFIG_JUMP_LABEL=y):

./arch/arm64/include/asm/jump_label.h:33:3: error: invalid operand in inline asm: '1:   nop                                                     .pushsection   __jump_table, "aw"                       .align          3                      .long            1b - ., ${1:l} - .                      .quad           ${0:c} - .                                      .popsection                            '

**Comment by nathanchance** [comment]
I think Nick was tracking this in #6 but I believe this is fixed with:

https://reviews.llvm.org/D60428

https://llvm.org/pr41402

**Comment by kees** [comment]
I think that fixes asm-goto for arm64, yes? This still is a problem for building other targets, I think. It's a weakness in how Kconfig calls $(CC) (without the target information).

**Comment by nathanchance** [comment]
Correct, I wasn't thinking of other architectures. How would we add the target information without interfering with GCC? I wonder if `$(CLANG_FLAGS)` is available to us at that point.

**Comment by nathanchance** [comment]
Indeed it is:

```diff
diff --git a/init/Kconfig b/init/Kconfig
index b00b07e296dd..a0ef9e48be5f 100644
--- a/init/Kconfig
+++ b/init/Kconfig
@@ -33,7 +33,7 @@ config LD_IS_LLD
        def_bool $(success,$(LD) --version | head -n 1 | grep -q 'LLD')

 config CC_HAS_ASM_GOTO
-       def_bool $(success,$(srctree)/scripts/gcc-goto.sh $(CC))
+       def_bool $(success,$(srctree)/scripts/gcc-goto.sh $(CC) $(CLANG_FLAGS))

 config CC_HAS_WARN_MAYBE_UNINITIALIZED
        def_bool $(cc-option,-Wmaybe-uninitialized)

```

Tested by adding `echo "$*" > /tmp/kconfig-test` to the top of `scripts/gcc-goto.sh`.

**Comment by nickdesaulniers** [comment]
Note: look at my latest LLVM commits; I'm currently refactoring AsmPrinter for %c to be recognized by all targets.

**Comment by nickdesaulniers** [comment]
Final piece of the puzzle: https://reviews.llvm.org/D60887 of [8 commits](https://github.com/llvm/llvm-project/commits?author=nickdesaulniers&since=2019-04-01&until=2019-04-29).

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/rL359337

**Comment by nickdesaulniers** [comment]
as reported in https://github.com/ClangBuiltLinux/linux/issues/6#issuecomment-486877672 by @nathanchance ,

I see an error in
> ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- make CC=clang -j46 net/bridge/br_forward.o

**Comment by nickdesaulniers** [comment]
Filed #469 .  Let's sort it out there.
