### ISSUE TITLE
.bss truncated under LTO

### ISSUE THREAD

**Issue by kees** [ClangBuiltLinux/linux#450]
When building with Clang LTO, x86 was corrupting memory. It appears this was due to a truncated .bss section, as tracked down by @samitolvanen 

Patch to fix this:
https://lkml.kernel.org/r/20190415164956.124067-1-samitolvanen@google.com

**Comment by dileks** [comment]
"x86/build/lto: Fix truncated .bss with -fdata-sections"

[1] https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=x86/urgent&id=6a03469a1edc94da52b65478f1e00837add869a3

**Comment by dileks** [comment]
@kees @nickdesaulniers 
Where you able to boot on x86_64 with `CONFIG_LD_DEAD_CODE_DATA_ELIMINATION=y`?

**Comment by kees** [comment]
> @kees @nickdesaulniers @samitolvanen
> Were you able to boot on x86_64 with `CONFIG_LD_DEAD_CODE_DATA_ELIMINATION=y`?

Sami has a set of patches for doing Clang LTO on x86 now (which overlaps a bit with that option). The arm64 series is here:
https://android-review.googlesource.com/q/topic:android-4.19-lto

Sami, are you able to push your x86 LTO patches into a github branch somewhere?

**Comment by samitolvanen** [comment]
> Were you able to boot on x86_64 with `CONFIG_LD_DEAD_CODE_DATA_ELIMINATION=y`?

We don't actually use `CONFIG_LD_DEAD_CODE_DATA_ELIMINATION` anymore, but LLD forces `-fdata-sections` with LTO.

> Sami, are you able to push your x86 LTO patches into a github branch somewhere?

I'll upload my 4.19 changes to Gerrit once I have a chance to clean them up a bit.

**Comment by dileks** [comment]
@samitolvanen 
To use `-fdata-sections` was also suggested in #431.
Where did you place it (arch/x86/Makefile)?

This weekend I will take some time for more experimenting with updating my llvm-toolchain (asm-goto) and LLD on x86-64.
It would be great if you have a Git branch for me.
Thanks.

**Comment by samitolvanen** [comment]
> Where did you place it (arch/x86/Makefile)?

We don't pass `-fdata-sections` to clang, LLD splits the sections with LTO even without the flag.

**Comment by dileks** [comment]
@samitolvanen
Is this with your android-4.19-lto patchset or the default behaviour of LLD?

**Comment by nickdesaulniers** [comment]
mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6a03469a1edc94da52b65478f1e00837add869a3

**Comment by nickdesaulniers** [comment]
@samitolvanen you may want to send this to stable so that @ajs1984 can use LLD for cuttlefish.
