### ISSUE TITLE
Remove linker option "-z common-page-size=4096" for arm32

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#451]
`common-page-size` is not supported by LLD and should be removed in similar fashion to #31.

The line in question is:
https://github.com/ClangBuiltLinux/linux/blob/6f0d349d922ba44e4348a17a78ea51b7135965b1/arch/arm/vdso/Makefile#L14

**Comment by nickdesaulniers** [comment]
probably needs a rebase: https://lore.kernel.org/patchwork/patch/1023578/

**Comment by nathanchance** [comment]
This is now a hard error:

http://git.armlinux.org.uk/cgit/linux-arm.git/commit/?id=fe00e50b2db8c60e4ec90befad1f5bab8ca2c800

https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/195178894

**Comment by nickdesaulniers** [comment]
submitted to the custom patch tracker: https://www.armlinux.org.uk/developer/patches/viewpatch.php?id=8859/1

**Comment by nathanchance** [comment]
That patch will need to be rebased on RMK's latest tree because of http://git.armlinux.org.uk/cgit/linux-arm.git/commit/?id=fe00e50b2db8c60e4ec90befad1f5bab8ca2c800.

**Comment by nickdesaulniers** [comment]
Right, I knew that...thanks
https://www.armlinux.org.uk/developer/patches/viewpatch.php?id=8860/1

**Comment by nickdesaulniers** [comment]
FWIW: https://llvm.org/pr38774 support was added to LLD by @smithp35 in https://reviews.llvm.org/rL360593.  Let's keep this bug open until the kernel patch removing the last trace of `-z common-page-size=` lands.

**Comment by nickdesaulniers** [comment]
accepted: https://www.armlinux.org.uk/developer/patches/viewpatch.php?id=8860/1

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/b777a981d504678d7d90e7449a3da0b2924a2a76
