### ISSUE TITLE
mrs_s/msr_s macros need operand macro adjustments

### ISSUE THREAD

**Issue by kees** [ClangBuiltLinux/linux#452]
The mrs_s/msr_s macros don't work with the Clang integrated assembler (needed for LTO), as asm() macro definitions can't cross asm() blocks. And global definitions can't be used because linking sees them as duplicates.

Proposed patch exists:
https://lkml.kernel.org/r/20190415143821.GA46880@beast

**Comment by nickdesaulniers** [comment]
v5: https://lore.kernel.org/patchwork/patch/1065813/

**Comment by nickdesaulniers** [comment]
landed in be604c616ca71cbf5c860d0cfa4595128ab74189, thanks @samitolvanen and @kees

**Comment by nickdesaulniers** [comment]
might want to think about whether we need this sent back through stable/LTS (@samitolvanen )
