### ISSUE TITLE
CFI failure with android-4.19 patch set when booting arm64 kernel

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#459]
I've been testing the LTO/CFI android-4.19 patchset and while I can build the kernel successfully, it does not boot successfully for me with cuttlefish's arm64 defconfig. Build and boot log are here: https://gist.github.com/nathanchance/743893a543b846a84fce100a9048d419

Is this a known issue or am I doing something wrong? I tried investigating it myself but I'm not sure I entirely understand why it is failing, especially since 4.14 is fine and none of that code appeared to change...

The QEMU flags are the same ones from our continuous integration (along with the rootfs image):

https://github.com/ClangBuiltLinux/continuous-integration/blob/05c20eb4307400df1ef6ea4c84c5f8b872044f8c/driver.sh#L85-L87

https://github.com/ClangBuiltLinux/continuous-integration/blob/05c20eb4307400df1ef6ea4c84c5f8b872044f8c/driver.sh#L274-L278

cc @samitolvanen

**Comment by samitolvanen** [comment]
Can you test this with `HAVE_ARCH_PREL32_RELOCATIONS` disabled in arch/arm64/Kconfig? That CFI failure looks strange though, `deflate_init` seems to have the correct type.

**Comment by nathanchance** [comment]
Hmmm without `HAVE_ARCH_PREL32_RELOCATIONS`, that error is gone but another one replaces it: https://gist.github.com/e559b1f00b6a4199fded941747de4a56

**Comment by samitolvanen** [comment]
I won't be able to test this until a bit later, but this might help:

```diff --git a/arch/arm64/include/asm/syscall.h b/arch/arm64/include/asm/syscall.h
index ad8be16a39c9d..58102652bf9e3 100644
--- a/arch/arm64/include/asm/syscall.h
+++ b/arch/arm64/include/asm/syscall.h
@@ -20,7 +20,7 @@
 #include <linux/compat.h>
 #include <linux/err.h>
 
-typedef long (*syscall_fn_t)(struct pt_regs *regs);
+typedef long (*syscall_fn_t)(const struct pt_regs *regs);
 
 extern const syscall_fn_t sys_call_table[];
 
```

**Comment by samitolvanen** [comment]
Here's a CL that disables PREL32 with LTO:

https://android-review.googlesource.com/c/kernel/common/+/951925

And here are the syscall fixes added to the CFI patch set:

https://android-review.googlesource.com/c/kernel/common/+/951926
https://android-review.googlesource.com/c/kernel/common/+/951927

Note that the 4.19 patch set is currently under active development, so you will probably run into further issues still. There's also an x86 topic, which does boot on cuttlefish at the moment:

https://android-review.googlesource.com/q/topic:android-4.19-x86-cfi

**Comment by nathanchance** [comment]
Thanks, I'll give all of those a test later tonight.

> Note that the 4.19 patch set is currently under active development, so you will probably run into further issues still.

I figured, I debated whether or not to file this at all. Do you want me to hold off on reporting issues until later or do you have a preference for how I should report issues?

**Comment by samitolvanen** [comment]
> Do you want me to hold off on reporting issues until later

Not at all, these reports are very useful. Please feel free to continue filing issues here about LTO/CFI if you notice that something is broken.

**Comment by nathanchance** [comment]
I can confirm the latest patch set builds and boots for arm64 in QEMU, thanks Sami!

**Comment by samitolvanen** [comment]
Great, thanks for testing!
