### ISSUE TITLE
-Wenum-conversion in drivers/crypto/ccree/cc_{hash,aead,ivgen}.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#46]
drivers/crypto/ccree/cc_hash.c is full of:
```sh
  CC      drivers/crypto/ccree/cc_hash.o
drivers/crypto/ccree/cc_hash.c:99:28: warning: implicit conversion from enumeration
      type 'enum cc_hash_conf_pad' to different enumeration type
      'enum drv_crypto_direction' [-Wenum-conversion]
                set_cipher_config0(desc, HASH_DIGEST_RESULT_LITTLE_ENDIAN);
                ~~~~~~~~~~~~~~~~~~       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
`CONFIG_CRYPTO_DEV_CCREE=y`.

**Comment by eiais** [comment]
looking into this, HASH_DIGEST_RESULT_LITTLE_ENDIAN is 2 and drv_crypto_direction doesn't have a 2. set_cipher_config0 says "Any one of the modes defined in [CC7x-DESC]" but I can't find [CC7x-DESC].

**Comment by nathanchance** [comment]
I think the parameter on `set_cipher_config0` should just be changed to an int (or unsigned int).

**Comment by tpimh** [comment]
These files have the problem: `drivers/crypto/ccree/cc_hash.c`, `drivers/crypto/ccree/cc_aead.c`, `drivers/crypto/ccree/cc_ivgen.c`

**Comment by nathanchance** [comment]
@eiais did you ever get around to working on this?

This seems like the simplest solution because as you pointed out, `drv_crypto_direction` doesn't have a 2 value but the `mode` parameter is just used as the left hand value in a shift operation, I don't think the enum type has any significance.

```diff
diff --git a/drivers/crypto/ccree/cc_hw_queue_defs.h b/drivers/crypto/ccree/cc_hw_queue_defs.h
index a091ae57f902..45985b955d2c 100644
--- a/drivers/crypto/ccree/cc_hw_queue_defs.h
+++ b/drivers/crypto/ccree/cc_hw_queue_defs.h
@@ -449,8 +449,7 @@ static inline void set_flow_mode(struct cc_hw_desc *pdesc,
  * @pdesc: pointer HW descriptor struct
  * @mode:  Any one of the modes defined in [CC7x-DESC]
  */
-static inline void set_cipher_mode(struct cc_hw_desc *pdesc,
-                                  enum drv_cipher_mode mode)
+static inline void set_cipher_mode(struct cc_hw_desc *pdesc, int mode)
 {
        pdesc->word[4] |= FIELD_PREP(WORD4_CIPHER_MODE, mode);
 }
@@ -461,8 +460,7 @@ static inline void set_cipher_mode(struct cc_hw_desc *pdesc,
  * @pdesc: pointer HW descriptor struct
  * @mode: Any one of the modes defined in [CC7x-DESC]
  */
-static inline void set_cipher_config0(struct cc_hw_desc *pdesc,
-                                     enum drv_crypto_direction mode)
+static inline void set_cipher_config0(struct cc_hw_desc *pdesc, int mode)
 {
        pdesc->word[4] |= FIELD_PREP(WORD4_CIPHER_CONF0, mode);
 }
```

The alternative is to just use the proper enum value from the expected type which means adding a 2 value.

**Comment by eiais** [comment]
Feel free to take it. I got busy with non 20% work.

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20181010214006.21304-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/herbert/cryptodev-2.6.git/commit/?id=18e732b8035d175181aae2ded127994cb01694f7

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=18e732b8035d175181aae2ded127994cb01694f7
