### ISSUE TITLE
CONFIG_GCOV_PROFILE_FTRACE broken for arm32

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#468]
via KernelCI
```
00:04:00 trace_selftest_dynamic.c:(.text+0xac): undefined reference to `llvm_gcda_start_file'
00:04:00 trace_selftest_dynamic.c:(.text+0xc4): undefined reference to `llvm_gcda_emit_function'
00:04:00 trace_selftest_dynamic.c:(.text+0xd0): undefined reference to `llvm_gcda_emit_arcs'
00:04:00 trace_selftest_dynamic.c:(.text+0xe8): undefined reference to `llvm_gcda_emit_function'
00:04:00 trace_selftest_dynamic.c:(.text+0xf4): undefined reference to `llvm_gcda_emit_arcs'
```

gcov support is in -next (#17 ), but it looks like arm32 allmodconfig enables `CONFIG_GCOV_PROFILE_FTRACE`, which then fails to link the correct files.  Normally, you'd say something like `GCOV_PROFILE := n`, but I think `CONFIG_GCOV_PROFILE_FTRACE` intentionally exists to get code coverage of ftrace.

cc @vo4

**Comment by nickdesaulniers** [comment]
KernelCI is reporting this issue for arm64 now, too. (arm64 linux-next allyesconfig)

**Comment by nathanchance** [comment]
The arm64 report that we just received is for 4.19, which doesn't have the gcov patches from 5.2. Isn't this failure expected?

**Comment by nickdesaulniers** [comment]
ah, ok, I didn't notice it was a 4.19 report (I though it was -next) but that can be justification for the backports.

**Comment by nathanchance** [comment]
arm32 allmodconfig builds fine for me with `ld.lld` on both mainline and -next, I don’t think this is relevant anymore.
