### ISSUE TITLE
-Wignored-attributes in drivers/dma/xilinx/zynqmp_dma.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#47]
```sh
  CC      drivers/dma/xilinx/zynqmp_dma.o
drivers/dma/xilinx/zynqmp_dma.c:166:4: warning: attribute 'aligned' is ignored, place
      it after "struct" to apply attribute to type declaration [-Wignored-attributes]
}; __aligned(64)
   ^
./include/linux/compiler_types.h:200:38: note: expanded from macro '__aligned'
#define __aligned(x)            __attribute__((aligned(x)))
                                               ^
```

`CONFIG_XILINX_DMA=y`

should be on the other side of the `;` (oops!)

**Comment by nathanchance** [comment]
Patch posted: https://lore.kernel.org/lkml/20180911230533.31873-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch v2 based on Nick's suggestion sent: https://lore.kernel.org/lkml/20181025180525.28378-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/vkoul/slave-dma.git/commit/?id=aeaebcc17cdf37065d2693865eeb1ff1c7dc5bf3

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=aeaebcc17cdf37065d2693865eeb1ff1c7dc5bf3
