### ISSUE TITLE
s390 missing inline assembly support

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#470]
llvm bug: https://bugs.llvm.org/show_bug.cgi?id=41744

via: https://github.com/ClangBuiltLinux/continuous-integration/issues/152

**Comment by nathanchance** [comment]
While there might be a missing modifier, the kernel builds fine for s390 after the most recent s390 pull request (and we have wired it up into our CI):

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=740eaf7d4dd255789987a543b0203ca239b37087

Given we have the upstream bug, we should be good here.
