### ISSUE TITLE
arm64: expected absolute expression

### ISSUE THREAD

**Issue by gwelymernans** [ClangBuiltLinux/linux#473]
I'm seeing this with ARM64, but I think it's a generic failure. This occurs when compiling `arch/arm64/kernel/vdso/gettimeofday.S`:

```
$ cat bad.s
.macro jump_slot jumptable, index, label
.if (. - \jumptable) != 4 * (\index)
.error "Jump slot index mismatch"
.endif
  b \label
.endm

.text
jumptable:
  jump_slot jumptable, 0, realtime

$ clang -cc1as -triple aarch64-grtev4-linux-gnu -target-cpu generic -target-feature +neon -mrelocation-model static -o /dev/null bad.s
<instantiation>:1:5: error: expected absolute expression
.if (. - jumptable) != 4 * (0)
    ^
bad.s:10:3: note: while in macro instantiation
  jump_slot jumptable, 0, realtime
  ^
<instantiation>:2:1: error: Jump slot index mismatch
.error "Jump slot index mismatch"
^
bad.s:10:3: note: while in macro instantiation
  jump_slot jumptable, 0, realtime
  ^
```

**Comment by bwendling** [comment]
https://llvm.org/pr41825

**Comment by jcai19** [comment]
> https://llvm.org/pr41825

I have a patch at https://reviews.llvm.org/D69411 for issue #742. The causes of the two issue are different, but their solution seems to be similar enough so I have added code to the same patch to fix issue as well. I have updated the upstream bug with more details.

**Comment by jcai19** [comment]
A new solution is available at https://reviews.llvm.org/D70062.

**Comment by nickdesaulniers** [comment]
Fixed: https://reviews.llvm.org/rGbf142fc43347d8a35a71f46f7dda7e2a0a992e0d
