### ISSUE TITLE
-Wheader-guard in drivers/mfd/stmfx.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#475]
```
In file included from drivers/mfd/stmfx.c:13:
include/linux/mfd/stmfx.h:7:9: warning: 'MFD_STMFX_H' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
#ifndef MFD_STMFX_H
        ^~~~~~~~~~~
include/linux/mfd/stmfx.h:8:9: note: 'MFX_STMFX_H' is defined here; did you mean 'MFD_STMFX_H'?
#define MFX_STMFX_H
        ^~~~~~~~~~~
        MFD_STMFX_H
1 warning generated.
```

Patch sent: https://lore.kernel.org/lkml/20190511012301.2661-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
Sounds like it was accepted, but I did not see it in the expected tree: https://git.kernel.org/pub/scm/linux/kernel/git/lee/mfd.git/log/?h=ib-mfd-pinctrl-5.2-2

https://lore.kernel.org/r/20190513073059.GH4319@dell/

**Comment by nathanchance** [comment]
Unfortunately, this regressed into mainline :(

Lee said he would pick it up for another RC: https://lore.kernel.org/r/20190514185404.GP4319@dell/

**Comment by nathanchance** [comment]
Accepted: https://git.kernel.org/next/linux-next/c/eca37b27f4bbed6a6fcf804d4605220c9ad38cfd

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/b1c83bd84618e5a3ec6395845d11803047a3ef9a
