### ISSUE TITLE
-Wunused-variable in drivers/hwtracing/intel_th/msu.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#477]
```
drivers/hwtracing/intel_th/msu.c:783:21: warning: unused variable 'i' [-Wunused-variable]
        int ret = -ENOMEM, i;
                           ^

drivers/hwtracing/intel_th/msu.c:863:6: warning: unused variable 'i' [-Wunused-variable]
        int i;
            ^
```

**Comment by nathanchance** [comment]
Anders Roxell sent a patch to fix this: https://lore.kernel.org/lkml/20190507135233.31836-1-anders.roxell@linaro.org/

**Comment by nathanchance** [comment]
Patch fixing this accepted: https://git.kernel.org/gregkh/char-misc/c/b96fb368b08f1637cbf780a6b83e36c2c5ed4ff5

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/b96fb368b08f1637cbf780a6b83e36c2c5ed4ff5
