### ISSUE TITLE
LLVM/UML/Libfuzzer

### ISSUE THREAD

**Issue by EricSesterhennX41** [ClangBuiltLinux/linux#495]
hi,

taking the chance for -EWONTFIX, not sure if this is something you are interested in.

I tried to build a libfuzzer enabled linux kernel for UML for some experiments with fuzzing ( https://github.com/x41sec/slides/blob/master/2019-bsides-stuttgart/ContextSwitchingYourKernelFuzzing.pdf ). But got into several issues (eg. sancov counters section descriptions wrong). It would be nice to get this working so one could perform fuzzing tests against a linux kernel in userspace where there is less overhead than with qemu and its easier to control the fuzzing in comparison to fuzzing a running kernel from its own userspace.

$ make ARCH=um CFLAGS="-fsanitize=fuzzer" CC="clang-7" defconfig
...

$ make ARCH=um CFLAGS="-fsanitize=fuzzer" CC="clang-7"
  CC      arch/x86/um/user-offsets.s
clang: warning: argument unused during compilation: '-mno-global-merge'
[-Wunused-command-line-argument]
arch/x86/um/user-offsets.c:19:13: warning: variable 'syscalls' is not
needed and will not be emitted
      [-Wunneeded-internal-declaration]
static char syscalls[] = {
            ^
fatal error: error in backend: Cannot select: 0x43c3400: i64 =
X86ISD::WrapperRIP TargetGlobalTLSAddress:i64<i64*
      @__sancov_lowest_stack> 0 [TF=10]
  0x43c3398: i64 = TargetGlobalTLSAddress<i64* @__sancov_lowest_stack> 0
[TF=10]
In function: foo
clang: error: clang frontend command failed with exit code 70 (use -v to
see invocation)
clang version 7.0.1-8 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to
https://bugs.llvm.org/ and include the crash backtrace, preprocessed
source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/user/1000/user-offsets-e4acae.c
clang: note: diagnostic msg: /tmp/user/1000/user-offsets-e4acae.sh
clang: note: diagnostic msg:

********************
make[1]: *** [scripts/Makefile.build:112: arch/x86/um/user-offsets.s]
Error 70
make: *** [arch/um/Makefile:118: archprepare] Error 2

trying to remove the -no-integrated-as get a lot of inline assembly errors, which are confusing because its not obvious why a UML kernel would need this.

**Comment by nickdesaulniers** [comment]
Cool! That sounds like a great project, and I'm sure the folks working on
libfuzzer would be interested!

It looks like as a prerequisite, we need to be able to build `ARCH=um
CC=clang`, which I don't think anyone here has tried.

So it's probably worthwhile to tackle that first, then see how we would
integrate libfuzzer's runtime dependencies into the kernel.

**Comment by Allegra42** [comment]
>It looks like as a prerequisite, we need to be able to build `ARCH=um
CC=clang`, which I don't think anyone here has tried.

I tried it with a current mainline kernel in this morning while chatting with Eric about this issue. Without adding libfuzzer, the build was OK but I did not run the resulting binary with a rootfs.

**Comment by nickdesaulniers** [comment]
+Dmitry Vyukov <dvyukov@google.com> FYI

**Comment by nickdesaulniers** [comment]
@EricSesterhennX41 that compiler crash should probably be reported upstream. Can you reliably reproduce with upstream/top of tree LLVM?
