### ISSUE TITLE
error: expected a symbol reference (asm goto + LTO)

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#500]
(split off from #6)

With [D56571](https://reviews.llvm.org/D56571) (#6) and [D62555](https://reviews.llvm.org/D62555) (#494) for proper asm goto support, android-4.9 and android-4.14 fail to build with `CONFIG_LTO_CLANG` and `CONFIG_CFI_CLANG`.

android-4.9 error:
```
  LTO     vmlinux.o
<inline asm>:4:14: error: expected a symbol reference in '.quad' directive
        .quad 1b, "", arch_timer_read_ool_enabled
                    ^
LLVM ERROR: Error parsing inline asm
```

android-4.14 error:
```
  LTO     vmlinux.o
<inline asm>:1:9: error: expected a symbol reference
        1: b ""
               ^
<inline asm>:1:7: error: invalid operand
        1: b ""
             ^
<inline asm>:4:14: error: expected a symbol reference in '.quad' directive
        .quad 1b, "", arm64_const_caps_ready+1
                    ^
LLVM ERROR: Error parsing inline asm
```

android-4.19 is fine though... Is there a way to get a bigger picture of the surrounding assembly? I think the `.quad 1b` comes from [arch/arm64/include/asm/jump_label.h](https://android.googlesource.com/kernel/common/+/f2c9d68ed3c2cda6df03afcc150e1c6ad1d072d5/arch/arm64/include/asm/jump_label.h) but I have no idea where the other one comes from.

Without `CONFIG_LTO_CLANG`, everything works as well.

cc @samitolvanen

**Comment by samitolvanen** [comment]
I see a similar issue on a ToT upstream kernel with [LTO_CLANG](https://github.com/samitolvanen/linux/tree/clang-lto).

arm64:
```
  LTO     vmlinux.o
<inline asm>:1:12: error: expected a symbol reference
        1:      b               ""              
                                                ^
<inline asm>:1:8: error: invalid operand
        1:      b               ""              
                                ^
<inline asm>:4:21: error: expected a symbol reference in '.long' directive
                .long           1b - ., "" - .  
                                           ^
LLVM ERROR: Error parsing inline asm
```

It looks like these are from arch/arm64/include/asm/jump_label.h:50 and arch/arm64/include/asm/jump_label.h:52.

x86:
```
  LTO     vmlinux.o
<inline asm>:14:10: error: expected a symbol reference
4: jmp ""
         ^
<inline asm>:28:8: error: expected a symbol reference
 jnz ""
       ^
<inline asm>:29:8: error: expected a symbol reference
 jmp ""
       ^
LLVM ERROR: Error parsing inline asm
```

These are from arch/x86/include/asm/cpufeature.h:196, arch/x86/include/asm/cpufeature.h:197, and arch/x86/include/asm/jump_label.h:43.

@kees and/or @nickdesaulniers, FYI.

> Is there a way to get a bigger picture of the surrounding assembly?

Disabling LTO and not passing -no-integrated-as to clang seems to be the easiest.

**Comment by samitolvanen** [comment]
Disabling `CONFIG_JUMP_LABEL` can be used to work around this issue on arm64, but I think we'll need to fix the integrated assembler for x86.

**Comment by nickdesaulniers** [comment]
A [similar bug](https://godbolt.org/z/9ampMP) was reported [upstream](https://reviews.llvm.org/D56571#1529349).

**Comment by gwelymernans** [comment]
I've looked at this a bit. It *doesn't* happen if you generate a `.s` file. It only seems to happen if you generate a `.o` file. What seems to be happening is that when LLVM goes to emit the inline assembly, it generates a symbol for the block it may jump to. However, it doesn't give that symbol a name (it saves memory since the textual symbol isn't needed). So when it writes the inline ASM, the label's name isn't emitted.

**Comment by gwelymernans** [comment]
Here's a proposed patch. Thoughts?

```
Index: lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp
===================================================================
--- lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp	(revision 366371)
+++ lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp	(working copy)
@@ -139,7 +139,7 @@
           DiagInfo->SrcMgr, OutContext, *OutStreamer, *MAI, BufNum));
 
   // Do not use assembler-level information for parsing inline assembly.
-  OutStreamer->setUseAssemblerInfoForParsing(false);
+  //OutStreamer->setUseAssemblerInfoForParsing(false);
 
   // We create a new MCInstrInfo here since we might be at the module level
   // and not have a MachineFunction to initialize the TargetInstrInfo from and
@@ -394,6 +394,7 @@
         if (*LastEmitted != '}')
           report_fatal_error("Bad ${} expression in inline asm string: '" +
                              Twine(AsmStr) + "'");
+
         ++LastEmitted;    // Consume '}' character.
       }
 
@@ -430,8 +431,13 @@
           if (Modifier[0] == 'l') { // Labels are target independent.
             if (MI->getOperand(OpNo).isBlockAddress()) {
               const BlockAddress *BA = MI->getOperand(OpNo).getBlockAddress();
-              MCSymbol *Sym = AP->GetBlockAddressSymbol(BA);
-              Sym->print(OS, AP->MAI);
+              const Value *BB = BA->getOperand(1);
+              const MachineFunction *MF = MI->getParent()->getParent();
+              for (auto I = MF->begin(), E = MF->end(); I != E; ++I)
+                if (BB == I->getBasicBlock()) {
+                  I->getSymbol()->print(OS, AP->MAI);
+                  break;
+                }
             } else if (MI->getOperand(OpNo).isMBB()) {
               const MCSymbol *Sym = MI->getOperand(OpNo).getMBB()->getSymbol();
               Sym->print(OS, AP->MAI);
```

**Comment by gwelymernans** [comment]
Ahem. Once more without cruft. :-)

```
Index: lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp
===================================================================
--- lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp	(revision 366371)
+++ lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp	(working copy)
@@ -430,8 +430,13 @@
           if (Modifier[0] == 'l') { // Labels are target independent.
             if (MI->getOperand(OpNo).isBlockAddress()) {
               const BlockAddress *BA = MI->getOperand(OpNo).getBlockAddress();
-              MCSymbol *Sym = AP->GetBlockAddressSymbol(BA);
-              Sym->print(OS, AP->MAI);
+              const Value *BB = BA->getOperand(1);
+              const MachineFunction *MF = MI->getParent()->getParent();
+              for (auto I = MF->begin(), E = MF->end(); I != E; ++I)
+                if (BB == I->getBasicBlock()) {
+                  I->getSymbol()->print(OS, AP->MAI);
+                  break;
+                }
             } else if (MI->getOperand(OpNo).isMBB()) {
               const MCSymbol *Sym = MI->getOperand(OpNo).getMBB()->getSymbol();
               Sym->print(OS, AP->MAI);
```

**Comment by nickdesaulniers** [comment]
ah, is this what https://reviews.llvm.org/D64888 is for?

**Comment by gwelymernans** [comment]
Yup!

**Comment by nathanchance** [comment]
It looks like this is fixed (I don't see if on 4.14): https://github.com/llvm/llvm-project/commit/ccbffefccaff42b0d094c9ef0f49fc3e8c8456ea

4.9 kernel/common still fails to build but the error is different so I'll file a new issue.

Should this be merged into the 9.x branch? https://llvm.org/docs/HowToReleaseLLVM.html#merge-requests

**Comment by nickdesaulniers** [comment]
https://llvm.org/pr42147

**Comment by nickdesaulniers** [comment]
Reverted in r366600.

**Comment by nathanchance** [comment]
```
a() {
  asm goto("1: b %l[l_yes]\n\t" : : : : l_yes);
l_yes:;
}
```

**Comment by nathanchance** [comment]
Some creduce reproducers:

`error: expected a symbol reference` with arm64 on android-4.9:

```
a() {
  asm goto("1: b %l[l_yes]\n\t" : : : : l_yes);
l_yes:;
}
```

`error: expected a symbol reference in '.quad' directive` with arm64 on android-4.9:

```
a() {
  _Bool b = 0;
  int *c = 0;
  asm goto("1: b %l[l_yes]\n\t.quad b, %l[l_yes], %c0\n\t"
           :
           : "i"(&c[b])
           :
           : l_yes);
l_yes:;
}
```

`error: expected a symbol reference` with x86 on ToT:

```
a() {
  asm goto(" jmp %l[t_no]\n" : : : : t_no);
t_no:;
}
```

All of the files + interestingness tests are available here: https://github.com/nathanchance/creduce-files

**Comment by gwelymernans** [comment]
Another patch attempt: https://reviews.llvm.org/D65181

**Comment by nathanchance** [comment]
That patch appears to fix all of the issues I have seen including:

* This issue (both the android-4.9 arm64 issue and the x86 ToT issue that Sami noticed)
* #614 
* #615 (the arm allyesconfig one)

However, that patch still causes the x86 allyesconfig error: https://github.com/ClangBuiltLinux/linux/issues/615#issuecomment-513118516

That creduce'd reproducer still shows `.LBB1_2` as an undefined symbol using `nm`.

**Comment by nickdesaulniers** [comment]
Just jotting down some thoughts while this is still fresh in my mind:

LLVM seems to have complicated handling for temporary addresses when `blockaddress` `Constant`s are used in IR.  The current handling is broken for the use of such `Constants` with `callbr`, particularly at the call site `EmitGCCInlineAsmStr` in `llvm/lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp`.  By "complicated handling" it seems that there's machinery for invoking a callback on temporary labels when they're changed/updated/?.  It seems that for `-no-integrated-as`, as noted in https://llvm.org/pr42147, is that the mapping gets messed up.

Some thoughts: does using `blockaddress`es from computed gotos (no asm goto) also result in the creation of `.Ltmp` labels w/ or w/o `-no-integrated-as`?  If not for both cases, I think it's critical to not emit them for `callbr`, but I'm not sure of what that all would entail at this point.

**Comment by kees** [comment]
I can _build_ both arm64 and x86_64 with LTO+CFI+JUMP_LABEL without the "expected a symbol reference" error.

arm64 fails to boot (I assume due to something about JUMP_LABEL vs CFI vs alternatives: separate issue.
x86_64 fails to build for other reasons related to LTO, but no longer this specific bug's issue.

So, I think this did get fixed, but I can't figure out which LLVM commits fixed it. :)

**Comment by nathanchance** [comment]
Should be https://github.com/llvm/llvm-project/commit/1b104388752f66191c867380efde7bbf1f13ca80 and https://github.com/llvm/llvm-project/commit/79176a2542d03107b90613c84f18ccba41ad8fa8.
