### ISSUE TITLE
Clang needs support for __attribute__((target("branch-protection=none")))

### ISSUE THREAD

**Issue by kees** [ClangBuiltLinux/linux#501]
To support `-mbranch-protection=pac-ret`, the kernel needs to be able to disable the compiler's marking of some very early functions that are responsible for actually setting up the PAC protections (since they will return and won't have the needed markings).

https://lore.kernel.org/linux-arm-kernel/201905300851.4A68705B0@keescook/T/#mab342863a3525c41af0d19c647c3c2b30907fb50

**Comment by nickdesaulniers** [comment]
TODO: file a bug in https://bugs.llvm.org/enter_bug.cgi and assign/cc @kbeyls @smithp35

**Comment by nickdesaulniers** [comment]
LLVM bug: https://llvm.org/pr42095

**Comment by DanielKristofKiss** [comment]
Support for `__attribute__((target("branch-protection=none")))`  function attribute landed in LLVM 10.

**Comment by nickdesaulniers** [comment]
Thanks @DanielKristofKiss !
