### ISSUE TITLE
Clang may not be vectorizing xor_8regs_* in arch/arm/lib/xor-neon.c 

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#503]
via this thread w/ @nathanchance and @arndb 
https://groups.google.com/forum/#!topic/clang-built-linux/FOEWAfxhIAc

It seems like `-Rpass-missed='.*'` is suggesting that some code expected to be vectorized is not being vectorized.  We should investigate (current warnings say the transform is possible but not worthwhile).

forked from #496

**Comment by nathanchance** [comment]
LLVM bug that @kbeyls commented on as well: https://llvm.org/pr40976

**Comment by nickdesaulniers** [comment]
Some notes from #496 and the upstream discussion. If we use `#pragma clang loop vectorize(enable)`, we can overrule the cost model to provide a loop versioned on non-overlapping arguments that is vectorized.  If we instead or in addition mark the parameters as `__restrict` qualified, then we get vectorized only loops, though we'd need to check that callers weren't passing overlapping parameters.

**Comment by nickdesaulniers** [comment]
v4 [was resent](https://lore.kernel.org/linux-arm-kernel/20210119131724.308884-1-adrian.ratiu@collabora.com/). I'm still [not yet convinced](https://bugs.llvm.org/show_bug.cgi?id=40976#c8) there is a bug here.

**Comment by nathanchance** [comment]
https://lore.kernel.org/r/20220127081227.2430-1-ardb@kernel.org/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/herbert/cryptodev-2.6/c/297565aa22cfa80ab0f88c3569693aea0b6afb6d

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/297565aa22cfa80ab0f88c3569693aea0b6afb6d
