### ISSUE TITLE
undefined reference to `__compiletime_assert_2340'

### ISSUE THREAD

**Issue by himanshujha199640** [ClangBuiltLinux/linux#507]
config: defconfig

log: https://gist.github.com/himanshujha199640/aa824e564bd478bd58721ffebc69ecb6

My current solution: DRM_I915 [=n]

```
himanshu@himanshu-Vostro-3559:~/clang-thread-safety-analysis$ clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by bulwahn** [comment]
I can confirm that I have seen the same issue on clang-7 and x86.

@nathanchance You must have seen the same issue in the current CI setup, right?

**Comment by nathanchance** [comment]
No, CI is fine but we are only testing the latest stable release (8.0.x) and tip of tree (9.0.0).

https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/205922165

https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/205922191

Ideally, you guys should probably be using at least the latest stable release if not tip of tree given how many issues we have fixed on the LLVM side.

If you can't use [tc-build](https://github.com/ClangBuiltLinux/tc-build), our Docker image has all of the tools so you don't have to alter your environment (or you can use http://apt.llvm.org yourself).

**Comment by bulwahn** [comment]
Thanks, @nathanchance.
I will update and test again, this will probably resolve the build issue.

**Comment by bulwahn** [comment]
Update resolved the issue.
