### ISSUE TITLE
arm64: ThinLTO fails with "Alias must point to a definition" for crc32_le_base

### ISSUE THREAD

**Issue by samitolvanen** [ClangBuiltLinux/linux#509]
When compiling ToT arm64 defconfig with ThinLTO, linking fails with the following error:
```
Alias must point to a definition
i32 (i32, i8*, i64)* @crc32_le_base
Alias must point to a definition
i32 (i32, i8*, i64)* @__crc32c_le_base
LLVM ERROR: Broken module found, compilation aborted!
```

In lib/crc32.c, we have:
```c
u32 __pure __weak crc32_le(u32 crc, unsigned char const *p, size_t len)
{
    ....
}
u32 __pure crc32_le_base(u32, unsigned char const *, size_t) __alias(crc32_le);
```

And in arch/arm64/lib/crc32.S:
```
ENTRY(crc32_le)
alternative_if_not ARM64_HAS_CRC32
        b               crc32_le_base
alternative_else_nop_endif
        __crc32
ENDPROC(crc32_le)
```

This issue is trivially reproducible with the following code:

alias.c:
```c
__attribute__((__weak__)) int __a(int n)
{
	return n;
}
int a(int n)  __attribute__((__alias__("__a")));

int main()
{
	return __a(0);
}
```
alias.s:
```
.arch armv8-a

__a:
	b a
.globl __a 
```

When compiled with `clang -flto=thin -fvisibility=hidden -fuse-ld=lld --target=aarch64-linux-gnu- alias.s alias.c`, we get the same error:
```
Alias must point to a definition
i32 (i32)* @a
LLVM ERROR: Broken module found, compilation aborted!
```

Switching from `-flto=thin` to `-flto` fixes the problem.

**Comment by nickdesaulniers** [comment]
> Switching from -flto=thin to -flto fixes the problem.

Interesting.  What's the difference in the symbols/disassembly between `-flto` and `-flto=thin`.

**Comment by samitolvanen** [comment]
> What's the difference in the symbols/disassembly between

Considering that this doesn't compile with ThinLTO, the difference is that with LTO I actually end up with a binary I can disassemble. :)

I did look at the IR generated for lib/crc32.c and it looks pretty much identical for both, as expected.

**Comment by samitolvanen** [comment]
LLVM bug: https://llvm.org/pr42542

**Comment by samitolvanen** [comment]
Fixed in r369766.
