### ISSUE TITLE
-Wenum-conversion in drivers/gpu/drm/amd/*

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#51]
many instances of:
```sh
  CC      drivers/gpu/drm/amd/amdgpu/../powerplay/hwmgr/ppatomfwctrl.o
drivers/gpu/drm/amd/amdgpu/../powerplay/hwmgr/ppatomfwctrl.c:532:57: warning: 
      implicit conversion from enumeration type 'enum atom_smu11_syspll0_clock_id' to
      different enumeration type 'BIOS_CLKID' (aka 'enum atom_smu9_syspll0_clock_id')
      [-Wenum-conversion]
  ...(!pp_atomfwctrl_get_clk_information_by_clkid(hwmgr, SMU11_SYSPLL0_SOCCLK_ID, &...
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~        ^~~~~~~~~~~~~~~~~~~~~~~
```

and two in:
```
  CC      drivers/gpu/drm/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm_pp_smu.o
drivers/gpu/drm/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm_pp_smu.c:519:32: warning: 
      implicit conversion from enumeration type 'enum wm_set_id' to different
      enumeration type 'enum dm_pp_wm_set_id' [-Wenum-conversion]
                                        ranges->reader_wm_sets[i].wm_inst;
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
drivers/gpu/drm/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm_pp_smu.c:535:32: warning: 
      implicit conversion from enumeration type 'enum wm_set_id' to different
      enumeration type 'enum dm_pp_wm_set_id' [-Wenum-conversion]
                                        ranges->writer_wm_sets[i].wm_inst;
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
```

```
  CC      drivers/gpu/drm/amd/amdgpu/../display/dc/dce/dce_aux.o
drivers/gpu/drm/amd/amdgpu/../display/dc/dce/dce_aux.c:315:19: warning: implicit
      conversion from enumeration type 'enum aux_channel_operation_result' to
      different enumeration type 'enum aux_transaction_reply' [-Wenum-conversion]
                reply->status = AUX_CHANNEL_OPERATION_FAILED_HPD_DISCON;
                              ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
```
  CC      drivers/gpu/drm/amd/amdgpu/../display/dc/i2caux/dce110/aux_engine_dce110.o
drivers/gpu/drm/amd/amdgpu/../display/dc/i2caux/dce110/aux_engine_dce110.c:343:19: warning: 
      implicit conversion from enumeration type 'enum aux_channel_operation_result' to
      different enumeration type 'enum aux_transaction_reply' [-Wenum-conversion]
                reply->status = AUX_CHANNEL_OPERATION_FAILED_HPD_DISCON;
                              ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

`CONFIG_DRM_AMDGPU=y`

**Comment by nathanchance** [comment]
Patch for first one: https://lore.kernel.org/lkml/20180921210106.24310-1-natechancellor@gmail.com/

I don't see the next set of two in -next, seems this was the fix: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=b0a634ac68337b263e01d83359a023676e370cce

Patch for the last set of two: https://lore.kernel.org/lkml/20180921215505.14634-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
First patch accepted (doesn't look like AMD's queue gets added to -next nor do they have a git web interface): https://lore.kernel.org/lkml/CADnq5_P1uq=k4V9A_H+kewbaKtO6tnXXE_DBcuK-Q3tpuYJNow@mail.gmail.com/

Second patch v2: https://lore.kernel.org/lkml/20180927180632.11520-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
> doesn't look like AMD's queue gets added to -next nor do they have a git web interface

Do they list the URL for their tree in `MAINTAINERS`?

**Comment by nathanchance** [comment]
They do but it doesn't have a web interface: git://people.freedesktop.org/~agd5f/linux

**Comment by nathanchance** [comment]
First patch in -next: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=3ea81f7125dfda80e264e4552b1146c88eff1aa7

Second patch v2 was accepted, I'll link the commit in -next when it shows up: https://lore.kernel.org/lkml/1188b75c-9e4f-1c0b-f014-cfd958640caf@amd.com/

**Comment by nathanchance** [comment]
Second patch in drm-next: https://cgit.freedesktop.org/drm/drm/commit/?id=dd330d8c27864494d863caf3cf867e53415fa56e

**Comment by nathanchance** [comment]
All three patches have landed:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3ea81f7125dfda80e264e4552b1146c88eff1aa7

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b0a634ac68337b263e01d83359a023676e370cce

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=dd330d8c27864494d863caf3cf867e53415fa56e
