### ISSUE TITLE
-Wunused-const-variable in drivers/clk/clk-qoriq.c

### ISSUE THREAD

**Issue by Nathan-Huckleberry** [ClangBuiltLinux/linux#525]
Unused variable in clk-qoriq.c.
```
drivers/clk/clk-qoriq.c:138:38: warning: unused variable 'p5020_cmux_grp1' [-Wunused-const-variable]
static const struct clockgen_muxinfo p5020_cmux_grp1 = {
                                     ^
drivers/clk/clk-qoriq.c:146:38: warning: unused variable 'p5020_cmux_grp2' [-Wunused-const-variable]
static const struct clockgen_muxinfo p5020_cmux_grp2 = {
                                     ^
```
Definition of p5020 chip info.
```
static const struct clockgen_muxinfo p5020_cmux_grp1 = {
	{
		[0] = { CLKSEL_VALID, CGA_PLL1, PLL_DIV1 },
		[1] = { CLKSEL_VALID, CGA_PLL1, PLL_DIV2 },
		[4] = { CLKSEL_VALID | CLKSEL_80PCT, CGA_PLL2, PLL_DIV1 },
	}
};

static const struct clockgen_muxinfo p5020_cmux_grp2 = {
	{
		[0] = { CLKSEL_VALID | CLKSEL_80PCT, CGA_PLL1, PLL_DIV1 },
		[4] = { CLKSEL_VALID, CGA_PLL2, PLL_DIV1 },
		[5] = { CLKSEL_VALID, CGA_PLL2, PLL_DIV2 },
	}
};
```

In the definition of the p5020 chip, the p2041 chip's info is used instead. The p5020 and p2041 chips have different info. Possibly a typo.

```
static const struct clockgen_chipinfo chipinfo[] = {
...
	{
		.compat = "fsl,p5020-clockgen",
		.guts_compat = "fsl,qoriq-device-config-1.0",
		.init_periph = p5020_init_periph,
		.cmux_groups = {
			&p2041_cmux_grp1, &p2041_cmux_grp2
		},
		.cmux_to_group = {
			0, 1, -1
		},
		.pll_mask = 0x07,
	},
...
};
```

**Comment by nhukc** [comment]
Messaged author+maintainers https://lore.kernel.org/r/CAJkfWY7qEX3AX3BMqYUranCeQ1j-MvQiZtqesBfwOOW-ZpqkcQ@mail.gmail.com/

**Comment by nhukc** [comment]
Patch submitted https://lore.kernel.org/r/20190627220642.78575-1-nhuck@google.com/

**Comment by nickdesaulniers** [comment]
Time to re-ping the maintainers.
M:	Michael Turquette <mturquette@baylibre.com>
M:	Stephen Boyd <sboyd@kernel.org>
Would've expected it in their tree if accepted: https://git.kernel.org/pub/scm/linux/kernel/git/clk/linux.git

**Comment by nickdesaulniers** [comment]
Reopening until patch hits mainline.

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/clk/linux.git/commit/?h=clk-next&id=a95fb581b144b5e73da382eaedb2e32027610597

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/a95fb581b144b5e73da382eaedb2e32027610597
