### ISSUE TITLE
-Wunused-const-variable in drivers/input/touchscreen/atmel_mxt_ts.c

### ISSUE THREAD

**Issue by Nathan-Huckleberry** [ClangBuiltLinux/linux#527]
```
drivers/input/touchscreen/atmel_mxt_ts.c:259:42: warning: unused variable 'mxt_video_fops' [-Wunused-const-variable]
static const struct v4l2_file_operations mxt_video_fops = {
                                         ^
```
Variable is only used inside an ifdef. It should probably be moved inside the ifdef. V4L2 only seems supported for T37 and `mxt_video_fops` looks specific to V4L2.
```
#ifdef CONFIG_TOUCHSCREEN_ATMEL_MXT_T37
```

**Comment by Nathan-Huckleberry** [comment]
patch: https://groups.google.com/forum/#!topic/clang-built-linux/dF0M5G4-qOY

**Comment by nickdesaulniers** [comment]
mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5cecc2bccc03f5f7b496b43a80fd5b768d44f13c
