### ISSUE TITLE
powerpc build

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/linux#53]
This issue is tracking the work I've been doing to enable clang builds of the powerpc64le kernel. I can open individual issues if you would prefer, but I thought it would be helpful to share the work that is being done.

### Kernel patches

1. https://patchwork.ozlabs.org/patch/967928/
1. https://patchwork.ozlabs.org/patch/966825/
1. https://patchwork.ozlabs.org/patch/967927/

### Clang patches

1. https://reviews.llvm.org/D50965 (https://bugs.llvm.org/show_bug.cgi?id=38864)

### Clang bugs

These occur when building the vectorised raid routines in `lib/raid6/`

1. https://bugs.llvm.org/show_bug.cgi?id=38886
1. https://bugs.llvm.org/show_bug.cgi?id=38887

### Building

The bugs can be worked around by disabling btrfs and raid. With the kernel and clang patches applied to 4.19-rc1 and trunk, a powernv_defconfig can be built and booted:

```
export ARCH=powerpc CROSS_COMPILE=powerpc64le-linux-gnu-
make powernv_defconfig
./scripts/config -e PPC_DISABLE_WERROR -d FTRACE -d BTRFS_FS -d MD_RAID456
make CC=clang-8 CLANG_TRIPLE=powerpc64le-linux-gnu -j128
```

### Booting
```
qemu-system-ppc64 -M powernv -m 3G -nographic -kernel arch/powerpc/boot/zImage.epapr \
 -L ~/skiboot/ -initrd ~/rootfs.cpio.xz

...

Linux version 4.19.0-rc3-00003-g728b25f26bce (joel@ozrom3) (clang version 8.0.0 (trunk 341773)) #12 SMP Mon Sep 10 17:32:05 ACST 2018
```

**Comment by nickdesaulniers** [comment]
@shenki , thanks for the awesome summary (especially the tricky qemu flags, which is one of my most frustrating things to track down).

Questions:
1. Can you provide more context regarding those kernel patches? They are merged, or being carried externally?
2. Can you verify which build of clang that patch went into, and what config it's required for (or is it needed regardless of config)?
3. Those 2 clang bugs both have comments claiming they are duplicated of https://llvm.org/pr31177.  Can you help them decide if they are duplicates or not?
4. So you linked to the clang bugs for raid6, but why do you explicitly disable FTRACE and BTRFS_FS?

**Comment by shenki** [comment]
> @shenki , thanks for the awesome summary (especially the tricky qemu flags, which is one of my most frustrating things to track down).
> 
> Questions:
> 
> 1. Can you provide more context regarding those kernel patches? They are merged, or being carried externally?

The patches are on linuxppc-dev (the powerpc kernel mailing list). I just sent out a v2 of the series with a few more fixes: https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=65639

> 2. Can you verify which build of clang that patch went into, and what config it's required for (or is it needed regardless of config)?

The clang patch is not yet merged (I don't know why not). I did a local build of master with it applied.

> 3. Those 2 clang bugs both have comments claiming they are duplicated of https://llvm.org/pr31177.  Can you help them decide if they are duplicates or not?

Yes, I think they are dupes. Should I mark them as such myself?

I've spoken to some of the clang powerpc developers and they are aware of the issue, and are adding it to their plans to work on. 

 4. So you linked to the clang bugs for raid6, but why do you explicitly disable FTRACE and BTRFS_FS?

FTRACE was due to the `-mno-sched-epilog` issue, which I've now posted a patch for.

BTRFS_FS and MD_RAID456 both select RAID6_PQ. The platform selects ALTIVEC, which causes us to build the files in lib/raid6 which clang cannot build.

I just re-tested from a make mrproper, and we still need PPC_DISABLE_WERROR due to XMON: https://github.com/ClangBuiltLinux/linux/issues/59

**Comment by shenki** [comment]
> especially the tricky qemu flags, which is one of my most frustrating things to track down

I feel your pain. A good reference for qemu flags for exotic architectures is the buildroot tree:

 https://github.com/buildroot/buildroot/tree/master/board/

eg:

 https://github.com/buildroot/buildroot/tree/master/board/qemu/ppc64le-pseries

Where the kernel config is not the upstream defconfig, they often include a Linux .config:

 https://github.com/buildroot/buildroot/tree/master/board/qemu/mips64-malta

**Comment by shenki** [comment]
https://reviews.llvm.org/D50965 is now committed

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D50965 will land in Clang 8.

**Comment by nickdesaulniers** [comment]
@shenki can you update the status of this bug?  I think it should be closed out and finer grain issues filed, that way we can track when & where fixes land. Can you do that, please?

**Comment by shenki** [comment]
We have landed these patches in linux-next for inclusion in 4.20:

- ftrace: Build with CPPFLAGS to get -Qunused-arguments
- powerpc: Disable -Wbuiltin-requires-header when setjmp is used
- powerpc: avoid -mno-sched-epilog on GCC 4.9 and newer
- powerpc: consolidate -mno-sched-epilog into FTRACE flags
- powerpc: remove old GCC version checks
- powerpc: Fix duplicate const clang warning in user access code
- powerpc/boot: Ensure _zimage_start is a weak symbol
- powerpc/pseries: Remove VLA from lparcfg_write()
- powerpc/prom: Remove VLA in prom_check_platform_support()

This was dropped due to a fix landing in clang (https://github.com/ClangBuiltLinux/linux/issues/210):

- powerpc/boot: Fix crt0.S syntax for clang

These are outstanding:

- powerpc: Disable -Wbuiltin-requires-header when setjmp is used (https://github.com/ClangBuiltLinux/linux/issues/59)
- powerpc/Makefiles: Fix clang/llvm build (https://github.com/ClangBuiltLinux/linux/issues/211)

Closing this issue; I'll track the individual problems in their own issue as you suggested.
