### ISSUE TITLE
-Wunused-const-variable in drivers/usb/host/xhci-tegra.c

### ISSUE THREAD

**Issue by Nathan-Huckleberry** [ClangBuiltLinux/linux#533]
```
drivers/usb/host/xhci-tegra.c:357:27: warning: unused variable 'mbox_cmd_name' [-Wunused-const-variable]
static const char * const mbox_cmd_name[] = {
                          ^
```
Each entry of the array holds a string value that matches with command request enums. I would guess that this was intended for logging and was never implemented.

**Comment by Nathan-Huckleberry** [comment]
Reached out to author+maintainers: https://groups.google.com/forum/#!topic/clang-built-linux/Jh6Y6k0bR_Q

**Comment by Nathan-Huckleberry** [comment]
Patch submitted: https://groups.google.com/forum/#!topic/clang-built-linux/Jh6Y6k0bR_Q

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1a65a03561198f38f8198650b52f55a21cbb4b6c
