### ISSUE TITLE
-Wunused-const-variable in kernel/time/timer_list.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#534]
reported via 0day bot: https://groups.google.com/forum/#!topic/clang-built-linux/w27FQOTlb70

> If you fix the issue, kindly add following tag 
> Reported-by: kbuild test robot <lkp@intel.com> 

seems like 0day bot found this via an arm64 allnoconfig build of mainline.

**Comment by Nathan-Huckleberry** [comment]
```
kernel/time/timer_list.c:361:36: warning: unused variable 'timer_list_sops' [-Wunused-const-variable] 
   static const struct seq_operations timer_list_sops = { 
                                      ^ 
```
```
//in kernel/time/timer_list.c
static const struct seq_operations timer_list_sops = {
	.start = timer_list_start,
	.next = timer_list_next,
	.stop = timer_list_stop,
	.show = timer_list_show,
};

static int __init init_timer_list_procfs(void)
{
	struct proc_dir_entry *pe;

	pe = proc_create_seq_private("timer_list", 0400, NULL, &timer_list_sops,
			sizeof(struct timer_list_iter), NULL);
	if (!pe)
		return -ENOMEM;
	return 0;
}
```
There's no warning with `defconfig`, but there is one with `allnoconfig`.
```
//in include/linux/proc_fs.h
#ifdef CONFIG_PROC_FS
...
struct proc_dir_entry *proc_create_seq_private(const char *name, umode_t mode,
		struct proc_dir_entry *parent, const struct seq_operations *ops,
		unsigned int state_size, void *data);
...
#else
#define proc_create_seq_private(name, mode, parent, ops, size, data) ({NULL;})
...
#endif
```
Looks like `allnoconfig` turns off `CONFIG_PROC_FS`. Thus `proc_create_seq_private` expands to NULL. Looks like in other areas of the kernel `CONFIG_PROC_FS` is checked, probably should be here as well.

**Comment by nhukc** [comment]
Patch submitted: https://lore.kernel.org/r/20190614181604.112297-1-nhuck@google.com/

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=timers/core&id=a9314773a91a1d3b36270085246a6715a326ff00

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a9314773a91a1d3b36270085246a6715a326ff00
