### ISSUE TITLE
arm64: ThinLTO+CFI fails with "Called function is not the same type as the call"

### ISSUE THREAD

**Issue by samitolvanen** [ClangBuiltLinux/linux#538]
Ignoring issue #537, ThinLTO+CFI fails when compiling arm64 defconfig with the following error:
```
Called function is not the same type as the call!
  %45 = call i64 @probe_kernel_read(i8* nonnull %10, i8* nonnull %44, i64 %25) #10, !dbg !2405779
in function read_mem.cfi
LLVM ERROR: Broken function found, compilation aborted!
```
This resembles issue #509, except now the alias is weak instead of the function to which it points:
```c
long __weak probe_kernel_read(void *dst, const void *src, size_t size)
    __attribute__((alias("__probe_kernel_read")));

long __probe_kernel_read(void *dst, const void *src, size_t size)
{
	...
}
EXPORT_SYMBOL_GPL(probe_kernel_read);
```
Defining `probe_kernel_read` (and `probe_kernel_write`) as weak functions instead of aliases can be used to work around this issue.

**Comment by nickdesaulniers** [comment]
The return types and formal parameters match.  What do the definitions of `@probe_kernel_read` and `@__probe_kernel_read` looks like in IR?  Surely the attributes on `probe_kernel_read` 's declaration don't need to reappear on its definition?

**Comment by samitolvanen** [comment]
`llvm-modextract -b -n 0 -o - mm/maccess.o | llvm-dis | grep probe_kernel_read`:
```
...
@probe_kernel_read = weak hidden alias i64 (i8*, i8*, i64), i64 (i8*, i8*, i64)* @__probe_kernel_read
define hidden i64 @__probe_kernel_read(i8*, i8*, i64) #0 !dbg !2757 !type !2766 !type !2767 !type !2768 {
...
```

**Comment by samitolvanen** [comment]
r369766 also fixes this issue.
