### ISSUE TITLE
section mismatch in omap3xxx_prm_late_init

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#540]
reported via kernelCI: http://staging-storage.kernelci.org/next-clang/master/next-20190617/arm/allmodconfig/clang-8/build.log

```
WARNING: vmlinux.o(.text+0x84930): Section mismatch in reference from the function omap3xxx_prm_late_init() to the function .init.text:omap3xxx_prm_enable_io_wakeup()
The function omap3xxx_prm_late_init() references
the function __init omap3xxx_prm_enable_io_wakeup().
This is often because omap3xxx_prm_late_init lacks a __init 
annotation or the annotation of omap3xxx_prm_enable_io_wakeup is wrong.
```

**Comment by nathanchance** [comment]
@arndb sent a patch for this a couple of months ago, looks like it never got applied: https://lore.kernel.org/lkml/20190307103557.1688556-1-arnd@arndb.de/

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/27e23d8975270df6999f8b5b3156fc0c04927451
