### ISSUE TITLE
section mismatch in imx6q_obtain_fixed_clk_hw

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#541]
reported via kernelCI: http://staging-storage.kernelci.org/next-clang/master/next-20190617/arm/allmodconfig/clang-8/build.log

```
WARNING: vmlinux.o(.text+0x99173c): Section mismatch in reference from the function imx6q_obtain_fixed_clk_hw() to the function .init.text:imx_obtain_fixed_clock_hw()
The function imx6q_obtain_fixed_clk_hw() references
the function __init imx_obtain_fixed_clock_hw().
This is often because imx6q_obtain_fixed_clk_hw lacks a __init 
annotation or the annotation of imx_obtain_fixed_clock_hw is wrong.
```

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20190618022405.27952-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Arnd sent the same fix, which has been picked up: https://git.kernel.org/shawnguo/c/0e12248c68f3b667ca7899d1d92a3a9f54197a21

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/next/linux-next/c/0e12248c68f3b667ca7899d1d92a3a9f54197a21
