### ISSUE TITLE
-Wreturn-type in arch/arm/include/asm/arch_timer.h

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#542]
reported via kernelCI: http://staging-storage.kernelci.org/next-clang/master/next-20190617/arm/bcm2835_defconfig/clang-8/build.log

```
In file included from ../arch/arm/kernel/vdso.c:30:
../arch/arm/include/asm/arch_timer.h:131:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.
In file included from ../drivers/clocksource/arm_arch_timer.c:31:
../arch/arm/include/asm/arch_timer.h:131:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
```

**Comment by nathanchance** [comment]
This was reported by GCC as well and a patch was sent: https://lore.kernel.org/lkml/20190617093601.34511-1-andrew.murray@arm.com/

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/next/linux-next/c/21c768d5ef2fab62be42c88f32b987c66938bb5f
