### ISSUE TITLE
Building for ARMv6 fails

### ISSUE THREAD

**Issue by agners** [ClangBuiltLinux/linux#55]
In theory LLVM/Clang should be able to build ARMv6 (see ).

However, when enabling "ARMv6 based platforms (ARM11)" in the kernel configuration build fails with:

    /tmp/main-405daa.s: Assembler messages:                                                                                                                                                                            
    /tmp/main-405daa.s:967: Error: selected processor does not support `cpsid i' in ARM mode                                                                                                                           
    /tmp/main-405daa.s:1101: Error: selected processor does not support `cpsie i' in ARM mode                                                                                                                          
    /tmp/main-405daa.s:1180: Error: selected processor does not support `cpsid i' in ARM mode                                                                                                                          
    /tmp/main-405daa.s:1856: Error: selected processor does not support `cpsie i' in ARM mode                                                                                                                          
    clang-6.0: error: assembler command failed with exit code 1 (use -v to see invocation)

This is due to a wrong architecture detection, with what the build system fails back to `-march=arm5t`.

However, when forcing the build system to use ARMv6 (e.g. by setting `-march=armv6[k]`  as a fallback in arch/arm/Makefile), it shows that clang uses a unknown CPU type in the assembler file:

    empty.s: Assembler messages:
    empty.s:4: Error: unknown cpu `arm1176j-s'
    clang-6.0: error: assembler command failed with exit code 1 (use -v to see invocation)

**Comment by agners** [comment]
This is probably an issue in LLVM/Clang: https://reviews.llvm.org/D18086

**Comment by nickdesaulniers** [comment]
Fixed in Clang-8:
https://reviews.llvm.org/rL343303
https://reviews.llvm.org/rC343304
