### ISSUE TITLE
can't find switch jump table in arch/x86/net/bpf_jit_comp.o

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#553]
Makefile and config are the same as uploaded here: #548

With a vanilla clang version 9.0.0 (363704) and Kernel 5.2-rc5 (Suse), I get the following objtool error:

arch/x86/net/bpf_jit_comp.o: warning: objtool: bpf_int_jit_compile()+0x127f: can't find switch jump table

**Comment by ms178** [comment]
Not reproducible any longer with linux-next-next-20190726 and clang version 10.0.0 (366783).

**Comment by nickdesaulniers** [comment]
probably was related to loop unrolling, which I fixed in #551.
