### ISSUE TITLE
unreachable instruction in drivers/block/skd_main.o

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#558]
Makefile and config are the same as uploaded here: #548

With a vanilla clang version 9.0.0 (363704) and Kernel 5.2-rc5 (Suse), I get the following objtool error:

drivers/block/skd_main.o: warning: objtool: skd_pci_probe()+0x391: unreachable instruction

**Comment by ms178** [comment]
Not reproducible any longer with linux-next-next-20190726 and clang version 10.0.0 (366783).

**Comment by nickdesaulniers** [comment]
probably was related to loop unrolling, which I fixed in #551.
