### ISSUE TITLE
unreachable instruction in net/bridge/netfilter/ebtables.o

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#559]
Another one, this time while using "-O3 -march=native -mtune=native" in the top level Makefile and the x86 Makefile (hence not identical with the settings from #548), but it seems these settings do not affect these warnings. 

With a vanilla clang version 9.0.0 (363704) and Kernel 5.2-rc5 (Suse), I get the following objtool error:

net/bridge/netfilter/ebtables.o: warning: objtool: compat_calc_entry()+0x1bb: unreachable instruction

**Comment by ms178** [comment]
Not reproducible any longer with linux-next-next-20190726 and clang version 10.0.0 (366783).

**Comment by nickdesaulniers** [comment]
probably was related to loop unrolling, which I fixed in #551.
