### ISSUE TITLE
unreachable instruction in drivers/gpu/drm/ttm/ttm_bo.o

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#564]
With a vanilla clang version 9.0.0 (363704), Kernel 5.2-rc5 (Suse) and Makefile settings from https://github.com/ClangBuiltLinux/linux/issues/559, I get the following objtool error:

drivers/gpu/drm/ttm/ttm_bo.o: warning: objtool: ttm_bo_device_release()+0x201: unreachable instruction

**Comment by ms178** [comment]
Not reproducible any longer with linux-next-next-20190726 and clang version 10.0.0 (366783).

**Comment by ms178** [comment]
Not reproducible any longer with linux-next-next-20190726 and clang version 10.0.0 (366783).

**Comment by nickdesaulniers** [comment]
probably was related to loop unrolling, which I fixed in #551.
