### ISSUE TITLE
unreachable instruction in net/netfilter/nf_conntrack_proto_gre.o

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#565]
With a vanilla clang version 9.0.0 (363704), Kernel 5.2-rc5 (Suse) and Makefile settings from #559, I get the following objtool error:

net/netfilter/nf_conntrack_proto_gre.o: warning: objtool: nf_ct_gre_keymap_destroy()+0xe2: unreachable instruction

**Comment by ms178** [comment]
Not reproducible any longer with linux-next-next-20190726 and clang version 10.0.0 (366783).

**Comment by nickdesaulniers** [comment]
probably was related to loop unrolling, which I fixed in #551.
