### ISSUE TITLE
undefined stack state + stack state mismatch in drivers/gpu/drm/radeon/evergreen_cs.o:

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#567]
With a vanilla clang version 9.0.0 (363704), Kernel 5.2-rc5 (Suse) and Makefile settings from #559, I get the following objtool errors:

drivers/gpu/drm/radeon/evergreen_cs.o: warning: objtool: evergreen_dma_cs_parse()+0x9: undefined stack state
drivers/gpu/drm/radeon/evergreen_cs.o: warning: objtool: evergreen_dma_cs_parse()+0x0: stack state mismatch: cfa1=6+16 cfa2=7+8

GPU of my laptop is a AMD 6770M (dGPU).

**Comment by ms178** [comment]
This one was also noticed by others upstream (see: https://lore.kernel.org/r/alpine.DEB.2.21.1907182223560.1785@nanos.tec.linutronix.de/), but as I haven't compiled in the radeon drm driver with my current testing efforts with linux-next-next-20190726 and clang version 10.0.0 (366783), I'll leave this open for now.

**Comment by nathanchance** [comment]
I went and grabbed Debian’s config, which Thomas mentioned, to try and reproduce this and I do not see it with ToT LLVM and kernel. If it is still reproducible for you, please give us a `.config` file to reproduce it.
