### ISSUE TITLE
Compilation fails with GNU AR near AR net/built-in.a error

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#568]
With a vanilla clang version 9.0.0 (363704), Kernel 5.2-rc5 (Suse) and Makefile settings from #559 using GNU AR, the compilation fails with:

AR      net/built-in.a
error: Bad exit status from /var/tmp/rpm-tmp.YB77Jh (%build)

**Comment by nickdesaulniers** [comment]
run `make ... V=1` to see how GNU AR is being invoked.  Then take the object files being passed in and verify that they're not garbage files, then report this to binutils.

**Comment by ms178** [comment]
I re-ran the compilation with the mentioned verbose output (this time with just -march=native and -mtune=native added to the default flags). See the attached files for the error output.

As I am not a programmer (compiling the Kernel is just a hobby for me), please advise me what to do next if it is simple enough for a laymen as me to do, as I don't understand what you mean with the first part of the last sentence. I hope my bug reports are of some value to you anyway though.

I use the most recent GCC toolchain available on Tumbleweed from GCC developer Martin Liska's repo, which reports AR as: GNU Binutils; home:marxin:home:marxin:gcc-periodic-testing-v2 / openSUSE_Tumbleweed) 2.32

 
[Error_log.txt](https://github.com/ClangBuiltLinux/linux/files/3315999/Error_log.txt)
[rpm-tmp.GpoahF.txt](https://github.com/ClangBuiltLinux/linux/files/3315997/rpm-tmp.GpoahF.txt)

**Comment by ms178** [comment]
Not reproducible any longer with linux-next-next-20190726 and clang version 10.0.0 (366783).
