### ISSUE TITLE
-Wundef in drivers/pinctrl/qcom/pinctrl-sdm845.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#569]
```
drivers/pinctrl/qcom/pinctrl-sdm845.c:1320:5: warning: 'CONFIG_ACPI' is not defined, evaluates to 0 [-Wundef]
#if CONFIG_ACPI
    ^
1 warning generated.
```

Patch sent: https://lore.kernel.org/lkml/20190621202043.95967-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
Joe's feedback was interesting; seems like there's a few more cases of this pattern of bug.

**Comment by nathanchance** [comment]
Indeed. I'll file a meta issue and look into them when I have time over the next couple of weeks).

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/linusw/linux-pinctrl/c/3fe2f17c0ed5ca1a1ed6291499067256dd338f66

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/next/linux-next/c/3fe2f17c0ed5ca1a1ed6291499067256dd338f66
