### ISSUE TITLE
i386 with integrated-as: non-retpoline compiler

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#574]
```
You are building kernel with non-retpoline compiler.
Please update your compiler.
make: *** [arch/x86/Makefile:308: checkbin] Error 1
```

**Comment by nathanchance** [comment]
I’m just curious, what is your compiler command and what changes have you made to Makefiles?

**Comment by tpimh** [comment]
Only one change: removed this line https://github.com/ClangBuiltLinux/linux/blob/249155c20f9b0754bc1b932a33344cfb4e0c2101/Makefile#L530
Building the kernel with `make -j8 ARCH="x86_64" 'CC=/usr/bin/ccache clang-9' 'HOSTCC=/usr/bin/ccache clang-9' LD=ld.lld-9 HOSTLD=ld.lld-9 AR=llvm-ar-9 NM=llvm-nm-9 OBJDUMP=llvm-objdump-9 OBJCOPY=llvm-objcopy-9 STRIP=llvm-strip-9 AS=clang-9 bzImage` (GNU binutils not installed at all)

**Comment by nickdesaulniers** [comment]
probably some earlier test for `-mretpoline` or whatever is failing due to `-no-integrated-as` so it's not getting added to cflags.

**Comment by tpimh** [comment]
I have successfully compiled x86_64 kernel with Clang integrated assembler. Marking this as unreproducible.

**Comment by tpimh** [comment]
I hit it again with i386 build with LLVM's integrated assembler. Definitely needs more investigation. Reopening.

**Comment by nickdesaulniers** [comment]
So these failures are usually an unsupported flag was added to KBUILD_CFLAGS without first checking it with cc-option.  Then, later checks fail for erroneous reasons.  I recommend adding prints to cc-option, see what the last set of flags that were tested, manually invoke clang with them, observe them fail, then wrap them in cc-option is the typical fix.  We hit this consistently with stack protector and LTO.

**Comment by nickdesaulniers** [comment]
I was able to build+boot
`$ ARCH=i386 make -j71 LLVM=1 LLVM_IAS=1 defconfig` without observing this failure on `next-20201130`. Please reopen with additional STR if you still observe this failure.
