### ISSUE TITLE
can't create dynamic relocation R_386_32 with LLD

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#579]
```
ld.lld: error: can't create dynamic relocation R_386_32 against symbol: _bss in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in 
>>> referenced by arch/x86/boot/compressed/head_32.o:(.text+0x4)
```
This is specific to i386 and LLD. Not yet submitted to LLVM bugzilla.

**Comment by nickdesaulniers** [comment]
arch/x86/boot/compressed/Makefile resets KBUILD_CFLAGS and KBUILD_LDFLAGS.  Can you try:

```diff
diff --git a/arch/x86/boot/compressed/Makefile b/arch/x86/boot/compressed/Makefile
index 6b84afdd7538..90d59a064136 100644
--- a/arch/x86/boot/compressed/Makefile
+++ b/arch/x86/boot/compressed/Makefile
@@ -43,7 +43,7 @@ KBUILD_AFLAGS  := $(KBUILD_CFLAGS) -D__ASSEMBLY__
 GCOV_PROFILE := n
 UBSAN_SANITIZE :=n
 
-KBUILD_LDFLAGS := -m elf_$(UTS_MACHINE)
+KBUILD_LDFLAGS := -m elf_$(UTS_MACHINE) -z notext
 # Compressed kernel should be built as PIE since it may be loaded at any
 # address by the bootloader.
 ifeq ($(CONFIG_X86_32),y)
```

**Comment by nickdesaulniers** [comment]
We do that in arch/arm64/Makefile if CONFIG_RELOCATABLE is set.  So I'm guessing this issue might go away if KASLR (CONFIG_RANDOMIZE_BASE and CONFIG_RELOCATABLE) is used.  If that's the case, then my diff above should probably similarly be guarded like in arch/arm64/Makefile by CONFIG_RELOCATABLE.

**Comment by tpimh** [comment]
Builds fine with `-z notext`, [confirmed](https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/212235992).

**Comment by tpimh** [comment]
I have tested with both CONFIG_RELOCATABLE set and unset and can confirm that the guess was right. I updated the patch:
```patch
--- a/arch/x86/boot/compressed/Makefile
+++ b/arch/x86/boot/compressed/Makefile
@@ -56,6 +56,12 @@ KBUILD_LDFLAGS += $(shell $(LD) --help 2>&1 | grep -q "\-z noreloc-overflow" \
 	&& echo "-z noreloc-overflow -pie --no-dynamic-linker")
 endif
 LDFLAGS_vmlinux := -T
+ifeq ($(CONFIG_RELOCATABLE), y)
+# LLD by default disallows relocations in read-only segments. For a relocatable
+# kernel, we pass -z notext to the linker to explicitly allow relocations. This
+# behavior is default for BFD.
+LDFLAGS_vmlinux += -z notext
+endif
 
 hostprogs-y	:= mkpiggy
 HOST_EXTRACFLAGS += -I$(srctree)/tools/include
```

**Comment by nickdesaulniers** [comment]
I like the check for `CONFIG_RELOCATABLE`. @tpimh did you test that LLD can link the image both w/ and w/o that config enabled? The comment can go in the commit message, rather than in source I think.

**Comment by tpimh** [comment]
Tested with both `CONFIG_RELOCATABLE` set and unset. Links and boots fine in both cases.

**Comment by nickdesaulniers** [comment]
Cool, send it.

**Comment by tpimh** [comment]
https://lore.kernel.org/patchwork/patch/1234153/

**Comment by nickdesaulniers** [comment]
With this series applied: https://lore.kernel.org/lkml/20200717201801.3661843-2-nivedita@alum.mit.edu/T/#u

I was able to link and boot an i386_defconfig with LLD. (Also https://lore.kernel.org/linux-next/20200717213127.3bd426e1@canb.auug.org.au/, and a series I recently sent to Linus most of patches from Brian Gerst plus one).  So this is close to working.
