### ISSUE TITLE
can we compile with -DLLVM_ENABLE_ASSERTIONS=ON

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#589]
clang releases are typically produced with the cmake option `-DCMAKE_BUILD_TYPE=Release` because debug builds are too slow.  `-DLLVM_ENABLE_ASSERTIONS=ON` is a happy medium; a release optimized build but with `LLVM_ASSERT`s kept on.  We should see if we fail any assertions for some allyesoonfig builds.

**Comment by nathanchance** [comment]
I’ll see if I can allocate some time tonight/tomorrow to see what kind of time impact we are looking at here. Doesn’t Chromium do this? I thought there was some discussion about whether to turn this off because of the performance impact.

**Comment by nathanchance** [comment]
Ah, I thought this was in the `tc-build` repo, whoops. I will still take a look at time stats just in case this is something we would want to turn on there (as well as seeing if it is feasible).

**Comment by nathanchance** [comment]
arm little endian allyesconfig shows some assertion failures ([build log](https://gist.githubusercontent.com/nathanchance/52653f5cede3c23523a25ca03bba2efc/raw/24dd42b7ab5c79fc8746772b1e1a28ce07e3b6b5/kernel_assertions.log))

I am going to apply the following LLVM patches to see if anything changes:

* https://reviews.llvm.org/D62555
* https://reviews.llvm.org/D64167
* https://reviews.llvm.org/D64368

**Comment by nathanchance** [comment]
Looks like with all of those patches, the following builds pass with assertions enabled:

* arm little endian allyesconfig
* arm64 little endian allyesconfig
* ppc32 ppc44x_defconfig
* ppc64le powernv_defconfig
* x86_64 allyesconfig

Times:
* Without assertions: 42m 16s
* With assertions: 49m 48s

**Comment by nickdesaulniers** [comment]
That's great to hear, thanks too for the stats!
