### ISSUE TITLE
Declaration of built-in function 'setjmp' requires inclusion of the header <setjmp.h>

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/linux#59]
powerpc's `CONFIG_XMON` fails to build:

```
  CC      arch/powerpc/xmon/xmon.o
In file included from arch/powerpc/xmon/xmon.c:51:
./arch/powerpc/include/asm/setjmp.h:15:13: error: declaration of built-in function 'setjmp' requires inclusion of the header <setjmp.h>
      [-Werror,-Wbuiltin-requires-header]
extern long setjmp(long *);
            ^
./arch/powerpc/include/asm/setjmp.h:16:13: error: declaration of built-in function 'longjmp' requires inclusion of the header <setjmp.h>
      [-Werror,-Wbuiltin-requires-header]
extern void longjmp(long *, long);
            ^
2 errors generated.
```

This is a hard error for powernv_defconfig as it sets -Werror for `arch/powerpc` code.

**Comment by nickdesaulniers** [comment]
`setjmp` and `longjmp` are defined in `setjmp.h` in the c standard library, which the kernel does not use.  Instead, it looks like `arch/powerpc/xmon/xmon.c` includes `asm/setjmp.h` which is  `arch/powerpc/include/asm/setjmp.h`, which simply declares:

```
  extern long setjmp(long *);                                                     
  extern void longjmp(long *, long);
```

I wonder if we should either:
- disable `-Wbuiltin-requires-header` in `arch/powerpc/xmon/Makefile`.
- consider this a bug in clang. Surely you can define your own symbols that conflict with the standard library if you don't include those headers, which the kernel explicitly does not. (`-nostdinc`).  Let me ask some LLVM coworkers their thoughts.

**Comment by stephenhines** [comment]
The best fix is probably to disable this warning. This is expected when either a non-standard header (like is present here), or an already preprocessed source file is used as an input. Alternatively, you could create and \#include a setjmp.h that includes the proper asm/setjmp.h and put that as a system header location in the Makefile. That doesn't seem any better to me, though.

**Comment by shenki** [comment]
I posted a patch to disable this where the powerpc kernel uses it:

 https://patchwork.ozlabs.org/patch/970424/

I think it probably makes sense to disable this for the entire kernel though. I will see what discussion is generated by the patch.

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=aea447141c7e7824b81b49acd1bc78
