### ISSUE TITLE
-Wunused-variable in drivers/watchdog/digicolor_wdt.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#591]
Reported-by: kernelci.org bot <bot@kernelci.org>
```
drivers/watchdog/digicolor_wdt.c:121:6: warning: unused variable 'ret' [-Wunused-variable]
```

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20190709203409.117123-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/next/linux-next/c/7fb832ae72949c883da52d6316ff08f03c75d300
