### ISSUE TITLE
ppc44x_defconfig init segfault on next-20190708+

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#593]
Forgot to create this issue yesterday when I first discovered it.

Commit [6c5875843b87](https://git.kernel.org/next/linux-next/c/6c5875843b87c3adea2beade9d1b8b3d4523900a) ("powerpc: slightly improve cache helpers") causes a boot failure because of an init segfault:

```
Run /init as init process
init[1]: segfault (11) at b7e1d6f4 nip b7daad0c lr b7daacc0 code 2 in libuClibc-1.0.30.so[b7d65000+89000]
init[1]: code: 83bf002c 3b3c0010 813d0004 5529003a 7f994840 419d03f8 7d5de214 63880001 
init[1]: code: 7f9c4850 915f002c 639c0001 911d0004 <938a0004> 4800007c 7f99e040 419c0034 
Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b
CPU: 0 PID: 1 Comm: init Not tainted 5.2.0-next-20190708 #1
Call Trace:
[c7835d48] [c065a660] dump_stack+0x24/0x34 (unreliable)
[c7835d58] [c003a200] panic+0x148/0x378
[c7835db8] [c003d230] exit_mm+0x0/0x1e8
[c7835e08] [c003d4ec] do_group_exit+0x98/0xac
[c7835e28] [c004c3e0] get_signal+0x914/0xae4
[c7835ec8] [c0008e20] do_notify_resume+0xd8/0x2fc
[c7835f38] [c000f97c] do_user_signal+0x2c/0x34
--- interrupt: 300 at 0xb7daad0c
```

Full log: https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/213944668

I reached out to the patch author, who thinks it might be a clang bug but will need some disassembly to see: https://lore.kernel.org/lkml/a5864549-40c3-badd-8c41-d5b7bf3c4f3c@c-s.fr/

I am currently waiting to hear back but if anyone else wants to start digging in in the meantime, I'd appreciate it.

**Comment by nathanchance** [comment]
https://lore.kernel.org/lkml/20190721075846.GA97701@archlinux-threadripper/

cc @daxtens @shenki just in case you guys have any input/thoughts.

**Comment by nickdesaulniers** [comment]
Tentatively marking this a bug in LLVM: https://llvm.org/pr42762

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/r/20190729202542.205309-1-ndesaulniers@google.com/

**Comment by nathanchance** [comment]
This is fixed in mainline now: https://git.kernel.org/linus/ed4289e8b48845888ee46377bd2b55884a55e60b

We should eventually follow up on the LLVM bug but I think this is worth closing for now.
