### ISSUE TITLE
Can not build Linux for RISC-V with clang

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#60]
At the moment it is not possible to build Linux for RISC-V with clang.

**Comment by nickdesaulniers** [comment]
Did you try compiling the kernel with clang for `ARCH=riscv`? If so, can you please start filing bugs in our issue tracker?  Google's RISCV LLVM team has expressed interest in supporting this.

**Comment by tpimh** [comment]
Yes, I did. I'm now trying to find a solution for the problems I found during compilation. But I can start submitting to the issue tracker without solutions.

**Comment by nickdesaulniers** [comment]
thanks! keep filing new bugs and we'll take a look :fire: :water_buffalo:
