### ISSUE TITLE
infinite loop in kexec

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#601]
Reported internally by google production kernel team.  Commenting some of the discussion here.

It seems that kexec is broken; internal teams found that definitions in arch/x86/purgatory/string.c lead to infinite recursion.

https://godbolt.org/z/grs_A9

Fixes are being discussed internally.

CrOS issue: https://bugs.chromium.org/p/chromium/issues/detail?id=984056

**Comment by tpimh** [comment]
I wonder if we can detect more bugs like this one with [LTP](http://linux-test-project.github.io/).

**Comment by dileks** [comment]
Following the discussion CrOS #984056.

Looking at:
```
[ arch/x86/purgatory/Makefile ]

KBUILD_CFLAGS := -fno-strict-aliasing -Wall -Wstrict-prototypes -fno-zero-initialized-in-bss -fno-builtin -ffreestanding -c -Os -mcmodel=large
```

Instead of using `-Os` optimization use `-O2`?
Does that help?

**Comment by dileks** [comment]
@tpimh 
Concerning LTP - are there specific testcases to check `kexec`?

You happen to know the testcase-name(s)?
```
./runltp -p -l <log file name> -f <testcase name>
```

It's a while I used LTP.

**Comment by tpimh** [comment]
I don't know specifically about kexec, but found [kdump test automation suite](https://github.com/linux-test-project/ltp/tree/master/testcases/kdump).

**Comment by nickdesaulniers** [comment]
> Instead of using -Os optimization use -O2?
> Does that help?

Clang generates the references to memcmp/memset unconditionally.  We're testing a patch internally that reuses definitions from arch/x86/boot/compressed/string.c.

**Comment by nickdesaulniers** [comment]
Submitted: https://lore.kernel.org/r/CAKwvOdm_D1RnbzP6ZSuyOjm5DuNFrST4s8ihwVfOyAXm6wOc_g@mail.gmail.com/

**Comment by nickdesaulniers** [comment]
v4: https://lore.kernel.org/r/20190725200625.174838-3-ndesaulniers@google.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/tip/b059f801a937d164e03b33c1848bb3dca67c0b04

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/linus/b059f801a937d164e03b33c1848bb3dca67c0b04

**Comment by nickdesaulniers** [comment]
I've sent backports to 4.19 FWIW.  Also, this was the last major issue before Google's COS kernel team could switch to clang built kernels.  Now Google Cloud VM instances use clang built kernels. :zambia: :zap:
