### ISSUE TITLE
-fheinous-gnu-extensions and invalid output constraint in lib/mpi/generic_mpih-mul1.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#605]
```
lib/mpi/generic_mpih-mul1.c:37:24: error: invalid use of a cast in a inline asm context requiring an l-value: remove the cast or build with -fheinous-gnu-extensions
                umul_ppmm(prod_high, prod_low, s1_ptr[j], s2_limb);
                ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/mpi/longlong.h:652:20: note: expanded from macro 'umul_ppmm'
        : "=l" ((USItype)(w0)), \
                ~~~~~~~~~~^~~
lib/mpi/generic_mpih-mul1.c:37:3: error: invalid output constraint '=h' in asm
                umul_ppmm(prod_high, prod_low, s1_ptr[j], s2_limb);
                ^
lib/mpi/longlong.h:653:7: note: expanded from macro 'umul_ppmm'
             "=h" ((USItype)(w1)) \
             ^
2 errors generated.
```

These errors were fixed in the upstream libgcrypt repo, which should be able to be submitted to the Linux kernel as they are licensed under the LGPLv2:

https://github.com/gpg/libgcrypt/commit/1ecbd0bca31d462719a2a6590c1d03244e76ef89

https://github.com/gpg/libgcrypt/commit/e7ae0ae243c8978a67c802169183187d88557be8

I have reached out to the author of the first patch because his signoff is not present, which I believe will be a problem during submission.

**Comment by nickdesaulniers** [comment]
reminds me of 7b7c1df2883dd4393592859758c3e76207da8b1d and an older bug on ppc

**Comment by nathanchance** [comment]
Correct. Upstream’s solution works so no need to reinvent the wheel I think.

**Comment by phcoder** [comment]
As I said in private e-mail: I'm fine with relicensing it as GPLv2+ and LGPLv2+

Signed-off-by: Vladimir Serbinenko

**Comment by nathanchance** [comment]
Patches sent:

https://lore.kernel.org/lkml/20190812033120.43013-4-natechancellor@gmail.com/

https://lore.kernel.org/lkml/20190812033120.43013-5-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch v2: https://lore.kernel.org/lkml/20190812193256.55103-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/herbert/cryptodev-2.6.git/commit/?id=b0c091ae04f6746f541b9be91809e1f4f43e9a65

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/b0c091ae04f6746f541b9be91809e1f4f43e9a65
