### ISSUE TITLE
-Wuninitialized in arch/mips/lib/uncached.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#606]
```
arch/mips/lib/uncached.c:45:6: warning: variable 'sp' is uninitialized when used here [-Wuninitialized]
        if (sp >= (long)CKSEG0 && sp < (long)CKSEG2)
            ^~
arch/mips/lib/uncached.c:40:18: note: initialize the variable 'sp' to silence this warning
        register long sp __asm__("$sp");
                        ^
                         = 0
1 warning generated.
```

Not really sure how to solve this one.

Full code: https://github.com/torvalds/linux/blob/3b2663ca844648c1b511f4dc8b1d5918174da58b/arch/mips/lib/uncached.c#L38-L80

**Comment by nickdesaulniers** [comment]
I'm guessing `$sp` is the stack pointer on mips?  I'm not sure that the `register` qualifier initializes the variable `sp` to the contents of `$sp`, but rather uses `$sp` for storage.  I wonder if there's a more C-like way of accessing the stack pointer? Also, not sure that `ret` needs to be `register`.

**Comment by gwelymernans** [comment]
The `__asm__("$sp")` bit is what causes it to be the stack pointer.  It doesn't initialize it with the stack pointer. It *is* the stack pointer. And there isn't a C way of getting it, unfortunately. :-/

**Comment by nathanchance** [comment]
Is there a problem with initializing it to zero then?

**Comment by nathanchance** [comment]
Although I guess that would change the value in it?

**Comment by gwelymernans** [comment]
Yeah. :-) The other option is write it as inline assembly instead of ... the name for that code, which I forget at the moment.

**Comment by nathanchance** [comment]
If it is the stack pointer, is it uninitialized then? Should clang even be warning about this?

**Comment by gwelymernans** [comment]
Probably not. I have a vague memory that this cropped up before. But that could just be a false memory.

**Comment by nathanchance** [comment]
Interestingly enough, there was a patch that commented on this a while ago: https://git.kernel.org/linus/fe92da0f355e9f664a56702c36c50e20e84c51cd

Looks like this is actually pointing out there is a problem: https://lore.kernel.org/linux-mips/20200102030229.GA4478@ubuntu-m2-xlarge-x86/

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/linux-mips/20201211102437.3929348-1-anders.roxell@linaro.org/

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/mips/linux.git/commit/?id=5b058973d3205578aa6c9a71392e072a11ca44ef

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/5b058973d3205578aa6c9a71392e072a11ca44ef
