### ISSUE TITLE
-Wpointer-bool-conversion in drivers/hwmon/scmi-hwmon.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#61]
```sh
  CC      drivers/hwmon/scmi-hwmon.o
drivers/hwmon/scmi-hwmon.c:59:24: warning: address of array 'sensor->name' will always
      evaluate to 'true' [-Wpointer-bool-conversion]
        if (sensor && sensor->name)
                   ~~ ~~~~~~~~^~~~
```

`name` must refer to an array embedded in whatever struct `sensor` is a pointer to an instance of.  Likely the second part of the conditional is not needed, but it could be that they meant that the first item in the array is not zero, in which case they'd want `if (sensor && sensor->name[0])`.

**Comment by nathanchance** [comment]
I've sent an email to the author of the driver and the hwmon maintainers asking for clarification on this one: https://lore.kernel.org/lkml/20180915051032.GA23900@flashbox/

**Comment by nathanchance** [comment]
Guenter's response: https://lore.kernel.org/lkml/bb1167c5-d0d7-7d14-d2ba-0df3830ab53a@roeck-us.net/

Patch sent: https://lore.kernel.org/lkml/20180916000506.28905-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch has been accepted and is currently in -next: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=59a5eef8ff68ffe22f03f3c5d97c050ac02e0f6c

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a31796c30e423f58d266df30a9bbf321fc071b30
