### ISSUE TITLE
additional switch table entries

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#611]
From the discussion with @jpoimboe in https://lkml.org/lkml/2019/7/16/759:

it seems that LLVM is producing dead entries in switch tables.  It would likely cut down on code size to discard these.

I should:
1. figure out how to reproduce
2. file a bug upstream in LLVM's issue tracker

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/r/CAKwvOd=5jJxkRaAC+sEYOd9s3vfWDdQzN-a3YxHh-Qen7FHBpA@mail.gmail.com/

**Comment by nickdesaulniers** [comment]
This might be the bug I filed for this issue: https://llvm.org/pr43129
and patch: https://reviews.llvm.org/D68131

**Comment by nathanchance** [comment]
Looks like this would be fixed in LLVM 11 then.
