### ISSUE TITLE
-Wpointer-bool-conversion in drivers/gpu/drm/drm_connector.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#613]
just spotted in x86_64 defconfig mainline:
```
drivers/gpu/drm/drm_connector.c:144:15: warning: address of array 'mode->name' will always evaluate to 'true' [-Wpointer-bool-conversion]
                      mode->name ? mode->name : "",
                      ~~~~~~^~~~ ~
./include/drm/drm_print.h:366:29: note: expanded from macro 'DRM_DEBUG_KMS'
        drm_dbg(DRM_UT_KMS, fmt, ##__VA_ARGS__)
                                   ^~~~~~~~~~~
```

**Comment by nathanchance** [comment]
I could have sworn we filed an issue for this...

Regardless, it's fixed in -next, it regressed into mainline: https://git.kernel.org/next/linux-next/c/e5704b3fe9d5ffa810abd8ce00215f52f3fd675b

**Comment by nickdesaulniers** [comment]
"some compilers" is the way to not have get_maintainers.pl cc our list ;)

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e5704b3fe9d5ffa810abd8ce00215f52f3fd675b
