### ISSUE TITLE
llvm-objcopy doesn't support wildcards

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#616]
based on https://github.com/ClangBuiltLinux/continuous-integration/issues/183#issuecomment-506861074 @nathanchance mentioned that arm64 4.4 builds fail due to missing wildcard support.  We should file a bug in upstream llvm's issue tracker if there's not one already, then see why this is 4.4 specific? Maybe there's a backport we can send to stable.  cc @rupprecht

**Comment by nathanchance** [comment]
https://llvm.org/pr41268

https://github.com/ClangBuiltLinux/linux/issues/478#issuecomment-492420162

**Comment by nickdesaulniers** [comment]
wouldn't the backports simply be:
1. https://github.com/ClangBuiltLinux/linux/commit/696204faa6e8a318320ebb49d9fa69bc8275644d#diff-a293b6e43601de50c3660edbde6b4bde
2. https://github.com/ClangBuiltLinux/linux/commit/02562d0ca1084a688ac5c92e0e92947f62f13093#diff-a293b6e43601de50c3660edbde6b4bde

**Comment by nathanchance** [comment]
Pretty sure that I tried those and the conflicts were fairly invasive... Don't quite recall though. I'll try to revisit this in the next couple of days.

**Comment by tpimh** [comment]
Maybe we can check for objcopy support for regexes and if they are supported, use regexes instead of globs? Or maybe even take it one step further and write a function that converts globs to regexes.

**Comment by nathanchance** [comment]
I just revisited the backports now.

1. 696204faa6e8a318320ebb49d9fa69bc8275644d depends on 81a0bc39ea1960bbf8ece6a895d7cfd2d9efa28a but that doesn't appear to matter for arm64.

2. 02562d0ca1084a688ac5c92e0e92947f62f13093 depends on f922c4abdf7648523589abee9460c87f51630d2f which in turn depends on at least f235541699bcf14fb8be797c6bc1d7106df0eb64, e4aca45950050fc584e036bb1b266ce1264a6daf, and c1a95fda2a40ae8c7aad3fa44fa7718a3710eb2d. I see what appear to be several follow up fixes so I think this is all too invasive for a stable backport.

**Comment by nickdesaulniers** [comment]
Progress: https://llvm.org/pr41268

**Comment by nickdesaulniers** [comment]
dup #478
