### ISSUE TITLE
audit `KBULD_CFLAGS :=` antipattern 

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#618]
```sh
ag 'KBUILD_CFLAGS\s+:='
```
turns up 19 cases.  This is bad as it wipes away important clang flags like `--gcc-toolchain` and `-no-integrated-as`. cc @ajs1984 

I just sent a series for kexec/purgatory:
1. https://lkml.org/lkml/2019/7/22/1138
2. https://lkml.org/lkml/2019/7/22/1139

**Comment by nickdesaulniers** [comment]
https://android-review.googlesource.com/c/kernel/common/+/1089032 for some x86 cases.

v3 of purgatory: https://lore.kernel.org/r/20190723212418.36379-3-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment]
v4: https://lore.kernel.org/r/20190725200625.174838-3-ndesaulniers@google.com/

**Comment by nathanchance** [comment]
Patch for purgatory accepted: https://git.kernel.org/tip/b059f801a937d164e03b33c1848bb3dca67c0b04

**Comment by nathanchance** [comment]
Patch for purgatory merged: https://git.kernel.org/linus/b059f801a937d164e03b33c1848bb3dca67c0b04

**Comment by dileks** [comment]
My first run with using `ag`...
```
root@iniza:~# apt-get install silversearcher-ag

sdi@iniza:~/src/linux-kernel/linux$ ag 'KBUILD_CFLAGS\s+:='

arch/x86/realmode/rm/Makefile
71:KBUILD_CFLAGS        := $(REALMODE_CFLAGS) -D_SETUP -D_WAKEUP \

```

Antipattern from x86 folks in `tip.git#x86/urgent`

```
commit 183e6429186150690cee034eb85745cf2b15ccb4
x86/build: Add -Wnoaddress-of-packed-member to REALMODE_CFLAGS, to silence GCC9 build warning
```

[1] https://packages.debian.org/buster/amd64/silversearcher-ag/filelist
[2] https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=x86/urgent&id=183e6429186150690cee034eb85745cf2b15ccb4

**Comment by nickdesaulniers** [comment]
I'm glad that GCC added -Waddress-of-packed-member, but sad to see it disabled immediately.  So this antipattern is x86 exclusively (currently).

**Comment by dileks** [comment]
@nickdesaulniers

Thanks for the feedback.

What happened to this double?
```
Revert "x86/mm: Identify the end of the kernel area to be reserved"
ANDROID: x86: boot: Makefile: pass CLANG_FLAGS to Kbuild
```

You still have this in android-x86 applied?

**Comment by dileks** [comment]
Someone has seen and played with...

```
commit 67fc918a41cdcce0f2ffe9a0905543d46095c24c (HEAD -> for-5.3/kbuild-clangflags-masahir0y)
Author: Masahiro Yamada <yamada.masahiro@socionext.com>
Date:   Mon Jul 29 18:15:17 2019 +0900

    kbuild: initialize CLANG_FLAGS correctly in the top Makefile
    
    CLANG_FLAGS is initialized by the following line:
    
      CLANG_FLAGS     := --target=$(notdir $(CROSS_COMPILE:%-=%))
    
    ..., which is run only when CROSS_COMPILE is set.
    
    Some build targets (bindeb-pkg etc.) recurse to the top Makefile.
    
    When you build the kernel with Clang but without CROSS_COMPILE,
    the same compiler flags such as -no-integrated-as are accumulated
    into CLANG_FLAGS.
    
    If you run 'make CC=clang' and then 'make CC=clang bindeb-pkg',
    Kbuild will recompile everything needlessly due to the build command
    change.
    
    Fix this by correctly initializing CLANG_FLAGS.
    
    Fixes: 238bcbc4e07f ("kbuild: consolidate Clang compiler flags")
    Cc: <stable@vger.kernel.org> # v4.20+
    Signed-off-by: Masahiro Yamada <yamada.masahiro@socionext.com>

diff --git a/Makefile b/Makefile
index fa0fbe7851ea..5ee6f6889869 100644
--- a/Makefile
+++ b/Makefile
@@ -472,6 +472,7 @@ KBUILD_CFLAGS_MODULE  := -DMODULE
 KBUILD_LDFLAGS_MODULE := -T $(srctree)/scripts/module-common.lds
 KBUILD_LDFLAGS :=
 GCC_PLUGINS_CFLAGS :=
+CLANG_FLAGS :=
 
 export ARCH SRCARCH CONFIG_SHELL HOSTCC KBUILD_HOSTCFLAGS CROSS_COMPILE AS LD CC
 export CPP AR NM STRIP OBJCOPY OBJDUMP PAHOLE KBUILD_HOSTLDFLAGS KBUILD_HOSTLDLIBS
@@ -519,7 +520,7 @@ endif
 
 ifneq ($(shell $(CC) --version 2>&1 | head -n 1 | grep clang),)
 ifneq ($(CROSS_COMPILE),)
-CLANG_FLAGS    := --target=$(notdir $(CROSS_COMPILE:%-=%))
+CLANG_FLAGS    += --target=$(notdir $(CROSS_COMPILE:%-=%))
 GCC_TOOLCHAIN_DIR := $(dir $(shell which $(CROSS_COMPILE)elfedit))
 CLANG_FLAGS    += --prefix=$(GCC_TOOLCHAIN_DIR)
 GCC_TOOLCHAIN  := $(realpath $(GCC_TOOLCHAIN_DIR)/..)
```

**Comment by nathanchance** [comment]
This has come up yet again: https://lore.kernel.org/lkml/3b793c42-8983-4502-1f9e-729cc0ebec47@gmail.com/

**Comment by nathanchance** [comment]
I see `drivers/firmware/efi/libstub/Makefile`, some folders within `arch/s390`, and and some within `arch/x86` that are full blow aways; most of the other ones are filtering. Given that we have not run into this recently aside from the link I posted above, I am going to close this out. We can reopen if we get bit by it again.
