### ISSUE TITLE
drivers/gpu/drm/amd/amdgpu/atom.o: warning: objtool: atom_op_move() falls through to next function atom_op_and()

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#620]
With `-O3`,  linux-next-next-20190726 and clang version 10.0.0 (366783), there is an objtool warning observed in:

drivers/gpu/drm/amd/amdgpu/atom.o: warning: objtool: atom_op_move() falls through to next function atom_op_and()

It should be reproducible while using the attached config plus Makefile and /arch/x86/Makefile settings.

[buildlog_Westmere_2.txt](https://github.com/ClangBuiltLinux/linux/files/3438031/buildlog_Westmere_2.txt)

[config_Westmere_2.txt](https://github.com/ClangBuiltLinux/linux/files/3438034/config_Westmere_2.txt)

[Makefile_Westmere_2.txt](https://github.com/ClangBuiltLinux/linux/files/3438037/Makefile_Westmere_2.txt)

[arch_x86_Makefile.txt](https://github.com/ClangBuiltLinux/linux/files/3438039/arch_x86_Makefile.txt)

_Originally posted by @ms178 in https://github.com/ClangBuiltLinux/linux/issues/548#issuecomment-515672728_

**Comment by ms178** [comment]
Testing with `-O2`,  linux-next-next-20190730 and clang version 10.0.0 (366783) also confirmed this issue.

[buildlog_o2.txt](https://github.com/ClangBuiltLinux/linux/files/3445547/buildlog_o2.txt)

It now errors out at the end with:

WARNING: "phys_base" [vmlinux] is the static EXPORT_SYMBOL
WARNING: "ahci_em_messages" [vmlinux] is the static EXPORT_SYMBOL_GPL
WARNING: "ftrace_set_clr_event" [vmlinux] is the static EXPORT_SYMBOL_GPL
WARNING: "empty_zero_page" [vmlinux] is the static EXPORT_SYMBOL
WARNING: "hypercall_page" [vmlinux] is the static EXPORT_SYMBOL_GPL
  MODINFO modules.builtin.modinfo
ld: drivers/gpio/gpiolib-devres.o: in function `devm_gpiod_get_from_of_node':
(.text+0x172): undefined reference to `gpiod_get_from_of_node'

**Comment by tpimh** [comment]
I got similar warning while building x86_64 kernel `arch/x86/events/intel/uncore_nhmex.o: warning: objtool: nhmex_uncore_msr_enable_event() falls through to next function __uncore_event_show()`.

**Comment by tpgxyz** [comment]
Still occurs with kernel 5.3.1 and LLVM/clang-9.0.0 on x86_64

```
  CC [M]  drivers/gpu/drm/amd/amdgpu/atom.o
BUILDSTDERR: drivers/gpu/drm/amd/amdgpu/atom.o: warning: objtool: atom_op_move() falls through to next function atom_op_and()
  CC [M]  sound/soc/soc-jack.o
```

**Comment by nathanchance** [comment]
I do not see this with ToT LLVM and kernel with the provided `.config`.
