### ISSUE TITLE
ld: drivers/gpio/gpiolib-devres.o: in function devm_gpiod_get_from_of_node': (.text+0x172): undefined reference to gpiod_get_from_of_node'

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#622]
Testing with -O2, linux-next-next-20190730 and clang version 10.0.0 (366783) shows a new issue.

[buildlog_o2.txt](https://github.com/ClangBuiltLinux/linux/files/3445552/buildlog_o2.txt)

It now errors out at the end with:

ld: drivers/gpio/gpiolib-devres.o: in function devm_gpiod_get_from_of_node': (.text+0x172): undefined reference to gpiod_get_from_of_node'

Here is the config used: 
[config.txt](https://github.com/ClangBuiltLinux/linux/files/3445555/config.txt)

_Originally posted by @ms178 in https://github.com/ClangBuiltLinux/linux/issues/621#issuecomment-516293124_

**Comment by ms178** [comment]
Testing with -O2, linux-next-next-20190730, the same config and lld instead of GNU ld shows the same error.

MODPOST vmlinux.o
WARNING: "phys_base" [vmlinux] is the static EXPORT_SYMBOL
WARNING: "ahci_em_messages" [vmlinux] is the static EXPORT_SYMBOL_GPL
WARNING: "ftrace_set_clr_event" [vmlinux] is the static EXPORT_SYMBOL_GPL
WARNING: "empty_zero_page" [vmlinux] is the static EXPORT_SYMBOL
WARNING: "hypercall_page" [vmlinux] is the static EXPORT_SYMBOL_GPL
  MODINFO modules.builtin.modinfo
ld.lld: error: undefined symbol: gpiod_get_from_of_node
>>> referenced by gpiolib-devres.c
>>>               gpio/gpiolib-devres.o:(devm_gpiod_get_from_of_node) in archive drivers/built-in.a

**Comment by nathanchance** [comment]
Not a clang issue: https://lore.kernel.org/lkml/CA+G9fYtWFhak1_N1sAJk=HGo+yzYvrU9DDfZRV_3a8C9JUMT0Q@mail.gmail.com/
