### ISSUE TITLE
Switch fallthrough to empty case statements inconsistent between GCC and Clang

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#636]
While testing @Nathan-Huckleberry's patch (https://reviews.llvm.org/D64838):

```
../include/linux/signal.h:245:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
        case 1: ;
        ^
../include/linux/signal.h:245:2: note: insert '__attribute__((fallthrough));' to silence this warning
        case 1: ;
        ^
        __attribute__((fallthrough));
../include/linux/signal.h:245:2: note: insert 'break;' to avoid fall-through
        case 1: ;
        ^
        break;
```

This comes from [`include/linux/signal.h`](https://github.com/torvalds/linux/blob/v5.3-rc4/include/linux/signal.h#L225-L247) in `siginitset` and `siginitsetinv`:

```c
static inline void siginitset(sigset_t *set, unsigned long mask)
{
	set->sig[0] = mask;
	switch (_NSIG_WORDS) {
	default:
		memset(&set->sig[1], 0, sizeof(long)*(_NSIG_WORDS-1));
		break;
	case 2: set->sig[1] = 0;
	case 1: ;
	}
}

static inline void siginitsetinv(sigset_t *set, unsigned long mask)
{
	set->sig[0] = ~mask;
	switch (_NSIG_WORDS) {
	default:
		memset(&set->sig[1], -1, sizeof(long)*(_NSIG_WORDS-1));
		break;
	case 2: set->sig[1] = -1;
	case 1: ;
	}
}
```

It appears that GCC and Clang disagree on emitting a diagnostic when falling through to an empty case statement.

C++ example because C doesn't work right now (#236): https://godbolt.org/z/dFJyAY

Not sure if that should be considering intentional or a bug but making a note of it because this warning appears 6849 times in an x86 allyesconfig build...

**Comment by nathanchance** [comment]
I think this also falls under this issue:

```
../include/linux/jhash.h:113:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
        case 0: /* Nothing left to add */
        ^
../include/linux/jhash.h:113:2: note: insert 'break;' to avoid fall-through
        case 0: /* Nothing left to add */
        ^
        break;
../include/linux/jhash.h:152:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
        case 0: /* Nothing left to add */
        ^
../include/linux/jhash.h:152:2: note: insert 'break;' to avoid fall-through
        case 0: /* Nothing left to add */
        ^
        break;
12 warnings generated.
```

https://github.com/torvalds/linux/blob/v5.3-rc4/include/linux/jhash.h#L101

```c
	case 2:  a += (u32)k[1]<<8;	/* fall through */
	case 1:  a += k[0];
		 __jhash_final(a, b, c);
	case 0: /* Nothing left to add */
		break;
```

**Comment by nickdesaulniers** [comment]
> It appears that GCC and Clang disagree on emitting a diagnostic when falling through to an empty case statement.

Which does what?

**Comment by nathanchance** [comment]
GCC does not warn, Clang does. Sorry, thought the godbolt link would have made that clear!

I am working through an x86 allyesconfig build after running Joe Perches's cvt_style perl script and most of the warnings I see from clang come from this pattern (falling through to the last case statement that either does nothing or breaks).

**Comment by nathanchance** [comment]
These are the few patterns that I am seeing, hopefully this is a little clearer: https://godbolt.org/z/xgkvIh

**Comment by nathanchance** [comment]
Joe filed a GCC bug, he thinks that GCC is wrong here:

https://lore.kernel.org/lkml/3078e553a777976655f72718d088791363544caa.camel@perches.com/

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91432

**Comment by groeck** [comment]
I am kind of lost about:

```
	case 2:  a += (u32)k[1]<<8;	/* fall through */
	case 1:  a += k[0];
		 __jhash_final(a, b, c);
	case 0: /* Nothing left to add */
		break;
```
Isn't there a "fall through" missing before "case 0:" ? What am I missing ?

**Comment by groeck** [comment]
Never mind, I can see the discussion with the gcc community. Sorry for the noise.

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D91895

**Comment by nathanchance** [comment]
https://lore.kernel.org/lkml/20201121124019.21116-1-ogabbay@kernel.org/

Clang's version of the warning would have caught this ¯\\\_(ツ)\_/¯

```
drivers/misc/habanalabs/gaudi/gaudi.c:5439:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
        default:
        ^
drivers/misc/habanalabs/gaudi/gaudi.c:5439:2: note: insert '__attribute__((fallthrough));' to silence this warning
        default:
        ^
        __attribute__((fallthrough));
drivers/misc/habanalabs/gaudi/gaudi.c:5439:2: note: insert 'break;' to avoid fall-through
        default:
        ^
        break;
1 warning generated.
```

**Comment by nickdesaulniers** [comment]
kernel/sched/core.o (for aarch64) and a few others I haven't yet tracked down produces a fallthrough with no line info...

**Comment by nickdesaulniers** [comment]
Based on @kees ' [feedback](https://reviews.llvm.org/D91895#2417170), I'm going to close this as wontfix.  I'm happy to reopen/revisit, but I think we'll ultimately land the series @GustavoARSilva is working on in #236 .

**Comment by tansy** [comment]
Have you tried to use comment (`/* fall through */` or `/* fallthrough */`, whatever works) as it's been done [here](https://github.com/inikep/lizard/commit/dda3b335e92ecd5caceccc9c577b39dd4e3c9950), or [here](http://stackoverflow.com/questions/45349079/ddg#48702576)?

**Comment by nathanchance** [comment]
Clang does not and will not support fall through comments:

https://godbolt.org/z/fW4zx1dnG

https://llvm.org/pr43465

https://reviews.llvm.org/D73852

The conversion to `__attribute__((__fallthrough__))` is being tracked at #236.

This issue is concerned with the fact that Clang and GCC disagree on warning on cases that fallthrough to `break`, `return`, etc:

https://godbolt.org/z/vvorYjfPj

**Comment by tansy** [comment]
Ok, I get that.
