### ISSUE TITLE
-Wunused-function in drivers/soundwire/slave.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#637]
```
../drivers/soundwire/slave.c:16:12: warning: unused function 'sdw_slave_add' [-Wunused-function]
static int sdw_slave_add(struct sdw_bus *bus,
           ^
1 warning generated.
```

Patch sent: https://lore.kernel.org/lkml/20190813061014.45015-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
My patch was rejected because this one will fix the warning: https://mailman.alsa-project.org/pipermail/alsa-devel/2019-August/153716.html

I'll close this once it is applied in -next. Hopefully further improvements to testing infrastructure like the 0day bot can help prevent warnings like this from cropping up in the future :)

**Comment by nathanchance** [comment]
Fixed in -next but unfortunately, this leaked into mainline: https://git.kernel.org/next/linux-next/c/a2e484585ad306aa8ac84140ef54d722ac8f45df

**Comment by tpgxyz** [comment]
Trying to compile kernel 5.3.1 with LLVM/clang on armv7hnl
Full log is here https://abf.openmandriva.org/build_lists/610529 also links to GitHub sources.

```
BUILDSTDERR: drivers/soundwire/slave.c:16:12: warning: unused function 'sdw_slave_add' [-Wunused-function]
BUILDSTDERR: static int sdw_slave_add(struct sdw_bus *bus,
BUILDSTDERR:            ^
BUILDSTDERR: 1 warning generated.
```

**Comment by nickdesaulniers** [comment]
Looks like a2e484585ad306aa8ac84140ef54d722ac8f45df hit mainline in 5.4.
