### ISSUE TITLE
-Wsection in weim_probe

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#645]
Reported-by: kernelci.org bot <bot@kernelci.org>

```
> Section mismatches:
>     WARNING: vmlinux.o(.text+0xaa84d4): Section mismatch in reference from the function weim_probe() to the function .init.text:imx_weim_gpr_setup()
>     WARNING: vmlinux.o(.text+0xaa860c): Section mismatch in reference from the function weim_probe() to the function .init.text:weim_timing_setup()
```

Looks like two function may need to either be marked `__init` or should not be.

**Comment by ihalip** [comment]
Likely introduced by [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/bus/imx-weim.c?id=4a92f07816ba3020c690cc0f6e9627fec15b335e).

**Comment by ihalip** [comment]
Should have sent it to `linux-next` instead of `linux-kernel`, but the maintaners are CC'd, so hopefully this is fine.

https://patchwork.kernel.org/patch/11114307/

**Comment by nickdesaulniers** [comment]
cc @arndb

**Comment by arndb** [comment]
I'm sorry about the bad timing. I had merged the broken commit yesterday and found the same issue in testing. I applied an identical patch that I produced myself and pushed it out already.

**Comment by ihalip** [comment]
This can be resolved. It was fixed by Arnd, so there's no sense in keeping it open for a few more weeks (Stephen mentioned there will be no -next release until the end of the month [1]).

[1] https://lore.kernel.org/linux-next/20190905160237.2e972a89@canb.auug.org.au/
