### ISSUE TITLE
undefined reference to __memcpy

### ISSUE THREAD

**Issue by butterflyhack** [ClangBuiltLinux/linux#650]
clang compile linux kernel, and some error is as below:
```
drivers/firmware/efi/libstub/efi-stub-helper.o: In function `efi_relocate_kernel':
efi-stub-helper.c:(.text+0x15a4): undefined reference to `__memcpy'
drivers/firmware/efi/libstub/tpm.o: In function `efi_retrieve_tpm2_eventlog':
tpm.c:(.text+0x25e): undefined reference to `__memcpy'
tpm.c:(.text+0x3fe): undefined reference to `__memcpy'
tpm.c:(.text+0x46c): undefined reference to `__memset'
tpm.c:(.text+0x49a): undefined reference to `__memcpy'
```
clang version:clang-10, kernel: 5.3.6-rc7

**Comment by butterflyhack** [comment]
I use the CONFIG_KMSAN instead of CONFIG_KASAN.

**Comment by nickdesaulniers** [comment]
cc @ramosian-glider 

grep turns up no hits for `CONFIG_KMSAN` or `KMSAN` or `MSAN`.  Is that the correct config, or is KMSAN not in the upstream kernel?

**Comment by nathanchance** [comment]
Not in the upstream kernel: https://github.com/google/kmsan

**Comment by ramosian-glider** [comment]
This is fixed in https://github.com/google/kmsan/issues/64, but should be probably closed as invalid, because it's not a Linux or Clang issue per se.
