### ISSUE TITLE
-Wreturn-type in drivers/base/cpu.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#651]
in linux-next arm64 defconfig:
```
drivers/base/cpu.c:404:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
```

**Comment by nathanchance** [comment]
I think this might have been related to https://reviews.llvm.org/D66404#1650349, which is fixed in https://github.com/llvm/llvm-project/commit/e5c0994ddfcf64bbc7e65ebb68890e98141b84d9. I assume this is a local warning you are seeing?
