### ISSUE TITLE
-Wsizeof-array-div warnings

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#655]
r371605 adds a new diagnostic: https://github.com/llvm/llvm-project/commit/3240ad4ced0d3223149b72a4fc2a4d9b67589427

So far in my build tests, I have seen two instances:

```
mm/hugetlb.c:4055:40: warning: expression does not compute the number of elements in this array; element type is 'unsigned long', not 'u32' (aka 'unsigned int') [-Wsizeof-array-div]
        hash = jhash2((u32 *)&key, sizeof(key)/sizeof(u32), 0);
                                          ~~~ ^
mm/hugetlb.c:4049:16: note: array 'key' declared here
        unsigned long key[2];
                      ^
1 warning generated.
```

```
drivers/net/ethernet/amd/xgbe/xgbe-dev.c:361:49: warning: expression does not compute the number of elements in this array; element type is 'u8' (aka 'unsigned char'), not 'u32' (aka 'unsigned int') [-Wsizeof-array-div]
        unsigned int key_regs = sizeof(pdata->rss_key) / sizeof(u32);
                                       ~~~~~~~~~~~~~~  ^
1 warning generated.
```

I have no idea if these are legitimate or not, I am merely documenting them right now.

**Comment by ihalip** [comment]
Coincidentally, I was looking at LLVM commits yesterday and saw this new warning too. Mind if I look into these?

**Comment by ihalip** [comment]
There's another warning in `drivers/net/ethernet/synopsys/dwc-xlgmac-hw.c`, very similar to the one in `xgbe-dev.c`.

At a glance, these warnings seem to be false positives. The pattern is to reinterpret an array of X as an array of Y, and `sizeof(X[])/sizeof(Y)` is done to compute the number of Y elements.

**Comment by nathanchance** [comment]
> Mind if I look into these?

Please do :)

> At a glance, these warnings seem to be false positives.

I was thinking the same thing, this appears to be a deliberate pattern as it only occurs in these few places and places right around it use the `ARRAY_SIZE` macro, which doesn't get that calculation wrong. I wonder why the kernel does this in the first place.

**Comment by davidbolvansky** [comment]
Author of warning here. Yes, unfortunely a false positives but affected is already suspicious and should be improved.

I would suggest to change kernel code to

unsigned blk_size = sizeof(u32);

And then:
// code comment why this weird division (eg: interface requires it)
sizeof(array)/blk_size 

I think also sizeof(array)/ /*block_size=*/sizeof(u32) could work here.

**Comment by davidbolvansky** [comment]
GCC will probably do it soon too:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91741

**Comment by nathanchance** [comment]
Given that this pattern occurs in a few different locations in the net drivers, it might be a good idea to add a macro that explains why this logic happens, maybe something like this (the macro would need to be in a common net header and have a comment, just using this one file as an example):

```diff
diff --git a/drivers/net/ethernet/amd/xgbe/xgbe-dev.c b/drivers/net/ethernet/amd/xgbe/xgbe-dev.c
index d5fd49dd25f3..b2e781dc460b 100644
--- a/drivers/net/ethernet/amd/xgbe/xgbe-dev.c
+++ b/drivers/net/ethernet/amd/xgbe/xgbe-dev.c
@@ -356,9 +356,15 @@ static int xgbe_write_rss_reg(struct xgbe_prv_data *pdata, unsigned int type,
        return ret;
 }
 
+#define RSS_KEY_REGS(key)                      \
+({                                             \
+       unsigned int block_size = sizeof(u32);  \
+       sizeof(key) / block_size;               \
+})
+
 static int xgbe_write_rss_hash_key(struct xgbe_prv_data *pdata)
 {
-       unsigned int key_regs = sizeof(pdata->rss_key) / sizeof(u32);
+       unsigned int key_regs = RSS_KEY_REGS(pdata->rss_key);
        unsigned int *key = (unsigned int *)&pdata->rss_key;
        int ret;
 
```

**Comment by ihalip** [comment]
That macro looks suitable for the ethernet drivers only. I think a more proper fix would be something like this:

```
diff --git a/drivers/net/ethernet/amd/xgbe/xgbe-dev.c b/drivers/net/ethernet/amd/xgbe/xgbe-dev.c
index d5fd49dd25f3..55e3da97a93c 100644
--- a/drivers/net/ethernet/amd/xgbe/xgbe-dev.c
+++ b/drivers/net/ethernet/amd/xgbe/xgbe-dev.c
@@ -358,7 +358,7 @@ static int xgbe_write_rss_reg(struct xgbe_prv_data *pdata, unsigned int type,

 static int xgbe_write_rss_hash_key(struct xgbe_prv_data *pdata)
 {
-       unsigned int key_regs = sizeof(pdata->rss_key) / sizeof(u32);
+        unsigned int key_regs = ARRAY_SIZE_OF(pdata->rss_key, u32);
        unsigned int *key = (unsigned int *)&pdata->rss_key;
        int ret;

diff --git a/drivers/net/ethernet/synopsys/dwc-xlgmac-hw.c b/drivers/net/ethernet/synopsys/dwc-xlgmac-hw.c
index bf6c1c6779ff..927688d00ffd 100644
--- a/drivers/net/ethernet/synopsys/dwc-xlgmac-hw.c
+++ b/drivers/net/ethernet/synopsys/dwc-xlgmac-hw.c
@@ -2326,7 +2326,7 @@ static int xlgmac_write_rss_reg(struct xlgmac_pdata *pdata, unsigned int type,

 static int xlgmac_write_rss_hash_key(struct xlgmac_pdata *pdata)
 {
-       unsigned int key_regs = sizeof(pdata->rss_key) / sizeof(u32);
+       unsigned int key_regs = ARRAY_SIZE_OF(pdata->rss_key, u32);
        unsigned int *key = (unsigned int *)&pdata->rss_key;
        int ret;

diff --git a/include/linux/kernel.h b/include/linux/kernel.h
index 4fa360a13c1e..4081428981f4 100644
--- a/include/linux/kernel.h
+++ b/include/linux/kernel.h
@@ -46,6 +46,15 @@
  */
 #define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]) + __must_be_array(arr))

+/**
+ * ARRAY_SIZE_OF - get the number of elements of a different type in array @arr
+ * @arr: array to be sized
+ *
+ * Use this macro to silence compiler warnings in expressions
+ * like sizeof(X[])/sizeof(Y), where sizeof(Y) != sizeof(X[0])
+ */
+#define ARRAY_SIZE_OF(arr, kind) (sizeof(arr) / (sizeof(kind)) + __must_be_array(arr))
+
 #define u64_to_user_ptr(x) (           \
 {                                      \
        typecheck(u64, (x));            \
diff --git a/mm/hugetlb.c b/mm/hugetlb.c
index 6d7296dd11b8..30a8f369d192 100644
--- a/mm/hugetlb.c
+++ b/mm/hugetlb.c
@@ -3983,7 +3983,7 @@ u32 hugetlb_fault_mutex_hash(struct hstate *h, struct address_space *mapping,
        key[0] = (unsigned long) mapping;
        key[1] = idx;

-       hash = jhash2((u32 *)&key, sizeof(key)/sizeof(u32), 0);
+       hash = jhash2((u32 *)&key, ARRAY_SIZE_OF(key, u32), 0);

        return hash & (num_fault_mutexes - 1);
 }
```

**Comment by davidbolvansky** [comment]
Good solution. We only need a good name for this macro. My ideas:

ARRAY_SIZE_ELEM_TYPE
ARRAY_SIZE_FOR_TYPE

**Comment by nickdesaulniers** [comment]
So in the `xgbe-dev.c` case they're declaring a `u8[]` but then seeing how many `u32`'s would fit?  Makes me wonder if these should just be declared as `u32[]`?

**Comment by nathanchance** [comment]
@ihalip your solution looks way better!

@nickdesaulniers it might be worth getting clarification from the maintainers on why this is happening since there are no comments and git history is not helpful at all.

**Comment by nickdesaulniers** [comment]
I would investigate each case more before creating `ARRAY_SIZE_OF` to ensure there were no mistakes done during development.  Otherwise `ARRAY_SIZE_OF` may be covering up actual mistakes.

**Comment by nathanchance** [comment]
Inquiries sent to the maintainers:

https://lore.kernel.org/netdev/20190917073232.GA14291@archlinux-threadripper/

https://lore.kernel.org/linux-mm/20190917073444.GA14505@archlinux-threadripper/

**Comment by nathanchance** [comment]
From the comments of the maintainers, it seems like these warnings should be silenced.

The maintainer of `hugetlb.c` already silenced his: https://lore.kernel.org/lkml/20190919011847.18400-1-mike.kravetz@oracle.com/

**Comment by nathanchance** [comment]
Jose Abreu's patch to fix the warning in the stmmac driver was accepted: https://git.kernel.org/netdev/net/c/3c72d4d33059cf84a23492e827731f12c023ab00

The last two warnings that I see across a couple of `allyesconfig` builds:

```
../drivers/net/ethernet/amd/xgbe/xgbe-dev.c:361:49: warning: expression does not compute the number of elements in this array; element type is 'u8' (aka 'unsigned char'), not 'u32' (aka 'unsigned int') [-Wsizeof-array-div]
        unsigned int key_regs = sizeof(pdata->rss_key) / sizeof(u32);
                                       ~~~~~~~~~~~~~~  ^
../drivers/net/ethernet/amd/xgbe/xgbe-dev.c:361:49: note: place parentheses around the 'sizeof(u32)' expression to silence this warning
1 warning generated.
../drivers/net/ethernet/synopsys/dwc-xlgmac-hw.c:2329:49: warning: expression does not compute the number of elements in this array; element type is 'u8' (aka 'unsigned char'), not 'u32' (aka 'unsigned int') [-Wsizeof-array-div]
        unsigned int key_regs = sizeof(pdata->rss_key) / sizeof(u32);
                                       ~~~~~~~~~~~~~~  ^
../drivers/net/ethernet/synopsys/dwc-xlgmac-hw.c:2329:49: note: place parentheses around the 'sizeof(u32)' expression to silence this warning
1 warning generated.
```

I don't really understand where we landed on discussions but I guess they should just be silenced? I still don't entirely understand why the code is structured the way that it is so I am not sure I feel comfortable drafting patches to silence warnings that I don't understand.

**Comment by davidbolvansky** [comment]
Yeah, silence with extra parens.

**Comment by gwelymernans** [comment]
Any update on the maintainer's patch?

**Comment by nathanchance** [comment]
The `hugetlb.c` patch is in `-next`. The other two ethernet warnings have not been dealt with. I have gathered from the discussions they should be silenced I guess but I don’t think there was ever a conclusion.

**Comment by nathanchance** [comment]
The last two warnings have been silenced within clang: https://github.com/llvm/llvm-project/commit/67f542aba72f552c4833bb253761dbcc54071016

I am closing this because there are no more warnings in the tree. If anymore crop up, we can deal with them under new issues.

**Comment by nickdesaulniers** [comment]
> The hugetlb.c patch is in -next.

Could use a backport through to 4.19.
