### ISSUE TITLE
-Wignored-attributes in arch/powerpc/platforms/maple/setup.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#662]
When building ppc64_defconfig:

```
arch/powerpc/platforms/maple/setup.c:368:1: warning: attribute declaration must precede definition [-Wignored-attributes]
machine_device_initcall(maple, maple_cpc925_edac_setup);
^
arch/powerpc/include/asm/machdep.h:297:43: note: expanded from macro 'machine_device_initcall'
#define machine_device_initcall(mach, fn)       __define_machine_initcall(mach, fn, 6)
                                                ^
arch/powerpc/include/asm/machdep.h:280:7: note: expanded from macro '__define_machine_initcall'
                if (machine_is(mach)) return fn(); \
                    ^
arch/powerpc/include/asm/machdep.h:251:19: note: expanded from macro 'machine_is'
                        __attribute__((weak));           \
                                       ^
arch/powerpc/platforms/maple/setup.c:297:1: note: previous definition is here
define_machine(maple) {
^
arch/powerpc/include/asm/machdep.h:246:23: note: expanded from macro 'define_machine'
        struct machdep_calls mach_##name __machine_desc =
                             ^
<scratch space>:175:1: note: expanded from here
mach_maple
^
1 warning generated.
```

**Comment by ihalip** [comment]
This looks like an easy one. clang complains that a symbol definition is then followed by a declaration. More specifically, after some macro expansions, `machine_device_initcall` declares a symbol, but it is already defined by `define_machine`, which is used in the same file. The fix seems very straightforward: move `define_macine` at the end of the file.

**Comment by nathanchance** [comment]
I am fairly certain that is the conclusion that I came to as well when I initially looked into this; every other file has it that way, which is why this warning only occurs in this one file. I assume you want to send a patch since you assigned this?

**Comment by nathanchance** [comment]
Patch submitted: https://lore.kernel.org/lkml/20200323222729.15365-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?id=af6cf95c4d003fccd6c2ecc99a598fb854b537e7

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/af6cf95c4d003fccd6c2ecc99a598fb854b537e7
