### ISSUE TITLE
-Wunused-function in arch/powerpc/boot/inffast.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#664]
When building ppc64_defconfig:

```
arch/powerpc/boot/inffast.c:31:1: warning: unused function 'get_unaligned16' [-Wunused-function]
get_unaligned16(const unsigned short *p)
^
1 warning generated.
```

The file location is misleading, it really comes from `lib/zlib_inflate/inffast.c` it seems...

**Comment by tinti** [comment]
This is still happening at: https://github.com/ClangBuiltLinux/continuous-integration2/runs/1759040908?check_suite_focus=true

I think this would fix it: https://lore.kernel.org/r/20201124104030.903-1-lukas.bulwahn@gmail.com/

**Comment by nickdesaulniers** [comment]
cc @bulwahn to follow up on the requested v2

**Comment by nickdesaulniers** [comment]
This is still visible with `ARCH=powerpc CROSS_COMPILE=powerpc64le-linux-gnu- make CC=clang -j71 defconfig`. Clearing assignee for now.

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/linus/b7cd9fa5ccc392d9f2269edc4cb82508632c28da
