### ISSUE TITLE
llvm-objdump issues with ppc64_defconfig

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#666]
When using `OBJDUMP=llvm-objdump`, there are issues with two scripts used to check `vmlinux` for relocation issues at the end of the build:

```
  SORTEX  vmlinux
  SYSMAP  System.map
  CHKHEAD vmlinux
  CHKREL  vmlinux
llvm-objdump: error: 'vmlinux': not a dynamic object
llvm-objdump: error: 'vmlinux': not a dynamic object
llvm-objdump: for the   --stop-address option: '0x' value invalid for ulong argument!
```

This corresponds to the [`relocs_check.sh`](https://github.com/torvalds/linux/blob/574cc4539762561d96b456dbc0544d8898bd4c6e/arch/powerpc/tools/relocs_check.sh) and [`unrel_branch_check.sh`](https://github.com/torvalds/linux/blob/574cc4539762561d96b456dbc0544d8898bd4c6e/arch/powerpc/tools/unrel_branch_check.sh) scripts in `arch/powerpc/tools/`.

This can be reproduced on Linux 5.3 with the following set of commands:

```
# Grab a few needed patches
% for NUM in $(seq 2 4); do curl -LSs https://lore.kernel.org/lkml/20190911182049.77853-${NUM}-natechancellor@gmail.com/raw | git am; done

# Make the config
% make -j$(nproc) -s ARCH=powerpc CC=clang CROSS_COMPILE=powerpc64-linux-gnu- KCFLAGS=-Wno-implicit-fallthrough OBJDUMP=llvm-objdump O=out distclean ppc64_defconfig

# Disable -Werror in arch/powerpc for unrelated reasons
% ./scripts/config --file out/.config --enable PPC_DISABLE_WERROR

# Build the kernel image
% make -j$(nproc) -s ARCH=powerpc CC=clang CROSS_COMPILE=powerpc64-linux-gnu- KCFLAGS=-Wno-implicit-fallthrough OBJDUMP=llvm-objdump O=out vmlinux
```

**Comment by nickdesaulniers** [comment]
cc @rupprecht

**Comment by ihalip** [comment]
There are actually a couple of issues with llvm's objdump.

First, it doesn't seem to allow dumping relocs from executables (only shared objects). https://reviews.llvm.org/D67873 should fix that.

Second, the way `llvm-objdump -R` works doesn't match what binutils does, so `unrel_branch_check.sh` still shows the second issue:
```
llvm-objdump: for the   --stop-address option: '0x' value invalid for ulong argument!
```

**Comment by ihalip** [comment]
binutils' objdump dumps function names in <angular brackets>, llvm's objdump doesn't. grep commands need to be adjusted. Also, binutils' objdump ignores -R when -D is also given, llvm's objdump runs both. WIP patch:
```diff
diff --git a/arch/powerpc/tools/unrel_branch_check.sh b/arch/powerpc/tools/unrel_branch_check.sh
index 1e972df3107e..3026533e06e7 100755
--- a/arch/powerpc/tools/unrel_branch_check.sh
+++ b/arch/powerpc/tools/unrel_branch_check.sh
@@ -20,15 +20,15 @@ vmlinux="$2"
 end_intr=0x$(
 "$objdump" -R "$vmlinux" -d --start-address=0xc000000000000000         \
                 --stop-address=0xc000000000010000 |
-grep '\<__end_interrupts>:' |
+grep -E '\<?__end_interrupts>?:' |
 awk '{print $1}'
 )

 BRANCHES=$(
-"$objdump" -R "$vmlinux" -D --start-address=0xc000000000000000         \
+"$objdump" "$vmlinux" -D --start-address=0xc000000000000000            \
                --stop-address=${end_intr} |
 grep -e "^c[0-9a-f]*:[[:space:]]*\([0-9a-f][0-9a-f][[:space:]]\)\{4\}[[:space:]]*b" |
-grep -v '\<__start_initialization_multiplatform>' |
+grep -v -E '\<?__start_initialization_multiplatform>?' |
 grep -v -e 'b.\?.\?ctr' |
 grep -v -e 'b.\?.\?lr' |
 sed 's/://' |
```

`unrel_branch_check.sh` dumps the branching instructions in the file. For that, it runs `objdump -D`. Trouble here is, binutils' objdump prints function name/offset when it can, but llvm's objdump doesn't. An example: https://gist.github.com/ihalip/1e33a4bb35f285d184edff9bff0dd12d

**Comment by ihalip** [comment]
Right, there's no machine code instruction analyzer for powerpc64 in LLVM.

**Comment by ihalip** [comment]
Hacked together in a couple of hours to also include the address to jump to in disassembly. https://gist.github.com/ihalip/8b68b321fcc59212c9f270eac3f585ad

**Comment by nickdesaulniers** [comment]
[bug number](https://www.youtube.com/watch?v=WxnN05vOuSM)

**Comment by MaskRay** [comment]
llvm-objdump output (`<function>:` instead of `function:`) matches GNU objdump after https://reviews.llvm.org/D75713 (in LLVM 11.0.0)
