### ISSUE TITLE
ld error when using lld on x86_64

### ISSUE THREAD

**Issue by DanySpin97** [ClangBuiltLinux/linux#667]
```
  DESCEND  objtool
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  Building modules, stage 2.
  LD      arch/x86/boot/setup.elf
ld: error: init sections too big!
make[1]: *** [arch/x86/boot/Makefile:105: arch/x86/boot/setup.elf] Error 1
make: *** [arch/x86/Makefile:324: bzImage] Error 2
make: *** Waiting for unfinished jobs....
  MODPOST 152 modules
```

I am compiling on x86_64-pc-linux-musl.

**Comment by nathanchance** [comment]
Hmmm if you are using `ld.lld`, `ld` shouldn't be used... What is your config and what is your compiling command?

**Comment by DanySpin97** [comment]
The distro I use (exherbo) let the user choose what ld and cc point to. I have selected clang for `cc`, `cpp` and `c++`, and lld for `ld`.

```
$  ld --version
LLD 8.0.1 (compatible with GNU linkers)
```

clang and lvm are both version 8.0.1. I have tried both binutils and llvm utils and I have the same output.

I just use `make -j$[JOBS}` to compile. Just switching to bfd resolve the issue. The kernel version is pf-kernel-v3-pf1 ([Link](https://gitlab.com/post-factum/pf-kernel/wikis/README)].

[This discussion](https://lists.llvm.org/pipermail/llvm-dev/2017-January/109300.html) maybe related.

**Comment by nathanchance** [comment]
Are you using your distro's config file or something else? Can you either link it or upload it so I make sure I am testing the same thing as you are?

**Comment by nickdesaulniers** [comment]
cc @MaskRay 

I'd be curious to know more about the config as well.  Maybe LLD has or had section size restrictions, and having too many TU's putting code in `.init` trips the size restriction?

@DanySpin97 if you build lld from source top of tree, can you still repro with that?

**Comment by MaskRay** [comment]
Neither LLD nor GNU ld has the diagnostic. The diagnostic came from https://elixir.bootlin.com/linux/latest/source/arch/x86/boot/setup.ld

```ldscript
	. = ASSERT(__end_init <= 5*512, "init sections too big!");
```

I think this is just some compatibility issue fixed in the 9.0.0 release of LLD.

```
$  ld --version
LLD 8.0.1 (compatible with GNU linkers)
```

http://releases.llvm.org/9.0.0/tools/lld/docs/ReleaseNotes.html says "Linker script compatibility with GNU ld has generally improved."

Can you try the 9.0.0 release? http://releases.llvm.org/download.html#9.0.0

```zsh
# Download "LLVM source code" and rename the extracted directory to llvm
# Download "LLD source code" and rename the extracted directory to llvm/projects/lld
cd llvm
cmake -H. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release # -DLLVM_TARGETS_TO_BUILD=X86
ninja -C Release lld
# built Release/bin/lld and Release/bin/ld.lld
# create a symlink "ld" in some PATH directory and point it to Release/bin/lld
# make sure your cc links with "ld" by default (readelf -p.comment $exe to verify)
```

https://github.com/ClangBuiltLinux/tc-build can be used to build a top-of-tree toolchain.

**Comment by nathanchance** [comment]
> https://github.com/ClangBuiltLinux/tc-build can be used to build a top-of-tree toolchain.

It can also be used for older versions through the `--branch` parameter :) I've used it for 7.1.0, 8.0.1, and 9.0.0.

**Comment by DanySpin97** [comment]
Sorry for the delay but I've had some problems updating clang to release 9.0.0. I've fixed those and I've been able to successfullly build the kernel using clang and lld 9.0.0. Thanks for your help, updating did the trick!
