### ISSUE TITLE
LLVM/Clang/LLD/etc. release version 9.0.0

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/linux#668]
My personal Thank-You to all involved people from ClangBuiltLinux for contributing to the final release of LLVM/Clang/LLD version 9.0.0.

Especially this one (from [0]):

- Support for asm goto, enabling for example the mainline Linux kernel
  for x86_64 to build with Clang

- Sedat -

[0] http://lists.llvm.org/pipermail/llvm-announce/2019-September/000085.html
[1] http://releases.llvm.org/download.html#9.0.0

**Comment by pltrz** [comment]
Seconded! Great work everybody!!!
