### ISSUE TITLE
unsupported arguments '-mpower4' and '-many' to option 'Wa,'

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#672]
I'm trying to compile ppc64/ppc64le kernel using `AS=clang` (integrated-as in being used). The following error messages are produced when compiling scripts/mod/empty.o:
```
clang: error: unsupported argument '-mpower4' to option 'Wa,'
clang: error: unsupported argument '-many' to option 'Wa,'
```
This arguments are added here:
https://github.com/ClangBuiltLinux/linux/blob/45824fc0da6e46cc5d563105e1eaaf3098a686f9/arch/powerpc/Makefile#L255
 The compilation continues without error if the option is removed:
```patch
--- a/arch/powerpc/Makefile
+++ b/arch/powerpc/Makefile
@@ -249,10 +249,6 @@ cpu-as-$(CONFIG_ALTIVEC)	+= $(call as-option,-Wa$(comma)-maltivec)
 cpu-as-$(CONFIG_E200)		+= -Wa,-me200
 cpu-as-$(CONFIG_E500)		+= -Wa,-me500
 
-# When using '-many -mpower4' gas will first try and find a matching power4
-# mnemonic and failing that it will allow any valid mnemonic that GAS knows
-# about. GCC will pass -many to GAS when assembling, clang does not.
-cpu-as-$(CONFIG_PPC_BOOK3S_64)	+= -Wa,-mpower4 -Wa,-many
 cpu-as-$(CONFIG_PPC_E500MC)	+= $(call as-option,-Wa$(comma)-me500mc)
 
 KBUILD_AFLAGS += $(cpu-as-y)
```

**Comment by ihalip** [comment]
You probably need one of the ppc64 patches. Maybe [this one](https://github.com/ClangBuiltLinux/continuous-integration/blob/master/patches/llvm-all/linux/ppc64/0001-powerpc-Don-t-add-mabi-flags-when-building-with-Clan.patch)?

**Comment by tpimh** [comment]
I actually had it applied for ppc64 and still hit this bug. I have reproduced the issue on Travis CI today, [here are the applied patches in travis job](https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/237983327#L664).

**Comment by nickdesaulniers** [comment]
cc @gwelymernans Did you hit this? (960e30029863db95ec79a71009272d4661db5991 looks related)

**Comment by gwelymernans** [comment]
I haven't yet. That may not be in our tree.

**Comment by nickdesaulniers** [comment]
```diff
diff --git a/arch/powerpc/Makefile b/arch/powerpc/Makefile
index 5f8544cf724a..8c56c58a08fe 100644
--- a/arch/powerpc/Makefile
+++ b/arch/powerpc/Makefile
@@ -252,7 +252,9 @@ cpu-as-$(CONFIG_E500)               += -Wa,-me500
 # When using '-many -mpower4' gas will first try and find a matching power4
 # mnemonic and failing that it will allow any valid mnemonic that GAS knows
 # about. GCC will pass -many to GAS when assembling, clang does not.
+ifneq ($(LLVM_IAS),1)
 cpu-as-$(CONFIG_PPC_BOOK3S_64) += -Wa,-mpower4 -Wa,-many
+endif
 cpu-as-$(CONFIG_PPC_E500MC)    += $(call as-option,-Wa$(comma)-me500mc)
 
 KBUILD_AFLAGS += $(cpu-as-y)
```
is probably a better patch, though there are many more issues with LLVM_IAS=1 for ppc using [the above commands](https://github.com/ClangBuiltLinux/linux/issues/672#issuecomment-747708570). Though it's not clear to me yet if clang _should_ accept -Wa,-mpower4.

**Comment by nickdesaulniers** [comment]
@aik sent [this patch](https://lore.kernel.org/llvm/20211221055904.555763-3-aik@ozlabs.ru/) from @daxtens 

@mpe [accepted it into powerpc/next](https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?h=next&id=f5140cab448e4819ca6f158cb4130352f73c92e4)

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/f5140cab448e4819ca6f158cb4130352f73c92e4
