### ISSUE TITLE
-Wunused-label in drivers/media/dvb-frontends/tas2101.c

### ISSUE THREAD

**Issue by tpgxyz** [ClangBuiltLinux/linux#680]
Trying to build kernel 5.3.1 with LLVM/clang-9.0.0 on x86_64

```
  CC [M]  drivers/media/dvb-frontends/tas2101.o
BUILDSTDERR: drivers/media/dvb-frontends/tas2101.c:641:1: warning: unused label 'err1' [-Wunused-label]
BUILDSTDERR: err1:
BUILDSTDERR: ^~~~~
BUILDSTDERR: 1 warning generated.
```

**Comment by nathanchance** [comment]
This file doesn't exist in the mainline kernel?

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/drivers/media/dvb-frontends/tas2101.c?h=linux-5.3.y

Are you building a distro kernel?

**Comment by tpgxyz** [comment]
@nathanchance Yes, that is out of kernel tree SAA716x DVB driver which comes from git@github.com:crazycat69/linux_media

**Comment by nathanchance** [comment]
http://github.com/crazycat69/linux_media goes nowhere for me, unless it is a private repo. In which case, these warnings should probably be reported there since they can only be fixed by that person, not by us. We focus primarily on mainline.

**Comment by tpgxyz** [comment]
It seems a little bit abandoned DVB driver. I'm closing it.
