### ISSUE TITLE
-Wint-in-bool-context in net/ipv4/fib_trie.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#685]
linux-next x86 defconfig
```
net/ipv4/fib_trie.c:1110:33: warning: converting the result of '<<' to a boolean; did you mean '(key << plen) != 0'? [-Wint-in-bool-context]
        if ((plen < KEYLENGTH) && (key << plen)) {
                                       ^
```

**Comment by nathanchance** [comment]
```
% echo | clang -Wunknown-warning-option -Wint-in-bool-context -x c -c -o /dev/null -
warning: unknown warning option '-Wint-in-bool-context'; did you mean '-Wgnu-include-next'? [-Wunknown-warning-option]
1 warning generated.
```

🤔

**Comment by nickdesaulniers** [comment]
rebuild your clang. r372612 was submitted today via @davidbolvansky

**Comment by davidbolvansky** [comment]
Surprised a bit, GCC was unable to catch it? -Wint-in-bool-context is originally GCC's warning.

**Comment by nathanchance** [comment]
Sigh... figures this would happen to me eventually :(

Interesting that GCC hasn't caught it until now...

**Comment by davidbolvansky** [comment]
I would suggest to change it to (key << plen) != 0 - the code looks better I think.

**Comment by nickdesaulniers** [comment]
>Interesting that GCC hasn't caught it until now...

Maybe GCC doesn't enable it by default, but Clang does?

**Comment by nathanchance** [comment]
No, it is enabled after commit [`a3bc88645e92`](https://git.kernel.org/linus/a3bc88645e9293f5aaac9c05a185d9f1c0594c6c) ("kbuild: re-enable int-in-bool-context warning").

**Comment by davidbolvansky** [comment]
-Wall - same for both. Interestingly, gcc warns for (1<<key) too. They original idea was a bit different since they suggest ‘<‘, but google results show that the real fix for this warning for != 0 for (almost) all cases.. gcc warns when one side is constant? maybe..

I could change this warning to be exactly as gcc’s one, not sure yet (I will wait for reports from chromium)

**Comment by nickdesaulniers** [comment]
cc @arndb @masahir0y

**Comment by davidbolvansky** [comment]
This warning will probably go away with https://reviews.llvm.org/rL372708

**Comment by nathanchance** [comment]
Fixed after https://reviews.llvm.org/rL372708.
