### ISSUE TITLE
OpenMandriva managed to build kernel with LLVM/clang

### ISSUE THREAD

**Issue by tpgxyz** [ClangBuiltLinux/linux#690]
Hi,

it took a lot of time and finally it is there, a kernel compiled with LLVM/clang-9.0.0
**x86_64** build: https://abf.openmandriva.org/build_lists/610456
**znver1** build: https://abf.openmandriva.org/build_lists/610531
**armv7hnl** build: https://abf.openmandriva.org/build_lists/611357
**i686** build: https://abf.openmandriva.org/build_lists/612950
**aarch64** build: waiting for bug fixes
**risvc64** build: waiting for OpenMandriva bug fixes

Many thanks to you all who worked with upstream to add all the needed features and fixed all the compilation bugs!

https://openmandriva.org

**Comment by javashin** [comment]
thinlto ?

**Comment by tpgxyz** [comment]
@javashin nope, as LTO support is on another project https://github.com/andikleen/linux-misc

**Comment by nathanchance** [comment]
I believe that LTO implementation is for GCC. @samitolvanen has made one for Clang to take advantage of CFI: https://github.com/samitolvanen/linux/commits/clang-lto

**Comment by tpgxyz** [comment]
Phoronix article https://www.phoronix.com/scan.php?page=news_item&px=OpenMandriva-Clang-Kernel

OpenMandriva source for kernel compiled with LLVM/clang https://abf.openmandriva.org/openmandriva/kernel-release-clang

**Comment by nickdesaulniers** [comment]
> OpenMandriva source for kernel compiled with LLVM/clang https://abf.openmandriva.org/openmandriva/kernel-release-clang

HTTP 404

**Comment by mati865** [comment]
> HTTP 404

Use this one https://abf.openmandriva.org/openmandriva/kernel-release-clang/build_lists

**Comment by tpgxyz** [comment]
@nickdesaulniers I've fixed URL, sorry for the inconvenience
