### ISSUE TITLE
undefined reference to `mcount' in kernel/softirq.c

### ISSUE THREAD

**Issue by tpgxyz** [ClangBuiltLinux/linux#696]
Trying to compile kernel 5.3.1 with LLVM/clang on armv7hnl

Full log is here https://abf.openmandriva.org/build_lists/610529 also links to GitHub sources.

``  MODINFO modules.builtin.modinfo
BUILDSTDERR: ld.bfd: kernel/softirq.o: in function `__local_bh_disable_ip':
BUILDSTDERR: softirq.c:(.text+0x39e): undefined reference to `mcount'
BUILDSTDERR: ld.bfd: kernel/softirq.o: in function `_local_bh_enable':
BUILDSTDERR: softirq.c:(.text+0x3fe): undefined reference to `mcount'
BUILDSTDERR: ld.bfd: kernel/softirq.o: in function `__local_bh_enable_ip':
BUILDSTDERR: softirq.c:(.text+0x458): undefined reference to `mcount'
BUILDSTDERR: ld.bfd: kernel/softirq.o: in function `do_softirq':
BUILDSTDERR: softirq.c:(.text+0x4ec): undefined reference to `mcount'
BUILDSTDERR: ld.bfd: kernel/softirq.o: in function `irq_enter':
BUILDSTDERR: softirq.c:(.text+0x56a): undefined reference to `mcount'
BUILDSTDERR: ld.bfd: kernel/softirq.o:softirq.c:(.text+0x666): more undefined references to `mcount' follow
BUILDSTDERR: make: *** [Makefile:1071: vmlinux] Error 1
BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.j4M3Dp (%build)
``

**Comment by nathanchance** [comment]
Can you see if https://git.kernel.org/linus/b0fe66cf095016e0b238374c10ae366e1f087d11 fixes this for you?

If so, I will send it as a backport for 4.19, 5.2, and 5.3.

**Comment by tpgxyz** [comment]
@nathanchance sure will do if not today, then tommorow

**Comment by nickdesaulniers** [comment]
dup of #35 (#35 just needs backports)

**Comment by tpgxyz** [comment]
@nathanchance @nickdesaulniers guys I've applied that patch, but no success https://abf.openmandriva.org/build_lists/610696

**Comment by nathanchance** [comment]
The compiler needs to be added to the configuration step:

```
make ARCH=arm defconfig common.config common-server.config arm-common.config
```

to

```
make ARCH=arm CC=clang defconfig common.config common-server.config arm-common.config
```

That should prevent `CONFIG_FUNCTION_TRACER` from being enabled.

**Comment by tpgxyz** [comment]
@nathanchance thanks for the hint, I've restarted build.

**Comment by tpgxyz** [comment]
Build just failed with same error 

https://abf.openmandriva.org/build_lists/610797

**Comment by nathanchance** [comment]
```
Value of CONFIG_FUNCTION_TRACER is redefined by fragment ./kernel/configs/common.config:
Previous value: # CONFIG_FUNCTION_TRACER is not set
New value: CONFIG_FUNCTION_TRACER=y
```

Hmmm, I guess that might be a bug in whatever tool does the config merge... I will try to look at this later tonight but you should keep `CONFIG_FUNCTION_TRACER` disabled for arm32 on clang 9.0.0.

**Comment by tpgxyz** [comment]
@nathanchance I've corected configs for arm32 https://github.com/OpenMandrivaAssociation/kernel-release/commit/60e3d4b5950571f6a86b9198635db412cd26fd8a

still same error https://abf.openmandriva.org/build_lists/610826

**Comment by tpgxyz** [comment]
Looks good, armv7hnl build is done https://abf.openmandriva.org/build_lists/611357. Thanks.

**Comment by nathanchance** [comment]
@tpgxyz I just got a chance to fully look at this. You picked an older version of my commit, which is why you got that error :( https://github.com/OpenMandrivaAssociation/kernel-release/commit/74561564163f112a3bb06dcdf473b068799efea4

1. Remove that patch.
2. Properly pick [the mainline commit](https://git.kernel.org/linus/b0fe66cf095016e0b238374c10ae366e1f087d11).
3. Don't modify the `100000` like you did [here](https://github.com/OpenMandrivaAssociation/kernel-release/commit/d9b099ccc57f9f95ec0d875604a7bfd44fe60268).

That should all work properly. If it does, I will send backports for my commit so that everything will work with a future version of 5.3 and you won't need to carry it out of tree for very long.
