### ISSUE TITLE
-Wunknown-pragmas in arch/arm/lib/xor-neon.c

### ISSUE THREAD

**Issue by tpgxyz** [ClangBuiltLinux/linux#700]
Trying to compile kernel 5.3.1 with LLVM/clang on armv7hnl

Full log is here https://abf.openmandriva.org/build_lists/610529 also links to GitHub sources.
```

  CC      arch/arm/lib/xor-neon.o
BUILDSTDERR: arch/arm/lib/xor-neon.c:23:13: warning: unknown pragma ignored [-Wunknown-pragmas]
BUILDSTDERR: #pragma GCC optimize "tree-vectorize"
BUILDSTDERR:             ^
BUILDSTDERR: 1 warning generated.
  CC      arch/arm/mach-omap2/cm3xxx.
```

**Comment by nathanchance** [comment]
I think this is a duplicate of #496 (I assume you have applied a patch to get this warning to avoid that one). Apply my patch from lore.kernel.org linked in that issue and you should see no warnings.

**Comment by davidbolvansky** [comment]
Maybe sou should add #pragma clang vectorize(enable)?

While clang with -O2 enables vectorizer, but compiler may decide to not vectorize it.

If kernel people do this for gcc, probably clang should have it too

**Comment by tpgxyz** [comment]
@nathanchance After applying patch you have metnioned, warning does not occur https://lore.kernel.org/lkml/20190528235742.105510-1-natechancellor@gmail.com/

Build logs:
https://abf.openmandriva.org/build_lists/610696

**Comment by nathanchance** [comment]
@davidbolvansky correct me if I am wrong but the pragma only seems to be valid for the loop vectorizer according to [the documentation](https://llvm.org/docs/Vectorizers.html), as your statement gives a warning:

```
../arch/arm/lib/xor-neon.c:23:15: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma clang vectorize(enable)
              ^
1 warning generated.
```

Adding `#pragma clang loop vectorize(enable) interleave(enable)` does appear to eliminate some of the `remark: the cost-model indicates that interleaving is not beneficial` comments from `-S -Rpass-missed=.*` but the code as a whole does not appear to get vectorized.

**Comment by davidbolvansky** [comment]
Is this xor_8regs_2?

I tried with x86-64

 #pragma clang loop vectorize(enable)
 do {
  p1[0] ^= p2[0];
  p1[1] ^= p2[1];

git/arm-soc/include/asm-generic/xor.h:19:1: remark: vectorized loop (vectorization width: 2, interleaved count: 1) [-Rpass=loop-vectorize]

xor_8regs_2(unsigned long bytes, unsigned long  *p1, unsigned long * p2)


The loop is now vectorized with runtime alias check. (if you add "restrict", runtime check is gone)

**Comment by nickdesaulniers** [comment]
> I tried with x86-64

IIRC, it was arm32 not vectorizing: https://llvm.org/pr40976

**Comment by davidbolvansky** [comment]
Ah..

Anyway, Arnd Bergmann has a solution:

https://llvm.org/pr40976

original warning can be fixed by ifdefing for gcc only.
