### ISSUE TITLE
invalid escape sequence in arch/arm64/kernel/head.S

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#713]
```
arch/arm64/kernel/head.S:84:9: error: invalid escape sequence (unrecognized character) in '.ascii' directive
 .ascii "ARM\x64"
        ^
```

**Comment by nickdesaulniers** [comment]
I suspect that Clang's integrated assembler doesn't understand `\x` for hexadecimal escape codes. cc @jcai19

**Comment by nickdesaulniers** [comment]
upstream bug: https://llvm.org/pr43567

**Comment by nickdesaulniers** [comment]
patch: https://reviews.llvm.org/D68483

**Comment by jcai19** [comment]
D68483 relanded as https://reviews.llvm.org/D68598

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/rL374018
https://reviews.llvm.org/rL374124
