### ISSUE TITLE
LLD hangs with CONFIG_CFI_CLANG after r372893

### ISSUE THREAD

**Issue by samitolvanen** [ClangBuiltLinux/linux#714]
LLVM r372893 breaks kernel CFI. LLD appears to hang when linking vmlinux.o. Reproducible with both full LTO and ThinLTO.

**Comment by samitolvanen** [comment]
Submitted: https://llvm.org/pr43455

**Comment by nathanchance** [comment]
For me, it took 2 hours to fully link... I am trying to figure out if there is a single translation unit at fault.

**Comment by nathanchance** [comment]
Reverted in [r373060](https://github.com/llvm/llvm-project/commit/3740ae3b8aeeb498243504148f666204f9856302) and the LLVM bug was closed as well.
