### ISSUE TITLE
-Winitializer-overrides in tools/power/cpupower/utils/idle_monitor/hsw_ext_idle.c

### ISSUE THREAD

**Issue by tpgxyz** [ClangBuiltLinux/linux#718]
Trying to compile kernel 5.3.1 with LLVM/clang-9.0.0 on armv7hnl

Full logs can be found here https://abf.openmandriva.org/build_lists/611355 also links to GitHub sources
```

 CC       utils/idle_monitor/hsw_ext_idle.o
BUILDSTDERR: utils/idle_monitor/hsw_ext_idle.c:42:16: warning: initializer overrides prior initialization of this subobject [-Winitializer-overrides]
BUILDSTDERR:                 .desc                   = N_("Processor Package C2"),
BUILDSTDERR:                                              ^~~~~~~~~~~~~~~~~~~~~~
BUILDSTDERR: ./utils/helpers/helpers.h:25:33: note: expanded from macro 'N_'
BUILDSTDERR: #define N_(String) gettext_noop(String)
BUILDSTDERR:                                 ^~~~~~
BUILDSTDERR: ./utils/helpers/helpers.h:23:30: note: expanded from macro 'gettext_noop'
BUILDSTDERR: #define gettext_noop(String) String
BUILDSTDERR:                              ^~~~~~
BUILDSTDERR: utils/idle_monitor/hsw_ext_idle.c:41:16: note: previous initialization is here
BUILDSTDERR:                 .desc                   = N_("Processor Package C9"),
BUILDSTDERR:                                              ^~~~~~~~~~~~~~~~~~~~~~
BUILDSTDERR: ./utils/helpers/helpers.h:25:33: note: expanded from macro 'N_'
BUILDSTDERR: #define N_(String) gettext_noop(String)
BUILDSTDERR:                                 ^~~~~~
BUILDSTDERR: ./utils/helpers/helpers.h:23:30: note: expanded from macro 'gettext_noop'
BUILDSTDERR: #define gettext_noop(String) String
BUILDSTDERR:                              ^~~~~~
BUILDSTDERR: 1 warning generated.
```

**Comment by nathanchance** [comment]
This comes from `tools/power/cpupower/utils/idle_monitor/hsw_ext_idle.c` by the way and can be reproduced by `make -j$(nproc) -C tools/power/cpupower CC=clang all`.

Patch sent: https://lore.kernel.org/lkml/20190927162642.2292584-1-natechancellor@gmail.com/

@tpgxyz In the future, would you like an explicit `Reported-by:` tag in the commit message? I will always include a link to the original issue so you get credit that way but I am happy to add it to the commit message as well. If so, let me know what email you would like it under.

**Comment by tpgxyz** [comment]
@nathanchance hi, if you like please use my email tpgxyz at gmail dot com

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/shuah/linux/c/7e5705c635ecfccde559ebbbe1eaf05b5cc60529

I probably should have marked it as cc stable but Sasha's AUTOSEL process has been picking up most of my warning fixes so I expect this to be no different.

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/7e5705c635ecfccde559ebbbe1eaf05b5cc60529
