### ISSUE TITLE
-Wimplicit-fallthrough in drivers/video/fbdev/sh_mobile_lcdcfb.c

### ISSUE THREAD

**Issue by tpgxyz** [ClangBuiltLinux/linux#719]
Trying to compile kernel 5.3.1 with LLVM/clang-9.0.0 on armv7hnl

Full logs can be found here https://abf.openmandriva.org/build_lists/611355 also links to GitHub sources

Same warnings are for 
drivers/usb/phy/phy-ab8500-usb.c
drivers/video/fbdev/vt8500lcdfb.c: In function 'vt8500lcd_blank'
drivers/usb/host/ohci-tmio.c
drivers/usb/gadget/udc/atmel_usba_udc.c
drivers/gpu/drm/sti/sti_hdmi.c
drivers/pinctrl/pinctrl-rockchip.c
drivers/media/pci/saa716x/saa716x_ff_main.c
drivers/pinctrl/qcom/pinctrl-spmi-gpio.c
drivers/mmc/host/atmel-mci.c
drivers/mmc/host/sdhci-s3c.c
drivers/gpu/drm/arm/malidp_hw.c
drivers/dma/imx-dma.c
drivers/hsi/clients/ssi_protocol.c
drivers/cpufreq/ti-cpufreq.c

```

  CC [M]  drivers/video/fbdev/sh_mobile_lcdcfb.o
BUILDSTDERR: drivers/video/fbdev/sh_mobile_lcdcfb.c: In function 'sh_mobile_lcdc_channel_fb_init':
BUILDSTDERR: drivers/video/fbdev/sh_mobile_lcdcfb.c:2086:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
BUILDSTDERR:  2086 |   info->fix.ypanstep = 2;
BUILDSTDERR:       |   ~~~~~~~~~~~~~~~~~~~^~~
BUILDSTDERR: drivers/video/fbdev/sh_mobile_lcdcfb.c:2087:2: note: here
BUILDSTDERR:  2087 |  case V4L2_PIX_FMT_NV16:
BUILDSTDERR:       |  ^~~~
BUILDSTDERR: drivers/video/fbdev/sh_mobile_lcdcfb.c: In function 'sh_mobile_lcdc_overlay_fb_init':
BUILDSTDERR: drivers/video/fbdev/sh_mobile_lcdcfb.c:1596:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
BUILDSTDERR:  1596 |   info->fix.ypanstep = 2;
BUILDSTDERR:       |   ~~~~~~~~~~~~~~~~~~~^~~
BUILDSTDERR: drivers/video/fbdev/sh_mobile_lcdcfb.c:1597:2: note: here
BUILDSTDERR:  1597 |  case V4L2_PIX_FMT_NV16:
BUILDSTDERR:       |  ^~~~
```

**Comment by nathanchance** [comment]
For the record, that looks like GCC's warning. However, please pick https://git.kernel.org/linus/e2079e93f562c7f7a030eb7642017ee5eabaaa10 for now. Sasha's AUTOSEL has [picked it up](https://lore.kernel.org/stable/20190924164144.25591-64-sashal@kernel.org/) for a future 5.3 update so you shouldn't need to carry it for very long.
