### ISSUE TITLE
-Wvla in drivers/media/pci/saa716x/tbsci.c

### ISSUE THREAD

**Issue by tpgxyz** [ClangBuiltLinux/linux#723]
Trying to compile kernel 5.3.1 with LLVM/clang-9.0.0 on armv7hnl

Full logs can be found here https://abf.openmandriva.org/build_lists/611355 also links to GitHub sources

```
  CC [M]  drivers/media/pci/saa716x/tbsci.o
BUILDSTDERR: drivers/media/pci/saa716x/tbsci.c: In function 'tbsci_i2c_write':
BUILDSTDERR: drivers/media/pci/saa716x/tbsci.c:51:2: warning: ISO C90 forbids variable length array 'buf' [-Wvla]
BUILDSTDERR:    51 |  unsigned char buf[len + 1];
BUILDSTDERR:       |  ^~~~~~~~
```

**Comment by nathanchance** [comment]
This driver doesn't exist in mainline so I assume it is another out of tree driver that you guys have picked up.

**Comment by tpgxyz** [comment]
Yes indeed. Closing it.
