### ISSUE TITLE
LD error: init sections too big!

### ISSUE THREAD

**Issue by tpgxyz** [ClangBuiltLinux/linux#729]
Trying to compile kernel 5.3.2 with LLVM/clang 9.0.0 on arch x8_64
On 5.3.1 errors did not occur, and our toolchain was not touched.

Full build logs can be found here https://abf.openmandriva.org/build_lists/612488
Sources can be found here https://github.com/OpenMandrivaAssociation/kernel-release-clang

```

LD      arch/x86/boot/compressed/vmlinux
BUILDSTDERR: ld.lld: warning: multiple common of __force_order
  OBJCOPY arch/x86/boot/vmlinux.bin
  ZOFFSET arch/x86/boot/zoffset.h
  AS      arch/x86/boot/header.o
  LD      arch/x86/boot/setup.elf
BUILDSTDERR: ld.lld: error: init sections too big!
BUILDSTDERR: make[1]: *** [arch/x86/boot/Makefile:105: arch/x86/boot/setup.elf] Error 1
BUILDSTDERR: make: *** [arch/x86/Makefile:317: bzImage] Error 2
BUILDSTDERR: make: **
```

**Comment by nathanchance** [comment]
Unless I am missing something, the build log you have linked to shows the error occurring when building with GCC...

```
/usr/bin/make ... CC=gcc CXX=g++ ...
```

**Comment by tpgxyz** [comment]
sorry my bad, again wrong build
