### ISSUE TITLE
relocation R_ARM_PREL31 out of range

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#732]
Testing our CI locally: https://github.com/ClangBuiltLinux/continuous-integration
```sh
$ ARCH=arm32_v6 REPO=linux-next LD=ld.lld ./driver.sh
...
  LD      .tmp_vmlinux1
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x34AF0): relocation R_ARM_PREL31 out of range: 2136460448 is not in [-1073741824, 1073741823]
```

**Comment by nathanchance** [comment]
I wonder if it is related to https://github.com/ClangBuiltLinux/linux/issues/626? cc @smithp35

**Comment by nathanchance** [comment]
LLVM bug filed: https://llvm.org/pr44824

**Comment by tpimh** [comment]
Oops, sorry for duplicate bug.

**Comment by nathanchance** [comment]
I went to go test the Raspberry Pi kernel with `ld.lld` now that #282 is resolved but it seems that it is now tripping over this:

```
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x36408): relocation R_ARM_PREL31 out of range: 2135585664 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x395CC): relocation R_ARM_PREL31 out of range: 2135638460 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x395DC): relocation R_ARM_PREL31 out of range: 2135638444 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x39674): relocation R_ARM_PREL31 out of range: 2135638292 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x39684): relocation R_ARM_PREL31 out of range: 2135638276 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x3969C): relocation R_ARM_PREL31 out of range: 2135638252 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x396A4): relocation R_ARM_PREL31 out of range: 2135638244 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x396C4): relocation R_ARM_PREL31 out of range: 2135638212 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x396CC): relocation R_ARM_PREL31 out of range: 2135638204 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x396DC): relocation R_ARM_PREL31 out of range: 2135638188 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x396E4): relocation R_ARM_PREL31 out of range: 2135638180 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x396EC): relocation R_ARM_PREL31 out of range: 2135638172 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x39704): relocation R_ARM_PREL31 out of range: 2135638148 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x39714): relocation R_ARM_PREL31 out of range: 2135638132 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x39724): relocation R_ARM_PREL31 out of range: 2135638116 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x3972C): relocation R_ARM_PREL31 out of range: 2135638108 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x3976C): relocation R_ARM_PREL31 out of range: 2135638044 is not in [-1073741824, 1073741823]
ld.lld: error: .tmp_vmlinux1:(.ARM.exidx+0x397FC): relocation R_ARM_PREL31 out of range: 2135637900 is not in [-1073741824, 1073741823]
```

**Comment by smithp35** [comment]
Normally the .ARM.exidx instructions are discarded in the linker script. Does it have a pattern with something like /DISCARD/ (.arm.exidx .arm.exidx.*)?

If you can post a command line to reproduce, sorry I'm way out of practice, that I can build on x86_64 cross compilation then I can see what's wrong. May need to do with over the Easter break if no-one else can get to it first.

**Comment by nathanchance** [comment]
> Normally the .ARM.exidx instructions are discarded in the linker script. Does it have a pattern with something like /DISCARD/ (.arm.exidx .arm.exidx.*)?

It appears that `.ARM.exidx` is kept in `vmlinux` but discarded in `zImage`:

https://elixir.bootlin.com/linux/v5.6.2/source/arch/arm/kernel/vmlinux.lds.h#L89

https://elixir.bootlin.com/linux/v5.6.2/source/arch/arm/boot/compressed/vmlinux.lds.S#L20

> If you can post a command line to reproduce, sorry I'm way out of practice, that I can build on x86_64 cross compilation then I can see what's wrong. May need to do with over the Easter break if no-one else can get to it first.

```
$ make -j$(nproc) -s ARCH=arm CC=clang CROSS_COMPILE=arm-linux-gnueabi- LD=ld.lld O=out/arm32 distclean aspeed_g5_defconfig vmlinux
```

should do it on mainline.

**Comment by smithp35** [comment]
Thanks for the command. 

I have a suspicion something strange is going on, to get a positive offset that large the .ARM.exidx would have to be very low down in the memory map and the rest of the kernel would need to be over 2 Gigabytes away. I guess this is possible if the start address of the kernel is over 0x80000000 and maybe via orphan placement the .ARM.exidx end up close to 0.

**Comment by nathanchance** [comment]
Maybe something to do with `CONFIG_VMSPLIT_2G`?

https://elixir.bootlin.com/linux/v5.6.2/source/arch/arm/Kconfig#L1315

https://elixir.bootlin.com/linux/v5.6.2/source/arch/arm/Kconfig#L1325

**Comment by smithp35** [comment]
It is possible it looks like the linker script extract that selects them is only present with CONFIG_ARM_UNWIND, so it is possible that they are being placed as orphans in an inconvenient place.

#ifdef CONFIG_ARM_UNWIND
	ARM_UNWIND_SECTIONS
#endif

**Comment by smithp35** [comment]
OK, there are a couple of things that are causing it. I need to leave the (virtual) office so I'll try and write this up tomorrow.

There are a couple of problems, the first is an LLD problem. I think it is to do with a selective DISCARD of .ARM.exidx without discarding the InputSections they describe.
/DISCARD/ : { (.ARM.exidx.exit.text) *(.ARM.exidx.extab.exit.text) *(.ARM.exidx.text.exit) *(.ARM.extab.text.exit) *(.exitcall.exit) *(.discard) (*.discard.*) } 
I'll need to reproduce with a smaller example and fix that.

The second is possibly an LLD problem possibly a kernel problem. The .ARM.exidx for the .vectors section is at 0xfff0000 which is too far away from the .ARM.exidx table at 0x8021216c8
The .ARM.exidx for the .vectors section is linker generated as the linker must fill gaps in the .ARM.exidx table to stop an exception matching a later table entry (difficult to explain without going through the .ARM.exidx table construction). I'll need to think about this one. Technically LLD is right, but it may be possible to not generate gap filling .ARM.exidx sections if they are too far away from the .ARM.exidx table.

**Comment by smithp35** [comment]
Spent a bit more time looking at this. Unfortunately this is a bit of a nightmare, I'll comment on the PR as I don't think that there are any clean fixes.
- The /DISCARD/ of a subset of the .ARM.exidx.exit.text is problematic because .ARM.exidx is a custom section so the /DISCARD/ code doesn't see the .ARM.exidx.exit.text. We'll need a way of exposing the /DISCARD/ code to custom container sections like .ARM.exidx to allow selective /DISCARD/. The alternative is to say this is not supported and users of LLD must all or nothing /DISCARD/ .arm.exidx and not subsets of it.

The second problem has exposed a second problem, the sorting of the .ARM.exidx entries so that we can compress adjacent entries is run after Section Sorting but before Address allocation. The Linker script assigns addresses to sections in a non-ascending order which breaks the assumption that section index (output of Sort Output Sections) is sufficient to order the .ARM.exidx table.

These are fixable, but not over an Easter Weekend. May take some time to look at.

**Comment by nickdesaulniers** [comment]
> users of LLD must all or nothing /DISCARD/ .arm.exidx and not subsets of it.

What are the other subsets that the kernel is keeping around? Maybe those are non-intentional?  That would make fixing on the kernel side a bit simpler.

**Comment by smithp35** [comment]
This particular configuration of the kernel is keeping everything but 
*(.ARM.exidx.exit.text) *(.ARM.exidx.extab.exit.text) 
*(.ARM.exidx.text.exit) *(.ARM.extab.text.exit) (.exitcall.exit)
The vast majority of exception tables have been kept. I don't know why .exit.text and .text.exit have been excluded.

LLD like BFD will synthesise a CANT_UNWIND .ARM.exidx sections for InputSections that don't have a .ARM.exidx, it is unclear what should happen if the existing .ARM.exidx table has been discarded. I can see arguments for both sides. One is to trust the user and not regenerate the table (my preferred option), the other is that the user doesn't like the compiler's larger unwind table and would prefer the smaller synthesised .ARM.exidx table.

**Comment by nathanchance** [comment]
https://reviews.llvm.org/D79289
https://reviews.llvm.org/D79687

@smithp35 I can confirm that these allow `aspeed_g5_defconfig` to link with `ld.lld` and passes a boot test with [`boot-utils`](https://github.com/ClangBuiltLinux/boot-utils):

```
$ ~/cbl/git/boot-utils/boot-qemu.sh -a arm32_v6 -k ~/src/linux/out/arm32
/home/nathan/cbl/git/boot-utils/images/arm/rootfs.cpio.zst: 3174400 bytes
+ timeout 3m unbuffer qemu-system-arm -dtb /home/nathan/src/linux/out/arm32/arch/arm/boot/dts/aspeed-bmc-opp-romulus.dtb -machine romulus-bmc -no-reboot -display none -initrd /home/nathan/cbl/git/boot-utils/images/arm/rootfs.cpio -kernel /home/nathan/src/linux/out/arm32/arch/arm/boot/zImage -m 512m -nodefaults -serial mon:stdio
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.7.0-rc5 (nathan@ubuntu-s3-xlarge-x86) (ClangBuiltLinux clang version 11.0.0 (https://github.com/llvm/llvm-project bafc37f6088f4577e02b5183d840376e65f2a21d), LLD 11.0.0 (https://github.com/llvm/llvm-project bafc37f6088f4577e02b5183d840376e65f2a21d)) #1 SMP Sun May 10 21:06:37 MST 2020
...
```

I will try to get my Raspberry Pi into a working state tomorrow and verify it on actual hardware.

Thank you for the work you have put into this, it is much appreciated :)

**Comment by nathanchance** [comment]
https://github.com/llvm/llvm-project/commit/3b1622d63a9c2e0a63a5796f94a7f4218a9a4cad
https://github.com/llvm/llvm-project/commit/48aebfc908ba7b9372aaa478a9c200789491096e
https://github.com/llvm/llvm-project/commit/0ae7990b6071b941995183d872b928bba3a5d3b8

```
pi@raspberrypi:~ $ cat /proc/version
Linux version 4.19.122-v7+ (nathan@ubuntu-s3-xlarge-x86) (ClangBuiltLinux clang version 11.0.0 (https://github.com/llvm/llvm-project bafc37f6088f4577e02b5183d840376e65f2a21d), LLD 11.0.0 (https://github.com/llvm/llvm-project bafc37f6088f4577e02b5183d840376e65f2a21d)) #1 SMP Mon May 11 17:53:12 MST 2020
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.122-v7+ #1 SMP Mon May 11 17:53:12 MST 2020 armv7l GNU/Linux
```

**Comment by nickdesaulniers** [comment]
Thanks @smithp35 for the patches and @nathanchance for verifying!

**Comment by nickdesaulniers** [comment]
Reopening. KernelCI is reporting that this is still broken for Clang-10 (aspeed_g5_defconfig).  Do we want to mark some config as broken unless clang version > 10?

**Comment by nathanchance** [comment]
I don't know what we would disable. It might have been related to `CONFIG_VMSPLIT_2G`  but I never got the chance to confirm it plus I think that disabling the selection of it is just going to result in a silently broken kernel.

**Comment by nickdesaulniers** [comment]
Isn't this related to CONFIG_ARM_UNWIND though?

**Comment by nathanchance** [comment]
```diff
diff --git a/arch/arm/Kconfig.debug b/arch/arm/Kconfig.debug
index 4ff04201a8cc..3daf540fb88d 100644
--- a/arch/arm/Kconfig.debug
+++ b/arch/arm/Kconfig.debug
@@ -66,6 +66,8 @@ config UNWINDER_FRAME_POINTER
 config UNWINDER_ARM
        bool "ARM EABI stack unwinder"
        depends on AEABI && !FUNCTION_GRAPH_TRACER
+       # https://github.com/ClangBuiltLinux/linux/issues/732
+       depends on !LD_IS_LLD || LLD_VERSION >= 110000
        select ARM_UNWIND
        help
          This option enables stack unwinding support in the kernel
```

should fix it.

**Comment by nickdesaulniers** [comment]
@nathanchance can you send the above hunk?

**Comment by nathanchance** [comment]
Done: https://lore.kernel.org/r/20210311005418.2207250-1-nathan@kernel.org/

**Comment by nickdesaulniers** [comment]
@nathanchance I think that can get submitted to RMK's queue?

**Comment by nathanchance** [comment]
Sure, I will submit it today.

**Comment by nathanchance** [comment]
Done: https://www.armlinux.org.uk/developer/patches/viewpatch.php?id=9070/1

**Comment by nathanchance** [comment]
Accepted: http://git.armlinux.org.uk/cgit/linux-arm.git/commit/?id=9e6014c4f5794f03eeb4457dde7122270deb3083

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/linus/7411cfc3c91a08a884463bbc7623087ecc2efdd8
