### ISSUE TITLE
asm-offsets.s built for incorrect architecture

### ISSUE THREAD

**Issue by jcai19** [ClangBuiltLinux/linux#737]
$ ARCH=arm64 CROSS_COMPILER=aarch64-linux-gnu- make CC=clang AS=clang arch/arm64/kernel/asm-offsets.s

In file included from ./arch/arm64/include/asm/thread_info.h:18:
./arch/arm64/include/asm/stack_pointer.h:8:51: error: register 'sp' unsuitable for global register variables on this target
register unsigned long current_stack_pointer asm ("sp");

In file included from ./include/linux/kgdb.h:20:
./arch/arm64/include/asm/kgdb.h:21:25: error: value '1025' out of range for constraint 'I'
        asm ("brk %0" : : "I" (KGDB_COMPILED_DBG_BRK_IMM));
                               ^~~~~~~~~~~~~~~~~~~~~~~~~
./arch/arm64/include/asm/brk-imm.h:24:35: note: expanded from macro 'KGDB_COMPILED_DBG_BRK_IMM'
#define KGDB_COMPILED_DBG_BRK_IMM       0x401

Experimentally added the following to arch/arm64/Makefile fixed it.
 
KBUILD_CFLAGS  += -target aarch64

**Comment by nathanchance** [comment]
If that is the exact command you used, it looks like CROSS_COMPILER should actually be CROSS_COMPILE.

**Comment by jcai19** [comment]
> If that is the exact command you used, it looks like CROSS_COMPILER should actually be CROSS_COMPILE.

You are absolutely right! Thank you for the correction.
