### ISSUE TITLE
Consider enabling -fgnuc-version

### ISSUE THREAD

**Issue by davidbolvansky** [ClangBuiltLinux/linux#738]
Clang claims it is GCC 4.2.1-compatible (__GNUC__ is 4, etc) and this fact can cause some problems (especially missed opportunities for GCC-only "fast paths").

```
#ifdef __GNUC__ > 4
...
#endif
```

Clang recently gained option to override this hardcoded version (hardcoded macros) via -fgnuc-version.

So maybe it is worth to add this to kernel's Makefile?
KBUILD_CFLAGS	+= $(call cc-option,-fgnuc-version=9.2.0,)
(pretend Clang is GCC 9.2-compatible).

I successfully compiled kernel-5.3.6 with -fgnuc-version=9.2.0.

I think it is better to fix some breakages in the future rather than miss some optimization/perf opportunities.

**Comment by nickdesaulniers** [comment]
Yes, I subscribed to rnk's change.

Duping this to https://github.com/ClangBuiltLinux/linux/issues/427, as it will help us for those that remain if relevant.

One thing to be aware of are functional tests that are run as shell scripts.  The recently added `asm inline` is a shell script that *doesn't* check __GNUC__ and friends.
