### ISSUE TITLE
ld.lld: error: undefined symbol: int3_magic

### ISSUE THREAD

**Issue by kees** [ClangBuiltLinux/linux#739]
When building with ThinLTO on x86, I see this build failure. The int3_magic code itself is very odd kind-of-inline asm that gets called through an interrupt callback. I haven't found a way to move the code around to keep LLD happy, though.

My diff to enable ThinLTO on x86:

```
diff --git a/arch/x86/Kconfig b/arch/x86/Kconfig
index 34e59357be23..d866472b9ba1 100644
--- a/arch/x86/Kconfig
+++ b/arch/x86/Kconfig
@@ -91,6 +91,7 @@ config X86
        select ARCH_SUPPORTS_ATOMIC_RMW
        select ARCH_SUPPORTS_NUMA_BALANCING     if X86_64
        select ARCH_SUPPORTS_LTO_CLANG          if X86_64
+       select ARCH_SUPPORTS_THINLTO            if X86_64
        select ARCH_USE_BUILTIN_BSWAP
        select ARCH_USE_QUEUED_RWLOCKS
        select ARCH_USE_QUEUED_SPINLOCKS
```

**Comment by kees** [comment]
Reverting ecc606103837b ("x86/alternatives: Fix int3_emulate_call() selftest stack corruption") gets past the error (though likely makes the test corrupt the stack again, based on the commit log).

Then I get stalled during relocs generation with:
Unsupported relocation type: R_X86_64_8 (14)

**Comment by nickdesaulniers** [comment]
> I see this build failure. 

Can you provide the full error message, if you still have it?

**Comment by kees** [comment]
Full error is:

```
ld.lld: error: undefined symbol: int3_magic
>>> referenced by usercopy_64.c
>>>               vmlinux.o:(int3_magic.cfi_jt)
>>> did you mean: int3_magic
>>> defined in: vmlinux.o
make[1]: *** [vmlinux] Error 1
```
The crazy extern-but-not int3_magic() seems to have seriously confused ThinLTO. :)

**Comment by nickdesaulniers** [comment]
cc @samitolvanen

**Comment by samitolvanen** [comment]
I believe this is only an issue with CFI, which we are currently working around with commit 66bf6eeeba96db5c84abf415fc0f25482a0060dd.

**Comment by nickdesaulniers** [comment]
So ThinLTO is discarding this global asm statement?

**Comment by samitolvanen** [comment]
I suspect this has something to do with `int3_magic` not being marked as global in assembly, but declared as a global in C, which confuses ThinLTO+CFI. We had a similar issue with commit 2194a6b76dc7045fb1fd005aacfa143901393b04.

**Comment by nickdesaulniers** [comment]
Oh, maybe.  Out of line assembly typically uses `SYM_FUNC_START` from include/linux/linkage.h to declare a symbol with global visibility. There are no `*.c` files that use `SYM_FUNC_START`, so it likely is only meant for inclusion in out of line assembly.

Consider this case from arch/x86/kernel/kvm.c:
```c
838 asm(                                                                                                                                                                                                                                                                
839 ".pushsection .text;"                                                                                                                                                                                                                                               
840 ".global __raw_callee_save___kvm_vcpu_is_preempted;"                                                                                                                                                                                                                
841 ".type __raw_callee_save___kvm_vcpu_is_preempted, @function;"                                                                                                                                                                                                       
842 "__raw_callee_save___kvm_vcpu_is_preempted:" 
```
the `.global` is missing from the definition of `int3_magic`.

**Comment by nickdesaulniers** [comment]
See this thread: https://lore.kernel.org/lkml/YH6AaBY5A+x2pmqI@hirez.programming.kicks-ass.net/

Sounds like maintainers are ok making `int3_magic` defined in asm for v2 of x86 CFI support.

**Comment by samitolvanen** [comment]
As `int3_magic()` isn't called from C code, it might be better to just change the C declaration to something like `extern u8 int3_magic[];` and void issues with CFI altogether.

**Comment by kees** [comment]
This is currently worked around, and will be a non-issue once KCFI lands:
https://lore.kernel.org/linux-hardening/20220429203644.2868448-8-samitolvanen@google.com/T/#u
