### ISSUE TITLE
booting x86 with LTO+CFI+KPTI leads to hung init task

### ISSUE THREAD

**Issue by kees** [ClangBuiltLinux/linux#740]
With full LTO and CFI on x86, I can build and boot, but the init process never makes progress. Attempts to debug this so far have failed. The execve() succeeds, but it seems like scheduling never happens. Attempted with x86_64 defconfig (with VIRTIOs enabled).

**Comment by nickdesaulniers** [comment]
Just triple checking that this is FULL LTO, not thin LTO?

**Comment by kees** [comment]
After working around issue #739 and issue #741 I've reproduced this with Thin LTO as well, so this appears to be a kernel vs CFI issue.

**Comment by kees** [comment]
Booting with KPTI disabled (either via config or "nopti") allows userspace to start normally. There appears to be an issue with page visibility during syscall entry.

**Comment by kees** [comment]
The entry stub uses many indirect function calls (include IDT entries), and the jump table isn't mapped. Current workaround is to also map the jump table.

**Comment by kees** [comment]
I'm closing this, since it's been addressed. There is still the matter of address exposures under CFI, which I'm leaving open at https://github.com/KSPP/linux/issues/23
