### ISSUE TITLE
error: expected absolute expression on arm

### ISSUE THREAD

**Issue by jcai19** [ClangBuiltLinux/linux#742]
CC=clang AS=clang
```
arch/arm/mm/proc-v7.S:169:143: error: expected absolute expression
 .pushsection ".alt.smp.init", "a" ; .long 9998b ;9997: orr r1, r1, #((1 << 0) | (1 << 6))|(3 << 3) ; .if . - 9997b == 2 ; nop ; .endif ; .if . - 9997b != 4 ; .error "ALT_UP() content must assemble to exactly 4 bytes"; .endif ; .popsection
```
gnu as does not have this issue.

**Comment by nickdesaulniers** [comment]
I suspect it's the `.if . - 9997b == 2` again.

**Comment by jcai19** [comment]
> .if . - 9997b == 2

Yes you are correct.  I'm not sure if it is caused by the same reason of similar issues for other architecture, so I just created this one to track the issues on 32-bit arm. 

Strange enough, if I simply copy the instructions and make a test case out of it, clang would not have the issue. So right now to reproduce this issue, I will have to run 
$ clang -I./arch/arm/include -I./arch/arm/include/generated  -I./include -I./arch/arm/include/uapi -I./arch/arm/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h  -D__ASSEMBLY__  --target=arm-linux-gnueabihf -D__LINUX_ARM_ARCH__=7 -march=armv7-a -include asm/unified.h  -c -o /tmp/proc-v7.o arch/arm/mm/proc-v7.S

The reason seemed to be that this instruction and label 9997 are assigned to two different fragments, and without layout current integrated assembler cannot calculate their difference. While in the test case somehow they are assigned to the same fragment, so the integrated assembler can simply compare their offset and produce a constant value as the result of the substraction.

**Comment by jcai19** [comment]
Some more observation: I only found one macro (ALT_UP) uses dot symbol in .if directive.

linux $ grep -r   "\.if \.\ "
arch/arm/include/asm/assembler.h:	.if . - 9997b == 2					;\
arch/arm/include/asm/assembler.h:	.if . - 9997b != 4					;\

Turned out both instances are in used in the same macro. 

#ifdef CONFIG_SMP
#define ALT_SMP(instr...)                                       \
9998:   instr
/*
 * Note: if you get assembler errors from ALT_UP() when building with
 * CONFIG_THUMB2_KERNEL, you almost certainly need to use
 * ALT_SMP( W(instr) ... )
 */
#define ALT_UP(instr...)                                        \
        .pushsection ".alt.smp.init", "a"                       ;\
        .long   9998b                                           ;\
9997:   instr                                                   ;\
        .if . - 9997b == 2                                      ;\
                nop                                             ;\
        .endif                                                  ;\
        .if . - 9997b != 4                                      ;\
                .error "ALT_UP() content must assemble to exactly 4 bytes";\
        .endif                                                  ;\
        .popsection
#define ALT_UP_B(label)                                 \
        .equ    up_b_offset, label - 9998b                      ;\
        .pushsection ".alt.smp.init", "a"                       ;\
        .long   9998b                                           ;\
        W(b)    . + up_b_offset                                 ;\
        .popsection
#else
#define ALT_SMP(instr...)
#define ALT_UP(instr...) instr
#define ALT_UP_B(label) b label
#endif

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D69411

**Comment by nickdesaulniers** [comment]
Without support for `adrl` (#430 ) I can't boot test this. I can disable configs for drivers that use `adrl`, but arch/arm/boot/compressed/head.S:1447 uses `adrl`.

**Comment by nickdesaulniers** [comment]
Big thanks @jcai19 . (adrl patches linked in #430 help to test this).
