### ISSUE TITLE
Clang doesn't support -mno-save-restore

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#75]
I just removed `KBUILD_CFLAGS += -mno-save-restore` from `arch/riscv/Makefile` to continue with compilation.

**Comment by lenary** [comment]
Clang HEAD now will not error on `-mno-save-restore` or `-msave-restore`! https://reviews.llvm.org/D63498

However, as the RISC-V LLVM backend does not yet support save/restore via libcalls, you will get a warning to tell you this if you try to use `-msave-restore`.

**Comment by nickdesaulniers** [comment]
@tpimh I think this issue can be closed now?

**Comment by tpimh** [comment]
Technically the error is gone, but if there is still no RISC-V LLVM backend implementation of this feature and a warning is still printed, I would keep it open until it is implemented since it's specific to `[ARCH] risc-v`.

**Comment by lenary** [comment]
You’re passing ‘-mno-save-restore’ which is implemented, in as much as prologues/epilogues in LLVM do not use libcalls. If you were passing ‘-msave-restore’ I would agree it was unimplemented, as this option is the one to request the use of libcalls.

**Comment by tpimh** [comment]
Closing the issue then.
