### ISSUE TITLE
hexagon linux port

### ISSUE THREAD

**Issue by androm3da** [ClangBuiltLinux/linux#751]
@nickdesaulniers we spoke today during the llvm dev roundtable, I'm the (new) hexagon arch maintainer.  We build and run downstream configs on target, and there's no upstream qemu support for hexagon (yet).

If there's a baby step to integrate a configuration here that at least builds our target with clang and lld, that would be great and I'd be happy to investigate regressions.

bcain@quicinc.com

**Comment by nickdesaulniers** [comment]
Great! Welcome @androm3da !

Yeah so the first things for us to do:
1. add an `[ARCH] hexagon` label for this issue tracker for helping track bugs specific to hexagon.
2. in our CI repo, we should add support for checking an env var, `BOOT=0` that skips the boot test when set.  Then we can at least add build tests to our CI.  Once we have QEMU support, then we can remove that env var and do build+boot tests.

**Comment by androm3da** [comment]
> Yeah so the first things for us to do:

"us" isn't explicit enough 😉 so I will assume "us" includes me for now.

AFAICT I cannot apply labels until/unless my account has more privileges in the repo.

Regarding number 2, I browsed through the `driver.sh` and can see how this should be done.

**Comment by nickdesaulniers** [comment]
I'll start filing issues here to track separately, but a quick test of:

```sh
$ ARCH=hexagon CROSS_COMPILE=hexagon-linux-gnu- make CC=clang AS=clang LD=ld.lld AR=llvm-ar -j71
...
/arch/hexagon/include/asm/atomic.h:137:1: warning: Missing parenthesis around predicate register [-Winline-asm]
...
fatal error: error in backend: Invalid register name global variable
```

```

**Comment by nickdesaulniers** [comment]
filed #754 and #755 . We'll need to build first to add to CI.

**Comment by androm3da** [comment]
Thanks, I'll prioritize fixes for these.  I'd forgotten that the assembler got pickier.  It should be an easy fix but I'm a bit new to both the Qualcomm internal review for upstreaming and linux kernel upstreaming processes, so it might take a bit.

The compiler crash could be a quicker fix, I'll work with the compiler team.  With luck we will have downstream compiler patch that just didn't get upstreamed yet.

**Comment by androm3da** [comment]
filed #759 -- it's becoming clear that we've fallen behind on upstreaming critical content for building the kernel.  I'll follow through on it and make sure we've got what we need.

**Comment by nickdesaulniers** [comment]
@androm3da , status?

**Comment by androm3da** [comment]
@nickdesaulniers sorry for going radio silence for a bit there, working on a software release that is consuming much of my attention.

I'm out next week on vacation but I'll pick this up the following week.

In related news -- we have published our initial qemu support here: https://github.com/quic/qemu (linux-user mode only so far).  There's a competing implementation, so we'll need to merge our changes before we jointly upstream it.

**Comment by nickdesaulniers** [comment]
closing this in favor of #759 which is the last blocker IIRC.

**Comment by nickdesaulniers** [comment]
Note also that we added support for s390 without booting it; so resolving upstreaming QEMU patches shouldn't be a blocker.
