### ISSUE TITLE
-Wtautological-constant-compare in drivers/md/dm-raid.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#753]
```
drivers/md/dm-raid.c:619:8: warning: converting the result of '<<' to a boolean always evaluates to true [-Wtautological-constant-compare]
                r = !RAID10_OFFSET;
                     ^
drivers/md/dm-raid.c:517:28: note: expanded from macro 'RAID10_OFFSET'
#define RAID10_OFFSET                   (1 << 16) /* stripes with data copies area adjacent on devices */
                                           ^
1 warning generated.
```

Patch submitted: https://lore.kernel.org/lkml/20191024202803.47613-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
This was apparently picked up...? Never got an email about it and Nick's reviewed-by is missing :/

https://git.kernel.org/next/linux-next/c/35ad035b8398c634d888324a299ec50a84cbc6cc

**Comment by nickdesaulniers** [comment]
YOLO! (I would've gotten away with it too, if it weren't for you god damned kids and your github!)

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/35ad035b8398c634d888324a299ec50a84cbc6cc
