### ISSUE TITLE
ld.lld-10: error: init sections too big!

### ISSUE THREAD

**Issue by ihalip** [ClangBuiltLinux/linux#760]
x86_64 defconfig, CC=gcc, LD=ld.lld-10

```
  LD      arch/x86/boot/setup.elf
ld.lld-10: error: init sections too big!
```

I see this was reported in the past, but the tickets were closed. However, the issue is still present and I'd like to look into it.

**Comment by ihalip** [comment]
This happens because `ld.lld` adds the merged `.eh_frame` section before `__end_init`, whereas `ld.bfd` places it after `.rodata`.

**Comment by nickdesaulniers** [comment]
> I see this was reported in the past, but the tickets were closed.

Which bug? Reopen it if it's solely focused on this issue.

> ld.lld adds the merged .eh_frame section before __end_init

So withing the `.init` section markers? That's odd, but if the linker script doesn't specify precisely where it should go, I suspect the linker is allowed to do so.

cc @MaskRay @smithp35 @rui314 @GeorgiiR 

That patch LGTM, can you please send to LKML?

**Comment by nickdesaulniers** [comment]
Actually, I wonder if `.eh_frame` should be added to the `/DISCARD/` list? Is it being used for anything (I'm not sure what it's typically used for, need to look it up), at boot/setup?

**Comment by ihalip** [comment]
> Which bug? Reopen it if it's solely focused on this issue.

#667 and #729 were closed by the reporters.

> So within the .init section markers? That's odd, but if the linker script doesn't specify precisely where it should go, I suspect the linker is allowed to do so.

Yes, both ld.lld and ld.bfd add input sections to the output file without having them named in the linker script. It's just that, in the case of this script, order matters.

> Actually, I wonder if .eh_frame should be added to the /DISCARD/ list? Is it being used for anything (I'm not sure what it's typically used for, need to look it up), at boot/setup?

Seems it contains unwind information. Compiling with `-fno-asynchronous-unwind-tables` gets rid of this section (though another one, `.debug_frame` seems to be used instead). I don't think it should be discarded.

> That patch LGTM, can you please send to LKML?

Will do.

**Comment by MaskRay** [comment]
How I reproduce at top of the tree?

I have tried the following but it works fine.

```
% make -j20 HOSTCC=~/llvm/Release/bin/clang HOSTLD=~/llvm/Release/bin/ld.lld CC=~/llvm/Release/bin/clang LD=~/llvm/Release/bin/ld.lld O=out.x86_64 defconfig vmlinux
...
% ~/llvm/Release/bin/ld.lld --version
LLD 10.0.0 (git@github.com:llvm/llvm-project.git 45ee0d6de6f82833de1320de35366669b2b1cdf2) (compatible with GNU linkers)
```

Without access to a broken reproduce, I cannot say for sure what happened. ld.lld places R sections before RX sections. Some linker scripts may depend on R sections following RX.

**Comment by nathanchance** [comment]
This issue does not happen with `CC=clang LD=ld.lld`, only `CC=gcc LD=ld.lld`

**Comment by MaskRay** [comment]
> This issue does not happen with `CC=clang LD=ld.lld`, only `CC=gcc LD=ld.lld`

Cannot reproduce with `make -j20 HOSTLD=~/llvm/Release/bin/ld.lld LD=~/llvm/Release/bin/ld.lld O=out.x86_64 defconfig vmlinux`

To confirm that GCC is used:
```
% readelf -p.comment out.x86_64/arch/x86/entry/common.o

String dump of section '.comment':
  [     1]  GCC: (Debian 8.3.0-6) 8.3.0

```

**Comment by nathanchance** [comment]
@MaskRay it appears that building just `vmlinux` does not reproduce this because the error occurs in the x86 boot code; build for `bzImage` and you will see it. I can reproduce it with Ubuntu 18.04's GCC:

```
$ make -j$(nproc) -s LD=${CBL_LLVM}/ld.lld O=out.x86_64 defconfig bzImage
ld.lld: error: init sections too big!
ld.lld: error: init sections too big!
../arch/x86/boot/Makefile:105: recipe for target 'arch/x86/boot/setup.elf' failed
make[3]: *** [arch/x86/boot/setup.elf] Error 1
arch/x86/Makefile:284: recipe for target 'bzImage' failed
make[2]: *** [bzImage] Error 2
/home/nathan/src/linux/Makefile:326: recipe for target '__build_one_by_one' failed
make[1]: *** [__build_one_by_one] Error 2
Makefile:179: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2

$ readelf -p.comment out.x86_64/vmlinux

String dump of section '.comment':
  [     0]  GCC: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
  [    2c]  Linker: LLD 10.0.0 (git://github.com/llvm/llvm-project 622176705550d5af5e2837f4b2188ce9f7590887)

**Comment by MaskRay** [comment]
If .eh_frame is not desired, we probably should add `-fno-asynchronous-unwind-tables`, otherwise we should add `+	.eh_frame	: { *(.eh_frame*) }`.

This is related to the orphan placement rule. An orphan section is a section that is not described by the linker script.

```
# a.s
.section .aa,"ax",@progbits; .byte 0
.section .bb,"a",@progbits; .byte 0
.section .cc,"ax",@progbits; .byte 0
.section .dd,"a",@progbits; .byte 0
.section .ee,"ax",@progbits; .byte 0
.section .ff,"a",@progbits; .byte 0
.section .gg,"ax",@progbits; .byte 0

.section .hh,"ax",@progbits; .byte 0
# a.x
SECTIONS {
  .aa : { *(.aa) }
  .bb : { *(.bb) }
  .cc : { *(.cc) }
  .dd : { *(.dd) }
  .ee : { *(.ee) }
  .ff : { *(.ff) }
  .gg : { *(.gg) }
}
```

ld.bfd seems to place the orphan section .hh after the last AX section (.hh) while lld places .hh after the first AX section. The orphan section placement is not well documented and the rule used by ld.bfd is not very clear. Being more explicit is the way to go.

**Comment by nickdesaulniers** [comment]
Let's be more explicit, ie. @ihalip 's [patch](https://github.com/ClangBuiltLinux/linux/issues/760#issuecomment-548844841). If `.eh_frame` may be discarded, let the x86 maintainers point that out in code review.

**Comment by ihalip** [comment]
Submitted patch v3 that discards the `.eh_frame` sections instead, at Boris' suggestion.

**Comment by dileks** [comment]
Patch v3 <https://lore.kernel.org/patchwork/patch/1158993/>.

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=163159aad74d3763b350861b879b41e8f64121fc

**Comment by ihalip** [comment]
Now in Linus' tree, closing.
