### ISSUE TITLE
operand must be a register in range [r0, r14] or apsr_nzcv in arch/arm/boot/compressed/head.S

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#761]
Build of arm32_v5 kernel with integrated-as enabled failing:
```
arch/arm/boot/compressed/head.S:1276:16: error: operand must be a register in range [r0, r14] or apsr_nzcv
1: mrc p15, 0, r15, c7, c14, 3 @ test,clean,invalidate D cache
               ^
```

**Comment by nathanchance** [comment]
@agners just sent a patch for this yesterday: https://lore.kernel.org/lkml/472f8bd1f000f45343cc0c66a26380fe4b532147.1572644664.git.stefan@agner.ch/

**Comment by tpimh** [comment]
Merged into mainline: https://git.kernel.org/linus/9f1984c6ae30e2a379751339ce3375a21099b5d4
