### ISSUE TITLE
arm build not hermetic `nm`

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#766]
@tpimh points out that the arm32 build [isn't hermetic](https://github.com/ClangBuiltLinux/continuous-integration/issues/73#issuecomment-550053825).

Let's find and fix that.

**Comment by nickdesaulniers** [comment]
Looks like `nm` is hard coded https://github.com/ClangBuiltLinux/linux/blob/master/arch/arm/boot/compressed/Makefile#L124 and https://github.com/ClangBuiltLinux/linux/blob/master/arch/arm/boot/compressed/Makefile#L168.  These should likely be `$(NM)` which is set correctly for cross compiling by [the top level `Makefile`](https://github.com/ClangBuiltLinux/linux/blob/26bc672134241a080a83b2ab9aa8abede8d30e1c/Makefile#L412).

**Comment by nickdesaulniers** [comment]
cc @metti

**Comment by tpimh** [comment]
Thank you for finding where `nm` is used. Just replacing with correct variable fixes the build:
```patch
--- a/arch/arm/boot/compressed/Makefile
+++ b/arch/arm/boot/compressed/Makefile
@@ -121,7 +121,7 @@ ccflags-y := -fpic $(call cc-option,-mno-single-pic-base,) -fno-builtin -I$(obj)
 asflags-y := -DZIMAGE
 
 # Supply kernel BSS size to the decompressor via a linker symbol.
-KBSS_SZ = $(shell echo $$(($$($(CROSS_COMPILE)nm $(obj)/../../../../vmlinux | \
+KBSS_SZ = $(shell echo $$(($$($(NM) $(obj)/../../../../vmlinux | \
 		sed -n -e 's/^\([^ ]*\) [AB] __bss_start$$/-0x\1/p' \
 		       -e 's/^\([^ ]*\) [AB] __bss_stop$$/+0x\1/p') )) )
 LDFLAGS_vmlinux = --defsym _kernel_bss_size=$(KBSS_SZ)
@@ -165,7 +165,7 @@ $(obj)/bswapsdi2.S: $(srctree)/arch/$(SRCARCH)/lib/bswapsdi2.S
 # The .data section is already discarded by the linker script so no need
 # to bother about it here.
 check_for_bad_syms = \
-bad_syms=$$($(CROSS_COMPILE)nm $@ | sed -n 's/^.\{8\} [bc] \(.*\)/\1/p') && \
+bad_syms=$$($(NM) $@ | sed -n 's/^.\{8\} [bc] \(.*\)/\1/p') && \
 [ -z "$$bad_syms" ] || \
   ( echo "following symbols must have non local/private scope:" >&2; \
     echo "$$bad_syms" >&2; false )
```

**Comment by nickdesaulniers** [comment]
@tpimh can you please send that to lkml?

**Comment by tpimh** [comment]
I can do it on this weekend. If you want to submit it sooner, feel free.

**Comment by tpimh** [comment]
https://lore.kernel.org/r/20191110153043.111710-1-dima@golovin.in/
Please, correct me if I did something wrong.

**Comment by nickdesaulniers** [comment]
should be good to submit it to [rmk's q](https://lore.kernel.org/r/CAKwvOdnwKP5gRVmvKou1UoqHn7Fi-uoGFeAMf2dWoaEy0fibzA@mail.gmail.com/)

**Comment by tpimh** [comment]
With the registration fixed, I finally submitted the patch: https://www.armlinux.org.uk/developer/patches/viewpatch.php?id=8939/1

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/29c623d64f0dcd6aa10e0eabd16233e77114090b
