### ISSUE TITLE
-Wunused-variable in lib/vsprintf.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#767]
Reported-by: kernelci.org bot bot@kernelci.org

>     lib/vsprintf.c:766:14: warning: unused variable 'str' [-Wunused-variable]

**Comment by nathanchance** [comment]
I am not sure it is worth sending a patch to fix this right now. The warning comes from a patch in Andrew Morton's tree and there have been some further comments on it from the mailing list including the warning so there will probably be a v2 eventually:

https://lore.kernel.org/lkml/20191106024452.81923-1-joel@joelfernandes.org/

**Comment by nathanchance** [comment]
No longer relevant.
