### ISSUE TITLE
-Wsection in drivers/gpio/gpio-xgs-iproc.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#768]
Reported-by: kernelci.org bot bot@kernelci.org

>     WARNING: drivers/gpio/gpio-xgs-iproc.o(.data+0x50): Section mismatch in reference from the variable bcm_iproc_gpio_driver to the variable .init.rodata:bcm_iproc_gpio_of_match

**Comment by nathanchance** [comment]
Mark Brown sent a fix for this: https://lore.kernel.org/linux-gpio/20191105124915.34100-1-broonie@kernel.org/

**Comment by nickdesaulniers** [comment]
fixed: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5d682fa3d8943c19a632ebeaf70e8b9e41c78a5b
