### ISSUE TITLE
TOOLS_SUPPORT_RELR can not be enabled

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#769]
This config option is always shown as `Symbol: TOOLS_SUPPORT_RELR [=n]`, but my toolchain passes the test for RELR:
```
$ CC=clang-10 LD=ld.lld-10 NM=llvm-nm-10 OBJCOPY=llvm-objcopy-10 scripts/tools-support-relr.sh
$ echo $?
0
```
These are the variables I set when running make: `ARCH=arm64 AR=llvm-ar-10 AS=clang-10 'CC=/usr/bin/ccache clang-10' 'HOSTCC=/usr/bin/ccache clang-10' HOSTLD=ld.lld-10 KCFLAGS=-Wno-implicit-fallthrough HOSTLDFLAGS=-fuse-ld=lld LD=ld.lld-10 NM=llvm-nm-10 OBJCOPY=llvm-objcopy-10 OBJDUMP=llvm-objdump-10 OBJSIZE=llvm-size-10 STRIP=llvm-strip-10`

Relevant Kconfig options:
```
config TOOLS_SUPPORT_RELR
	def_bool $(success,env "CC=$(CC)" "LD=$(LD)" "NM=$(NM)" "OBJCOPY=$(OBJCOPY)" $(srctree)/scripts/tools-support-relr.sh)

# Select if the architecture has support for applying RELR relocations.
config ARCH_HAS_RELR
	bool

config RELR
	bool "Use RELR relocation packing"
	depends on ARCH_HAS_RELR && TOOLS_SUPPORT_RELR
	default y
	help
	  Store the kernel's dynamic relocations in the RELR relocation packing
	  format. Requires a compatible linker (LLD supports this feature), as
	  well as compatible NM and OBJCOPY utilities (llvm-nm and llvm-objcopy
	  are compatible).
```

**Comment by ihalip** [comment]
This seems to happen because of `ccache`. `CC=clang-10` doesn't show the issue.

**Comment by ihalip** [comment]
Crude fix:

```diff
diff --git a/scripts/tools-support-relr.sh b/scripts/tools-support-relr.sh
index 97a2c844a95e..45e8aa360b45 100755
--- a/scripts/tools-support-relr.sh
+++ b/scripts/tools-support-relr.sh
@@ -4,13 +4,13 @@
 tmp_file=$(mktemp)
 trap "rm -f $tmp_file.o $tmp_file $tmp_file.bin" EXIT
 
-cat << "END" | "$CC" -c -x c - -o $tmp_file.o >/dev/null 2>&1
+cat << "END" | $CC -c -x c - -o $tmp_file.o >/dev/null 2>&1
 void *p = &p;
 END
-"$LD" $tmp_file.o -shared -Bsymbolic --pack-dyn-relocs=relr -o $tmp_file
+$LD $tmp_file.o -shared -Bsymbolic --pack-dyn-relocs=relr -o $tmp_file
 
 # Despite printing an error message, GNU nm still exits with exit code 0 if it
 # sees a relr section. So we need to check that nothing is printed to stderr.
-test -z "$("$NM" $tmp_file 2>&1 >/dev/null)"
+test -z "$($NM $tmp_file 2>&1 >/dev/null)"
 
-"$OBJCOPY" -O binary $tmp_file $tmp_file.bin
+$OBJCOPY -O binary $tmp_file $tmp_file.bin
```

**Comment by pcc** [comment]
That looks like the correct fix, would you like to send it upstream?

**Comment by ihalip** [comment]
Sure, will send a patch later.

**Comment by tpimh** [comment]
Hope I can get `Reported-by: Dmitry Golovin <dima@golovin.in>` 😄

**Comment by ihalip** [comment]
Sent the patch just now, sorry it took so long.

**Comment by ihalip** [comment]
Closing this, the [change](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=65e1f38d9a2f07d4b81f369864c105880e47bd5a) is now in Linus' tree.

And that's my first contribution to the Linux kernel!

**Comment by nathanchance** [comment]
@ihalip congratulations, hopefully that is the first of many!

**Comment by nickdesaulniers** [comment]
then I can retire and drink :margaritas:, as was my plan all along
