### ISSUE TITLE
Warning: entity size for SHF_MERGE not specified

### ISSUE THREAD

**Issue by agners** [ClangBuiltLinux/linux#77]
Currently building for ARM32 shows warnings for several files:

      CC      drivers/soc/tegra/fuse/speedo-tegra114.o
    /tmp/speedo-tegra114-a6d4fc.s: Assembler messages:
    /tmp/speedo-tegra114-a6d4fc.s:155: Warning: entity size for SHF_MERGE not specified

This appears for multiple files, at least `drivers/soc/tegra/fuse/speedo-tegra114.c`, `drivers/soc/tegra/fuse/speedo-tegra124.c`, `drivers/clk/berlin/berlin2-avpll.c` and `drivers/clk/ti/clkctrl.c` are affected. It seems to be related to structs marked with `__initconst`.

It is probably a LLVM issue, it has been reported here: https://bugs.llvm.org/show_bug.cgi?id=31828

**Comment by nickdesaulniers** [comment]
I saw this during an arm64 build as well, in issue #44 which we've marked as a dupe of this one.

**Comment by nathanchance** [comment]
I don't see any warnings on an arm64 allyesconfig build with that patch.

**Comment by nickdesaulniers** [comment]
Thanks for testing! That's going above and beyond the call of duty!

**Comment by nickdesaulniers** [comment]
Was reverted since the new test was failing on OSX. Relanding in https://reviews.llvm.org/D53146.
