### ISSUE TITLE
$(CC) is used to link powerpc vDSO

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#774]
This means that `ld.lld` might not be used (see #342 for more background).

https://elixir.bootlin.com/linux/v5.3.12/source/arch/powerpc/kernel/vdso32/Makefile

https://elixir.bootlin.com/linux/v5.3.12/source/arch/powerpc/kernel/vdso64/Makefile

**Comment by tpimh** [comment]
`-fuse-ld=lld` workaround is good, but not very reliable, it's better to split those steps in two: separate compilation and linking. So it's easier to specify any linker and inspect linker options.

**Comment by nickdesaulniers** [comment]
So, similar to #785 (mips) but ppc?

**Comment by nathanchance** [comment]
https://lore.kernel.org/lkml/20200901222523.1941988-1-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment]
heh, I should have checked the issue tracker.  Seems I'm starting to forget about open issues we have. Maybe it's time for me to do a bug scrub and reread them all.

**Comment by nickdesaulniers** [comment]
I think this is causing issues because `-no-integrated-as` is dropped, too: https://groups.google.com/g/clang-built-linux/c/ayNmi3HoNdY

**Comment by nathanchance** [comment]
This is still relevant but judging from Nick's patch series above, I think this would require a pretty significant rewrite of the PowerPC vDSO Makefiles.

**Comment by nickdesaulniers** [comment]
So Christophe had [mentioned](https://lore.kernel.org/lkml/b2066ccd-2b81-6032-08e3-41105b400f75@csgroup.eu/) that my series would crash BFD 2.26. @nathanchance [mentioned](https://lore.kernel.org/lkml/20200902052123.GA2687902@ubuntu-n2-xlarge-x86/) an issue with ppc44x_defconfig that I was not able to reproduce.

Seems like this was worked around in
commit 4c62285439f8 ("Revert "powerpc/build: vdso linker warning for orphan sections"")

I've re-pinged https://lore.kernel.org/lkml/3d837a36-a186-6789-7924-eaa97f056b68@csgroup.eu/. Attached are rebased patches.
[ppc.774.mbox.txt](https://github.com/ClangBuiltLinux/linux/files/6361629/ppc.774.mbox.txt)

**Comment by nathanchance** [comment]
Christophe [mentioned](https://lore.kernel.org/r/a120fa0c-4d00-ed4c-cffa-0df1fb5abb2b@csgroup.eu/) that the PowerPC vDSO has been reworked in -next

https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/log/arch/powerpc/kernel/vdso

which might make doing this a little simpler.

**Comment by nickdesaulniers** [comment]
@nathanchance 's [diff](https://lore.kernel.org/llvm/YnlYemdzBDCobK%2Fd@dev-arch.thelio-3990X/) might be a solution here, too.

**Comment by nathanchance** [comment]
https://lore.kernel.org/20220509204635.2539549-1-nathan@kernel.org/

**Comment by nathanchance** [comment]
v2: https://lore.kernel.org/20220511185001.3269404-1-nathan@kernel.org/

**Comment by nathanchance** [comment]
Accepted:

https://git.kernel.org/powerpc/c/e247172854a57d1a7213bb835ecb4a40ce9bb2b9
https://git.kernel.org/powerpc/c/4406b12214f6592909b63dabdea86d69f1b5ba2e

**Comment by nathanchance** [comment]
Merged into mainline:

https://git.kernel.org/linus/e247172854a57d1a7213bb835ecb4a40ce9bb2b9
https://git.kernel.org/linus/4406b12214f6592909b63dabdea86d69f1b5ba2e

**Comment by nickdesaulniers** [comment]
Anything to update in our CI (such as previously disabled builds to re-enable)? Anything for #1601?

**Comment by nathanchance** [comment]
No, #1601 impacts using `LLVM=1` without `CROSS_COMPILE`, which is currently irrelevant for CI because `tuxmake` always passes `CROSS_COMPILE`.
