### ISSUE TITLE
CONFIG_DEBUG_INFO_BTF does not work with llvm-objdump + llvm-objcopy

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#779]
I came across [a patch on the netdev mailing list](https://lore.kernel.org/netdev/20191126174221.200522-1-sdf@google.com/) regarding GNU objcopy and I wanted to make sure that `llvm-obcopy` would not regress. As it turns out, `llvm-objcopy` does not work at all on either x86_64 or aarch64 (I have not tested anything else).

x86_64 failure (defconfig + `CONFIG_DEBUG_INFO` + `CONFIG_DEBUG_INFO_BTF`):

```
$ make -j$(nproc) -s CC=clang LD=ld.lld OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump O=out.x86_64 distclean defconfig vmlinux
...
llvm-objcopy: error: invalid output format: 'ELF64-x86-64'
```

AArch64 failure (defconfig + `CONFIG_DEBUG_INFO_BTF`):

```
$ make -j$(nproc) -s ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- LD=ld.lld NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump O=out.aarch64 distclean defconfig vmlinux
...
llvm-objcopy: error: invalid output format: 'ELF64-aarch64-little'
```

The relevant snippet of code from [`scripts/link-vmlinux.sh`](https://elixir.bootlin.com/linux/v5.4/source/scripts/link-vmlinux.sh#L102):

```sh
# generate .BTF typeinfo from DWARF debuginfo
# ${1} - vmlinux image
# ${2} - file to dump raw BTF data into
gen_btf()
{
	local pahole_ver
	local bin_arch

	if ! [ -x "$(command -v ${PAHOLE})" ]; then
		info "BTF" "${1}: pahole (${PAHOLE}) is not available"
		return 1
	fi

	pahole_ver=$(${PAHOLE} --version | sed -E 's/v([0-9]+)\.([0-9]+)/\1\2/')
	if [ "${pahole_ver}" -lt "113" ]; then
		info "BTF" "${1}: pahole version $(${PAHOLE} --version) is too old, need at least v1.13"
		return 1
	fi

	info "BTF" ${2}
	vmlinux_link ${1}
	LLVM_OBJCOPY=${OBJCOPY} ${PAHOLE} -J ${1}

	# dump .BTF section into raw binary file to link with final vmlinux
	bin_arch=$(LANG=C ${OBJDUMP} -f ${1} | grep architecture | \
		cut -d, -f1 | cut -d' ' -f2)
	bin_format=$(LANG=C ${OBJDUMP} -f ${1} | grep 'file format' | \
		awk '{print $4}')
	${OBJCOPY} --dump-section .BTF=.btf.vmlinux.bin ${1} 2>/dev/null
	${OBJCOPY} -I binary -O ${bin_format} -B ${bin_arch} \
		--rename-section .data=.BTF .btf.vmlinux.bin ${2}
}
```

They are using the output from `${OBJDUMP}` to set the `-O` flag on `${OBJCOPY}`. With the GNU tools, these appear to be mapped 1:1 but that does not appear to be the case for LLVM.

For x86_64: `llvm-objdump`'s file format is `ELF64-x86-64` but `llvm-objcopy` expects an `-O` value of `elf64-x86-64`.

For AArch64 : `llvm-objdump`'s file format is `ELF64-aarch64-little` but `llvm-objcopy` expects an `-O` value of  `elf64-littleaarch64`.

I am not sure how to reconcile this.

NOTE: To reproduce this, you will need `pahole 1.13` or newer. I just did this:

```bash
git clone git://git.kernel.org/pub/scm/devel/pahole/pahole.git
mkdir pahole/build
cd pahole/build
cmake -D__LIB=lib ..
make -j$(nproc)
```

and just added that build folder to my PATH to avoid actually installing it.

**Comment by tpimh** [comment]
Maybe this should be fixed on LLVM side? Probably the easiest way to fix it is to change `llvm-objdump` output to match the expected `-O` value for `llvm-objcopy`.

**Comment by nathanchance** [comment]
cc @rupprecht, I thought I did that initially but I forgot.

**Comment by rupprecht** [comment]
https://reviews.llvm.org/D74433 is one possible solution. There are other ways that might make this work, so we'll see which one sticks.

**Comment by rupprecht** [comment]
Also @MaskRay fyi

**Comment by MaskRay** [comment]
I vote for updating all the `llvm::object::ObjectFile::getFileFormatName()` derivatives to use lower case.

Please make comments if you agree so: https://reviews.llvm.org/D74433

**Comment by rupprecht** [comment]
Should be fixed as of 60a8a504f16dbbc5f2a6887ecb668ef4cb834949, lemme know if not.

**Comment by nathanchance** [comment]
x86_64 is fixed (although running into a different issue that I will post here shortly).

AArch64 still fails because `llvm-objdump` outputs `elf64-aarch64-little` but `llvm-objcopy` expects `elf64-littleaarch64`.

**Comment by nickdesaulniers** [comment]
@rupprecht thoughts on aarch64?

**Comment by rupprecht** [comment]
I agree they should be compatible. For ELF it was fortunately just a casing issue, but the aarch64 difference is annoying. The two choices are:
* Modify llvm-objdump to print a GNU objdump compatible name
* Change llvm-objcopy to allow either bfd or llvm style names

I'm not sure which one I'd prefer, because they each have their pros/cons -- on one hand, we don't need to inherit so much legacy bfd naming. On the other hand, we do want llvm-objdump to produce GNU objdump compatible output. Either way, though, we should have llvm-objdump and llvm-objcopy be on the same page.

**Comment by MaskRay** [comment]
Jordan asked me to finish this:/ 

https://reviews.llvm.org/D76046 should update ARM and AArch64 to match BFD names.

**Comment by MaskRay** [comment]
https://reviews.llvm.org/D76046 made llvm-objdump's "file format" line match ARM/AArch64/RISCV and big-endian PPC32/PPC64.

**Comment by nathanchance** [comment]
With the commit causing #871 reverted, BTF can be successfully generated for aarch64 with LLVM at https://github.com/llvm/llvm-project/commit/0616e9964b9ef2e2cb12790515610e7cdd0042e3.
