### ISSUE TITLE
-Wmisleading-indentation warnings

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#783]
https://reviews.llvm.org/D70638#1768200

**Comment by nathanchance** [comment]
As noted in the above link, this is probably more of a bug on the Linux side because of the mixing of tabs/spaces. While GCC does not warn about these instances, I do not think that it is unreasonable for Clang to do so.

Full list of warnings on -next: https://gist.github.com/747fd2ca5b41eb4bc0082c5b311347a5

I can probably tackle these over the next week.

**Comment by nathanchance** [comment]
I do not see any more warnings in mainline after https://github.com/llvm/llvm-project/commit/b4b904e19bb356724b2c6aea0199ce05c6f15cdb. As a result, I consider this fixed and I will close all but one of the misleading indentation warning issues, regardless of if the patches are accepted or not.

**Comment by nickdesaulniers** [comment]
but we don't set `-ftabstop` in the kernel, so what's the default?

**Comment by nathanchance** [comment]
It appears to be 8, otherwise we would still see warnings: https://elixir.bootlin.com/llvm/llvmorg-10-init/source/clang/include/clang/Basic/DiagnosticOptions.h#L69

**Comment by nickdesaulniers** [comment]
ah thanks, nice to see lxr indexing llvm.
