### ISSUE TITLE
Thoroughtly trying

### ISSUE THREAD

**Issue by altblitz** [ClangBuiltLinux/linux#784]
> blitz@inode /etc/systemd %                                
blitz@inode ~/backup/blitz/abs/extra/firefox-52 % cat ~/aur/linux-ck/PKGBUILD | grep -Ei 'clang'
  # make CC=clang AS=clang AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump OBJSIZE=llvm-objsize HOSTCC=clang HOSTCXX=clang bzImage modules
  make CC=clang CXX=clang HOSTCC=clang HOSTCXX=clang bzImage modules

`AS=clang' is the cultprit, since the compilation gives up on it.

**Comment by nathanchance** [comment]
There are [quite a few open issues](https://github.com/ClangBuiltLinux/linux/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BTOOL%5D+integrated-as%22) when using clang's integrated assembler on x86.

Feel free to follow along, file specific issues for errors that you find, or try to contribute fixes!

**Comment by altblitz** [comment]
Meanwhile, the ideas of CBL just works, with -O3 -march=native, MuQSS.
```
        msg2 "Running Steven Rostedt's make localmodconfig now"
        make LSMOD=$HOME/.config/modprobed.db localmodconfig
  make -s kernelrelease > version
  [[ -z "$_makenconfig" ]] || make nconfig
  # make CC=clang AS=clang AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump OBJSIZE=llvm-objsize 

blitz@inode ~/aur/linux-ck (git)-[master] % uname -a
Linux inode 5.4.1-2-ck #1 SMP PREEMPT Thu, 05 Dec 2019 10:46:29 +0000 x86_64 GNU/Linux
```

**Comment by nickdesaulniers** [comment]
>> `AS=clang' is the cultprit, since the compilation gives up on it.
> There are quite a few open issues when using clang's integrated assembler on x86.

Yep, closing the issue, but please do file bugs that are more specific if we don't already have an issue tracking them.  Your feedback for your configs is invaluable and we do appreciate it.
 
> with -O3

We have some issues at `-O3` due to aggressive loop unrolling and UB in the kernel, which you might not experience with your kernel, but it's non-standard to set `-O3 -march=native`, so it's something we definitely don't test.
