### ISSUE TITLE
MIPS VDSO is not built when using LLD

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#785]
When using lld to link MIPS kernel, the following warning is triggered:
```
arch/mips/vdso/Makefile:62: MIPS VDSO requires binutils >= 2.25
```
With with this segment removed, VDSO is built:
https://github.com/ClangBuiltLinux/linux/blob/dcf78ee660888d8302a0f0888bf746a164d267fa/arch/mips/vdso/Makefile#L50-L66

R_MIPS_PC32 relocation is supported by LLD: https://reviews.llvm.org/rLLD259782.

**Comment by nathanchance** [comment]
https://github.com/samitolvanen/linux/commit/44939cea7637b55fdb3950a4fe281c5e0fa70ce4 would solve this so we could just exclude this entire block if using LLD.

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20200419180445.26722-2-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
v2: https://lore.kernel.org/lkml/20200419202128.20571-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
v3: https://lore.kernel.org/lkml/20200423171807.29713-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
v4: https://lore.kernel.org/lkml/20200428221419.2530697-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
accepted:
1. https://git.kernel.org/pub/scm/linux/kernel/git/mips/linux.git/commit/?id=b744b43f79cc758127042e71f9ad7b1afda30f84
2. https://git.kernel.org/pub/scm/linux/kernel/git/mips/linux.git/commit/?id=e91946d6d93ef6167bd3b1456f163d1585095ea1
3. https://git.kernel.org/pub/scm/linux/kernel/git/mips/linux.git/commit/?id=fd9d0ca2cc4f3c26877eb336a7d26d705ff42b8a
4. https://git.kernel.org/pub/scm/linux/kernel/git/mips/linux.git/commit/?id=2ff906994b6c2b949c5bf65330a8abb5dde9c8e5
5. https://git.kernel.org/pub/scm/linux/kernel/git/mips/linux.git/commit/?id=22235ef34a9745c4964c5aa11d57d5ce0b0117de

**Comment by nathanchance** [comment]
That's not what we want... That regex lol.

**Comment by nathanchance** [comment]
Series merged into mainline :)

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/?h=22235ef34a9745c4964c5aa11d57d5ce0b0117de

#1025 is still outstanding.
