### ISSUE TITLE
Add AArch64 support for -fpatchable-function-entry

### ISSUE THREAD

**Issue by willdeacon** [ClangBuiltLinux/linux#788]
`AArch64` support for `-fpatchable-function-entry=N` was implemented in GCC in 2017 [1] and provides a mechanism to insert NOPs at the very beginning of each function, which in turn can be patched at runtime to allow functions to be 'hooked' prior to the prologue, along with their argument values. This is not something that can be done with the more traditional `-pg`/`'mcount'` approach, since the call to `_mcount()` is only defined to occur as "as one of its [the function's] first operations" [2]. Some other architectures (notably `x86`), implement `-mfentry` to solve this issue, but it's considerably less flexible.

The `arm64` Linux kernel requires toolchain support for `-fpatchable-function-entry` in order to support kernel live-patching via `CONFIG_FTRACE_WITH_REGS`, however it will also be needed in order to support the function graph tracer in the presence of pointer authentication for kernel functions. In this situation, it is necessary to rewrite the return address of the function from the entry hook, meaning that the return address must be authenticated/descrambled from the hook function which requires the unmodified stack pointer on entry to the function being hooked. For the same reasons as before, this is not something that is guaranteed by `-pg`.

[1] https://gcc.gnu.org/ml/gcc-patches/2017-07/msg00391.html
[2] https://sourceware.org/binutils/docs/gprof/Implementation.html#Implementation

**Comment by willdeacon** [comment]
It's probably worth mentioning that the GCC implementation of this seems to be broken when used in combination with `-mbranch-protection=bti`. With this combination, the landing pad instruction needs to be emitted before the additional `nop` instructions, otherwise functions would no longer be callable!

**Comment by nickdesaulniers** [comment]
https://llvm.org/pr43912

**Comment by willdeacon** [comment]
GCC BTI issue:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92424

**Comment by nickdesaulniers** [comment]
@MaskRay has implemented this in:
1. https://reviews.llvm.org/D72222
2. https://reviews.llvm.org/D72221
3. https://reviews.llvm.org/D72220
4. https://reviews.llvm.org/D72215

The question about interplay between BTI and PFE still remains.

**Comment by nickdesaulniers** [comment]
The above patches have landed. It sounds like there may be more work involved for BTI interplay, and supporting a non-zero offset.

**Comment by nathanchance** [comment]
Looks like Linaro's CI shows this regresses `all{mod,yes}config` for arm64:

https://groups.google.com/d/msg/clang-built-linux/d8z5F3bkfR8/ZgU3gkKvBwAJ

creduce spits out... (lol)

```c
a() {}
```

Original preprocessed file and interestingness test available [here](https://github.com/nathanchance/creduce-files/tree/e449ccbeba7d794ca395b5ded458e7f3e79992f6/f17ae668a96eeb69f0664f126cf672e1a05754d2).

**Comment by nathanchance** [comment]
cc @MaskRay (I added some more info to the information above).

**Comment by MaskRay** [comment]
Should be fixed by https://github.com/llvm/llvm-project/commit/7fa5290d5bd5632d7a36a4ea9f46e81e04fb819e

GNU as and GNU ld lack important features that make such metadata sections work. Without the features, `__patchable_function_entries` can only work in very few scenarios (read as: Linux kernel).

I reported these a few months ago and now with Linux kernel, we see a strong need for them... https://sourceware.org/ml/binutils/2019-11/msg00266.html `.tmp_vmlinux1` is broken if we pass `--gc-sections`...
