### ISSUE TITLE
Add support for "asm inline"

### ISSUE THREAD

**Issue by willdeacon** [ClangBuiltLinux/linux#789]
GCC 9 introduced support for `asm inline`, which forces the inliner to treat the `asm` block as having the "minimum size". This can be useful when the block may appear to be large, but actually ends up using asm directives such as `.pushsection`. See [1] and [2] for slightly more details. It may be that Clang just needs to accept the new syntax, rather than changing its inlining decisions.

[1] https://gcc.gnu.org/onlinedocs/gcc-9.2.0/gcc/Size-of-an-asm.html#Size-of-an-asm
[2] https://git.kernel.org/linus/227c3e9eb5cf35

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D75563
