### ISSUE TITLE
-Wmisleading-indentation in drivers/block/xen-blkfront.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#791]
```
../drivers/block/xen-blkfront.c:1117:4: warning: misleading indentation; statement is not part of the previous 'if' [-Wmisleading-indentation]
                nr_parts = PARTS_PER_DISK;
                ^
../drivers/block/xen-blkfront.c:1115:3: note: previous statement is here
                if (err)
                ^
```

Patch submitted: https://lore.kernel.org/lkml/20191209201444.33243-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/xen/tip.git/commit/?h=for-linus-5.5b&id=589b72894f53124a39d1bb3c0cecaf9dcabac417

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/589b72894f53124a39d1bb3c0cecaf9dcabac417
