### ISSUE TITLE
'-save-restore' is not a recognized feature for RISC-V

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#804]
It was previously mentioned here: https://github.com/ClangBuiltLinux/linux/issues/75#issuecomment-504371432. This warning is produced a lot:
```
'-save-restore' is not a recognized feature for this target (ignoring feature)
```
Warning is silenced after removing this line:
https://github.com/ClangBuiltLinux/linux/blob/95f1fa9e3418d50ce099e67280b5497b9c93843b/arch/riscv/Makefile#L45
Perhaps, something should be done on LLVM side to make this warning less annoying. Proper feature detection on Linux side should be nice as well.

**Comment by nathanchance** [comment]
https://elixir.bootlin.com/llvm/llvmorg-11-init/source/clang/lib/Driver/ToolChains/Arch/RISCV.cpp#L435

I definitely think this should be improved in LLVM (maybe just ignore `-mno-save-restore` if that is the default) but working around it in the kernel isn’t hard either.

```diff
diff --git a/arch/riscv/Makefile b/arch/riscv/Makefile
index b9009a2fbaf5..e6d261f00bcc 100644
--- a/arch/riscv/Makefile
+++ b/arch/riscv/Makefile
@@ -42,7 +42,9 @@ riscv-march-$(CONFIG_RISCV_ISA_C)     := $(riscv-march-y)c
 KBUILD_CFLAGS += -march=$(subst fd,,$(riscv-march-y))
 KBUILD_AFLAGS += -march=$(riscv-march-y)
 
+ifndef CONFIG_CC_IS_CLANG
 KBUILD_CFLAGS += -mno-save-restore
+endif
 KBUILD_CFLAGS += -DCONFIG_PAGE_OFFSET=$(CONFIG_PAGE_OFFSET)
 
 ifeq ($(CONFIG_CMODEL_MEDLOW),y)
```

**Comment by nathanchance** [comment]
Reported to upstream: https://llvm.org/pr44853

**Comment by nathanchance** [comment]
This has been fixed in LLVM 11: https://github.com/llvm/llvm-project/commit/07f7c00208b393296f8f27d6cd3cec2b11d86fd8
