### ISSUE TITLE
setup_vm() is called from head.S before relocate so it should not use absolute addressing

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#806]
This error is only triggered with LLVM 9, not LLVM 10. I don't know the exact commit that fixed it, but it should be found and backported to LLVM 9.
```
arch/riscv/mm/init.c:370:2: error: "setup_vm() is called from head.S before relocate so it should not use absolute addressing."
#error "setup_vm() is called from head.S before relocate so it should not use absolute addressing."
 ^
```
Relevant comment:
https://github.com/ClangBuiltLinux/linux/blob/43a2898631a8beee66c1d64c1e860f43d96b2e91/arch/riscv/mm/init.c#L355-L371

I suspect this is the change to be backported: https://reviews.llvm.org/D67065

**Comment by nickdesaulniers** [comment]
cc @tstellar

**Comment by nathanchance** [comment]
FWIW, it sounds like LLVM 9 is not getting any more releases so I think this should be closed.
