### ISSUE TITLE
-Wconstant-logical-operand in arch/mips/lantiq/irq.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#807]
```
arch/mips/lantiq/irq.c:305:48: error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
        if ((irq == LTQ_ICU_EBU_IRQ) && (module == 0) && LTQ_EBU_PCC_ISTAT)
                                                      ^  ~~~~~~~~~~~~~~~~~
arch/mips/lantiq/irq.c:305:48: note: use '&' for a bitwise operation
        if ((irq == LTQ_ICU_EBU_IRQ) && (module == 0) && LTQ_EBU_PCC_ISTAT)
                                                      ^~
                                                      &
arch/mips/lantiq/irq.c:305:48: note: remove constant to silence this warning
        if ((irq == LTQ_ICU_EBU_IRQ) && (module == 0) && LTQ_EBU_PCC_ISTAT)
                                                     ~^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by nathanchance** [comment]
Which config?

**Comment by tpimh** [comment]
I can't recall now, need to check. I'm travelling now, but hopefully will have access to a computer in couple of days. It might be 64 bit or big endian.

**Comment by tpimh** [comment]
Just tested. Was able to reproduce this error on `xway_defconfig`, should also be reproducible on other 32bit big endian MIPS configs.

**Comment by tpimh** [comment]
Checking other mips defconfigs now, xway is actually the only one that has `CONFIG_LANTIQ=y`.

**Comment by nathanchance** [comment]
Patch submitted: https://lore.kernel.org/r/20210105201548.50920-1-natechancellor@gmail.com

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/mips/c/c6f2a9e17b9bef7677caddb1626c2402f3e9d2bd

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/torvalds/c/c6f2a9e17b9b
