### ISSUE TITLE
-Wmisleading-indentation in mm/page_alloc.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#809]
```
mm/page_alloc.c:4479:4: warning: misleading indentation; statement is not part of the previous 'if' [-Wmisleading-indentation]
                 if (order >= pageblock_order && (gfp_mask & __GFP_IO) &&
                 ^
mm/page_alloc.c:4476:3: note: previous statement is here
                if (page)
                ^
1 warning generated.
```
Caused by an extra space in front of if statement.

**Comment by nathanchance** [comment]
Fixed by accident in -next: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit?id=7908693e318cab40a35b5da198f454797c1fdb22

**Comment by nathanchance** [comment]
No longer relevant after https://github.com/llvm/llvm-project/commit/b4b904e19bb356724b2c6aea0199ce05c6f15cdb.
