### ISSUE TITLE
-Wmisleading-indentation in fs/read_write.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#810]
```
fs/read_write.c:1760:3: warning: misleading indentation; statement is not part of the previous 'if' [-Wmisleading-indentation]
         if (unlikely((loff_t) (pos + len) < 0))
         ^
fs/read_write.c:1757:2: note: previous statement is here
        if (unlikely(pos < 0 || len < 0))
        ^
1 warning generated.
```

**Comment by nathanchance** [comment]
Patch submitted: https://lore.kernel.org/lkml/20191218032351.5920-1-natechancellor@gmail.com

David Sterba wants a different patch applied: https://lore.kernel.org/lkml/20191218110437.GJ3929@twin.jikos.cz/

**Comment by nathanchance** [comment]
No longer relevant after https://github.com/llvm/llvm-project/commit/b4b904e19bb356724b2c6aea0199ce05c6f15cdb.
