### ISSUE TITLE
-Wmisleading-indentation in drivers/staging/uwb/allocator.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#820]
```
../drivers/staging/uwb/allocator.c:353:3: warning: misleading indentation; statement is not part of the previous 'else' [-Wmisleading-indentation]
  alloc_found:
  ^
../drivers/staging/uwb/allocator.c:350:2: note: previous statement is here
        else
        ^
1 warning generated.
```

Isn't this a false positive? A goto label isn't affected by indentation, right?

**Comment by davidbolvansky** [comment]
Please write here

https://reviews.llvm.org/D70638

About this false positive..

**Comment by nathanchance** [comment]
> Please write here
> 
> https://reviews.llvm.org/D70638
> 
> About this false positive..

Done and tentatively marking this as a bug in clang.

**Comment by nathanchance** [comment]
This should be fixed with https://reviews.llvm.org/D72202.

**Comment by nathanchance** [comment]
Merged: https://reviews.llvm.org/rGf5329bfc76bb6fc30a589e8238aabc005c52e5d6
