### ISSUE TITLE
-Wself-assign in drivers/scsi/qla2xxx/qla_mbx.c

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/linux#83]
```
drivers/scsi/qla2xxx/qla_mbx.c:1489:4: warning: explicitly assigning value of variable of type 'uint64_t'
      (aka 'unsigned long long') to itself [-Wself-assign]
        l = l;
        ~ ^ ~
```

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20180920221706.4948-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/mkp/scsi.git/commit/?id=3e59790e07a94dc3bef541aa044dde36fdb61714

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3e59790e07a94dc3bef541aa044dde36fdb61714
