### ISSUE TITLE
-mrecord-mcount unrecognized for most arch's

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#833]
https://reviews.llvm.org/rG2520bef865329d4c04e2de30c222ad0d5ad13ccc added support for `-mrecord-mcount`, but only for systemZ.  When `CONFIG_FUNCTION_TRACER` and `CONFIG_FTRACE_MCOUNT_RECORD` are set in the top level Makefile

```make
ifeq ($(call cc-option-yn,-mrecord-mcount),y)
```
is run.
```sh
$ clang -mrecord-mcount -target aarch64-linux-gnu -c -x c /dev/null
```
returns `0`, but `-mrecord-mcount` will later fail for all non-systemZ targets.

**Comment by nickdesaulniers** [comment]
reported: https://reviews.llvm.org/D71627#1793006
Reported-by: ci_notify@linaro.org

**Comment by nathanchance** [comment]
Thanks @MaskRay!

https://reviews.llvm.org/rG0792ef72564071f21b727d0de3a14d565950290f

I’ll verify this tomorrow but I’ll close this now and reopen it if something explodes.
