### ISSUE TITLE
crash in clang ARMFrameLowering.cpp:1576

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#834]
Reported-by: ci_notify@linaro.org

https://reviews.llvm.org/rGbbcf1c3496ce2bd1ed87e8fb15ad896e279633ce is causing Clang to crash.
https://ci.linaro.org/job/tcwg_kernel-bisect-llvm-master-arm-next-allmodconfig/62/artifact/artifacts/build-bbcf1c3496ce2bd1ed87e8fb15ad896e279633ce/console.log

**Comment by nathanchance** [comment]
Reverted: https://github.com/llvm/llvm-project/commit/2ff5a596cbfd8fcf760f0deb62e52f5d378f5776#diff-9327e511c35eb06fb14e9f3075fcab9e
