### ISSUE TITLE
asm goto + output constraints

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#835]
@gwelymernans has 3 patches implementing this:
1. https://reviews.llvm.org/D69868
2. https://reviews.llvm.org/D69876
3. https://reviews.llvm.org/D71314

We'll need to wire up a proper config and feature detection in KBuild, then redefine `__get_user`/`__put_user` to take advantage of them.

**Comment by nathanchance** [comment]
https://github.com/llvm/llvm-project/commit/23c2a5ce33f0f05e4cc43c2cbb9009e9b549839c

https://github.com/llvm/llvm-project/commit/50cac248773c3a023e8f6ceb9938bdd5e9f15da2

**Comment by nickdesaulniers** [comment]
I have a patch for KBuild support, and a few others to make use of this feature (still under active development).

**Comment by nickdesaulniers** [comment]
https://reviews.llvm.org/D75098

**Comment by nickdesaulniers** [comment]
@jyknight has another approach in https://reviews.llvm.org/D79794. I ran into some issues with aarch64 with that and its previous dependencies which landed this morning, but need to retest and find a reproducer.

**Comment by nickdesaulniers** [comment]
Also, @nathanchance and @dileks both pointed me to https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=587f17018a2c6c414e41a312b002faaef60cf423, so Kbuild support has been added for this to the kernel.

**Comment by dileks** [comment]
You can write the URL shorter...

https://git.kernel.org/587f17018a2c6c414e41a312b002faaef60cf423

...and please add the name of the beast:

"Kconfig: add config option for asm goto w/ outputs"

Of course, I hope you plan an innovative blog on this topic :-).

**Comment by nickdesaulniers** [comment]
> Of course, I hope you plan an innovative blog on this topic :-).

@gwelymernans and I are working on a talk proposal for this at US LLVM Developers Conf 2020.

**Comment by nickdesaulniers** [comment]
This shipped in clang-11, and https://github.com/ClangBuiltLinux/linux/commit/587f17018a2c6c414e41a312b002faaef60cf423 + https://github.com/ClangBuiltLinux/linux/commit/865c50e1d279671728c2936cb7680eb89355eeea made use of it in linux 5.10.
