### ISSUE TITLE
unsupported inline asm: input with type 'unsigned long' matching output with type '__wsum' (aka 'unsigned int') on mips64

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#836]
Building on MIPS64 using `mips_paravirt_defconfig`:
```
./arch/mips/include/asm/checksum.h:195:9: error: unsupported inline asm: input with type 'unsigned long' matching output with type '__wsum' (aka 'unsigned int')
        : "0" ((__force unsigned long)daddr),
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ramosian-glider** [comment]
A similar issue has been previously discussed here: https://www.linux-mips.org/archives/linux-mips/2015-02/msg00032.html

**Comment by ramosian-glider** [comment]
Also reproducible for me with this config: [config.txt](https://github.com/ClangBuiltLinux/linux/files/4629416/config.txt) (thanks Dmitry for sharing it!)

```
make ARCH=mips CROSS_COMPILE=mips64el-linux-gnuabi64- CFLAGS=" -mabi=64 -EL --target=mips64el-linux-gnuabi64 -w" CC=clang LD=ld.lld -j64 
```

**Comment by nathanchance** [comment]
This should be fixed by https://git.kernel.org/linus/198688edbf77c6fc0e65f5d062f810d83d090166. There is a follow-up fix pending but it will keep everything working: https://lore.kernel.org/r/1617359240-16609-1-git-send-email-yangtiezhu@loongson.cn/.

**Comment by nickdesaulniers** [comment]
HTTP 404 on that first link @nathanchance

**Comment by nathanchance** [comment]
> HTTP 404 on that first link @nathanchance 

Thanks, fixed.

**Comment by nickdesaulniers** [comment]
Nice to see Longsoon folks testing with AND FIXING clang builds! 🎉
