### ISSUE TITLE
unsupported flag -P in llvm-ar

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#837]
cc @rupprecht 

Reported-by: Miles Chen (陳民樺) <Miles.Chen@mediatek.com>

Looks like drivers/xen/xenbus/built-in.a fails to build due to llvm-ar not supporting `-P`.  I haven't dug in to triage yet.

**Comment by rupprecht** [comment]
Support for `P` was added Feb 14, 2019: https://github.com/llvm/llvm-project/commit/b7ae7297b94c4bfde45e210a335d9f18e3b5f19a

I'd guess an older version of llvm is being used (llvm-8 is the min version needed, per llvm.org release history), or the command line is being passed in a way that tricks llvm-ar.

**Comment by nickdesaulniers** [comment]
ok, sorry for the noise.  I'll triple check the report that was sent.
