### ISSUE TITLE
[bfd] unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#844]
when compiling Linux next with an assertions enabled clang, I see a bunch of:

```
aarch64-linux-gnu-ld: warning: net/mac80211/trace.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000

```

**Comment by nathanchance** [comment]
FWIW, I can't seem to reproduce this... What version of binutils is it? I am using the latest from master, maybe it's visible on something that is older? Is it strictly related to assertions? What is your kernel `make` invocation?

**Comment by smithp35** [comment]
That message is coming from an older version of binutils that doesn't understand the .note.gnu.property entries for PAC and BTI. The 0xc000000 is defined in https://developer.arm.com/docs/ihi0056/f/elf-for-the-arm-64-bit-architecture-aarch64-abi-2019q2-documentation as GNU_PROPERTY_AARCH64_FEATURE_1_AND

I would only expect to see this property in object files if branch protection has been enabled, for example on an arbitrary c program: 
clang --target=aarch64-linux-gnu -mbranch-protection=standard ptr.c -c
llvm-readelf --notes ptr.o
```
Displaying notes found at file offset 0x00000050 with length 0x00000020:
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_PROPERTY_TYPE_0 (property note)
    Properties:    aarch64 feature: BTI, PAC
```
Maybe some of the all configs enable 8.3 and 8.5 PAC and BTI features?

**Comment by nickdesaulniers** [comment]
ah, that's likely. Any idea of the first versions of binutils that supports PAC/BTI? (@smithp35 )

**Comment by smithp35** [comment]
There is a nice page that I've only recently found with a good summary of which architectural feature is in which GNU toolchain https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/architecture-support
According to that it says 2.33.1 which makes sense as the first patches where in April 2019.

**Comment by nickdesaulniers** [comment]
dupe of #1054 #1068
