### ISSUE TITLE
-Wfortify-source in kernel/printk/printk.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#846]
Introduced by https://github.com/llvm/llvm-project/commit/6d485ff455ea2b37fef9e06e426dae6c1241b231.

Visible when `CONFIG_PRINTK` is disabled (which I discovered with arm64 allnoconfig) because `text`'s length is defined to be `LOG_LINE_MAX + PREFIX_MAX`, which evaluates to 0 when `CONFIG_PRINTK` is disabled ([link](https://elixir.bootlin.com/linux/v5.4.14/source/kernel/printk/printk.c#L2065)).

```
../kernel/printk/printk.c:2416:10: warning: 'sprintf' will always overflow; destination buffer has size 0, but format string expands to at least 33 [-Wfortify-source]
                        len = sprintf(text,
                              ^
1 warning generated.
```

I'll probably email the printk maintainers on Monday because I do not really see how to reconcile this without either bumping `LOG_LINE_MAX + PREFIX_MAX` when `CONFIG_PRINTK` is unset or changing the code when `CONFIG_PRINTK` is unset.

**Comment by nathanchance** [comment]
Message sent to the maintainers: https://lore.kernel.org/lkml/20200130021648.GA32309@ubuntu-x2-xlarge-x86/

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20200130221644.2273-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch accepted: https://git.kernel.org/pmladek/printk/c/5661dd95a2958634485bb1a53f90a6ab621d4b0c

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5661dd95a2958634485bb1a53f90a6ab621d4b0c
