### ISSUE TITLE
-Wswitch in drivers/scsi/*

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/linux#85]
```
drivers/scsi/cxlflash/superpipe.c:1948:7: warning: overflow converting case value to switch condition type
      (3228093062 to 18446744072642677382) [-Wswitch]
        case DK_CXLFLASH_MANAGE_LUN:
             ^
./include/uapi/scsi/cxlflash_ioctl.h:199:33: note: expanded from macro 'DK_CXLFLASH_MANAGE_LUN'
#define DK_CXLFLASH_MANAGE_LUN          CXL_IOWR(0x86, dk_cxlflash_manage_lun)
                                        ^
./include/uapi/scsi/cxlflash_ioctl.h:187:26: note: expanded from macro 'CXL_IOWR'
#define CXL_IOWR(_n, _s)        _IOWR(CXL_MAGIC, _n, struct _s)
                                ^
./include/uapi/asm-generic/ioctl.h:88:29: note: expanded from macro '_IOWR'
#define _IOWR(type,nr,size)     _IOC(_IOC_READ|_IOC_WRITE,(type),(nr),(_IOC_TYPECHECK(size)))
                                ^
./include/uapi/asm-generic/ioctl.h:70:2: note: expanded from macro '_IOC'
        (((dir)  << _IOC_DIRSHIFT) | \
        ^
```

**Comment by tpimh** [comment]
Is this only a warning? If it is nothing fatal, I suggest adding "low priority" label to it.

**Comment by nickdesaulniers** [comment]
[All](https://github.com/ClangBuiltLinux/linux/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A-Wswitch+) of our `-Wswitch` warnings go through `_IOC`.  Where there's smoke, there's fire.

**Comment by nathanchance** [comment]
The problem with the `-Wswitch` scsi warnings is they all come from ioctl functions, where the `cmd` parameter type is defined as `int` in `include/scsi/scsi_host.h` so fixing these warnings by turning the type to `unsigned int` is going to be a scsi wide change (and that's not taking into account if there are any ioctls that do allow a negative command).

Will probably need to brainstorm and think of other possible solutions.

**Comment by nathanchance** [comment]
I went ahead and sent an email to the SCSI people for clarification: https://lore.kernel.org/lkml/20181004183047.GA1885@flashbox/

**Comment by nathanchance** [comment]
Proposed diff: https://lore.kernel.org/lkml/20181019065104.GA27170@flashbox/

I'll clean it up and write a formal commit message tomorrow but it at least builds for both x86_64 and arm64 allyesconfig

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20181019175714.444-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch v2: https://lore.kernel.org/lkml/20181020050143.589-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch v3 to fix the second comment's warning (which I missed because I wasn't building PPC locally, that's been fixed now): https://lore.kernel.org/lkml/20190114044206.6351-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
Probably time to reping the thread (please put the maintainers in the To: field) @nathanchance .

**Comment by nathanchance** [comment]
I've sent v4 with Bart's suggested change, his review, and a plea for a response.

https://lore.kernel.org/lkml/20190126075256.29608-1-natechancellor@gmail.com/

If you could review/test it yourself to try and get the ball rolling, I'd appreciate it :)

**Comment by nickdesaulniers** [comment]
@nathanchance it's ok to be frustrated, but remember that maintaining FLOSS is a thankless job and the maintainers are only human.  When I get frustrated, I find it helpful to type out a big email spelling out what I really think, then go for a walk, get a cup of coffee, then delete the email.  I've done that for response to Linus a few times now.

I will do my best to add a tested by tag sometime this week.

**Comment by nathanchance** [comment]
Indeed. I tried my best to tone it down but it probably could have been even better (or just not there at all).

Thank you, hopefully we'll see some progress soon!

**Comment by nickdesaulniers** [comment]
No worries; one thing to note as well is that FLOSS software development involves dealing with people and their politics; sometimes even more so than with code.  This effort in particular strives to strike a balance and find compromise between two different, large, and import FLOSS code bases with different goals, interpretations, and developers.

While LKML is famous for being a shit show, do strive to hold yourself to a higher standard and try to do the right thing.  Both require constant and active pursuit.  And remind me when I need to remember this point; because it's easy to get frustrated.

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/r/yq1pns1x64t.fsf@oracle.com/
https://git.kernel.org/pub/scm/linux/kernel/git/mkp/scsi.git/commit/?h=5.1/scsi-queue&id=6f4e626fb0cc93d50b49b79c2ee33bd769ee57f0

**Comment by nathanchance** [comment]
Merged into mainline! https://git.kernel.org/torvalds/c/6f4e626fb0cc93d50b49b79c2ee33bd769ee57f0
