### ISSUE TITLE
android-4.19 Cuttlefish x86 does not boot after LLVM commit 5b22bcc2b70d82c73ce5428170dcc2038a729d74

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#852]
Background: I have started [boot testing Android Cuttlefish](https://nathanchance.dev/posts/building-using-cuttlefish/) to try and catch bugs before they hit Android through either upstream Linux or LLVM.

I do not really have a whole ton of information to offer up right now other than a `git bisect` and isolating the problem purely to `CONFIG_LTO_CLANG` (`CONFIG_CFI_CLANG` does not affect it). I do not see this problem with android-5.4 or android-mainline, which I suspect is because they are using ThinLTO.

https://github.com/llvm/llvm-project/commit/5b22bcc2b70d82c73ce5428170dcc2038a729d74

```bash
$ git bisect log
# bad: [c4b4c0c47c992e63fc0792d71bea82b6e6dcf0cd] [mlir] Expand shape functions in ShapeInference doc
# good: [f0654875fb240ed9d4b2718cfa5f5c7f9d9daef3] [gn build] Port f2af0607000
git bisect start 'origin/master' 'f0654875fb240ed9d4b2718cfa5f5c7f9d9daef3'
# bad: [200ac6c3d88a1816c7ea86d5cde85e115a809542] [llvm-objcopy][test] Fix tests when path contains "bar"
git bisect bad 200ac6c3d88a1816c7ea86d5cde85e115a809542
# good: [8bb9642fd7cda09449af5cb0cced220e57a0011a] [gn build] Port 601687bf731
git bisect good 8bb9642fd7cda09449af5cb0cced220e57a0011a
# good: [1d9e08ec35a5979f103b876f8dd2324f77db3f6e] [AMDGPU] Add file headers for few files where it is missing.
git bisect good 1d9e08ec35a5979f103b876f8dd2324f77db3f6e
# good: [17dbc6611df9044d779d85b3d545bd37e5dd5200] AMDGPU: Cleanup and fix SMRD offset handling
git bisect good 17dbc6611df9044d779d85b3d545bd37e5dd5200
# good: [84bd8511085891a7c5f413f2d54d3a31b98105aa] [GlobalISel][IRTranslator] When translating vector geps, splat the base pointer if required.
git bisect good 84bd8511085891a7c5f413f2d54d3a31b98105aa
# good: [d28763cad06e66651e1936756d3e28126b055abf] Replace 'AllowExplicit' bool with an enum. No functionality change.
git bisect good d28763cad06e66651e1936756d3e28126b055abf
# good: [5ae6554a1dcd2e39346030c06d364492901c9e8d] PR41991: Accept attributes on defaulted and deleted friends.
git bisect good 5ae6554a1dcd2e39346030c06d364492901c9e8d
# bad: [5b22bcc2b70d82c73ce5428170dcc2038a729d74] [X86][ELF] Prefer to lower MC_GlobalAddress operands to .Lfoo$local
git bisect bad 5b22bcc2b70d82c73ce5428170dcc2038a729d74
# good: [980517b3530ffb7faa1a23fdc007d78f5b45ae3c] [Concepts] Check function constraints before deducing auto return type
git bisect good 980517b3530ffb7faa1a23fdc007d78f5b45ae3c
# first bad commit: [5b22bcc2b70d82c73ce5428170dcc2038a729d74] [X86][ELF] Prefer to lower MC_GlobalAddress operands to .Lfoo$local
```

I do not have a super clean set of steps to reproduce this but I can at some point of the next couple of days. If you are familiar with building Android kernels using `build.sh` and the build config system and using Cuttlefish, it should be fairly easy to reproduce with an upstream version of LLVM.

[Good dmesg](https://gist.github.com/8df0c76d50d2a198f2d7391a31f4dd50).

[Bad dmesg](https://gist.github.com/c8d397024f707229ede3b11ac2161702).

cc @MaskRay @samitolvanen

**Comment by MaskRay** [comment]
(I have no experience building Android.)

Can you check disassembly of linked results before and at commit  5b22bcc2b70d82c73ce5428170dcc2038a729d74?

**Comment by nickdesaulniers** [comment]
https://github.com/llvm/llvm-project/commit/5b22bcc2b70d82c73ce5428170dcc2038a729d74

**Comment by nathanchance** [comment]
@MaskRay when I get home from work tonight, I will tar up all of the artifacts from the build so you can inspect them.

**Comment by nathanchance** [comment]
[Objects compiled without 5b22bcc2b70d82c73ce5428170dcc2038a729d74](https://1drv.ms/u/s!AsQNYeB-IEbqhxuPsQ0iFpxDamsg?e=yoKlgt)

[Objects compiled with 5b22bcc2b70d82c73ce5428170dcc2038a729d74](https://1drv.ms/u/s!AsQNYeB-IEbqhxooOHpkDzMCarHu?e=rh2bQa)

Warning, they are each 750MB... Let me know if there is anything else I can do to help!

**Comment by MaskRay** [comment]
Every bitcode `.o` is different. This is due to:

* `.ident` assembly directive. It can be turned off via `CFLAGS=-Qn` (you can compare` gcc/clang -S -Qy`)
* DW_AT_producer in `.debug_info`. Pass `-DLLVM_APPEND_VC_REV=off` when building clang can strip the commit id. It will be simply `DW_AT_producer    ("clang version 11.0.0 ")`. With this, `-Qn` should be unnecessary.

@nathanchance Can you build android-4.19 Cuttlefish x86 with `-DLLVM_APPEND_VC_REV=off` clang?

**Comment by nathanchance** [comment]
Yes, I will do so right now.

**Comment by nathanchance** [comment]
Alright, these objects should have been built with a version of clang built with `-DLLVM_APPEND_VC_REV=off`.

https://1drv.ms/u/s!AsQNYeB-IEbqhx0R58-gfhL42SO3?e=pEvHpr

**Comment by nickdesaulniers** [comment]
now running into this with https://android-review.googlesource.com/c/kernel/common/+/1301638.

I wonder if this is related to https://github.com/ClangBuiltLinux/linux/issues/872, which also mentions 5b22bcc2b70d82c73ce5428170dcc2038a729d74?

**Comment by nickdesaulniers** [comment]
@samitolvanen and I are looking into this together.  Posting a status update before we go into the weekend and I forget everything.

```diff
diff --git a/arch/x86/configs/gki_defconfig b/arch/x86/configs/gki_defconfig
index ea16bd5cd458..69a79310395f 100644
--- a/arch/x86/configs/gki_defconfig
+++ b/arch/x86/configs/gki_defconfig
@@ -54,7 +54,7 @@ CONFIG_PCI_MSI=y
 CONFIG_IA32_EMULATION=y
 CONFIG_JUMP_LABEL=y
 CONFIG_LTO_CLANG=y
-CONFIG_CFI_CLANG=y
+#CONFIG_CFI_CLANG=y
 CONFIG_MODULES=y
 CONFIG_MODULE_UNLOAD=y
 CONFIG_MODVERSIONS=y
diff --git a/kernel/Makefile b/kernel/Makefile
index 278153bc4604..96d9d729d4c6 100644
--- a/kernel/Makefile
+++ b/kernel/Makefile
@@ -12,6 +12,8 @@ obj-y     = fork.o exec_domain.o panic.o \
            notifier.o ksysfs.o cred.o reboot.o \
            async.o range.o smpboot.o ucount.o
 
+subdir-ccflags-y += $(DISABLE_LTO)
+
 obj-$(CONFIG_MODULES) += kmod.o
 obj-$(CONFIG_MULTIUSER) += groups.o
```
allows this to boot.  From here, we can narrow this down further to:
1. which object file[s]
2. which functions via outlining to TUs that do/don't have LTO enabled
3. which parts of code (via outlining + `__attribute__((no_inlining))`

**Comment by nickdesaulniers** [comment]
@samitolvanen has narrowed it down to kernel/time/timer.c.

If I move the definition of `jiffies_64` into its own TU, and disable LTO there, it boots.

**Comment by nickdesaulniers** [comment]
fix in hand, will post upstream

**Comment by nickdesaulniers** [comment]
comments before sending upstream? : https://android-review.googlesource.com/c/kernel/common/+/1310377

**Comment by nathanchance** [comment]
Seems to make sense to me.

**Comment by nickdesaulniers** [comment]
submitted: https://lore.kernel.org/lkml/20200515180544.59824-1-inglorion@google.com/T/#u

**Comment by dileks** [comment]
Now in `tip.git#x86/urgent`.

[1] https://git.kernel.org/tip/d8ad6d39c35d2b44b3d48b787df7f3359381dcbf

**Comment by nickdesaulniers** [comment]
fixed: d8ad6d39c35d2b44b3d48b787df7f3359381dcbf

**Comment by nickdesaulniers** [comment]
Looks like this was backported to 4.4. 👍

**Comment by dileks** [comment]
It's in all stable-queues.
