### ISSUE TITLE
arch/arm/lib/memmove.S:86:3: error: invalid instruction

### ISSUE THREAD

**Issue by agners** [ClangBuiltLinux/linux#857]
Trying to use AS=clang and CONFIG_THUMB2_KERNEL=y leads to the following errors:

```
arch/arm/lib/memmove.S:86:3: error: invalid instruction
  ldr.w r3, [r1, #-4]!
  ^
...
arch/arm/lib/memmove.S:97:3: error: invalid instruction
  str.w r3, [r0, #-4]!
  ^
```

**Comment by agners** [comment]
@smithp35 confirmed that this seems to be a bug in LLVM/Clang.

**Comment by agners** [comment]
A small reproducer:

```
        .text
        .syntax unified 
        .thumb
        .global _start
_start:
        ldr.w r3, [r1, #-4]!
```

Test output:
```
$ arm-none-linux-gnueabihf-as repr-wrong-selection.s
$ llvm-mc -triple=armv7-linux-gnueabi repr-wrong-selection.s
        .text
        .code   16
        .globl  _start
_start:
repr-wrong-selection.s:6:2: error: invalid instruction
        ldr.w r3, [r1, #-4]!
        ^
```

**Comment by agners** [comment]
Reported upstream: https://llvm.org/pr44858

**Comment by jcai19** [comment]
Thanks for the reproducer. I'll look into a fix.

**Comment by smithp35** [comment]
My intuition, not confirmed, is that this could be an attempted match against the unsigned encoding T3 which wouldn't permit signed immediates.

**Comment by jcai19** [comment]
This issue has been tracked at https://llvm.org/pr43382. LLVM is confused by the ".w" suffix

**Comment by agners** [comment]
From what I understand it is a combination of the `.w` suffix and the addressing mode. There has been an attempt to fix this for `ldrb.w`:
https://reviews.llvm.org/D68916

**Comment by nickdesaulniers** [comment]
duping to #1296
