### ISSUE TITLE
unsupported relocation on symbol when building arm32_v5 with integrated-as enabled

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#863]
```
arch/arm/kernel/entry-common.S:-135:2: error: unsupported relocation on symbol
 adr tbl, sys_call_table @ load syscall table pointer
 ^
```
This negative line number reported is obviously incorrect. Actual line number is 227.

**Comment by smithp35** [comment]
I think this is likely to be https://llvm.org/pr44929 this is a recent regression. I've left a comment in the PR.

**Comment by MaskRay** [comment]
https://reviews.llvm.org/D72892 is a workaround before we implement the relocations.

**Comment by agners** [comment]
The above fix has been commited on master and 10.x branch (see also https://llvm.org/pr44929). I tested it here and the issues on 32-bit ARM seem to be gone. I guess we can close this then?

@MaskRay when you say the kernel probably also needs a fix, is that when the error still persists or even when it compiles that there might be still something wrong?

**Comment by smithp35** [comment]
I'd hold off for a little while as there are some changes coming. The above fix is on master mainly so it could be merged to 10.0. For 11.0 we're exposing the relocations for the linker to handle. I've just committed the Thumb Side on Master with https://reviews.llvm.org/D75042 and https://reviews.llvm.org/D75039 
I'll be posting patches for Arm today.

The kernel should ideally refer to a local label for these short range pc-relative fixups. When using a global symbol the assembler must assume the object can be used in a shared library which means the symbol can be preempted.

**Comment by nickdesaulniers** [comment]
All of the LLVM patches mentioned in this bug are merged.
1. https://reviews.llvm.org/D75039
2. https://reviews.llvm.org/D75042
3. https://reviews.llvm.org/D72892

@tpimh is this issue still reproducible for you?  Can you provide steps to reproduce?

**Comment by tpimh** [comment]
I will try to reproduce the issue in the beginning of August, but if I forget, please, ping me.

**Comment by nickdesaulniers** [comment]
ping @tpimh

**Comment by nickdesaulniers** [comment]
bump @tpimh

**Comment by tpimh** [comment]
Sorry to keep you waiting, my renovation is taking a bit longer than I first anticipated, but hopefully soon I will have access to my computer and will be able to test it. I'm pretty sure it shouldn't be reproducible any more, but still need to check.

**Comment by nickdesaulniers** [comment]
tentatively closing this.  Not sure if llvm 11 or 10 is the precise fix.
