### ISSUE TITLE
objtool failures starting with next-20200212

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#872]

**Comment by nathanchance** [comment]
I have some more information on this which I will post when my internet comes back...

**Comment by nathanchance** [comment]
Reported by CI: https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/286292010

`objtool` issues are now fatal: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=644592d328370af4b3e027b7b1ae9f81613782d8

```
$ make -j$(nproc) -s CC=clang HOSTCC=clang O=out.x86_64 distclean defconfig kernel/printk/printk.o
kernel/printk/printk.o: warning: objtool: ignore_loglevel_setup()+0x10: can't find call dest symbol at .text+0xc67
make[4]: *** [../scripts/Makefile.build:268: kernel/printk/printk.o] Error 255
make[4]: *** Deleting file 'kernel/printk/printk.o'
```

As it turns out, this is not purely related to clang but also GNU as. My host is Ubuntu 18.04, which has binutils 2.30 and it does not show the issue but Debian's 2.31.1 does. I ended up bisecting binutils to see what commit introduced the issue.

```
$ git bisect log
# bad: [af127c216949509e57ab2a28cc56c44e4e548813] 2.31 Release point
# good: [8db5daf9efe8a6174d3b10ac7bba8c178836e9ce] Update version number and development status for the 2.30 release.
git bisect start 'binutils-2_31' 'binutils-2_30'
# good: [faf766e31794722b7e2c24e44e920d0476cede32] Add note about 2.30 branch creation to changelogs
git bisect good faf766e31794722b7e2c24e44e920d0476cede32
# bad: [f50d8a2eaea045cd6e9b8d6d5cf8da55e2047ffb] Fix gdb.base/fork-running-state.exp race
git bisect bad f50d8a2eaea045cd6e9b8d6d5cf8da55e2047ffb
# bad: [6f06d47ba0965013203af25c17854c01caae5544] Class-fy partial_die_info
git bisect bad 6f06d47ba0965013203af25c17854c01caae5544
# good: [2d6dda71611ba6cc16fe2bd21ac816d5f7d1e74d] MIPS/BFD: Correctly report unsupported `.reginfo' section size
git bisect good 2d6dda71611ba6cc16fe2bd21ac816d5f7d1e74d
# bad: [d00dd7dc5e415503de88614bf2ea4aafa2bca819] Remove bfd stub function casts.
git bisect bad d00dd7dc5e415503de88614bf2ea4aafa2bca819
# good: [9c3630e983df43e68006b526a92c2a9a2b64dfd9] Don't reference past the end of the vector
git bisect good 9c3630e983df43e68006b526a92c2a9a2b64dfd9
# bad: [db7bf1058d28b2b5e931c60435a13f6db15df6af] Fix ARm assembler so that it rejects invalid immediate values for the Thumb ORR instruction.
git bisect bad db7bf1058d28b2b5e931c60435a13f6db15df6af
# good: [d2159fdc0f0ac1d0aaafab725b930e78a8793494] MIPS: Fix encoding for MIPSr6 sigrie instruction.
git bisect good d2159fdc0f0ac1d0aaafab725b930e78a8793494
# good: [6e5e9d58c1eeef5677c90886578a895cb8c164c5] PR22836, "-r -s" doesn't work with -g3 using GCC 7
git bisect good 6e5e9d58c1eeef5677c90886578a895cb8c164c5
# good: [b29d26411c62fef6b1401aff4f2c6a157053de4d] WebAssembly: Disable subdirectory configuration for unsupported LD
git bisect good b29d26411c62fef6b1401aff4f2c6a157053de4d
# good: [80c96350467f23a54546580b3e2b67a65ec65b66] Fix typo in Russian translation for the bfd/ sub-directory which could lead to a seg-fault in the linker.
git bisect good 80c96350467f23a54546580b3e2b67a65ec65b66
# bad: [bd7ab16b4537788ad53521c45469a1bdae84ad4a] x86-64: Generate branch with PLT32 relocation
git bisect bad bd7ab16b4537788ad53521c45469a1bdae84ad4a
# first bad commit: [bd7ab16b4537788ad53521c45469a1bdae84ad4a] x86-64: Generate branch with PLT32 relocation

$ git show -s
commit bd7ab16b4537788ad53521c45469a1bdae84ad4a
Author: H.J. Lu <hjl.tools@gmail.com>
Date:   Tue Feb 13 07:34:22 2018 -0800

    x86-64: Generate branch with PLT32 relocation
    
    Since there is no need to prepare for PLT branch on x86-64, generate
    R_X86_64_PLT32, instead of R_X86_64_PC32, if possible, which can be
    used as a marker for 32-bit PC-relative branches.
    
    To compile Linux kernel, this patch:
    
    From: "H.J. Lu" <hjl.tools@gmail.com>
    Subject: [PATCH] x86: Treat R_X86_64_PLT32 as R_X86_64_PC32
    
    On i386, there are 2 types of PLTs, PIC and non-PIC.  PIE and shared
    objects must use PIC PLT.  To use PIC PLT, you need to load
    _GLOBAL_OFFSET_TABLE_ into EBX first.  There is no need for that on
    x86-64 since x86-64 uses PC-relative PLT.
    
    On x86-64, for 32-bit PC-relative branches, we can generate PLT32
    relocation, instead of PC32 relocation, which can also be used as
    a marker for 32-bit PC-relative branches.  Linker can always reduce
    PLT32 relocation to PC32 if function is defined locally.   Local
    functions should use PC32 relocation.  As far as Linux kernel is
    concerned, R_X86_64_PLT32 can be treated the same as R_X86_64_PC32
    since Linux kernel doesn't use PLT.
    
    is needed.  It is available on hjl/plt32/master branch at
    
    https://github.com/hjl-tools/linux
    
    bfd/
    
            PR gas/22791
            * elf64-x86-64.c (is_32bit_relative_branch): Removed.
            (elf_x86_64_relocate_section): Check PIC relocations in PIE.
            Remove is_32bit_relative_branch usage.  Disallow PC32 reloc
            against protected function in shared object.
    
    gas/
    
            PR gas/22791
            * config/tc-i386.c (need_plt32_p): New function.
            (output_jump): Generate BFD_RELOC_X86_64_PLT32 if possible.
            (md_estimate_size_before_relax): Likewise.
            * testsuite/gas/i386/reloc64.d: Updated.
            * testsuite/gas/i386/x86-64-jump.d: Likewise.
            * testsuite/gas/i386/x86-64-mpx-branch-1.d: Likewise.
            * testsuite/gas/i386/x86-64-mpx-branch-2.d: Likewise.
            * testsuite/gas/i386/x86-64-relax-2.d: Likewise.
            * testsuite/gas/i386/x86-64-relax-3.d: Likewise.
            * testsuite/gas/i386/ilp32/reloc64.d: Likewise.
            * testsuite/gas/i386/ilp32/x86-64-branch.d: Likewise.
    
    ld/
    
            PR gas/22791
            * testsuite/ld-x86-64/mpx1c.rd: Updated.
            * testsuite/ld-x86-64/pr22791-1.err: New file.
            * testsuite/ld-x86-64/pr22791-1a.c: Likewise.
            * testsuite/ld-x86-64/pr22791-1b.s: Likewise.
            * testsuite/ld-x86-64/pr22791-2.rd: Likewise.
            * testsuite/ld-x86-64/pr22791-2a.s: Likewise.
            * testsuite/ld-x86-64/pr22791-2b.c: Likewise.
            * testsuite/ld-x86-64/pr22791-2c.s: Likewise.
            * testsuite/ld-x86-64/x86-64.exp: Run PR ld/22791 tests.
```

Not really sure where the issue lies beyond this but I can upload object files once my internet is into a better state.

cc @jpoimboe

**Comment by nathanchance** [comment]
Furthermore I ran creduce to see what it spits out, the results can be viewed here:

https://github.com/nathanchance/creduce-files/tree/d744f8ad0bce73615f32dd7b3a950186db9347e5/objtool

**Comment by nickdesaulniers** [comment]
I'm seeing this as well w/ binutils 2.33.1:

```sh
$ make CC=clang defconfig
$ make CC=clang
```

Attaching object files (.txt suffix so github will let me attach them)

[sound_core_info.o.txt](https://github.com/ClangBuiltLinux/linux/files/4195174/sound_core_info.o.txt)
[arch_x86_kernel_tsc.o.txt](https://github.com/ClangBuiltLinux/linux/files/4195179/arch_x86_kernel_tsc.o.txt)
[kernel_printk_printk.o.txt](https://github.com/ClangBuiltLinux/linux/files/4195181/kernel_printk_printk.o.txt)

Interestingly, if I do:
```sh
$ make CC=clang AS=clang -j71 arch/x86/kernel/tsc.o
```
I get no failures, so this could indeed involve binutils.  Using `clang` for `AS` for the other two object files produces other `objtool` failures, but those are orthogonal.

**Comment by nickdesaulniers** [comment]
Looking into prink.o first:
kernel/printk/printk.o: warning: objtool: ignore_loglevel_setup()+0x10: can't find call dest symbol at .text+0xc67

```sh
$ llvm-objdump -dr kernel/printk/printk.o
```

```
0000000000000249 ignore_loglevel_setup:
     249: c6 05 00 00 00 00 01          movb    $1, (%rip)
                000000000000024b:  R_X86_64_PC32        .data..read_mostly+0x3
     250: 48 c7 c7 00 00 00 00          movq    $0, %rdi
                0000000000000253:  R_X86_64_32S .rodata.str1.1+0x3a0
     257: 31 c0                         xorl    %eax, %eax
     259: e8 00 00 00 00                callq   0 <ignore_loglevel_setup+0x15>
                000000000000025a:  R_X86_64_PC32        .text+0xc63
     25e: 31 c0                         xorl    %eax, %eax
     260: c3                            retq
...
0000000000000c67 printk:
```

It looks like in this case, the check in `tools/objtool/check.c`  for `insn->call_dest->type != STT_FUNC` is failing.


Attaching gdb to objtool:
```
$ gdb ./tools/objtool/objtool
(gdb) b check.c:698
Breakpoint 1 at 0x55555555d3a0: file check.c, line 698.
(gdb) r orc generate  --no-fp --retpoline --uaccess kernel/printk/printk.o
Starting program: /android0/linux-next/tools/objtool/objtool orc generate  --no-fp --retpoline --uaccess kernel/printk/printk.o

Breakpoint 1, add_call_destinations (file=0x555555570600 <file>) at check.c:698
698				insn->call_dest = find_symbol_by_offset(rela->sym->sec,
(gbd) n
(gdb) p *insn->call_dest
$4 = {list = {next = 0x5555556157c0, prev = 0x555555617740}, hash = {next = 0x0, 
    pprev = 0x7ffff7c2b130}, sym = {st_name = 5313, st_info = 0 '\000', st_other = 0 '\000', 
    st_shndx = 1, st_value = 3175, st_size = 0}, sec = 0x7ffff7c2b010, 
  name = 0x55555560aa51 ".Lprintk$local", idx = 283, bind = 0 '\000', type = 0 '\000', 
  offset = 3175, len = 0, pfunc = 0x0, cfunc = 0x0, alias = 0x555555615100, uaccess_safe = false}

So `type` was NULL.

```sh
$ llvm-readelf -s kernel/printk/printk.o | grep printk
   283: 0000000000000c67     0 NOTYPE  LOCAL  DEFAULT     1 .Lprintk$local
   295: 0000000000000c67   110 FUNC    GLOBAL DEFAULT     1 printk
```
so there are two symbols with the address 0xc67, `.Lprintk$local` and `printk`. The `.Lprintk$local` also appeared in the gdb output...I'm unfamiliar with the mangling.  I wonder if we're accidentally producing it, or if objtool should skip those when building a symbol table...

If I dump the assembly from the clang invocation, I get:
```asm
        .globl  printk                  # -- Begin function printk
        .type   printk,@function
printk:                                 # @printk
.Lprintk$local:
...
        .type   ignore_loglevel_setup,@function # -- Begin function ignore_loglevel_setup
ignore_loglevel_setup:                  # @ignore_loglevel_setup
...
        callq   .Lprintk$local
```
So it looks like Clang emitted two symbols for the function, but did not emit a `.type` directive for the alias.  Either it probably should not emit both, or at least produce a `.type` directive for the second.

I think @MaskRay may know more about this.

**Comment by nickdesaulniers** [comment]
I suspect this was regressed by https://github.com/llvm/llvm-project/commit/5b22bcc2b70d82c73ce5428170dcc2038a729d74 (cc @rnk) (testing that theory now)

**Comment by MaskRay** [comment]
It looks like objtool makes a unnecessary restriction. The referencing symbol of an R_X86_64_PLT32 (GNU as started to emit it instead of R_X86_64_PC32 after hjl's bd7ab16b4537788ad53521c45469a1bdae84ad4a)

**Comment by nickdesaulniers** [comment]
I mean, I think they're both wrong.  Clang should not emit a symbol with STT_NOTYPE and then use it as a jump target; it should at least additionally emit `.type L<func>$local,@function`.  And then `objtool` shouldn't assume that there's only one symbol name per value (since two labels could refer to the same instruction, as in this case). `find_symbol_containing` (in objtool) iterates until it finds the first symbol at that given offset, but there may be more than one symbol at that offset.

```
(gdb) b check.c:698
Breakpoint 1 at 0x55555555d3a0: file check.c, line 698.
(gdb) r orc generate  --no-fp --retpoline --uaccess kernel/printk/printk.o
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /android0/linux-next/tools/objtool/objtool orc generate  --no-fp --retpoline --uaccess kernel/printk/printk.o

Breakpoint 1, add_call_destinations (file=0x555555570600 <file>) at check.c:698
698				insn->call_dest = find_symbol_by_offset(rela->sym->sec,
(gdb) s
find_symbol_by_offset (sec=0x7ffff7c2b010, offset=3175) at elf.c:64
64		list_for_each_entry(sym, &sec->symbol_list, list)
(gdb) watch sym->offset == offset
Watchpoint 2: sym->offset == offset
(gdb) c
Continuing.

Watchpoint 2: sym->offset == offset

Old value = 0
New value = 1
0x000055555555f27f in find_symbol_by_offset (sec=0x7ffff7c2b010, offset=3175) at elf.c:64
64		list_for_each_entry(sym, &sec->symbol_list, list)
(gdb) p sym->name
$40 = 0x55555560aa51 ".Lprintk$local"
(gdb) p sym->offset
$41 = 3175
(gdb) set sym->offset = 0
(gdb) c
Continuing.

Watchpoint 2: sym->offset == offset

Old value = 0
New value = 1
0x000055555555f27f in find_symbol_by_offset (sec=0x7ffff7c2b010, offset=3175) at elf.c:64
64		list_for_each_entry(sym, &sec->symbol_list, list)
(gdb) p sym->offset
$45 = 3175
(gdb) p sym->name
$46 = 0x555555609860 "printk"
```

(reverting https://reviews.llvm.org/rG5b22bcc2b70d82c73ce5428170dcc2038a729d74 causes the `callq printk` to be emitted, but there is still `.Lprintk$local:` emitted.)

**Comment by nathanchance** [comment]
That same commit causes #852, I wonder if these two issues are related

**Comment by jpoimboe** [comment]
It seems odd that a ".L" local symbol would be showing up in the symbol table.  From the gas manual:

Local Symbol Names

A local symbol is any symbol beginning with certain local label prefixes. By default, the local label prefix is ‘.L’ for ELF systems or ‘L’ for traditional a.out systems, but each target may have its own set of local label prefixes. On the HPPA local symbols begin with ‘L$’.

Local symbols are defined and used within the assembler, but they are normally not saved in object files. Thus, they are not visible when debugging. You may use the ‘-L’ option (see Include Local Symbols) to retain the local symbols in the object files.

**Comment by nickdesaulniers** [comment]
> It seems odd that a ".L" local symbol would be showing up in the symbol table.

Given @nathanchance 's [reproducer](https://github.com/nathanchance/creduce-files/blob/d744f8ad0bce73615f32dd7b3a950186db9347e5/objtool/printk.i):

```sh
$ clang -no-integrated-as printk.i -c -o printk.o 2> /dev/null
$ llvm-readelf -s printk.o | grep La
     9: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT     1 .La$local
$ clang printk.i -c -o printk.o 2> /dev/null
$ llvm-readelf -s printk.o | grep La
```

So GAS is keeping the local symbol around.  Test case:

```asm
# printk.i
	.text
	.section	.init.text,"ax",@progbits
b:                                      # @b
.Lb$local:
	callq	.La$local
	retq
	.text
	.globl	a                       # -- Begin function a
	.type	a,@function
a:                                      # @a
.La$local:
	retq
```
```sh
$ as printk.s
$ readelf -s a.out | grep La
     6: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT    1 .La$local
$ clang printk.s -o a.out -c
$ readelf -s a.out | grep La
```

@jpoimboe can we please drop https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=644592d328370af4b3e027b7b1ae9f81613782d8 until this is resolved?

**Comment by nickdesaulniers** [comment]
Otherwise, I can work around this in objtool:
```diff
diff --git a/tools/objtool/elf.c b/tools/objtool/elf.c
index edba4745f25a..aac55899e7b4 100644
--- a/tools/objtool/elf.c
+++ b/tools/objtool/elf.c
@@ -63,8 +63,11 @@ struct symbol *find_symbol_by_offset(struct section *sec, unsigned long offset)
 
        list_for_each_entry(sym, &sec->symbol_list, list)
                if (sym->type != STT_SECTION &&
-                   sym->offset == offset)
+                   sym->offset == offset) {
+                       if (strstr(sym->name, ".L") == sym->name)
+                               continue;
                        return sym;
+               }
 
        return NULL;
 }
```
(which might be faster to ship a fix than get bintutils fixed and distributed).

I also have a patch for llvm to emit to emit `.type .L<func>$local,@function` assembler attributes, but this causes other validation failures for objtool (since they don't have sizes, and appear to fall through into the extern symbol's instruction stream).

**Comment by MaskRay** [comment]
GNU as patch: https://sourceware.org/ml/binutils/2020-02/msg00243.html

> I also have a patch for llvm to emit to emit .type .L<func>$local,@function assembler attributes, but this causes other validation failures for objtool (since they don't have sizes, and appear to fall through into the extern symbol's instruction stream).

Local symbols generally don't need st_type. ARM/MIPS relocations can behave differently with st_type==STT_FUNC and st_type!=STT_FUNC. I'm inclined to not add st_type.

I think the best way forward is to teach objtool to not warn on R_X86_64_PLT32 referencing a `.L` symbol.

**Comment by jpoimboe** [comment]
@nickdesaulniers I'm ok with teaching objtool to ignore ".L" symbols.  Does that solve all your issues or do you also need me to revert the 'Fail the kernel build on fatal errors' commit?

**Comment by nickdesaulniers** [comment]
Kernel patch sent: https://lore.kernel.org/lkml/20200213184708.205083-1-ndesaulniers@google.com/T/#u

@jpoimboe , in testing allyesconfig, I'm hitting #873 and #874 . #876 has some warnings that are nonfatal.

If you have cycles to help us debug #873 and #874 to see whether we have a compiler bug, or a fix for objtool, that might better inform us whether the fatal error patch should be reverted or not.

**Comment by jpoimboe** [comment]
@nickdesaulniers I'll revert the fatal error upgrade patch tomorrow-ish.  Will also try to take a look at the issues you pointed out.

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/lkml/87sgjeghal.fsf@nanos.tec.linutronix.de/

**Comment by nickdesaulniers** [comment]
[arch_x86_entry_entry_64.o.txt](https://github.com/ClangBuiltLinux/linux/files/4206051/arch_x86_entry_entry_64.o.txt)

**Comment by nickdesaulniers** [comment]
patches: https://lore.kernel.org/r/cover.1581997059.git.jpoimboe@redhat.com/

**Comment by dileks** [comment]
Patchset now in `tip.git#core/objtool`:
```
objtool: Fix clang switch table edge case
objtool: Improve call destination function detection
```
[1] https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=core/objtool&id=113d4bc9048336ba7c3d2ad972dbad4aef6e148a
[2] https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=core/objtool&id=7acfe5315312fc56c2a94c9216448087b38ae909

**Comment by nathanchance** [comment]
Josh's series is in next-20200223 so this issue is fixed.

**Comment by nickdesaulniers** [comment]
thanks @jpoimboe !
