### ISSUE TITLE
-Wshift-overflow in arch/mips/pci/pci-rc32434.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#877]
Reproducible with rb532_defconfig (mips32_be):
```
arch/mips/pci/pci-rc32434.c:41:2: warning: signed shift result (0x90000000000) requires 44 bits to represent, but 'int' only has 32 bits [-Wshift-overflow]
        KORINA_CNFG1, KORINA_CNFG2, KORINA_CNFG3, KORINA_CNFG4,
        ^~~~~~~~~~~~
./arch/mips/include/asm/mach-rc32434/pci.h:380:36: note: expanded from macro 'KORINA_CNFG1'
#define KORINA_CNFG1            ((KORINA_STAT<<16)|KORINA_CMD)
                                  ~~~~~~~~~~~^ ~~
1 warning generated.
```

**Comment by nickdesaulniers** [comment]
I can still reproduce this issue. We could convert `korina_cnfg_regs` to be `unsigned long long`, but the use of it to assign to `struct pci_reg.pcicfgd` would need to be changed as well. Probably should reach out to the author of 
commit 73b4390fb2345 ("[MIPS] Routerboard 532: Support for base system")

**Comment by nathanchance** [comment]
https://git.kernel.org/linus/109d587a4b4d7ccca2200ab1f808f43ae23e2585
