### ISSUE TITLE
error: unknown argument: '-mexplicit-relocs'

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#890]
Reported by CI: https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/288021406

Patch submitted: https://lore.kernel.org/lkml/20200217211149.44132-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/mips/linux.git/commit/?h=mips-fixes&id=72cf3b3df423c1bbd8fa1056fed009d3a260f8a9

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/next/linux-next/c/72cf3b3df423c1bbd8fa1056fed009d3a260f8a9
