### ISSUE TITLE
-Wtautological-compare in kernel/extable.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#892]
```
../kernel/extable.c:37:52: warning: array comparison always evaluates to a constant [-Wtautological-compare]
        if (main_extable_sort_needed && __stop___ex_table > __start___ex_table) {
                                                          ^
1 warning generated.
```

**Comment by nathanchance** [comment]
Patch sent: https://lore.kernel.org/lkml/20200219202036.45702-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment]
akpm accepted this.
"This patch should soon appear at
    http://ozlabs.org/~akpm/mmots/broken-out/kernel-extable-use-address-of-operator-on-section-symbols.patch
and later at
    http://ozlabs.org/~akpm/mmotm/broken-out/kernel-extable-use-address-of-operator-on-section-symbols.patch"

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/63174f61dfaef58dc0e813eaf6602636794f8942
