### ISSUE TITLE
ld.lld: error: discarding .shstrtab section is not allowed

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#899]
Reported upstream, see that for more context: https://lore.kernel.org/lkml/20200222050845.GA19912@ubuntu-m2-xlarge-x86/

**Comment by nickdesaulniers** [comment]
Arvind just submitted patches for this:

https://lore.kernel.org/lkml/20200222235709.GA3786197@rani.riverdale.lan/T/#mb2afd386933b4423dce5a883514905e760a8148c

**Comment by nathanchance** [comment]
Arvind’s series has been picked up:

https://git.kernel.org/tip/003602ad5516e59940de42e44c8d8033387bb363

https://git.kernel.org/tip/6f8f0dc980028e98ae339876a8403edae4d20e39

**Comment by nathanchance** [comment]
Fixed in next-20200227.
