### ISSUE TITLE
invalid -fmerge-all-constants

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#9]
see: https://lkml.org/lkml/2018/3/20/872
https://bugs.llvm.org/show_bug.cgi?id=18538#c16
https://lkml.org/lkml/2018/4/4/601

**Comment by nickdesaulniers** [comment]
this has been fixed in clang 6.0.1: https://reviews.llvm.org/rL329300

**Comment by nickdesaulniers** [comment]
We may want to revert the kernel patch or make it work for better based on clang version.

**Comment by nickdesaulniers** [comment]
The code from the patch from the very first link can now be wrapped in clang version > 6.0.1 checks.

**Comment by nickdesaulniers** [comment]
We can revert this if we set the base version of clang for the compiler to clang-9. We should maybe avoid such a backport.

**Comment by nickdesaulniers** [comment]
revert sent: https://lore.kernel.org/lkml/20200901002326.1137289-1-ndesaulniers@google.com/T/#m8486e7513f25d71ea59cd4fc4db0be6c7365a08d

**Comment by nathanchance** [comment]
Fixed now that we only support LLVM 10.0.1 and later: https://git.kernel.org/linus/4c207c50ea35abf98f087bbcda8c95b23c4bb3b1
