### ISSUE TITLE
audit as-instr

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#904]
there seem to be two as-instr's:

```
scripts/Kbuild.include
110:# as-instr
111:# Usage: cflags-y += $(call as-instr,instr,option1,option2)
113:as-instr = $(call try-run,\

scripts/Kconfig.include
34:# $(as-instr,<instr>)
36:as-instr = $(success,printf "%b\n" "$(1)" | $(CC) $(CLANG_FLAGS) -c -x assembler -o /dev/null -)
```
I should check that they work correctly; on the second seems to use CLANG_FLAGS.  cc @masahir0y

**Comment by agners** [comment]
Just used the implementation in `scripts/Kbuild.include` for a Makefile to fix an assembler issue for ARM, it seems to work here: https://github.com/ClangBuiltLinux/linux/commit/3c8127839ced991fadb08c0a5a7beebb3ff489af

**Comment by masahir0y** [comment]
> I should check that they work correctly; on the second seems to use CLANG_FLAGS.

CFLANG_FLAGS is needed to pass the target triple etc.

It is included in KBUILD_CFLAGS, so the one in
scripts/Kbuild.include also takes it into account.

    config AS_HAS_VMRS_FPINST
            def_bool $(as-instr,.fpu vfpv2\nvmrs r0$(comma)FPINST)

Doesn't this work for you?

**Comment by agners** [comment]
@masahir0y are Kbuild tests preferred today over Makefile tests? Personally I prefer the Makefile test as it does not pollute the kernel configs.

**Comment by masahir0y** [comment]
@agners I did not mean that. I reacted to Nick's comment "I should check that they work correctly". I want to make sure either way works.

**Comment by nickdesaulniers** [comment]
ah right, I see that `CLANG_FLAGS` get included in `BUILD_AFLAGS`.
