### ISSUE TITLE
error: invalid operand for instruction in arch/arm/vfp/vfpmodule.c

### ISSUE THREAD

**Issue by agners** [ClangBuiltLinux/linux#905]
Clang warns when compiling `arch/arm/vfp/vfpmodule.c` with integrated assembler:

```
arch/arm/vfp/vfpmodule.c:342:2: error: invalid operand for instruction
        fmxr(FPEXC, fpexc & ~(FPEXC_EX|FPEXC_DEX|FPEXC_FP2V|FPEXC_VV|FPEXC_TRAP_MASK));
        ^
arch/arm/vfp/vfpinstr.h:79:6: note: expanded from macro 'fmxr'
        asm("mcr p10, 7, %0, " vfpreg(_vfp_) ", cr0, 0 @ fmxr   " #_vfp_ ", %0" \
            ^
<inline asm>:1:6: note: instantiated into assembly here
        mcr p10, 7, r0, cr8, cr0, 0 @ fmxr      FPEXC, r0
            ^
```
This has been previously tracked by #306, but since this can be solved separately lets use a separate issue. It is not technically a bug in Linux, but it should be straight forward to solve the issue in Linux.

**Comment by agners** [comment]
Patch submitted: https://lore.kernel.org/m/8bb16ac4b15a7e28a8e819ef9aae20bfc3f75fbc.1582266841.git.stefan@agner.ch

**Comment by agners** [comment]
Sent a new patch set which tackles this:
https://lore.kernel.org/lkml/3c8127839ced991fadb08c0a5a7beebb3ff489af.1583360296.git.stefan@agner.ch/

**Comment by nickdesaulniers** [comment]
Looks like these got merged/accepted: https://www.arm.linux.org.uk/developer/patches/section.php?section=20&page=133

**Comment by nickdesaulniers** [comment]
merged:
1. https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a6c30873ee4a5cc0549c1973668156381ab2c1c4
2. https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ee440336e5ef977c397afdb72cbf9c6b8effc8ea
3. https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2cbd1cc3dcd3e84be1fc1987da24b190ddf24a70

Closing. @agners if there's more to do here, please reopen.  Thanks for all of the work that went into these patches!
