### ISSUE TITLE
work queues compare worker function but this may mismatch when used from modules

### ISSUE THREAD

**Issue by kees** [ClangBuiltLinux/linux#907]
When a work queue is built from a module, the module's view of the function pointer for delayed_work_timer_fn() (in the main kernel .text) will differ in visibility in the module (since it points to the module's jump table for the function). Therefore direct tests of equality will fail.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/workqueue.c?h=v5.5#n1622

`	WARN_ON_ONCE(timer->function != delayed_work_timer_fn);
`
Workaround is to disable this warning. To get this functionality back, some invasive changes will be needed...

**Comment by nathanchance** [comment]
Current solution: https://lore.kernel.org/lkml/20210408182843.1754385-6-samitolvanen@google.com/

Will the invasive changes ever come or is it worth closing this up?

**Comment by kees** [comment]
There is a workaround in place currently, and the future KCFI work will make this a non-issue.
https://lore.kernel.org/linux-hardening/20220429203644.2868448-12-samitolvanen@google.com/T/#u
