### ISSUE TITLE
error: invalid instruction (adrl) arch/arm/crypto/sha512-core.S/sha256-core.S

### ISSUE THREAD

**Issue by agners** [ClangBuiltLinux/linux#911]
Building with Clangs integrated assembler leads to:

```
  AS [M]  arch/arm/crypto/sha256-core.o
  AS [M]  arch/arm/crypto/sha512-core.o
arch/arm/crypto/sha512-core.S:546:2: error: invalid instruction, did you mean: adr?
 adrl r3,K512
 ^
arch/arm/crypto/sha256-core.S:1888:2: error: invalid instruction, did you mean: adr?
 adrl r14,K256
 ^
```

There is already a similar case #430, but those two cases probably will need separate fixes.

There is already quite some resources about `adrl`, and this issue even has work around for this particular sha256 implementations (from OpenSSL):
https://bugs.llvm.org/show_bug.cgi?id=24350

**Comment by nickdesaulniers** [comment]
duping to #430
