### ISSUE TITLE
save_stack_trace() broken with CONFIG_FRAME_POINTER

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#912]
`Reported-by: Miles Chen <Miles.Chen@mediatek.com>`

cc @milesdotchen 

It looks like `unwind_frame()` is making the same non portable assumptions about the order that caller saved registers are pushed on the stack that we had to fix in backtrace-clang.S.  If unwind_frame() just needs fp, sp, and lr, then we can probably refactor out the logic in backtrace-clang.S (the first five labels after `for_each_frame`) which should give us what we want, and reuse that.

**Comment by luislinaro** [comment]
Nick, i investigated this briefly and the standard doesn't define a specific ordering for saving caller-saved registers. Checking backtrace-clang.S and unwind_frame(), i agree with your assessment of the problem.

**Comment by nickdesaulniers** [comment]
This seems like the most detailed report of the various issues I can find: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92172

**Comment by Nathan-Huckleberry** [comment]
Patch submitted https://lore.kernel.org/lkml/20200616223633.73971-1-nhuck@google.com/T/#u

**Comment by nickdesaulniers** [comment]
accepted: https://www.arm.linux.org.uk/developer/patches/viewpatch.php?id=8992/1

**Comment by nickdesaulniers** [comment]
merged: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b4d5ec9b39f8b31d98f65bc5577b5d15d93795d7
