### ISSUE TITLE
__compiletime_assert_184 in intel_workarounds.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#918]
via [ci](https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/293826383?utm_medium=notification&utm_source=email):
```
ld.lld-11: error: undefined symbol: __compiletime_assert_184
>>> referenced by intel_workarounds.c
>>>               gpu/drm/i915/gt/intel_workarounds.o:(intel_engine_init_workarounds) in archive drivers/built-in.a
>>> referenced by intel_workarounds.c
>>>               gpu/drm/i915/gt/intel_workarounds.o:(intel_engine_init_workarounds) in archive drivers/built-in.a
```

**Comment by nickdesaulniers** [comment]
It looks like `_MASKED_FIELD` is related, the first 2 BCP related asserts are failing.
```c
  263 #define _MASKED_FIELD(mask, value) ({            \                              
  264   if (__builtin_constant_p(mask))            \                                  
  265     BUILD_BUG_ON_MSG(((mask) & 0xffff0000), "Incorrect mask"); \                
  266   if (__builtin_constant_p(value))           \                                  
  267     BUILD_BUG_ON_MSG((value) & 0xffff0000, "Incorrect value"); \                
  268   if (__builtin_constant_p(mask) && __builtin_constant_p(value))     \          
  269     BUILD_BUG_ON_MSG((value) & ~(mask),        \                                
  270          "Incorrect value for mask");      \                                    
  271   __MASKED_FIELD(mask, value); })
```

via the call to `wa_masked_en(wal, UNSLICE_UNIT_LEVEL_CLKGATE2, VSUNIT_CLKGATE_DIS_TGL);` in `rcs_engine_wa_init`. I haven't tested `REG_BIT`'s `BUILD_BUG_ON_ZERO`.

**Comment by nickdesaulniers** [comment]
Seems to be from commit 50148a25f841 ("drm/i915/tgl: Move and restrict Wa_1408615072").

**Comment by nickdesaulniers** [comment]
Not sure this is the precise issue, but with creduce spat out:
```c
a() {
  int b;
  if (__builtin_constant_p(b))
    __compiletime_assert_184();
}
```
as a difference between GCC and Clang. cc @jyknight @gwelymernans 
[intel_workarounds.i.orig.txt](https://github.com/ClangBuiltLinux/linux/files/4294314/intel_workarounds.i.orig.txt)
[test.sh.txt](https://github.com/ClangBuiltLinux/linux/files/4294315/test.sh.txt)

**Comment by nickdesaulniers** [comment]
So I think part of why this happens is that clang is inlining `wa_masked_en` into `rcs_engine_wa_init`, which gives it further visibility into the constant check. (when I manually inline all callees of `wa_masked_en` into it, we can still repro. Once I manually inline `wa_masked_en` into `rcs_engine_wa_init`, then the differences between compilers disappear). GCC does not make the same inlining decision, so the `__builtin_constant_p` check fails in GCC, and not in Clang.  Thus GCC doesn't run the `BUILD_BUG_ON_MSG` validation.

So I think there's likely a bug in the source code; it's just that GCC made different inlining decisions, so the `__builtin_constant_p` check in `_MASKED_FIELD` (called via `_MASKED_BIT_ENABLE` via `wa_masked_en` doesn't run).

I just need to figure out what the value of
```c
(unsigned int)( ((((1UL))) << (19)) + ( (int)( sizeof(struct { int:( -!!(( sizeof(int) == sizeof(      *(8 ? ((void *)((long)(19) * 0l)) : (int *)8))) && ((19) < 0 || (19) > 31))); }))));

```
is, and why it fails the `BUILD_BUG_ON_MSG`.

Looks like both compilers agree that it's `0x80000`. https://godbolt.org/z/w6ErLH

So the checks: `(mask) & 0xffff0000)` and `(value) & 0xffff0000` (`_MASKED_BIT_ENABLE` passes the same value twice for `mask` and `value` parameters of `_MASKED_FIELD`) will fail.

**Comment by nickdesaulniers** [comment]
Author contacted: https://lore.kernel.org/intel-gfx/20200305190811.3009-1-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment]
submitted: https://lore.kernel.org/intel-gfx/20200305202435.1284242-1-matthew.d.roper@intel.com/T/#u

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/next/linux-next/c/dbe748cd3af4a7c264a94e3e7c56a084dbd0164d
