### ISSUE TITLE
'arm7m' is not a recognized processor for this target (ignoring processor)

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#921]
Reported-by: kernelci.org bot <bot@kernelci.org>

rpc_defconfig defconfig fails with lots of errors:
```
'arm7m' is not a recognized processor for this target (ignoring processor)
```

Not sure who's setting that, but `V=1` shows that `-march=armv3m` is getting set...

**Comment by nickdesaulniers** [comment]
literally just `clang  --target=arm-linux-gnueabihf -march=armv3m -c foo.c ` on an empty C file prints that warning 8 times.

**Comment by nickdesaulniers** [comment]
using -march=armv4m prints the error: clang-13: error: the clang compiler does not support '-march=armv4m'

**Comment by nickdesaulniers** [comment]
cc @DavidSpickett

**Comment by DavidSpickett** [comment]
(I had my email rules wrong so I missed this)

Very strange:
```
$ ./bin/clang --target=arm-linux-gnueabihf -march=armv2m -c /tmp/test.c -o /tmp/test.o
clang-13: error: the clang compiler does not support '-march=armv2m'
$ ./bin/clang --target=arm-linux-gnueabihf -march=armv3m -c /tmp/test.c -o /tmp/test.o
'arm7m' is not a recognized processor for this target (ignoring processor)
'arm7m' is not a recognized processor for this target (ignoring processor)
'arm7m' is not a recognized processor for this target (ignoring processor)
'arm7m' is not a recognized processor for this target (ignoring processor)
'arm7m' is not a recognized processor for this target (ignoring processor)
'arm7m' is not a recognized processor for this target (ignoring processor)
'arm7m' is not a recognized processor for this target (ignoring processor)
'arm7m' is not a recognized processor for this target (ignoring processor)
$ ./bin/clang --target=arm-linux-gnueabihf -march=armv4m -c /tmp/test.c -o /tmp/test.o
clang-13: error: the clang compiler does not support '-march=armv4m'
```

Something about 3. I'll look at this today and at least raise an llvm bug.

**Comment by DavidSpickett** [comment]
Opened https://llvm.org/pr50454

For now the fix for your build is, well, don't pass armv3m if you don't want warnings. (unless there is an effort to actually build for that) I don't think it'll change codegen though.

I'll clean these up on the llvm side so that in future this is either a hard error "does not support" or it recognises the CPU. Depends on whether they're actually real CPUs.

**Comment by DavidSpickett** [comment]
The llvm bug covers a few CPU discrepancies I found, https://reviews.llvm.org/D103028 will fix this specifically.

**Comment by DavidSpickett** [comment]
Fixed by https://reviews.llvm.org/rGf4543dce5db585f2b37f39145ad3fa34b6c75b0e.

**Comment by nickdesaulniers** [comment]
big thanks @DavidSpickett !
