### ISSUE TITLE
unrecognized instruction mnemonic in arch/arm64/include/asm/alternative.h

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#924]
```
<instantiation>:2:2: error: unrecognized instruction mnemonic
 _ASM_EXTABLE 9999b, 9f
 ^
arch/arm64/mm/cache.S:50:1: note: while in macro instantiation
user_alt 9f, "dc cvau, x4", "dc civac, x4", 0
^
```
Defined here: https://github.com/ClangBuiltLinux/linux/blob/067ba54c7a7d4cb76da4c8434bd6f117b61ac8ee/arch/arm64/include/asm/alternative.h#L224

**Comment by ihalip** [comment]
Seems that case matters for clang, but not for as. Fix seems dead easy:
```diff
diff --git a/arch/arm64/include/asm/alternative.h b/arch/arm64/include/asm/alternative.h
index 324e7d5ab37e..5e5dc05d63a0 100644
--- a/arch/arm64/include/asm/alternative.h
+++ b/arch/arm64/include/asm/alternative.h
@@ -221,7 +221,7 @@ alternative_endif
 
 .macro user_alt, label, oldinstr, newinstr, cond
 9999:  alternative_insn "\oldinstr", "\newinstr", \cond
-       _ASM_EXTABLE 9999b, \label
+       _asm_extable 9999b, \label
 .endm
 
 /*
```

**Comment by ihalip** [comment]
https://lore.kernel.org/linux-arm-kernel/20200319214530.2046-1-ilie.halip@gmail.com/T/#u

**Comment by nickdesaulniers** [comment]
Reported upstream, too: https://llvm.org/pr45257

**Comment by nathanchance** [comment]
https://git.kernel.org/arm64/c/6f5459da2b8736720afdbd67c4bd2d1edba7d0e3

**Comment by jcai19** [comment]
I also filed an LLVM upstream review request at https://reviews.llvm.org/D76719 to support case-insensitive .macros, although there's disagreement on whether we should add the support. Some links: http://lists.llvm.org/pipermail/llvm-dev/2020-February/138955.html
http://lists.llvm.org/pipermail/llvm-dev/2020-February/138937.html

**Comment by nickdesaulniers** [comment]
(Removing the `[FIXED][LINUX] -next` tag; undocumented semantics of it: it's used when we fix an issue before it hits mainline.  Since this is a long standing pre-existing issue, we want to use a fixed tag once the patch hits mainline, that specifies the first tag the fix landed in so that when we hit this again on LTS branches we know where to look for the fix).

**Comment by ihalip** [comment]
Sorry for the confustion.

**Comment by nickdesaulniers** [comment]
It's my fault; my own undocumented semantics. Join our bi-weekly call in 4 minutes if you wan't to talk more about it!

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/6f5459da2b8736720afdbd67c4bd2d1edba7d0e3

**Comment by nathanchance** [comment]
Removing the LLVM label since it seems like this is considered WONTFIX up there (which is fine, there don’t appear to be any other instances of this so far).
