### ISSUE TITLE
arch/x86/entry/entry_64_compat.S: Assertion `OS.tell() - Start == Layout.getSectionAddressSize(Sec)' failed

### ISSUE THREAD

**Issue by jcai19** [ClangBuiltLinux/linux#929]
clang: /path/to/llvm-project/llvm/lib/MC/MCAssembler.cpp:720: void llvm::MCAssembler::writeSectionData(llvm::raw_ostream&, const llvm::MCSection*, const llvm::MCAsmLayout&) const: Assertion `OS.tell() - Start == Layout.getSectionAddressSize(Sec)' failed.
Stack dump:
0.	Program arguments: /path/to/llvm-project/build/debug/bin/clang -cc1as -triple x86_64-unknown-linux-gnu -filetype obj -main-file-name entry_64_compat.S -target-cpu x86-64 -I ./arch/x86/include -I ./arch/x86/include/generated -I ./include -I ./arch/x86/include/uapi -I ./arch/x86/include/generated/uapi -I ./include/uapi -I ./include/generated/uapi -fdebug-compilation-dir /path/to/linux -dwarf-debug-producer clang version 11.0.0 (https://github.com/llvm/llvm-project.git cfff4851acc5132c8dcaebca6af92f817e133d66) -I ./arch/x86/include -I ./arch/x86/include/generated -I ./include -I ./arch/x86/include/uapi -I ./arch/x86/include/generated/uapi -I ./include/uapi -I ./include/generated/uapi -dwarf-version=4 -mrelocation-model static -o arch/x86/entry/entry_64_compat.o entry_64_compat-8fd4cb.s 
 #0 0x000055bd0305f058 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /path/to/llvm-project/llvm/lib/Support/Unix/Signals.inc:564:22
 #1 0x000055bd0305f0eb PrintStackTraceSignalHandler(void*) /path/to/llvm-project/llvm/lib/Support/Unix/Signals.inc:625:1
 #2 0x000055bd0305d190 llvm::sys::RunSignalHandlers() /path/to/llvm-project/llvm/lib/Support/Signals.cpp:68:20
 #3 0x000055bd0305ea9a SignalHandler(int) /path/to/llvm-project/llvm/lib/Support/Unix/Signals.inc:406:1
 #4 0x00007f9a1f81f520 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x13520)
 #5 0x00007f9a1f2fa081 raise /build/glibc-G5rUEF/glibc-2.29/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #6 0x00007f9a1f2e5535 abort /build/glibc-G5rUEF/glibc-2.29/stdlib/abort.c:81:7
 #7 0x00007f9a1f2e540f _nl_load_domain /build/glibc-G5rUEF/glibc-2.29/intl/loadmsgcat.c:1177:9
 #8 0x00007f9a1f2f2b92 (/lib/x86_64-linux-gnu/libc.so.6+0x32b92)
 #9 0x000055bd02b51f10 llvm::MCAssembler::writeSectionData(llvm::raw_ostream&, llvm::MCSection const*, llvm::MCAsmLayout const&) const /path/to/llvm-project/llvm/lib/MC/MCAssembler.cpp:711:5
#10 0x000055bd02bff447 (anonymous namespace)::ELFWriter::writeSectionData(llvm::MCAssembler const&, llvm::MCSection&, llvm::MCAsmLayout const&) /path/to/llvm-project/llvm/lib/MC/ELFObjectWriter.cpp:859:5
#11 0x000055bd02c00458 (anonymous namespace)::ELFWriter::writeObject(llvm::MCAssembler&, llvm::MCAsmLayout const&) /path/to/llvm-project/llvm/lib/MC/ELFObjectWriter.cpp:1104:25
#12 0x000055bd02bfd0e8 (anonymous namespace)::ELFSingleObjectWriter::writeObject(llvm::MCAssembler&, llvm::MCAsmLayout const&) /path/to/llvm-project/llvm/lib/MC/ELFObjectWriter.cpp:297:21
#13 0x000055bd02b52db6 llvm::MCAssembler::Finish() /path/to/llvm-project/llvm/lib/MC/MCAssembler.cpp:871:62
#14 0x000055bd02ba439a llvm::MCObjectStreamer::FinishImpl() /path/to/llvm-project/llvm/lib/MC/MCObjectStreamer.cpp:778:1
#15 0x000055bd02b8814d llvm::MCELFStreamer::FinishImpl() /path/to/llvm-project/llvm/lib/MC/MCELFStreamer.cpp:677:1
#16 0x000055bd02baf177 llvm::MCStreamer::Finish() /path/to/llvm-project/llvm/lib/MC/MCStreamer.cpp:965:1
#17 0x000055bd02c10666 (anonymous namespace)::AsmParser::Run(bool, bool) /path/to/llvm-project/llvm/lib/MC/MCParser/AsmParser.cpp:993:10
#18 0x000055bd00829638 ExecuteAssembler((anonymous namespace)::AssemblerInvocation&, clang::DiagnosticsEngine&) /path/to/llvm-project/clang/tools/driver/cc1as_main.cpp:531:25
#19 0x000055bd00829dfc cc1as_main(llvm::ArrayRef<char const*>, char const*, void*) /path/to/llvm-project/clang/tools/driver/cc1as_main.cpp:617:42
#20 0x000055bd00814f72 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) /path/to/llvm-project/clang/tools/driver/driver.cpp:330:22
#21 0x000055bd008155d4 main /path/to/llvm-project/clang/tools/driver/driver.cpp:402:26
#22 0x00007f9a1f2e6bbb __libc_start_main /build/glibc-G5rUEF/glibc-2.29/csu/../csu/libc-start.c:342:3
#23 0x000055bd0081377a _start (/path/to/llvm-project/build/debug/bin/clang+0x281877a)
./reproduce.sh: line 17: 40657 Aborted                 "/path/to/llvm-project/build/debug/bin/clang" "-cc1as" "-triple" "x86_64-unknown-linux-gnu" "-filetype" "obj" "-main-file-name" "entry_64_compat.S" "-target-cpu" "x86-64" "-I" "./arch/x86/include" "-I" "./arch/x86/include/generated" "-I" "./include" "-I" "./arch/x86/include/uapi" "-I" "./arch/x86/include/generated/uapi" "-I" "./include/uapi" "-I" "./include/generated/uapi" "-fdebug-compilation-dir" "/path/to/linux" "-dwarf-debug-producer" "clang version 11.0.0 (https://github.com/llvm/llvm-project.git cfff4851acc5132c8dcaebca6af92f817e133d66)" "-I" "./arch/x86/include" "-I" "./arch/x86/include/generated" "-I" "./include" "-I" "./arch/x86/include/uapi" "-I" "./arch/x86/include/generated/uapi" "-I" "./include/uapi" "-I" "./include/generated/uapi" "-dwarf-version=4" "-mrelocation-model" "static" "-o" "arch/x86/entry/entry_64_compat.o" "entry_64_compat-8fd4cb.s"

**Comment by jcai19** [comment]
Dug around a little bit and turned out a FT_FILL fragment is somehow skipped when calculating the offsets of fragments in section .entry.text. The immediately following fragment (of FT_DATA kind) of the problematic fragment has the same offset within the enclosing section (returned by Layout.getFragmentOffset(const MCFragment *F)). Counting the size of the FT_FILL fragment should fix the assertion failure. It is not clear why the offset is ignored though. Need to investigate further.

**Comment by jcai19** [comment]
cc @nickdesaulniers

**Comment by jcai19** [comment]
cc @m-gupta

**Comment by jcai19** [comment]
The cause was due to a macro ALTERNATIVE.
I was able to reduce the reproducer to the following code
$ cat bad.s 
.macro ALTERNATIVE newinstr
 .skip 144f-143f,0x0
 .pushsection .altinstr_replacement,"ax"
143:
 \newinstr
144:
 .popsection
.endm

 .section .entry.text, "ax"
  ALTERNATIVE "jmp .Lint80_keep_stack"
.Lint80_keep_stack:

$ gcc -c bad.s
$ echo $?
0

$ clang -c bad.s
clang-11: /usr/local/google/home/jiancai/storage/llvm-project/llvm/lib/MC/MCAssembler.cpp:728: void llvm::MCAssembler::writeSectionData(llvm::raw_ostream&, const llvm::MCSection*, const llvm::MCAsmLayout&) const: Assertion `OS.tell() - Start == Layout.getSectionAddressSize(Sec)' failed.

Changing the .skip to use a fixed number of bytes or replacing jmp with a non-relaxable instructions (i.e. with fixed size) fixed the issue. I suspect the integrated assembler fails to update the offset of the fragments following the FT_Fill segment that enclosed the .skip instruction, when the jmp instruction is relaxed and the evaluation of 144f-143f is finalized.

**Comment by nickdesaulniers** [comment]
(More background on [`alternatives`](https://lwn.net/Articles/164121/)

**Comment by jcai19** [comment]
Thanks for the link! Meanwhile, I have reported this issue upstream at https://llvm.org/pr45190.

**Comment by jcai19** [comment]
Proposed fix: https://reviews.llvm.org/D76114

**Comment by jcai19** [comment]
Proposed fix has been accepted on LLVM upstream and submitted.
