### ISSUE TITLE
-Wconstant-logical-operand in kernel/sched/fair.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#93]
```
kernel/sched/fair.c:3705:14: warning: use of logical '&&' with constant operand [-Wconstant-logical-operand]
        if (initial && sched_feat(START_DEBIT))
                    ^  ~~~~~~~~~~~~~~~~~~~~~~~
kernel/sched/fair.c:3705:14: note: use '&' for a bitwise operation
        if (initial && sched_feat(START_DEBIT))
                    ^~
                    &
kernel/sched/fair.c:3705:14: note: remove constant to silence this warning
        if (initial && sched_feat(START_DEBIT))
                   ~^~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

**Comment by nickdesaulniers** [comment]
There's a patch for this, working it's way up the tree. I also filed an llvm issue because clang warns when the constant operand is on the right hand side of the binary logical operand, but not the left.

**Comment by tpimh** [comment]
I can't see how it's connected. The previous function's body is indeed conditional for `CONFIG_SCHED_DEBUG`: https://github.com/ClangBuiltLinux/linux/blob/96eddb810b146e4d364e35f38dc11d16680c66eb/kernel/sched/fair.c#L3683
But `place_entity()` doesn't have anything to do with it.

**Comment by nickdesaulniers** [comment]
https://llvm.org/pr38571 is the llvm bug, let me find the kernel patch.

**Comment by nickdesaulniers** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=7e6f4c5d600c1c8e2a1d900e65cab319d9b6782e is the patch, currently in the -next tree.

**Comment by tpimh** [comment]
This is in 4.19: 7e6f4c5d600c1c8e2a1d900e65cab319d9b6782e
