### ISSUE TITLE
../scripts/link-vmlinux.sh: line 101: 63378 Killed       ${LD} ${LDFLAGS} -r -o ${1} $(modversions) ${objects}

### ISSUE THREAD

**Issue by shandongtlb** [ClangBuiltLinux/linux#931]
Hello, I'm sorry to disturb you. I tried to turn on LTO LLD optimization for the kernel. Before it was turned on, everything was normal. But after it was turned on, when I finally compiled vmlinux, it made an error like this
............
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  AR      init/built-in.o
  AR      built-in.o
  LTO     vmlinux.o
../scripts/link-vmlinux.sh: line 101: 63378 Killed                  ${LD} ${LDFLAGS} -r -o ${1} $(modversions) ${objects}
/root/kernel_MIUI_Q_cepheus/Makefile:1145: recipe for target 'vmlinux' failed
make[1]: *** [vmlinux] Error 137
make[1]: Leaving directory '/root/kernel_MIUI_Q_cepheus/out'
Makefile:146: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2

The kernel version is 4.14.172 ,compiling with clang11 compiler.
arch:arm64
device:xiaomi9
Android verion:10
compiler:gcc4.9+clang-11 https://github.com/EviraKernel/Clang-11

Everything is normal before opening LTO LLD. I tried to merge the submission of re4son https://github.com/Re4son/android_kernel_oneplus_sm8150/commits/nethunter-10.0-2?after=b087ef8ae801e44bda270be1116fa55553068d88+34 to open it. As a result, vmlinux encountered an error 
!
![IMG_20200314_010136](https://user-images.githubusercontent.com/40312509/76643112-6eb05500-658f-11ea-814c-9330237126e6.jpg)

This is all my logs, please check,
https://github.com/shandongtlb/paste/blob/master/kernel-lld-fail.log

Thanks! God bless you!

**Comment by nathanchance** [comment]
I haven’t looked through the commits but usually the killed note means that you ran out of memory, what are your machine specs?

**Comment by shandongtlb** [comment]
> I haven’t looked through the commits but usually the killed note means that you ran out of memory, what are your machine specs?

First of all, thank you for your answer! I used VMware Ubuntu 18, so the memory is a little small. 4GB ram, is not enough memory?😄

**Comment by shandongtlb** [comment]
> I haven’t looked through the commits but usually the killed note means that you ran out of memory, what are your machine specs?

I will try to increase the memory tomorrow. Then I will tell you the result of the solution. Thank you, have a good day, And LORD bless you!

**Comment by nathanchance** [comment]
> First of all, thank you for your answer! I used VMware Ubuntu 18, so the memory is a little small. 4GB ram, is not enough memory?😄

Definitely not for full LTO; ThinLTO should in theory work with 4GB because it is a lot less memory intensive but I have never had access to a machine where I could test it on.

For lld support, I would nuke all of those commits that you have and align with the Pixel 4. Fetch `android-r-preview-1_r0.7` from https://android.googlesource.com/kernel/msm/ and pick `10fa2703fb52f2adf0332c6743587d44ce670b0f` to `71d1e547a6ccff11307c7f93426b2db32d791f0c` ([git log](https://android.googlesource.com/kernel/msm/+log/ab3f7595f43d3ad7ca6e021ab61c88dab976411d)). That should be all you need (unless @nickdesaulniers is aware of any other fixes that were needed before or after, I do not see any combing over the tree).

If you want ThinLTO, pick `6d6127fd19f11f20579454e6b31d53fccdf7d929` to `ab3f7595f43d3ad7ca6e021ab61c88dab976411d` then fetch `android-4.14` from https://android.googlesource.com/kernel/common/ and pick `75f80b3632ccbc11b48cb164b5ef0a49b5663a57`.

If you want to stick to full LTO, you will need a lot more memory (I think I see my machine go upwards of 40GB when building a crosshatch or coral kernel).

**Comment by shandongtlb** [comment]
OK, thank you. I'm driving a complete LTO Chinese style I'm trying to change ThinLTO

**Comment by shandongtlb** [comment]
Thank you for your advice. ThinLTO has been successfully opened,but when I command "readelf --string-dump .comment vmlinux" ,it only shows [0] clangversion11xxxxxxxxxx, no Link LLD😂.When I delete the LLD in clang/bin/, it will display an error, which proves that LLD is indeed applicable, so I don't know why readelf doesn't display LLD

**Comment by nathanchance** [comment]
Have you specified `LD=ld.lld` like how you specify `CC=clang`?

**Comment by shandongtlb** [comment]
> Have you specified `LD=ld.lld` like how you specify `CC=clang`?

Hello, I'm sorry to disturb you again, when I compiled vmlinux with the following command, there was a relocate error.

command:
mkdir out
export ARCH=arm64
export SUBARCH=arm64
export DTC_EXT="/root/dtc-1.6.0/dtc"
export CROSS_COMPILE=/root/toolchain/bin/aarch64-linux-android-
make O=out  LD=ld  CC=/root/Clang-11/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- cepheus_user_defconfig
make -j16  LD=ld  O=out CC=/root/Clang-11/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- 2>&1 | tee kernel.log

show error:

  AR      init/built-in.o
  AR      built-in.o
  LTO     vmlinux.o
  MODPOST vmlinux.o
ld: error: relocation R_AARCH64_ABS32 cannot be used against symbol __crc_gsi_write_channel_scratch; recompile with -fPIC
>>> defined in vmlinux.o
>>> referenced by win_minmax.c
>>>               vmlinux.o:(___kcrctab+gsi_write_channel_scratch+0x0)
/root/kernel_MIUI_Q_cepheus/Makefile:1150: recipe for target 'vmlinux' failed
make[1]: *** [vmlinux] Error 1
make[1]: leave“/root/kernel_MIUI_Q_cepheus/out”
Makefile:146: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2

And when I disable LTO and only use LLD, this error still occurs.

How to fix it...... Thanks!!XD

**Comment by shandongtlb** [comment]
[kernel.log](https://github.com/ClangBuiltLinux/linux/files/4333889/kernel.log)
This is kernel.log

**Comment by nathanchance** [comment]
Please push your latest source so I can try to investigate.

If you want a quick hack, removing the `EXPORT_SYMBOL(gsi_write_channel_scratch);` line in `drivers/platform/msm/gsi/gsi.c` should resolve it and not cause any issues since `gsi_write_channel_scratch` is only used in drivers that are built into the kernel and not any modules.

I've combed through the Pixel 4 source and don't see any clear fix but it might not have been labelled as such. @nickdesaulniers might know if this came up or not. Probably has something to do with the

```
WARNING: EXPORT symbol "gsi_write_channel_scratch" [vmlinux] version generation failed, symbol will not be versioned.
```

that I regularly see when building the Pixel 4 kernel.

**Comment by shandongtlb** [comment]
Yes! I get same error `WARNING: EXPORT symbol "gsi_write_channel_scratch" [vmlinux] version generation failed, symbol will not be versioned.`

Now I try to delete 
EXPORT_SYMBOL(gsi_write_channel_scratch)

In addition, I invite you to obtain submit access to my kernel warehouse, please agree.
You're really great,Thank you!

**Comment by shandongtlb** [comment]
I have deleted them, but emmmmmm

ld: error: output file too large: 18446743524483380624 bytes

thanks
[kernel.log](https://github.com/ClangBuiltLinux/linux/files/4334214/kernel.log)

**Comment by shandongtlb** [comment]
There are my latest kernel source, thanks please
https://github.com/shandongtlb/kernel_MIUI_Q_cepheus

**Comment by nickdesaulniers** [comment]
gsi_write_channel_scratch is an issue we faced on Pixel 4 and other QC SoC codebases.  `gsi_write_channel_scratch` misuses `__packed` where it should not (function parameters), that confuses the kernel's broken C parser used in MODPOST, that produces checksums of `0`.  We haven't published the kernel patch yet; but you can manually delete all these `__packed` on `gsi_write_channel_scratch` in function parameters. DO NOT DELETE `__packed` on the **definition** of `gsi_write_channel_scratch`, which is the only correct place for that attribute to appear.

**Comment by nathanchance** [comment]
Ah so it is all of the cleanup patches here? https://android.googlesource.com/kernel/msm/+log/4045d8f33e1fdd776c6d39b5171fc80361a363bd/drivers/platform/msm/gsi

**Comment by nickdesaulniers** [comment]
Ah, good, so they are published.  Yes, I wrote up a big long commit message on why all this was busted, then Petri went and split up the patches into 4 and cleaned up some other places I missed.  No harm in publishing my original commit message:
```
msm: fix symbol versioning failure for gsi_write_channel_scratch

When building the kernel, we'd see the following warning:
WARNING: EXPORT symbol "gsi_write_channel_scratch" [vmlinux] version
generation failed, symbol will not be versioned.

When upgrading the kernel toolchain, the following related linkage
failure started occurring:
ld.lld: error: relocation R_AARCH64_ABS32 cannot be used against symbol
__crc_gsi_write_channel_scratch; recompile with -fPIC

This device config enables CONFIG_MODVERSIONS, a way of doing symbol
versioning, which can protect from loading kernel modules for which the
expected kernel interfaces (ABI) have changed.

CONFIG_MODVERSIONS uses scripts/genksyms/genksyms to create a file,
Module.symvers, that is a simple mapping of crc's of various symbols'
types to the symbol names.  It's produces these crc's by using the C
preprocessor, then passing this into genksyms. genksyms has a lex/yacc
based C parser to parse the preprocessed sources of kernel modules.  It
turns out that it's incomplete, copied from an upstream project that
ceased development in 2013, and was slated to be removed around the 4.9
kernel release.

Because genksyms's C parser is incomplete, it doesn't understand
compiler __attribute__'s on structs/enums/unions.  This has dire
implications for MODULE_EXPORT'ed function symbols that expect
__attribute__((packed)) structs/enums/unions, such as
gsi_write_channel_scratch.

The crc failure can be observed:
$ grep 0x00000000 out/android-msm-floral-4.14/private/msm-google/Module.symvers
0x00000000	gsi_write_channel_scratch	vmlinux	EXPORT_SYMBOL
$ echo 'union __attribute__((packed)) foo { char bar; };' | \
    ./scripts/genksyms/genksyms -d
Hash table occupancy 0/4096 = 0
$ echo 'union foo { char bar; };' | ./scripts/genksyms/genksyms -d
Defn for union foo == <union foo { char bar ; } >
Hash table occupancy 1/4096 = 0.000244141

This results in incorrect relocations being produced to the crc's.

Some possible solutions:
* Update the kernel's version of genksyms.  There's a comment that the
  kernel's sources were copied from "modutils." It seems that modutils'
  last release was v2.4.27 in 2004, and that development on it has
  stopped.  Upstream modutils also has the same parsing bug.
* Don't rely on MODVERSIONS.  While the current work being done on
  libabigail is meant to help, it's a build time only check and doesn't
  solve the problem of loading a potentially harmful kernel module at
  runtime. Further, Android has VTS tests for CONFIG_MODVERSIONS, which
  will take time to undo.
* Fix the parsing bug in genksysms. While the discussion about removing
  CONFIG_MODVERSIONS has started again upstream due to my bugreport,
  this would be the optimal solution, if I could just figure out how to
  rewrite the parser correctly.
* Adjust the definition of gsi_channel_scratch when __GENKSYMS__ is
  defined, such that the type appears to be something that genksyms can
  at least version.  This is suboptimal, but a quick enough fix to
  unblock the toolchain upgrade.

The final option is rather simple: __attribute__((packed)) only needs to
be applied to the declaration of a struct/enum/union, not everywhere its
used as a formal parameter or variable. For example:

struct __attribute__((packed)) foo { short z; int y; };
size_t bar(struct foo my_foo) { return sizeof(my_foo); }

would return 6 on an LP64 machine (and would return 8 if foo wasn't
packed).

Simply remove the __attribute__((packed)) from the declaration of
gsi_channel_scratch when __GENKSYMS__ is defined, and remove __packed
from all references to the type `union gsi_channel_scratch` since it's
not necessary (and the code was already inconsistent in its usage).

With gsi_write_channel_scratch being crc'ed correctly, we can now link
the kernel, and move on with the toolchain update.

A better long term solution would be to replace genksyms's
modutils/lex/yacc based incomplete and dead C parser with a libclang
based one, but such work is beyond the scope of a toolchain update.

For future travelers that would like to take a crack at fixing the
existing parser, I found the develop/build/test/debug cycle to be:

$ rm scripts/genksyms/genksyms
$ make scripts/genksyms/
$ ./scripts/genksyms/genksyms -d < test_case.i
$ ./scripts/genksyms/genksyms -d -d < test_case.i
Best of luck on that endeavor.

Change-Id: Iba4567e571be10030e01accf41424d70c3acdbb3
Link: https://lwn.net/Articles/707520/
Link: https://mirrors.edge.kernel.org/pub/linux/utils/kernel/modutils/v2.4/
Link: https://lore.kernel.org/lkml/CAKwvOdnJAApaUhTQs7w_VjSeYBQa0c-TNxRB4xPLi0Y0sOQMMQ@mail.gmail.com/
Bug: 139808631
Bug: 139442076
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
```

**Comment by shandongtlb** [comment]
Thank you first! I have modified it manually according to the above patch or not... Report error 
`ld: error: output file too large: 18446743524483450200bytes`
 
XD

**Comment by shandongtlb** [comment]
Although it was modified, the same error was reported..XD

**Comment by nickdesaulniers** [comment]
Great, now for that error, look for a commit to `arch/arm64/kernel/vmlinux.lds.S` titled `selinux: Relocate ss_initialized and selinux_enforcing to separate 4k` and revert it.  It specifies `.bss` a second time, which confuses LLD.

**Comment by shandongtlb** [comment]
Thank you,Where is the specific link for this commit? Thank you XD😁

**Comment by nathanchance** [comment]
https://android.googlesource.com/kernel/msm.git/+/d9d36ace40ca279bf6841a0843b72600b10ae17e

**Comment by shandongtlb** [comment]
> https://android.googlesource.com/kernel/msm.git/+/d9d36ace40ca279bf6841a0843b72600b10ae17e

Thank you. I found this commit almost in the 4.14 branch after 2018.XD😁😁

**Comment by shandongtlb** [comment]
It works! Thank you very very much, perfect!😃😃😃😃😃

**Comment by shandongtlb** [comment]
I want to Close this issue

**Comment by shandongtlb** [comment]
Thanks for being late and GOD bless you!
