### ISSUE TITLE
ppc32 boot panic on -next

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#935]
Just filing this so we can track it in the future, but -next ppc32 builds have been failing to build.  I reported this upstream, and a fix has already been authored and accepted: https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?id=cc6f0e39000900e5dd1448103a9571f0eccd7d4e

example: https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/298901533

**Comment by nathanchance** [comment]
Fixed: https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/301119554
