### ISSUE TITLE
PowerPC ".weak" symbol not made weak

### ISSUE THREAD

**Issue by gwelymernans** [ClangBuiltLinux/linux#937]
This seems like a problem. 

```
$ cat ppc-asm.S
	.text
	.weak	_zimage_start
	.globl	_zimage_start
_zimage_start:
$ clang -target powerpc64-linux-gnu -o /tmp/t.o ../ppc-asm.S -c
$ nm /tmp/t.o
0000000000000000 T _zimage_start
```

`_zimage_start` should be weak, right?

**Comment by nickdesaulniers** [comment]
(not specific to ppc)
```
$ clang -c foo.s -o foo.o                             
$ llvm-nm foo.o
0000000000000000 T _zimage_start
$ clang -c foo.s -o foo.o --target=aarch64-linux-gnu  
$ llvm-nm foo.o                                     
0000000000000000 T _zimage_start
$ clang -c foo.s -o foo.o --target=arm-linux-gnueabihf
$ llvm-nm foo.o                                       
00000000 T _zimage_start
$ clang -c foo.s -o foo.o --target=powerpc64-linux-gnu
$ llvm-nm foo.o                                       
0000000000000000 T _zimage_start
```
```c
// foo.c
__attribute__((weak))
void foo(void) {}
```
```sh
$ clang -c foo.c -o foo.o
$ llvm-nm foo.o          
0000000000000000 W foo
$ clang -S foo.c -o foo.s
$ clang -c foo.s -o foo.o
$ llvm-nm foo.o
0000000000000000 W foo
```
```asm
.weak foo
foo:
```
```sh
$ llvm-nm foo.o          
0000000000000000 W foo
$ llvm-nm foo.o    
0000000000000000 W foo
```
```asm
.weak   foo
.globl  foo
foo:
```
```sh
$ llvm-nm foo.o          
0000000000000000 T foo
$ as foo.s -o foo.o
$ llvm-nm foo.o
0000000000000000 T foo
```
so no disagreement between Clang and GAS.  Looks like `.globl` directive messes this up.
https://sourceware.org/binutils/docs/as/Global.html#Global doesn't really give any guidance when used with `.weak`, but I think `.weak` would imply global, as otherwise how would a strong symbol interpose it?  https://sourceware.org/binutils/docs/as/Weak.html#Weak (also gives no guidance in concert with `.globl`).

**Comment by nickdesaulniers** [comment]
via `man 1 nm`:
```
If lowercase, the symbol is usually local; if uppercase, the symbol is global (external).
```
So I guess you could have a weak local symbol; only other symbols in the same translation unit could interpose it.

**Comment by gwelymernans** [comment]
Also at PR45245 at bugs.llvm.org

**Comment by MaskRay** [comment]
https://sourceware.org/pipermail/binutils/2020-March/110376.html

I propose that we error for the second binding directive.

arch/powerpc/boot/crt0.o should not use both directives. Sent https://lore.kernel.org/linuxppc-dev/20200325051820.163253-1-maskray@google.com/

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?id=968339fad422a58312f67718691b717dac45c399

**Comment by nathanchance** [comment]
Merged into mainline: https://git.kernel.org/linus/968339fad422a58312f67718691b717dac45c399
