### ISSUE TITLE
unknown pseudo-op: `.cfi_negate_ra_state'

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#938]
just when I expected our CI to finally go green:
https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/299816618

```
  CC      arch/arm64/kernel/vdso/vgettimeofday.o
/tmp/vgettimeofday-36a54b.s: Assembler messages:
/tmp/vgettimeofday-36a54b.s:40: Error: unknown pseudo-op: `.cfi_negate_ra_state'
/tmp/vgettimeofday-36a54b.s:573: Error: unknown pseudo-op: `.cfi_negate_ra_state'
/tmp/vgettimeofday-36a54b.s:931: Error: unknown pseudo-op: `.cfi_negate_ra_state'
```

**Comment by nickdesaulniers** [comment]
Looks like this is caused by `-mbranch-protection=pac-ret+leaf` via https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git/commit/?h=for-next/core&id=74afda4016a7437e6e425c3370e4b93b47be8ddf

**Comment by nickdesaulniers** [comment]
https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=e8dc9b5bfd234f61c6127d23cb80fbd4b0382115

The first tag that contains that commit is binutils-2_34.

**Comment by nickdesaulniers** [comment]
maybe something like this (untested):
```diff
diff --git a/arch/arm64/Kconfig b/arch/arm64/Kconfig
index b889d7956abf..99f0a0e681f7 100644
--- a/arch/arm64/Kconfig
+++ b/arch/arm64/Kconfig
@@ -1505,7 +1505,7 @@ config ARM64_PTR_AUTH
        bool "Enable support for pointer authentication"
        default y
        depends on !KVM || ARM64_VHE
-       depends on (CC_HAS_SIGN_RETURN_ADDRESS || CC_HAS_BRANCH_PROT_PAC_RET) && AS_HAS_PAC
+       depends on (CC_HAS_SIGN_RETURN_ADDRESS || CC_HAS_BRANCH_PROT_PAC_RET) && AS_HAS_PAC && AS_HAS_CFI_NEGATE_RA_STATE
        depends on (!FUNCTION_GRAPH_TRACER || DYNAMIC_FTRACE_WITH_REGS)
        help
          Pointer authentication (part of the ARMv8.3 Extensions) provides
@@ -1550,6 +1550,9 @@ config CC_HAS_SIGN_RETURN_ADDRESS
 config AS_HAS_PAC
        def_bool $(as-option,-Wa$(comma)-march=armv8.3-a)
 
+config AS_HAS_CFI_NEGATE_RA_STATE
+       def_bool $(as-instr,.cfi_negate_ra_state)
+
 endmenu
 
 menu "ARMv8.4 architectural features"
```

**Comment by nickdesaulniers** [comment]
future notes to self:
1. to cross compile binutils: `./configure --target=aarch64-elf` (and `cp ./gas/as-new ./gas/aarch64-linux-gnu-as`)
2. to test that new binutils: `printf "%b\n" ".cfi_startproc\n.cfi_negate_ra_state\n.cfi_endproc\n" | clang --target=aarch64-linux-gnu -no-integrated-as -c -x assembler -o /dev/null --gcc-toolchain=/android1/binutils-gdb/ --prefix=/android1/binutils-gdb/gas - -v`
  * verify it's using /android1/binutils-gdb/gas/aarch64-linux-gnu-as
3. `ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- make CC=clang GCC_TOOLCHAIN_DIR=/android1/binutils-gdb/gas/ -j71 defconfig`

**Comment by nickdesaulniers** [comment]
submitted: https://lore.kernel.org/linux-arm-kernel/20200319181951.102662-1-ndesaulniers@google.com/T/#u

**Comment by nickdesaulniers** [comment]
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git/commit/?h=for-next/core&id=3b446c7d27ddd06342901bb35211363f6944291a

**Comment by nathanchance** [comment]
Fixed:

https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/301119551

https://git.kernel.org/next/linux-next/c/3b446c7d27ddd06342901bb35211363f6944291a
