### ISSUE TITLE
LLD doesn't support -z nodefaultlib flag

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#94]
Needed to compile `arch/x86/purgatory/purgatory.ro`. Currently lld fails

    ld.lld: error: unknown -z value: nodefaultlib

This is the description of what it should do:

    -z nodefaultlib
    
    Marks the object so that the runtime default library
    search path (used after any LD_LIBRARY_PATH or runpaths)
    is ignored. This option implies that all dependencies of
    the object can be satisfied from its runpath.

**Comment by nickdesaulniers** [comment]
LLVM bug: https://llvm.org/pr38978

**Comment by tpimh** [comment]
https://reviews.llvm.org/D54577
