### ISSUE TITLE
STUBCPY fails with llvm-strip

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#940]
``llvm-strip`` doesn't support `-o` option, which is used here: 
https://github.com/ClangBuiltLinux/linux/blob/5ad0ec0b86525d0c5d3d250d3cfad7f183b00cfa/drivers/firmware/efi/libstub/Makefile#L91

When building the kernel commands like
```
llvm-strip-11 --strip-debug -o drivers/firmware/efi/libstub/lib-fdt.stub.o drivers/firmware/efi/libstub/lib-fdt.o
```
would fail with
```
llvm-strip-11: error: unknown argument '-o'
```

**Comment by nathanchance** [comment]
Documentation says it should... https://llvm.org/docs/CommandGuide/llvm-strip.html

What command can I reproduce this with?

**Comment by tpimh** [comment]
Yes, I can see it in the man page, but not in the source code. Probably, the implementation is just missing: not listed [here](https://github.com/llvm-mirror/llvm/blob/c86b9d718d75228a591a101b1aeb9cacce997d79/tools/llvm-objcopy/CommonOpts.td) nor [here](https://github.com/llvm-mirror/llvm/blob/c86b9d718d75228a591a101b1aeb9cacce997d79/tools/llvm-objcopy/StripOpts.td).

You can just do `llvm-strip unstripped-object.o -o stripped-object.o` to get the same error message.

For building the kernel I'm using defconfig (except for CONFIG_KVM being disabled) and building with:

```
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- AR=llvm-ar-11 AS=clang-11 CC=clang-11 HOSTCC=clang-11 HOSTLD=ld.lld-11 HOSTAR=llvm-ar-11 KCFLAGS=-Wno-implicit-fallthrough LD=ld.lld-11 NM=llvm-nm-11 OBJCOPY=llvm-objcopy-11 OBJDUMP=llvm-objdump-11 OBJSIZE=llvm-size-11 READELF=llvm-readelf-11 STRIP=llvm-strip-11 Image.gz
```

**Comment by nathanchance** [comment]
> Yes, I can see it in the man page, but not in the source code. Probably, the implementation is just missing: not listed [here](https://github.com/llvm-mirror/llvm/blob/c86b9d718d75228a591a101b1aeb9cacce997d79/tools/llvm-objcopy/CommonOpts.td) nor [here](https://github.com/llvm-mirror/llvm/blob/c86b9d718d75228a591a101b1aeb9cacce997d79/tools/llvm-objcopy/StripOpts.td).

It's right here: https://github.com/llvm-mirror/llvm/blob/c86b9d718d75228a591a101b1aeb9cacce997d79/tools/llvm-objcopy/StripOpts.td#L3-L4

> You can just do `llvm-strip unstripped-object.o -o stripped-object.o` to get the same error message.

```
$ echo | clang -c -x c - -o test.o
$ llvm-strip -o test-stripped.o test.o
$ ls
test.o  test-stripped.o
$ rm *.o
$ echo | clang -c -x c - -o test.o
$ llvm-strip test.o -o test-stripped.o
$ ls
test.o  test-stripped.o
```

> For building the kernel I'm using defconfig (except for CONFIG_KVM being disabled) and building with:
> 
> ```
> make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- AR=llvm-ar-11 AS=clang-11 CC=clang-11 HOSTCC=clang-11 HOSTLD=ld.lld-11 HOSTAR=llvm-ar-11 KCFLAGS=-Wno-implicit-fallthrough LD=ld.lld-11 NM=llvm-nm-11 OBJCOPY=llvm-objcopy-11 OBJDUMP=llvm-objdump-11 OBJSIZE=llvm-size-11 READELF=llvm-readelf-11 STRIP=llvm-strip-11 Image.gz
> ```

```
$ git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
$ cd linux
$ curl -LSs 'https://git.kernel.org/pub/scm/linux/kernel/git/robh/linux.git/patch/?id=35595372d95c0d10784bce1aec8cc144a39eb66d' | git am
$ git pull --no-edit https://github.com/ihalip/linux elfnote
$ make -j$(nproc) -s ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- AR=llvm-ar AS=clang CC=clang HOSTCC=clang HOSTLD=ld.lld HOSTAR=llvm-ar LD=ld.lld NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump OBJSIZE=llvm-size READELF=llvm-readelf STRIP=llvm-strip distclean allyesconfig drivers/firmware/efi/
```

compiles/works fine for me at https://github.com/llvm/llvm-project/commit/2b52e4e629e6793f832caef5e47f9d84607740f3. Using `V=1` and `|& rg "llvm-strip"` shows that it is getting invoked and I see the files created. Are the files that are getting stripped getting created?

**Comment by tpimh** [comment]
You are right, I didn't look properly at StripOpts.td. However, for some odd reason my toolchain behaves as if it was not there.

I'm using the latest llvm (`1:11~++20200320102625+e708471395b-1~exp1~20200320213219.659`) from llvm apt repo and similar test fails for me:
```
$ echo | clang-11 -c -x c - -o test.o
$ llvm-strip-11 -o test-stripped.o test.o
llvm-strip-11: error: unknown argument '-o'
```

I can try to set up a travis job that fails with this error.

**Comment by nathanchance** [comment]
So there seems to be something up with the symlinks that Debian has for the `-11` binaries. Your example fails for me on Debian too. However...

```
$ echo | /usr/lib/llvm-11/bin/clang -c -x c - -o test.o
$ /usr/lib/llvm-11/bin/llvm-strip -o test-stripped.o test.o
```

works fine.

**Comment by tpimh** [comment]
Just built a bootable kernel using `STRIP=/usr/lib/llvm-11/bin/llvm-strip`. This is strange: I guess for some reason `IsStrip` is being set to `false` [here](https://github.com/llvm-mirror/llvm/blob/c86b9d718d75228a591a101b1aeb9cacce997d79/tools/llvm-objcopy/llvm-objcopy.cpp#L319), but it's not obvious to me why as symlink name contains the word "strip". So command-line parsing is performed for objcopy, not strip and objcopy lacks '-o' option which is causing the error to be produced.

**Comment by nathanchance** [comment]
Oh... That's the outdated split repo. The monorepo makes it apparent why this is failing.

https://github.com/llvm/llvm-project/blob/a1e02753c0ec163eb84d6648bde09181d40f4e47/llvm/tools/llvm-objcopy/llvm-objcopy.cpp#L331

https://github.com/llvm/llvm-project/commit/c54959c00d0b39f357d48c3b4f955d72de4c9fc1

I'll see if I can't fix this myself, otherwise I'll report it upstream.

```
$ echo | /usr/lib/llvm-11/bin/clang -c -x c - -o test.o
$ ln -s /usr/lib/llvm-11/bin/llvm-strip llvm-strip-11
$ ./llvm-strip-11 test.o -o test-stripped.o
./llvm-strip-11: error: unknown argument '-o'
```

Might as well key @rupprecht and @MaskRay in as they work on the LLVM tools.

**Comment by nathanchance** [comment]
With the current setup of `StringSwitch` and `sys::path`, there does not appear to be a way to:

* Partial match `strip` (it has to either be at the beginning or end of the string, due to `StartsWith` or `EndsWith`).

* Follow symlinks, as `sys::path` does not have any function that does (nor would this likely work because `llvm-strip` is just a symlink to `llvm-objcopy`, which is how this all works anyways).

I am not at all familiar with the LLVM data structures to resolve this further so reported upstream: https://llvm.org/pr45271

For what it's worth, this is an LLVM 10 regression but I do not think it is serious enough to warrant holding up the release. This is a pretty fringe case and realistically we can easily work around this by just adding `/usr/lib/llvm-11/bin` to the front of `PATH` while invoking `make`.

**Comment by nathanchance** [comment]
Hack of a patch that basically restores the old behavior by basically open coding `StringSwitch`.

```diff
diff --git a/llvm/tools/llvm-objcopy/llvm-objcopy.cpp b/llvm/tools/llvm-objcopy/llvm-objcopy.cpp
index 8e95ebb7333..24f20d21357 100644
--- a/llvm/tools/llvm-objcopy/llvm-objcopy.cpp
+++ b/llvm/tools/llvm-objcopy/llvm-objcopy.cpp
@@ -327,11 +327,15 @@ enum class ToolType { Objcopy, Strip, InstallNameTool };
 int main(int argc, char **argv) {
   InitLLVM X(argc, argv);
   ToolName = argv[0];
-  ToolType Tool = StringSwitch<ToolType>(sys::path::stem(ToolName))
-                      .EndsWith("strip", ToolType::Strip)
-                      .EndsWith("install-name-tool", ToolType::InstallNameTool)
-                      .EndsWith("install_name_tool", ToolType::InstallNameTool)
-                      .Default(ToolType::Objcopy);
+  StringRef BaseToolName = sys::path::stem(ToolName);
+  ToolType Tool;
+  if (BaseToolName.contains("strip"))
+    Tool = ToolType::Strip;
+  else if (BaseToolName.contains("install-name-tool") ||
+           BaseToolName.contains("install_name_tool"))
+    Tool = ToolType::InstallNameTool;
+  else
+    Tool = ToolType::Objcopy;
   // Expand response files.
   // TODO: Move these lines, which are copied from lib/Support/CommandLine.cpp,
   // into a separate function in the CommandLine library and call that function
```

**Comment by MaskRay** [comment]
Regressed by https://reviews.llvm.org/D69146 (rupprecht actually proposed `contains` but the advice was not adopted)

I will work on a fix similar to https://reviews.llvm.org/D71301
