### ISSUE TITLE
lld cannot handle R_PPC64_REL14 long branch thunks for pseries_defconfig

### ISSUE THREAD

**Issue by MaskRay** [ClangBuiltLinux/linux#951]
Reproduce:

```
make -j30 ARCH=powerpc CROSS_COMPILE=powerpc64-linux-gnu- CC=clang LD=ld.lld O=/tmp/out/ppc64 pseries_defconfig vmlinux
```

When linking `.tmp_vmlinux1`: `ld.lld -EB -m elf64ppc -Bstatic --orphan-handling=warn --build-id -o .tmp_vmlinux1 ...`

**Comment by nathanchance** [comment]
Is this a dupe of #602 or something different?

**Comment by MaskRay** [comment]
It is different from #602 . lld has thunk infrastructure for R_PPC64_REL14 but it just disallows that with an assertion:/ 

The code change is trivial https://reviews.llvm.org/D76904 but I'd like https://reviews.llvm.org/D76907 (llvm-objdump -d improvement on condition branches) to be merged first to make history clean.

I forgot `cflags-$(CONFIG_CPU_BIG_ENDIAN) += $(call cc-option,-mabi=elfv1)`

lld's PPC64 elfv1 was intentionally deleted when elfv2 support was contributed. I think there is simply no interest maintaining PPC64 elfv1.

**Comment by MaskRay** [comment]
The particular R_PPC64_REL14 thunk is fixed by https://reviews.llvm.org/D76904
