### ISSUE TITLE
multi_v5_defconfig assertion failure in kernel/trace/trace_clock.o

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#954]
When LLVM is compiled with `-DLLVM_ENABLE_ASSERTIONS=ON`:

```
$ make -j$(nproc) -s ARCH=arm CC=clang CROSS_COMPILE=arm-linux-gnueabi- O=out/arm32 distclean multi_v5_defconfig kernel/trace/trace_clock.o
fragment covers entire variable
!1079 = !DIGlobalVariableExpression(var: !1074, expr: !DIExpression(DW_OP_LLVM_fragment, 0, 64))
!1074 = distinct !DIGlobalVariable(name: "trace_clock_struct", scope: !2, file: !1057, line: 89, type: !1075, isLocal: true, isDefinition: true)
fatal error: error in backend: Broken module found, compilation aborted!
clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
...
```

creduce spits out ([files](https://github.com/nathanchance/creduce-files/tree/d09780fbcf83f4707527f6bf6e553c79ea43d5e4/multi_v5_defconfig-trace_clock-crash)):

```c
typedef struct {
} a;
static struct {
  long b;
  a c
} d;
e() {
  long f = d.b + 1;
  d.b = f;
}
```

Reported upstream: https://bugs.llvm.org/show_bug.cgi?id=45335

**Comment by nickdesaulniers** [comment]
Is this a recent regression? Can we bisect llvm if so?

**Comment by nathanchance** [comment]
This is not a recent regression. I can reproduce this back to LLVM 7.0.1. I just have not been testing LLVM with assertions enabled but I'm wiring that into my testing framework to catch more potential issues.

**Comment by nathanchance** [comment]
Patch submitted: https://reviews.llvm.org/D78720

**Comment by nickdesaulniers** [comment]
might want to take 3929429347d398773577b79f7fdb780d4f7ed887 into clang-10.1? cc @tstellar

**Comment by tstellar** [comment]
I created a tracking bug for this: https://llvm.org/PR45760

**Comment by nickdesaulniers** [comment]
Thanks Tom! Who are you directing your question to in that bug?

**Comment by tstellar** [comment]
@nickdesaulniers The initial comment is auto-generated by the script and it's directed at the release manager (which is me for this release).
