### ISSUE TITLE
objtool warnings in gcov

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#955]
```
>> arch/x86/kernel/sys_ia32.o: warning: objtool: __llvm_gcov_writeout()+0x14: call without frame pointer save/setup
>> arch/x86/kernel/sys_ia32.o: warning: objtool: __llvm_gcov_flush()+0x0: call without frame pointer save/setup
```

**Comment by nickdesaulniers** [comment]
@arndb had reported this upstream in https://llvm.org/pr43141.

**Comment by nickdesaulniers** [comment]
`__llvm_gcov_writeout` and `__llvm_gcov_flush` are special instrumentation routines inserted by the compiler. A global function passes them to `llvm_gcov_init`, which is implemented in the kernel runtime in kernel/gcov/clang.c.  `llvm_gcov_init` calls the `writeout` and `flush` callbacks, which in this case are `__llvm_gcov_writeout` and `__llvm_gcov_flush`.

I think the gcov pass needs to set the LLVM IR function level attributes `"frame-pointer"="all"` on these two functions if `-fno-omit-frame-pointer` was set.

```diff
diff --git a/llvm/lib/Transforms/Instrumentation/GCOVProfiling.cpp b/llvm/lib/Transforms/Instrumentation/GCOVProfiling.cpp
index 3a9409601120..5c92df824f6c 100644
--- a/llvm/lib/Transforms/Instrumentation/GCOVProfiling.cpp
+++ b/llvm/lib/Transforms/Instrumentation/GCOVProfiling.cpp
@@ -921,6 +921,7 @@ bool GCOVProfiler::emitProfileArcs() {
     F->setUnnamedAddr(GlobalValue::UnnamedAddr::Global);
     F->setLinkage(GlobalValue::InternalLinkage);
     F->addFnAttr(Attribute::NoInline);
+    F->addFnAttr("frame-pointer", "all");
     if (Options.NoRedZone)
       F->addFnAttr(Attribute::NoRedZone);
 
@@ -1005,6 +1006,7 @@ Function *GCOVProfiler::insertCounterWriteout(
                                  "__llvm_gcov_writeout", M);
   WriteoutF->setUnnamedAddr(GlobalValue::UnnamedAddr::Global);
   WriteoutF->addFnAttr(Attribute::NoInline);
+  WriteoutF->addFnAttr("frame-pointer", "all");
   if (Options.NoRedZone)
     WriteoutF->addFnAttr(Attribute::NoRedZone);
 
@@ -1242,6 +1244,7 @@ Function *GCOVProfiler::insertReset(
                               "__llvm_gcov_reset", M);
   ResetF->setUnnamedAddr(GlobalValue::UnnamedAddr::Global);
   ResetF->addFnAttr(Attribute::NoInline);
+  ResetF->addFnAttr("frame-pointer", "all");
   if (Options.NoRedZone)
     ResetF->addFnAttr(Attribute::NoRedZone);
 
@@ -1275,6 +1278,7 @@ Function *GCOVProfiler::insertFlush(Function *ResetF) {
                               "__llvm_gcov_flush", M);
   FlushF->setUnnamedAddr(GlobalValue::UnnamedAddr::Global);
   FlushF->addFnAttr(Attribute::NoInline);
+  FlushF->addFnAttr("frame-pointer", "all");
   if (Options.NoRedZone)
     FlushF->addFnAttr(Attribute::NoRedZone);
```
seems to fix the issue for x86, but we should probably have a conditional check to only do this if `-fno-omit-frame-pointer` was set.

**Comment by nickdesaulniers** [comment]
@MaskRay and @pcc think that these functions don't need frame pointers, and that objtool should whitelist these.  I would think that means then that we cannot unwind out of them properly?  Let me look into the 32b ARM related failure reported upstream too, and see if that's in any way related or sheds more light.  Then we can ask jpoimboe.

**Comment by MaskRay** [comment]
* `__llvm_gcov_init` is a global constructor which calls `llvm_gcov_init(__llvm_gcov_write, __llvm_gcov_flush, __llvm_gcov_reset` (in compiler-rt or `kernel/gcov/clang.c`). `kernel/gcov/clang.c` currently ignores flush and reset.
* `llvm_gcov_init` registers `__llvm_gcov_flush` to be called when the user application calls `__gcov_flush` (removed. See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93623), and registers `__llvm_gcov_writeout` with `atexit`.

`__llvm_gcov_writeout` is only executed once. `__llvm_gcov_flush` is likely never executed. They don't really need frame pointers.

**Comment by nickdesaulniers** [comment]
> __llvm_gcov_writeout is only executed once. __llvm_gcov_flush is likely never executed. They don't really need frame pointers.

Maybe, but assume `__llvm_gcov_writeout` causes a kernel panic.  Then we wont be able to unwind properly out of it to print a stack trace hinting at what went wrong where.

@jpoimboe do you have thoughts on the above?

**Comment by jpoimboe** [comment]
> Maybe, but assume `__llvm_gcov_writeout` causes a kernel panic. Then we wont be able to unwind properly out of it to print a stack trace hinting at what went wrong where.

Right, stack trace gaps can cause problems with oopses, not to mention other users of the unwinder like perf, tracing, and live patching.  That's why this warning exists.

**Comment by nickdesaulniers** [comment]
More upstream discussion on this topic: https://lore.kernel.org/lkml/CAKwvOd=T3w1eqwBkpa8_dJjbOLMTTDshfevT3EuQD4aNn4e_ZQ@mail.gmail.com/

**Comment by MaskRay** [comment]
> Right, stack trace gaps can cause problems with oopses, not to mention other users of the unwinder like perf, tracing, and live patching. That's why this warning exists.

I am still unsure about the value adding frame pointers. However, if @pcc is ok, I will not object.

> We could do that today by maybe scanning all other function definitions for the presence of "frame-pointer"="all" fn attr, breaking early if we find one, and emitting the frame pointer setup in that case. 

The default is `"frame-pointer"="none"` (`TargetOptions::DisableFramePointerElim`). The function scanning scheme works, but if we go down this route, I'd rather we always add `"frame-pointer=all"`. The function is called once or never called in user programs and the cost is minimal.

**Comment by MaskRay** [comment]
Patch https://reviews.llvm.org/D101129: this fixes `-fno-exceptions -fno-asynchronous-unwind-tables -g` as well.
