### ISSUE TITLE
warning: argument unused during compilation: '-march=armv7-a'

### ISSUE THREAD

**Issue by agners** [ClangBuiltLinux/linux#957]
When using Clang's integrated assembler, the Linux build system passes arguments which are not understood by Clang, leading to warnings such as:

```
clang-10: warning: argument unused during compilation: '-march=armv7-a' [-Wunused-command-line-argument]
clang-10: warning: argument unused during compilation: '-Wa,-march=armv7-a' [-Wunused-command-line-argument]
```

There are about a dozen of instances where this warning is printed. Grepping by `AFLAGS` in `arch/arm` and `inspecting where `-Wa,` is used to pass the architecture to the assembler turns up a list of files to fix.

**Comment by nickdesaulniers** [comment]
cc @kbeyls

**Comment by nickdesaulniers** [comment]
cc @jcai19 @smithp35 

It looks like this was added by kernel commit aff7b4f ("ARM: Ensure ARMv6/7 mm files are built using appropriate assembler options"). So I'm curious if Clang should be consuming these and doing something differently in codegen? I wonder if GAS generates different code with that kernel commit reverted?

**Comment by smithp35** [comment]
Empirically it looks like GCC will pass -march=<arch> through to GNU as, at least as far back as GCC 5.3. However if the GCC command didn't have -march then as I understand it GNU as would infer the architecture from the instructions.

Passing through flags to a non-integrated assembler with -Wa doesn't really fit the integrated assembler, clang just uses -march=<arch>. If clang has to support this for GCC compatibility then we'd probably want to intercept -Wa,-march=<arch> to integrate it with the target-triple (and -march) to avoid conflicts.

**Comment by nickdesaulniers** [comment]
see also the pattern from #1195 that looks more portable. (Using `.arch` directives in source, rather than command line flags).

**Comment by nickdesaulniers** [comment]
duping to #1195 which has an llvm patch.
