### ISSUE TITLE
offset is outside the section

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#959]
https://lists.01.org/hyperkitty/list/kbuild-all@lists.01.org/thread/V6YPX24H2YFOKOE7FWFJ66DQI63R3WKZ/

**Comment by nathanchance** [comment]
https://groups.google.com/d/msg/clang-built-linux/XkHn49b_TnI/S-3yh7H1BgAJ

**Comment by nickdesaulniers** [comment]
arm64 BE was enabled in llvm 13 and disabled otherwise in kernel 5.12, #1288.

arm BE was disabled in the kernel in 5.11 #965.
