### ISSUE TITLE
__aeabi_uldivmod undefined

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#960]
linux-next arm allmodconfig
```
    ERROR: modpost: "__aeabi_uldivmod" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
```

**Comment by nathanchance** [comment]
I fixed this already: https://cgit.freedesktop.org/~agd5f/linux/commit/?id=81b45bad2381e1276a72226b3f7a781482c7ecfc

Didn’t file an issue because it isn’t related to LLVM.

**Comment by nickdesaulniers** [comment]
is that branch not flowing into -next?

**Comment by nathanchance** [comment]
It was only applied this morning so it has not had a chance to flow into -next yet.

**Comment by nathanchance** [comment]
Fixed: https://git.kernel.org/next/linux-next/c/5a6b5458699d8e6fdb5ae09d950935a48b79f8c7

**Comment by nickdesaulniers** [comment]
can we close this @nathanchance or did this regress into mainline with the merge window opening?

**Comment by nathanchance** [comment]
Yes, sorry I meant to close this yesterday :/
