### ISSUE TITLE
ld.lld 10.0.0 crashes after Linux commit af73d78bd384a

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#962]
As I commented here: https://bugs.llvm.org//show_bug.cgi?id=44878#c4

Unfortunately, this issue is also present in `ld.lld 9.0.x`, which might hinder turning on `ld.lld` in certain CIs :/

**Comment by nathanchance** [comment]
That commit is now in Linus' tree: https://git.kernel.org/linus/af73d78bd384aa9b8789aa6e7ddbb165f971276f

**Comment by nickdesaulniers** [comment]
cc @tstellar

**Comment by MaskRay** [comment]
`git cherry-pick -n 6c73246179376442705b3a545f4e1f1478777a04`

is safe in release/10.x and I am in favor of the cherry-pick.

**Comment by tstellar** [comment]
LLVM Tracking bug: https://llvm.org/PR45390
