### ISSUE TITLE
arm32 allyesconfig enabled big endian, which lld doesn't support

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#965]
very similar to #380 but for 32b: https://groups.google.com/g/clang-built-linux/c/XkHn49b_TnI/m/6Zfh0cz0BgAJ

cc @rli9

**Comment by nickdesaulniers** [comment]
I'm curious if LLD doesn't support this emulation, or claims to but has a bug in this case?

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/lkml/20201109224713.16308-1-ndesaulniers@google.com/T/#u

**Comment by nickdesaulniers** [comment]
TODO(Nick): include reported by tag for 0day bot

**Comment by nickdesaulniers** [comment]
submitted: https://www.armlinux.org.uk/developer/patches/viewpatch.php?id=9025/1 (and I forgot to tag the bot, sorry bot :( )

**Comment by nathanchance** [comment]
Workaround now in mainline: https://git.kernel.org/linus/28187dc8ebd938d574edfc6d9e0f9c51c21ff3f4

Do we want to close this?

**Comment by nickdesaulniers** [comment]
Yes, once we have more investment into LLD + BE than we can revisit.
