### ISSUE TITLE
rearchitect callbr

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#972]
posting some links I'll need in the future to provide context to some ideas I have for making `asm goto` less brittle in llvm.

- https://reviews.llvm.org/D64101#1569218
- https://reviews.llvm.org/D76961#1950958
- https://reviews.llvm.org/D76961#1960529

**Comment by nickdesaulniers** [comment]
My thoughts on this; the duplication in the asm parameters that are block AND indirect target list could be avoided by making the indirect target list be instead of a list of basic blocks, placeholders (a la `std::bind`/`std::placeholders::_1`) that represent which asm parameter is the indirect destination.  For example, today
```c
void foo (void) {
    asm goto (""::::bar, baz);
bar:
    return;
baz:
    return;
}
```
looks like:
```llvm
define dso_local void @foo() #0 {
  callbr void asm sideeffect "", "X,X,~{dirflag},~{fpsr},~{flags}"(i8* blockaddress(@foo, %3), i8* blockaddress(@foo, %2)) #1
          to label %1 [label %3, label %2], !srcloc !3

1:                                                ; preds = %0
  br label %3

2:                                                ; preds = %0
  br label %3

3:                                                ; preds = %0, %1, %2
  ret void
}
```
where `label %3` is both in the indirect target list, and the `blockaddress`. Same for `label %2`. This is redundant, and error prone as https://reviews.llvm.org/D74947 demonstrates; `User::replaceUsesOfWith` updates one of the two operands, but not both.

Instead perhaps we could do something like:
```llvm
  callbr void asm sideeffect "", "X,X,~{dirflag},~{fpsr},~{flags}"(i8* blockaddress(@foo, %3), i8* blockaddress(@foo, %2)) #1
          to label %1 [i32 1, i32 2], !srcloc !3
```
(though https://reviews.llvm.org/D76961#1960529 mentions the opposite; rather than placeholders, only use `blockaddress`es).

Clearing the assignee for now.

**Comment by nikic** [comment]
Just as a quick note, the way to do this is to keep the target list as-is and remove the blockaddress arguments (or replace them with placeholders referencing the target list), not the other way around. Keeping only blockaddresses (while dropping the target list) is not compatible with blockaddress semantics -- the blocks would just get DCEd, because they are not reachable through control-flow.

**Comment by nickdesaulniers** [comment]
@nikic completed this work in
commit [2a721374aef3](https://github.com/llvm/llvm-project/commit/2a721374aef3) ("[IR] Don't use blockaddresses as callbr arguments")
clang-15
