### ISSUE TITLE
error: unsupported argument '-mno-warn-deprecated' to option 'Wa,'"

### ISSUE THREAD

**Issue by jcai19** [ClangBuiltLinux/linux#973]
While assembling arm32 kernel with the integrated assembler, I saw many instances of this error, e.g. init/version.o. Clang does not seem to provide a comparable warning for warn-deprecated provided by arm-linux-gnueabihf-as, therefore this option is not needed to suppress these warnings when building arm32 kernel with clang.

**Comment by nathanchance** [comment]
That warning should be going through as-option and getting rejected I thought?

https://github.com/torvalds/linux/blob/5364abc57993b3bf60c41923cb98a8f1a594e749/arch/arm/Makefile#L123

**Comment by nickdesaulniers** [comment]
I think this is a dupe of a bug that @agners sent a patch for.

**Comment by nickdesaulniers** [comment]
#956 #306

**Comment by jcai19** [comment]
> That warning should be going through as-option and getting rejected I thought?
> 
> https://github.com/torvalds/linux/blob/5364abc57993b3bf60c41923cb98a8f1a594e749/arch/arm/Makefile#L123

Yes, indeed. I made a wrapper of clang and used that to build linux. It seems something went wrong and as-option somehow included that option. Sorry for the confusion. Closing this issue.
