### ISSUE TITLE
invalid instruction mnemonic jmp.d32

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#974]
Working on a blog post related to `asm goto`, I stumbled on a patch set that's looking to use similar tricks to lower the overhead of spectre+meltdown mitigations by replacing indirect calls through global function pointers with direct calls.

https://lwn.net/ml/linux-kernel/20200324142245.819003994@infradead.org/ and friends, but it shows that the inline asm uses:

```c
void foo(void) { asm("jmp.d32 bar\n"); }
```

Clang's IA barfs on this, as the suffix isn't recognized.  It seems `d8` is another valid suffix?

This thread seems of interest: https://sourceware.org/legacy-ml/binutils/2019-07/msg00130.html

cc @jcai19 @MaskRay

**Comment by nickdesaulniers** [comment]
above thread was created after https://lore.kernel.org/r/20190628103224.888336008@infradead.org/ so I'll bet they're related.

**Comment by MaskRay** [comment]
None of the following gas features is supported by clang integrated assembler

- [Add .d32 encoding suffix.](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=f8a5c266971d7b5b96f973805551c6e88669cada) 2010-10
- [Add .d8 suffix support to x86 assembler](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=a501d77eeba717f6d54dce44f286f9e3aad83144) 2012-01
- [X86: Add pseudo prefixes to control encoding](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=86fa6981e7487e2c2df4337aa75ed2d93c32eaf2)

The patch can use this trick as a workaround:
```
% grep -A2 'jmp.d32' arch/x86/include/asm/jump_label.h
        /* Equivalent to "jmp.d32 \target" */
        .byte           0xe9
        .long           \target - .Lstatic_jump_after_\@
...
```

**Comment by MaskRay** [comment]
The integrated assembler supports '{disp32}' jmp/jcc now https://reviews.llvm.org/D84709

**Comment by nickdesaulniers** [comment]
cc @topperc for thoughts.

**Comment by topperc** [comment]
.d32 and .d8 should be supported now https://github.com/llvm/llvm-project/commit/09288bcbf5f124a2b0e24a6b1f2d27b66dba9adf

**Comment by nickdesaulniers** [comment]
lol, thanks @topperc ; ask and you shall receive!

@zmodem can we get that in clang-11?
