### ISSUE TITLE
Failed to assemble arch/arm/kernel/iwmmxt.S with clang's integrated assembler

### ISSUE THREAD

**Issue by jcai19** [ClangBuiltLinux/linux#975]
Building arch/arm/kernel/iwmmxt.S with clang's integrated assembler caused many instances of the following errors.

/usr/local/google/home/jiancai/storage/llvm-project/build/release/bin/clang -Wp,-MD,arch/arm/kernel/.iwmmxt.o.d  -nostdinc -isystem /media/storage/jiancai/llvm-project/build/release/lib/clang/11.0.0/include -I./arch/arm/include -I./arch/arm/include/generated  -I./include -I./arch/arm/include/uapi -I./arch/arm/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Qunused-arguments -D__ASSEMBLY__ -fno-PIE --target=arm-linux-gnueabihf --prefix=/usr/bin/ --gcc-toolchain=/usr -Werror=unknown-warning-option -mabi=aapcs-linux -mfpu=vfp -funwind-tables -meabi gnu -marm -Wa,-W -D__LINUX_ARM_ARCH__=7 -march=armv7-a -include asm/unified.h -msoft-float -Wa,-mcpu=iwmmxt    -c -o arch/arm/kernel/iwmmxt.o arch/arm/kernel/iwmmxt.S
arch/arm/kernel/iwmmxt.S:108:2: error: invalid instruction, did you mean: mrc, mrc2, mrrc?
 tmrc r2, wCon
 ^
arch/arm/kernel/iwmmxt.S:116:2: error: invalid instruction, did you mean: str?
 wstrw wCSSF, [r1, #(0x80)]
 ^

arch/arm/kernel/iwmmxt.S:127:2: error: invalid instruction, did you mean: str, strd?
 wstrd wR0, [r1, #(0x00)]
 ^

arch/arm/kernel/iwmmxt.S:150:2: error: invalid instruction, did you mean: ldr, ldrd?
 wldrd wR0, [r0, #(0x00)]
 ^

arch/arm/kernel/iwmmxt.S:168:2: error: invalid instruction, did you mean: ldr?
 wldrw wCSSF, [r0, #(0x80)]
 ^

**Comment by agners** [comment]
Looks like, yes:
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0489c/BABFFFIA.html

Not very familiar with XScale stuff, but adding a assembler directive like `.cpu iwmmxt` might help.

**Comment by jcai19** [comment]
Thanks for the suggestion! Unfortunately the integrated assembler still failed to assemble with the directive.  I think LLVM does not support xscale instructions at all. I searched for tmrc or the [special registers](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0473m/dom1361289999475.html) for [Marvell Wireless MMX Technology](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0473m/dom1361289999475.html) in LLVM code base but found nothing. I think the arm backend does not have such support at all, and we will have to add support of all such xscale-specific instructions to LLVM.

$ cat bad.s 
.cpu iwmmxt
tmrc r2, wCon

$ clang --target=thumbv5-linux-gnueabi -mcpu=xscale -c bad.s -o bad.o
bad.s:2:1: error: invalid instruction, did you mean: mrc, mrc2, mrrc?
tmrc r2, wCon

**Comment by jcai19** [comment]
cc @smithp35 @m-gupta

**Comment by agners** [comment]
This is support for rather old systems, and probably not much in use these days. We probably should just make sure that those type of systems cannot be selected when using Clang via Kconfig.

**Comment by smithp35** [comment]
From what I can tell the most recent processor that supported WMMX2 was the Marvell PJ4 (Arm V7-A) but I don't think that there is any support for it. The closest I could find was D24521 which was never merged.

I can't find any support for any of the WMMX instructions. I think @agners is right to say don't enable clang when building for this or any of the older Marvell/Intel XScale.

**Comment by jcai19** [comment]
> I think @agners is right to say don't enable clang when building for this or any of the older Marvell/Intel XScale.

Thanks @agners and @smithp35 for the update. An obvious way that I can think of to achieve this is to pass --no-integrated-assembler when building this file with clang, but I am not sure if that is the best practice. @nickdesaulniers mentioned we could achieve this via configs. I am new to Linux kernel so not completely sure on how to do that yet. Are there any example files I can refer to?

**Comment by ihalip** [comment]
If you want to remove that file from the build, look at arch/arm/Kconfig:
```
config IWMMXT
	bool "Enable iWMMXt support"
	depends on CPU_XSCALE || CPU_XSC3 || CPU_MOHAWK || CPU_PJ4 || CPU_PJ4B
	default y if PXA27x || PXA3xx || ARCH_MMP || CPU_PJ4 || CPU_PJ4B
```
The wording is pretty self-explanatory: "config IWMMXT is enabled by default if any of ... is enabled". You could make it depend on e.g. `!CC_IS_CLANG`. The file is added to the build in arch/arm/kernel/Makefile.

Alternatively, you can set specific flags for that file alone. In the same Makefile, you could add something like this (probably wrong syntax but you get the idea):
```
ifeq ($(CONFIG_CC_IS_CLANG),y)
AFLAGS_iwmmxt.o	+= -no-integrated-as
endif
```

**Comment by nickdesaulniers** [comment]
>  In the same Makefile

This should be done via Kconfig.  Just as we have CC_IS_CLANG, we should have LD_IS_LLD (@samitolvanen I think has a patch for this) and AS_IS_CLANG.  Then you can `depends on !AS_IS_CLANG` or `depends on !LD_IS_LLD` for a given config we're choosing not to support.

ARM has a lot of baggage over the years, and as discussed with @kbeyls , some old things just need to die.  Implementing support for them in LLVM is a non-priority.

For the compiler:
OABI vs EABI (we disable OABI when CC_IS_CLANG, no plans to support)
BE vs LE (LLD doesn't support BE #380, we should make LD_IS_LLD, then disable this)
XSCALE (LLVM_IAS doesn't support (this bug), we should make AS_IS_CLANG, then disable this)

Otherwise CI bots will continue to dig up these wacky configs via `randconfig` build.  Kconfig is the place to mark something broken, such that it cannot even be selected.

cc @masahir0y

**Comment by samitolvanen** [comment]
> This should be done via Kconfig. Just as we have CC_IS_CLANG, we should have LD_IS_LLD (@samitolvanen I think has a patch for this)

Yes, we need the patch for LTO, and it's trivial: https://github.com/samitolvanen/linux/commit/fe9786cb52a0100273c75117dcea8b8e07006fde

**Comment by jcai19** [comment]
Thanks all for the feedback. Will work on a patch.

**Comment by jcai19** [comment]
Patch sent: https://groups.google.com/g/clang-built-linux/c/Rs0864OO6Og/m/b8_XRXl0AAAJ

**Comment by nickdesaulniers** [comment]
We should probably look to implement support for these instructions.

**Comment by jcai19** [comment]
> We should probably look to implement support for these instructions.

Will start to work on that.

**Comment by nickdesaulniers** [comment]
https://lore.kernel.org/lkml/20201107001056.225807-1-jiancai@google.com/

**Comment by nickdesaulniers** [comment]
https://www.armlinux.org.uk/developer/patches/viewpatch.php?id=9029/1

**Comment by jcai19** [comment]
Applied to linux-next: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/arch/arm/kernel/iwmmxt.S?h=next-20201208&id=3c9f5708b7aed6a963e2aefccbd1854802de163e

**Comment by jcai19** [comment]
Applied to mainline https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/arch/arm/kernel/iwmmxt.S?h=v5.11-rc3&id=3c9f5708b7aed6a963e2aefccbd1854802de163e
