### ISSUE TITLE
objtool: unsupported stack pointer realignment

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#977]
0day bot reported:
```
>> drivers/pinctrl/pinctrl-ingenic.o: warning: objtool: ingenic_pinconf_group_get()+0x12: unsupported stack pointer realignment
>> drivers/pinctrl/pinctrl-ingenic.o: warning: objtool: ingenic_pinconf_group_get()+0x0: stack state mismatch: cfa1=7+136 cfa2=7+8
```
via: https://groups.google.com/g/clang-built-linux/c/bSNh_MA6MFU
this was on 4.19.y stable with a randconfig.

**Comment by nathanchance** [comment]
This is reproducible with ToT LLVM @ https://github.com/llvm/llvm-project/commit/1c10201d9660c1d6f43a7226ca7381bfa255105d with the config in the 0day report on latest 4.19. It is not reproducible on mainline. Looks like https://git.kernel.org/linus/d6d43a92172085a2681e06a0d06aac53c7bcdd12 fixed this. Is it worth requesting a stable backport for it?

**Comment by nickdesaulniers** [comment]
backport requested in https://lore.kernel.org/stable/CAKwvOd=iaL8_e4gxBPAzZbgCHtMy=gLi1YT9ja5Q_9+dE-L==w@mail.gmail.com/T/#u. Thanks @nathanchance for identifying the fix.

**Comment by nickdesaulniers** [comment]
Sasha picked this up as 57ef65b34fc5ac05095f4facf746d78cce49bbb0 for v4.19.191.
