### ISSUE TITLE
power_supply_hwmon_read_string() falls through to next function power_supply_hwmon_write()

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#978]
0day bot randconfig reports:
```
> >> drivers/power/supply/power_supply_hwmon.o: warning: objtool: power_supply_hwmon_read_string() falls through to next function power_supply_hwmon_write()
```
via: https://groups.google.com/g/clang-built-linux/c/yMjh9g41HiE
randconfig

**Comment by nickdesaulniers** [comment]
I tried to reproduce with:
```
// clang -O2
char* x[] = {
    "x"
};
char* y[] = {
    "y"
};

void foo(int bar, char** baz, int channel) {
    switch (bar) {
        case 2:
        case 0:
            *baz = y[channel];
            break;
        case 1:
            *baz = x[channel];
            break;
        default:
            __builtin_unreachable();
    }
    return;
}
```
but could not.  Maybe related to flags from configs enabled by the randconfig, or my reproducer is bad and needs to be creduced from the souce.

**Comment by ihalip** [comment]
I reproduced the issue with that commit. Some relevant disassembly:
```
0000000000000460 <power_supply_hwmon_read_string>:
 460:   83 fe 01                cmp    $0x1,%esi
 463:   75 11                   jne    476 <power_supply_hwmon_read_string+0x16>
 465:   48 63 c1                movslq %ecx,%rax
 468:   48 8b 04 c5 00 00 00    mov    0x0(,%rax,8),%rax
 46f:   00 
 470:   49 89 00                mov    %rax,(%r8)
 473:   31 c0                   xor    %eax,%eax
 475:   c3                      retq   
 476:   66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)
 47d:   00 00 00 

0000000000000480 <power_supply_hwmon_write>:
 480:   48 83 ec 10             sub    $0x10,%rsp
```

It does look like objtool is right: from the generated assembly, `jne` (offset 0x463) could branch to `nopw` (0x476) and then execution continues to the next function. GCC generates the same code, so the same warning happens. From the GCC docs:

> If control flow reaches the point of the __builtin_unreachable, the program is undefined. It is useful in situations where the compiler cannot deduce the unreachability of the code.

This behavior is probably fine from the compiler's perspective, since the `__builtin_unreachable()` hint says this branch is never executed. Removing the `unreachable()` call is probably the best option. Without it, I get:
```
0000000000000460 <power_supply_hwmon_read_string>:
 460:   83 fe 01                cmp    $0x1,%esi
 463:   75 0e                   jne    473 <power_supply_hwmon_read_string+0x13>
 465:   48 63 c1                movslq %ecx,%rax
 468:   48 8b 04 c5 00 00 00    mov    0x0(,%rax,8),%rax
 46f:   00 
 470:   49 89 00                mov    %rax,(%r8)
 473:   31 c0                   xor    %eax,%eax
 475:   c3                      retq   
 476:   66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)
 47d:   00 00 00 
```

Much better.

**Comment by osctobe** [comment]
> I reproduced the issue with that commit. Some relevant disassembly:
> 
> ```
> 0000000000000460 <power_supply_hwmon_read_string>:
>  460:   83 fe 01                cmp    $0x1,%esi
>  463:   75 11                   jne    476 <power_supply_hwmon_read_string+0x16>
>  465:   48 63 c1                movslq %ecx,%rax
>  468:   48 8b 04 c5 00 00 00    mov    0x0(,%rax,8),%rax
>  46f:   00 
>  470:   49 89 00                mov    %rax,(%r8)
>  473:   31 c0                   xor    %eax,%eax
>  475:   c3                      retq   
>  476:   66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)
>  47d:   00 00 00 
> 
> 0000000000000480 <power_supply_hwmon_write>:
>  480:   48 83 ec 10             sub    $0x10,%rsp
> ```
[...]

Why would the compiler remove unreachable code, but not the branch to it?

**Comment by osctobe** [comment]
Can you share the compiler version you used? I can only reproduce this using gcc-8. gcc-7, gcc-9 and all recent clangs are ok, according to my quick Godbolt test.

**Comment by ihalip** [comment]
```
$ gcc -v
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
$ clang-11 -v
clang version 11.0.0-++20200403092301+69c8fb1c65f-1~exp1~20200403072856.1600
```

> Why would the compiler remove unreachable code, but not the branch to it?

GCC activates `-falign-functions` at [-O2](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#Optimize-Options). I think clang is doing the same.

**Comment by osctobe** [comment]
Symptoms look like https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51513

-falign-functions doesn't seem to influence my simplified testcase (-O is enough for gcc-8 to leave falling-off branch).

**Comment by nickdesaulniers** [comment]
> Why would the compiler remove unreachable code, but not the branch to it?

That's a fair point.

**Comment by gwelymernans** [comment]
> > Why would the compiler remove unreachable code, but not the branch to it?
> 
> That's a fair point.

It would be to retain the behavior of the original code in the face of an error. For instance, in the switch statement, a jump to `default` is supposed to be invalid (the unreachable builtin), but it could still potentially happen in an error situation.

**Comment by nickdesaulniers** [comment]
```sh
$ curl -L https://groups.google.com/group/clang-built-linux/attach/88cbec37f442d/.config.gz\?part\=0.1 | gunzip -d > .config
$ make LLVM=1 LLVM_IAS=1 -j72 olddefconfig
$ make LLVM=1 LLVM_IAS=1 -j72 drivers/power/supply/power_supply_hwmon.o
```
seems no longer reproducible with llvm @ bdd68357901d2ccdd110cf35746703ac8e46de3c and linux @ e359bce39d9085ab24eaa0bb0778bb5f6894144a.
